### ISSUE TITLE
Link to get the latest version

### ISSUE THREAD

**Issue by guest20** [highlightjs/highlight.js#1109]
Hi there,

  I just downloaded a custom version of hilight with a couple of languages from "below the line", and I wonder if it would be possible for `hilight.pack.js` to contain a link like

```
https://highlightjs.org/download/?scripts=apache,bash,cs,cpp,css,coffeescript,dts,diff,xml,http,ini,json,java,javascript,makefile,markdown,nginx,objectivec,php,perl,python,ruby,sql,1c,brainfuck,cmake,dns,dos,erlang,go,groovy,haskell,lisp,powershell,protobuf,puppet,vim,yaml
```

This way I can easily snag a new version when it becomes availble

As a bonus, it could include the current version (at the time of download), which could be tracked to see how long folks wait between upgrades...

**Comment by isagalaev** [comment]
As of lately, the site actually remembers the state of the check boxes since your last visit. Does it solve the problem for you?

As for upgrade tracking, it would probably be pretty useless as downloading from the site is not the most common way of getting highlight.js.

**Comment by guest20** [comment]
I'm not going to have the same browser in 6 months time. Realistically I was hoping to just grab the new version with wget or curl.

(i vendor the downloaded version in my git  repo for my app)

**Comment by isagalaev** [comment]
Fair enough. I think I can include a file named "source.url" into the zip.

**Comment by guest20** [comment]
That would be amazing, thanks.

**Comment by yyyc514** [comment]
@isagalaev Is there some plan to make the website/utils OSS and available to contributors or should we just consider this stuff impossible without your involvement? Or are they already and I just don't know where?

Or has this perhaps already been completed long ago?

**Comment by isagalaev** [comment]
The only reason it's still on me is that nobody wanted to take it over when I was looking for volunteers :-) I can happily publish the source code for the site here on GitHub (it's a Django application), but the key problem is deployment: it is now being published by me ssh'ing on my server and running a couple of commands. This never required any automation.

Now, to pry it out of my hands we need to come up with some sort of deployment procedure. I don't fancy installing anything too complicated on the server, so *ideally* we could solicit some money from the community and publish it somewhere in the cloud. This probably already sounds too complicated, so may be I'm overthinking it?

**Comment by isagalaev** [comment]
Back to the original issue though, I don't think any of it is worth the effort. Sure, there is some value in providing the URL in the archive, but it's very marginal.

**Comment by yyyc514** [comment]
The question wasn’t about only this issue.  If there are no secrets in the codebase I’d say publishing it would be a good start?  Then we could at least see what we are working with and go from there. Or fix documentation style stuff and perhaps you could manually update it a while longer.

**Comment by isagalaev** [comment]
I'll put it on my list :-) I do need to extract a secret into local settings and move it all from bzr to git.

I'm actually fine maintaining it as long as it doesn't take too much time. And it tends not to :-)

**Comment by yyyc514** [comment]
@guest20 Closing this for now.  I don't think @isagalaev has any time for it and it's not really something anyone else can do until the website stuff is open-sourced.  Also seems to be of marginal value (considering everything else we could be working on).  _Once the website is OSS if someone wanted to contribute a PR to do this I think that'd be fine, but I don't see the core team spending time on this right now._

Alternative suggestion:

Clone the git repo and just use the build tool... you can write a tiny script to call the build tool and pass it your list of languages... then to refresh you simply checkout whatever version you want, rebuild, and finished.

It does require node locally of course, but after that it's pretty trivial.
