### ISSUE TITLE
Add YAML

### ISSUE THREAD

**Issue by gka** [highlightjs/highlight.js#119]
YAML syntax highlighting would be really nice.

Awesome lib, btw! Thanks so much.

**Comment by wwi-johnbuhay** [comment]
isagalev,

Here is some info, let me know if I can do anything else to help. Thank you

http://docs.ansible.com/YAMLSyntax.html
https://github.com/clifford-github/sublime-ansible

**Comment by isagalaev** [comment]
@wwi-johnbuhay new languages in highlight.js don't happen this way, here's how: http://highlightjs.readthedocs.org/en/latest/language-requests.html

**Comment by lukeroge** [comment]
This issue server as at least an expression of interest in case a
contributor wants to submit a language.
