### ISSUE TITLE
Add prefix (lang-) for sublanguages

### ISSUE THREAD

**Issue by unreal666** [highlightjs/highlight.js#1209]
Without prefix, class names can to conflict with class names unrelated with highlighting.

**Comment by yyyc514** [comment]
Didn't we use to have `lang-` a long time ago? Does anyone know the history on this?

**Comment by egor-rogov** [comment]
highlight.js:
```js
41       languagePrefixRe = /\blang(?:uage)?-([\w-]+)\b/i,
```
i. e. we support both `lang-` and `language-` prefixes, and I believe we can close this issue.

**Comment by yyyc514** [comment]
Thank you!  I did not know we already supported this.

**Comment by yyyc514** [comment]
ANd it also takes priority if it’s specified... so “lang-javascript sql” would be rendered as Javascript.
