### ISSUE TITLE
Include UMD builds in npm package for unpkg support

### ISSUE THREAD

**Issue by jayphelps** [highlightjs/highlight.js#1250]
http://npmcdn.com/ is all the rage. It's handy to not have to rummage through a project's website to find the CDN links and instead we can do things like https://npmcdn.com/react/dist/react.min.js and it'll resolve to the latest.

![image](https://cloud.githubusercontent.com/assets/762949/16897132/09dc4184-4b5d-11e6-80f0-39a21da1f32c.png)

**Comment by isagalaev** [comment]
Could you explain how highlight.js could benefit from it? Our CDN build has little to do with npm.

**Comment by jayphelps** [comment]
It's the users of highlight.js who benefit from it. If you published the builds in the npm package, people can consume them with http://npmcdn.com without needing to dig through your documentation website to find the CDN links, and also to remain consistent with their preferred CDN. _http://npmcdn.com is a CDN_.

**Comment by jayphelps** [comment]
Also--because npmcdn supports npm as a first-class, you can, but don't have to, provide a semver range. If you exclude it, it will resolve to the latest published build. The existing CDNs provided do not support this AFAIK.

**Comment by isagalaev** [comment]
Our problem is that the build we publish on npm is huge, it's not suitable for browser consumption even after compression. The build we publish on CDN is a limited, custom-compressed variant, and it's still bigger than we'd like. That's why we have to even bother with all the multi-build machinery we've got in place instead of simply publishing to npm and have third-parties deal with everything else.

**Comment by jayphelps** [comment]
Sorry for the confusion. I'm suggesting that the same build you publish to existing CDNs just be included in the npm published package. No custom tooling is required--just include the already-being-built file.

**Comment by isagalaev** [comment]
Ah… That might actually make sense, I don't see any immediate disadvantages to this approach. But let me think some more about it.

@sourrust, @Sannis what do you think about it?

**Comment by yyyc514** [comment]
Ok, this is now https://unpkg.com.

I immediately get this.  This would be helpful I think.  I dunno about bundling the WHOLE CDN build (and all the language files),  but we could for sure start by bundling a minified (production) and development (non-minified) distributables.

@jayphelps Is there a convention on path?  I see react use to use `dist`, but now it's `umd` and `cjs`.  Since we're kind of "works with whatever" right now I wonder if we'd want to stick with `dist`?

**Comment by jayphelps** [comment]
@yyyc514 There indeed is not a solid convention everyone uses. As long as it's documented, it doesn't matter too much IMO. Though organizing them in directories helps natural discoverability if someone is peeking into the node_modules.

I'm not in a position that needs right anymore btw. (old ticket)

**Comment by yyyc514** [comment]
> I'm not in a position that needs right anymore btw. (old ticket)

Yes, it is, but better late than never they say...

Would you expect the WHOLE CDN worth of 184 files to be there, or just the default :common distributable?

**Comment by jayphelps** [comment]
Generally speaking I'd expect the same thing you provide for the existing CDN ability, which I think is that all the languages are available as separate addon files.

**Comment by yyyc514** [comment]
Does no one care about the size of npm packages these days? :)

**Comment by jayphelps** [comment]
@yyyc514 Most don't unless its universally considered "large" e.g. 1 GB would universally be a no-no. Still, many folks do care about every byte in their node_modules e.g. electron users most come to mind, but of course everyone complains about node_modules in general being large because death by a thousand cuts.

The maintainers (if you are one, you included) just make the call whether it's worth it or not. I don't know off hand how much extra size that would be.

**Comment by yyyc514** [comment]
Unminified close to 1mb just for JS.

**Comment by jayphelps** [comment]
@yyyc514 It's not tiny, but it seems like an acceptable compromise to me, but YMMV. It's not uncommon to have several megabytes of optional/dev-only/bundles/etc and in most cases it's worth it. Since I don't need this right now, I don't want to fight too hard for something I won't use, though. 😉

In case others are reading this: we're not talking about adding this to what everyone ships with their app, we're only talking about the size of the installed npm package itself, on your local disk

**Comment by yyyc514** [comment]
I think we could start by including only common (which has recently grown) and then see how people react to that... if they are appeased or clamor for more.  Probably won't happen until .12 when we rejiggle the whole build system though.

**Comment by jayphelps** [comment]
@yyyc514 sounds reasonable!

**Comment by yyyc514** [comment]
This is considered resolved by: 

https://www.npmjs.com/package/@highlightjs/cdn-assets

If you really want your assets from NPM (whether via npm/yarn) or `unpkg`, cdn-assets is how you should get them.
