### ISSUE TITLE
Add docs: Using only a subset of languages with Node/npm

### ISSUE THREAD

**Issue by vladshcherbin** [highlightjs/highlight.js#1257]
If you install the package from `npm`, the built file has all languages.

How is it possible to use only some languages?

**Comment by Snead** [comment]
Fork

**Comment by isagalaev** [comment]
Sure. You can pass `languageSubset` as a parameter for `highlightAuto()`: http://highlightjs.readthedocs.io/en/latest/api.html#highlightauto-value-languagesubset

**Comment by Remo** [comment]
@isagalaev but that will not exclude the files from the packed JavaScript file or am I missing something? 

in index.js we have a ton of calls to `require`:

```
var hljs = require('./highlight');

hljs.registerLanguage('1c', require('./languages/1c'));
hljs.registerLanguage('abnf', require('./languages/abnf'));
...
```

As far as I understand we can just avoid `index.js` and include `highlight.js` directly and then call `registerLanguage` for the languages we actually need?

**Comment by Remo** [comment]
Here's my complete example which is working for me

```javascript
var hljs = require("highlight.js/lib/highlight.js");
hljs.registerLanguage('xml', require('highlight.js/lib/languages/xml'));
hljs.registerLanguage('sql', require('highlight.js/lib/languages/sql'));
```

**Comment by danoc** [comment]
Thanks, @remo. This was incredibly helpful. Would love to see it documented on the website or README.

**Comment by yyyc514** [comment]
This is in the README now.

**Comment by fhsinchy** [comment]
> Here's my complete example which is working for me
> 
> ```js
> var hljs = require("highlight.js/lib/highlight.js");
> hljs.registerLanguage('xml', require('highlight.js/lib/languages/xml'));
> hljs.registerLanguage('sql', require('highlight.js/lib/languages/sql'));
> ```

for some reason importing 'highlight.js' didn't work for me, I had to import 'core.js' instead.

```javascript
import hljs from 'highlight.js/lib/core'
import json from 'highlight.js/lib/languages/json'
import shell from 'highlight.js/lib/languages/shell'
import javascript from 'highlight.js/lib/languages/javascript'

hljs.registerLanguage('javascript', javascript)
hljs.registerLanguage('shell', shell)
hljs.registerLanguage('json', json)
```
