### ISSUE TITLE
Exponential Processing Time

### ISSUE THREAD

**Issue by dnl-blkv** [highlightjs/highlight.js#1313]
Strings of format (\/a)<sup>n</sup> require exponential time to be highlighted.

Some clients using HLJS, such as RocketChat, freeze attempting to process strings potentially taking millions of years to process, due to this.

Example:

``` HTML
<pre>
<code>
\/a\/a\/a\/a\/a\/a\/a\/a\/a\/a\/a\/a\/a\/a\/a\/a\/a\/a\/a\/a\/a\/a\/a\/a\/a\/a
</code>
</pre>
```

``` JS
hljs.initHighlightingOnLoad();
```

**Comment by yyyc514** [comment]
Is this still an issue?  Any details on which grammar is actually at fault here would be helpful.  Or a PR with a test to reproduce the issue.

**Comment by yyyc514** [comment]
Ping.

**Comment by yyyc514** [comment]
If any beginning would like to see if this is still a reproducible issue in 2019 that'd be greatly appreciated.

**Comment by yyyc514** [comment]
@dnl-blkv https://jsfiddle.net/ajoshguy/fp82xa7k/

I can't reproduce this.  If this is still an issue please provide an updated jsfiddle that reproduces the issue and we'll be happy to look into it!
