### ISSUE TITLE
(java) parameter annotations that take parameters

### ISSUE THREAD

**Issue by wyattallen** [highlightjs/highlight.js#1324]
Java parameter annotations that take parameters prematurely end the parameter list as delimited by the `span[class="hljs-params"]`.

As a simple example, consider the following code:

```
public class Example {
  public static void foo(@SuppressWarnings("unused") int bar) { }
}
```

In this case, when highlighted by HLJS, the `hljs-params` span ends before `int bar` -- apparently misinterpreting the close-parenthesis in the `@SuppressWarnings` annotation as the end of the function parameters.

**Comment by Miha-x64** [comment]
Also, parameter annotations should be `hljs-metadata`, but their highlighting is just getting skipped.

**Comment by yyyc514** [comment]
Can someone confirm this is still and issue and if so a jsfiddle would be great.

You can use my template:
https://jsfiddle.net/ajoshguy/nagkqytv/18/

**Comment by wyattallen** [comment]
Still reproducible: https://jsfiddle.net/fowcuL8q/
The hljs-params span stops at the end of the annotation instead of the end of the parameter list (probably it's misinterpreting the close-paren of the annotation as the end of the parameter list).

**Comment by yyyc514** [comment]
Yeah.  Any chance you want to work on a PR? ;-)
