### ISSUE TITLE
SASS

### ISSUE THREAD

**Issue by jrean** [highlightjs/highlight.js#1335]
Hi,

Is that possible you provide alongside with the `.css` files a `default.scss` sass file?
It would be awesome!

Thank you for the amazing work

**Comment by ralphbolliger** [comment]
+1

**Comment by Grawl** [comment]
I really want it too

**Comment by Grawl** [comment]
what about .sass?

**Comment by marcoscaceres** [comment]
I don’t know .sass, is it just css too?

**Comment by Grawl** [comment]
[Sass](https://sass-lang.com) has two syntaxes: `.scss`, CSS-like one, and `.sass` — indented syntax, looking like this:

```sass
nav
  ul
    margin: 0
    padding: 0
    list-style: none

  li
    display: inline-block

  a
    display: block
    padding: 6px 12px
    text-decoration: none
```

**Comment by marcoscaceres** [comment]
Is there a tool that can convert css to sass? Right now, the scss files are just css files with a different file extension.

**Comment by marcoscaceres** [comment]
Ah, ok. So I don’t think we can provide sass unfortunately.

**Comment by yyyc514** [comment]
Out of curiosity:

> Is that possible you provide alongside with the .css files a default.scss sass file?

WHY? I think understanding the context of a request is always super important.
