### ISSUE TITLE
Using with Vue.js

### ISSUE THREAD

**Issue by subdesign** [highlightjs/highlight.js#1339]
Any idea how to use hljs with Vue.js and vue-router? The problem in my opinion is, when changing urls that loads the page parts and after that hljs isn't reinitialize itself. 
I would be happy to know a solution for Vue 1.x and 2.x

**Comment by chrisvfritz** [comment]
I think this is more a question for [the Vue forum](http://forum.vuejs.org/). If you post your code there, the community will be able to point out what's going wrong.

**Comment by yyyc514** [comment]
>  The problem in my opinion is, when changing urls that loads the page parts and after that hljs isn't reinitialize itself.

Yes, whenever you rendered new content on the page that might have new code blocks that needs to be colorized you'd need to ask Highlight.js to do that for you.  There is likely a callback or something in Vue to make this easier.  If you get help on the Vue form and find the answer and want to post it back here to help others that would be great.

Note, Highlight.js currently really isn't exactly perfect for use in that environment if you're just trying to call `initHighlighting` or `initHighlightingOnLoad`. Those are only intended to be called once.  You'll likely have to dig down into the source and edit `highlightBlock` by hand to make sure it colors blocks once and only once.  Then write your own `initHighlightingRefresh()` that is something like:

```
  function initHighlightingRefresh() {
    var blocks = document.querySelectorAll('pre code');
    ArrayProto.forEach.call(blocks, highlightBlock);
  }
```

Then you'd trigger that from Vue - whenever the page changed and might need to be re-colorized.

**Comment by yyyc514** [comment]
Closing as asked and answered (we're trying to clear out old issues).  **If you have additional questions feel free to ask though.**

Also there might be room for a PR regarding the "only highlight a block a single time" if it was clean.   Question is only if it'd be an object property or attribute or how we'd store the state. I certainly wouldn't object to such a thing as it would make dripping Highlight.js into SPA apps a lot easier.
