### ISSUE TITLE
Left-shift in C-Preprocessor directive consumes additional lines

### ISSUE THREAD

**Issue by wyattallen** [highlightjs/highlight.js#1341]
# Background

When a left-shift (`<<`) appears inside the value of a CPP `#define`, HLJS includes many of the subsequent lines into a `hljs-meta-string` span.

For example, consider the following C program.

    #include<stdio.h>
    #define SIZE (1ull << 30)
    void main() {
        printf("Hello World");
    }

# Actual result

Observe the following output DOM, and how the entire `main` function is erroneously included in the `hljs-meta-string`.

    <code class="c hljs cpp">
      <span class="hljs-meta">#
        <span class="hljs-meta-keyword">include</span>
        <span class="hljs-meta-string">&lt;stdio.h&gt;</span>
      </span>
      <span class="hljs-meta">#
        <span class="hljs-meta-keyword">define</span>
        SIZE (1ull
        <span class="hljs-meta-string">&lt;&lt; 30)
          void main() {
              printf("Hello World");
          }
        </span>
      </span>
    </code>

# Expected result

In expectation, the `hljs-meta` encloses only the `#define SIZE (1ull << 30)` line and the `main` function is highlighted normally.

    <code class="c hljs cpp">
      <span class="hljs-meta">#
        <span class="hljs-meta-keyword">include</span>
        <span class="hljs-meta-string">&lt;stdio.h&gt;</span>
      </span>
      <span class="hljs-meta">#
        <span class="hljs-meta-keyword">define</span>
        SIZE (1ull &lt;&lt 32)
      </span>
      <span class="hljs-function">
        <span class="hljs-keyword">void</span>
        <span class="hljs-title">main</span>
        <span class="hljs-params">()</span>
      </span>{
      <span class="hljs-built_in">printf</span>
      (<span class="hljs-string">"Hello World"</span>);
      }
    </code>

**Comment by yyyc514** [comment]
Can you confirm this is still an issue?  A jsfiddle would be great.

You can borrow my template:
https://jsfiddle.net/ajoshguy/nagkqytv/18/

**Comment by wyattallen** [comment]
I cannot repro: https://jsfiddle.net/h4af8ct1/1/
