### ISSUE TITLE
Highlighting on the fly

### ISSUE THREAD

**Issue by huuson235** [highlightjs/highlight.js#1356]
I'm working with react, I want to create a simple text editor. However highlight.js doesn't highlight after real-time updating content. Any suggesstion?

**Comment by Tuning-Soft** [comment]
+1 
Yes, the same problem as before editing the text to turn off the backlight, and then edit the play?

**Comment by Tuning-Soft** [comment]
Need some this
``var message_edit = function () {

  $('pre code').each(function(i, block) {
    hljs.unhighlightBlock(block);
  });

}
var message_save = function () {

  $('pre code').each(function(i, block) {
    hljs.highlightBlock(block);
  });

}

**Comment by yyyc514** [comment]
Highlight.js really isn't intended to be used as a live code editor.  You might not have great luck with this.  You'll need to:

- save the custom position
- rip out the raw content each time
- remove HTML
- ask Highlight.js to rehighlight
- replace the content with the newly highlighted content
- (you could try to do this smartly with some kind of shadow-dom/html-diff thingy)
- put the cursor back in the right spot

And either it'll work like magic or work pretty terribly. :-)  The unhighlighting is the least of your concerns I think.  There is a newer issue where someone is trying the same thing:

https://github.com/highlightjs/highlight.js/issues/1677

**Comment by yyyc514** [comment]
You'd have better luck if you were building an editor + say preview system... and as they typed you just had a thread that updated the content every 200ms or so... like a Markdown editor/preview, etc... then you only have to deal with updating the content not the whole cursor issue, etc.

**Comment by marcoscaceres** [comment]
Agree. This is unfortunately outside the scope of this library.
