### ISSUE TITLE
(cpp) bug when two more vars construct with param

### ISSUE THREAD

**Issue by LFsWang** [highlightjs/highlight.js#1363]
test : https://runkit.com/lfswang/20161123-hljs-cpp-bug

fine example 
```cpp
vector<int> a(c,c),b(d,d);
aaa b(c,d);
```
broken code example (and github highlight also rendered failed)
```cpp
//using ABC = vector<int>;
ABC a(c,c),b(d,d);
```

![image](https://cloud.githubusercontent.com/assets/7088579/20567952/a7f32e08-b1d5-11e6-9da1-1fea16af827f.png)

**Comment by yyyc514** [comment]
Can you confirm this is still an issue and if possible make a JSFiddle reproducing it?

Simple template you can fork:
https://jsfiddle.net/ajoshguy/nagkqytv/11/

**Comment by yyyc514** [comment]
Ping.

**Comment by LFsWang** [comment]
I think it is already fixed. Thanks.

**Comment by yyyc514** [comment]
Thanks!
