### ISSUE TITLE
Ruby's highlighting doesn't work on nested brackets in some cases

### ISSUE THREAD

**Issue by hachi8833** [highlightjs/highlight.js#1367]
Version: v9.8.0

I found that highlighting for Ruby is not working within nested brackets in some cases. 

I'm afraid similar issues might occur as well on other nested braces/parentheses etc.

## not nested

* ![image](https://cloud.githubusercontent.com/assets/4289625/20699519/14fb9c0a-b64b-11e6-87f1-c0d28e3cd71c.png)

* ![image](https://cloud.githubusercontent.com/assets/4289625/20699528/2472555c-b64b-11e6-939c-7a73aff4f265.png)

## nested

* 
![image](https://cloud.githubusercontent.com/assets/4289625/20699562/4991f018-b64b-11e6-8e24-1ca2c05bffaf.png)

* 
![image](https://cloud.githubusercontent.com/assets/4289625/20699573/586a1d40-b64b-11e6-85ce-01093933da66.png)

Thank you,

**Comment by yyyc514** [comment]
Can you confirm this is still an issue?  A jsfiddle reproducing would be great.

You can fork my template:
https://jsfiddle.net/ajoshguy/nagkqytv/18/

**Comment by yyyc514** [comment]
Awesome. :-)
