### ISSUE TITLE
Regex problem

### ISSUE THREAD

**Issue by JBR69** [highlightjs/highlight.js#1376]
Hi,

I'm beginner with highlight.js and I have a problem to specify my regex.
My text is 
```
Country Name (2 letter code) [FR]:
```
and I want to colorize the text between [ and ].
So I write this regex
```
{
      cN:"strong",
      v:[
           ....
           {b:"\\[(.+)\\]:$"},                        
           ....
      ]
}
```
but "full match" is colored `[FR]:` !
How to specify only the group `FR` 

ty
Jérôme
PS: sorry for my poor english

**Comment by yyyc514** [comment]
You'd need a partner rule to match the [ and ] and then you'd need a child rule (in contains) to match the inner most content.

**Comment by yyyc514** [comment]
Closing because of age and lack of response.  If this is still an issue, please let us know.  Working on clearing out old issues.
