### ISSUE TITLE
Explicit styles overridden by detected styles

### ISSUE THREAD

**Issue by johnstray** [highlightjs/highlight.js#1379]
When manually using span tags on some elements, the class specified in the span tag is overridden and an extra span tag is added. Example:

```html
<pre><code class="php">
    <span class="hljs-type">array</span> ( 'arrayitem' );
</code></pre>
```
The above ends up looking like this:
```html
<pre><code class="php">
    <span class="hljs-type">
        <span class="hljs-keyword">array</span>
    </span>
    ( 'arrayitem' );
</code></pre>
```

**Comment by isagalaev** [comment]
And what would be the behavior you expect?

highlight.js preserves whatever custom markup there was before highlighting.

**Comment by yyyc514** [comment]
You can fix this just by adding CSS that targets your custom class and it's children.

But if you're trying to label things with Highlight.js's own classes then yes you're going to have issues.  This is just not really something that's supported.

You might have better luck using a custom syntax if you need to tag certain keywords differently.
