### ISSUE TITLE
Working on FireFox but not Chrome

### ISSUE THREAD

**Issue by ChrisWellsWood** [highlightjs/highlight.js#1400]
I'm having an annoying issue where the code highlighting is working perfectly on FireFox, but not on Chrome. I'm almost positive that it's something stupid that I'm doing, but I can't figure it out. You can checkout a page with this issue [here](https://chriswellswood.github.io/posts/code/rust/empty-rust-structs.html).

Here's the relevant HTML:

```Html
<!DOCTYPE HTML>
<html>

<head>
  <meta charset="UTF-8">
  <title>BaPaOaE • Empty Rust Structs</title>
  
  <link href="https://fonts.googleapis.com/css?family=Open+Sans|Droid+Serif" rel="stylesheet">
  <link rel="stylesheet" href="../../../css/style.css">

  <!-- Markdown Highlighting -->
  <link rel="stylesheet" href="../../../css/github.css">
  <script src="../../../js/highlight.pack.js"></script>
  <script>hljs.initHighlightingOnLoad();</script>
</head>

<body>
  <div id="main"></div>
  <script type="text/javascript" src="empty-rust-structs.js"></script>
  <script type="text/javascript">
      var node = document.getElementById('main');
      var app = Elm.EmptyRustStructs.embed(node);
  </script>
</body>

</html>
```

I'm I doing anything obviously wrong?

**Comment by Sannis** [comment]
@ChrisWellsWood I'm not so familiar with browsers, but it looks like Firefox and Chrome differently threat "onload" event. I'm also think that Elm is also do all his stuff after "onload" so you need to call `hljs.highlightBlock()` implicitly after Elm render this page.

**Comment by ChrisWellsWood** [comment]
I fixed this by using a `highlight.pack.js` [file](https://github.com/elm-lang/package.elm-lang.org/blob/e0b7aa4282038475612722ff7a57195866f8645b/assets/highlight/highlight.pack.js) that another Elm app used.

**Comment by mossarelli** [comment]
Be aware of double highlighting in already highlighted code tags when you invoke highlight methods.
It was not uncommon for my keywords to have two span tags with the same CSS class in the project I was working on.

**Comment by yyyc514** [comment]
Is this still an issue?

**Comment by yyyc514** [comment]
Closing due to age.  A more recent report says it works everywhere but Safari 12.  If this is still an issue, please ping here.
