### ISSUE TITLE
Add Python log file (logging) grammar

### ISSUE THREAD

**Issue by vsoch** [highlightjs/highlight.js#1402]
Your library is great! I'm looking to highlight a standard python error log (created with [logging](https://docs.python.org/2/library/logging.html)), meaning bringing certain lines to the user's attention with a different color. This would be a simple matter of formatting an entire line in one style based on the starting text. For example, here is a log:

https://singularity-hub.org/containers/46/

Right now it looks nice, but the important information (errors, then warnings) doesn't jump out. Ideally, the `INFO` lines would all be a lighter color, the `ERROR` would be the most noticable, etc. 

I can definitely do the coding for the custom theme, I am hoping you could point me in the right direction of a (close to what I am looking for) language template and /or docs to start? Thanks a bunch!

**Comment by shivavelingker** [comment]
Any update on this?

**Comment by vsoch** [comment]
The maintainer never responded to the issue, so there isn't any update from me :)

**Comment by egor-rogov** [comment]
Hi everybody,
the docs are here: https://highlightjs.readthedocs.io/en/latest/
To accomplish the task you'll have to define a new language first, and this is the hard part of it. You can scan through the existing language definitions to find something more or less similar, copy and modify it. Then make sure that all tests pass. Something like this.

**Comment by yyyc514** [comment]
@vsoch Good luck!  If you do build a theme, let us know so we can host it here at highlightjs organization or link people to it so they can find it. 

Or if you have any questions about the docs, feel free to ask!

---

Rather than leave these issues open to languish forever (as we have in the past) we're going to start closing them (to clean up the issues list).

I've also moved this request to the wish list (just incase you don't find the time to work on it yourself):
https://github.com/highlightjs/highlight.js/wiki/Grammar-Requests

**Comment by yyyc514** [comment]
Nope.

Well you could include your own "recommended" CSS file, but anyone just plugging your extension into the broader library is likely to be using one of the many available themes, not yours.  Plus without knowing what theme they are using (light or dark) individual colors would be kind of meaningless.  Color only exists in the context of the color around it.

Your CSS file could perhaps include CSS that takes control of the whole <code> block...

```
.hljs.pythonlog {

}
```

Though in that case I think you'd want to ship both light and dark themes so someone could pick what most fix with the rest of their site.  But at this point your syntax is going to be something very specific that someone chooses to use (and sets up properly including our CSS, etc)... not just something you could drop into a build with many other languages.

Perhaps a simple use case, but something that hasn't really come up before (AFAIK). :-)

Now there is an issue to allow configuring a theme per block, which could be helpful here, but no work has been made on that.

**Comment by vsoch** [comment]
Hmm, yeah including my own file sounds a bit hacky. 

What I could do is pick arbitrary colors (classes) and then minimally the user could select a theme to get variations. It wouldn't be very logical in terms of the color matching, but minimally it would serve to distinguish the levels.

**Comment by yyyc514** [comment]
There is some precedent for shipping separate themes... I've seen at least one of the language repositories do just that... 

But yeah for "general" use your options are limited - but might improve once you get themes per block... then one could imagine some languages having a "default" theme, though I'm not sure how great an idea that is.  Actually I think we'd probably do it the way I already suggested... let people ship CSS and then the packagers/users could decide how much CSS they want to include... if they want all the custom CSS or not...

Although still you have the light/dark problem, lol...

**Comment by yyyc514** [comment]
Well, currently it's just an idea:

https://github.com/highlightjs/highlight.js/issues/1802

**Comment by vsoch** [comment]
Thanks! That's exactly what I was looking for - I've subscribed to the issue.
