### ISSUE TITLE
JS: Expressions inside template literals don't display correctly

### ISSUE THREAD

**Issue by teameh** [highlightjs/highlight.js#1405]
```js
res = `start ${tags.map(tag => `pre ${tag} post`).join('\n    ')}end`;
```

Displays like:

![image](https://cloud.githubusercontent.com/assets/1330668/21728863/b60d1bda-d448-11e6-8e76-34451ca3a265.png)

`pre` and `tags.map` don't have the right color

Fiddle: https://jsfiddle.net/ug3tLcf6/

**Comment by yyyc514** [comment]
Not sure I see any issue.  What are you expecting?  Or perhaps this has been fixed.

![Screen Shot 2019-10-09 at 5 33 03 AM](https://user-images.githubusercontent.com/6473/66469697-4f4c5380-ea56-11e9-961b-9d91f6b7dba7.png)

https://jsfiddle.net/ajoshguy/ym41ukjd/

**Comment by teameh** [comment]
Partly fixed (`pre` is coloured now). Partly as expected (`tags.map` is indeed also not coloured outside the template literal, I expected it to be coloured). 

Closing this. 

Thanks for responding after 3y instead of closing it after x months due to inactivity 😊!

**Comment by yyyc514** [comment]
Glad to help!
