### ISSUE TITLE
Ignore special french characters

### ISSUE THREAD

**Issue by kGk13** [highlightjs/highlight.js#1408]
Hello,

Your plugin works great. I'm just curios if i can add a custom behavior. I used on a searach page after the search is made in order to highlight the words.

If i make a search after "emigre" is there any way to highlight also "émigré" ?

Thanks.

**Comment by yyyc514** [comment]
How is this a highlight.js question specifically?  Could you show us an example perhaps of how your'e using it, etc?  I'm not sure I follow your question.

**Comment by yyyc514** [comment]
> If i make a search after "emigre" is there any way to highlight also "émigré" ?

I think that's outside the scope of highlight.js.

Closing this for now (trying to clean out old issues).  We can reopen if there is actually an issue about Hightlight.js usage.
