### ISSUE TITLE
(go) Misunderstands Backslash Character Literals

### ISSUE THREAD

**Issue by wyattallen** [highlightjs/highlight.js#1411]
In Go, when invoking the escape sequence for backslash in a character literal, HLJS gets stuck incorrectly interpreting the following lines as part of a string. Observe the following simple go program.

    package main
    import "fmt"
    func main() {
      s := "\\"
      c := '\\'
      fmt.Println("Hello, 世界", s, c)
    }

When highlighted with HLJS 9.5.0, the entire file following the `'\\'` is highlighted as a string. It doesn't have this issue with the string literal (`"\\"`).

**Comment by yyyc514** [comment]
Can you confirm this is still and issue and if so perhaps provider a jsfiddle example?

Quick template:
https://jsfiddle.net/ajoshguy/nagkqytv/

**Comment by wyattallen** [comment]
Still looks broken to me: https://jsfiddle.net/vchkrL3a/

**Comment by yyyc514** [comment]
```
      {
        className: 'string',
        variants: [
          hljs.QUOTE_STRING_MODE,
          {begin: '\'', end: '[^\\\\]\''},
          {begin: '`', end: '`'},
        ]
```

We don't seem to think that is valid.  The grammar right now says you can't end a string like that... I think it's trying to poorly protect against escaping, but I"m not sure.

**Comment by yyyc514** [comment]
That doesn't seem right to me, seems like we should probably use APOS_STRING_MODE there?

```
  };
  hljs.APOS_STRING_MODE = {
    className: 'string',
    begin: '\'', end: '\'',
    illegal: '\\n',
    contains: [hljs.BACKSLASH_ESCAPE]
  };
```

**Comment by yyyc514** [comment]
@wyattallen Any chance you could whip up a PR?  Looks like `go` could use some markup tests for strings also.
