### ISSUE TITLE
(yaml) Fails on Literal Blocks followed by Comments

### ISSUE THREAD

**Issue by tajmone** [highlightjs/highlight.js#1417]
YAML highlighter doesn't handle well literal blocks followed by comments.

You can see the problem live at this link:

https://cdn.rawgit.com/tajmone/gh-themes-magick/baf5927/gh-themes/leapday/index.html#configuration

where the comments are treated as part of the literal block scalar even though indentation has ended:

```yaml
header-includes: |
  <!-- anything you put here will go verbatim in the header section
       Useful for adding javascripts, custom metadata, and so on... -->
# ******************************************************************************
# *                             INSERT BEFORE BODY                             *
# ******************************************************************************
```

In the [yaml.js source file (53-59)](https://github.com/isagalaev/highlight.js/blob/master/src/languages/yaml.js#L53) we read:

```javascript
      { // multi line string
        className: 'string',
        begin: '[\\|>] *$',
        returnEnd: true,
        contains: STRING.contains,
        // very simple termination: next hash key
        end: KEY.variants[0].begin
      },
```

so the problem seems that the criterion by which a liter block is considered ended is not by checking the indentation but by capturing a new key definition — therefore comments are ignored in this process. The author states in the comment: `// very simple termination: next hash key`, so it's not a bug but just the way it was implemented.

I've attempted to fix it butI don't know how to handle checking the indentation level — need to keep some record of the initial indentation level? Possibly the easiest soultion would be to add an `end` check that also considers comments as a sign that the literal block is over. 

I'd love to fix it myself, but this particular task is beyond my reach right now; so all I can do is open an issue for it.

**Comment by ttrahan** [comment]
+1

**Comment by yyyc514** [comment]
I don't think YAML has changed much but can someone confirm this is still and issue and perhaps create a jsfiddle to reproduce it?

Template:
https://jsfiddle.net/ajoshguy/nagkqytv/

**Comment by cdbax** [comment]
Here's a reproduction: https://jsfiddle.net/cdbax/jr5w0q2d/7/
I'll be opening a WIP PR to discuss fixes to these sorts of outstanding YAML bugs.
