### ISSUE TITLE
Improper splitting of regular Strings in JavaScript highlighting.

### ISSUE THREAD

**Issue by danielkov** [highlightjs/highlight.js#1422]
I've started using `highlight.js` with `marked` today and straight away I bumped into an issue, it seems.

Here's my code to convert the source markdown file, using `marked`.

```js
const marked = require('marked')
const fs = require('fs')
const highlight = require('highlight.js')

marked.setOptions({
  highlight (code, lang) {
    return highlight.highlightAuto(code).value
  }
})

let test

fs.readFile('./test.md', (err, file) => {
  if (err) throw err
  if (file) {
    test = file;
    let parsed = marked(test.toString())
    fs.writeFile('test.html', parsed, err => {
      if (err) throw err
    })
  }
})
```

Inside `test.md` I have a regular code block:

```markdown
    ```js
    import React from 'react'
    import ReactDOM from 'react-dom'
    ```
 ```

This compiles down to the following: 

```html
<pre>
  <code class="lang-js">
    <span class="hljs-keyword">import</span>
    <span class="hljs-type">React</span> from <span class="hljs-symbol">'reac</span>t'
    <span class="hljs-keyword">import</span> <span class="hljs-type">ReactDOM</span> from <span class="hljs-symbol">'react</span>-dom'
  </code>
</pre>
```

As you can see it splits the string portion wrong for some reason I couldn't seem to figure out. I am not too familiar with the code so far, so I tried duplicating the issue with using `"react"` instead of single quotes.

This approach produced the right input, which is what made me think that this is an issue with `highlight.js`.

Any help on how to fix it would be appreciated, until then I need to realign myself to using double quotes... eugh.

**Comment by yyyc514** [comment]
Is this still an issue in 2019?  If so could you please reproduce with a jsfiddle perhaps?

I have a simple template you can use:
https://jsfiddle.net/ajoshguy/nagkqytv/18/

**Comment by danielkov** [comment]
@yyyc514 I've checked in your Fiddle and it seems to work fine now. I even forgot about this issue, it's been so long but it's great that you check old issues. I will close it now. Thanks.

**Comment by yyyc514** [comment]
Well, I'm new on the scene here. :)  Trying to close down the old issues so we can clearly see where the actual problems are hiding. :-)
