### ISSUE TITLE
Highligthing fails with generic interfaces in C#

### ISSUE THREAD

**Issue by Mackiovello** [highlightjs/highlight.js#1424]
When trying to use generic interfaces in my C# code, highlighting stops to work.

I'm using highlight.js in GitBook through the [highlight plugin](https://github.com/GitbookIO/plugin-highlight).

Screenshot:
![capture](https://cloud.githubusercontent.com/assets/19392292/21979053/8d664b06-dbdd-11e6-91b6-1704dfd03f44.PNG)

**Comment by MedAnd** [comment]
Further to above, multiple inheritance for c# also has an issue. For example B, C renders the correct color if the comma is removed. 

This does not work

internal sealed class A : B, C
{
}

While this version has the correct keyword color:

internal sealed class A : B C
{
}

**Comment by MedAnd** [comment]
The bug is in highlight.js\lib\languages\cs.js file... 
I have a partial hack/fix:

hljs.C_NUMBER_MODE,
      {
        beginKeywords: 'class interface', end: /[{;=]/,
        illegal: /[^\s:]/,
        contains: [
          hljs.TITLE_MODE,
          hljs.C_LINE_COMMENT_MODE,
          hljs.C_BLOCK_COMMENT_MODE,
          {
            begin: ','
          }
        ]
      }

**Comment by Mackiovello** [comment]
Is there any progress on this?

**Comment by isagalaev** [comment]
The project is very slow at the moment, so anything that requires non-trivial attention span gets backed off unfortunately. If you're interested in taking a stub at fixing it yourself I suggest looking at how a similar thing is defined in java (https://github.com/isagalaev/highlight.js/blob/master/src/languages/java.js#L9) and making it for C# as well. It's much easier to accept a PR with a clear [markup test case](http://highlightjs.readthedocs.io/en/latest/building-testing.html#testing-markup)!

**Comment by TAGC** [comment]
This is causing major problems for people using generic C# classes in Hastebin.

+1 from me.

**Comment by TAGC** [comment]
Interestingly, Discord does not suffer this problem even though I've read it uses highlight.js for syntax highlighting:

Interesting, Discord apparently uses highlight.js for syntax highlighting and has no issues with generic classes/interfaces:

![discord_2017-09-30_21-37-07](https://user-images.githubusercontent.com/1588951/31049264-9cc7caba-a627-11e7-82be-d247a4e0c144.png)

**Comment by yyyc514** [comment]
Is this still an issue in 2019?  Can someone please add a jsfiddle with reproduction if so?

You can borrow my template:
https://jsfiddle.net/ajoshguy/nagkqytv/18/

**Comment by Mackiovello** [comment]
It seems to work now, from your jsfiddle:

![Example](https://user-images.githubusercontent.com/19392292/66590068-3b0c7180-eb90-11e9-9281-7de6e3c114d9.PNG)

Closing this as fixed

**Comment by yyyc514** [comment]
THanks!

**Comment by VontineDev** [comment]
I have same issue on HTML

https://jsfiddle.net/s0a3oevb/

**Comment by yyyc514** [comment]
Those keywords don’t exist in JavaScript. Your class is “JavaScript”. We’re talking about csharp here.

**Comment by VontineDev** [comment]
Sorry. It was my mistake. Even if I change the class to csharp, it has same issue.
https://jsfiddle.net/VontineDev/7oy9m264/

**Comment by yyyc514** [comment]
Not sure what you're expecting.  It looks good to me.

**Comment by VontineDev** [comment]
![IMG_2141](https://user-images.githubusercontent.com/57723128/69823029-1ad16880-124b-11ea-9357-26c3ff462323.jpg)
What I write

![IMG_2142](https://user-images.githubusercontent.com/57723128/69823022-1907a500-124b-11ea-990e-ac33ff0a0943.jpg)
This is result

<int, CharacterData>  dissappeard

**Comment by yyyc514** [comment]
Please make a jsfiddle that SHOWS this actually happening.  A screen shot is not enough.  It's likely you aren't ending the HTML properly... You need to use `&lt;` not a literal `<`.
