### ISSUE TITLE
(javascript) Complex function call syntax not highlighted

### ISSUE THREAD

**Issue by rvlewerissa** [highlightjs/highlight.js#1428]
Hi, thanks for the great syntax highlighter.

It would be great if you can add highlights to JavaScript ES6 arrow and chaining, as in:

ES6 Arrow:
![screen shot 2017-01-19 at 12 34 20 am](https://cloud.githubusercontent.com/assets/15160023/22075563/1154e262-dddf-11e6-8478-5bed849f1fee.png)
What I meant is the color for the arguments.

Chaining:
![screen shot 2017-01-19 at 12 35 04 am](https://cloud.githubusercontent.com/assets/15160023/22075584/24ecbd4a-dddf-11e6-884f-9aca9ef7c418.png)
And on this one is color after the dot.

Thanks! :)

**Comment by BosenY** [comment]
https://github.com/isagalaev/highlight.js/issues/1296

**Comment by yyyc514** [comment]
There has been some work done on this.  Can you confirm if this is still an issue or not?

**Comment by yyyc514** [comment]
Ping.

**Comment by paladox** [comment]
Hi,

Doing something like:

```js
    /**
     * @suppress {checkTypes}
     */
    _import(url) {
      return new Promise((resolve, reject) => {
        (this.importHref || Polymer.importHref)(url, resolve, reject);
      });
    },
```

Still dosen't highlight arrow.

It currently looks like:

<img width="1438" alt="Screenshot 2019-10-20 at 02 17 08" src="https://user-images.githubusercontent.com/5727000/67153368-d6fc5280-f2df-11e9-9583-629c767f4cb4.png">

It's not highlighting the resolve and reject params. It's also not highlighting the params in "(url, resolve, reject)".

**Comment by yyyc514** [comment]
The params technically should be highlighted (for consistency), but that's tough because what you're doing there doesn't look like a function call... it'd be hard to detect that...

Traditionally we don't highlight operators and punctuation, so that is intentional.

**Comment by yyyc514** [comment]
Can you provide a jsfiddle so it's clear (for all time also) which version this is running against?

You can use my template:
https://jsfiddle.net/ajoshguy/a1kntyg4/

**Comment by yyyc514** [comment]
Seems it would be possible to teach it that:

```
(.*)(params)
```

Is a function call... I assume anything inside the first parens could be an expression... or even other function calls, but I'd think this was doable if someone wanted to attempt it.

**Comment by yyyc514** [comment]
> I would love to see some colour on => though.

I'm coming around a bit on this as you could argue it's more of a keyword than an operator. :)

**Comment by yyyc514** [comment]
**Closing this as resolved.**

- `resolve, reject` are now properly identified as params (if they weren't in the past)
- `=>` is intentionally not highlighted (as it's an operator)
- `(url, resolve, reject)` should NOT be highlighted.  parameters are not highlighted in general, only when part of a function definition.  This is a function call, not a definition, so these don't need to be flagged as `params`.

Reference:

https://jsfiddle.net/ajoshguy/dc4o5gnz/6/
