### ISSUE TITLE
C, Objective-C, and C++ syntax misunderstand macros.

### ISSUE THREAD

**Issue by Rapptz** [highlightjs/highlight.js#1430]
A simple case:

```cpp
#define foo (1 << 20)
```

Anything after the `<` is seen as a meta-string because it incorrectly assumes if the string starts with `#` then anything enclosed in < and > is an include path.

**Comment by samsam2310** [comment]
https://github.com/isagalaev/highlight.js/blob/master/src/languages/cpp.js#L58
Here use '<' '>' as the begin and the end of the meta string.

**Comment by deror1869107** [comment]
`#define MAX(a,b) ((a > b) ? a : b))`

**Comment by yyyc514** [comment]
If this is still an issue a jsfiddle showing a few examples of what currently performs poorly would be greatly appreciated.

https://jsfiddle.net/ajoshguy/nagkqytv/

**Comment by Rapptz** [comment]
Looks fixed to me. Thanks!

**Comment by yyyc514** [comment]
Awesome.  Thanks!
