### ISSUE TITLE
SQL language detection breaks if you use a < or > character in an if statement

### ISSUE THREAD

**Issue by jasongisstl** [highlightjs/highlight.js#1432]
If you have a less than or greater than character in an if statement, SQL language detection will fail.

E.g:
`hljs.highlightAuto("if 5 < 10", ["sql"]);`

Returns text with no language highlighting, as "<" is detected as an 'illegal lexeme'.

**Comment by DavidSimner** [comment]
For Microsoft SQL Server's Transact-SQL (T-SQL), this issue is fixed in https://github.com/isagalaev/highlight.js/pull/1524

**Comment by egor-rogov** [comment]
Now works for PostgreSQL (#1804).
As for pure standard SQL, `if` is not a valid statement anyway.

**Comment by yyyc514** [comment]
Sounds like we could close this one then? @egor-rogov

**Comment by egor-rogov** [comment]
I guess so.
