### ISSUE TITLE
HAML syntax highlighting broken

### ISSUE THREAD

**Issue by skylarmb** [highlightjs/highlight.js#1435]
### Codepen:
http://codepen.io/skylarmb/pen/dNZzMb

<img width="398" alt="screen shot 2017-01-27 at 4 53 15 pm" src="https://cloud.githubusercontent.com/assets/7543705/22392700/26c86adc-e4b1-11e6-9c5e-d838986a1ba8.png">

<img width="456" alt="screen shot 2017-01-27 at 4 53 50 pm" src="https://cloud.githubusercontent.com/assets/7543705/22392707/3979bbea-e4b1-11e6-9342-0802d60f74ec.png">

divs are not being syntax highlighted. Only tags that are specified with a `%` are properly highlighted.

**Comment by skylarmb** [comment]
I am working on a fix for this. There are also a number of places where ruby should be used as a sublanguage (such as inside of `{...}` where it is not currently...)

**Comment by yyyc514** [comment]
Any update? :-)

**Comment by skylarmb** [comment]
sorry, never got around to this. We ended up using Prism.js instead

**Comment by yyyc514** [comment]
Seems to work now: https://jsfiddle.net/ajoshguy/gdby50x7/

![Screen Shot 2019-10-12 at 5 45 49 PM](https://user-images.githubusercontent.com/6473/66708036-3377d480-ed18-11e9-87a6-2a2c4bdca53d.png)
