### ISSUE TITLE
Deactivate auto language detect add to readme?

### ISSUE THREAD

**Issue by rjb25** [highlightjs/highlight.js#1438]
The auto-detection is not very great for terminal commands. Having to type:
\`\`\`text
This is yet another of many code blocks that do not need highlighting
\`\`\`
instead of just
\`\`\`
code
\`\`\`
Is getting on my nerves.
However there are cases where I do want to highlight syntax, so removing highlight.js entirely is not an option.
Is there any way to set highlight.js to have text or nothing as default, when a language is not specified?

**Comment by rjb25** [comment]
I found a way to get this behavior. Replace 
```
<script>hljs.initHighlightingOnLoad();</script>
```
with
```
$(document).ready(function() {
  $('pre code').each(function(i, block) {
      if(!(block.classList.length==0)){
    hljs.highlightBlock(block);
      }
  });
});
```

**Comment by Sannis** [comment]
@rjb25 you can use `nohighlight` class for such blocks: https://github.com/isagalaev/highlight.js/blob/master/README.md#getting-started

**Comment by rjb25** [comment]
Yes, I think nothing is a better default. Some users might want to know
that is an option.

**Comment by lonelyelk** [comment]
When I use `text` or `nohighlight`, selected theme is not applied either. How do I apply color theme but avoid guessing syntax highlight?

**Comment by asmeurer** [comment]
For me (using the output of Markdown from the Python `commonmark` package), when using `text` or `nohighlight`, I get a block like this

`this is a block`
`of some text`

instead of

```
this is a block
of some text
```

I would like some way to disable highlighting but still keep the block.

**Comment by yyyc514** [comment]
I think this will be resolved by adding `plaintext` to the list of languages.  If what you want is a code block STYLED by highlight.js without any actual language highlighted then you want to use "plaintext", a grammar created for just this "placeholder" purpose.  The next release should include plaintext.

Closing this as asked and answered.
