### ISSUE TITLE
Latest branch colorization bug

### ISSUE THREAD

**Issue by c0rvax** [highlightjs/highlight.js#1441]
Hey guys, 

Firstly, i would like to say 'thanks' for the work you do, it helped me a lot! Keep going!

However, i faced some problems while trying to highlight PHP-code in the latest branch of highlightJS (9.x.x), although the code is highlighted right if using previous highlightJS branch. For more info, see the screenshots.

9.9.0 view:
![9 9 0_view](https://cloud.githubusercontent.com/assets/7037785/22513941/d2c973ca-e8ae-11e6-986c-1feeb99f4714.png)

9.9.0 html:
![9 9 0_html](https://cloud.githubusercontent.com/assets/7037785/22513943/d482809e-e8ae-11e6-8ba4-84bb21095f22.png)

8.9.1 view:
![8 9 1_view](https://cloud.githubusercontent.com/assets/7037785/22513951/dc1940f4-e8ae-11e6-9f62-e73490c53f68.png)

8.9.1 html:
![8 9 1_html](https://cloud.githubusercontent.com/assets/7037785/22513962/e040330e-e8ae-11e6-9131-7092af44a5f1.png)

**Comment by Rarst** [comment]
PHP got _a lot_ less highlight in 9.x, see #1142

**Comment by yyyc514** [comment]
If you're still interested in weighing in on this issue after so much time has passed there is a new discussion issue:

https://github.com/highlightjs/highlight.js/issues/1378

Closing this as a duplicate though.
