### ISSUE TITLE
Lua highlight bug after comments

### ISSUE THREAD

**Issue by exotickg1** [highlightjs/highlight.js#1447]
After comment in the code all the other lines are displayed as a comment
![Ez image](https://i.gyazo.com/3fd63a8d1079772d63e03fafcfcc92b1.png)

**Comment by Lemmmy** [comment]
Any update on this issue?

**Comment by Lemmmy** [comment]
I've found the source of the issue, at least on our end. Our forum software (Simple Machines Forums) inserts `<br>` tags into the end of each line of code, which causes highlightjs to not match `$` in the COMMENT regex. This is likely fixable on the SMF end, but is there any way to make highlightjs ignore `<br>`? I'm assuming that it should be reasonable to do, as anything in code would have to be escaped anyway.

**Comment by DCubix** [comment]
THis is still not fixed

**Comment by marcoscaceres** [comment]
Pull request welcome 🙏

**Comment by yyyc514** [comment]
Have you tried:

```js
hljs.configure({useBR: true})
```

**Comment by yyyc514** [comment]
Closing as asked and answered if the problem is indeed `<br>` tags as confirmed by @Lemmmy .  If you have any other questions, feel free to ask.  If your software is going to insist on adding br tags then you should be able to get proper results with `usrBR`.
