### ISSUE TITLE
C++ Syntax Misunderstands Nested Parens in String Constructor

### ISSUE THREAD

**Issue by wyattallen** [highlightjs/highlight.js#1451]
Consider the following C++ program

    void main() {
      std::string foo(bar()->baz());
    }

HLJS will incorrectly mark the `(bar()` as the parameters to the string constructor, resulting in inconsistently highlighted parens.

    <span class="hljs-built_in">std</span>
    ::
    <span class="hljs-function">
      <span class="hljs-built_in">string</span> 
      <span class="hljs-title">foo</span>
      <span class="hljs-params">(bar()</span>
      ->
      <span class="hljs-title">baz</span>
      <span class="hljs-params">()</span>)
    </span>;

**Comment by erikman** [comment]
I think I see a related problem. The following fails to highlight at all for me:

```c++
Buffer myBuffer(getBuffer());
```

For me I think it is related to the `))`. If I replace by a single `)` it hightlights correctly.

**Comment by yyyc514** [comment]
Can you confirm this is still and issue and perhaps provide a jsfiddle?

You can use my template:
https://jsfiddle.net/ajoshguy/nagkqytv/18/

**Comment by wyattallen** [comment]
I can no longer repro: https://jsfiddle.net/jmpgx6hc/
Thanks!

**Comment by erikman** [comment]
I also verify that it has been fixed: https://jsfiddle.net/goodbyte/jhv3L7do/ thanks!
