### ISSUE TITLE
Enter clears input field

### ISSUE THREAD

**Issue by simkessy** [highlightjs/highlight.js#1457]
When I start typing, if I hit the enter key in the input field, it clears the field but leaves the results box open. 

How would I go about prevent anything from happening when I hit enter? 

I've tried this:

```
$('.input-container').on("keypress", "input", function(event) {
  return event.keyCode != 13;
});

$(document).on("keypress", "input", function(event) {
  return event.keyCode != 13;
});

```

But that's not currently working.

**Comment by yyyc514** [comment]
How is this related to Highlight.js?  I don't see the connection.
