### ISSUE TITLE
JavaScript: / following a unary operator mistaken as start of regular expression

### ISSUE THREAD

**Issue by atesgoral** [highlightjs/highlight.js#1458]
Demo: https://jsfiddle.net/atesgoral/n5cgtfzv/2/

<img width="605" alt="screen shot 2017-02-22 at 8 42 14 am" src="https://cloud.githubusercontent.com/assets/50832/23213933/e815cca6-f8da-11e6-9553-2ef234ed53f3.png">

The sequence `a++ /...` is mistakenly taken as the start of a regular expression (hljs-regexp).

**Comment by yyyc514** [comment]
Closing this as a dup of https://github.com/highlightjs/highlight.js/issues/2050

I will copy your Fiddle reference over though, thanks for that!
