### ISSUE TITLE
(javascript) fails on nested code inside template literal

### ISSUE THREAD

**Issue by ivan-kleshnin** [highlightjs/highlight.js#1463]
```js
// Spies function calls
function spy(fn) {
  return function (...args) {
    console.log("spy:", fn.name + `(${inspect(args, {colors: true}).slice(2, -2)})`)
    return fn(...args)
  }
}
```

![bug](https://cloud.githubusercontent.com/assets/2128182/23302315/f1a2ed22-fa96-11e6-86f6-8578eabde069.png)

Note that the parens are mismatched.

**Tested on: highlight.js@9.9.0**

**Comment by yyyc514** [comment]
Currently the nesting support isn't very robust.  Can you confirm this is still an issue though?

**Comment by yyyc514** [comment]
Closing this in favor of https://github.com/highlightjs/highlight.js/issues/1405 as it includes a fiddle example.  Feel free to respond on that thread.

**Comment by yyyc514** [comment]
If you could contribute a recent failing case on that thread in jsfiddle that'd be great.
