### ISSUE TITLE
(java) @annotations don’t support numbers 

### ISSUE THREAD

**Issue by Vnthf** [highlightjs/highlight.js#1478]
```java
@RunWith(SpringRunner.class)
@SpringBootTest
@AutoConfigureMockMvc
@Transactional     
@Slf4j
public class BoardControllerTest {
...

In hightlight js 

Slf``4j``

4j is not hightlighting correctly.

I use tomorrow skin

**Comment by jxsl13** [comment]
Java syntax highlighting is buggy in general. ._.

**Comment by CloudSen** [comment]
The problem still exists ...  
![image](https://user-images.githubusercontent.com/25652685/61808310-bbfb7d00-ae6d-11e9-8631-8a79ddeb37d2.png)

**Comment by marcoscaceres** [comment]
We unfortunately don't have resources to maintain individual languages, so pull requests welcome 🙏

**Comment by yyyc514** [comment]
Line 109 of java.js for anyone who wants to take a whack at a PR for this. :-)  Looks easy.

**Comment by yyyc514** [comment]
And yes java is super-short as far as syntaxes go... probably could be much improved.
