### ISSUE TITLE
GAMS language causes freezing, high CPU usage, and inevitable RangeError when parsing specific strings

### ISSUE THREAD

**Issue by omarestrella** [highlightjs/highlight.js#1494]
The issue I am seeing is with this particular string (or similar ones): I t...

In certain scenarios, using an ellipsis will cause the auto highlighter to loop through the languages and when it gets to GAMS, it locks up the browser. Chrome Canary is the only one that eventually gets out of the endless loop with a RangeError.

You can reproduce this in 9.10 by running: `hljs.highlight('gams', 'I t...')`

**Comment by yyyc514** [comment]
Can you confirm if this is still an issue or not?  Thanks, Josh.

**Comment by yyyc514** [comment]
Should be fixed:
https://github.com/highlightjs/highlight.js/commit/d05317a8bc9ad2335bd4b7709e507314546836b1#diff-dbb0a20b500e16aeef15c7f6aa7b78d5
