### ISSUE TITLE
(cpp) template type in function declaration

### ISSUE THREAD

**Issue by arximboldi** [highlightjs/highlight.js#1502]
Hi!

In general, highlight.js is highlighting C++ function declarations with a special syntax so the function names and arguments do stand out. However if there is a template anywhere in there, it fails. Example:
```
boost::optional&lt;application> handle_key(application state, key_code key, coord size);
```
Is highlighted all in the same basic color. A simpler declaration like this otherwise works:
```
int main(int argc, char* argv[])
```

**Comment by yyyc514** [comment]
Shouldn't this really be a little tighter:

```
var IDENT_RE = '[a-zA-Z][<>\\w]*';
```

Ie detect `identifier<something>`.  Right now it's pretty open ended.  You could probably even reuse the existing ident:

```
var IDENT_RE = hljs.IDENT_RE + '(<...>)?;
```

**Comment by yyyc514** [comment]
If this was tightened up a little and you added a `markup` test (or updated one if there is one that makes sense) and submitted a PR we'd be happy to look at it more closely.

**Comment by yyyc514** [comment]
Might first confirm we haven't fixed this in the meanwhile already? :)
