### ISSUE TITLE
(bash) $((Base#number)) variable syntax issue

### ISSUE THREAD

**Issue by GHGibonus** [highlightjs/highlight.js#1504]
In bash, you can specify the base of a number in an arithmetic expression with the construct B#n where the value of that construct is ``n`` is base ``B`` (B can be anything from 2 to 32, or can be specified with a ``$variable``).

The issue is that in highlight.js, in this configuration, # is considered as the start of a comment. Here are three examples use cases:
```bash
echo $(( 16#deadbeef / 1003 ))
```
```bash
yumi=deadbeef
echo $(( 16#$yumi / 1003 ))
```
```bash
B=20
yumi=deadbeef
echo $(( $B#$yumi / 1003 ))
```

What I see in hightlight js: everything after the # is a comment.

What I expect: ``16#`` and ``$B#`` should be considered as a numeric literal or something similar (at least when inside the ``$((...))`` arithmetic expression construct); And stuff after it should not be considered a comment. Typically, I expect normal syntax highlight to work after ``16#``.

Some tests gives me:

```node
> hljs = require("highlight.js")
> hljs.highlightAuto("echo $(( 16#deadbeef * 10))").value
'<span class="hljs-built_in">echo</span> $(( 16<span class="hljs-comment">#deadbeef * 10))</span>'
```
Note: this is the original snippet of code that prompted me to open this issue:
```bash
#!/bin/sh

#Sets the current system date to one hour before now.
#WARNING!! don't use after midnight.
curhour=$(date +'%H')
curdate=$((10#$curhour - 1)):$(date +'%M:%S')
date --set="$curdate"
```

**Comment by yyyc514** [comment]
Is it even possible to have comments inside of subexpressions I wonder?

**Comment by yyyc514** [comment]
So If there is whitespace around it can I actually put a comment inside an `$(( ))` block?

**Comment by egor-rogov** [comment]
I believe no. `man bash` says:

>       Arithmetic expansion allows the evaluation of an arithmetic expression and the substitution of the result.  The format for arithmetic expansion is:
>
>              $((expression))
>
>       The expression is treated as if it were within double quotes, but a double quote inside the parentheses is not treated specially.   All  tokens  in
>       the  expression undergo parameter and variable expansion, command substitution, and quote removal.  The result is treated as the arithmetic expres‐
>       sion to be evaluated.  Arithmetic expansions may be nested.

As the expression "is treated as if it were within double quotes", comments can't be allowed in it.

**Comment by yyyc514** [comment]
Awesome. :)
