### ISSUE TITLE
javascript code are treated as comment

### ISSUE THREAD

**Issue by 274659281** [highlightjs/highlight.js#1506]
My javascript code are treated as comment. The code and screenshot are in the attach files.
Please help!

[Desktop.zip](https://github.com/isagalaev/highlight.js/files/961319/Desktop.zip)

**Comment by yyyc514** [comment]
Ok, I'm not downloading a zip file, sorry.  If you're still having issues please upload sample code, a screen grab, etc.  If you want to show a reproducible test case please consider jsfiddle:

Simple template you can fork:
https://jsfiddle.net/ajoshguy/nagkqytv/11/

**Comment by yyyc514** [comment]
Closing due to age (we're trying to clear out old dead issues), but we can reopen if you provide additional details and are still having trouble.
