### ISSUE TITLE
Convert from TextMate grammar

### ISSUE THREAD

**Issue by goodmind** [highlightjs/highlight.js#1513]
Is there converters from textmate grammars or I need to rewrite grammar manually?

**Comment by isagalaev** [comment]
No, there's no converter. Mostly due to out peculiar syntax and also different philosophies in what gets highlighted. Look at [Language definition guide][1] and [Style guide][2].

[1]: http://highlightjs.readthedocs.io/en/latest/language-guide.html
[2]: http://highlightjs.readthedocs.io/en/latest/style-guide.html

**Comment by goodmind** [comment]
@isagalaev well, how to do something like `beginCaptures`?

**Comment by isagalaev** [comment]
This is something that highlight.js doesn't have, and what makes a generic converter impossible :-)

The more useful answer depends on what you're trying to achieve. Sometimes there are highlight.js-specific solutions, sometimes we just straight up don't want to highlight something. So please provide an example!

**Comment by goodmind** [comment]
I have this grammar and want to convert it into highlight.js one: https://github.com/goodmind/language-typelanguage/blob/master/grammars/typelanguage.tmLanguage.json

And I have `combinator-declaration-without-hash`
with `begin` regex `(([_$\\w]+)(\\b\\.))?([_$\\w]*)(\\b#)([[:alpha:][:alnum:]]*)\\s*`

And I want to color captures inside it:
```
"2": {
					"name": "meta.definition.combinator.tl variable.other.tl"
				},
				"4": {
					"name": "meta.definition.combinator.tl variable.other.tl"
				},
				"5": {
					"name": "storage.type.tl"
				},
				"6": {
					"name": "storage.type.tl"
				}
```

**Comment by goodmind** [comment]
@isagalaev any thoughts?

**Comment by stevepeak** [comment]
@goodmind did you end up solving this problem?

**Comment by goodmind** [comment]
@stevepeak I didn't

**Comment by stevepeak** [comment]
@goodmind Would you be interested in helping contribute to an open source package that does this?

**Comment by goodmind** [comment]
@stevepeak yes, but I think it's impossible because TextMate uses oniguruma regexp engine (doesn't work in browser at least now)

**Comment by yyyc514** [comment]
If you all made any progress with a general purpose converted I'd be curious.

**Comment by yyyc514** [comment]
Closing as this is asked and answered.  Still if you make any progress I'd love to hear about it. :)
