### ISSUE TITLE
(javascript) ES2015 shorthand properties

### ISSUE THREAD

**Issue by maurobringolf** [highlightjs/highlight.js#1514]
As far as I can tell shorthand object properties from ES2015 are not highlighted because the semicolon is missing, but used in the relevant RegExp. Is that right? Are there any plans for supporting them?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer

**Comment by yyyc514** [comment]
Can you provide:

- a specific code example
- how Highlight.js currently highlights it
- how you expect Highlight.js should highlight it in a perfect world

**Comment by yyyc514** [comment]
Ping.

**Comment by yyyc514** [comment]
Closing due to age and inactivity.  If there is still an issue here feel free to respond when you have time and we'll happily reopen the issue! Also a specific code example (here on Github) would be nice.

You can fork my template if it helps:
https://jsfiddle.net/ajoshguy/a1kntyg4/
