### ISSUE TITLE
Python code misdetected as Ruby

### ISSUE THREAD

**Issue by wolfy1339** [highlightjs/highlight.js#1518]
If you look at this Live demo I created: https://output.jsbin.com/zeqegux, you can see that HLJS detects Python code as Ruby. The only way to defy this bug is to add the `.python` class to the code block, as seen in this live demo: https://output.jsbin.com/zeqegux/1.

**Comment by MicroDroid** [comment]
I can confirm this on my website https://codebottle.io/s/5c3c51cfdd

I use NPM's module and I load only a specific set of languages via webpack's config.

**Comment by yyyc514** [comment]
The code detection is not guaranteed to be 100% accurate.  It's a "best effort" system.  If you wanted to identify specific changes to improve the relevancy scores of the Python or Ruby syntaxes (that still passes all tests) a PR would be great.

**Comment by yyyc514** [comment]
I wonder if for Python just counting lines that end in `:` would be a good relevancy check. :-)

**Comment by yyyc514** [comment]
`self` is a convention in Python right, not a keyword?  One reason Ruby wins is it claims all the `self` as being Ruby keywords. :-)

**Comment by MicroDroid** [comment]
@yyyc514 `:` definitely sounds like a good deal lol

**Comment by yyyc514** [comment]
Closing this as: The code detection is not guaranteed to be 100% accurate.  Adding the `python` class is the correct fix here, this is one of the "too close to call" cases.

**Comment by MicroDroid** [comment]
I approve your action :P
