### ISSUE TITLE
Bring back the old python-based build system

### ISSUE THREAD

**Issue by infinity0** [highlightjs/highlight.js#1521]
Hi, I'm trying to update this in Debian from 8.2 to the latest 9.11 version.

Unfortunately you switched build system in the meantime to node-gear which is not available in Debian, and no longer available in github - https://github.com/yahoo/gear gives a 404. Would it be possible to bring back the old python-based build system?

**Comment by infinity0** [comment]
In fact, it still works quite well. I only have to apply this patch for it to work:

```diff
--- debian/old-build.py	2017-05-16 13:40:42.493179176 +0200
+++ tools/build.py	2017-05-16 13:41:16.541612025 +0200
@@ -134,7 +134,7 @@
     if not match:
         return
     headers = match.group(1).split('\n')
-    headers = dict(h.strip().split(': ') for h in headers if ': ' in h)
+    headers = dict(h.strip().split(': ', 1) for h in headers if ': ' in h)
     return headers if 'Language' in headers else None
 
 def language_filenames(src_path, languages):
@@ -204,7 +204,7 @@
         hljs = 'var hljs=new %s();' % strip_read(hljs_filename).rstrip(';')
         file_func = lambda f: utf8_open(f).read()
     else:
-        hljs = 'var hljs = new %s();\n' % strip_read(hljs_filename)
+        hljs = 'var hljs = new %s();\n' % strip_read(hljs_filename).rstrip(';')
         file_func = strip_read
     return ''.join([hljs] + [wrap_language(f, file_func(f), compressed) for f in language_filenames])
 
```

**Comment by infinity0** [comment]
Patch update:

https://anonscm.debian.org/cgit/pkg-javascript/highlight.js.git/tree/debian/patches/python-buildsystem-update.patch

This works well to avoid a needless dependency on node-gear.

**Comment by isagalaev** [comment]
The build system has been switched to node because it was easier for us to maintain, and the reasoning didn't change since. The current build system relies on packages in npm, so what you need from your OS package manager is the reasonably modern version of node (>4) and accompanying npm.

On a related note, your patch may not be working correctly and may be the reason for the bug with auto-detection you reported.

**Comment by infinity0** [comment]
We have nodejs 4.8.2 but the npm ecosystem is the main problem here. There is basically one new "buildsystem" for every new *useful* package and there's no way Debian volunteers can keep up with this stupid situation.

What does node-gear do, exactly? The old python build script was simple and had no dependencies. These new build scripts are split over many files, hard to read, and have lots of external dependencies that make it even harder to read. One also has to keep track of their versions, adding to the overhead. I'm surprised that you think it's easier to maintain.

**Comment by tjis** [comment]
Looks like the official Gear.js repository is here now: https://github.com/twobit/gear. Too bad the website didn't get updated to reflect this.
