### ISSUE TITLE
how can i use highlight in <textarea>?

### ISSUE THREAD

**Issue by kobehht** [highlightjs/highlight.js#1531]

**Comment by dguo** [comment]
I don't think you can. See https://stackoverflow.com/a/25691254/1481479

**Comment by yyyc514** [comment]
Related: https://github.com/highlightjs/highlight.js/issues/1356

And I dropped a few comments.  Short answer: This isn't what Highlight.js is intended to do and you probably aren't going to have the best of luck. :-)

**Comment by yyyc514** [comment]
@marcoscaceres Think we could close this one.
