### ISSUE TITLE
(jsx) closing tag being parsed as a regex

### ISSUE THREAD

**Issue by esprehn** [highlightjs/highlight.js#1551]
ex.

<img width="534" alt="jsx" src="https://user-images.githubusercontent.com/415779/27318700-ca125c1e-5542-11e7-91ed-45a8e2a9c500.png">

**Comment by esprehn** [comment]
Would it be possible to reuse the regexes from here?
https://github.com/babel/babel-sublime

**Comment by yyyc514** [comment]
Can you provide actual code or a jsfiddle example?  Is this still an issue?  I've seen working examples of JSX now... the big issue we have is with self-closing tags, when you aren't using here.

**Comment by yyyc514** [comment]
Ping.
