### ISSUE TITLE
(scala) comment rendered as class title

### ISSUE THREAD

**Issue by pijusn** [highlightjs/highlight.js#1559]
Given input

```
class A  // Something goes here
{
}
```

Comment words (including `//`) are rendered as titles:

```
<span class="hljs-class"><span class="hljs-keyword">class</span> <span class="hljs-title">A</span>  <span class="hljs-title">//</span> <span class="hljs-title">Something</span> <span class="hljs-title">goes</span> <span class="hljs-title">here</span></span>
{
}
```

On the other hand if curly bracket is in the same line:

```
class A {  // Something goes here
}
```

Output is rendered as expected:

```
<span class="hljs-class"><span class="hljs-keyword">class</span> <span class="hljs-title">A</span> </span>{  <span class="hljs-comment">// Something goes here</span>
}
```

I used `hljs.highlight('Scala', rawSourceCode)` for the formatting.

Highlight.js version: `9.12.0`

**Comment by yyyc514** [comment]
Can you please confirm this issue on latest and if possible provider a jsfiddle reproducing?

You can borrow my template:
https://jsfiddle.net/ajoshguy/nagkqytv/18/

**Comment by pijusn** [comment]
Yes, it's still present for Scala highlighting with version `9.15.10`. One thing to note is that I see it's not just Scala related. I see same happening for Kotlin as well. Maybe it affects all languages with similar syntax (re-using same parsers).

Fiddle with Scala: https://jsfiddle.net/y58dnucs/3/
Fiddle with Kotlin: https://jsfiddle.net/9j6uwdnr/

**Comment by yyyc514** [comment]
I imagine the "class" rule is looking for { to end the match and not expecting comments... so we'd need to teach both grammars that comments could pop up in the middle of "starting a class". That's off the top of my head without looking.

**Comment by yyyc514** [comment]
If you'd like to take a pass at making a PR it'd be welcomed.
