### ISSUE TITLE
Invalig highlighting of SQLite query

### ISSUE THREAD

**Issue by maximal** [highlightjs/highlight.js#156]
Example:

``` sql
DROP TRIGGER IF EXISTS undo_delete_message;
CREATE TRIGGER undo_delete_message
BEFORE UPDATE OF body_xml
ON Messages
FOR EACH ROW
WHEN NEW.body_xml = ''
BEGIN
    SELECT
        CASE WHEN (NEW.body_xml = '' AND NEW.author != 'your_skype_login')
            THEN RAISE(ROLLBACK, '1')
        END;
END;
```

(from http://sijeko.ru/lab/skype-messages)

**Comment by Nennner** [comment]
Это работает?
![default](https://cloud.githubusercontent.com/assets/13180917/8511529/6f8f89bc-2324-11e5-9a7d-042ced07c71c.jpg)
Я правильно пишу? Туда?
У меня сообщения только разве что не восстанавливаются.

=======================================
Does it works?
(IMG)
I'm writing right? In the correct place?
My messages doesn't restoring.

**Comment by maximal** [comment]
@Nennner, здесь было обсуждение _подсветки SQL-синтаксиса_ в библиотеке _highlight.js_, а не правильности работы скрипта.

Вы не туда пишете.

**Comment by Nennner** [comment]
Аа.. а куда нужно тогда? http://sijeko.ru/lab/skype-messages

**Comment by maximal** [comment]
Найдите где-нибудь на сайте контакты, напишите. При чём тут библиотека „highlight.js“.

**Comment by Nennner** [comment]
Окей, Вы правы. Удалил.
