### ISSUE TITLE
How to hightlight the code after using the Jquery to append <pre><code></code></pre>

### ISSUE THREAD

**Issue by dvx1231** [highlightjs/highlight.js#1562]
$("#Have").append("&lt;pre>"+"&lt;code>"+ data[i].DMDNR +"&lt;/code>"+"&lt;/pre>");

**Comment by dvx1231** [comment]
After loading the page How to highlight again

**Comment by yyyc514** [comment]
Call `initHighlighting` or `highlightBlock(element)`

**Comment by marcoscaceres** [comment]
Closing as answered.
