### ISSUE TITLE
(fortran) number before underscore disappears

### ISSUE THREAD

**Issue by interkosmos** [highlightjs/highlight.js#1566]
If an underscore follows a number in formatted Fortran code, the number disappears. The code
````
e = init_pair(1_c_short, COLOR_YELLOW, COLOR_BLACK)
````
will be shown as
````
e = init_pair(_c_short, COLOR_YELLOW, COLOR_BLACK)
````

**Comment by yyyc514** [comment]
Can you confirm this is still a real issue with the current version of the library or provide a jsfiddle?

Sample you can fork:
https://jsfiddle.net/ajoshguy/nagkqytv/11/

**Comment by kazk** [comment]
@yyyc514 Still an issue with v9.15.10. https://jsfiddle.net/94qdb70x/

![image](https://user-images.githubusercontent.com/639336/66335338-b7345a00-e8ef-11e9-8b1d-01f94e18ac6b.png)

Also, it seems like the first digit of the number before the underscore is disappearing.

```
4_ikind
35_ikind
```
becomes
```
_ikind
5_ikind
```

**Comment by yyyc514** [comment]
@kazk Thanks so much! :-)  How very very annoying this must be.  Will whip up some test cases.

**Comment by yyyc514** [comment]
I'm not sure if we should call this a parser bug or a grammar bug, but the parser does NOT like rules that match 0 length strings, such as the Fortran number rule is prone to do:

```
      {
        className: 'number',
        begin: '(?=\\b|\\+|\\-|\\.)(?=\\.\\d|\\d)(?:\\d+)?(?:\\.?\\d*)(?:[de][+-]?\\d+)?\\b\\.?',
        relevance: 0
      }
```

When this happens that data will just be "dropped", which is what you're seeing happen here.

**Comment by yyyc514** [comment]
I think the following would be better, but not 100% sure:

```
(?=\b|\+|\-|\.)
(\d*\.\d*|\d+\.|\d+)
([de][+-]?\d+)?
(_[a-z_]+)?
\b\.?
```

![Screen Shot 2019-10-09 at 7 37 47 AM](https://user-images.githubusercontent.com/6473/66478139-b6263880-ea67-11e9-99f6-befea624ab12.png)


Thoughts?

**Comment by yyyc514** [comment]
I don't understand the goal of the optional trailing period either though.

**Comment by egor-rogov** [comment]
The handbook defines the following formats:
* `[sign] digit-string [ _ kind-parameter ]`
* `[sign] digit-string exponent-letter exponent [ _ kind-parameter ]`
* `[sign] whole-part . [ fraction-part ] [ exponent-letter exponent ] [ _ kind-parameter ]`
* `[sign] . fraction-part [ exponent-letter exponent ] [ _ kind-parameter ]`

where

* `whole-part` and `fraction-part` are `digit-string`,
* `exponent` is signed `digit-string`,
* `kind-parameter` is either `digit-string` or identifier.

I'd tackle them with the following:

```js
variants: [
  { begin: /[+-]?\d+(\.(\d+)?)?([de][+-]?\d+)?(_[0-9a-z_]+)?/ }, // the first 3 formats
  { begin: /[+-]?\.\d+([de][+-]?\d+)?(_[0-9a-z_]+)?/ } // the last format
]
```

**Comment by yyyc514** [comment]
I thought we weren't wanting to pull in th prefix + - as part of the number though...

**Comment by egor-rogov** [comment]
Aye. Hence lookahead.
I think `.` is part of the number.

**Comment by yyyc514** [comment]
> I thought we weren't wanting to pull in th prefix + - as part of the number though...

Although I'm pretty sure I saw we're not 100% consistent about that... but I did read that's the "consistent" desire or at least has been. :-)

**Comment by egor-rogov** [comment]
Why, we don't need lookaheads. Just drop `[+-]?` part of the regex. No?

**Comment by yyyc514** [comment]
Maybe.  The lookahead was so you could have a single regex to catch both boundaries and \. for start instead of having two. :-)  I'm not opposed to have two though.

**Comment by egor-rogov** [comment]
Hm, we can do it in a single regex without lookahead:
```js
begin: /(\d+(\.(\d+)?)?|\.\d+)([de][+-]?\d+)?(_[0-9a-z_]+)?/
```
