### ISSUE TITLE
Show/log an error if the user requests a valid language that isn't currently available

### ISSUE THREAD

**Issue by juzraai** [highlightjs/highlight.js#1569]
When highlighting Kotlin code, keywords in comment confuse the highlighter in some cases:

https://jsfiddle.net/juzraai/3w6ckxLo/

**Comment by yyyc514** [comment]
Works you actually load kotlin language:

https://jsfiddle.net/jrme1wh7/

Otherwise half the time you're getting parsed as Python.

**Comment by yyyc514** [comment]
@marcoscaceres @egor-rogov 

How would you feel about adding the full list of languages (just an array of strings) to the parser and when someone tries to use one that actually isn't present/registered it either logs to console or does something subtle.  I have a feeling this isn't the only issue like this.

The current behavior is it ignores the language you specified and instead tries to find the closest match in the built-in bundle, which often is not so great...

I'd suggest something more visible, but the worry would be breaking existing installs that might depend on the quiet, broken behavior.

**Comment by juzraai** [comment]
@yyyc514 Thank you for your help! It seems I missed the relevant part in the documentation:

> The CDN-hosted package doesn't have all the languages. Otherwise it'd be too big. If you don't see the language you need in the "Common" section, it can be added manually

I agree that a simple console (error) message would be great help in these cases, when I specify a language and forget to load its specific script.

**Comment by egor-rogov** [comment]
@yyyc514 Good idea, I like it. And I agree, it should be something visible.

**Comment by marcoscaceres** [comment]
Agree. Would be quite helpful.
