### ISSUE TITLE
Documentation is confusing

### ISSUE THREAD

**Issue by julio-pixelements** [highlightjs/highlight.js#1576]
http://highlightjs.readthedocs.io/en/latest/api.html#highlight-name-value-ignore-illegals-continuation

Listed arguments don't match with the signature. It's very confusing and I have to read the code to understand what the arguments are.

Edit: I just realized I confused input arguments with return value. It should be more clear. I suggest putting the "Returns an object..." sentence in a separate paragraph, and naming the first argument "language" or "language_name", the second "html_string", etc.

**Comment by yyyc514** [comment]
I'd settle for:

- languageName
- code

Would that not be clear?

**Comment by yyyc514** [comment]
Ping.
