### ISSUE TITLE
cdnjs missing https: from links on web page

### ISSUE THREAD

**Issue by pawal** [highlightjs/highlight.js#1580]
On the Download web page, the first examples on how to use cdnjs is missing https: in the links.

**Comment by yyyc514** [comment]
Are you referring to here? https://highlightjs.org/download/

Isn't `//` the new syntax to let the browser decide how to fetch it?

**Comment by yyyc514** [comment]
Ping. @pawal 

Could you please clarify?

**Comment by pawal** [comment]
This was over two years ago, I don't even recognize the website any longer.

However, the use of double slash is to let the browser decide on how to fetch it, but more explicitly, use the same protocol as whatever used to fetch the page it was coming from. So using http it will use http, not https.

**Comment by yyyc514** [comment]
> However, the use of double slash is to let the browser decide on how to fetch it, but more explicitly, use the same protocol as whatever used to fetch the page it was coming from. So using http it will use http, not https.

Which should be fine for a HTTP website, no?  I'm not sure I'm of the opinion that we should force people to use HTTPs if they don't want to.  I'm not sure this is a broken doc issue so much as "it's up to you to decide".

@egor-rogov Thoughts?

**Comment by egor-rogov** [comment]
Hm, no strong opinion, so I'm inclined to leave it as it is.

**Comment by yyyc514** [comment]
Closing as "no need for fix" then. :)
