### ISSUE TITLE
(typescript) declaration files parse incorrectly

### ISSUE THREAD

**Issue by DusterTheFirst** [highlightjs/highlight.js#1585]
when styling a declaration file, after a declared function, the syntax highlighting is gone, it may have something to do with it not containing a body
![image](https://user-images.githubusercontent.com/14093962/29085382-1cf428ce-7c3d-11e7-85cb-76bce4dc8ae8.png)

**Comment by yyyc514** [comment]
Yeah, I bet this is because we expect a `{`.  But I'd think it could be fixed.

Can you confirm it's still an issue and perhaps provider a jsfiddle example?

You can use my template:
https://jsfiddle.net/ajoshguy/nagkqytv/18/

**Comment by yyyc514** [comment]
Pretty sure this is still an issue but if you could provide the raw text instead of a snap that'd be super useful for us writing a test case.

**Comment by DusterTheFirst** [comment]
Heres a link
https://unpkg.com/browse/mechan.js@1.2.3/Command/Handler/CommandHandler.d.ts

And another
https://unpkg.com/browse/mechan.js@1.2.3/Command/Command.d.ts
