### ISSUE TITLE
Nested string interpolation is broken in TypeScript

### ISSUE THREAD

**Issue by pkaminski** [highlightjs/highlight.js#1590]
When trying to nest interpolated strings in TypeScript the string never gets "closed" and the rest of the code doesn't get properly formatted.  Here's a repro using highlight.js 9.12.0: https://jsfiddle.net/91twpfa2/3/  Note that this works correctly with the language set to JavaScript so hopefully just needs the relevant fix applied to the TypeScript language definition.

(Downstream bug report:  https://github.com/Reviewable/Reviewable/issues/498)

**Comment by levilansing** [comment]
I took a peek at this the other day. The typescript definition is missing the concept of substring nesting that exists in the Javascript language file.

Relevant lines in [languages/javascript.js](https://github.com/isagalaev/highlight.js/blob/master/src/languages/javascript.js#L52-L58) and [languages/typescript.js](https://github.com/isagalaev/highlight.js/blob/master/src/languages/typescript.js#L44-L47)

It'd be easier to see the difference if the typescript language file were refactored a little to match the JS file.

**Comment by rictic** [comment]
I forgot to mention it on the PR, but this should be fixed by #2105

https://jsfiddle.net/yd4ume3s/1/

**Comment by marcoscaceres** [comment]
Great! Closing as fixed by #2105.
