### ISSUE TITLE
A link inside the highlighted code block

### ISSUE THREAD

**Issue by stehuebn** [highlightjs/highlight.js#1592]
Hello,

is there a chance to make a link inside a code block? I need something like a reference link to another wiki article describing the reference class...

TIA,

Ste

**Comment by yyyc514** [comment]
Related:

https://github.com/highlightjs/highlight.js/issues/1603
https://github.com/highlightjs/highlight.js/issues/2126

Why can't you put the link outside the block?

**Comment by yyyc514** [comment]
> is there a chance to make a link inside a code block? 

Did you try this?  Seems to me like it might actually "just work".  The way you can embed HTML inside the code blocks is obviously a feature I need to learn more about.

**Comment by yyyc514** [comment]
@egor-rogov This `mergeStreams` stuff is just black magic. :-)

**Comment by egor-rogov** [comment]
@yyyc514 you've dug deeper than me into this (:

**Comment by yyyc514** [comment]
@egor-rogov I knew there was a whole portion of the codebase I'd pretty much ignored but I didn't imagine it would try and walk both strings and line up the HTML tags in the original while it skipped them in the parser... that's a very neat little trick and lets you do some pretty cool stuff. :-)
