### ISSUE TITLE
Event hooks on elements inside a block highlight.js has colored

### ISSUE THREAD

**Issue by aenon83** [highlightjs/highlight.js#1593]
I'm making a small documentation of a personal project in html and I'm using highlightjs for formatting my code.

In some lines I want to show some comments, so I put a span with a class that shows an exponent number, to indicate that you must look at the footer of the code. My code looks like this.
`<pre><code class="csharp">`
`line 1;`
`line 2 <span id="sup-legend-1" class="sup sup-hover">1</span>;`
`line 3;`
`</code></pre>`
`<div><span class="sup">1</span><span id="legend-1">Explanation of the code</span></div>`

The class `sup` is used to convert the number in an exponent and the `sup-hover` is going to fire the `.hover` event from jQuery. This event is goint to take the id `sup-legend-1`, look for the span with id `legend-1` and add a class to highlight it.

The problem is that the .hover event is not being fired, if I disable the highlightjs library it works, so I don't know if it is a conflict with jQuery.

**Comment by yyyc514** [comment]
https://github.com/highlightjs/highlight.js/issues/1603
https://github.com/highlightjs/highlight.js/issues/2126

This isn't currently possible and would probably be pretty difficult to implement.  How is Highlight.js supposed to guess what is really HTML and what should be highlighted?  Even CSHARP could contain perfectly valid HTML inside strings, etc.

**Comment by yyyc514** [comment]
> The problem is that the .hover event is not being fired, if I disable the highlightjs library it works, so I don't know if it is a conflict with jQuery.

Actually it seems this is a lot more possible than I thought, but your even needs to hook the WHOLE  pre/code block... not the individual ids... because Highlight.js *rewrites all that code*, so your event hooks are going to get destroyed.

On the other hand if you set the event on the pre/code and then when the event fires you check if it's hovered over a "legend" element then it should "just work".

**Comment by yyyc514** [comment]
Or you highlight first, THEN you run your code that hooks up the legends. (after  highlighting is finished).  That would probably work too.

**Comment by yyyc514** [comment]
Closing this as asked and answered.  If you have any other questions, feel free to ask! :-)
