### ISSUE TITLE
Highlight.js installion

### ISSUE THREAD

**Issue by pegasia** [highlightjs/highlight.js#1594]
Hello! I installed highlight.js on my website, its a tech blog site, after using `<pre><code class="html">...</code></pre>`
to test the code, it just treats it as text.. how would i fix this?

**Comment by yyyc514** [comment]
Please provide more details or a link to your site, etc... Or is this still an issue?

**Comment by yyyc514** [comment]
Closing for lack of response.  Feel free to respond whenever if your'e still having issues.  We're trying to clean out old issues.
