### ISSUE TITLE
Compiling with hljs variable?

### ISSUE THREAD

**Issue by simlu** [highlightjs/highlight.js#1595]
Regarding this issue: https://github.com/Tampermonkey/tampermonkey/issues/439

Is there an easy way to compile highlight.js with the hljs variable explicitly exposed as done before version 8.4?

**Comment by lukas-gitl** [comment]
This was a bug in tamper-monkey that has been fixed.

**This can be closed now!**

**Comment by yyyc514** [comment]
@marcoscaceres Please close.
