### ISSUE TITLE
New language request procedure

### ISSUE THREAD

**Issue by jf990** [highlightjs/highlight.js#1596]
documented at http://highlightjs.readthedocs.io/en/latest/language-requests.html states

> project works by accepting language definitions from interested contributors. There are also no rules at the moment forbidding any languages from being added

I've had a PR in since November 2016 #1371 that is till untagged and unmerged. so what is the proper procedure to get a new language looked at? we've been waiting, and due to node dependencies there's no solution for us other than to get this merged into this repo.

**Comment by larshp** [comment]
Same issue in https://github.com/isagalaev/highlight.js/pull/1259

Looking at the last month, 2 PRs was opened, and 11 issues. Is help needed for maintaining the project? I'm sure some people in the community will step up and help if needed.
