### ISSUE TITLE
About Perl 6 support

### ISSUE THREAD

**Issue by sumanstats** [highlightjs/highlight.js#1602]
Hi,

Now as Perl 6 has entered into production and is a mature language, we love to see support for Perl 6 in
this awesome syntax highlighting library.

Best,
Suman

**Comment by kawaii** [comment]
+1 for Perl 6 support.

**Comment by yyyc514** [comment]
Lets close this in favor of:  https://github.com/highlightjs/highlight.js/issues/1674  We only need one issue to track this.

@marcoscaceres
