### ISSUE TITLE
[SQL] Add Support for 'varchar2'

### ISSUE THREAD

**Issue by ar0ra1** [highlightjs/highlight.js#1604]
Varchar changes to red but varchar2 doesn't

![sql](https://user-images.githubusercontent.com/20777462/30604366-28edda1a-9d5a-11e7-9359-220cf53a33ef.png)

**Comment by yyyc514** [comment]
Could you make a PR for this?

**Comment by yyyc514** [comment]
Is this in the SQL standard, Postgres, MySQL or both?

**Comment by ar0ra1** [comment]
It is Oracle. 

Oracle suggests the use of varchar2 over varchar.

**Comment by yyyc514** [comment]
I'd add it as just a built_in to the basic SQL then.  

https://github.com/highlightjs/highlight.js/blob/master/src/languages/sql.js

**Comment by yyyc514** [comment]
Believe this was just merged.

**Comment by yyyc514** [comment]
https://github.com/highlightjs/highlight.js/pull/2163
