### ISSUE TITLE
Syntax highlighting for gettext po files

### ISSUE THREAD

**Issue by archatas** [highlightjs/highlight.js#1607]
Hello! I find highlight.js a very mature and useful tool. But I found a language that is missing: that's gettext *.po files. I would be very glad if someone added it to the script.

**Comment by adeelshahid** [comment]
@ararslan try language mode *lsl* where you find *po* or *pot* files. I tried adding POT file language but during _npm test_ highlight.js automatically detects lsl

```
  1) hljs.highlightAuto() should be detected as pot:

      AssertionError: expected 'lsl' to be 'pot'      
      actual expected
```

**Comment by ararslan** [comment]
@adeelshahid, did you mean to ping me or were you looking for @archatas, who opened this issue?

**Comment by adeelshahid** [comment]
@ararslan sorry about that blind autocomplete, meant to refer to @archatas

**Comment by archatas** [comment]
@adeelshahid Sorry, I didn't understand what you are suggesting. Neither "pot", nor "lsl" is listed in the supported languages: https://highlightjs.org/static/demo/

**Comment by archatas** [comment]
@adeelshahid Oh. Now I got it. This language (lsl) exists in the repository, but not in the demo.
