### ISSUE TITLE
(cpp) [cpp11] std::future not highlighted

### ISSUE THREAD

**Issue by externl** [highlightjs/highlight.js#1610]
> Highlight.js 9.12.0

Compare the two following lines:

![std future](https://user-images.githubusercontent.com/2126835/31238807-090bcc54-a9c9-11e7-93fa-43455b342359.png)

The highlighting of `std::shared_ptr` is correct, but `std::future` is wrong. `future` should be colored as well.

**Comment by yyyc514** [comment]
@externl I Think you'd just need to add `future` to the list of built_ins if it's a built in now.  Could you make a PR for that?
