### ISSUE TITLE
Suggestion: dns.js.org support

### ISSUE THREAD

**Issue by PointyDev** [highlightjs/highlight.js#1617]
Hey there,

Was possibly thinking there could be a gh-pages site that redirected to the from `highlight.js.org` to the main [`highlightjs.org`](https://highlightjs.org) site. [js.org](https://js.org) provide free subdomains for open source projects, might be cool if there was a lil redirect there. Check it out over at [dns.js.org](https://dns.js.org).

Thanks,
Pointy

**Comment by yyyc514** [comment]
@marcoscaceres @egor-rogov Unless either of you care a lot about this I'm going to simply close... Doesn't seem necessary or that helpful to me.

**Comment by yyyc514** [comment]
@PointyDev Thanks for the suggestion though.
