### ISSUE TITLE
(?clarify?) [[]] strings are not highlighted 

### ISSUE THREAD

**Issue by mohaiminalaoun** [highlightjs/highlight.js#1624]
This happens with file names such as 'sample-retail.xls', where the word `sample` is highlighted even though it's a part of a file's name `retail-sample-data.xls` 

Here's a jsfiddle example.

http://jsfiddle.net/25maz9x4/1/

**Comment by yyyc514** [comment]
This is expected behavior (currently) as the SQL syntax is a simple keyword highlighter.  Someone would have to write a MUCH more complex SQL syntax that knew a lot more about the ins and outs of the full SQL specification to resolve this.

**Comment by yyyc514** [comment]
Curious: What variant of SQL are you using with filenames like that?

**Comment by mohaiminalaoun** [comment]
We're using PostgreSQL. File names selected by user.

**Comment by yyyc514** [comment]
I don't understand. Is [] some type of alternative quoting syntax?

**Comment by egor-rogov** [comment]
These square brackets looks like MS SQL Server. So makes sense to try `tsql`: https://github.com/highlightjs/highlightjs-tsql

**Comment by yyyc514** [comment]
Well, if it's just a quoting issue we can probably fix that.

Reference: https://github.com/highlightjs/highlightjs-tsql/blob/master/src/languages/tsql.js#L2661

**Comment by yyyc514** [comment]
@mohaiminalaoun Want to try your hand at a PR?

**Comment by egor-rogov** [comment]
This is not standard quoting, we shouldn't fix it in `sql`.

**Comment by yyyc514** [comment]
@mohaiminalaoun Does this work if you use the pgsql syntax?

**Comment by egor-rogov** [comment]
PostgreSQL doesn't allow it either. It's specific to Microsoft AFAIK.

**Comment by yyyc514** [comment]
Oh well they specifically said they are using Postgres.... this is why we need a maintainer per language. ;-)

**Comment by yyyc514** [comment]
@mohaiminalaoun I looked on Google quickly but found nothing.  If this is Postgres syntax please link us to a reference or something.  Or perhaps double check if you aren't using a different SQL?

**Comment by mohaiminalaoun** [comment]
@yyyc514 I apologize. Looks like we had been using MS SQL Server at that time.

**Comment by yyyc514** [comment]
You should try `tsql` then as Egor linked to and you'll probably have much better luck:

https://github.com/highlightjs/highlightjs-tsql

**Comment by yyyc514** [comment]
Closing, recommendation is to try tsql.
