### ISSUE TITLE
(python) comments in function parameter lists not highlighted

### ISSUE THREAD

**Issue by jboning** [highlightjs/highlight.js#1627]
With 9.12.0:
```
def foo(
      x=1, # comment not highlighted properly
  ):
  pass
```
Jsfiddle repro (with a normal comment for comparison, and a quote to demonstrate why this can be painful): http://jsfiddle.net/c5ac72fe/5/

**Comment by yyyc514** [comment]
Reproduced:

https://jsfiddle.net/ajoshguy/gc9f3548/

This is probably fixable by telling the grammar to expect possible comments in the argument lists...
