### ISSUE TITLE
Pasting in OneNote will not preserve the line break

### ISSUE THREAD

**Issue by tamlok** [highlightjs/highlight.js#1635]
Copy the code block from highlight.js demo and paste it in OneNote. The code block will be changed into single line.

![image](https://user-images.githubusercontent.com/5763157/32813708-6061f4a0-c9e6-11e7-944b-1d700b705733.png)

**Comment by yyyc514** [comment]
I don't have OneNote, but I've heard no other issues similar to this and cutting and pasting just now from a block into VS Code has no issues at all. 

Perhaps this is a bug with OneNote?

What if you paste it into a text editor or Notepad or such on your computer, are the line breaks preserved then?

**Comment by yyyc514** [comment]
Weekend ping.

**Comment by tamlok** [comment]
Hi,

Time flies (2 years ago :))!

If I select the code block like this:

![image](https://user-images.githubusercontent.com/5763157/66723866-1266cf00-ee51-11e9-9c3e-99b9caa5b247.png)

The result is:

- OneNote: No
- Word: Yes
- Notepad++: Yes

If I select one more line like this:

![image](https://user-images.githubusercontent.com/5763157/66723876-40e4aa00-ee51-11e9-8abf-e72594d667d2.png)

Then OneNote works, too.

![image](https://user-images.githubusercontent.com/5763157/66723881-5063f300-ee51-11e9-8423-00166d14cacf.png)

I think it is caused by some CSS stylesheet difference between OneNote and web. That is fine.

**Comment by yyyc514** [comment]
Weird.  I dunno if it has anything to do with CSS.  Sounds like a bug in OneNote though if it works in Word and Notepad++ - and sadly we can't fix OneNote bugs.  Closing this.

Out of curiosity, which web browser are you using?  Have you tried a different browser to see if it makes a difference?

If you keep poking around and find some sort of CSS fix that is within our power, please let us know.

**Comment by tamlok** [comment]
I use QtWebEngine, which is based on Chromium, and Chrome itself.

Change to `inline-block` will solve this in OneNote, though I am not sure if it is proper.

![image](https://user-images.githubusercontent.com/5763157/66723995-d7fe3180-ee52-11e9-9cec-7439a1ca7aef.png)

**Comment by yyyc514** [comment]
Well traditionally code snippets are a block, not an inline-block - so I don't think that's something we can just change.  That's very strange that that would fix it though.

**Comment by yyyc514** [comment]
I'd suggest filing a support issue with OneNote.
