### ISSUE TITLE
Swift doesn't seem to work...

### ISSUE THREAD

**Issue by leifashley** [highlightjs/highlight.js#1636]
In my HTML:

```
<pre><code class="swift">
public extension Date {
	
	/// SwifterSwift: Day name format.
	///
	/// - threeLetters: 3 letter day abbreviation of day name.
	/// - oneLetter: 1 letter day abbreviation of day name.
	/// - full: Full day name.
	public enum DayNameStyle {
		case threeLetters
		case oneLetter
		case full
	}
}
</code></pre>
```

From Chrome console:

> highlight.pack.js:2 Uncaught SyntaxError: Invalid regular expression: /\b[A-Z][\wÃ€-Ê¸']*/: Range out of order in character class
>     at new RegExp (<anonymous>)
>     at t (highlight.pack.js:2)
>     at r (highlight.pack.js:2)
>     at highlight.pack.js:2
>     at Array.forEach (<anonymous>)
>     at r (highlight.pack.js:2)
>     at s (highlight.pack.js:2)
>     at f (highlight.pack.js:2)
>     at d (highlight.pack.js:2)
>     at NodeList.forEach (<anonymous>)

**Comment by yyyc514** [comment]
The content is UTF-8... your web server needs to send the correct headers... or you can fix it i your html:

```
<script
 charset="UTF-8"
 href="...">
```
