### ISSUE TITLE
Add ReasonML support

### ISSUE THREAD

**Issue by thangngoc89** [highlightjs/highlight.js#1666]
Site: https://reasonml.github.io

ReasonML is just a syntax on top of Ocaml. All the semantic underneath remain the same

**Comment by thangngoc89** [comment]
I found this 

https://github.com/rickyvetter/resaurus/blob/master/index.js

It's what the ReasonML's docummentation is using for highlighting.

**Comment by egor-rogov** [comment]
Already there: #1793
