### ISSUE TITLE
Disable specific tag?

### ISSUE THREAD

**Issue by hackjutsu** [highlightjs/highlight.js#1667]
Can we disable some specific tag, like `<span class="hljs-doctag">`? I mean no longer wrap this tag around `@param`. Thanks!

**Comment by yyyc514** [comment]
I'm not sure what you are asking, can you please me a little more specific or give an example:

- EXACTLY what Highlight.js does now
- EXACTLY what you would prefer it do instead

**Comment by yyyc514** [comment]
Can't you do the same thing with CSS by adding a style that resets the color so it just doesn't appear visually any different?

Also can you explain what the use case for such a feature might be, why you need it or don't want doctags to be highlighted?

If you're open to editing the source of Highlight.js itself you could just muck with the global doctag rule I think.

**Comment by yyyc514** [comment]
Ping.

**Comment by yyyc514** [comment]
Closing as asked and answered.  Feel free to respond if there is still a question here.
