### ISSUE TITLE
Problem with quotes in Matlab (seems still have bug)

### ISSUE THREAD

**Issue by silverHugh** [highlightjs/highlight.js#1669]
The `highlight.js` version I use is `9.12.0`, and the example code is shown below.

``` matlab
%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%  Vectors and matrices %%
v = [1 2 3]
v'             % conjugate transpose
v.'            % transpose
v = 1:0.1:2    % from 1 to 2, with stepsize of 0.1. Useful for plot axes
v = 1:6        % from 1 to 6, assumes stepsize of 1
v = linspace(1,6,6)
A = [1 2; 3 4; 5 6]
```

The highlighting result is not correct as shown in the picture, which can be also seen by visiting https://memoex.github.io/note/matlab/

<img width="559" alt="matlab" src="https://user-images.githubusercontent.com/10184905/34398545-bd48fbb4-ebba-11e7-9d23-da079988fe2e.png">

**Comment by JohnC32** [comment]
This is fixed by changing line 13 in src/languages/matlab.js from

       begin: '\'', end: '\'',

to

       begin: '\'' to begin: /\B(\')/

Could someone make this change? Thanks.

**Comment by egor-rogov** [comment]
Fixed, but other way. @JohnC32 could you test this PR?

**Comment by JohnC32** [comment]
Hi

I saw you updated the tip. Thanks. This does work much better than before. However, it doesn't handle all cases - see example below and desired result in snap.png. MATLAB now supports two types of strings double quotes "strings" and single quote 'strings'. I'm not familiar with the internals of highlightjs, thus not sure what the correct solution is.

    % This use of ' is for transpose:
    mat2x2 = [1 2; 3 4]';  % transpose of a matrix
    cell2x2 = {1 2; 3 4}'; % transpose of a cell
    v=mat2x2';             % transpose of a variable
    v2 = (v')';            % two transpose operations
    foo = 1.';             % transpose of scalar 1.
    
    % single quote strings:
    sq1 = 'a single quote string';
    sq2 = ...
    ' abcd ';         % single quote string starting at column 1
    sq3 = ['a','bc']; % array of single quote strings
    sq4 = {'a','bc'}; % cell of single quote strings
    
    % double quote strings
    dq1 = "a double string";
    dq2 = ...
    " abcd ";         % double quote string starting at column 1
    dq3 = ["a","bc"]; % array of double quote strings
    
    % Mixture of strings and transpose
    c2 = {'a','bc'}'; % transpose of a cell of strings
    s = ['a','bc']';     % you can transpose vectors of strings (they are really 'char' arrays)
    s = s';           % and transpose back
    % (s')' is a double transpose of a string
    x = [(s')', ' xyz ', 'a single quote in a string'', two quotes in a string'''''];  
    
    s2 = "abc";     % newer versions of MATLAB support double quoted strings
    s3 = (["abc", "defg"]')';  % transpose a vectors of quoted string twice
![snap](https://user-images.githubusercontent.com/18011314/46323812-1dd8b680-c5be-11e8-8254-6ba464d87af8.png)

**Comment by JohnC32** [comment]
To get the double quote strings working, if you updating line 13 to be

    begin: '(\'|")', end: '(\'|")',

somewhat works, but this confuses the start and ending, i.e. the following is wrong. It thinks
most of the comment is part of the string.

    x3 = "foo ' ";  % double quote string containing a ' char
To get the double quote strings working, if you updating line 13 to be

    begin: '(\'|")', end: '(\'|")',

somewhat works, but this confuses the start and ending, i.e. the following is wrong. It thinks
most of the comment is part of the string.

    x3 = "foo ' ";  % double quote string containing a ' char

Is the right approach to define two different string types, single quote strings and double quote
strings?

**Comment by egor-rogov** [comment]
@JohnC32 Yes, I think two different string types is the right way to go. I gonna look into this on the weekend.

**Comment by egor-rogov** [comment]
@JohnC32 Thanks for the extensive example, I have used it as a test case with some additions. I believe it should work now.

**Comment by marcoscaceres** [comment]
Thanks for checking @JohnC32. Closing.
