### ISSUE TITLE
Color sintax isn't works

### ISSUE THREAD

**Issue by PedroFumero** [highlightjs/highlight.js#1671]
I start to test highlight.js, but sintax color isn't works, I have done follows: 

1- Clone repo 
2- Inside repo folder create an index.html file with a basic html structure and add some javascript code

```
<!DOCTYPE html>
<html>
<head>
<title>Prueba</title>
<link rel="stylesheet" href="./src/styles/atom-one-dark.css">
<script src="./src/highlight.js"></script>

</head>
<body>
<pre><code class="javascript">
function $initHighlight(block, cls) {
  try {
    if (cls.search(/\bno\-highlight\b/) != -1)
      return process(block, true, 0x0F) +
             ` class="${cls}"`;
  } catch (e) {
    /* handle exception */
  }
  for (var i = 0 / 2; i < classes.length; i++) {
    if (checkCondition(classes[i]) === undefined)
      console.log('undefined');
  }
}
export  $initHighlight;
</code></pre>

<script>hljs.initHighlightingOnLoad();</script>
</body>
</html>
```

3- Then, when I try to test a style (darcula, github,atom-one-dark), sintax colors isn't works, background color works fine, but sintax is not.

I have done something wrong?

A picture is worth a thousand words: [Capture](https://image.prntscr.com/image/l93hyr1eS3ioe_guyUnloQ.png)

**Comment by yyyc514** [comment]
Sorry for no response.  Are you still having troubles?
