### ISSUE TITLE
DM grammar (needs package & maintainer)

### ISSUE THREAD

**Issue by Redict** [highlightjs/highlight.js#1673]
There's [BYOND](http://byond.com) game platform and there's [DM](http://www.byond.com/docs/ref) language to make your own games on it.

**Comment by yyyc514** [comment]
@Redict Currently any new languages are living in their own repos - but if we have maintainers we're happy for that repo to have a home at the `highlighjs` organization.  So if you or the original author wanted to be that maintainer and move this grammar into it's own repository that'd be great!

**Comment by yyyc514** [comment]
Closing in favor of https://github.com/highlightjs/highlight.js/pull/1917.

If the original author is no long around any chance you'd want to step up and become the official maintainer of a 3rd party language module for DM/BYOND?
