### ISSUE TITLE
linebreak is not working in react.js 

### ISSUE THREAD

**Issue by ShawnBaek** [highlightjs/highlight.js#1675]
Here is snippet of my code.

import hljs from 'highlight.js/lib/highlight';

 componentDidMount(){
        document.querySelectorAll('code').forEach((block) => {
            hljs.highlightBlock(block);
        });

        ['javascript', 'swift', 'bash'].forEach((langName) => {
            // Using require() here because import() support hasn't landed in Webpack yet
            const langModule = require(`highlight.js/lib/languages/${langName}`);
            hljs.registerLanguage(langName, langModule);
        });

        
    }

 componentDidUpdate(){
        // Prism.highlightAll();

        document.querySelectorAll('code').forEach((block) => {
            hljs.highlightBlock(block);
        });

    }

 <article 
                        dangerouslySetInnerHTML={ { __html: postContents } }>
                    </article>

<img width="866" alt="screen shot 2018-01-09 at 12 13 05 am" src="https://user-images.githubusercontent.com/12643700/34678069-5f2ecfbc-f4d5-11e7-958d-694ab9804a6d.png">

**Comment by yyyc514** [comment]
This might not be a highlight.js issue but an issue with some other components not working will with highlight.js.  If you think this is still an issue please provide us a reproducible test case with a jsfiddle and we can look into it.

You can use my template:
https://jsfiddle.net/ajoshguy/nagkqytv/18/

**Comment by yyyc514** [comment]
Closing this (no response).  We're trying to clear out old, stale issues - to better focus on what's still an actual issue.

If you do still have an issue please provide an example as requested and we'll happily re-open!
