### ISSUE TITLE
Update highlighting

### ISSUE THREAD

**Issue by TheFlow95** [highlightjs/highlight.js#1677]
Hi,

I want to update highlighting on key up (text editor), so I tried to do this:

```
function highlight() {
	hljs.initHighlighting.called = false;
	$('#text-content').each(function(i, block) {
		hljs.highlightBlock(block);
	});
}

$('#text-content').keyup(function(e) {
	highlight();
})
```

But this is not working and the cursor is set back to first position.

How can I do it?

Thanks

**Comment by yyyc514** [comment]
> But this is not working and the cursor is set back to first position.

That's what's going to happen as you're replacing the full content each time.  You'd have to save the cursor and try to put it back yourself - not sure how much luck you'll have with that.

Are you sure `highlightBlock` is intended to be called multiple times for the same thing?  That'd be where to spend your time looking.

**Comment by yyyc514** [comment]
Following the example from the other thread:

> This is unfortunately outside the scope of this library.

Highlight.js is not intended for usage as a real-time code editor.  Good luck if you get it working, but we can't support that.
