### ISSUE TITLE
Mediawiki Syntax support?

### ISSUE THREAD

**Issue by EoD** [highlightjs/highlight.js#1682]
Would it be possible to add MediaWiki syntax support?

Some highlighting for common wiki-code like (random page): https://en.wikipedia.org/w/index.php?title=Johnny_Johns&action=raw

Or some template code: https://en.wikipedia.org/w/index.php?title=Template:Yesno&action=raw

**Comment by ldct** [comment]
hi @EoD , we can review and merge PRs with language implementations but won't be able to actually implement all the requested languages.

see http://highlightjs.readthedocs.io/en/latest/language-requests.html for more details.
