### ISSUE TITLE
Escape characters stripped in CDN version

### ISSUE THREAD

**Issue by Floofies** [highlightjs/highlight.js#1687]
After I noticed several broken web pages in my projects, I began to investigate and found the cause to be several modules which were imported from cdnjs.com. Upon closer inspection, I determined that the minified source code did not match the original source code, because **critical escape characters have been removed in the minified source code.**

Of the affected modules I discovered, I found these responsible for breaking my web pages:
[https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/languages/xml.min.js](xml.min.js)
[https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js](highlight.min.js)

After checking the same modules on jsdelivr.net, I have found the same issue.

Specifically, there are `<\/script>` strings in the source code which have their backslashes removed from the documents, causing the browser to end `<script>` elements earlier than it should.

I have verified that the original source code does indeed contain the backslashes, and I cross-checked the release version with this repository based on commit, therefore the only possible cause left is the process in which these files are minified.

**Comment by yyyc514** [comment]
Can you confirm this is still an issue with latest version on CDN?

**Comment by Floofies** [comment]
I think the issue is now resolved. I have inspected the version 9.15.10 source code on the CDN and it appears to be corrected now. I also crosschecked the source code on the CDN with the source code of the 9.15.10 release commit tree for good measure. :)

**Comment by yyyc514** [comment]
Thanks!
