### ISSUE TITLE
Could not get Rust code hightlighted 

### ISSUE THREAD

**Issue by ramsayleung** [highlightjs/highlight.js#1705]
![screenshot_2](https://user-images.githubusercontent.com/14180681/36844134-723b1824-1d8c-11e8-9495-f71f845be7dc.png)

![screenshot_3](https://user-images.githubusercontent.com/14180681/36844137-78b02154-1d8c-11e8-94d2-bfb1b4a0df76.png)
(never mind the Chinese words)
As the screenshot shows, it is so weird that `hightlight.js` could highlight Python code, but could not work with the Rust code. This is my [website](http://samray.xyz/rspotify---%E6%88%91%E7%9A%84%E7%AC%AC%E4%B8%80%E4%B8%AARust%20crate), is there something wrong with my website?

**Comment by yyyc514** [comment]
Are you loading the rust.js syntax? I don't think it's built-in.

**Comment by yyyc514** [comment]
If you're still having issues a reproducible example fo this not working would be great, such as a jsfiddle, etc...

You can even fork my template:
https://jsfiddle.net/ajoshguy/nagkqytv/18/

**Comment by ramsayleung** [comment]
> Are you loading the rust.js syntax? I don't think it's built-in.

Where should I find the info about `rust.js`, it seems the official doc doesn't make mention of the `rust.js` syntax file

**Comment by yyyc514** [comment]
https://highlightjs.org/usage/

Read Getting Started and Getting the library.  You need to add a second JS script tag or else build a custom library that includes Rust.

**Comment by ramsayleung** [comment]
It works now, thanks so much for your help.

**Comment by yyyc514** [comment]
Glad to help!
