### ISSUE TITLE
Bug: Do not highlight if auto-detection is turned off

### ISSUE THREAD

**Issue by zemanlx** [highlightjs/highlight.js#1709]
I have turned off autodetection as mentioned in https://github.com/isagalaev/highlight.js/issues/415 by @isagalaev 

```javascript
      hljs.configure({
        languages: [] // Turn-off autodetection
      })
      hljs.initHighlightingOnLoad();
```
and adding language in `code class` as mentioned in [Usage](https://highlightjs.org/usage/)

```html
<code class="JSON">{
  "userName": "test",
  "password": "password"
}</code>
```

But I am not getting any highlighting

![image](https://user-images.githubusercontent.com/18702153/37146873-f0012c14-22bc-11e8-9715-1c39b8894176.png)

Is there anything I am doing wrong?

**Comment by yyyc514** [comment]
Well all the examples specifically have the language in lowercase.  Did you try `json`?

**Comment by zemanlx** [comment]
@yyyc514 it the same with lowercase `json`

**Comment by yyyc514** [comment]
Could it be your CDN or web setup? Seems to be working for me:

https://jsfiddle.net/v2j1a85n/3/

**Comment by zemanlx** [comment]
Interesting. It also works for me in `jsfiddle`. Looks like this is not behaving properly when I run it locally for testing. Anyway, thanks for your time!
