### ISSUE TITLE
Can anyone help me document .properties syntax

### ISSUE THREAD

**Issue by bostko** [highlightjs/highlight.js#1713]
I'd like to be able to support https://en.wikipedia.org/wiki/.properties format.
Could you point me at similar `language/*.js` file for reference?

**Comment by jolkdarr** [comment]
Hi

Have you studied `ini` syntax?
Doc at: https://en.wikipedia.org/wiki/INI_file

**Comment by yyyc514** [comment]
@marcoscaceres Another merged item we can close out.

**Comment by yyyc514** [comment]
Thanks!
