### ISSUE TITLE
(csharp) "where" keyword is not recognized as constraint

### ISSUE THREAD

**Issue by superyyrrzz** [highlightjs/highlight.js#1714]
Here's an example:
```cs
public class TesterA<R, S>  where R : class where S : IComparable
```
Rendered  result:
![image](https://user-images.githubusercontent.com/3831744/37749868-faf759e6-2dc4-11e8-8148-51fe19699f9f.png)

**Comment by KristianWedberg** [comment]
This (i.e. constraints and base class keywords should be colored as keywords) is still an issue, any chance it will be addressed?

**Comment by marcoscaceres** [comment]
Hi @KristianWedberg or @superyyrrzz, as we have limited people maintaining the project, we rely on the community to help us with maintaining the languages themselves. Would you be willing to have a look at the language file and add "where" as a keyword if its missing? Most language files are pretty easy to change and logically organized.

**Comment by KristianWedberg** [comment]
I took a quick look, and the `where` and `class` keywords are already present in the language file. Despite this, the neither `where` nor `class` gets highlighted when used as _constraints_, even though `class` gets highlighted as part of `public class`.

Debugging this is a bit beyond me, any ideas what might cause this?

**Comment by marcoscaceres** [comment]
@KristianWedberg thanks for taking a look. Not sure what might be causing it. Will leave this open in the hope someone else picks it up.

**Comment by yyyc514** [comment]
```js
      {
        beginKeywords: 'class interface', end: /[{;=]/,
        illegal: /[^\s:,]/,
        contains: [
          hljs.TITLE_MODE,
          hljs.C_LINE_COMMENT_MODE,
          hljs.C_BLOCK_COMMENT_MODE
        ]
      },
```

class starts a match and doesn't stop until it hits `{`,`;`, etc... and only matches title, or comments... so it won't match keywords.  Someone would have to extend this matcher to also match class related keywords.
