### ISSUE TITLE
How does it play with other highlighters

### ISSUE THREAD

**Issue by cabonamigo** [highlightjs/highlight.js#1718]
I am trying to adapt it for use with PmWiki, but I don't know how can I make it play nice with other highlighters on the same page. Can I make it load and run for just one "pre code" block?

Do you any option for line numbering?

The pmwiki markup I am trying to acomplish is this:

[highlight id=myid(used to id a block) language=xxxxxx(some language id) theme=xxxxx(HL theme to be loaded for the block) linenum=1(self explanatory) @(here is where the code starts) 

# this is code to be highlighted
function HighlightLineNun($c){
  return LineNum($c);
}

echo LineNum($c);

@](the final markup tag)

**Comment by yyyc514** [comment]
Sure, just manually call `highlightBlock` on what you'd like to be highlighted.

**Comment by yyyc514** [comment]
Just look at how the code already applies highlighting when you call init:

```js
function initHighlighting() {
    if (initHighlighting.called)
      return;
    initHighlighting.called = true;

    var blocks = document.querySelectorAll('pre code');
    ArrayProto.forEach.call(blocks, highlightBlock);
  }
```

**Comment by yyyc514** [comment]
Themes are global for Highlight.js though, so specifying a theme per block currently would make no sense.  Let us know if you have any other questions. 

Closing as asked and answered.
