### ISSUE TITLE
Support PlantUML and Graphviz Dot

### ISSUE THREAD

**Issue by tamlok** [highlightjs/highlight.js#1726]
Hi, could you please support highlight of **PlantUML** and **Graphviz Dot** for their popularity?

Thanks!

**Comment by XadillaX** [comment]
+1

**Comment by ldct** [comment]
hi @tamlok , we can review and merge PRs with language implementations but won't be able to actually implement all the requested languages.

see http://highlightjs.readthedocs.io/en/latest/language-requests.html for more details.

**Comment by MadEmperorYuri** [comment]
@tamlok I myself need support for DOT, and I may be able to implement it myself at some point. No promises, but if I ever actually do it, it will appear in my fork of highlight.js. GitHub enables to you 'watch' repositories so that you are notified if something happens to them. So if you watch my fork, then, if I ever implement it, you will automatically get a notification.

**Comment by tamlok** [comment]
@MadEmperorYuri Thanks!

**Comment by DanielFlaum** [comment]
Not on my end, @mbana, sorry. I ended up getting re-prioritized onto a different project. But I will try to pick up implementing a DOT plugin for highlight.js in my spare time.

My plan is to adapt [the DOT grammar from this plugin for the Atom text editor](https://github.com/AdoPi/language-dot/blob/master/grammars/dot.cson) into the format that highlight.js takes, like [this one for CSS](https://github.com/highlightjs/highlight.js/blob/master/src/languages/css.js).

It doesn't look like it will be very simple, but that DOT plugin at least provides a starting point.

**Comment by magjac** [comment]
This could also be of help:
https://github.com/ajaxorg/ace/blob/master/lib/ace/mode/dot.js
https://github.com/ajaxorg/ace/blob/master/lib/ace/mode/dot_highlight_rules.js

**Comment by HighlyHylian** [comment]
Currently desiring support for plantUML. Any updates? I could begin work on it myself if needed later this year.

**Comment by tamlok** [comment]
I already turned into prism.js :)
