### ISSUE TITLE
Request: Class names aren't recognized types

### ISSUE THREAD

**Issue by cppcooper** [highlightjs/highlight.js#1729]
It would be *nice* if class names were added to the keyword list upon first highlight.

**Comment by yyyc514** [comment]
I think I know what you mean, but can you please give a specific example?

**Comment by cppcooper** [comment]
Unfortunately this was so long ago that I've forgotten what I was even doing with this. I suspect it was for my website, but I don't remember working on it at all in 2018.

I suspect it had to do with this project not interpretting words as types in situations that they clearly should have been. `class WordThatShouldBeAType` or perhaps subsequent uses of the new type.

You probably have a better idea than I do. Sorry I didn't document this properly.

**Comment by yyyc514** [comment]
Yeah, the parser has no memory.  Not sure if that is a desire or not.  No way to do that kind of thing without a memory of which tokens you've seen before in which contexts, etc.

Thanks for responding. :-)
