### ISSUE TITLE
Function calls in javascript not being highlighted

### ISSUE THREAD

**Issue by Nokel81** [highlightjs/highlight.js#1731]
Currently function calls (notably in javascript) are not being highlighted differently than other statements. I think that this is a mistake

**Comment by yyyc514** [comment]
You meant the calls themself?

```
// call doSomething
doSomething(3,2,"Hello")
```

This has always been a purposeful omission.  Traditionally we've valued consistency also... so it would be a massive amount of effort right now to do this for EVERY core language all at once... so this probably stands more of a chance once grammars are all broken out into smaller repos and have their own community and maintainers who could make those types of decisions.

**Comment by yyyc514** [comment]
@Nokel81 To push this forward for Javascript (or any other language at the moment) the best way would be to find a few people interested in maintaining the Javascript grammar and then fork that into it's own repo and make those improvements there.

Then we could discuss the value in that new repo becoming the defacto "JS" that's bundled by default with Highlight.js.  I think that's how these types of discussions are going to move forward in a meaningful way - by people to show they are willing to put in the effort to maintain these things.  That's currently the problem in core.  Too many grammars, too little time and maintainers.  So you can imagine the hesitancy to add even more features that will break, require maintenance, etc...

At the very least people would have a choice and could use the built-in one or decide to use the enhanced version and all it offers.  

Personally I'm interested in a slightly "more complex" JS highlighter and have been playing with the idea personally... so I'd be happy to be part of that group of people if they exist.

**Comment by ChristianIvicevic** [comment]
For training material and a lot of code that I am writing, I am in the process of migrating over from Markdown to AsciiDoc. Missing some of the highlighting I had previously is really noticeable as you can see in this example:

<img width="538" alt="Screenshot 2019-10-12 at 19 28 42" src="https://user-images.githubusercontent.com/45569997/66705407-86588880-ed26-11e9-879a-eaf713756466.png">

<img width="567" alt="Screenshot 2019-10-12 at 19 29 06" src="https://user-images.githubusercontent.com/45569997/66705409-95d7d180-ed26-11e9-9f3f-1cf41efd824b.png">

The same code snippet is more difficult to read (which is highly subjective of course) and I personally appreciate the distinction of classes/types from object members etc. which is helpful for beginners to distinguish various code elements.

**Comment by yyyc514** [comment]
Maybe would have made a better comment over on #1378 

The problem is we're not a full parser... we have no ideas those things are classes or types... they are just words... is that Typescript with `is` and `as`?

If so it might be possible to highlight them when they are mentioned after an `is` or `as`...

**Comment by ChristianIvicevic** [comment]
@yyyc514 I moved the discussion with my input over to #1378.
