### ISSUE TITLE
Possible to disable auto highlight for undefended languages

### ISSUE THREAD

**Issue by BenjaminHoegh** [highlightjs/highlight.js#1737]
Is it possible to disable auto highlight for undefended languages

Example as default this gets highlighted:

    ```
    Hello World
    ```

but i want to make so its only highlight if i write:

    ```html
    Hello World
    ```

**Comment by tovic** [comment]
Add a `no-highlight` class to all `<code>` tag without classes before highlighting:

~~~ .js
document.querySelectorAll('pre code:not([class])').forEach(function($) {
    $.className = 'no-highlight';
});
hljs.initHighlighting();
~~~

**Comment by yyyc514** [comment]
> Is it possible to disable auto highlight for undefended languages

Or just add "plaintext".  Which effectively would do the same thing without requiring any fancy JS code.  Since there are already several easy ways of doing this I'm closing this issue.
