### ISSUE TITLE
Bash highlighting erroneously bolds "set" when used as an argument to a bash command

### ISSUE THREAD

**Issue by tygern** [highlightjs/highlight.js#1740]
When a common bash command is included in an argument to another command, highlightjs unnecessarily bolds the command. For example, applying highlighting to the following html
```html
<pre><code class="bash">fly set-pipeline --help</code></pre>
```
results in "set" appearing in bold, which should not be the case.

See [this codepen](https://codepen.io/anon/pen/deNOvQ) for an example.

**Comment by yyyc514** [comment]
That's just how the highlighter works... unless it's already matching a specific pattern all is does is scan the file looking for keywords wherever it might find them.

**Comment by yyyc514** [comment]
@marcoscaceres Can we close something like this as "expected but unfortunate behavior" like the approach we sometimes take to auto detection failures or does it need to live forever until perhaps one day we find a magic way to fix it? :-)

**Comment by marcoscaceres** [comment]
Yes, that seems fine.

**Comment by yyyc514** [comment]
@tygern A PR would be welcome if you have a solid idea how to fix this problem generally, but off the top of my head this would seem to be a limitation of our approach to parsing... ie it's really a "cant fix" more than a "won't fix".
