### ISSUE TITLE
Elements in <code> converted to all lower-case

### ISSUE THREAD

**Issue by seanmcilvenna** [highlightjs/highlight.js#1745]
When I apply highlight.js to a &lt;code&gt; block, it seems to be converting the elements in the XML code-block to be all lower-case.
For example, if I provide it:
```<code>&lt;ClinicalDocument&gt;test&lt;ClinicalDocument&gt;</code>```
It ends up converting it to:
```<code>&lt;clinicaldocument&gt;test&lt;clinicaldocument&gt;</code>```
How do I stop this from happening? In my XML snippets, the case sensitivity is important.

**Comment by yyyc514** [comment]
Can you confirm this is still an issue and please provide a full reproducible example?  This does not look like correct behavior.

**Comment by seanmcilvenna** [comment]
I'd like to, but unfortunately I'm completely swamped for the next while. I'll re-test with the latest version as soon as I can, though.

**Comment by cdbax** [comment]
Looks to be fixed on 9.15.10
https://jsfiddle.net/cdbax/r8wy324e/1/

**Comment by yyyc514** [comment]
Awesome. :-)
