### ISSUE TITLE
How do I force assign a language to render?

### ISSUE THREAD

**Issue by foreshadow** [highlightjs/highlight.js#1754]
I am using `<code class="tex">` to make it render as tex language. However, I find the explicit class is only a FALLBACK option, it will try to detect the language first, which gets the wrong language. For example, I got `<code class="tex hljs ruby">` (or bash) after loading hljs. The inner content is short and contains Chinese characters. How do I force assign a language to render?

**Comment by JJ-Atkinson** [comment]
Likely you don't have the whole compiled version of hljs downloaded. It comes in multiple language packs.

**Comment by yyyc514** [comment]
Agree, I haven't seen this behavior.  Anytime I override the override sticks.

**Comment by yyyc514** [comment]
Closing because of age and non-response. [cleaning out old issues]

If this is still an issue, please let us know and we're happy to reopen.
