### ISSUE TITLE
Enforcing to stop automatic language detection and manually setting class attribute

### ISSUE THREAD

**Issue by BentCoder** [highlightjs/highlight.js#1763]
Hi,

How do I enforce highlighter to stop automatically detecting the language and always set `class` attribute to `hljs less`? I am using code below but it automatically detects the language and sticks `json` in and the result becomes `hljs less json`. 

Thanks

```
<link href="sunburst.min.css" rel="stylesheet" />
<script src="highlight.min.js"></script>

<script>
$(document).ready(function() {
    $("pre code").each(function(i, block) {
        $(this).removeClass().addClass("hljs less");
        hljs.highlightBlock(block);
    });
});
</script>
```

**Comment by isagalaev** [comment]
Most likely your highlight.min.js doesn't have the definition for "less", so it doesn't know this class name is a language. Download a custom package or include the language separately if you're using the CDN-hosted version.

**Comment by BentCoder** [comment]
I dowloaded it but auto detection still enabled and needs to disabled somehow. I get `hljs less http`, `hljs less xml`, `hljs less json` so on. It just suffixes classes.

**Comment by isagalaev** [comment]
Yes, this is exactly the behavior when the package lacks the language definition. Another thing, your file is named "highlight.min.js", whereas if you download a custom build from the site (http://highlightjs.org/download/) it's highlight.pack.js.

**Comment by BentCoder** [comment]
I've been looking at that page for hours but never noticed "Download" button until you mentioned it. I think it needs to be a more "in your eye" like button. Thank you.
