### ISSUE TITLE
[feature request] toml support 

### ISSUE THREAD

**Issue by xgdgsc** [highlightjs/highlight.js#1774]
https://github.com/toml-lang/toml

a good config file type

**Comment by gusbemacbe** [comment]
I rewrite what @ldct said in other issues:

We can review and merge PRs with language implementations but won't be able to actually implement all the requested languages.

Please see http://highlightjs.readthedocs.io/en/latest/language-requests.html for more details.

**Comment by gusbemacbe** [comment]
I rewrite what @ldct said in other issues:

We can review and merge PRs with language implementations but won't be able to actually implement all the requested languages.

Please see http://highlightjs.readthedocs.io/en/latest/language-requests.html for more details.
