### ISSUE TITLE
allocation size overflow

### ISSUE THREAD

**Issue by igor-i** [highlightjs/highlight.js#1782]
Some combination inside the block of code without the name of the language immediately after the backticks causes an error "allocation size overflow".

The full block of code on which we encountered this error:
```
startsWith(string $substring [, boolean $caseSensitive = true ])

s('...')->startsWith($term, false);
```

It seems that the problematic combination of characters such:
```
some_letter('..
```

**Comment by yyyc514** [comment]
Does this still seem to be an issue?  If so can anyone help run down which grammar might be at fault here?

**Comment by yyyc514** [comment]
9.15.10 detect this as PHP quite quickly without issue.  I don't see any issues in the browser.

https://jsfiddle.net/ajoshguy/zpd14vca/

If you're still seeing this problem please provide a reproducible test case.

Closing this from lack of activity and can't reproduce.
