### ISSUE TITLE
Wrong coloring with apostrophes with prefix (cpp)

### ISSUE THREAD

**Issue by mbndr** [highlightjs/highlight.js#1787]
If I want to highlight this code (cpp) with hljs
```cpp
char16_t c16val {u'Ω'};
char32_t c32val {U'Ω'};

// just a random comment ' wrong highlighted
```
it gets colored like this:
![image](https://user-images.githubusercontent.com/7734369/43508318-e0955c16-956f-11e8-9c70-5b43415ccfba.png)

There seems to be a problem with the `'` char in combination with a prefix (`u`).
If I remove the `u` and `U` the highlighting is correct.

**Comment by yyyc514** [comment]
Can you test this again against the Github master branch?  This should be resolved now with:

https://github.com/highlightjs/highlight.js/pull/2156
