### ISSUE TITLE
Add Gremlin language syntax

### ISSUE THREAD

**Issue by PhilStollery** [highlightjs/highlight.js#1790]
A graph language that would be nice to see in colour.

**Comment by gusbemacbe** [comment]
@PhilStollery 

I rewrite what @ldct said in other issues:

> We can review and merge PRs with language implementations but won't be able to actually implement all the requested languages.
>
> Please see http://highlightjs.readthedocs.io/en/latest/language-requests.html for more details.

**Comment by yyyc514** [comment]
Asked and answered, thanks @gusbemacbe.

Rather than leave these issues open to languish forever (as we have in the past) we're going to start closing them (to clean up the issues list).

I've moved this request to the wish list:
https://github.com/highlightjs/highlight.js/wiki/Grammar-Requests
