### ISSUE TITLE
Code consisting of several languages

### ISSUE THREAD

**Issue by zertex** [highlightjs/highlight.js#1794]
Do you plan to make the highlighting of code consisting of several languages, for example PHP + HTML?

--- RUSSIAN

Не планируете ли Вы сделать подсветку кода, состоящего из нескольких языков, например PHP+HTML?

Можно ли, в противном случае, как-то игнорировать другие языки, а то слетает вся подсветка в случае:
`тут произвольный HTML код <?php echo "test"; ?> тут произвольный HTML код`

**Comment by gusbemacbe** [comment]
Новые помо́щники не русские. Поэтому, пожалуйста, напиши по-английски.
