### ISSUE TITLE
Request: Theme Customization per code block

### ISSUE THREAD

**Issue by WilliamRagstad** [highlightjs/highlight.js#1802]
Add support for attribute controlling what theme/style the code snippet should show in. As well as a language tag for specifying what language it is. The theme attribute could be set to the current theme unless anything else is set.
```
<pre><code language="cs" theme="dracula">
using system.net

namespace myApp {
	int myapp = new App();
	myapp.isAwesome();
}
</code></pre>
```

**Comment by yyyc514** [comment]
You can already do half of this with class:

```html

<pre><code class="cs">...</code></pre>
```

**Comment by yyyc514** [comment]
This isn’t a high priority but you could do it yourself easily enough by doing the loop yourself and simply changing `classPrefix` with `configure()` before you highlighted each block.  Of course you’d need custom themes perhaps using the theme name as the “prefix” instead of “hljs”, etc... but probably only 5-10 lines of custom JS.

**Comment by yyyc514** [comment]
@egor-rogov You perhaps interested in adding this?  If not I’ll probably close this due to lack of time and since it’s pretty easy to do this already without it being a core feature (As already mentioned).

**Comment by egor-rogov** [comment]
I will gladly accept PR but won't possibly do it myself. Why not leave it be as a feature request?

**Comment by yyyc514** [comment]
>  Why not leave it be as a feature request?

Do we want ever feature even if they're pretty trivial to whip up in JS itself?  Every feature also requires dev time to maintain, answer questions about, etc. :-)

**Comment by egor-rogov** [comment]
Every feature - no, but this one looks like something that can be accepted for me.

**Comment by yyyc514** [comment]
> this one looks like something that can be accepted for me.

So be it. :-)  Tagging accordingly.  I'm not opposed, I just worry the CSS side will be messy, but I guess we can wait and see what is suggested. :-)

Possibly beginner friendly.  I think the hard part of this is how to deal with the CSS rules which are hard coded in a single namespace... just adding an attribute and then rendering the span tags a little differently probably isn't super complex.

**Comment by joshgoebel** [comment]
Has seen zero interest in over a year.  Closing.
