### ISSUE TITLE
Bug: Code is not show correct

### ISSUE THREAD

**Issue by DavidRotert** [highlightjs/highlight.js#1803]
Hello, I use a template from the Internet which is using Bootstrap and JQuery for my website. I use a pre tag followed by a code tag, but in all web browsers I tried (chrome, ie11, edge) my code is shown like this:
```
importAPI example
"a test string"example.f(, None)
```
I tried to copy the code from the web browser, and the text I get is the same like in real:
```
from API import example
...
```
Is there might anything I can do to show my code correct?

**Comment by yyyc514** [comment]
I'm not following at all.  Any chance you can make a reproducible example of your issue on say https://jsfiddle.net or perhaps screen grab?

**Comment by DavidRotert** [comment]
Sorry, this post is to old to remember how I can reproduce this bug. I only could find out that it appears in version 9.12.0.
