### ISSUE TITLE
[html] add highlights for entities, &amp; etc.

### ISSUE THREAD

**Issue by w3suli** [highlightjs/highlight.js#1805]
Highlight js do not highlighted html entities!

Example:
&amp;amp;gt;

could this bug be corrected?

**Comment by gusbemacbe** [comment]
All these bugs will be fixed in the next version.

**Comment by w3suli** [comment]
Not fixed this bug in 9.13.0!

**Comment by marcoscaceres** [comment]
@w3suli, would appreciate a pull request if you’d like these fixed.

**Comment by gusbemacbe** [comment]
I can not fix it now due to my thesis job. After my graduation, I will fix it. 

Maybe @canvasplay, @egor-rogov, @brunophilipe and @romanresh can fix it.

**Comment by w3suli** [comment]
@yyyc514 
There are many HTML entities.
One solution to highlight is to search for all existing entities. This solution is perfect but slow.
Alternatively, each element that appears to be an entity is labeled as an entity.

**Example:**
Copyright html entities: &amp;copy; or &amp;#169;
Highlighted variants: &amp;amp;copy; or &amp;amp;#169;

That is, each entity begins with an **&amp;amp;** and ends with a **semicolon**.

_&amp;amp;EntitiesName;_
_&amp;amp;#EntitiesCode;_

**Comment by w3suli** [comment]
Example:
[https://jsfiddle.net/w3suli/ug97Ly4f/6/](https://jsfiddle.net/w3suli/ug97Ly4f/6/)

**Comment by yyyc514** [comment]
> Alternatively, each element that appears to be an entity is labeled as an entity.

Yes. That is how we’d want it done. There are two patterns:

- &copy; textual
- &#169; numerical 

And I think(?) you can also use hexadecimal numbers and stuff when we’d need to support, so numerical might be a tiny bit complex. 

Still should be a tiny little patch I think.

**Comment by w3suli** [comment]
Yes, they can be hexadecimal numbers. However, for entities, numbers are not highlighted separately.
Entities are the same color regardless of name, number.
There must be no spaces within delimiters, because they are no entities.

Additional example:
[https://jsfiddle.net/w3suli/ug97Ly4f/7/](https://jsfiddle.net/w3suli/ug97Ly4f/7/)

**Comment by yyyc514** [comment]
I wasn't suggesting separate highlight, just making sure to mention it so that when someone goes to run with this they deal with all the permutations, not just 1 or 2.

**Comment by w3suli** [comment]
All options example:
https://jsfiddle.net/w3suli/ug97Ly4f/12/
