### ISSUE TITLE
CSS prefix and attributes bug

### ISSUE THREAD

**Issue by w3suli** [highlightjs/highlight.js#1806]
**example:**
animation:
-webkit-animation:

-webkit-, -moz-, -ms-, -o- : not css attributes! Css attributes only animation!

-webkit-, -moz-, -ms-, -o- : css prefix! You must separate the css prefix mark from the attribute!

**Comment by marcoscaceres** [comment]
Thanks for checking. However, please note that if an issue is open, it usually means it’s not been fixed. As this project is community maintained, we appreciate help with bug fixes.

**Comment by marcoscaceres** [comment]
Note that some -webkit prefixes are standard (and possibly others), so it might not be possible to fix this.

**Comment by w3suli** [comment]
One prefix (-webkit, -moz-, -ms-, -o-) is neither css3 standard.
Many editors mark them separately. Therefore, it would be nice to include them in a
`<span class = "hljs-prefix">-webkit-</ span>`
class. In this way, it is possible to decide whether or not to have a separate coloring on the css themes.

**Comment by yyyc514** [comment]
We'll probably not add an extra class... since none of the themes support it... that's something someone could do in their own custom theme/language if they desired to do so.

Is there an issue with the highlighting in general though?  I'm not sure from reading this issue.  If there is could you whip up an reproducible example?   a jsfiddle would be great.

Quick Template:
https://jsfiddle.net/ajoshguy/nagkqytv/

**Comment by yyyc514** [comment]
Weekend ping.

**Comment by w3suli** [comment]
I'll get back to you soon and write about the problem again.
Thank you for your interest!

**Comment by yyyc514** [comment]
Closing from inactivity (cleaning out old issues).  If you do find the time to add a reproducible test case we can definitely reopen this issue!

Thanks!

**Comment by w3suli** [comment]
Current state:
BAD!
![BAD](https://user-images.githubusercontent.com/20889555/67665502-225ed280-f96a-11e9-83f5-f89a7682e098.png)

GOOD (if no prefix):
![GOOD-NoPrefix](https://user-images.githubusercontent.com/20889555/67665621-5934e880-f96a-11e9-802a-15b14252be3d.png)
GOOD (prefix):
![GOOD-Prefix](https://user-images.githubusercontent.com/20889555/67665643-66ea6e00-f96a-11e9-9f00-9cab7b3222e2.png)

**Just do not introduce prefix notation because the themes do not support I think bad.

If the new class were introduced I would be happy to adjust the themes.
Enough to add to css themes:
.hljs-prefix{
opacity:0.55
}**

Unfortunately, there are other bugs:

- Numbers in parentheses are not highlighted. color: rgba(51, 170, 51, .1); or width: calc(100% - 80px); or transform: rotate(45deg); or filter: grayscale(0.5) blur(10px);
- In the parentheses of the at rules, properties are not highlighted. @media only screen and (orientation: landscape) or @media screen and (max-width: 900px) and (min-width: 600px), (min-width: 1100px)

**Comment by yyyc514** [comment]
> If the new class were introduced I would be happy to adjust the themes.

I don't think we're looking to extend the classes.  This is kind of neat, but doesn't seem to be a huge benefit (compared to the effort of adding a new class to every theme, etc).  That's also very hard to do for all the 3rd party themes that aren't located in a single place, etc...

Could you please create a jsfiddle showing examples of your other issues?

You can fork my template:
https://jsfiddle.net/ajoshguy/a1kntyg4/
