### ISSUE TITLE
Documentation is outdated

### ISSUE THREAD

**Issue by Harmon758** [highlightjs/highlight.js#1808]
The last [build for Read the Docs](https://readthedocs.org/projects/highlightjs/builds/) was almost a year ago.
Possibly due to [the project repository](https://readthedocs.org/projects/highlightjs/) still being https://github.com/isagalaev/highlight.js.

**Comment by marcoscaceres** [comment]
@Harmon758, would you be willing to help do another rebuild?

**Comment by marcoscaceres** [comment]
oh, it's new to all of us, as the project has a whole new bunch of maintainers. 

Anyone done it before?

**Comment by Harmon758** [comment]
I assumed that it just wasn't automatically being built anymore because of the Read the Docs configuration/setup not being updated after the migration.
I'm not sure, but it's likely the webhook needs to be reconfigured through the Read the Docs project settings and/or the GitHub repository settings.
The [Read the Docs project page](https://readthedocs.org/projects/highlightjs/) still references https://github.com/isagalaev/highlight.js as the repository, so there might be other project settings that need to be updated as well.

**Comment by yyyc514** [comment]
@isagalaev Can you help us get this updated and perhaps we can get this building docs again?

**Comment by yyyc514** [comment]
@isagalaev Can you help us get this updated and perhaps we can get this building docs again? Or perhaps add admin rights to one of the other maintainers so we could fix this?

**Comment by egor-rogov** [comment]
@isagalaev Repository is already changed to https://github.com/highlightjs/highlight.js, but still someone from maintainers should be able to make a build. My account is https://readthedocs.org/profiles/egorius/

**Comment by isagalaev** [comment]
@egor-rogov added you as a maintainer. @yyyc514 do you have account on readthedocs?

It shouldn't require manual intervention though. I can see the last build was done over two months ago, looking into it right now.

**Comment by isagalaev** [comment]
So apparently readthedocs was hooked to GitHub via a deprecated GitHub API ("Services"), so I now recreated it via a generic webhook manually, as suggested by the docs on readthedocs. Hopefully it will start building automatically again. If not, feel free to ping me again or fiddle with the settings on both sides.

**Comment by yyyc514** [comment]
When?  After next release?

**Comment by egor-rogov** [comment]
@isagalaev Thanks!

**Comment by egor-rogov** [comment]
> When? After next release?

We shall see. As for now, the docs are up-to-date.

**Comment by isagalaev** [comment]
It actually builds for every push to master (I never defined any versions besides `latest`). You can see the commit SHA in the footer of the index page at https://highlightjs.readthedocs.io/en/latest/, it should be the same as the last commit in master.

**Comment by yyyc514** [comment]
Oh. Nice. Thanks.
