### ISSUE TITLE
(python) f-string incorrectly matches "if" followed by string

### ISSUE THREAD

**Issue by Harmon758** [highlightjs/highlight.js#1809]
For Python, `if` followed by a string, without a space in between, highlights as an f-string.
For example:
```py
if"text"=="text":
    pass
```
becomes
```html
i<span class="hljs-string">f"test"</span>==<span class="hljs-string">"test"</span>:
    <span class="hljs-keyword">pass</span>
```
rather than
```html
<span class="hljs-keyword">if</span><span class="hljs-string">"test"</span>==<span class="hljs-string">"test"</span>:
    <span class="hljs-keyword">pass</span>
```

**Comment by yyyc514** [comment]
Can you confirm this is still an issue?  If so I think we could fix this by requiring a word boundary before the start of a Python fstring.  A jsfiddle that reproduces the issue would also be great.

Quick template:
https://jsfiddle.net/ajoshguy/nagkqytv/

**Comment by Harmon758** [comment]
This is still an issue, as the example I provided still applies.
You can simply replace the code block in that template with it and set the class to Python to test it, i.e.:
```py
<code class="python">
if"text"=="text":
    pass
</code>
```
![image](https://user-images.githubusercontent.com/9403740/66284455-69870580-e88d-11e9-8f30-9298f18701ed.png)

**Comment by yyyc514** [comment]
Thanks. Confirmed.

**Comment by yyyc514** [comment]
For anyone wanting to dig into this and perhaps make a PR:

>  If so I think we could fix this by requiring a word boundary before the start of a Python fstring

I think a `\b` to start the matches would solve it, but I'm not sure.
