### ISSUE TITLE
Mention TOML on the website

### ISSUE THREAD

**Issue by mortenpi** [highlightjs/highlight.js#1814]
Hoping that this is an appropriate place for this request:

TOML is implemented as part of the ini language (#864). However, it does not show up anywhere on the highlightjs.org website that it is supported. Could the website listing of languages be updated to say e.g. "Ini / TOML" instead?

I have a feeling that I am not the only one who initially thought that TOML is not supported (#1774).

**Comment by egor-rogov** [comment]
Done
