### ISSUE TITLE
Markdown highlighting doesn't work with indentation

### ISSUE THREAD

**Issue by lukakerr** [highlightjs/highlight.js#1821]
I'm not sure if highlight.js supports nested items, such as lists, but I thought I'd open the issue anyway to clarify.

If indentation is used as shown below, the syntax highlighting doesn't seem to work 100% correctly. In the second item below, the dash `-` doesn't get syntax highlighted but everything else does, and in the third nested item nothing gets syntax highlighted.

```html
<pre><code class="markdown">
- list [link](link) `code` **bold**
  - nested list [link](link) `code` **bold**
    - nested again [link](link) `code` **bold**
</code></pre>
```

You can find an interactive demo here showing the exact issue: https://codepen.io/anon/pen/vzZQYb

**Comment by gusbemacbe** [comment]
I address this issue to the #1822 .

**Comment by lukakerr** [comment]
@gusbemacbe 1822 seems to be a different unrelated issue. Mine is related specifically to markdown and indentation. Is there something I’m missing?

**Comment by gusbemacbe** [comment]
Sorry for my absence, I was to busy with my college.

This issue and that issue are related to Markdown. It is a regular expression bug.
