### ISSUE TITLE
Custom No-op Plain Text Syntax exhibits odd Behavior

### ISSUE THREAD

**Issue by RickStrahl** [highlightjs/highlight.js#1822]
In order to handle plain text I've created a custom `test.js` syntax which is intended as a no-op. I realize that I can use `class="nohighlight"` for no-ops that just render the code, but that involves intercepting the tags, which currently is handled natively by a Markdown parser which generates `langauage-syntax` tags.

To get around this I created a no-op syntax that doesn't do anything which looks like this:

```js
function(hljs) {
  return {
    aliases: ['txt','plain','none'],
    case_insensitive: true,
    keywords: '',
    contains: []
  }
}
```

and rebuild the package that includes this `text` syntax.

This sort of works - for `txt` and `none`, but not for `text` and plain:

![image](https://user-images.githubusercontent.com/1374013/45072671-da5b5d00-b090-11e8-9a9a-6d2d320d7fc5.png)

The rendered output is this.

**Doesn't work:**

```html
<pre><code class="language-text">text
one
two
three
</code></pre>
```

**Works:**

```html
<pre><code class="language-txt">txt
one
two
three
</code></pre>
```

when using this code to highlight:

```js
function highlightCode() {
    $("pre code")
        .each(function (i, block) {
            hljs.highlightBlock(block);
       });
}
```

If I remove the text syntax completely none of them work, so it seems the no-op syntax definition is working but somehow not hitting all the aliases.

Two questions:

* Is there an easier way to handle plain text - ideally I'd like to be able to just use a fence without auto-detection **without checking the entire document** (ie. `highlight()` - I'm handling each block individually using `highlightBlock()`).

* Why is the `text.js` syntax working for some of the aliases and not for others?

**Comment by egor-rogov** [comment]
It would be helpful to see a complete example which can be reproduced (all files necessary to build the package).
I was thinking of something like this myself (to render `select` results), but I can't figure out what to do about `detect/text/default.txt`. This "language" won't autodetect any document and hence never will pass tests.
AFAIK currently there is no way to disable autodetection. Maybe it's worth discussing such feature.

**Comment by RickStrahl** [comment]
Yes it would be super nice if there was a way to specify that highlightBlock() wouldn't auto-detect. The docs seem to imply that `highlight()` doesn't auto-detect, so it seems that this is possible? Or am I reading that wrong?

IAC the behavior that I would love to see is a `noAutoDetection` flag which when set just applies the `.hljs` style and doesn't do anything else.

I can work around this by pre-processing my code before it gets handed to hljs:

```js
function highlightCode() {
    $("pre code")
        .each(function (i, block) {
            // handle special cases
            var $code = $(block);
            if ($code.hasClass("language-text") ||
                $code.hasClass("language-none") ||
                $code.hasClass("language-txt") ||
                $code.hasClass("language-plain")) {
                   $code.addClass("hljs");
                    return;
            }

            hljs.highlightBlock(block);
        });
}
```

This gets the desired effect for me, but it's kind of ugly and specific to the *custom* types I added to my markdown processing code. It would be much nicer if there was an option if no language is specified to just render the raw text.

```js
hljs.highlightBlock(block,);
```

I don't have a manageable working sample - the code I'm working with is open but it's a large codebase of a Windows Markdown Editor which is hard to manage.

Should be easy to repro though. What I did was:

* Add `text.js` (above) into the syntax folder
* Then create HTML with the `language-text` etc. snippets.

**Comment by egor-rogov** [comment]
> Why is the text.js syntax working for some of the aliases and not for others?

It turns that `text` and `plain` (as well as `no-highlight` and `nohighlight`) are special hardcoded language names which prevent highlighting in `hljs.highlightBlock()`.

As for
> Is there an easier way to handle plain text 

why not just specify some non-existing language? Like `<code class='language-highlightmenot'>` or something. `hljs.highlightBlock()` won't autodetect language for that block.

**Comment by RickStrahl** [comment]
The problem is that it doesn’t add the highlights style when using an invalid language among other things. The way it should work imho is that

**Comment by egor-rogov** [comment]
Ah, I see the problem. For `plain` / `text` / `nohighlight` and for invalid language names `highlightBlock()` exits immediately and doesn't even add `hljs` class to block. Probably it is by design, because the documentation says:

> To disable highlighting altogether use the `nohighlight` class

Though not sure what 'altogether' means exactly.

I'm thinking about adding `plain` to the list of supported languages. It will essentially be just a shortcut in `highlight()` function, which leaves the source code untouched. This will work for `highlightBlock()` and for `highlight()` as well. `highlightAuto()` will never autodetect this language due to zero relevance.
How about that?

**Comment by egor-rogov** [comment]
Created PR #1834

**Comment by RickStrahl** [comment]
This looks great... 

I think for me and my users the most typical expectation would be `text` and `plain` as a second, but it looks like both of those cases are covered.

Thank you... closing and further comments on PR if any.

**Comment by egor-rogov** [comment]
You are welcome!
