### ISSUE TITLE
Add support of .rst language

### ISSUE THREAD

**Issue by bocharsky-bw** [highlightjs/highlight.js#1823]
Or can I highlight .rst files with HighlightJS in some way? Probably a similar language? Any ideas?

**Comment by gusbemacbe** [comment]
I rewrite what @ldct said in other issues:

We can review and merge PRs with language implementations but won't be able to actually implement all the requested languages.

Please see http://highlightjs.readthedocs.io/en/latest/language-requests.html for more details.

**Comment by bocharsky-bw** [comment]
@gusbemacbe of course, it makes sense. Thanks for pointing to this. But I'm not going to implement this either, at least for now. Could you advise me how I can highlight rst files for now? Maybe some kind of default or similar language? Thanks!

**Comment by gusbemacbe** [comment]
HI @bocharsky-bw 

You can read the short language guide to build a new syntax:

https://github.com/highlightjs/highlight.js/blob/master/docs/language-guide.rst

Or you can copy any of language syntax: https://github.com/highlightjs/highlight.js/tree/master/src/languages and modify, and implement.

**Comment by bocharsky-bw** [comment]
OK, thanks for your help

**Comment by jolkdarr** [comment]
Hi

Asciidoc is supported. Maybe it's a good template for reStructuredText format.

**Comment by bocharsky-bw** [comment]
Hey @jolkdarr ,

Thanks for this advice! I have even never heard about Asciidoc, but its syntax looks similar. FYI, I reused Markdown language highlighting for `.rst` files so far, but will take a look at Asciidoc, maybe it would even better.

Cheers!

**Comment by jolkdarr** [comment]
Hi

Glad to know that could help! ;)
Main markup formats are compared at many sites such the following:
http://hyperpolyglot.org/lightweight-markup

I think both Markdown and Asciidoc should be used to achieve .rst support.
