### ISSUE TITLE
Elixir highlighting is incorrect

### ISSUE THREAD

**Issue by TMSCH** [highlightjs/highlight.js#1824]
Hi Highlight team,

Here is an example showcasing the issues of Elixir highlighting. It's taken from reviewable.io UI that uses highlight.js under the hood.

**First, highlight.js**

![screen shot 2018-09-05 at 10 20 31 am](https://user-images.githubusercontent.com/2036827/45109948-c85fd580-b0f5-11e8-8055-6fa117049270.png)

**Second, my VSCode editor**
![screen shot 2018-09-05 at 10 25 59 am](https://user-images.githubusercontent.com/2036827/45110193-70759e80-b0f6-11e8-8739-4da891350a34.png)
(there's some custom coloring going on here but I'll focus on the general issues)

**What's wrong in highlight.js**

- Incorrect namespace highlighting in `defmodule`declaration (different colors when it should be monochrome)
- Incorrect namespace highlighting in code body (monochrome when namespace should be different color)
- `require` and `import` statements are not highlighted.
- `@moduledoc`, `@doc`, `@typedoc` incorrectly highlighted as module attributes.
- `<-` and `|>` not highlighted.
- `with` statement not highlighted.

Thanks for looking into this!

**Comment by pkaminski** [comment]
I'm working on a PR &mdash; here are my thoughts so far:
- `require`, `import` and `with` are simply missing; added.
- Module names can be compound (perhaps other names too?); allow `.` as part of identifier.
- `@moduledoc`, `@doc` and `@typedoc` appear to be [defined as module attributes](https://hexdocs.pm/elixir/writing-documentation.html), not sure why it's wrong to highlight them as such?
- As far as I can tell by looking at the [CSS class reference](https://highlightjs.readthedocs.io/en/latest/css-classes-reference.html) and other languages, highlight.js philosophy is not to highlight operators or namespaces.  If that's not correct perhaps a maintainer can correct me?
- Found an extra bug where `::` and neighbors gets highlighted as symbol; fixed.

If we can clarify my questions above I can open a PR with the fixes.  Thanks!

**Comment by TMSCH** [comment]
- OK
- OK
- You're right, it's OK to keep them highlighted as module attributes.
- Fine not to highlight namespace, as #2 is fixed.
- Great :)
