### ISSUE TITLE
Made API tool out of highlight.js

### ISSUE THREAD

**Issue by jimmywarting** [highlightjs/highlight.js#1831]
The idea was to not having to add the hole bundle and install the css/javascript and just only put the finished formated code into the place where i want it

I also turn all css to inline style so it could be easily copied into other rich text editor. like email and rtf document 

https://highlight-saas.herokuapp.com

**Comment by yyyc514** [comment]
Very very neat idea.

**Comment by yyyc514** [comment]
This is definitely cool (as I said before), but is there actually an issue here or can this be closed out?  Were you hoping for us to add this to docs or website or something?

Just trying to clean up the queue.

**Comment by jimmywarting** [comment]
Its not an issue so do whatever you like. Would be cool of you added it to your docs your website doe 🙂

**Comment by yyyc514** [comment]
I'll flag is as docs related and perhaps we'll consider adding it in the future once we figure out whose keeping the website maintained and such details. :)

**Comment by yyyc514** [comment]
Is this app OSS?

**Comment by yyyc514** [comment]
Ping.

**Comment by jimmywarting** [comment]
OSS?

**Comment by taufik-nurrohman** [comment]
Open Source Software

**Comment by jimmywarting** [comment]
yea https://github.com/jimmywarting/highlight-saas

**Comment by yyyc514** [comment]
Unless there is an action item here (a clear "next step") I'm going to close out this issue. (in my ongoing quest to clear out old issues)...

So, towards that end...

@jimmywarting @egor-rogov Does anyone have a specific recommend for where we might add this to docs?  Do we need a "Tools" or "Sites that use Highlight.js" section of the readme or something?  Thoughts? Opposition?

**Comment by jimmywarting** [comment]
Do as you like.

**Comment by egor-rogov** [comment]
It's easy to add, but difficult to keep it up-to-date. So it's hardly possible unless someone volunteers to maintain such list of tools/sites...
