### ISSUE TITLE
How to get normal code back?

### ISSUE THREAD

**Issue by sszczep** [highlightjs/highlight.js#1838]
Hi. I'm using highlight.js with quell. How can I reverse highlight to get pure, untouched code? I don't want to store all these classes added by hljs in database. Is it possible?

**Comment by marcoscaceres** [comment]
The short answer is "yes" - but it depends how you are doing things. Assuming you can access the DOM nodes in JS, you can just do:

```JS
// Just the raw code in the document
var code = Array.from(document.querySelectorAll("pre")).map(pre => pre.textContent);
```

**Comment by sszczep** [comment]
This is the solution I’ve been looking for, but my text is not a dom element. It’s coming from vue component and it’s just a string. Do you know how can I perform these actions on regular string?
Thanks

**Comment by marcoscaceres** [comment]
So, unfortunately, I don't know anything about Vue, but all JS libraries are just built on-top DOM elements... if they are wrapped in some kind of JS object, it should be possible to inspect them and add a method to `.toString()`. 

I'd suggest poking around in browser's developer console until you find a way to getting to the actual backing HTML element... then you should be able to get to `.innerText` of that element. 

Closing, as it's outside the scope of this project. But if other folks have ideas, please chime in. 

@sszczep, if you can put up what you have somewhere, I can have a quick look and see if I can give you some more hints where to look - but without seeing actual running code, it's hard for me to help.

**Comment by marcoscaceres** [comment]
> I can get around it and get content with a selector as you said earlier. I just thought I can somehow strip all these tags from a normal string without a need to parse it as a DOM element.

It might be possible, but I honestly don't know without seeing the code.
