### ISSUE TITLE
Prepare release

### ISSUE THREAD

**Issue by marcoscaceres** [highlightjs/highlight.js#1845]
As per https://github.com/highlightjs/highlight.js/blob/master/docs/maintainers-guide.rst#release-process

Need update the CHANGES file, make sure we captured all the latest stuff.

**Comment by isagalaev** [comment]
Copying the micro-postmortem from Slack:

Fixed.
Here's what was wrong:

- `npm update` failed trying to remove js-beautify:

```
npm ERR! Refusing to delete /home/maniac/code/highlight/node_modules/js-beautify/node_modules/.bin/mkdirp: containing path /home/maniac/code/highlight/node_modules/js-beautify/node_modules/mkdirp isn't under npm's control
npm ERR! File exists: /home/maniac/code/highlight/node_modules/js-beautify/node_modules/.bin/mkdirp
npm ERR! Move it away, and try again.
```

- also, my password for npm exired (I vaguely remember npm had some sort of a breach during the last year and a half, so it possibly was the reason)

**Comment by marcoscaceres** [comment]
Closing. 9.13.0 is out! 🎉
