### ISSUE TITLE
Syntax coloring does not activate properly

### ISSUE THREAD

**Issue by kaphula** [highlightjs/highlight.js#1846]
Hey,

I am trying to get the highlight.js working on my webpage, but all of the `<pre><code></pre></code>` blocks appear with only background and foreground colors. For example, with github.css I only see white background and black text, but no highlighted keywords.

I have set up the highlight.js in my html document's head section like this:

```
    <!--highlight.js for code snippets-->
    <link rel="stylesheet" href="../vimwiki_templates/node_modules/highlight.js/styles/atom-one-dark.css">
    <script src="../vimwiki_templates/node_modules/highlight.js/lib/highlight.js"></script>
    <script>hljs.initHighlightingOnLoad();</script>
```
I am not quite sure what script I should be using, since all of the usage manuals talk about highlight.pack.js, but I only have highlight.js, whether I build it from source or install it with npm. I would also like to know is it possible to have one highlighter script that will highlight all of the languages (specified with class="language") on the webpage?

My page has other javascript functions that will form the original html elements to suit the highlight.js required format` <pre><code class="language_name"></pre></code>`. After all of these scripts have run, I reinitialize highlight.js in the same window.onload function as my custom scripts like this:

```
  ...
  myscripts();
  hljs.initHighlighting.called = false;
  hljs.initHighlighting();
```
 
After running my own scripts to get the elements in right form for highlight.js they look like this:

```
<pre><code class="python">    x = 40
    name = "something"
    y = do_something()
</code></pre>
```

And after running highlight.js the elements look like this:

```
<pre><code class="python hljs">    x = 40
    name = "something"
    y = do_something()
</code></pre>
```

**Comment by marcoscaceres** [comment]
@kaphula, can you try replacing with:

````
<script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/languages/go.min.js"></script>
````

To check if it works. It looks like you might have not built it properly.

Can you confirm that you followed the build steps:

https://highlightjs.readthedocs.io/en/latest/building-testing.html

**Comment by kaphula** [comment]
Using this script I get errors that hljs is not defined:
```
Uncaught ReferenceError: hljs is not defined
    at go.min.js:1
```

**Comment by marcoscaceres** [comment]
Oh, hmmm... could you put what you have up on GitHub maybe? Can then have a quick look.

**Comment by marcoscaceres** [comment]
Is there some particular reason for doing the edit_pre_blocks? You should be able to drop that.

**Comment by kaphula** [comment]
I am using vimwiki (vim plugin) to convert my notes as html files. Vimwiki outputs code snippets in this form:

```
<pre  class="python">
code
is
here
</pre>
```
So in order for highlight.js to recognize these snippets, I must modify the snippets in `<pre><code></code></pre>` format? I am sure the scripts could be a lot prettier but I am not html/javascript expert :)

**Comment by kaphula** [comment]
That's odd. 

Are there any similar example projects available where the highlight.js actually works and is included in the project like in my example repo. Just a simple web page with couple snippets of code highlighted would do. It would be good place to start figuring out what's different and why the other works and the does not.

Anyway, thank you for taking your time to look at this.

**Comment by egor-rogov** [comment]
@kaphula In your example the problem is that the languages are not registered. Basically highlightjs starts without knowledge of any language, hence it can't highlight anything. `highlight.pack.js` contains some code for registering all the included languages (via `hljs.registerLanguage()` calls).

I suggest to run the build process:

```nodejs tools/build.js -n```

and you'll get your `highlight.pack.js` in `build/` directory.
Then just replace `highlight.js` with `highlight.pack.js` in the html page.

**Comment by kaphula** [comment]
@egor-rogov Doing this made the colors work properly. Thanks a bunch!
