### ISSUE TITLE
Inconsistant syntax highlighting

### ISSUE THREAD

**Issue by jonesmz** [highlightjs/highlight.js#1847]
For the 9.x series:

These code blocks get highlighted very differently. Note that no language is specified.

```
IoContext::Ptr_t(m_pRawIoContext.get(), false);
```
Gets only "false" highlighted.

```
{
   IoContext::Ptr_t p(m_pRawIoContext.get(), false);
}
```
Gets nothing highlighted
```
{
   IoContext::Ptr_t p(m_pRawIoContext.get(), false);
   p.clear();
}
```
Gets m_pRawIoContext.get() highlighted green, and false highlighted blue.

The code in these blocks happens to be c++, but my concern is that such similar code gets highlighted so differently.

**Comment by egor-rogov** [comment]
Highlight.js determines the language of code block by trying to apply every known language to it and choosing the one that "recognized" more "items". This generally works fine for rather large code snippets, but often fails on smaller ones. I'm afraid there is nothing we can do about it. In such cases you can specify the desired language manually.

**Comment by marcoscaceres** [comment]
Closing as answered. Best practice is to be explicit about the language.

**Comment by jonesmz** [comment]
Sure, I fully understand where your coming from.

All I ask is that the bug not be closed unless its actually an invalid bug. If it is invalid, please tell me, but I did not get the impression that you believed it was invalid, just that you believed you were unlikely to fix it.

If the bug stays open, someone may see it and decide to try to fix it.
