### ISSUE TITLE
(javascript) highlight jsdoc annotations

### ISSUE THREAD

**Issue by jimmywarting** [highlightjs/highlight.js#1857]
like github's markdown dose:

```js
/**
 * @param  {Image} the image to rotate
 * @param  {Function} cb function to call when done
 */
function rotateFrame (img, cb) {...}
```

or atom
![skarmavbild 2018-10-09 kl 17 27 13](https://user-images.githubusercontent.com/1148376/46680108-9d7f0a80-cbe8-11e8-9cdd-c9df1bb51ef8.png)

right now the jsdoc is just grayed like a normal comment

**Comment by yyyc514** [comment]
Closing this with #2245.
