### ISSUE TITLE
`highlightAuto` with language subset doesn't appear to be working

### ISSUE THREAD

**Issue by Martii** [highlightjs/highlight.js#1868]
Hello,

Re: 
* [/highlightjs/highlight.js/blob/`0651014`/docs/api.rst#highlightautovalue-languagesubset](https://github.com/highlightjs/highlight.js/blob/06510146c3130532f920bbb609e1e66347c80760/docs/api.rst#highlightautovalue-languagesubset) *(we use this... and thank you and your team for the longevity and expertise with this package :)*
* [https://openuserjs.org/&hellip;#comment-16615f8e2df](https://openuserjs.org/scripts/eileen12/HaremHeroes_Automatic/issues/Anyone_working_on_this_If_not,_then_Ill_try_to_figure_it_out#comment-16615f8e2df) *(one target where it's currently not auto highlighting since it's not a named fence)*
* [/OpenUserJS/OpenUserJS.org/pull/1528/files#diff-`b9cfc7f`](https://github.com/OpenUserJS/OpenUserJS.org/pull/1528/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L28) *(Dep upgrade from *highlight.js*@9.12.0 to *highlight.js*@9.13.0)*
* [/OpenUserJS/OpenUserJS.org/blob/`c5cb49c`/libs/markdown.js#L225-L260](https://github.com/OpenUserJS/OpenUserJS.org/blob/c5cb49cdf0bdb4f0df2611c824ac5da9bef4424f/libs/markdown.js#L225-L260) *(our code where it currently works in *highlight.js*@9.12.0 but __not__ *highlight.js*@9.13.0 which is currently on production. Using a limited Array of Strings.)*

Spec:
``` sh-session
$ node -v
v10.12.0
```

NOTES:
* [https://openuserjs.org/&hellip;#comment-16627b793f6](https://openuserjs.org/scripts/eileen12/HaremHeroes_Automatic/issues/Anyone_working_on_this_If_not,_then_Ill_try_to_figure_it_out#comment-16627b793f6) *(fixed this one to be a named fence to ensure correct library is being loaded and it is along with the CSS we inject... so it is currently working with named ones just not automatic detection)*.
* All languages are available for named fences however we have had to limit unnamed fences since auto-detection doesn't always pin the right language. Been through a few revisions and landed on this methodology as the best available for our use cases.
* Same issue in development. Clean package installs, etc.
* We use ES5 syntax as a default and minimal to none ES6+.

Thanks for the look.

**Comment by egor-rogov** [comment]
Hi @Martii 
The problem is in `xpath`. There is no such language in highlightjs:

```javascript
  highlight: function (aCode, aLang) {
    var obj = null;
    var lang = [ // NOTE: More likely to less likely
      'javascript', 'xpath', 'xml',         // <------- remove xpath
        'css', 'less', 'scss',
          'json',
            'diff',
              'shell',
                'bash', 'dos',
                  'vbscript'
];
```

In 9.12 this fact was silently ignored, but now we throw an error. Probably we should not.
So, quick fix for you is to remove `xpath` from the list of languages.

**Comment by Martii** [comment]
@egor-rogov 

> The problem is in `xpath`. There is no such language in highlightjs

That did the trick. Will push to dev. Thank you! Could have sworn that I validated all the language names but I'm only human. ;) :)

> In 9.12 this fact was silently ignored, but now we throw an error.

Looks like I'll need to add a few more dev console messages to track this. :) Good to know.

Thanks a bazillion!

**Comment by Martii** [comment]
Hmm just trapped on local dev and nothing thrown. :\ Oh well... I'm ready for rest and will tackle our issue later.

**Comment by Martii** [comment]
Okay I'm stubborn... trapped every layer of our code, and several hard refreshes of my browser, and got this:

``` console
TypeError: Cannot read property 'disableAutodetect' of undefined
    at autoDetection (~/repo/git/OpenUserJS.org/martii/OpenUserJS.org/node_modules/highlight.js/lib/highlight.js:711:29)
    at Array.filter (<anonymous>)
    at Object.highlightAuto (~/repo/git/OpenUserJS.org/martii/OpenUserJS.org/node_modules/highlight.js/lib/highlight.js:572:40)
    at Object.highlight (~/repo/git/OpenUserJS.org/martii/OpenUserJS.org/libs/markdown.js:261:21)
    at Renderer.code (~/repo/git/OpenUserJS.org/martii/OpenUserJS.org/node_modules/marked/lib/marked.js:920:28)
    at Parser.tok (~/repo/git/OpenUserJS.org/martii/OpenUserJS.org/node_modules/marked/lib/marked.js:1199:28)
    at Parser.parse (~/repo/git/OpenUserJS.org/martii/OpenUserJS.org/node_modules/marked/lib/marked.js:1144:17)
    at Function.Parser.parse (~/repo/git/OpenUserJS.org/martii/OpenUserJS.org/node_modules/marked/lib/marked.js:1126:17)
    at marked (~/repo/git/OpenUserJS.org/martii/OpenUserJS.org/node_modules/marked/lib/marked.js:1533:19)
    at exports.renderMd (~/repo/git/OpenUserJS.org/martii/OpenUserJS.org/libs/markdown.js:285:10)
    at exports.renderComment (~/repo/git/OpenUserJS.org/martii/OpenUserJS.org/libs/modelParser.js:719:30)
    at Function._.map._.collect (~/repo/git/OpenUserJS.org/martii/OpenUserJS.org/node_modules/underscore/underscore.js:205:24)
    at preRender (~/repo/git/OpenUserJS.org/martii/OpenUserJS.org/controllers/issue.js:240:13)
    at asyncComplete (~/repo/git/OpenUserJS.org/martii/OpenUserJS.org/controllers/issue.js:254:11)
    at ~/repo/git/OpenUserJS.org/martii/OpenUserJS.org/node_modules/async/dist/async.js:3888:9
    at ~/repo/git/OpenUserJS.org/martii/OpenUserJS.org/node_modules/async/dist/async.js:473:16
```

... that's not quite the stack trace I was thinking I was going to get... `disableAutodetect` of `undefined`.

**Comment by egor-rogov** [comment]
Ah, I see. It doesn't accept aliases (and never did), so use `xquery` instead.
Please leave the issue open, we'll need to rethink this. Probably we should accept aliases as well.

**Comment by egor-rogov** [comment]
Okay, basically we have two options here:

1. Update the docs to reflect the current behavior (i. e. that `highlightAuto()` and `configure()` don't accept aliases). Previously aliases were accepted but ignored (that's too bad), now an error occurs. This change appeared quite accidentally, it wasn't planned.
2. Tweak the code to actually accept aliases along with language names.

(2) is doable but seems not worth the effort. It shouldn't be a big problem for the caller to specify a right name. So I'm inclined to (1).
@marcoscaceres what do you think?
