### ISSUE TITLE
SyntaxError: Unexpected token: keyword (const)

### ISSUE THREAD

**Issue by xwzpp** [highlightjs/highlight.js#1871]
Hello, i find the latest version has one error when i build my project。
![image](https://user-images.githubusercontent.com/7036549/46950201-8d6a9d80-d0b6-11e8-8e50-4fdbbd8a6285.png)

**Comment by Lee182** [comment]
Same I've just had this issue using node v10.10, I'm using webpack with UglifyJSPlugin
which is where the issue is coming. Could be parsing error in UglifyJS and not handly multi-line strings

**Comment by drewmoore** [comment]
Same here. Who doesn't love `const` and `let`, though?

**Comment by marcoscaceres** [comment]
Ok, can someone change that to a `var` and send a PR? I can push out a minor release.

**Comment by marcoscaceres** [comment]
Sent a PR for this.
