### ISSUE TITLE
Publish version 9.13.0 on npm

### ISSUE THREAD

**Issue by anlambert** [highlightjs/highlight.js#1874]
While the latest release is version 9.13.0, the latest published version on npm is 9.12.0 (https://www.npmjs.com/package/highlightjs). Maybe there was an issue in the release process ?

**Comment by marcoscaceres** [comment]
Oh, thanks for letting us know! we had some hiccups with the last release. I’m going to push out a new minor release today. Will leave this open until I confirm it gets published correctly.

**Comment by marcoscaceres** [comment]
Oh, I see what's happened... there actual official one is:

https://www.npmjs.com/package/highlight.js

 Let me see who owns "highlight.js"

**Comment by marcoscaceres** [comment]
Moved to other repo. https://github.com/components/highlightjs/issues/47
