### ISSUE TITLE
Support HCL / Terraform

### ISSUE THREAD

**Issue by aequasi** [highlightjs/highlight.js#1879]
https://github.com/hashicorp/hcl

**Comment by marcoscaceres** [comment]
Hi, we accept language contributions from the community, but don’t generally write them ourselves. Would this be something the hcl community would be willing to create and maintain?

**Comment by raphink** [comment]
So far, I've been using the Ruby highlighter for HCL, but a dedicated language would be better of course.

**Comment by qubyte** [comment]
I recently opened a PR (#2076) with a language file for github workflows, which I've just learnt are based upon HCL. I've found a vim syntax file [here](https://github.com/jvirtanen/vim-hcl/blob/master/syntax/hcl.vim) for HCL, and it seems relatively simple. I could update my PR to cover HCL with `workflow` as an alternative name.

If languages are now being split into their own repositories, I'd be happy to maintain this one. Thoughts?

**Comment by marcoscaceres** [comment]
@qubyte, sorry for the delay. That would be amazing. I'll set a repo for gh-workflow for you. We have a terraform language definition in a repo already... is it the same language as this one?

**Comment by marcoscaceres** [comment]
Here is the link to the terraform one: http://github.com/highlightjs/highlight-terraform/
if it's the same, I can add you as a collaborator to that one.

**Comment by qubyte** [comment]
It appears to be the same! I didn't realise this existed :D

**Comment by marcoscaceres** [comment]
heh, that's my fault for not keeping docs up to date 🤪 Added you to that one too. The nice thing about the terraform repo is that is has tests already. You can probably copy/paste what's there and adapt it.

**Comment by qubyte** [comment]
It may be that these can be added as aliases. The terraform one should probably (though I'd need to take a closer look) be called HCL, since HCL is the language whereas terraform, github workflow etc. are use cases.

**Comment by marcoscaceres** [comment]
Could be... I honestly don't know as I've not looked at the languages.

**Comment by qubyte** [comment]
Is the terraform definition currently bundled with highlight.js? How does that work?

**Comment by marcoscaceres** [comment]
> Is the terraform definition currently bundled with highlight.js? 

No, a consumer needs to `npm install` it. 

> How does that work?

Then they can, for example:

```
hljs.registerLanguage('customLanguage', customLanguage);
```

Then they can create a custom build, for example:
https://github.com/w3c/respec-hljs

The bundle is great, because it only includes the the languages the project needs.

**Comment by qubyte** [comment]
I see! Is the long-term plan to split all the languages out and always manually include them, or something midway with a set of default languages bundled (just asking out of curiosity now)?

**Comment by marcoscaceres** [comment]
> I see! Is the long-term plan to split all the languages out and always manually include them, or something midway with a set of default languages bundled (just asking out of curiosity now)?

We will keep the current "core" set as to not break existing functionality, and split out all new ones.

**Comment by yyyc514** [comment]
> We will keep the current "core" set as to not break existing functionality, and split out all new ones.

Actually if we thought of a way to package multiple languages you could do something like separate the whole Highlight.js codebase from the languages... and then you just install "highlightjs-core-languages"... and then the core languages are "just another language pack".

Something to think about perhaps once we figure out tooling for all this. :)

**Comment by yyyc514** [comment]
Is HCL still separate and this is still and open request or can this be closed now that we have the teraform repo?

**Comment by dbrennand** [comment]
It would be helpful to provide a usage example in the [repo](https://github.com/highlightjs/highlight-terraform/) on how to apply the syntax.

**Comment by dbrennand** [comment]
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Test</title>
    <script type="text/javascript" src="highlight.pack.js"></script>
    <script type="text/javascript" src="highlightjs-terraform/terraform.js"></script>
    <script type="text/javascript">
        hljs.registerLanguage('terraform', window.hljsDefineTerraform);
        hljs.initHighlightingOnLoad();
    </script>
</head>
<body>
    <pre><code class="tf">provider "azure" {
        arm_endpoint    = ""
        subscription_id = ""
        client_id       = ""
        client_secret   = ""
        tenant_id       = ""
      }
      </code></pre>
</body>
</html>
```

The highlighting doesn't work. Can anybody spot the mistake I am making?

**Comment by yyyc514** [comment]
Looks decent to me, any errors in console log?

**Comment by dbrennand** [comment]
> 
> 
> Looks decent to me, any errors in console log?

Not that I can see, I have tried in Firefox and Chrome.

![image](https://user-images.githubusercontent.com/52419383/67090031-fb9de080-f1a0-11e9-82b3-d67c46d4f856.png)

It looks like hightlightjs is working but there is no colour on the html page. 😞

**Comment by yyyc514** [comment]
Sounds like a css issue.

**Comment by dbrennand** [comment]
> 
> 
> Sounds like a css issue.

Wow I fell pretty stupid... Added a style.css file and it's working 😆. Thanks!

**Comment by marcellino-ornelas** [comment]
Any reason why https://github.com/highlightjs/highlightjs-terraform is not available on npm/yarn/etc ?

**Comment by joshgoebel** [comment]
> This project is currently in need of a maintainer.

No one to do it?
