### ISSUE TITLE
Invalid CSS in xt256.css theme

### ISSUE THREAD

**Issue by arnonerba** [highlightjs/highlight.js#1894]
The xt256 theme is missing a unit measurement for the `padding` property on the `.hljs` class. Existing code:
```
.hljs {
  ---
  padding: 0.5;
}
```
This should probably be:
```
.hljs {
  ---
  padding: 0.5em;
}
```
I can submit a PR if that's easier.

**Comment by marcoscaceres** [comment]
Would you kindly please send a pull request?

**Comment by arnonerba** [comment]
Absolutely! Opened as https://github.com/highlightjs/highlight.js/pull/1895.
