### ISSUE TITLE
error registering arduino language

### ISSUE THREAD

**Issue by AlbyIanna** [highlightjs/highlight.js#1899]
I am trying to register arduino language like this:
```js
import arduinoHljs from 'highlight.js/lib/languages/arduino';

hljs.registerLanguage('arduino', arduinoHljs);
hljs.configure({
  languages: [arduinoHljs]
});
```
But I am getting this error:
```
Uncaught TypeError: Cannot read property 'exports' of undefined
    at module.exports (arduino.js:2)
    at Object.registerLanguage (highlight.js:694)
...
``` 

Reading issue #1235 i understood that arduino relies on cpp language, and the order of the languages could mess things up, so I tried to register cpp too like this:
```js
import cppHljs from 'highlight.js/lib/languages/cpp';
import arduinoHljs from 'highlight.js/lib/languages/arduino';

hljs.registerLanguage('cpp', cppHljs);
hljs.registerLanguage('arduino', arduinoHljs);
hljs.configure({
  languages: [arduinoHljs]
});
```
and it went well.
But this still feels a little weird. Why do I have to import a language when it is already specified elsewhere that arduino relies on cpp? I believe this should be done automatically when registering a derived language. But maybe I am missing something, am I?

**Comment by marcoscaceres** [comment]
No, you are right... what might be good fix is to make sure arduinoHljs is importing cpp.

**Comment by yyyc514** [comment]
The problem is HighlightJS would have no way to know WHERE the CPP was imported at, right?  Thoughts?

```
hljs.registerLanguage('cpp', cppHljs);
```

This works because YOU know the CPP is available in the variable cppHljs.  When Highlight.JS loads the Arduino syntax file all it knows is that it depends on "cpp".

Thoughts?

**Comment by yyyc514** [comment]
> But this still feels a little weird. Why do I have to import a language when it is already specified elsewhere that arduino relies on cpp?

Isn't import a keyword not a statement?  Can JS randomly import things dynamically?  I haven't played around too much with runtime modules, usually I compile everything down to one static file.

The whole "export/import" nature of the module system makes this kind of thing hard... We could perhaps make the API simpler though:

```js
import cppSyntax from 'highlight.js/lib/languages/cpp';
import arduinoSyntax from 'highlight.js/lib/languages/arduino';

hljs.registerLanguage(
  cppSyntax,
  arduinoSyntax)
hljs.configure({
  languages: ["arduino"]
});
```

So you just import them and register them, but you'd still be on your own to import them.

**Comment by yyyc514** [comment]
Potential docs issue?

**Comment by yyyc514** [comment]
Actually a simpler fix might be a small console error:

```
"Sorry: Arduino depends on and requires the `cpp` language to be loaded first.
```
