### ISSUE TITLE
Several SQL keywords missing taht are supported by traditional RDBMS and BigData Platforms

### ISSUE THREAD

**Issue by MichaelReichertOnGitHub** [highlightjs/highlight.js#1907]
Using language `sql` some keywords used by traditional and new SQL constructs are not highlighted. These constructs are supported by traditional RDBMS, e.g. IBM DB2, and BigData platforms like Spark (SparkSQL):
* The keyword `values` can start a so-called *values statement*.  The list of `beginKeywords` has to be updated.
* The keyword `all` supported by set opersations.
* The keywords `bucket` and `tablesample` used to specify table sampling.
* The SQL function `explode` is not recognized.
* The keywords `hours`, `minutes`, and `seconds` used to specify a time interval.
* The keyword `lateral` used in *lateral view* specification.
* The keyword `semi` used in *semi  join* definitions.
* The keyword `window` used in *window functions*.
* The numerical data type `tinyint`.

**Comment by marcoscaceres** [comment]
Thanks for gathering the list @MichaelReichertOnGitHub. Any chance you'd want to do a PR and add them to: 

https://github.com/highlightjs/highlight.js/blob/master/src/languages/sql.js#L24

**Comment by marcoscaceres** [comment]
@MichaelReichertOnGitHub, did you make a fork? Let me know if you are having git issues and happy to help.

**Comment by MichaelReichertOnGitHub** [comment]
@marcoscaceres I created PR https://github.com/highlightjs/highlight.js/pull/1908 to merge changes from branch `fix_issue_1907` in my fork to `master`. Please kindly advise.

**Comment by yakov116** [comment]
This issue can be closed it was fixed by #1908
