### ISSUE TITLE
EXCEL VBA

### ISSUE THREAD

**Issue by hiromi3** [highlightjs/highlight.js#1909]
Hello,
I looked around the languages that highlight.js supported and I could not find Excel VBA.
Do you have any plan to add VBA ? or Am I misunderstanding?

**Comment by marcoscaceres** [comment]
hi @hiromi3, languages are contributed by community members, the core team generally just maintain the core code - so we wouldn't plan to add support for it ourselves. However, if you or anyone in the community would like to contribute it and maintain it, we wouldn't hesitate to take it.

**Comment by hiromi3** [comment]
Hi marcoscaceres,
Thank you for your quick reply.
Ok, I will use VBScript for VBA code.
