### ISSUE TITLE
(python) block comments not highlighted

### ISSUE THREAD

**Issue by jookyboi** [highlightjs/highlight.js#1918]
Hi,

Our snippet organizer (www.cacher.io) uses highlight.js behind the scenes. A user reported the following issues with its Python highlighting:

https://support.cacher.io/hc/en-us/community/posts/360032397692-Improved-Code-Syntax-Highlighting-Python-

**Comment by yyyc514** [comment]
Please confirm this is still an issue. From a quick check it seems this should be highlighted as a string now.  If it's still an issue a jsfiddle showing the problem reproduced would be very helpful.

Quick template you could fork:
https://jsfiddle.net/ajoshguy/nagkqytv/

**Comment by yyyc514** [comment]
Ping.

**Comment by jookyboi** [comment]
@yyyc514 Looking.

**Comment by jookyboi** [comment]
Looks like it's been fixed. Thanks.

**Comment by yyyc514** [comment]
Awesome. Thanks for checking.
