### ISSUE TITLE
Lua long string incorrect - Need to capture begin pattern.

### ISSUE THREAD

**Issue by bakpakin** [highlightjs/highlight.js#1927]
Lua long string and comments are incorrect. The language syntax seems to expect that the delimiters needed to be paired, which is not the case.

Example:

```lua
--[===[
This a comment
]==]
This is still a comment, but not recognized as such by highlight.js
]===]

local function more(...)
  return
end
```
I encountered this issue while trying to add syntax highlighting for my own language, and was looking at other examples. Is there anyway to reference captures in the begin pattern in the end pattern?

**Comment by egor-rogov** [comment]
Well, the requested feature was discussed in https://github.com/highlightjs/highlight.js/pull/1897#issuecomment-434832000 but it's not likely to be implemented.

Currently you can use `endSameAsBegin` attribute. An example can be found in `pgsql` language, and description is in `docs/css-classes-reference.rst`.

**Comment by bakpakin** [comment]
Ok, thanks then. I'll close this.
