### ISSUE TITLE
Cant deal namespace {class{}} in php

### ISSUE THREAD

**Issue by m4p1e** [highlightjs/highlight.js#1933]
in highlight.js
```
{
            bK: "namespace",
            e: ";",
            i: /[\.']/,
            c: [e.UTM]
}
```
for php namespace
when my code is like 
```
namespace test/test{
     class mytest{}
}
```
`namespace` not end with ;
the `class` keyword will become `hljs-title`  not the `hljs-keyword`

**Comment by yyyc514** [comment]
Can you confirm this is still an issue and perhaps provide a jsfiddle if it is?

Template:
https://jsfiddle.net/ajoshguy/nagkqytv/

What would a naked class (with one or two functions) look like?  Is the problem perhaps that it's thinking the class is a function name?

**Comment by m4p1e** [comment]
seem work well now , awk  a year has passed :(

**Comment by yyyc514** [comment]
Ok if this has been fixed in the intervening time, then closing this. :-)
