### ISSUE TITLE
Regex issue in Cloudflare link (not present in jsdelivr link)

### ISSUE THREAD

**Issue by JayWett** [highlightjs/highlight.js#1938]
When using the recommended Cloudflare link to the library, syntax highlighting doesn't work because of an apparent regex bug. (See screenshot below from latest version of Chrome on macOS High Sierra--both Safari and Firefox display the same behavior.) 

Using the jsdelivr link resolves the problem. 

<img width="1268" alt="screen shot 2019-01-06 at 6 31 25 pm" src="https://user-images.githubusercontent.com/18277824/50746187-bf395f00-11e2-11e9-9f89-c9c9fad5222e.png">

**Comment by marcoscaceres** [comment]
oh, looks like an encoding issue...

**Comment by marcoscaceres** [comment]
As a temporary fix, can you try adding: `charset="UTF-8"` attribute  to the `<script>` tag and see if that fixes it?

**Comment by JayWett** [comment]
This does solve the problem. I will continue to use the jsdelivr link, but this is a good fix.

Thanks Marcos!

**Comment by marcoscaceres** [comment]
Awesome, thanks for checking. I've updated the README to include the attribute.

**Comment by JayWett** [comment]
Well done sir. Amazon-level "customer service".
