### ISSUE TITLE
leading space remove problem

### ISSUE THREAD

**Issue by hiromi3** [highlightjs/highlight.js#1942]
Hello,
for example,
when I write a simple code like below,
&lt;pre&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;foo
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;bar
&lt;/pre&gt;

highlight.js removes leading spaces of the first line.
Then the result is,

foo
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;bar

I tried several languages, but highlight.js always removes the leading spaces in pre tag.
So, if code has space indentation, only the first line does not match to others indent positon.
Is this normal behaviour?
Can I disable this behaviour?

**Comment by egor-rogov** [comment]
Hi @hiromi3 
No I don't think it's normal, but I can't reproduce it. Can you provide minimal working example (an html page that demonstrates the issue)?

**Comment by hiromi3** [comment]
Hi egor-rogov
Thank you for your reply.
I found a cause of the problem.
highlight.js has no problem.
The html minifier I am using removes the spaces.
Sorry!
