### ISSUE TITLE
it doesn't work well with '=> & jsx' in some cases

### ISSUE THREAD

**Issue by yjzzcao** [highlightjs/highlight.js#1943]
If the => returns JSX directly, it will fail to parse

![image](https://user-images.githubusercontent.com/2212428/51229949-3caa5f80-1999-11e9-83d0-c159a07828a3.png)

parse result
```
exception: <span class="hljs-function"><span class="hljs-params">props</span> =></span> <div>{props.type}<<span class="hljs-regexp">/div>,</span>
```

if use return, it would be well.

![image](https://user-images.githubusercontent.com/2212428/51230365-ab3bed00-199a-11e9-8f60-a137e4ce2268.png)

how to fix the bug

**Comment by yyyc514** [comment]
From what I can see this should have been resolved by #2024.  Please let us know if it has not been.  Closing.
