### ISSUE TITLE
[Feature request] Ability to copy code and switch between light and dark

### ISSUE THREAD

**Issue by Extarys** [highlightjs/highlight.js#1944]
A small toolbar which allow the user to switch between dark and light theme and copy the code would be very useful.

I wasn't able to find anything online about this.

**Comment by tovic** [comment]
Sorry but in my opinion, that feature would be too broad. You could simply combine `highlight.js` with `clipboard.js`.

Simple code to toggle between dark and light can be achieved like this:

~~~ .html
<style>
pre code {background:#fff;color:#000}
pre code.dark {background:#000;color:#fff}
</style>
<pre><code>
<a href='javascript:;" onclick="this.parentNode.classList.toggle('dark');">toggle</a>

Code snippet goes here...

</code></pre>
~~~

**Comment by Extarys** [comment]
Ohhhhh thanks! :heart:
