### ISSUE TITLE
(csharp) Reference path in inheritance breaks highlighting

### ISSUE THREAD

**Issue by svd-sea** [highlightjs/highlight.js#1947]
The following snippet breaks the highlighting:

`public class AgentTryout : System.Windows.Forms.Form { }`

without reference path, it works as expected:

`public class AgentTryout : Form { }`

**Comment by yyyc514** [comment]
What are you expecting that "System.Windows.Forms.Form" is a single title, or 4 titles separated by .s?

**Comment by yyyc514** [comment]
This is because we don't think TITLEs can contain .s...  or it could be that the space between them can contain dots and you have 4 titles, hence my question.

```js
{
        beginKeywords: 'class interface', end: /[{;=]/,
        illegal: /[^\s:,]/,
        contains: [
          hljs.TITLE_MODE,
          hljs.C_LINE_COMMENT_MODE,
          hljs.C_BLOCK_COMMENT_MODE
        ]
      },
```

**Comment by xp44mm** [comment]
the class `AgentTryout` inherit from  class `System.Windows.Forms.Form`. `:` represents inherit.

**Comment by xp44mm** [comment]
What are you expecting that "System.Windows.Forms.Form" is a single title, or **4 titles separated by .s**?
the `.` same as `javaScript`.

**Comment by yyyc514** [comment]
I'd think a single title... I think all the .s being different colors would be annoying.
