### ISSUE TITLE
Question: highlighting stars in markdown bold text

### ISSUE THREAD

**Issue by javisperez** [highlightjs/highlight.js#1953]
Hello 👋 !

I dont know if theres any other place to ask questions rather that opening an issue but i couldnt find any place.

i'm trying to highlight the stars on a bold text on markdown but im not sure that's possible, here's how I'm trying:

```
{
        className: "strong",
        begin: "\\*{2}.+?\\*{2}",
        returnBegin: true,
        contains: [
          { className: 'symbol', begin: /\*\*/ },
        ]
}
```

that does work for the opening stars but not for the closing ones (which makes sense). Is there anyway to tell highlightjs to look for that same patter as closing too?

Thanks!

**Comment by egor-rogov** [comment]
Hi,
```js
{
        className: "strong",
        lexemes: hljs.IDENT_RE + '|\\*\\*',
        begin: /\*\*/, end: /\*\*/,
        keywords: { symbol: '**' }
}
```
should do the trick.

**Comment by javisperez** [comment]
Wow, worked like a charm!  I guess i need to understand better the docs, thank you a lot!
