### ISSUE TITLE
Arduino Syntax

### ISSUE THREAD

**Issue by komputronika** [highlightjs/highlight.js#1959]
I do not see support Arduino language. 
Yes, it is C/C++. But Arduino has it's own language structure and standard functions. 
I hope you will add support for Arduino.
Thanks.

**Comment by marcoscaceres** [comment]
If there are special reserved keywords, etc. we could probably just enhance or extended the c++ definition. As always, a pull request (or even a list of differences here) would be welcome and we could go from there.

**Comment by yyyc514** [comment]
We have Arduino now, take another look.  `arduino.js`

@komputronika 

Not sure when it was added.
