### ISSUE TITLE
Idea: `hljs.options`

### ISSUE THREAD

**Issue by tovic** [highlightjs/highlight.js#1969]
I like the idea of being straight-forward and simple, as how you don&rsquo;t accept about the idea of adding line numbers feature. To be straight-forward means to be framework-agnostic. But as I have observed, _HighlightJS_ has a lack for getting the global configure(d) data to be used by 3rd party extensions.

A simple example is [here](https://github.com/wcoder/highlightjs-line-numbers.js/blob/master/README.md#options). Someone creates a line-number plugin with some options available, but it has options passed to the trigger method instead of getting them from the global options provided by the core. Which is not ideal because it does not follow the core pattern.

It would be good to add a feature for getting the global configuration data so that the API can be standardized like this:

~~~ .js
hljs.configure({
    tabReplace: '    ',
    forceLineNumberOnSingleLine: true
});
// or `hljs.setOptions({ ... })`
// but it will break the overall API unless `setOptions` will be added only as an alias method  for `configure`
// naming things is hard :(

hljs.initHighlighting();
hljs.initLineNumbers();
~~~

I think you need to add some methods to get the current configuration data so that it can be used by other extension as well. Example:

~~~ .js
hljs.getOptions = function() {
    return options;
};
hljs.getOption = function(name) {
    return options[name];
};
~~~

Usage:

~~~ .js
hljs.initLineNumbers = function() {
    var options = this.getOptions();
    if (options.useBR) { ... }
};

hljs.registerLanguage("yaml", function($) {
    if ($.getOption('tabReplace') === '    ') { ... }
});

// etc.
~~~

Or&hellip; simply put the `options` variable to the `hljs` object as the most safe solution (no need to add, remove or rename things):

~~~ .js
hljs.options = { ... };

// ...

hljs.initLineNumbers = function(override) {
    var options = Object.assign(this.options, override);
};
~~~

Thanks.

**Comment by yyyc514** [comment]
I think (off the top of my head) I'd rather see plugins "wrap" us... if we start handing out our internal state then we need to worry about deep vs shallow cloning it (to prevent the external from mucking with our state), etc...

I'm not sure it's our job to act as configuration central for plugins.  

The idea of configurable grammars is interesting, but of course that would be a very new idea... none of the grammars (that I'm aware of) currently are much more than data...  They do not make decisions and change their behavior based on configuration options.

**Comment by yyyc514** [comment]
I glanced at the line number plugin, looks simple and easy.  Not sure how it would be much enhanced by something like this.

**Comment by yyyc514** [comment]
Closing this out as an individual issue, but going to link it over in the Plugin thread since it might prove useful to reference in the future as part of that larger effort.
