### ISSUE TITLE
Custom separators for values inside tags

### ISSUE THREAD

**Issue by adelarsq** [highlightjs/highlight.js#1973]
When rendering a tag with multiple values separated by some custom char (in this case e-mails) the rendering appears wrong:

![captura de tela_2019-02-14_11-39-16](https://user-images.githubusercontent.com/430272/52790452-bb082900-304d-11e9-925a-9757497cd203.png)

It's possible to support custom separators inside tags?

**Comment by yyyc514** [comment]
Please provide details on which language you're using.  A jsfiddle would actual code be even better.

Template you can use:
https://jsfiddle.net/ajoshguy/nagkqytv/

**Comment by yyyc514** [comment]
Ping.

**Comment by adelarsq** [comment]
I can't reproduce the problem. I was using with XML. I will close this since can be a problem with other lib.

**Comment by yyyc514** [comment]
Yeah, XML is pretty simple, that'd be a strange issue.  Its' also possible it's been fixed since Feb 14 when you submitted.

Thanks!
