### ISSUE TITLE
add support for mathematica

### ISSUE THREAD

**Issue by natestemen** [highlightjs/highlight.js#1975]
there exists some projects which have gotten the grammar like https://github.com/halirutan/Mathematica-Source-Highlighting.

Would be cool if this project could implement something similar so mathematica code could make it's way onto the internet while being pretty 🌟

**Comment by egor-rogov** [comment]
Actually highlight.js supports Mathematica.

**Comment by natestemen** [comment]
It does? I was looking on https://highlightjs.org/static/demo/ and couldn't find any. could you point me to a demo?

**Comment by egor-rogov** [comment]
Yeah. Choose scientific language category on that page.

**Comment by natestemen** [comment]
wonderful. thank you!
