### ISSUE TITLE
Python recognized as Makefile

### ISSUE THREAD

**Issue by kernc** [highlightjs/highlight.js#1976]
(Originally reported in https://github.com/pdoc3/pdoc/issues/32.)

The following `<pre><code>` is recognized as Makefile instead of Python ([live example](https://jsbin.com/jejirufeke/2/edit?html,output)).
```html
<!DOCTYPE html>
<html>
<head><meta charset="utf-8">
  
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.14.2/styles/default.min.css">
  <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.14.2/highlight.min.js"></script>
  <script>hljs.initHighlightingOnLoad();</script>
  
</head>
<body>

<pre><code>

#!python
import constraintanalysis as ca
import atmospheres as at
import unitconversions as co

designbrief = {'stloadfactor': 2, 'turnalt_m': 3050, 'turnspeed_ktas': 140}

etap = {'turn': 0.85}

designperformance = {'CLmaxclean': 1.45, 'CDminclean': 0.02541,
                     'etaprop': etap}

designdef = {'aspectratio': 10, 'sweep_le_deg': 2,
             'sweep_mt_deg': 0, 'bpr': -1}

TOW_kg = 1500

designatm = at.Atmosphere()
concept = ca.AircraftConcept(designbrief, designdef,
                             designperformance, designatm)

wingloading_pa = 1000

twreq, _, _ = concept.twrequired_trn(wingloading_pa)

turnspeed_mpstas = co.kts2mps(designbrief['turnspeed_ktas'])

pw_trn_wpn = ca.tw2pw(twreq, turnspeed_mpstas, etap['turn'])
pw_trn_hpkg = co.wn2hpkg(pw_trn_wpn)
p_trn_hp = pw_trn_hpkg * TOW_kg

print(p_trn_hp)

</code></pre>

  </body>
</html>
```
I believe hanging-indented lines containing **spaces instead of tabs (`\x09`) should exclude Makefile** altogether.

**Comment by yyyc514** [comment]
> I believe hanging-indented lines containing spaces instead of tabs (\x09) should exclude Makefile altogether.

Can you elaborate?  Do Makefiles alway force tabs?  That's not something that's guaranteed to come thru in code snippets online though... they might have already gone thru a few different translation processes so I don't think we can necessarily expect their to be LITERAL tabs in the content.

**Comment by kernc** [comment]
> Do Makefiles alway force tabs?

For indentation, [yes](https://en.wikipedia.org/wiki/Makefile#Rules). Weird errors otherwise. :sweat_smile: 

> That's not something that's guaranteed to come thru in code snippets online though... they might have already gone thru a few different translation processes

Right, haven't really thought of that. Then again, most verbatim blocks should preserve all contained characters.


---
Alternatively, Makefile might be set to lower priority compared to Python (which for above snippet also triggers)?

**Comment by yyyc514** [comment]
> Right, haven't really thought of that. Then again, most verbatim blocks should preserve all contained characters.

I'm not worried so much about the browser (though I haven't tested) as actually like how snippets might end up there in the first place, copied and pasted, etc... 

> Alternatively, Makefile might be set to lower priority compared to Python (which for above snippet also triggers)?

How would we set those priorities? :-)  Right now the tuning of the auto-detect stuff  (which is the only priority system we have) is all a bit of dark magic. :-)

**Comment by kernc** [comment]
Copy-pasting [should](https://stackoverflow.com/questions/1929812/how-does-cut-and-paste-affect-character-encoding-and-what-can-go-wrong) also preserve characters! :stuck_out_tongue: 

> dark magic

Where is that, approximately?

**Comment by yyyc514** [comment]
> Where is that, approximately?

Are you taking back the question? LOL.

> Copy-pasting should also preserve characters! 

You'd think, but I was imagining other ways of getting the content to the page also not just copy/paste... if you want to play around with tabs vs spaces and if that might help out, feel free and report your findings. :-)

**Comment by yyyc514** [comment]
You gave me this idea though: https://github.com/highlightjs/highlight.js/issues/2174

**Comment by yyyc514** [comment]
Out of curiosity what is the context where you simply couldn't tell it the snippet was python?

**Comment by kernc** [comment]
Simple indented markdown code block (https://github.com/pdoc3/pdoc/issues/32). The user was able to workaround with a fenced code block.

Shebangs do give a clue, I was also thinking of that, but now it seems of too little benefit assuming only very few code snippets contain shebangs. :confused:

**Comment by kernc** [comment]
I just thought it a makefile plugin bug. For `text` from example.
<details>

```js
text = `#!python
import constraintanalysis as ca
import atmospheres as at
import unitconversions as co

designbrief = {'stloadfactor': 2, 'turnalt_m': 3050, 'turnspeed_ktas': 140}

etap = {'turn': 0.85}

designperformance = {'CLmaxclean': 1.45, 'CDminclean': 0.02541,
                     'etaprop': etap}

designdef = {'aspectratio': 10, 'sweep_le_deg': 2,
             'sweep_mt_deg': 0, 'bpr': -1}

TOW_kg = 1500

designatm = at.Atmosphere()
concept = ca.AircraftConcept(designbrief, designdef,
                             designperformance, designatm)

wingloading_pa = 1000

twreq, _, _ = concept.twrequired_trn(wingloading_pa)

turnspeed_mpstas = co.kts2mps(designbrief['turnspeed_ktas'])

pw_trn_wpn = ca.tw2pw(twreq, turnspeed_mpstas, etap['turn'])
pw_trn_hpkg = co.wn2hpkg(pw_trn_wpn)
p_trn_hp = pw_trn_hpkg * TOW_kg

print(p_trn_hp)`
```
</details>

The makefile relevance just seems overzealous:
```js
hljs.listLanguages()
    .map(name => name + '\t\t' + hljs.highlight(name, text, false).r)
    .toString().replace(/,/g, '\n')
```
```text
apache		0
bash		15
coffeescript		21
cpp		0
cs		17
css		0
diff		0
http		0
ini		0
java		0
javascript		20
json		0
makefile		25
xml		0
markdown		1
nginx		0
objectivec		0
perl		15
php		18
python		21
ruby		14
shell		2
sql		0
```

**Comment by yyyc514** [comment]
Many of the languages will seem overzealous for given samples... it's very hard to do magic auto-detection of languages and get it right 100% of the time.

**Comment by yyyc514** [comment]
If you think you have ideas or answers I"d love to hear them or see sample code.

**Comment by yyyc514** [comment]
@kernc Out of curiosity did you look to see HOW makefile is getting all that relevance?

**Comment by kernc** [comment]
I don't have a JS debugging environment set up. But I supposed that's the way to go about it. :smile:

**Comment by yyyc514** [comment]
Root cause here is Makefile earned lots of points for simple assignment operations, which is a little silly. PR improves this situation greatly.
