### ISSUE TITLE
bash: nested variables only partially highlighted

### ISSUE THREAD

**Issue by DerPoet** [highlightjs/highlight.js#1978]
In a bash script, you may have a variable WURST und refer to it via $WURST or ${WURST}.
You can supply a default value ${WURST:-salami} and that default value may itself be a variable
${WURST:-${CARNE}}. And this is where there's a bug in highlight.js:
In the last example, of the two closing curly braces at the end only the first one gets color, the latter one doesn't -- although it should because it is the closing brace to the very first opening curly brace.

**Comment by yyyc514** [comment]
This is because we don't currently support deep nesting like that in the grammar.

**Comment by yyyc514** [comment]
Closing this as a dup of #2099.
