### ISSUE TITLE
Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

### ISSUE THREAD

**Issue by TuguldurJ** [highlightjs/highlight.js#1990]
When installing this package via NPM, I get the following warnings and errors:
`npm install highlight.js vue-highlight.js`
> npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated hoek@0.9.1: The major version is no longer supported. Please update to 4.x or newer
npm ERR! path /Users/******/node_modules/highlight.js/tools/build.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod '/Users/******/node_modules/highlight.js/tools/build.js'
npm ERR! enoent This is related to npm not being able to find a file.

This is not [vue-highlight.js](https://github.com/gluons/vue-highlight.js/issues/15#issuecomment-467049409) issue.

**Comment by ritikasib** [comment]
same issue faced

**Comment by slinkardbrandon** [comment]
Yeah I'm facing the same problem and I'm not using vue at all.

**Comment by marcoscaceres** [comment]
Duplicate of #1984

**Comment by Cherry** [comment]
I think this may have been erroneously marked as a duplicate.

9.14.2 had no dependency deprecation warnings, whereas 9.15.5 where installed without any other packages reports:
```
npm install highlight.js
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated hoek@0.9.1: The major version is no longer supported. Please update to 4.x or newer
```

This then results in `npm audit` reporting `25 vulnerabilities (6 low, 11 moderate, 8 high)`. Some of these packages look to only be used in `tools` or `tests` - do they need to be shipped as dependency, creating these audit issues.

**Comment by Cherry** [comment]
Actually looks like this may be a duplicate-ish of #1369, sorry. It wasn't a big issue in the past as the build deps weren't shipped with the release, but that seems to have changed with 9.15.x.

**Comment by marcoscaceres** [comment]
Can leave this open and close it when we actually deal with #1369.

**Comment by marcoscaceres** [comment]
Fixed in 9.15.6

**Comment by TuguldurJ** [comment]
Thank you! @marcoscaceres

**Comment by marcoscaceres** [comment]
As a bonus, we fixes all the outdated dependencies by forking gear and gear-lib :) We only have 1 low severity security warning 🎉

**Comment by TuguldurJ** [comment]
You guys worked very well, I will go ahead with [highlight.js](https://github.com/highlightjs/highlight.js)
Thank you!
