### ISSUE TITLE
Unnecessary dependencies installed with 9.15.x

### ISSUE THREAD

**Issue by Filipoliko** [highlightjs/highlight.js#1993]
Hi,
I ran into a problem with the latest version of highliht.js. You have moved all the devDependencies to dependencies. I checked the packages and dont see any reason why this should have been done, since all of them are used in tools, or tests only and they are not necessary dependencies to use the highlight.js.

This update caused us an error in build, when using gulp-less package to install less. For some reason your dependency gear-lib forced our project to use less version 1.7.5 (instead of 2.x || 3.x versions from gulp-less) and this made our build fail. As workaround we freezed the less version in our project, but it would be great if you moved these dependencies back to devDependencies.

Or is there any reason for this move?

Thanks for hearing me out and for your work!

**Comment by mzyil** [comment]
I'm also getting async v0.8.0 installed as a dependency of gear-lib which breaks functionality of different modules. The broken module (botbuilder-unit) didn't have async as its dependency because it was a dependency of its dependency. Talk about bad practices...

**Comment by marcoscaceres** [comment]
Ok, will get those moved to devDependencies.

**Comment by realityking** [comment]
I appreciate the idea of making the build script accessible via the npm package. Have you considered turning the CLI into its own npm package? It would cut down on dependencies for those folks who don't need it.

I know time is scarce for this project, I'm happy to help get this set up.

**Comment by marcoscaceres** [comment]
I've sent a PR for this https://github.com/highlightjs/highlight.js/pull/1995

@realityking, that's a good suggestion. However, I think it might be best to not bother with the builder as the js files can be imported into projects (allowing for other bundlers to do their thing)... I'd be more interested investing time into converting the code into ES6 modules.
