### ISSUE TITLE
Support for git?

### ISSUE THREAD

**Issue by ddzy** [highlightjs/highlight.js#2005]
## Expected Feature
Hey, i want to add `git` commands to my docs. but it seems doesn't highlighted. 
![issue_1](https://user-images.githubusercontent.com/33921398/54174508-cec67400-44c1-11e9-804b-603a8e604361.png)
![issue_2](https://user-images.githubusercontent.com/33921398/54174509-cec67400-44c1-11e9-9aa1-b686d01b4a69.png)
How can i do?

**Comment by marcoscaceres** [comment]
Seems no one has written a highlighter for git. I don’t see it in our languages folder.
