### ISSUE TITLE
`.hljs` class not getting applied to root container.

### ISSUE THREAD

**Issue by pmkroeker** [highlightjs/highlight.js#2009]
I'm using highlight.js with marked.js in a preact environment to add some syntax highlighting. It seems though that the root class of `hljs` is not being applied to the root node that highlight returns.

**Comment by marcoscaceres** [comment]
@pmkroeker, we've probably need a bit more context to see what's going on. Do you have some sample code somewhere?

**Comment by pmkroeker** [comment]
I was using it with markedjs, and I think it was something with how marked was parsing things. I'll close this issue as I think its probably more of a marked thing than highlight
