### ISSUE TITLE
Sass syntax bug

### ISSUE THREAD

**Issue by TheJaredWilcurt** [highlightjs/highlight.js#2011]
It highlights the `round` in `Background` and makes it blue. Weird. just reporting it

```sass
@function blackOrWhiteTextFromBackground ($backgroundColor)
    @if (lightness($backgroundColor) > 50)
        @return $black
    @else
        @return $white
```

**Comment by yyyc514** [comment]
Is this still an issue?  Can you make Fiddle reproducing the issue?

Template: 
https://jsfiddle.net/ajoshguy/nagkqytv/
