### ISSUE TITLE
Support for SEPL

### ISSUE THREAD

**Issue by Wunder-Wulfe** [highlightjs/highlight.js#2015]
Would you guys mind adding support for a very simple programming language I created?
Thanks!
[SEPL](https://prodogtive.000webhostapp.com/)
Every keyword and etc is in the documentation directly below on the page.
It's based on a mix of languages like assembly and lua. A lot of stuff will be added later on but it would not need too much maintainability.

**Comment by marcoscaceres** [comment]
Hi @Wunder-Wulfe, they maintainers don't usually create language definitions. We rely on the community to create them. We are also asking folks to externally host new languages in their own repositories.

**Comment by Wunder-Wulfe** [comment]
ok thank you
