### ISSUE TITLE
Allow configurability of code block HTML element (pre, code, etc.)

### ISSUE THREAD

**Issue by cup** [highlightjs/highlight.js#2019]
Currently you must use this syntax with highlight.js:

~~~html
<pre><code class="rust">fn main() {
   println!(&quot;aaaaa bbbbb&quot;);
}
</code></pre>
~~~

however other projects omit the code tag:

~~~html
<pre class="prettyprint lang-rust">
fn main() {
   println!(&quot;aaaaa bbbbb&quot;);
}
</pre>
~~~

https://github.com/google/code-prettify

**Comment by marcoscaceres** [comment]
We are following the [html spec](https://html.spec.whatwg.org/multipage/grouping-content.html#the-pre-element): 

> To represent a block of computer code, the pre element can be used with a code element;

**Comment by cup** [comment]
@marcoscaceres thank you for the reply. However that quote raises a few
thoughts:

- It says "can", not "must"

- Syntactically it seems that `<pre>` and `<pre><code>` are identical

- If that is not the case, what is the difference?

- If that is the case, I ask again, why not just use `<pre>`?

**Comment by marcoscaceres** [comment]
Definitely not against it, just pointing out the reasoning as `<code>` can be highlighted inline without a pre. PR would be welcome to add support for it.

**Comment by yyyc514** [comment]
In my opinion: keep the behavior the same as it's always been. Which avoids a need to change the docs, add edge cases, etc.

**These tags are NOT interchangeable:**

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/code
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/pre

They mean different things semantically, and that is why they are so commonly paired and I presume also why we pair them.  Quoting MDN:

> The HTML <pre> element represents preformatted text which is to be presented exactly as written in the HTML file. 

> The HTML <code> element displays its contents styled in a fashion intended to indicate that the text is a short fragment of computer code.

**Comment by yyyc514** [comment]
IF we were to support this though it'd probably be minimally invasive... you'd just add an option to change "codeBlockMatchSelector" (or some better name)... start with the default of 'pre code' but if you set it to 'pre' then you'd have the requested behavior. No muss no fuss. :-)

**Comment by cup** [comment]
@yyyc514 I am not (and never was) making the point that `<pre> = <code>`. I would think that would be obvious.

The point is that, essentially, `<pre> = <pre><code>`.

**Comment by yyyc514** [comment]
> The point is that, essentially, <pre> = <pre><code>.

**I disagree completely with that conjecture also** (semantically), and think my comment explains why.  But this would be a trivial change, so I'm slightly less opposed since seeing it's almost a one-line patch. :-)

**Comment by cup** [comment]
@yyyc514 admittedly, I didnt read your comments all the way through. However upon doing that, Im still not seeing a valid argument.

So I will ask again: assuming that its a breaking change (which Im not arguing), and assuming that this issue should be fixed even if its a breaking change (which Im not arguing), *are there any other valid reasons to keep doing* `<pre><code>`?

**Comment by yyyc514** [comment]
>  I didnt read your comments all the way through.

I'll try to not be offended. ;-)

> and assuming that this issue should be fixed even if its a breaking change (which Im not arguing)

Wait, isn't that exactly what you are arguing/suggesting - that this should be changed?

>  are there any other valid reasons to keep doing <pre><code>

I think the semantic reason is a pretty good one of course (maybe the best one)... but other reasons?  Hmmmm... 

- Consistency (with our own historical precedent)
- Consistency with how it's typically done (in my experience at least)
- One less thing to worry about when setting it up
- IE, convention over configuration.  It's gotten us this far. :-)

I think @marcoscaceres was thinking of it as an OPTION when you presented it, not as a new default. :-)

--- 

Again:  **I'm slightly less opposed now since seeing it's almost a one-line patch.**

I'd be very much against changing the default, but it's not my choice. :-)  So I've laid my case out (whatever you may think of it). :-)  Powers that be will decide. :-)  It does seems we'd be open to making it an OPTION for those who prefer it that way. :-)

**Comment by yyyc514** [comment]
FYI: This isn't really an issue, it's a feature request.

**Comment by cup** [comment]
> Consistency (with our own historical precedent)

@yyyc514 I read your last comment, and again, Ive yet to see a single valid
reason other than one could say its a breaking change.

Arguably that is a good reason, but the question is, are there any other valid
reasons?

Finish this sentence:

Regarding changing from `<pre><code>` to `<pre>`; even if you ignore that fact
that its a breaking change, its still a bad idea because...

**Comment by yyyc514** [comment]
**I've answered you fully already. :-)** I can't help it if you don't find my reasons "valid" or "persuasive".  Thankfully they're only peripherally address to you - they're really addressed to the maintainers, who I'm sure will have their own thoughts on the subject. :-)

Only so many hours in the day ya know. :-)

**Comment by cup** [comment]
Ok then, then I will maintain my position that:

*There is not valid reason to use `<pre><code>` over `<pre>` other than thats
the way it was initially done*.

Further, I would argue that `<pre>` could have been implemented from the
beginning without adverse results.

If someone has a genuine counter, I certainly want to hear it. But thats yet to
happen.

**Comment by egor-rogov** [comment]
I want to mention #2129 also. Probably we indeed should be more flexible on `pre` and `code` (but  preserve backward compatibility).
As @marcoscaceres said, a PR would be welcome.

**Comment by yyyc514** [comment]
@cup Thanks.  I believe this would solve their issues also since "pre" as a matcher would work whether or not you had a code side inside... and in their case they ALREADY want to move the class designation, so that's the sticky point that would break for most people if this wasn't opt-in.

**Comment by yyyc514** [comment]
> Further, I would argue that <pre> could have been implemented from the
beginning without adverse results.


You mean `<pre> alone` I presume... Ha, finally, something we agree on. :-)  Yes, this is definitely more of a semantic (for people who care) and legacy issue more than any real technical issue with two tags vs one. :-)

**Comment by yyyc514** [comment]
See thoughts on #1699 as well.  Should we expand this to allow both <pre><code> [or just pre] (an actual block) AND <code> (just inline code)?

**Comment by cup** [comment]
Respectfully, I dont care about this issue anymore. At the time I was looking
for a new highlighter, and have since found one:

https://github.com/alecthomas/chroma

I am unsubscribing. Good luck to all.

**Comment by yyyc514** [comment]
Good luck! @cup

**Comment by yyyc514** [comment]
Closing this as no one else seems interested and the README already shows how to do this with only a few lines of code.
