### ISSUE TITLE
(pycon) Add pycon (Python repl) support 

### ISSUE THREAD

**Issue by asmeurer** [highlightjs/highlight.js#2025]
For Python interactive sessions (with `>>>`), the output of commands is also syntax highlighted as Python. This is almost always not correct. It's generally quite distracting to have `in`, `for` and so on colored differently in output. 

For example

```py
>>> print("Ask not what your country can do for you")
Ask not what your country can do for you
```

The `not` and `for` in the output are colored (you can also see GitHub's highlighter has the same issue).

The exception might be tracebacks, but even these should be highlighted with care. Currently the line numbers and "in" from the file lines (like `  File "<stdin>", line 2, in test`) are colored. A special `pytb`/`python-traceback` language could be useful here. 

It would be better if the presence of `>>>` in Python disabled highlighting for any lines that don't start with `>>>` or `...`. Alternately, you could add a `pycon` language like Pygments.

**Comment by egor-rogov** [comment]
+1 for a new language. We already have a very similar case: `shell` language for `bash`.
Perhaps such language can deal with both general output and tracebacks.
PR is welcome (:

**Comment by mjpieters** [comment]
This should be treated as a separate language, [just like Pygments does](http://pygments.org/docs/lexers/#pygments.lexers.python.PythonConsoleLexer). I'd love to see one for Python tracebacks too.

**Comment by asmeurer** [comment]
I agree a separate language could be useful, but since `python` already handles interactive prompts, shouldn't it try to be smarter about it. I would guess most people will tag interactive Python sessions with `py`. Or should we remove interactive prompt support from `py` and require `pycon` for interactive sessions?

**Comment by yyyc514** [comment]
>  Or should we remove interactive prompt support from py and require pycon for interactive sessions?

Perhaps though this might seem helpful sometimes?  Not sure.  Seems like work could proceed on a new syntax for pycon without getting hung up on this issue.

**Comment by yyyc514** [comment]
This should be a tiny little grammar with a dependency on python and using subLanguage I'd think.... might not be more than a few lines long... how does python console do multi-line input?

**Comment by yyyc514** [comment]
Is pycon the best name though?  Is that how they refer to it in the community?

**Comment by yyyc514** [comment]
@asmeurer Look at the vbscript-html.js for inspiration.

**Comment by asmeurer** [comment]
My preference would still be for this to be built into the `python` grammar. The `>>>` used in Python prompts never appears in normal Python code, so there is no ambiguity. The only reason I would split it is if it's not technically possible to not highlight lines that don't start with `>>>` or `...` in the presence of them.

**Comment by yyyc514** [comment]
It might be technically possible but I’m pretty sure it would be strange and convoluted and overly complicate the grammar.  _If you can show us it’s doable with a tiny patch I’m sure we’d be happy to at least consider the idea._

**Comment by mjpieters** [comment]
> My preference would still be for this to be built into the `python` grammar. The `>>>` used in Python prompts never appears in normal Python code, so there is no ambiguity. The only reason I would split it is if it's not technically possible to not highlight lines that don't start with `>>>` or `...` in the presence of them.

The prompts are not the issue, the *echoed output outside the prompts* are the problem.

E.g.

```python
>>> v = "foo = 42"
>>> v
"foo = 42"
>>> print(v)
foo = 42
>>> print(repr(v).rstrip('"'))
"foo = 42
>>> print(repr(v).lstrip('"'))
foo = 42"
```

This bounces around a simple string and echoes it in various ways. The output here is *not Python code*, but many highlighters treat it as if it is anyway. GitHub's implementation is no different, but not too broken, the unbalanced quotes don't throw it too much. Yet the `foo = 42` output is highlighted as if it is Python code.

Rouge handles consoles in an interesting way; they don't have specific Python console support, instead they have a generic `console` highlighter that's configurable; set the language to `console?lang=python&prompt=>>>,...` and anything following the configured prompt lines is treated as Python code and highlighted as such.

See [this blog post on my website](https://www.zopatista.com/python/2012/06/06/rtf-and-unicode/), which has several console sessions.

**Comment by asmeurer** [comment]
I don't think it can be done directly in the tokenizer. But does highlight.js have the abstraction to allow language=python to do some logic like

- If the first three non-whitespace characters are `>>>`, apply python-console highlighting
- Otherwise, apply python highlighting. 

At the end of the day, I'm writing Markdown, and I just want ```python to do the right thing no matter if it's Python code or Python console output. I don't care at what level that happens under the hood. 

But if it's too complicated to make it "magically" work I understand. The first priority would be some highlighter that works for console output at all, so that you can highlight the code parts but avoid faulty coloring like in my example in the OP.

**Comment by asmeurer** [comment]
A general console environment sounds like a good idea. That way one could easily support things like IPython console output as well (assuming the `prompt` can be a regular expression). And I imagine there's some finicky logic required to make multiline strings work correctly that you wouldn't want to duplicate.

(I also noticed GitHub doesn't do the right thing here. If you look closely below, the first continuation prompts are colored black, like they are part of the string. Maybe this isn't easy to actually do)

```py
>>> """
... abc 
... """
>>> def test():
...     pass
```

**Comment by yyyc514** [comment]
> The prompts are not the issue, the echoed output outside the prompts are the problem.

I'm clear on what the problem is.  My suggest was a grammar that treats all `>>>` and `...` lines as Python code and ignores the rest.  It would be trivial to build this BASED on python on a sublanguage.  Which is what I've recommend.

> But does highlight.js have the abstraction to allow language=python to do some logic like

Language definitions are just a list of rules to be applied, not "logic" per se.

> If the first three non-whitespace characters are >>>, apply python-console highlighting  Otherwise, apply python highlighting.

I'm not sure what the difference is between "python-console" and "python" highlighting.  I assume you want:

```
>>> colored code
... colored code
NOT colored
NOT colored
>>> colored code
```

The fastest way I can think of to get there is with a syntax that looks for >>> and ... at the beginning of lines and then declares the sublanguage to by python until the end of line.

**Comment by yyyc514** [comment]
>  set the language to console?lang=python&prompt=>>>,...

A language definition is JUST a javascript object.t.. one would write a language builder that does whatever you wanted to and then pass that language to Highlight.js.

```js
var language = doTheImpossibleLanguage(">>>","...")
hljs.registerLanguage("impossible", language)
hljs.highlight("impossible", source)
```

**Comment by yyyc514** [comment]
> Rouge handles consoles in a much more interesting way; they don't have specific Python console support, instead they have a generic console highlighter that's configurable; set the language to console?lang=python&prompt=>>>,... and anything following the configured prompt lines is treated as Python code and highlighted as such. This makes it behave entirely correctly for Python console output. Only traceback highlighting support would improve it.

You could wrap that type of thing up as a tiny JS function inside your language definition.  If we saw it was a useful pattern over time for a lot of REPLS then we'd consider bundling it into the core library.

There has also been some talk about plugins lately, but I'm not sure off the top of my head how you'd do this as a plugin... but it'd be SUPER easy as a dynamic language loader (at init time):

```
hljs.registerLanguage(replLanguageGenerator("python",">>>"))
```

Where your function would build a dynamic function that when called would generate and return a REPL mode that was keyed off of ">>>".

> Only traceback highlighting support would improve it.

That is the gotcha I think... very quickly you start to want more than the "bare minimum"...

**Comment by yyyc514** [comment]
Anyone want to actually work on this for .12 release in 6 weeks or so?

**Comment by raacampbell** [comment]
How about iPython support? This lacks the `>>>` prompts and doesn't work with the existing `python-repl` highlighting.

**Comment by joshgoebel** [comment]
You'd have to open a separate issue and explain what that is... and we'd have to see if it fits in the scope of the existing grammar or not.

**Comment by asmeurer** [comment]
If I understand https://github.com/highlightjs/highlight.js/pull/2413/files#diff-97413583814a425e51c22e01786347bc186ef95c80113475c01f26ee9b351441R23-R24 it should just be a question of adding a couple of regular expressions to match `In [1]:` and `  ...:` prompts. See https://ipython.readthedocs.io/en/stable/. It's fairly commonly used for Python examples on various webpages.

**Comment by raacampbell** [comment]
Yes, that's why I added it here: @joshgoebel it's a very common Python REPL environment. The prompts are usually colour-coded:

<img width="629" alt="image" src="https://github.com/highlightjs/highlight.js/assets/5427811/53f1b5da-b5e9-470d-a241-e71a856999ae">

In Python scientific computing it's ubiquitous. Nobody uses the vanilla Python prompt. IDEs like Spyder and PyCharm integrate an iPython console. It would be useful to have the syntax highlighting available in highlight.js

I can still start a separate issue.

**Comment by joshgoebel** [comment]
> I can still start a separate issue.

Yes, and a bit lengthier textual example (that we can copy and paste) might be nice as well.  I worry the red/green stuff might be hard as we have a single scope for this kind of thing `meta.prompt` and even if we added `meta.prompt.in` and `meta.prompt.out` no built-in schemes would support those and you'd get the existing singular `meta.prompt` theming.

But happy to explore in another topic.  Pattern matching just the prompt seems easy enough.

**Comment by joshgoebel** [comment]
<img width="813" alt="Screenshot 2023-05-28 at 12 36 44 AM" src="https://github.com/highlightjs/highlight.js/assets/6473/848aff64-9975-44f2-8890-698df14f015c">

Easy peasy.
