### ISSUE TITLE
(vbnet/vbscript?) Does not highlight correct vb code

### ISSUE THREAD

**Issue by RachamimYaakobov** [highlightjs/highlight.js#2028]
Please check [jsfiddle](http://jsfiddle.net/e1h2jym6/2/), the VB code does not accept colors in the correct places. why? Is it a bug?

**Comment by marcoscaceres** [comment]
Probably a bug. PR to fix welcome.

**Comment by yyyc514** [comment]
Could you provide a smaller example or clarify exactly what you feel is not colored correctly?

**Comment by yyyc514** [comment]
Ping.

**Comment by RachamimYaakobov** [comment]
[Here](http://jsfiddle.net/tw63jyhc/)  is a shorter example, as you can see the words: Imports, Public, Sub and other are not highlight correctly.

**Comment by yyyc514** [comment]
https://jsfiddle.net/ajoshguy/a1kntyg4/

Looks good to me.  I don't think you're loading the correct grammar extension.  Doesn't look like VB is built into the default distribution.  In my jsfiddle I load `vbnet` (as you should be doing) and the output looks MUCH better.

**Comment by RachamimYaakobov** [comment]
Your example works well with `vb`
And my example will not work with `vbnet`

**Comment by yyyc514** [comment]
I do not understand what you are saying.  You can call it "vb" or "vbnet" in the class css.  They both mean the same thing.  But you need to load the vbnet Javascript or none of it will work.

"vbnet" is the official name of the language in Highlight.js, not "vb".

**Comment by yyyc514** [comment]
![Screen Shot 2019-10-14 at 4 40 09 PM](https://user-images.githubusercontent.com/6473/66781451-4e298500-eea1-11e9-8997-00c63c110867.png)

When I load `vbnet` first it all works great.

**Comment by yyyc514** [comment]
@RachamimYaakobov **Since you are NOT loading vbnet you're just getting RANDOM highlighting** from whichever other language it might match...

- SQL one time
- "properties" another time...

Change the code, and the language it's highlighted with might change too, that's normal.

*_*If it's VB code you need to load `vbnet`_ (as my jsfiddle shows).  Otherwise "vb" means nothing and will just be ignored.**

**Comment by yyyc514** [comment]
See the instructions here: https://highlightjs.org/usage/

Please note:

> The CDN-hosted package doesn't have all the languages. Otherwise it'd be too big. If you don't see the language you need in the "Common" section, it can be added manually:

---

Closing this issue as asked and answered.
