### ISSUE TITLE
styles/school-book.css applies style to all <pre> (element selector, no classes)

### ISSUE THREAD

**Issue by tincho** [highlightjs/highlight.js#2032]
Hi there!
I'm facing a case where my bundle un-intendenly included **all** the css files from hljs/styles (that's something I ought to fix, yes, but...)

Unlike all other .css files, `school-book.css` [has a block defining styles for all `pre` elements, without any specificity](https://github.com/highlightjs/highlight.js/blob/160a57192755d6b620d896e9877abd54522c8ca7/src/styles/school-book.css#L15)

That's causing that, without initializing hljs in any way, all `<pre>` blocks are getting that yellow background image.

**Comment by marcoscaceres** [comment]
closed via https://github.com/highlightjs/highlight.js/pull/2034

**Comment by marcoscaceres** [comment]
thanks for your help on this @tincho!
