### ISSUE TITLE
Java declaration incorrectly displayed

### ISSUE THREAD

**Issue by silviomarazzato** [highlightjs/highlight.js#2033]
This Java code inside `<pre><code class="java">...</code></pre>`:

if (true) {
    Map<String, String> map = null;
    System.out.println("Hello.");
}

is displayed as:

if (true) {
    Map map = null;
    System.out.println("Hello.");
}

**Comment by marcoscaceres** [comment]
Try `Map&lt;String, String&gt;`, otherwise the String will be treated as HTML.

**Comment by silviomarazzato** [comment]
This one works. The problem is that I import the code directly from the filesystem inside the page and in this way a further replacement is necessary.

**Comment by marcoscaceres** [comment]
Unfortunately, I don’t know of any way of getting around that :(

**Comment by yyyc514** [comment]
Closing this as asked and answered: Actual HTML tags (or even just brackets) must be properly escaped or they will just be interpreted at HTML by the browser (which is a feature).

>  The problem is that I import the code directly from the filesystem inside the page and in this way a further replacement is necessary.

Import how?  Most any languages have HTML escaping libraries these days, it's a very common thing to need to do.  You'd probably solve 99% of your issues by just MANULLY writing code to replace greater than and less than with &gt; &lt; etc.
