### ISSUE TITLE
highlighting for Kotlin and plaintext does not fit pjax

### ISSUE THREAD

**Issue by ShadowySpirits** [highlightjs/highlight.js#2045]
I use 9.15.8 and I try to trigger highlighting by `hljs.highlightBlock()` in pjax callback, HTML code works fine, but kotlin code is not working properly.

The code I use in pjax callback:
```
$("pre code").each(function(i, block) {hljs.highlightBlock(block);});
```

The results I got:
![results](https://user-images.githubusercontent.com/32436597/58555461-1bf9ec80-824c-11e9-911e-d15084830de9.png)

And my website is https://blog.sspirits.top, you can check the first or second article to find out the problem.

**Comment by yyyc514** [comment]
Isn't the class supposed to be simply "kotlin" vs "lang-kotlin", or are you using auto detection?  Is Kotlin  built in language in the library you are using?  It's not built into the CDN version because of size constraints.

**Comment by yyyc514** [comment]
Ping.

**Comment by ShadowySpirits** [comment]
I change "lang-kotlin" to "kotlin" and it works. But I still don't know why "lang-kotlin" works when I don't use pjax.

**Comment by yyyc514** [comment]
Anything useful in your console log?

**Comment by yyyc514** [comment]
You might just have to turn on the debugger your browser and step thru it and find out what it's doing.  If you can pin it down a bit more though and there is something we can fix, we'd love to know about it.

**Comment by yyyc514** [comment]
It almost looks like it's only touching the very first block and none of the others... are you sure this has anything to do with pjax and kotlin?  If the first 3 were html does it work for 3?

**Comment by ShadowySpirits** [comment]
By debugging I found out that it is because hljs is included in other resource file I reference. When using pjax, that hljs (exclude kotlin) covered my hljs.

**Comment by ShadowySpirits** [comment]
thank you for your patient
