### ISSUE TITLE
Add Solidity highlighting

### ISSUE THREAD

**Issue by abcoathup** [highlightjs/highlight.js#2047]
I will work on a PR

**Comment by abcoathup** [comment]
@marcoscaceres I want to get Solidity highlighting working in a hosted Discourse forum
https://meta.discourse.org/t/how-to-get-solidity-syntax-highlighting/117774

The Discourse recommendation was to get Solidity added as a language to highlightjs.  With the move to having new languages in their own repo, how can highlightjs be configured to use the https://github.com/highlightjs/highlightjs-solidity repo? Is there existing documentation?

As an aside, may need to add some documentation that new languages should be created in separate repos.

Note: PR is now closed. https://github.com/highlightjs/highlight.js/pull/2051

**Comment by marcoscaceres** [comment]
You should be able to put together a custom bundle - see example:

https://github.com/w3c/respec-hljs

**Comment by yyyc514** [comment]
@abcoathup I'd like to make this much, much easier where you can just download the repos and then run the build command but just started digging into the idea.

**Comment by abcoathup** [comment]
Hi @yyyc514,

Sounds great.  

Discourse built a theme component so we could get Solidity highlights:
https://forum.openzeppelin.com/t/discourse-solidity-syntax-highlighting/267/11

**Comment by yyyc514** [comment]
Closing this issue since we have the https://github.com/highlightjs/highlightjs-solidity repository in place now.
