### ISSUE TITLE
(javascript) division and regular expressions can get confused and break highlighting

### ISSUE THREAD

**Issue by mjbvz** [highlightjs/highlight.js#2050]
**Version:** 9.15.8

**repo**
1. Run highlight.js on the the following javascript code:

```
console.log(`Bad ${foo / 1000}`)
const highlighting = 'broken'
```

**Bug**
![Screen Shot 2019-06-03 at 6 05 07 PM](https://user-images.githubusercontent.com/12821956/58844023-23453f80-862a-11e9-9121-e89c222eac10.png)

The division break highlighting

**Comment by yyyc514** [comment]
In C like languages telling the difference between `/` for division and `/` for regex can be quite tricky.  That's what we're running into here.  It thinks it see a regex, but then it hits the new line, realizes it was wrong and just aborts (newlines in regex are illegal).

**Comment by yyyc514** [comment]
This would be fixable with:

```js
  FULL_REGEXP_MODE = {
    begin: /\/[^\/\n]*\//,
    returnBegin: true,
    contains: [
      hljs.REGEXP_MODE
    ]
  };
```

@marcoscaceres  Thoughts?  First we actually match a FULL regex, and assume we found one we rewind ( returnBegin) and then let the default `hljs` rule take a swing at it...  This probably wouldn't be a bad idea for how to do it in general (Which would fix this problem everywhere).

Though look-ahead once we have it is another solution to this.  That's all we're doing with returnBegin here is building a fake look-ahead. :-)

**Comment by marcoscaceres** [comment]
Seems reasonable to me... but @egor-rogov is more knowledgeable than me on these matters.

**Comment by yyyc514** [comment]
Note: This still doesn't properly detect division vs regex, it just prevents regex from "crashing and burning" and taking the highlighting with it :-)

**Comment by yyyc514** [comment]
Example from #1458 https://jsfiddle.net/atesgoral/n5cgtfzv/2/

**Comment by egor-rogov** [comment]
> This would be fixable with:

Well, it's better than nought.
I'm afraid we can't tell, say, `foo = 2 / 2 + 2 / 2;` from `foo = / 2 + 2 /;` without proper syntax parsing, which is impossible with regexps.

**Comment by yyyc514** [comment]
I'm going to leave this hanging and try to get back to my parser work... if we could reach agreement there things like this would be much easier to fix without resorting to `returnBegin` which is really just a very ugly way to do working look-aheads. :-)

If someone needed this fixed ASAP a PR with something along the lines of my proposed fix would probably be passable in the short-term.

**Comment by yyyc514** [comment]
Not to forget this trick from Coffeescript:

```
hljs.inherit(hljs.C_NUMBER_MODE, {starts: {end: '(\\s*/)?', relevance: 0}}), // a number tries to eat the following slash to prevent treating it as a regexp
```
