### ISSUE TITLE
CHM packaging problem

### ISSUE THREAD

**Issue by WanManito** [highlightjs/highlight.js#2053]
CHM is packed.HLJS is not defined, addevenlistener is null, and the foeach method is not supported
![image](https://user-images.githubusercontent.com/26118508/59156597-45c6d500-8ad0-11e9-83fb-fe1da1ec8716.png)

**Comment by LunarSF** [comment]
highlight.js 应该是要求 utf-8 的，而 chm 对 utf-8 的支持相当之糟糕。
此外，highlight.js 应该要求 IE 9 或更高的内核版本，不在网页上指定使用新版本的内核就会出现这个问题。

**Comment by LunarSF** [comment]
So, use utf-8 & IE 9 .

**Comment by WanManito** [comment]
那在chm中不能使用highlight.js了吗，。。。。。。

**Comment by LunarSF** [comment]
办法是有的，只是可能有点潜在的小问题，所以要慎用。

> 编码的问题我用 GB18030 似乎也没什么异常。关键是处理 highlight.js 中提供的 js 脚本与浏览器的兼容性问题。

我试验的结果有这么两个法子：

- 方法一，还是比较简单的：是直接在网页中指定要使用 IE 9 以上的内核（前提是机器上要有高版本IE浏览器），也就是在网页文件的 &lt;head&gt; &lt;/head&gt; 之间加上下面这行：

&lt;meta http-equiv="X-UA-Compatible" content="IE=9"/&gt;

这样做有两个小问题：(1) 微软的 CHM 阅读器在打开这样的页面时，界面风格与阅读器整体风格不协调。(2) 如果机器上没有安装 IE 9 或更高版本则不起作用。（WinXP 最多只能安装到 IE 8）。

---

- 方法二，很繁琐：使用 新版浏览器打开网页，让 highlight.js 发挥作用，然后将 highlight.js 修改过的 html 保存为真正打包到 CHM 中的网页文件（保存后要去除对 highlight.js 中 js 脚本的引用，但要保留对 highlight.js 提供的相关 css 样式表文件的引用）。

这样做的原理是：把 highlight.js 对网页中 &lt;pre&gt;&lt;code&gt;...&lt;/code&gt;&lt;pre&gt; 片段的处理过程提前由新版浏览器完成了。而读者在阅读 CHM 文件时，CHM 即使使用旧版 IE 内核也没有必要再调用 highlight.js 提供的 js 脚本——自然也不会再出错。

这个方案是由 锋爷冷静冷静 在 [LunarMarkdownEditor 的 Issure 列表](https://gitee.com/lunarsf/Lunar-Markdown-Editor/issues/IV718) 中提出，我来解决的。

具体做法比较烦琐，但如果编程实现，用起来还算方便：

(1) 【如果只是偶尔使用，这步可以忽略，使用新版浏览器的”开发人员模式“，直接手工复制新 Html 并另存即可。】具体做法是：
在网页中加上对 jQuery 的引用（如果将来不想移除，用低版本的jQuery），以便从浏览器复制 highlight.js 加工后的新 Html 文本。复制Html文本可以使用以下JS方法：
    <script>function getHtml()
    {
        var html = $('html').clone();
        var htmlString = html.html();
        return htmlString;
    }
    </script>
这个 JS 方法要写到网页文件中，使用过后，在新版 Html 文件中可以删除。

> 由于浏览器不能直接使用这个方法向本地保存 html 文件（用 Ctrl+S 保存的网页还是旧版的），所以我在 LME 中做了一个名为“Html 工厂”的对话框，通过 WPF 界面库的 WebBrowser 控件与 JS 脚本的交互功能调用上面这个 'getHtml()' 方法来获得，再用 C# 保存新 Html 文件。

> > 如果偶尔使用，并**不需要自己实现这样的软件，也不需要下载 LunarMarkdownEditor **——可以尝试直接从新版浏览器中复制新的 DOM 文本，再手工保存为网页。FireFox 可以按 ‘F12’ ，打开”开发人员视图“，再找到”查看器“，右击后在弹出菜单中选择”复制→整体Html“。

(2)【如果是直接从浏览器的开发人员模式中复制的，这步也可以省略。】
给得到的新 Html 文本加上文件头（因为 jQuery 复制的新 Html 文本缺少这部分）。

> 从旧版 Html 文件复制、粘贴过来就行。

(3)【如果是直接从浏览器的开发人员模式中复制的，这步也可以省略。】根据需要移除对 jQuery 的引用，也就是删除下面这行：
    <script src="jquery-1.7.0.min.js"></script><script>

(4)【这步不可省略。】移除对 highlight.js 的 js 脚本的引用行，也就是删除下面这两行：
    <script src="./_highlight~/highlight.pack.js"></script>
    <script>hljs.initHighlightingOnLoad();</script>

注意：对 highlight.js 提供的 css 样式表的引用是要保留的，下面这行是不能删除的：

    <link type="text/css" rel="stylesheet" href="./_highlight~/styles/default.css"/>

> 打包进 CHM 时，highlight.js 中提供的 这些样式表文件也要打包进去。

**Comment by WanManito** [comment]
非常感谢

**Comment by LunarSF** [comment]
Because of my poor English...
1. You can use highlight.js with IE9
2. If you want use IE8(or older), you can use IE9 first to convert your html to highlighted html text, then remove the link to highlight.js, and save the new html.
- Package new html files to chm.

At 2019-10-07 17:46:58, "Josh Goebel" <notifications@github.com> wrote:


I can't read any of this. Is there still an issue here?

**Comment by yyyc514** [comment]
Is this whole issue about IE8 or older?

**Comment by yyyc514** [comment]
https://helpman.it-authoring.com/viewtopic.php?t=9294

> Actually, you don't need UTF-8 for CHM files because CHM doesn't support UTF-8 or Unicode. CHM is an ancient format that Microsoft has not really changed since Windows 98, and it has a number of quirks and restrictions like this

Highlight.js requires UTF-8 support for some of it's grammars, so it sounds like CHM is just something we will be unable to support.  Closing this issue.
