### ISSUE TITLE
Works in Chrome, Firefox but broken in Safari

### ISSUE THREAD

**Issue by jeffschwartz** [highlightjs/highlight.js#2057]
Mac OS v10.13.6
Chrome Version 75.0.3770.90 (Official Build) (64-bit)
Firefox 67.0.2 (64-bit)
Safari Version 12.1.1 (13607.2.6.1.2)

Safari reports no errors yet it fails to render highlighted code blocks. I've included screen shots from all three browsers:

![Screen Shot 2019-06-15 at 12 40 57 PM](https://user-images.githubusercontent.com/271288/59554049-aee49780-8f6b-11e9-8165-b1a282a80bf5.png)
![Screen Shot 2019-06-15 at 12 41 41 PM](https://user-images.githubusercontent.com/271288/59554050-aee49780-8f6b-11e9-9b30-46966c5e9fb0.png)
![Screen Shot 2019-06-15 at 12 42 47 PM](https://user-images.githubusercontent.com/271288/59554051-aee49780-8f6b-11e9-9341-5af32d1fc8cd.png)

**Comment by yyyc514** [comment]
I no longer have access to Safari 12... can someone else possible look into this and at least provide a bit more of a pointer to where the problem might lay?

**Comment by marcoscaceres** [comment]
Works for me in Safari.

**Comment by marcoscaceres** [comment]
(Safari Version 13.0 (14608.1.49))

**Comment by yyyc514** [comment]
Well yeah... I have 13.0.1. :-)  I wonder if we should care about this so much since Safari is a free upgrade (lets say it's an actual issue with 12.x)... I wonder if Safari 13 isn't available on some versions of OS X?

**Comment by marcoscaceres** [comment]
Unfortunately, we don't have the resources to support legacy browsers :(

**Comment by yyyc514** [comment]
> Safari 13 ships with iOS 13 and macOS 10.15. It’s also available for macOS 10.14.5 and 10.13.6.

At least it goes 3 versions back.

@jeffschwartz If you can identify the issue yourself and submit a PR I'm sure we'd be happy to review and merge it (I assume it's something simple once found), but otherwise we don't have the resources to track this down ourselves.

**Comment by yyyc514** [comment]
Awesome sauce.

**Comment by jeffschwartz** [comment]
@yyyc514 Awesome product :)
