### ISSUE TITLE
first line of hl.js treated css code is always indented.

### ISSUE THREAD

**Issue by BobWalsh** [highlightjs/highlight.js#2059]
In a rails app, I have blocks of CSS I want to display correctly. 

The code is being correctly formatted by hl.js, and the theme VS2015 is being applied.
```
<pre style="backface-visibility: hidden;"><code class="css hljs" style="backface-visibility: hidden;">
    <span class="hljs-selector-tag">a</span><span class="hljs-selector-pseudo">:link</span> { 
<span class="hljs-attribute">color</span>: red; }

<span class="hljs-selector-tag">a</span><span class="hljs-selector-pseudo">:visted</span> { 
<span class="hljs-attribute">color</span>: purple; }
                </code></pre>
```
But each block appears with the first <span> tag indented:

![Cursor_and_Learnshortcuts](https://user-images.githubusercontent.com/5097/59957241-4144d980-944b-11e9-82c9-deb68d9b5972.png)

Does anyone know why this is happening, or how I can fix it?

**Comment by TammyTee** [comment]
I dynamically added my hljs content via JavaScript and I found that trimming the content on it helped remove the indentation

![image](https://user-images.githubusercontent.com/8689444/64137340-94c99100-cdc5-11e9-8e63-a43951895fb6.png)

**Comment by yyyc514** [comment]
@BobWalsh What is your original HTML?  Are you sure this isn't just whitespace that's actually inside your <pre> tag and therefor it's being rendered exactly as it's supposed to be?

A https://jsfiddle.net or real reproducible bundled example we can play with would be great.

**Comment by BobWalsh** [comment]
it was an indent in VS code...

**Comment by yyyc514** [comment]
Awesome. :) Glad we solved it.
