### ISSUE TITLE
Publish non-minified distributable on cdnjs

### ISSUE THREAD

**Issue by OrbintSoft** [highlightjs/highlight.js#2061]
cdnjs provides only minified js files
I tied to use other providers,like npm, but that version doesn't work because it's intended to be used only on Node.js.
Can you publish non minified version on cdnjs?
Thank you.

**Comment by yyyc514** [comment]
Do you just need the content of the file?  What is the need for a non-minified version on a CDN?  Perhaps we should be providing source maps and we are not?

**Comment by OrbintSoft** [comment]
No I need non minified, for many reasons. 
1) I use to deploy non minified files in my debug environment, because it's more easy to debug and find errors than use source map.
2) I deploy minified files with source map only in production enviroment for performance.
3) I prefer to use my js compiler based on google closure compiler for my custom optimizations.
4) This is the only open source library that I know that has not published non minified files and I can't understand why.

**Comment by yyyc514** [comment]
@marcoscaceres Perhaps food for thought when we update the CDN/doc website next?    I'm not sure if there is some specific reason we haven't done this in the past?

> No I need non minified, for many reasons.

FYI: Of course if you have Node.js locally you can build it yourself (non-minified) fairly easily:

```
node tools/build.js -t node
```

**Comment by marcoscaceres** [comment]
Yes, we should see if it's possible to deploy a non-minified version.  

@OrbintSoft, you can always get the non-minified version doing what @OrbintSoft suggested.

**Comment by yyyc514** [comment]
@isagalaev IF we simply fix the build script so -t `cdn` splits out a few more files, will those automagically be pushed to the CDN also by the build process?

**Comment by yyyc514** [comment]
> This is the only open source library that I know that has not published non minified files and I can't understand why.

Do most ship 100s of individual JS files?  Are you wanting ALL of those the files to be in both minified and non-minified forms, or just the base highlightjs.js file?

**Comment by KyleMit** [comment]
FYI - You can look at the built files [from npm](https://www.npmjs.com/package/highlight.js) via [unpkg](https://unpkg.com/browse/highlight.js@9.17.1/lib/highlight.js)

For example, here's the unminified `highlight.js`:

https://unpkg.com/highlight.js/lib/highlight.js

**Comment by yyyc514** [comment]
We're just going to build both always for the CDN (minified and not).  And the CDN files are different than the NPM files, so just fetching the files from unpkg doesn't work for someone why truly needs CDN builds.
