### ISSUE TITLE
Add Vue Single File Component (.vue) highlighting.

### ISSUE THREAD

**Issue by sustained** [highlightjs/highlight.js#2062]
It shouldn't be too difficult to add since a Vue SFC basically looks like this:

```
<template>
VALID HTML HERE
</template>

<script>
VALID JAVASCRIPT HERE
</script>

<style>
VALID CSS HERE
</style>
```

The only thing to note would be that you can do e.g. `<script lang="ts">` and `<style lang="scss">` and such.

**Comment by stevenjoezhang** [comment]
Like this one: https://github.com/highlightjs/highlight.js/pull/1929

**Comment by marcoscaceres** [comment]
We need a maintainer for VueJS :(

**Comment by yyyc514** [comment]
@marcoscaceres I think this can be closed now yes since we have:

https://github.com/highlightjs/highlightjs-vue/

**Comment by patarapolw** [comment]
It isn't yet publish to NPM, but it can be installed using

```
npm i https://github.com/highlightjs/highlightjs-vue.git
```
