### ISSUE TITLE
Feature Request: hljs-callout

### ISSUE THREAD

**Issue by arkadianriver** [highlightjs/highlight.js#2064]
Unless there is a way to do this I'm missing, I'd like to suggest an `hljs-callout` general purpose class so that we have the ability to provide a special _color_ along with italic, bold, or other passthrough style for a _callout_, a word or phrase within the highlighted code that needs to be called out to the reader, typically in the surrounding text.

`hljs-callout` wouldn't be a detectable class, but one provided by the author that would override the detected class by highlight.js (or be _inside_ the detected class instead of the other way around).

Because, although it is true that we can provide a custom class/style inside the code, the color of that style is overridden by the detected syntax. See this fiddle for an example: https://jsfiddle.net/091cbza3/
Bold and italic are applied, but because highlight.js injects its styling for the token type _inside_ my custom `hljs-callout` style (`hljs-regexp` and `hljs-string` in this case), the color of the callout is overridden by highlight.js.

I think this is related to #1379 but more specific

**Comment by yyyc514** [comment]
You need to use a child selector:

```
.hljs-callout * {font-weight:bold;font-style:italic;background:gold;}
```

![Screen Shot 2019-10-04 at 4 27 37 PM](https://user-images.githubusercontent.com/6473/66237773-f1211880-e6c3-11e9-8bdb-85aebc12fc71.png)

**Comment by yyyc514** [comment]
Closing as asked and answered.  Let us know if you have any other questions! :-)
