### ISSUE TITLE
Squirrel language?

### ISSUE THREAD

**Issue by SpyceTewan** [highlightjs/highlight.js#2074]
Hi I'm making a website and need [squirrel](http://squirrel-lang.org/) highlighting.

There is a textmate syntax definition [here.](https://github.com/micheg/sublime_squirrel) Is there a way to easily convert it to highlight.js's format?

Thanks in advance!

**Comment by marcoscaceres** [comment]
Not super easy... you'd have to process those XML files to get out the actual language definition.  However, once you have all the keywords, it's pretty straight forward.
