### ISSUE TITLE
if two keywords that need to be highlighted come together, they will be in one line

### ISSUE THREAD

**Issue by Warrie** [highlightjs/highlight.js#2075]
for example: in java
```
//some comments
public static String json=""
```
this will be like:

```
<span class="hljs-comments>//some comments</span><span class="hljs-keywords">public</span> static String json=""
```
how to show code in two line?

**Comment by egor-rogov** [comment]
@Warrie this looks strange because highlightjs preserves line breaks. Most likely something's wrong with the newline character in your java source file. Can you provide a reproducible example?

**Comment by yyyc514** [comment]
@Warrie Any update?

**Comment by yyyc514** [comment]
Closing.  We an reopen if Warrie comes back with a reproducible example. :-)  For now hoping all is well!
