### ISSUE TITLE
CDN build fails

### ISSUE THREAD

**Issue by msimmer** [highlightjs/highlight.js#2077]
It looks like the `replaceSkippingStrings` task errors out on the CDN build due to the multiline comment in [mathematica.js](https://github.com/highlightjs/highlight.js/blob/master/src/languages/mathematica.js#L11-L20)

```
$ node tools/build.js -t cdn
  Starting build.
  Building language files.
  { task: 'tasks',
    error: { task: 'replaceSkippingStrings', error: 'Unmatched quote' } }
```

I tested out replacing the comment with a series of single line comments and the build/all builds succeed, so I'll open a PR for that

**Comment by marcoscaceres** [comment]
Thanks for the PR!

**Comment by yyyc514** [comment]
@egor-rogov Seems this is safe to close out since #2078 is merged.

**Comment by marcoscaceres** [comment]
Thanks for all the triage @yyyc514!

**Comment by yyyc514** [comment]
@marcoscaceres  Glad to help.
