### ISSUE TITLE
Support HTML strings in highlightAuto (web worker)

### ISSUE THREAD

**Issue by silverwind** [highlightjs/highlight.js#2086]
`highlightAuto` currently only supports text input, but it would be great if HTML strings could also be supported which would allow one to achieve the same end result like the methods that operate directly on the DOM, but in a web worker (e.g. preserving existing HTML nodes).

**Comment by marcoscaceres** [comment]
Hi, @silverwind. I’m a little unsure what HTML strings. Could you provide us with a few more details of what you are trying to do?

**Comment by silverwind** [comment]
The result of `node.innerHTML`: `<span class="line-1">something</span>`. So it would work like `highlightBlock` but operate on such a string instead of the real DOM in case the target node already contains HTML elements which would get lost when I pass `.textContent` as documented.

But after checking the code of `highlightBlock`, I see that it does leverage DOM APIs to fix up the lost HTML nodes via `mergeStreams`, so I guess this would be very hard to implement without access to DOM APIs (you'd probably have to regex-parse that HTML), so feel free to close.

**Comment by marcoscaceres** [comment]
Yeah, it would be quite challenging. Thanks anyway for the suggestion.
