### ISSUE TITLE
Elm's Virtual DOM patching/diffing conflicts with highlight.js

### ISSUE THREAD

**Issue by sashaafm** [highlightjs/highlight.js#2087]
I'm experimenting with this library to highlight some code in a Elm application. However, I recently found out that if I've got some nodes using the `pre` and `code` tags as required by `hljs` and Elm's Virtual DOM finds it necessary to patch the DOM this results in some errors and weird behaviour by Elm.

For example, in my case I got an `Uncaught TypeError: domNode.replaceData` followed by an infinite loop of errors with `removeChild`.

I know this isn't a lot of information and there may be nothing the `hljs` devs may be able to do, but I wanted to raise awareness to this issue. I'm not sure if there's any workaround to prevent these DOM nodes from causing problems with Elm's Virtual DOM? Should I report this to the Elm devs instead?

This was reproduced with `highlight.js` `v9.15.6`. I'll experiment with a more recent version shortly.

Thank you!

**Comment by yyyc514** [comment]
Can you provide a full Elm/HTML/JS example that reproduces the issue?

**Comment by cdbax** [comment]
FWIW @sashaafm (forgive me if I'm telling you something you already know) this approach is not a great idea. Elm doesn't play nicely with anything that isn't Elm, so you really don't want a JS library manipulating the same nodes as your Elm code.

Elm has some [clear approaches for JS interop](https://guide.elm-lang.org/interop/) so I'm afraid you'd need to use that approach for this integration to be reliable. You might be able to use `hljs.highlightBlock` through an Elm Port, but I haven't used highlight.js like this so I'm afraid I'm not much help there.

**Comment by yyyc514** [comment]
Ping.

**Comment by sashaafm** [comment]
Hello @yyyc514. Sorry for having taken so long to reply. AFAIK the problem is precisely the one @cdbax mentioned. Elm doesn't play nicely with JS libs who manipulate DOM nodes because it somehow messes up its VDOM from what I can tell.

I'm not sure if it's worth forging an example since I don't think there's anything you can do on your side. Most likely an Elm-only highlight lib must be built or at least use a JS one which interacts with Elm via Ports.

If you still want the example I can try to come up with one, but it will take some time due to busy schedule.

**Comment by yyyc514** [comment]
I'd consider what @cdbax said about interop.  It would seem to me (without knowing much about Elm) that it should have SOME facility to work around these types of things... like before/after hooks or telling it "hey  leave this block alone", etc...

But yes it does sound like this is more of an Elm issue than a Highlight.js issue.

If it turns out there is a hook or two or some minor feature we need to add to Highlight.js to make it play better with Elm that'd be the sort of thing worth finding out and then re-raising here as an issue. I think that'd be something we'd def consider a PR for.
