### ISSUE TITLE
A questions about sql

### ISSUE THREAD

**Issue by Godlike-meteor** [highlightjs/highlight.js#2093]
![image](https://user-images.githubusercontent.com/29011785/62596647-aaa67c00-b915-11e9-887d-7ccbf5582f84.png)
I don't know why this part of my highlight displays errors, using official website example, but splitting lines of code.
like 
```bush
document.addEventListener('DOMContentLoaded', (event) => {
  document.querySelectorAll('pre code').forEach((block) => {
    hljs.highlightBlock(block);
  });
});
```

**Comment by egor-rogov** [comment]
Hi @Godlike-meteor,
I'm not sure what do you mean by "displays errors," but PostgreSQL code looks better with  `pgsql` language.

**Comment by Godlike-meteor** [comment]
Thank you, this problem has been solved according to your prompt.
