### ISSUE TITLE
plaintext class ignored, still auto detects language and highlights

### ISSUE THREAD

**Issue by oerp-odoo** [highlightjs/highlight.js#2106]
According to `highlight.js` documentation, to make code look like code without any specific language highlighting, you can use this:
```html
<pre><code class="plaintext">...</code></pre>
```
Though, in my case it does not work. It ignores plaintext and tries to detect language automatically, which is not expected.
Before generating html for highlight, I pass these classes on `pre` tag: `o_website_snippet_code_highlight plaintext col-lg-6`

Though, it automatically adds `python` class too, even if I specified `plaintext` class to not do that.
```html
<pre class="o_website_snippet_code_highlight plaintext col-lg-6 hljs python"><code><span class="hljs-function"><span class="hljs-keyword">def</span> <span class="hljs-title">test</span><span class="hljs-params">()</span>:</span><br>&nbsp;&nbsp;&nbsp;&nbsp;<span class="hljs-keyword">return</span> <span class="hljs-string">'x'</span>;<br></code></pre>
```
It does not work even in simple cases like:
```html
<pre class="plaintext"><code>Some plain text</code></pre>
```
It still detects that it is `properties` syntax.

P.S. using highlight.js v9.15.9

**Comment by egor-rogov** [comment]
Hi @oerp-odoo,
it should not behave this way, although it's difficult to say something for sure without seeing your js code. Can you provide a working example that shows the problem?

**Comment by oerp-odoo** [comment]
@egor-rogov My bad. I thought `plaintext` was not part of languages you choose to highlight. I believed it was something like `nohighlight` class. I just needed to include that language in a package and it now recognizes it. So false alarm.
