### ISSUE TITLE
Unable to load styles

### ISSUE THREAD

**Issue by tbhaxor** [highlightjs/highlight.js#2108]
I am using it in vuejs

**My Snippet**

```js
// imports
import showdown from "showdown";
import sh from "showdown-highlight";
import "highlight.js/styles/agate.css";

// creating the converter
let c = new showdown.Converter({ extensions: [sh] });
document.querySelector('#preview') = c.makeHtml(this.content);

```

**My Output**

![image](https://user-images.githubusercontent.com/28386721/63229865-a1c17e80-c222-11e9-8458-df87c88b6bef.png)

**Expected**

Should load style like this

![image](https://user-images.githubusercontent.com/28386721/63229896-ec42fb00-c222-11e9-9d3a-c5fcd113fd25.png)

**Comment by tbhaxor** [comment]
Closing for no response. If you feel you should help me with this feel free to comment :wink:

**Comment by egor-rogov** [comment]
Hi @tbhaxor, sorry for the silence. A complete example (one that we can play with to make it work) should help.

**Comment by tbhaxor** [comment]
The example I have shared is complete.
