### ISSUE TITLE
Question: How do I change the style at runtime by clicking a button

### ISSUE THREAD

**Issue by manastalukdar** [highlightjs/highlight.js#2115]
I have highlight.js integrated into my website along with a style by including the corresponding css file. My website has light and dark modes. When the user changes the theme by clicking a button, I would also like to change the style (say from atom-one-light to atom-one-dark and vice versa) associated with highlight.js. If someone could please provide any pointer on how to do this that would be great.

**Comment by faunaee** [comment]
The highlight.js demo page shows you one way to do it: https://highlightjs.org/static/demo/

Each of the alternate stylesheets is included in a `<link>` tag in the page's `<head>` tag. `demo.js` (https://github.com/highlightjs/highlight.js/blob/master/demo/demo.js) disables all but the currently-selected style.

**Comment by lucasvazq** [comment]
If you are using `sass/scss` and handle your dependencies with `npm`, you can do the next thing:

```scss
@use "sass:meta";

html[data-theme="light"] {
  @include meta.load-css("highlight.js/styles/a11y-light");
}
html[data-theme="dark"] {
  @include meta.load-css("highlight.js/styles/a11y-dark");
}
```

To make it to work, you need to define the `data-theme` attribute in your html.
```html
<html data-theme="light">  <!-- ensure to change it with javascript and define one with default -->
  ...
</html>
```

**Comment by Pomax** [comment]
@faunaee that link doesn't appear to work (anymore):

![image](https://github.com/highlightjs/highlight.js/assets/177243/f7512d80-5a51-48ba-ab7a-a6509bf28b3b)

**Comment by joshgoebel** [comment]
Updated link to new demo page.

**Comment by cawoodm** [comment]
Unfortunately this approach fails when using a bungler... I mean bundler like vite. In build mode both .css files are combined and cannot be separately disabled. Even in develop mode it creates both .css `<link>` elements without a title.

Would it be hard to add a switch to say the `highlightElement()` method to provide a chosen theme? It's up to the dev of course to load their themes but it would make it easy to switch between a light and dark theme by just loading both and then toggling :-)

**Comment by joshgoebel** [comment]
> Would it be hard to add a switch to say the highlightElement() method to provide a chosen theme?

AFAIK that would require custom CSS (as shown above with SASS) - and you don't need much JS at all.  As faunee pointed out our own demo has an example of one way to to do this - but if your build system isn't going to allow you to - then I'm not sure what to tell you.

> this approach fails when using a bungler.

I'd suggest your bundler is broken or incorrectly configured - but can't help you with that, sorry.

**Comment by joshgoebel** [comment]
Sorry, not htttps, but I just realized pastie has another example of how to do this easily:

http://pastie.org/

**Comment by lucasvazq** [comment]
> Sorry, not htttps, but I just realized pastie has another example of how to do this easily:
> 
> http://pastie.org/
@joshgoebel 

Nice workaround!

How it works? If I'm right:
- It defines a base style through the backend with a purple theme by default ("shades-of-purple").
- If the user change the cookie "theme", the backend reads it and set that new value for the theme.

I think, this is a classic backend workaround, but u can do it without using the backend at all (if u don't need it for another thing).

You can set an inline script at the head (not in the bundle because you can get some flash of incorrect styles or weirdo blank flash page if the bundle is big and take a lot of time to process). That script can read the actual cookie and set the appropriate style based on that value.

```html
<!-- Approach with different style files for each theme -->
<html>
  <head>
    <script>
      (function() {
        const defaultTheme = "shades-of-purple"
        const cookieTheme = document.cookie.match(/(?:^|; )theme=([^;]*)/)?.[1]
        const theme = cookieTheme || defaultTheme
        const link = document.createElement("link")
        link.rel = "stylesheet"
        link.href = `${theme}.css`;
        document.head.appendChild(link)
      })();
    </script>
  </head>
</html>

<!-- Approach with only one style file for all themes -->
<html>
  <head>
    <script>
      (function() {
        const defaultTheme = "shades-of-purple"
        const cookieTheme = document.cookie.match(/(?:^|; )theme=([^;]*)/)?.[1]
        const theme = cookieTheme || defaultTheme
        document.documentElement.setAttribute("theme", theme)
      })();
    </script>

    <!--
      I put the styles inline, but a better approach would be to add the styles inside a file and load them using preload:
      <link rel="preload" href="styles.css" as="style" onload="this.onload=null;this.rel='stylesheet'">
    -->
    <styles>
      [theme="shades-of-purple"] {
        --background-color: purple;
      }
      [theme="nord"] {
        --background-color: cyan;
      }
      body {
        background-color: var(--background-color);
      }
    </styles>
  </head>
</html>
```

**Comment by ramsey** [comment]
Stumbled on this answer today and thought I'd share another way to accomplish this using CSS `@import`:

```html
<style>
    @import url("https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.11.1/styles/github.min.css");
    @import url("https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.11.1/styles/github-dark.min.css") (prefers-color-scheme: dark);
</style>
```

**Comment by Yang062** [comment]
tq

Ben Ramsey ***@***.***> 于 2026年3月18日周三 10:50写道：
