### ISSUE TITLE
Issue with <summary>, <param> & <return> balise in C# code

### ISSUE THREAD

**Issue by usernameHed** [highlightjs/highlight.js#2116]
Hello, here is the issue visually:
![jump line](https://user-images.githubusercontent.com/22715813/64077391-8cdbf500-ccd0-11e9-8805-3d6df2c4fa99.PNG)

Here the html part:
![clean](https://user-images.githubusercontent.com/22715813/64077415-c0b71a80-ccd0-11e9-9b3c-dedc211ca810.png)

And here, the real script in visual studio, balises summary, typeparam and returns are the problem:
![summary](https://user-images.githubusercontent.com/22715813/64077753-92870a00-ccd3-11e9-8b20-5d6b439fdabf.PNG)

**Comment by yyyc514** [comment]
Technically you need to escape these things inside your code block or else they are just HTML (which is what you are seeing).

&lt;summary&gt;

**Comment by yyyc514** [comment]
I wonder if there is any chance HTML supports CDATA or if we could use such a thing to help with this type of case?

Reference:

https://stackoverflow.com/questions/1398571/html-inside-xml-should-i-use-cdata-or-encode-the-html

**Comment by yyyc514** [comment]
Closing as asked and answered.  Tagging as a potential FAQ though since this has come up once or twice.
