### ISSUE TITLE
Invalid UTF-8 in Sass generated file

### ISSUE THREAD

**Issue by lobo-tuerto** [highlightjs/highlight.js#2118]
After installing with `yarn add highlight.js` and trying to import the Sass file for the **dracula** theme with this:

```sass
@import '~highlight.js/scss/dracula.scss'
```

I get this error:

```bash
SassError: Invalid UTF-8.
   ╷
12 │ @author �verton Ribeiro <nuxlli@gmail.com>
   │         ^
   ╵
  node_modules/highlight.js/scss/dracula.scss 12:9  @import
```

Looking at the CSS files, it looks like the character that should be there is an: `É`.

So the full line should read:

```
@author Éverton Ribeiro <nuxlli@gmail.com>
```

**Comment by marcoscaceres** [comment]
We might need to add `@charset "utf-8";` to the stylesheet. Also, check how you are serving the file.

**Comment by marcoscaceres** [comment]
could you try adding `@charset "utf-8";` locally for me? If it works, we can merge in #2119

**Comment by lobo-tuerto** [comment]
Locally where?

I'm seeing the invalid sequence character inside the `dracula.sass` file inside VSCode.
VSCode shows it's already in UTF-8 mode.

**Comment by marcoscaceres** [comment]
> Locally where?

Sorry for being unclear, in  dracula.scss, at the very top of  the  file, add `@charset "utf-8";`. 

> VSCode shows it's already in UTF-8 mode

That's odd... let check.

**Comment by marcoscaceres** [comment]
Mine seems ok? 

<img width="371" alt="Screenshot 2019-09-07 10 44 37" src="https://user-images.githubusercontent.com/870154/64467498-84fed380-d15c-11e9-8358-68250d95ef3b.png">

**Comment by marcoscaceres** [comment]
@lobo-tuerto how are you generating the scss file?

**Comment by lobo-tuerto** [comment]
@marcoscaceres I'm not, I just installed the `highlight.js` package and it includes `styles` and `scss` subdirectories under `node_modules/highlight.js/`.

The content in `styles/dracula.css` is all right, but the one inside `scss/dracula.scss` is not.

**Comment by marcoscaceres** [comment]
Ok, thanks for checking. I'll poke around and see if I can find why the file is not being encoded correctly.

**Comment by marcoscaceres** [comment]
Ok, I think this was the bug https://github.com/highlightjs/highlight.js/pull/2120 ... the treating the files as binary.

**Comment by lobo-tuerto** [comment]
Thanks for looking into this!
