### ISSUE TITLE
Hide tags such as span and code?

### ISSUE THREAD

**Issue by lechten** [highlightjs/highlight.js#2126]
Hi, many thanks for this library!

Without highlight.js, `span` and `code` tags inside `<pre><code>` are not displayed, e.g., this renders properly:

```
<pre><code class=" xml" ><code>&lt;root&gt;</code>
<code>  &lt;parent&gt;</code>
<code>    &lt;child&gt;&lt;/child&gt;</code>
<code>  &lt;/parent&gt;</code>
<code>&lt;/root&gt;</code>
</code></pre>
```

With highlight.js, the `code` tags are displayed as well. Can this be avoided?

**Comment by yyyc514** [comment]
Please provide a full HTML/JS example of what you are trying to do.

If you're just passing them as input to Highlight JS how would it know that they HTML and not just code to be highlighted?

**Comment by yyyc514** [comment]
The real problem seems to be browsers render ANY content inside there as HTML:

```js
<pre><code>
  <h1>Header
  </h1>
  This is a test
</code></pre>
```

Sample: https://jsfiddle.net/wckf59Le/

What you are asking would COMPLETELY break the HTML highlighting.  I think this might just be against one of the core assumptions of Highlight.JS is that anything inside your `code` block is intended to be highlighted, period.

**Comment by yyyc514** [comment]
You're kind of asking for Highlight.js to magically "work around" special tags in your content - that's a pretty huge feature request AFAIK.  It'd likely be easier to build this yourself.

- take raw content
- call `highlight` on it
- take parsed content
- add your <code></code> wrappers to each line

**Comment by yyyc514** [comment]
Deleting my prior comments since they were just *wrong*. :-)  I underestimated Highlight.js.

This seems to just work to me:

https://jsfiddle.net/fx6byraw/

I do NOT see the issue you are describing.  The code tags are hidden as they should be.

**Comment by lechten** [comment]
I'm sorry for the noise, you are right. The issue is not with Highlight.js but its specific [variant in reveal.js](https://github.com/hakimel/reveal.js/blob/master/plugin/highlight/highlight.js) that I'm using.

To answer your question: I do not need those tags, they are generated in the master version of [Org mode's HTML export](https://orgmode.org/manual/HTML-export.html) (presumably to simplify adding of line numbers).

**Comment by yyyc514** [comment]
Like CSS line numbers, yeah... Good luck. :-)  Maybe you could switch to the official build?

**Comment by lechten** [comment]
I opened an [issue for reveal.js](https://github.com/hakimel/reveal.js/issues/2495). Let's see...
