### ISSUE TITLE
Highlighting for Eiffel

### ISSUE THREAD

**Issue by yuselg** [highlightjs/highlight.js#2128]
Is it possible to obtain code highlighting for Eiffel?

**Comment by marcoscaceres** [comment]
New languages are contributed by the community (i.e., we maintainers don't generally create new language definitions). If Eiffel is like some other language (e.g., c-based language) you might be able to crib an existing definition to support Eiffel. Take a look at the src/languages folder to see what language definitions look like.

**Comment by yyyc514** [comment]
Rather than leave these issues open to languish forever (as we have in the past) we're going to start closing them (to clean up the issues list).

I've moved this request to the wish list:
https://github.com/highlightjs/highlight.js/wiki/Grammar-Requests
