### ISSUE TITLE
How to configure the library to consult the `class` attribute of the `<pre>` tag instead of the `<code>` tag for language indicators?

### ISSUE THREAD

**Issue by GoBigorGoHome** [highlightjs/highlight.js#2129]
I write blogs on some blog hosting website where the markdown format is supported. When rendering code fences, the underlying markdown-to-html converter  will add the language indicator to the `class` attribute of `<pre>` tag instead of `<code>` tag. For example, the following code fence
<pre>
```cpp
int a, b;
a + b;
```
</pre>

will be converted to html as
```html
<pre class="cpp"><code>int a, b;
  a + b = c;</code></pre>
```
So how can I tell highlight.js to find language indicator in the `class` attribute of `<pre>` tag instead of `<code>` tag.

**Comment by egor-rogov** [comment]
Hi @GoBigorGoHome, 
there's currently no way to tell the library to look at the `pre` attribute, but It seems it can be done by modifying `blockLanguage` function a bit. Here is the line you need:

```js
     classes += block.parentNode ? block.parentNode.className : '';
```

Can you make the necessary changes yourself?

**Comment by GoBigorGoHome** [comment]
Hi @egor-rogov, thanks for your response. I know few about JavaScript, but I'll try.

**Comment by cup** [comment]
https://github.com/highlightjs/highlight.js/issues/2019

**Comment by yyyc514** [comment]
Closing this in favor to #2019 which is a request to add this functionality.

**Comment by yyyc514** [comment]
@GoBigorGoHome It might be easier for you to just attempt the PR necessary to resolve this than that code change.

Take a look at lines:

- 737

```
var blocks = document.querySelectorAll('pre code')
```

and 52:

```
  // calling the `hljs.configure` function.
  var options = {
    classPrefix: 'hljs-',
    tabReplace: null,
    useBR: false,
    languages: undefined
  };
```

We just need to make this an option. We just need a good name for the option.

**Comment by yyyc514** [comment]
I'd be happy with `tagSelector` probably
