### ISSUE TITLE
How should non-standard (not CR/LF) line-breaks be treated?

### ISSUE THREAD

**Issue by LongTengDao** [highlightjs/highlight.js#2131]
For example, **HTML** newlines are *LF*, *CRLF*, *CR*,

The newline characters of **CSS** are *LF*, *CRLF*, *CR* and *FF*,

The newline characters of **JS** are *LF*, *CRLF*, *CR*, *LS*, *PS*.

Then the `.html` file as follows:

```txt
<style><FF></style><CR><script><LS></script>
```

It should be shown as (following the outermost mode):

```html
<style></style>
<script></script>
```

Or (following the pattern of each layer itself):

```html
<style>
</style>
<script>
</script>
```

?

At present, the mainstream editors do not care about the inner and outer layers at all. In fact, even if they are single language, they do not care about newline characters except *LF*, *CRLF* and *CR*. The difficulty of implementation is not considered here, but the rationality scale itself is only considered from the programming point of view.

Another edge case is that if there are fewer line breaks allowed in the inner layer than in the outer layer, then there are line breaks in the inner layer that are not converted in the inner layer but can be converted in the outer layer. How should the line number be displayed? Or is it that any language that can be nested avoids this when it is designed?

**Comment by yyyc514** [comment]
What are FF, LS, and PS non-abbreviated? I'm only familiar with CR/LF.

**Comment by LongTengDao** [comment]
FF (U+000C): Form Feed <https://unicode-table.com/en/000C/>, one of newlines in CSS <https://www.w3.org/TR/css-syntax-3/#input-preprocessing>

LS (U+2028): Line Separator <https://unicode-table.com/en/2028/>
PS(U+2029): Paragraph Separator <https://unicode-table.com/en/2029/>
They are newlines in JS <https://www.ecma-international.org/ecma-262/5.1/#sec-7.3>:
```js
/./.test('\u2028') // false
```

**Comment by yyyc514** [comment]
Is this issue related more to Node.js server-side usage or web usage?  If someone is using a UTF-8 encoded webpage and properly escaping their HTML... are these things really doing to show un inside their `<pre><code>` block before it's handed off to Highlight.js?

I've seen a lot of questions about unescaped HTML and our answer on that is "properly escape it, or it won't work"... I wonder for the web if this is a case of that - though that wouldn't help using Highlight.js more broadly...

But if HTML is limited to the more traditional CR/LF then "properly escaped" HTML in `<pre><code>` block shouldn't really include any of those, should it?

---

I think it would help if this conversation was less theoretical (hence my trying to drag it back into context).

**Comment by yyyc514** [comment]
@LongTengDao Whipping up a test for this on https://jsfiddle.net might be nice, so at least we have something to compare.

Currently (in the web context) we use whatever `textContent` from the browser gives us, so the first thing might be to see what that does to the various types of line breaks in the first place.

**Comment by LongTengDao** [comment]
I see, you mean highlight.js is mainly designed for standard use, not exact syntax use

**Comment by yyyc514** [comment]
Are these "edge syntax cases under consideration"? :-)

Well, I just meant that the browser MIGHT dictate some of our behavior *for the browser*.  If say it swallows those characters and turns them all into new lines (or effective escaping SHOULD do so) then really we don't have any choices to make here - the browser and escaping has already decided it.

This is probably just a theoretical discussion until we have a sample use case, or a failing test, or something. :-)

**Comment by LongTengDao** [comment]
Oh. <https://jsfiddle.net/dgvy693f/8/> I try in jsfiddle, chrome/firefox will reserve them, but in IE only `innerHTML` reserve CRLF, `textContent` will replace CRLF with LF. FF and LS, PS will be reserved anywhere.

**Comment by yyyc514** [comment]
Small issue with the wording, we aren't an "editor"... I'll update.  I've given this a bit of thought just now... and my thought is only in the context of web usage.  I have no thoughts outside that - and now one has brought this up as an issue (other than this hypothetical), and it would have to get a little less theoretical I think for me to have thoughts.

I'm currently just not sure any of these new ways to break a line matter at all. :-)

So, for web usage...

I would suggest that correct (and expected) behavior is that code block should be structured the same BEFORE and AFTER syntax highlighting **other than color/italics/bold/etc**.  IE, highlighting a snippet should NOT alter the whitespace... I don't expect whitespace/line breaks to be added, and I don't expect it to be removed.

So, regarding the web, is the existing behavior broken now according to this expectation?

**Comment by LongTengDao** [comment]
I see, thank you!
