### ISSUE TITLE
Strange output in minified result

### ISSUE THREAD

**Issue by simplenotezy** [highlightjs/highlight.js#2142]
I noticed my build has all this output:

SYSRES_CONST_REFERENCE_TYPE_CHAR SYSRES_CONST_REFERENCE_TYPE_REQUISITE_NAME SYSRES_CONST_REFERENCES_ADD_PARAMS_REQUISITE_CODE SYSRES_CONST_REFERENCES_DISPLAY_REQUISITE_REQUISITE_CODE SYSRES_CONST_REMOTE_SERVER_STATUS_WORKING SYSRES_CONST_REMOTE_SERVER_TYPE_MAIN SYSRES_CONST_REMOTE_SERVER_TYPE_SECONDARY SYSRES_CONST_REMOTE_USER_FLAG_VALUE_CODE SYSRES_CONST_REPORT_APP_EDITOR_INTERNAL SYSRES_CONST_REPORT_BASE_REPORT_ID_REQUISITE_CODE SYSRES_CONST_REPORT_BASE_REPORT_REQUISITE_CODE SYSRES_CONST_REPORT_SCRIPT_REQUISITE_CODE SYSRES_CONST_REPORT_TEMPLATE_REQUISITE_CODE 

Which seems to be useless. Is it? If so, what can be done to remove it?

**Comment by yyyc514** [comment]
Could you upload the FULL build and the steps you're using to produce it?

**Comment by yyyc514** [comment]
That is part of the ISBL language (isbl.js).  If you don't need it then I suggest you specify only the languages you wish to include during your build and do not include ISBL.
