### ISSUE TITLE
Policy: New themes going into core?

### ISSUE THREAD

**Issue by yyyc514** [highlightjs/highlight.js#2157]
https://github.com/highlightjs/highlight.js/pull/2151

What is our policy with new themes?  Are there any guidelines on what is required to merge them, or would we prefer all themes be in external repositories (like languages) and no longer accepting new themes to core?

And since themes are much simpler might it be preferable to have a `highlightjs-additional-themes` repository to direct people too and just always accept PRs there?  Kind of like a smorgasbord of themes for anyone who wants something not in the default set?

**Comment by marcoscaceres** [comment]
Should use same policy as languages: i.e., external repo.

**Comment by yyyc514** [comment]
@marcoscaceres @egor-rogov 

> And since themes are much simpler might it be preferable to have a highlightjs-additional-themes repository to direct people too and just always accept PRs there?

And what about this idea?  I don't think we want to setup individual STYLE repos at the core organization for people, but what about the "discoverability" (which we do seem to care about for languages)?  Wouldn't having one big style repo that was pretty much "open to contribution" solve both problems and give us a central place for styles?

Thoughts?

**Comment by marcoscaceres** [comment]
I don't mind to be honest... problem is just having people to maintain things. The intention is to build separate communities and maintainers of this project are also part of the new repo (why we put them in our own organization - so it's not so much "frack off", but more "own your stuff, and we are here to help you... but own your stuff.")

**Comment by yyyc514** [comment]
Well, are you saying we want 1000 CSS repos in the `highlight.js` organization also?  That seems like a LOT of work vs having one large one... Are we perhaps confusing ownership with "maintenance"?  I'm not sure just having separate repos really encourages regular "maintenance" of said repos.    Look at all the dead repos on Github. :-)

Does themes really require maintenance?

**Comment by yyyc514** [comment]
I think we're both worried about long-term maintenance, we're just thinking about it differently.  Not sure what the right answer is.

**Comment by marcoscaceres** [comment]
We get very few themes (vs languages), so happy to keep them here.

**Comment by yyyc514** [comment]
> We get very few themes (vs languages)

True.  Ok, why don't you handle a response to https://github.com/highlightjs/highlight.js/pull/2151 then and then I'll follow your lead on how I respond to themes in the future.

**Comment by yyyc514** [comment]
> We get very few themes (vs languages), so happy to keep them here.

Closing this with this as the answer if you have no issues, @egor-rogov.
