### ISSUE TITLE
In the year 2019 could we consider removing "vbscript" as a possible match for <script> tags in xml?

### ISSUE THREAD

**Issue by yyyc514** [highlightjs/highlight.js#2158]
Before:

```js
 subLanguage: ['actionscript', 'javascript', 'handlebars', 'xml', 'vbscript']
```

After:

```js
 subLanguage: ['actionscript', 'javascript', 'handlebars', 'xml']
```

Thoughts?

_Context: This came up when I was evaluating the parser making incorrect guesses about which sublanguage to use when playing around with the xml parser._

**Comment by yyyc514** [comment]
Seems it still lives on in other places and the CLR, but as Internet Explorer was the only browser that supported it on the web, isn't it pretty much dead now as far as HTML is concerned?

**Comment by marcoscaceres** [comment]
I’m ok with dropping it.

**Comment by yyyc514** [comment]
https://github.com/highlightjs/highlight.js/pull/2168
