### ISSUE TITLE
Add svg language support

### ISSUE THREAD

**Issue by lukasoppermann** [highlightjs/highlight.js#2161]
Hey,

it seems svg as a language is not supported. It would be neat if that could be added.

**Comment by marcoscaceres** [comment]
Svg is just xml, so it’s already supported 😊or do you mean something different?

**Comment by lukasoppermann** [comment]
I think maybe an alias would be great.

**Comment by marcoscaceres** [comment]
Ok, would you mind adding it here:
https://github.com/highlightjs/highlight.js/blob/master/src/languages/xml.js#L36

**Comment by lukasoppermann** [comment]
Happy to send a PR
