### ISSUE TITLE
Add example of how to use on nodejs

### ISSUE THREAD

**Issue by lukasoppermann** [highlightjs/highlight.js#2166]
I just as some others (#1284 #936) are using highlight.js on node. 

It would be great to have an example of how to use it on node in the readme.
If you agree I would send a PR adding this.

**Comment by yyyc514** [comment]
Yes, please take #1284 or #1257 and run with it. It'd be great if we had an example of not just using nodejs but also using just a few languages, etc. (ie, 1257)

Closing as a dup, lets keep the dialog happening on 1284.
