### ISSUE TITLE
Plugin Idea: Shebang lines to auto-detect language

### ISSUE THREAD

**Issue by yyyc514** [highlightjs/highlight.js#2174]
Ie if starts with:

```
#!/usr/bin/env python
```

Python relevancy +100, etc.  Or would this not be that useful in practice?  Was just at hough I had reading a LOT of Python samples. :)  I guess the trick is we're not always given full samples, but seems like when we are this would be a dead giveaway a lot of the time?

**Comment by yyyc514** [comment]
If there was value I'd suggesting adding it as a feature in general... such that you had a `shebang:` key that took a regex and you could do something simple like:

```
shebang: 'python'
````

Or get more complex... and the parser itself would check the very first like for "#!.*shebang pattern.*$" or something.

**Comment by yyyc514** [comment]
@egor-rogov Any objections to the idea if we find someone to work on it?  Just a relevance boost if there is a matching shebang line that starts the content... if not I'll promote to "help welcome".  If you're super opposed for some reason this can just die.  

I just thought it was a helpful idea for snippet that DID actually contain a shebang.

**Comment by egor-rogov** [comment]
Can't this be emulated using regex? What is the probability to find "false shebang" below the first line?

**Comment by yyyc514** [comment]
Maybe (although I'm not sure a rule can match only the first line), but the idea here would be to abstract the concept and encourage grammars to support it - if we thought it was a good idea.  Hence making it easy with some smart defaults like:

```
{ shebang: "ruby" }
```

And we could build a smart regex to detect many common shebang patterns.

This could also be a plugin too though... I'll start a thread on hooks (which we'd need for useful plugins).

**Comment by egor-rogov** [comment]
> although I'm not sure a rule can match only the first line

Have you ever seen something that can be mistaken to shebang in the middle of code? Is it worth to stick to the first line at all?

> we could build a smart regex to detect many common shebang patterns

Why the core should be concerned with language specifics (say, `#!/usr/bin/env python` or `#!/usr/bin/env python2` or`#!/usr/bin/python3` )? I think that this knowledge must reside in the language grammar.

**Comment by yyyc514** [comment]
> Why the core should be concerned with language specifics (say, #!/usr/bin/env python or #!/usr/bin/env python2 or#!/usr/bin/python3 )? I think that this knowledge must reside in the language grammar.

I meant that the key distinguishing part: `python\d` would be the grammar's responsibility but the core could deal with things like /usr/bin vs /bin vs /opt/bin, etc...

Closing this for now.  This is the kind of thing a plug-in could/should handle.

**Comment by egor-rogov** [comment]
>  This is the kind of thing a plug-in could/should handle.

Agree.

**Comment by yyyc514** [comment]
The languages might still need to SUPPORT that plugin though by providing a `shebang` key or such, but we can circle back around to that when we've made more progress on plugins in general.
