### ISSUE TITLE
bash and json skipped with highlightBlock in production (not in development) (only js being styled)

### ISSUE THREAD

**Issue by kuworking** [highlightjs/highlight.js#2178]
I am having a strange issue when applying highlight in a gatsby site with the suggested

```js
  document.querySelectorAll('pre code').forEach(block => {
    console.log(block)
    console.log(window.hljs)
    window.hljs && window.hljs.highlightBlock(block)
  })
```

I see no problems when in development, but in production I see that json and bash sections are not styled

![image](https://user-images.githubusercontent.com/4474004/66602846-3acd9f80-ebab-11e9-9f1b-16fb81d39239.png)

Yet when looking at the `console` I see that highlight sees the blocks, but there's no `hljs` classname added

Also in the same document other languages are seen as usual, all of them except json and bash ones

*Well, actually I only have json, bash and js blocks, so only the js blocks are styled

*In other pages I can see css is as well styled, but bash and json are not, and they have the classname `"language-bash"` added

The highlight js file contains both languages, and I've cleaned the cache (netlify deploy) just in case there was a version without them included

Any clue of what can be happening?

**Comment by yyyc514** [comment]
Are you specifying the class name of the language manually or expecting Highlight.js to auto-detect it for you?  Did you try it with a smaller snippet and see if it worked - it perhaps the parser is getting hung up on something?

Really if the SAME snippet worked in dev mode though then it’s quite strange... are you loading multiple JS files?  Some sort of dependency load ordering issue?

Any reason you can’t link us to the actual website?

**Comment by kuworking** [comment]
The classname is already specified (transformed from markdown, either at compilation time or downloaded from an external source)

You can see it [here](https://www.kuworking.com/git-la-guia-simple), where bash code is not styled, or [here](https://www.kuworking.com/javascript-substring-substr-slice) where js code is styled

In both cases I see that in development that they just work fine (which is the disturbing thing)

**Comment by yyyc514** [comment]
![Screen Shot 2019-10-10 at 7 59 14 PM](https://user-images.githubusercontent.com/6473/66614834-74e17600-eb98-11e9-8224-63483f1da25b.png)

Seems to be working to me?  They are getting hljs-bash and are going highlighted (though bash highlighting isn't much to look at).

**Comment by kuworking** [comment]
mmm, i've check it now and it's not working

BUT I've pressed shift+refresh and it's work

...

I'll assume some pages were cached by my browser somehow and this was the cause of the error ... (I'm always skeptical about these things)

Ok, happy anyway, I close the issue but not without giving you a thousand hands for your fast replies :)
