### ISSUE TITLE
(typescript) snippet containing a lambda which parameters are enclosed in parens fails

### ISSUE THREAD

**Issue by ChristianIvicevic** [highlightjs/highlight.js#2189]
**Editor:** Adding a list of samples we should add tests for:

```js
const array = [1, 2, 3].reduce<number[]>((acc, next) => [...acc, next], []);
return this.sides.every((length,width=(3+2+(4/5))) => length > 0 );
const bad = ((a, b) => [...a, b]);
const bad = (a => [...a, b]);
const bad = (_ => doSomething());
const good = () => 0;
const bad = (() => 0);
```

- [x] Nested parens in expressions
- [x] () surrounded arguments
- [x] flag argument with no ()
- [x] `_` argument

Possibly relevant:
https://stackoverflow.com/questions/18703187/count-parentheses-with-regular-expression

Since to do this I think we really need to count parens in the regex that's matching => functions.

---

This is an issue I noticed downstream in VS Code itself and in the output of Asciidoctor which uses highlightjs. The snippet causing issues is this one:

````typescript
const array = [1, 2, 3].reduce<number[]>((acc, next) => [...acc, next], []);
//                             ~~~~~~~~
// Type of the initial value, in our case making it an array of numbers.
````

And gets rendered in VS Code and Asciidoctor generated HTML as follows:

![image](https://user-images.githubusercontent.com/45569997/66688262-23afb000-ec86-11e9-9658-de58a7f860b9.png)

![image](https://user-images.githubusercontent.com/45569997/66714470-910f2e00-edb7-11e9-9a5b-d066ea0159a1.png)

When removing the arrowhead of the lambda (even though syntactically incorrect) the formatting is correct once again (since the comment at the ends gets picked up as a comment):

![image](https://user-images.githubusercontent.com/45569997/66688278-3aee9d80-ec86-11e9-9ddd-7a5b938d71ab.png)

![image](https://user-images.githubusercontent.com/45569997/66714488-bdc34580-edb7-11e9-8864-00a024425a33.png)

**Comment by cdbax** [comment]
This seems to be something to do with the parens enclosing that arrow function. Here's some minimal reproductions:

Working: https://jsfiddle.net/cdbax/tsvn1gpj/8/

Broken: https://jsfiddle.net/cdbax/tsvn1gpj/9/

**Comment by yyyc514** [comment]
You know you can put multiple examples in a single fiddle, right? 🙂

**Comment by cdbax** [comment]
Ahehe 😅 sure I knew that:
https://jsfiddle.net/cdbax/tsvn1gpj/11/

**Comment by yyyc514** [comment]
Sure it’s not the number in brackets before it?

**Comment by ChristianIvicevic** [comment]
Even the following snippet will break the highlighting:

```typescript
const good = () => 0;
// comment

const bad = (() => 0);
// comment
```

**Comment by yyyc514** [comment]
Oh. Yikes.

**Comment by yyyc514** [comment]
Someone looking into this might want to look at Javascript which has this same type of structure, but I believe it works in that grammar.

**Comment by mondeja** [comment]
Just if someone try to fix this: Javascript and Typescript markups for enclosed lambda functions are broken, so both needs to be fixed. Javascript does not produce this error on the comment, but this is the rendered markup:
![Captura de pantalla de 2020-04-11 15-29-38](https://user-images.githubusercontent.com/23049315/79045043-591f6100-7c09-11ea-959d-f09b8fb765c1.png)

Note the paren before the params against a properly render markup:
![Captura de pantalla de 2020-04-11 15-32-02](https://user-images.githubusercontent.com/23049315/79045111-a69bce00-7c09-11ea-978e-5fe97bade92f.png)

**Comment by yyyc514** [comment]
Thanks, I also updated the original message here with more detail.

**Comment by yyyc514** [comment]
Actually you might be able to get away with just oring them since it's just a "preflight" check: 

Ie:
- `_ =>`
- `(*) =>`
- `(*(*)*) =>`
- `(*(*(*)*)*) =>`

**Comment by yyyc514** [comment]
@mondeja Does my last comment make sense or did you give up on this?

**Comment by mondeja** [comment]
I have given up for now.

**Comment by yyyc514** [comment]
Thanks for trying!
