### ISSUE TITLE
(javascript) Naive highlighting of keywords 

### ISSUE THREAD

**Issue by ChristianIvicevic** [highlightjs/highlight.js#2191]
In Typescript (and most likely in some other scenarios in Javascript) the following snippet is erroneously highlighted:

```typescript
type Foo = {
    functionInFoo(): void;
};
```

![image](https://user-images.githubusercontent.com/45569997/66715952-7fcf1d00-edc9-11e9-9944-aca1c62ff136.png)

The library is naively highlighting `function` since it's a keyword but not considering it might be part of a different identifier (even though it is arguably a bad name anyways).

**Comment by yyyc514** [comment]
That looks wrong (and not for the reason you said).  Fixing keywords out of context an be hard... but in this case it's part of a larger word, so it shouldn't triple.  Could be something is off with the keyword matching.

**Comment by cdbax** [comment]
This is only a problem in TypeScript. #2199 explains why.

https://jsfiddle.net/cdbax/et0jwcvy/2/
