### ISSUE TITLE
1C:Enterprise (v7, v8)

### ISSUE THREAD

**Issue by yyyc514** [highlightjs/highlight.js#2205]
```
/*
Language: 1C:Enterprise (v7, v8)
Author: Stanislav Belov <...>
Description: built-in language 1C:Enterprise (v7, v8)
Category: enterprise
*/
```

Does anyone know what this is?  Just some enterprisey thing?  Is it popular?

**Comment by cdbax** [comment]
I think it's this? http://www.1csoftware.com/
The sample for it is all in Cyrillic characters, so it would make sense to be Russian software.

**Comment by egor-rogov** [comment]
Oh yeah. This is a Russian ERP-like software, mainly for small business. It's **highly** popular in Russia and probably in some ex-USSR countries, but I believe not known elsewhere.

**Comment by egor-rogov** [comment]
They have its own insane programming language with Russian keywords, which they translate into monstrous several-megabytes SQL statements (:

**Comment by yyyc514** [comment]
That sounds crazy.

**Comment by egor-rogov** [comment]
It is.
Although SAP ABAP is hardly less crazy (though I don't know both of them).
