### ISSUE TITLE
(groovy) strings are not allowed inside ternary clauses

### ISSUE THREAD

**Issue by paladox** [highlightjs/highlight.js#2217]
If you do for example:

```groovy
def createCodeStyleMsgBody(build, label) {
    def codeStyleFiles = findCodestyleFilesInLog(build)
    def formattingMsg = label < 0 ? ('The following files need formatting:\n    ' +
        codeStyleFiles.join('\n    ')) : 'All files are correctly formatted'
    def url = build.url + "consoleText"

    return "${Globals.resTicks[build.result]} $formattingMsg\n    (${url})"
}
```

'The following files need formatting:\n    ' is not highlighted correctly as a string, secondly everything after ' + is coloured in blue (so if you create another def after, it colours all that in blue).

**Comment by yyyc514** [comment]
Sounds like some issue with expectations around new lines... anyway you could make a jsfiddle of this so we can easily track it over time and confirm it?  Or if you want to make an attempt at fixing it that'd be amazing. :-)

You can fork my template:
https://jsfiddle.net/ajoshguy/a1kntyg4/

**Comment by paladox** [comment]
Hi, here's the jsfiddle https://jsfiddle.net/j4gq5at6/

**Comment by yyyc514** [comment]
Thanks, yeah something strange is in the neighborhood there.

**Comment by paladox** [comment]
@yyyc514 i guess it's because of https://github.com/highlightjs/highlight.js/blob/master/src/highlight.js#L938 (as that piece of text actually includes \n)

**Comment by paladox** [comment]
Oh, just tested, nope.

**Comment by yyyc514** [comment]
No that's not it because the string is terminated, it doesn't bridge multiple lines.

**Comment by yyyc514** [comment]
It doesn't like the ternary, but not sure why.

**Comment by yyyc514** [comment]
```
    {
                // catch middle element of the ternary operator
                // to avoid highlight it as a label, named parameter, or map key
                begin: /\?/, end: /\:/
            },
```
Guessing this is it.
