### ISSUE TITLE
Do we have a policy of language formatting?

### ISSUE THREAD

**Issue by yyyc514** [highlightjs/highlight.js#2227]
See `tools/codeformat.js`.

It's intent sees to be to beautify all the languages with the following settings:

```
var beautify_options = {
  "indent_size": 2,
  "indent_char": " ",
  "eol": "\n",
  "indent_level": 0,
  "indent_with_tabs": false,
  "preserve_newlines": true,
  "max_preserve_newlines": 10,
  "jslint_happy": false,
  "space_after_anon_function": false,
  "brace_style": "collapse",
  "keep_array_indentation": false,
  "keep_function_indentation": false,
  "space_before_conditional": true,
  "break_chained_methods": false,
  "eval_code": false,
  "end_with_newline": true
};
```

it seems this hasn't happened in a LONG time based on all the changes that doing so triggered... if this is a good idea can we agree on some standards for this and make it happen - or else we should just remove this `tool` as it's not really serving any purpose.

**Comment by yyyc514** [comment]
@egor-rogov Any thoughts?  If not I'm going to close this as something we just don't care about.  Io only brought it up because of the tool I found.

**Comment by egor-rogov** [comment]
Thought 1: Consistency is a good thing.
Thought 2: Need to see it in action... Give me some time to give it a try.

**Comment by yyyc514** [comment]
sure. I’m slightly against because I feel personally I’d make better choices on my own but as I’m not the one writing it all...... also hate how it will make git blame slightly harder to use but that’s less an issue here than in other projects. 

Probably hard to enforce a consistent standard without something like this. 

Let me know. no rush. Pay attention to whether it makes the grammars easier to read or not.

**Comment by yyyc514** [comment]
Closing this as I wasn't hugely in favor of this anyways and it's obviously not a high priority. :-)
