### ISSUE TITLE
C# parser error: single line lambda

### ISSUE THREAD

**Issue by xp44mm** [highlightjs/highlight.js#2228]
C# can not read single line lambda:
```C#
var y = arr.Select(x=>x+x);
```
previous code will error, more real-world example is：
```C#
Observable.Interval(TimeSpan.FromSeconds(1))
    .Buffer(2)
    .Subscribe(x => Trace.WriteLine(
        $"{DateTime.Now.Second}: Got {x[0]} and {x[1]}"));
```

**Comment by yyyc514** [comment]
Could you create a jsfiddle showing us the exact issue?

You can use my template:
https://jsfiddle.net/ajoshguy/a1kntyg4/

**Comment by yyyc514** [comment]
I'm not saying it's your mistake, just that a jsfiddle example is MUCH better than just pasting code here because it allows us to see exactly what is going on and means we can fix issues faster.
