### ISSUE TITLE
C# parser error: generic method

### ISSUE THREAD

**Issue by xp44mm** [highlightjs/highlight.js#2229]
for example this code will error:
```C#
[Fact]
public async Task Divide_WhenDenominatorIsZero_ThrowsDivideByZero()
{
  await Assert.ThrowsAsync<DivideByZeroException>(async () =>
  {
    await MyClass.DivideAsync(4, 0);
  });
}
```
when i change the type argument as comment, the parser will be correct:
```C#
[Fact]
public async Task Divide_WhenDenominatorIsZero_ThrowsDivideByZero()
{
  await Assert.ThrowsAsync/*<DivideByZeroException>*/(async () =>
  {
    await MyClass.DivideAsync(4, 0);
  });
}
```

**Comment by yyyc514** [comment]
Could you create a jsfiddle showing us the exact issue?

You can use my template:
https://jsfiddle.net/ajoshguy/a1kntyg4/

**Comment by yyyc514** [comment]
I'm not saying it's your mistake, just that a jsfiddle example is MUCH better than just pasting code here because it allows us to see exactly what is going on and means we can fix issues faster.
