### ISSUE TITLE
[css/scss] highlighting deficiencies

### ISSUE THREAD

**Issue by w3suli** [highlightjs/highlight.js#2232]
Current state:
BAD!
![BAD](https://user-images.githubusercontent.com/20889555/67665502-225ed280-f96a-11e9-83f5-f89a7682e098.png)

GOOD (if no prefix):
![GOOD-NoPrefix](https://user-images.githubusercontent.com/20889555/67665621-5934e880-f96a-11e9-802a-15b14252be3d.png)
GOOD (prefix):
![GOOD-Prefix](https://user-images.githubusercontent.com/20889555/67665643-66ea6e00-f96a-11e9-9f00-9cab7b3222e2.png)

**Just do not introduce prefix notation because the themes do not support I think bad.**

If the new class were introduced I would be happy to adjust the themes.
Enough to add to css themes:
.hljs-prefix{
opacity:0.55
}

Unfortunately, there are other bugs:

- Numbers in parentheses are not highlighted. `color: rgba(51, 170, 51, .1);` or `width: calc(100% - 80px);` or transform: rotate(45deg); or `filter: grayscale(0.5) blur(10px);`
- In the parentheses of the at rules, properties are not highlighted. `@media only screen and (orientation: landscape)` or `@media screen and (max-width: 900px) and (min-width: 600px), (min-width: 1100px)`

**Comment by yyyc514** [comment]
> If the new class were introduced I would be happy to adjust the themes.

We try to avoid this because it's a lot of work, and there are also 3rd party themes, not just the ones in this repo, etc... not sure there is THAT much value in making the prefixes slightly transparent.

> Unfortunately, there are other bugs:

A jsfiddle with special examples (that we can see actually running in context) would be great.

You can use my example:
https://jsfiddle.net/ajoshguy/a1kntyg4/

**Comment by w3suli** [comment]
[https://jsfiddle.net/w3suli/7xbLrcqa/40/](https://jsfiddle.net/w3suli/7xbLrcqa/40/)

No problem for users of old themes.
If someone wants to highlight prefixes, all they need is an extra css extension.
Further bugs can be easily corrected.
I've done what you asked for. I hope so, it's clear what I want!

I would appreciate it if you could improve the css highlights.

Thanks in advance!

**Comment by yyyc514** [comment]
For @media you're expert the max-width, min-width, etc to be highlighted?

**Comment by w3suli** [comment]
Selectors:
```
*
a[title], a[href*="example"] /*(The part between the square brackets can be colored like the pseudo-classes)*/
div, #id, .class
...
```

Pseudo-classes:
```
:first-child
:lang(en)
...
```

Pseudo-elements:
```
::after
::slotted(span)
...
```

CSS property or CSS attribute:
```
border:
background:
Color:
...
```
(The colon of the css property is followed by the property values)

Numbers and units:
```
4px
100%
45deg
...
```
(For numbers, you highlight numbers and units of measure separately. Some people only raise the number, not the unit of measurement. And some highlight the number and the unit of measure together. These solutions are acceptable.)

CSS functions:
```
calc(100% - 80px)
circle(6rem at 12rem 8rem)
...
```

CSS at-rules:
```
@page
@charset
@media
@supports
...
```

---------------------------------------------------------

```
@media screen and (min-width: 900px) {
  article {
    padding: 1rem 3rem;
  }
}
```

(at-rule: media, media type: screen, property: min-width, property value: 900px)


Interesting case:

```
@supports (display: flex) {
  @media screen and (min-width: 900px) {
    article {
      display: flex;
    }
  }
}
```
(at-rule: supports, property: display, value: flex)

**Comment by yyyc514** [comment]
@w3suli Some of that those things already work I'm sure... it'd be useful to have a checklist of the things you're currently finding lacking... that'd make it a lot easier for someone to pick this up and run with it.

**Comment by w3suli** [comment]
In the previous posts and in the example, I constantly show what doesn't work.

- The prefixes in the properties and the at-rules of are not uniform (dashes are not selected in one place).
- Properties are not highlighted in the at-rules.
- Numbers are not highlighted in functions.
- The at-rules do not highlight media types (this is less important).
- Numbers and units of measurement are highlighted together (highlighting separately would be better, but it doesn't matter).

These are all mistakes. Everything needs repair. Most of them are important. The last two are aesthetically pleasing but less important.

I want the css highlight to be as perfect as possible.
I try to keep track of the fixes and tell me if there are any bugs.

After correcting the bugs I will go through both css and scss.

**Comment by yyyc514** [comment]
> Numbers and units of measurement are highlighted together (highlighting separately would be better, but it doesn't matter).

Not sure that's a problem.  Pretty sure that's intentional.

---

I don't need a list, I need test cases (specific CSS that fails to colorize properly).  The closer you can provide to an actual test case (jsfiddle as requested) the sooner I might take a look at this myself.  Otherwise this might sit in the issue queue a very long time before anyone has time for "I want the css highlight to be as perfect as possible.".

I will leave this open as there are obvious deficiencies here, but if you want to see faster movement the information I asked for (in the format I asked for) would be super helpful. :)

**Comment by yyyc514** [comment]
Tagging this beginner friendly because a beginner can do a higher level overview and provide some nice test cases for developers to work with if @w3suli doesn't have the time or inclination.

**Comment by yyyc514** [comment]
To be clear, what would be super helpful (a jsfiddle with code like):

```
body {
/* numbers inside () are not highlighted proper */
width: calc(100% - 80px);
}

/* comment describing what is wrong with the below block:
media not highlighted,
min-width not highlighted.
screen not highlighted, etc.
 */
@supports (display: flex) {
  @media screen and (min-width: 900px) {
    article {
      display: flex;
    }
  }
}
```

**Comment by w3suli** [comment]
The prefixes in the properties and the at-rules of are not uniform (dashes are not selected in one place). 
[https://jsfiddle.net/w3suli/zkr9tno6/12/](https://jsfiddle.net/w3suli/zkr9tno6/12/)

Numbers are not highlighted in functions.
[https://jsfiddle.net/w3suli/w3n2b5ph/6/](https://jsfiddle.net/w3suli/w3n2b5ph/6/)

Properties are not highlighted in the at-rules. (The at-rules do not highlight media types) 
[https://jsfiddle.net/w3suli/phx9L5sd/10/](https://jsfiddle.net/w3suli/phx9L5sd/10/)

**Comment by yyyc514** [comment]
![Screen Shot 2019-10-29 at 10 33 59 PM](https://user-images.githubusercontent.com/6473/67824267-3c003700-fa9c-11e9-8c9e-0153f4353ecd.png)

I'm actually not sure which CSS to use... part of me wants to just make all the outside stuff the same color (keyword). ie ""all print screen speech only and or"

Not sure how the @ attributes should be colored.

**Comment by yyyc514** [comment]
![Screen Shot 2019-10-29 at 10 39 03 PM](https://user-images.githubusercontent.com/6473/67824517-ed9f6800-fa9c-11e9-8b23-75a984aaf71b.png)

Not sure and and or should be keyworded. Thoughts?

**Comment by w3suli** [comment]
The "@" sign is part of the rule. (At-rules). It would be better if he was highlighted, but not so much trouble if not.

However, where the prefix is used, the prefix dashes must be the same color as the prefix.

The "not", "only" and "and" must be the same color.
Media types: all, print, screen, speech.

**Comment by yyyc514** [comment]
> The "@" sign is part of the rule. (At-rules). It would be better if he was highlighted, but not so much trouble if not.

Yeah that's annoying. :-) Already saw that.

I know what the list of media types are.  If I go from the styling in my VS Code it's treating "print" screen and such as like "attribute values", which makes sense, but means that we wouldn't color them since we don't color values.

**Comment by w3suli** [comment]
Yes, the highlighting of the VS Code is clear.
![VScodeExample](https://user-images.githubusercontent.com/20889555/67858942-b5d70580-fb1a-11e9-826e-3936b60822b6.png)

**Comment by yyyc514** [comment]
Mine is different...
![Screen Shot 2019-10-30 at 8 41 17 AM](https://user-images.githubusercontent.com/6473/67859085-13565c80-faf1-11e9-8e4f-8311a8ec9c69.png)

**Comment by yyyc514** [comment]
![Screen Shot 2019-10-30 at 8 41 45 AM](https://user-images.githubusercontent.com/6473/67859108-1ea98800-faf1-11e9-8e8a-f6c1d50938fb.png)

Looks pretty nice to me though.

**Comment by w3suli** [comment]
These are not bad either.

**Comment by yyyc514** [comment]
@w3suli If you want to play around with that PR... feel free.

**Comment by w3suli** [comment]
The first tests are good.
The highlight has become nicer and clearer.

_I could have imagined a special emphasis on the prefixes._
_I would have highlighted "not", "only" and "and" separately from the At-Rules._

However, **the repair is good**.

Thanks

**Comment by w3suli** [comment]
Excuse me! I found a small bug.

Selector-attribute bug:

![SelectorAttribute](https://user-images.githubusercontent.com/20889555/67885441-e719fa80-fb47-11e9-914b-edabda115c64.png)

href, lang: attribute
"example": string
en: value

It's not that bad if you keep the current solution.
I know I haven't dealt with this in more detail before. But now, while testing, I thought about it.

These are true html attributes and HTML attribute values, but you might want to tag them as well.

**Comment by yyyc514** [comment]
> "example": string

I fixed this cause it's easy... please open a separate issue for the highlighting of the attribute inside a selector-attribute though, that needs to be thought about a bit more to be done correctly I think.

**Comment by w3suli** [comment]
[https://github.com/highlightjs/highlight.js/issues/2243](https://github.com/highlightjs/highlight.js/issues/2243)

**Comment by yyyc514** [comment]
Awesome, Very nice.  This will auto-close when the associated PR is merged.
