### ISSUE TITLE
C# parser error: method signature no take `async` into mind

### ISSUE THREAD

**Issue by xp44mm** [highlightjs/highlight.js#2233]
this example is misunderstand:
```C#
private async Task InitializeAsync()
{
}
```

**Comment by yyyc514** [comment]
How is it misunderstood?  A jsfiddle would be great.

You can fork my example:
https://jsfiddle.net/ajoshguy/a1kntyg4/

**Comment by xp44mm** [comment]
thank you! i will be check if it is my mistake again.

**Comment by yyyc514** [comment]
I'm not saying it's your mistake, just that a jsfiddle example is MUCH better than just pasting code here because it allows us to see exactly what is going on and means we can fix issues faster.
