### ISSUE TITLE
(csharp) highlight fail: `in` and `out` as generic variable modifier

### ISSUE THREAD

**Issue by xp44mm** [highlightjs/highlight.js#2239]
this is the jsfiddle:
```html
<pre>
<code class="C#">
interface IObserver&lt;in T&gt;
{
  void OnNext(T item);
  void OnCompleted();
  void OnError(Exception error);
}
interface IObservable&lt;out T&gt;
{
  IDisposable Subscribe(IObserver&lt;T&gt; observer);
}
</code>
</pre>
```
`in` and `out` should be keywords.

**Comment by yyyc514** [comment]
jsfiddle please.  Having a fiddle makes it easier to track these issues if they remain open a while and also allows developers to see them visually and fix them faster.

You can fork my template:
https://jsfiddle.net/ajoshguy/a1kntyg4/

**Comment by xp44mm** [comment]
this is the reproduction:
https://jsfiddle.net/0yu49Lf5/

**Comment by yyyc514** [comment]
I wonder if we even try to pattern match the `<>` at all...

**Comment by yyyc514** [comment]
@xp44mm If C# is your language this issue might be a great one to get your feet a little wet: https://github.com/highlightjs/highlight.js/issues/1947

**Comment by xp44mm** [comment]
maybe the highlightjs should split into two parts: tokenizer and render. people contribute their tokenizer will be easier.

**Comment by yyyc514** [comment]
If all you want is the CSS, it's pretty easy to build the tokenizer -> html side and then just use our stylesheets.

**Comment by yyyc514** [comment]
> maybe the highlightjs should split into two parts: tokenizer and render. people contribute their tokenizer will be easier.

I'm not sure for most people contributing a lexer would be simpler than contributing a list of regex patterns to match... 

Do you have a full JS tokenizer/lexer for C# though?  If so I'd be interested in exploring how someone MIGHT integrate such a thing as a plugin.  But my original point stands that if one has a parse tree already just turning it into HTML is the EASY part... you could simply wrap Highlight.js fairly easily. (though you don't need it at all at that point, just the CSS files)

**Comment by yyyc514** [comment]
What else are " generic variable modifier"s supported on other than interfaces?

Are in and out the only modifiers?
