### ISSUE TITLE
(css) selector-attributes are not highlight correctly

### ISSUE THREAD

**Issue by w3suli** [highlightjs/highlight.js#2243]
![SelectorAttribute](https://user-images.githubusercontent.com/20889555/67885441-e719fa80-fb47-11e9-914b-edabda115c64.png)

href, lang: attribute
"example": string
en: value, but must be highlighted as a string

_When using a selector-attribute, the attribute is highlighted as an attribute, but the value, number, or string that follows it is highlighted as a string._

[https://jsfiddle.net/w3suli/h13csq8r/7/](https://jsfiddle.net/w3suli/h13csq8r/7/)

Formats:
[attribute]
[attribute=value]
[attribute~=value]
[attribute|=value]
[attribute^=value]
[attribute$=value]
[attribute*=value]

_[attribute=value s]
[attribute$=value I]
[attribute^=value i]
[attribute~=value I]_

Values between the equals sign and the closing square bracket should always be highlighted as strings. Exceptions are "i", "I", "s", "S" before the closing square bracket. The keywords "i", "I", "s", "S".

> **[attr]**
>     Represents elements with an attribute name of attr.
> **[attr=value]**
>     Represents elements with an attribute name of attr whose value is exactly value.
> **[attr~=value]**
>     Represents elements with an attribute name of attr whose value is a whitespace-separated list of words, one of which is exactly value.
> **[attr|=value]**
>     Represents elements with an attribute name of attr whose value can be exactly value or can begin with value immediately followed by a hyphen, - (U+002D). It is often used for language subcode matches.
> **[attr^=value]**
>     Represents elements with an attribute name of attr whose value is prefixed (preceded) by value.
> **[attr$=value]**
>     Represents elements with an attribute name of attr whose value is suffixed (followed) by value.
> **[attr*=value]**
>     Represents elements with an attribute name of attr whose value contains at least one occurrence of value within the string.
> **[attr operator value i]**
>     Adding an i (or I) before the closing bracket causes the value to be compared case-insensitively (for characters within the ASCII range).
> **[attr operator value s]**
>     Adding an s (or S) before the closing bracket causes the value to be compared case-sensitively (for characters within the ASCII range).

(MDN)

**Comment by yyyc514** [comment]
Thanks, the matching all the equality expressions and testing all these cases was what I just didn't have time to get into.  I don't think this would be super difficult though, so tagged as such.

**Comment by yyyc514** [comment]
>  Exceptions are "i", "I", "s", "S" before the closing square bracket. The keywords "i", "I", "s", "S".

Ha, not even sure I knew about these.  I knew it would be more than meets the eye.

**Comment by yyyc514** [comment]
> but the value, number, or string that follows it is highlighted as a string.

Why wouldn't it be highlighted as a number perhaps if it was?

**Comment by w3suli** [comment]
`<html-element attribute="value">`
_The HTML5 standard does not require quotes around attribute values._

VSCode:
![SelectorAttributeVSCode](https://user-images.githubusercontent.com/20889555/67907189-75f23b80-fb77-11e9-9afb-b8175e5a9caa.png)

In the CSS attribute selector, attribute values are considered to be strings because they do not represent, for example, a numeric value. They function as simple strings.

**Comment by yyyc514** [comment]
Gotcha.

**Comment by yyyc514** [comment]
> The keywords "i", "I", "s", "S".

Do you have a suggestion from one of our exiting classes to highlight the modifier?

**Comment by w3suli** [comment]
Thinking about the class, I remembered that the prefixes "-webkit-", "-moz-", "-ms-", "-o-" could be put in the meta class.

"I", "I", "s", "S" are case-sensitive keywords. Since there is no case-sensitivity class, maybe the params class could be used.

**Comment by yyyc514** [comment]
> Thinking about the class, I remembered that the prefixes "-webkit-", "-moz-", "-ms-", "-o-" could be put in the meta class.

Which is often an entirely different color though.  The subtle opacity approach was a good idea if we were ever to do something like this.  I just don't think it's that big a deal.   Not worth creating  whole new class, and not worth using a drastically different class to differentiate a tiny part of the name.

If you'd like to fork the CSS grammar into your own 3rd party grammar and add such features you could.

**Comment by w3suli** [comment]
All right.
_Prefixes are not standard css elements. They were introduced as a necessary bad, which might eventually disappear._

What do you think about the params class?
"I", "I", '"s", "S" are case sensitive parameters.

**Comment by yyyc514** [comment]
I dunno traditionally that class has been for function params like `f(x,y)` where x,y are params... it'd be worth a try maybe if we have no other ideas.

**Comment by w3suli** [comment]
I know it's not perfect. Prismjs uses separate classes for this. I haven't found a better one yet, but I'm still thinking.

**Comment by yyyc514** [comment]
Even if we didn't highlight it all and just got the other stuff this would be nice. :)

**Comment by w3suli** [comment]
The symbol class may also be appropriate.

**Comment by yyyc514** [comment]
Closing as we are now tracking this with #2269
