### ISSUE TITLE
RELEASE: Can someone kick the release system please?

### ISSUE THREAD

**Issue by yyyc514** [highlightjs/highlight.js#2246]
http://highlightjs.org/api/release/

It's not releasing 9.16 and I have no idea why.

**Comment by marcoscaceres** [comment]
The only odd thing I see is “ add .0 back to package.json” associate with the release tag. I’d try a 9.16.1 release with that latest fix you added. If that fails Incan have a go at releasing.

**Comment by marcoscaceres** [comment]
Another thing to decipher is the fail message:
Traceback (most recent call last):
  File "/home/maniac/hljs_org/hljs_org/management/commands/updatehljs.py", line 104, in handle
    self._handle(version)
  File "/home/maniac/hljs_org/hljs_org/management/commands/updatehljs.py", line 44, in _handle
    assert re.search(r'"version"\s*:\s*"%s"' % node_version, open('package.json', encoding='utf-8').read()) is not None
AssertionError

Clue might be there? Did you tag things maybe before you updated the package file?

**Comment by marcoscaceres** [comment]
(Fwiw, it’s 99% something got done in the wrong order... the release script is pretty solid)

**Comment by yyyc514** [comment]
> File "/home/maniac/hljs_org/hljs_org/management/commands/updatehljs.py", line 44, in _handle
assert re.search(r'"version"\s*:\s*"%s"' % node_version, open('package.json', encoding='utf-8').read()) is not None

Probably but without the source and without knowing any context it's greek to me.  So node_version doesn't match? but what would that mean? No idea.

**Comment by yyyc514** [comment]
I'm also REALLY wanting to understand WHY it failed and what I did wrong, not just "try again and maybe it'll work"...

**Comment by yyyc514** [comment]
I retagged 9.16.0 to a new commit, and it failed again. I think the 3rd attempt is because it tries to build when a tag is deleted also.

**Comment by yyyc514** [comment]
> the release script is pretty solid

I think I'd beg to differ if the tiniest little thing can throw it off so easily.  Hard to say without knowing WHAT it's upset about though.

**Comment by yyyc514** [comment]
It's like saying "just reboot your computer".  So now it worked and I have no idea if it'll work next time or what the underlying problem is.  Not how I typically solve things like this. :(

**Comment by yyyc514** [comment]
It's interesting the last .0 was over a year ago... .14 and .15 are all missing .0 releases.

**Comment by yyyc514** [comment]
"Version 9.16.1 has not yet been updated on CDNs. Check back soon!" Interesting.

**Comment by isagalaev** [comment]
Hi everyone. I missed this notification unfortunately as I've got around 170+ messages from highlight.js in the last couple of weeks. I did notice deployment errors though… 

So this:

```
Traceback (most recent call last):
  File "/home/maniac/hljs_org/hljs_org/management/commands/updatehljs.py", line 104, in handle
    self._handle(version)
  File "/home/maniac/hljs_org/hljs_org/management/commands/updatehljs.py", line 44, in _handle
    assert re.search(r'"version"\s*:\s*"%s"' % node_version, open('package.json', encoding='utf-8').read()) is not None
AssertionError
```

… tries to find the version number that is being released in package.json to make sure npm has the same version. It should match exactly. So it was complaining when package.json contained `9.16` instead of `9.16.0`.

> Are the CDNs slow to update?

CDNs can indeed be slow to pick up a new version, sometimes for days. At the time of me writing this jsdeliver has picked it up and is displayed on the download page. It's business as usual.

> Or is that just the auto-memory of the site working?

I'd say it's browser remembering the form state from last time.

**Comment by yyyc514** [comment]
>  So it was complaining when package.json contained 9.16 instead of 9.16.0.

Only the VERY first time... after that it was 9.16.0 and that failed several times also.

**Comment by isagalaev** [comment]
Good suggestion, thanks! I'll add that just in case.
