### ISSUE TITLE
Breaks on mixed PHP and HTML

### ISSUE THREAD

**Issue by WishCow** [highlightjs/highlight.js#225]
The parser outputs broken HTML when you try to step out of the interpreter, and mix it with HTML:

```
<ul>
<? foreach ($items as $i) { ?>
<li><?=$i?></li>
<? } ?>
</ul>
```

Is there a way to make it fall back to HTML highlighting, outside <? or <?php blocks?

**Comment by JuanDiDiego** [comment]
Hello @isagalaev ,

I downloaded the latest version of highlight.js and I'm still having the issue that was talked about on this page.  I'm using PHP and HTML and when I preview the page the HTML doesn't show and it even looks like the HTML style gets applied.

Code View:
![screenshot from 2016-08-03 15-07-20](https://cloud.githubusercontent.com/assets/20046084/17378499/2c75145e-598c-11e6-9291-2d1683918aa2.png)

Browser View:
![screenshot from 2016-08-03 15-06-45](https://cloud.githubusercontent.com/assets/20046084/17378515/3efbf2e6-598c-11e6-95a5-66043ca5a2f3.png)
