### ISSUE TITLE
Can this support bbPress?

### ISSUE THREAD

**Issue by ajtruckle** [highlightjs/highlight.js#2255]
Thanks.

**Comment by yyyc514** [comment]
I think your going to have to provide a bit more detail?

**Comment by yyyc514** [comment]
Is bbpress not just PHP?  Please, more information and perhaps a link or some resources on exactly what you're asking for.  Are you meaning a grammar or some type of plugin for bbpress to highlight entries?

**Comment by ajtruckle** [comment]
Exactly. Some way to highlight sections of code in the two supported editors.

**Comment by yyyc514** [comment]
My question was an either or not a yes/no.

**Comment by yyyc514** [comment]
>  Some way to highlight sections of code in the two supported editors.

What are those two?  Can you provide some background or additional information?

**Comment by ajtruckle** [comment]
The TinyMCE editor and text editor. Like the former dual toolbar in the classic post|page editor in wp.

**Comment by yyyc514** [comment]
>  Like the former dual toolbar in the classic post|page editor in wp.

No idea what you're referring to here.  Pretend you're talking to someone who lives in a cave and ONLY works on Highlight.js. ;-)  You can attach images here, etc.

Ok, so sounds like this is about syntax coloring of a live code editor (and honestly perhaps an issue better filed against BBpress than us?).  That's specifically something we officially don't support (too complex).  Evidently some people have had some luck doing that, but it's not something we can support here.  Highlight.js is intended to support highlighting static code.

You could use it for a semi-live preview type thing, but if BBPress wasn't to use us for previews that would be something they'd have to add, not something we'd have to add. 

If I've misunderstood please correct me.

**Comment by yyyc514** [comment]
Closing as asked and answered. Let us know if you have any additional questions! :)
