### ISSUE TITLE
highlightjs.org/usage - List of supported languages

### ISSUE THREAD

**Issue by LukeTOBrien** [highlightjs/highlight.js#2256]
Hi guys,

I just wanted to see a list of supported languages a notices that your markdown table is not displaying at all.  
If you click on `The list of supported languages and corresponding classes` on the [usage page](https://highlightjs.org/usage/) you will see the markdown table appear as text rather than a table.

Thanks

(PS. I am creating lessons to teach kids programming and Highlight.js is awesome and saves me from using images to show code highlighting!)

**Comment by yyyc514** [comment]
Weird.

**Comment by yyyc514** [comment]
@isagalaev possibly some issue with the web server?  It looks good on Github.

**Comment by isagalaev** [comment]
Well… The technical reason is that Python's `markdown` library has no idea what a table is. Nor should it, as neither original markdown, nor even modern CommonMark has them.

A quick look shows that there's a plugin for tables, and there's a bunch of other markdown implementations I could try on the server side. On the other hand, may be that's another argument against having the full list directly within the Readme (I remember there was a discussion about that, but I don't remember the outcome).

My personal slight preference is always towards something standard, which currently means CommonMark, no matter how popular Github's flavor is. But I won't fight for it :-)

@yyyc514 @egor-rogov what do you think?

**Comment by yyyc514** [comment]
We can always just convey it to HTML too. ;)

**Comment by yyyc514** [comment]
> My personal slight preference is always towards something standard, which currently means CommonMark, no matter how popular Github's flavor is. 

How popular does it have to be before it becomes "standard"? :-)

**Comment by egor-rogov** [comment]
We had some discussion on this in #2096
+1 for a separate page with the list of supported languages, and link to it from README. Just can't find some time to do it.

**Comment by yyyc514** [comment]
I don't mind it being in the readme and would probably fix this by switching to a parser that supported GitHub style markdown and just be done with it.  Also don't see this as a super high priority though so time is an issue.
