### ISSUE TITLE
Uncaught TypeError: hljs.getLanguage(...).rawDefinition is not a function

### ISSUE THREAD

**Issue by mattwhocn** [highlightjs/highlight.js#2279]
when my code run in development with webpack it works fine, but when i build it and run at my website,
it went wrong and log the error message "Uncaught TypeError: hljs.getLanguage(...).rawDefinition is not a function", it looks like issues #1220 , but my version is 11.0.2.
plz help me out.

**Comment by yyyc514** [comment]
We’re still on version 9. Dunno what you mean by 11.

**Comment by yyyc514** [comment]
It sounds like your using a new grammar with an old release of highlight.js.

**Comment by yyyc514** [comment]
Cpp must be required before arduino.

**Comment by yyyc514** [comment]
How are you requiring the library in your setup?

**Comment by mattwhocn** [comment]
> We’re still on version 9. Dunno what you mean by 11.

sorry, i write wrong about the version.
the fact is: i use 'react-syntax-highlighter' version is 11.0.2
which depend on 'highlight.js', and when 'highlight.js' is update to 9.16.2,   'react-syntax-highlighter' auto use new version of 'highlight.js' lead to above error.

i solve it by  add "highlight.js": "9.15.10" in my package.json. but i still don't know why version 9.16.2  went wrong.

anyway thank for your reply and sorry about my poor english grammar.

**Comment by yyyc514** [comment]
This seems to be an upstream problem with `react-syntax-highlighter` and how they use/abuse the language loading process.  I will file an issue over there and see where it leads.

**Comment by yyyc514** [comment]
https://github.com/conorhastings/react-syntax-highlighter/issues/226

**Comment by yyyc514** [comment]
Ok, that was fun. 99% sure this is a problem with `lowlight` because it doesn't support one of the new internal features we added for dependencies.  Opened issue.

https://github.com/wooorm/lowlight/issues/19

**Comment by yyyc514** [comment]
@mattwhocn Thanks for bringing this to our attention!

**Comment by yyyc514** [comment]
https://github.com/wooorm/lowlight/commit/308eaea1fefe100fc1e6d7ab1e9bebebdc8a675a
