### ISSUE TITLE
The supported languages list is hard to spot and read

### ISSUE THREAD

**Issue by KrisAphalon** [highlightjs/highlight.js#2288]
[Documentation](https://highlightjs.readthedocs.io/en/latest/css-classes-reference.html#language-names-and-aliases) points to [README](https://github.com/highlightjs/highlight.js) file, but spotting tine little '►' is hard and confusing task. More than that, even spotted it is hard to read and seem out of place. It might be a good idea to move it into a separate file for easy linking and easier searching.

**Comment by lethargilistic** [comment]
I want to echo this. Kris mentioned not being able to find the list in a Discord chat I help moderate, before figuring it out. At least three other people tried to help and missed it.

**Comment by yyyc514** [comment]
Thanks.

Closing as duplicate of https://github.com/highlightjs/highlight.js/issues/2256.

**Comment by yyyc514** [comment]
N/m, slightly different. :)

**Comment by yyyc514** [comment]
I'm open to suggestions here.  We should find a way to kill both these birds with one stone.

**Comment by Samoxive** [comment]
Moving it to its own file would work, we can replace the section in README with a link to the documentation file for the supported files. If this proves cumbersome maybe it can be moved back to the readthedocs website of the project, I am not aware of why it was moved in the first place.

**Comment by yyyc514** [comment]
I think it has value in the README.  README is where I'd expect to find the list.

I think the issue is the HTML:

```
<details>
<summary>
```

Why not just make this a full heading "Supported languages" and do away with the details/summary since honestly the summary is NOT helpful at all?

**Comment by Samoxive** [comment]
That would work, we can directly link the heading, people should be able to expand the list afterwards.

**Comment by yyyc514** [comment]
I meant avoid the need to expand the list at all... scrolling long readme's isn't really a problem these days IMHO.

**Comment by egor-rogov** [comment]
Unfortunately after this change, the list is still not very easy to find.
I'm thinking about something like this:
1. Get rid of summary/details in README, but reduce the list to, say, the common set of languages (to make it shorter and easier to scroll)
2. Move the full list to a separate file and link to it from README
3. Link to the full list directly from the website

**Comment by yyyc514** [comment]
Sounds reasonable though I don’t like having to maintain data in two places. Easy to update one, forget the other. Etc. 

Really the table should be auto generated wherever it lands.

**Comment by yyyc514** [comment]
I do think the PR improved things but reopening this issue also.
