### ISSUE TITLE
Opening brace and quotes highlighted inconsistently

### ISSUE THREAD

**Issue by gmnash** [highlightjs/highlight.js#230]
The opening brace of some objects are not highlighted like all closing braces.  Also quotes are sometimes highlighted, sometimes not.  Not a problem with the CSS as it happens in all of the demo examples.  The parser does not tag those structures for presentation.
![highlightjs_bug](https://f.cloud.github.com/assets/19375/586722/7665e7ac-c955-11e2-9819-a95d4b375bd1.png)

**Comment by k-funk** [comment]
+1
