### ISSUE TITLE
[Syntax] System Log syntax highlight

### ISSUE THREAD

**Issue by matthewkwong2** [highlightjs/highlight.js#2303]
I am hoping to have syntax highlight for system log. Is this possible?

e.g. (Image resource from https://github.com/poucotm/Log-Highlight)
![image](https://raw.githubusercontent.com/poucotm/Links/master/image/Log-Highlight/lh-system.gif)

**Comment by yyyc514** [comment]
We're not currently accepting new language submissions (and the core team primarily maintains the library - we don't typically add requested languages - that's traditionally been the larger community), but anyone is free to publish a language as an external repo or NPM and it's very easily to plug new language files into Highlight.js as language extensions.

So if you wanted to take a stab at it feel free.

**Comment by yyyc514** [comment]
You might also look thru the open language PRs (which are all on hold). I think one or two people were working on something like this already.
