### ISSUE TITLE
9.17 Release

### ISSUE THREAD

**Issue by yyyc514** [highlightjs/highlight.js#2315]
Keying up for this.

@egor-rogov Could you take a quick look at PRs listed in https://github.com/highlightjs/highlight.js/milestone/19  sometime in the next week?  I'd like to get all this merged before 9.17.  I don't think it should require much work/review.  They are pretty simple ones; this list doesn't include any of the new plugin/hooks stuff (which will push off until 9.18 or 10).

If you have big concerns or issues let me know and we can always pull something, but otherwise if it's a small concern or some little thing please let me know what you'd like to see before you'd consider these approvable.

Thanks!

**Comment by yyyc514** [comment]
Ha, I think Github auto-tagged this 9.17, that was pretty cool.

**Comment by yyyc514** [comment]
9.17 has been released. @egor-rogov

**Comment by egor-rogov** [comment]
Hurray! (:
