### ISSUE TITLE
Add MDX support

### ISSUE THREAD

**Issue by lachlanjc** [highlightjs/highlight.js#2317]
It’d be amazing to have support for [MDX](https://mdxjs.com/), which is a mix of Markdown + JavaScript/JSX.

**Comment by yyyc514** [comment]
Please see: https://highlightjs.readthedocs.io/en/latest/language-requests.html

If you'd like to create support for this yourself as a language add-on you're more than welcome to do so and we can link to your repo (or even host it)!
