### ISSUE TITLE
Error with Object.Freeze() in IE 11

### ISSUE THREAD

**Issue by christopherpickering** [highlightjs/highlight.js#2318]
Hi, Thanks for the plugin!

When my site is run in IE 11 there is an error with the "object.freeze()". Do you know a workaround I can put in? Thanks!
![image](https://user-images.githubusercontent.com/17788706/70633320-a7f3c480-1c30-11ea-8433-c21276b19248.png)

**Comment by yyyc514** [comment]
If I float a fix are you capable of building a new distributable locally to test?

I’m guessing this is the issue:

https://github.com/datorama/akita/pull/95/commits/8a6306542595a8e2230b09299cff4be35fd3af7b
https://github.com/brandonroberts/ngrx-store-freeze/issues/7

Technically we don’t support IE11 any more but my intention was to try and not break it until 10.0 and then officially end support, which is likely the next release.

**Comment by christopherpickering** [comment]
Sure I can give it a shot! Thanks!

Thanks,
Christopher

**Comment by yyyc514** [comment]
Build a new version against https://github.com/highlightjs/highlight.js/pull/2319 and test please.

**Comment by christopherpickering** [comment]
Thanks, I built and tested, but still get the same error. I think the function Object.freeze(o); just doesn't exist in IE 11.

![image](https://user-images.githubusercontent.com/17788706/70697838-89400d00-1cc6-11ea-98b4-a42dd10fe788.png)

If this section of the code is removed it still works well (not sure what else is affected!) but in my app its cool.. maybe performance is slightly affected? I'm using highlight.js for a handful of  sql code blocks.

If you have another idea I'd appreciate it! - otherwise I can use the code w/ this block commented out. (lines 1130 - 1151 in src/highlight.js)

![image](https://user-images.githubusercontent.com/17788706/70698288-74b04480-1cc7-11ea-89f4-7fdb94dcbbb0.png)

**Comment by yyyc514** [comment]
Freeze exists. The error is telling you that. 

Could you add some logging and console.log both the object and property right before freeze is called and let me know **which** item or property it’s blowing up on?

Commenting it out will probably work as a quick fix. This code prevents language plugins from corrupting the parser itself by modifying the shared regexes - which it turns out our own languages were doing in the past (by accident).

**Comment by christopherpickering** [comment]
Good point 👍 

Yes - here's a few few pics. It seems to be because the first object is a string, not an "object" -

![image](https://user-images.githubusercontent.com/17788706/70702325-2d798200-1cce-11ea-9265-e6558a92b657.png)

![image](https://user-images.githubusercontent.com/17788706/70702357-38ccad80-1cce-11ea-91ce-0255fbf2b4cc.png)


To test out, I changed the order of the object array to put one of the "objects" first to see if the function would successfully complete. It fails in my console.log at the freeze check with the object error, but should not hit this at runtime because the first conditions are true.

![image](https://user-images.githubusercontent.com/17788706/70702676-e63fc100-1cce-11ea-97c7-33559a075723.png)


Here is  rerun with the console.log removed from that section:
Now it works until it gets to a string in the array.

![image](https://user-images.githubusercontent.com/17788706/70702892-54848380-1ccf-11ea-8f94-ba19e3f10440.png)

What do you think?

**Comment by christopherpickering** [comment]
btw, I apologize for using ie 11 😭 my personal feeling is that IE does not qualify as a browser 😄

**Comment by yyyc514** [comment]
> In ES5, if the argument to this method is not an object (a primitive), then it will cause a TypeError. In ES2015, a non-object argument will be treated as if it were a frozen ordinary object, and be simply returned.

Ah.  Can you try the PR again?  I modified it so we don't try to freeze any of the strings.

**Comment by yyyc514** [comment]
> btw, I apologize for using ie 11 

No problem.  I appreciate your reporting this.  My intention was always for 9.x to be a stable release series that people could continue to use for a while if they needed support for IE11 and older browsers while 10.0 moves on to newer things.  So I'd def like to see this fixed if we can. :)

But we don't actively test new changes in IE11.

**Comment by christopherpickering** [comment]
Thanks, that works very well. I appreciate it!

**Comment by yyyc514** [comment]
Releasing 9.17.1 with the fix.
