### ISSUE TITLE
9.17.0 introduced unnecessary `handlebars` as a dependency instead of devDependency

### ISSUE THREAD

**Issue by dr-js** [highlightjs/highlight.js#2320]
the commit: https://github.com/highlightjs/highlight.js/commit/6474be5c47a7b1214b57504d7b2ea6b11b5d1f2c

this issue should be similar to https://github.com/highlightjs/highlight.js/issues/1993

checked the released package code, there seems no direct `require()` to the `handlebars` package, maybe it's only for dev & testing?

```
Targets
    Occurrences of 'handlebars' in directory ...\node_modules\highlight.js
Found Occurrences  (5 usages found)
    node_modules\highlight.js  (1 usage found)
        package.json  (1 usage found)
            1130 "handlebars": "^4.5.3"
    node_modules\highlight.js\lib  (2 usages found)
        index.js  (2 usages found)
            77 hljs.registerLanguage('handlebars', require('./languages/handlebars'));
            77 hljs.registerLanguage('handlebars', require('./languages/handlebars'));
    node_modules\highlight.js\lib\languages  (2 usages found)
        handlebars.js  (1 usage found)
            31 aliases: ['hbs', 'html.hbs', 'html.handlebars'],
        xml.js  (1 usage found)
            130 subLanguage: ['actionscript', 'javascript', 'handlebars', 'xml']
```

and the ~3MB size bloat: https://packagephobia.now.sh/result?p=highlight.js@9.17.0

**Comment by yyyc514** [comment]
Do you know the npm command to type to fix that?

Even better would have been the npm command I should have used the first time to avoid this entirely. :)

**Comment by yyyc514** [comment]
Ok, --save-dev seems to fix it.  Do you feel this requires a 9.17.2 release?

**Comment by dr-js** [comment]
- `-D`, `--save-dev`: Package will appear in your `devDependencies`.
ref: https://docs.npmjs.com/cli/install

Edit the `package.json` by hand is also doable, should run `npm install` to update the `package-lock.json`

**Comment by dr-js** [comment]
I'm not affected by the size increase since I'll re-pack `highlight.js` with `webpack`

The fix https://github.com/highlightjs/highlight.js/commit/40ef5c4eeda72b96c54b9e2d820c4998d12e4af4 was quick! I'll close this issue then

**Comment by yyyc514** [comment]
Thanks for reporting!
