### ISSUE TITLE
(javascript) Support for JSX fragments

### ISSUE THREAD

**Issue by luisherranz** [highlightjs/highlight.js#2327]
Right now JSX only supports tags with at least one character, but JSX has a concept called fragments that are created without any character, like this:
```jsx
class Columns extends React.Component {
  render() {
    return (
      <>
        <td>Hello</td>
        <td>World</td>
      </>
    );
  }
}
```

It'd be great if highlight.js could support that.

**Comment by yyyc514** [comment]
Can fragments have attributes and such things or are they always literal `<>` and `</>`?

**Comment by luisherranz** [comment]
They can have a `key` but then you can't use `<>` anymore, you have to use `<Fragment>`: https://reactjs.org/docs/fragments.html#keyed-fragments

**Comment by yyyc514** [comment]
Can I have a fragment inside a fragment (though I don't know how that'd be useful)?

**Comment by luisherranz** [comment]
I guess so but I've never seen it. It looks like an extreme edge case to me. If it overcomplicates the regexp, I wouldn't include it.

**Comment by luisherranz** [comment]
Awesome! Thanks Josh :clap:
