### ISSUE TITLE
Suggest: Change require API for just the core library

### ISSUE THREAD

**Issue by yyyc514** [highlightjs/highlight.js#2334]
Suggestion:

```diff
// require the highlight.js library including all languages
const hljs = require('./highlight.js');

// require the highlight.js library without languages
- const hljs = require("highlight.js/lib/highlight.js");
+ const hljs = require("highlight.js/core.js"); 
```

We could slide this change in with v10.  I hate the redundancy and think this is a bit nicer.  Unless there is some JS convention here that says the other way is the normal way everyone expects libraries to be structured?

I think we could even preserve the old API and just deprecate it.

@egor-rogov Thoughts?

**Comment by egor-rogov** [comment]
It looks nicer, I agree. And what a request for a specific language will look like?

**Comment by yyyc514** [comment]
Exactly same, this is all the change I'm suggesting. :-)

**Comment by egor-rogov** [comment]
So, `core.js` and `lib/languages/foo`? Well, at least I'm not opposed.
