### ISSUE TITLE
It's not well to print error log info when I have catch the exception

### ISSUE THREAD

**Issue by sidian123** [highlightjs/highlight.js#2337]
I aware that some language haven't module and will throw exception. I have locate the code :
```javascript
    var language = getLanguage(name);
    if (!language) {
      console.error(LANGUAGE_NOT_FOUND.replace("{}", name));
      throw new Error('Unknown language: "' + name + '"');
    }
```
I can catch the exception and let highlight.js to auto detect the language, as follow:
```javascript
  /**
   * 代码解析
   * @param code raw代码
   * @param language 语言
   * @private
   */
  _codeHighlight(code,language){
    let res;
    try{//正常情况下, 执行语言解析
      res=highlight.highlight(language,code);
    }catch (e) {//highlight库不能识别该语言时, 让其自动推断最合适的解析方式(自动判断语言).
      res=highlight.highlightAuto(code);
    }

    return res.value;
  }
```
then my console print some error log:
```log
Could not find the language 'unknow', did you forget to load/include a language module?
```
I think it's not very good that print error log after I have catch exception. I think the following will be better:
```javascript
    var language = getLanguage(name);
    if (!language) {
      throw new Error('Unknown language: "' + name + '"');
    }
```
> no error log printed in here

**Comment by yyyc514** [comment]
Are you using this in the browser or Node?

What you can do instead is try calling `getLanguage` before you call `highlight`.  If the language isn't found, then call `highlightAuto`.  

I think in most cases the extended error messages are helpful and not sure if globbing them into one larger error message is better.

**Comment by yyyc514** [comment]
@sidian123 If you submitted a PR that added the second error message/suggestion to the actual error after a newline that'd be acceptable I think.

**Comment by sidian123** [comment]
I used it in browser.

Since i'm a Java programer, i'm used to catch exception to get info and handle it.

But the method `getLanguage` also can solve my problem, very thanks ~

**Comment by yyyc514** [comment]
Glad to help!  Again, PR welcome. Closing issue.
