### ISSUE TITLE
Does not support "explicit" in C++

### ISSUE THREAD

**Issue by ppwwyyxx** [highlightjs/highlight.js#2339]
```javascript
str = 'class B {\n' +
     '  public:\n' +
     '    explicit B(const A&amp; a) : a_{a} {}\n' +
     '};\n' +
     '\n'
hljs =require("highlight.js");
console.log(hljs.highlight("c++", str))
```

prints
```
{
  illegal: true,
  relevance: 0,
  value: 'class B {\n  public:\n    explicit B(const A&amp;amp; a) : a_{a} {}\n};\n\n'
}
```

but it works after removing "explicit".

**Comment by yyyc514** [comment]
Thanks for reporting this.  Currently this is known issue.

_Closing as a duplicate_ of https://github.com/highlightjs/highlight.js/issues/1980.

**Comment by yyyc514** [comment]
I have a fix for this laying around but its' mixed in with a bunch of other stuff and hasn't been a priority yet.
