### ISSUE TITLE
(fortran) does not highlight block statement

### ISSUE THREAD

**Issue by interkosmos** [highlightjs/highlight.js#2342]
The Fortran 2008 `block` statement is not recognised by highlightjs. It should be highlighted like any other intrinsic statement of the language. Example:

```
<pre><code class="fortran">program main
    implicit none

    block
        real :: r
    end block
end program main</code></pre>
```
(`block` is not formatted in bold.)

**Comment by yyyc514** [comment]
Confirmed.  Block does not seem to be a keyword at present.

**Comment by yyyc514** [comment]
@interkosmos Any chance you'd be willing to whip up a PR and quick test?
