### ISSUE TITLE
What is the syntax for language aliases in the hljs.configure() function

### ISSUE THREAD

**Issue by vonHabsi** [highlightjs/highlight.js#2346]
I am trying to use the languages option in hljs.configure() with an alias.

I  use org-export which prefixes the language with `src-` so bash is output as `src-bash`.

How do I configure detection of `src-bash` as an alias for bash?

I know  `src-bash` is detected as a language the automatic detection which always adds ruby to the `<pre>` blocks is disabled when I add it to configure. The syntax for making it an alias for bash is what I need now.

```
hljs.configure({
  classPrefix: 'src-',
  languages:['src-bash']
})
```

**Comment by yyyc514** [comment]
`languages` should always include the ACTUAL names.  `src-` prefixs are only when using CSS class names.

**Comment by yyyc514** [comment]
```
hljs.configure({
  classPrefix: 'src-',
  languages:['bash']
})
```

Later:

```
<pre><code class="src-bash">
...
</code></pre>
```

**Comment by vonHabsi** [comment]
I realized afterwards that `src-bash` is the prefix used in the CSS file and that was an error.

However  orgmode exports the language code prefixed with `src`. A bash block is expressed as  
`#+begin_src bash` and is exported as `<pre src src-bash>`, lisp is written as `#+begin_src lisp` and exported as `<pre src src-lisp>`, elisp expressed and exported as`#+begin_src elisp`  - > `<pre src src-elisp>` etc

The problem is highlightjs doesn't know of any languages `src-bash`, `src-lisp`, `src-elisp` so the languages parameter must alias`src-bash` to `bash` and both `src-lisp`and `src-elisp` to `lisp`.

[configure options](https://highlightjs.readthedocs.io/en/latest/api.html#configure-options)

`languages:` an array of language names and **aliases** restricting auto detection to only these languages.

I am not well versed in Javascript but from the way the documentation reads the languages parameter should be something along the lines of  `languages{['alias1', 'lang1'],['alias2','lang1'],...}` where `lang1` and `lang2` are the languages bundled in the pack.

So for example if my languages pack contains only lisp and bash I will want to use bash highlighting for `zsh`, `fish` and `ksh` and use lisp highlighting for `elisp` and `maclisp`,

the languages parameter would be along the lines of 

 `languages: {['zsh', 'bash'], ['ksh', 'bash'], ['fish','bash'], ['elisp', 'lisp'], ['maclisp', 'lisp']}`

It is the syntax for associating an alias with a language I want to know. I'm sure if was more familiar with Javascript I would have worked it by now. :)

**Comment by yyyc514** [comment]
Well, first if you *insist* on not using `code` tags you'll need to write some of your own JS, see the `README` for details.  Only `<pre><code>` blocks are auto-detected.

The snippets I gave you earlier should work IF You are using `pre/code`.  If not you're writing your own JS anyways so you might as well just strip off the `src-` rather than try and hack Highlight.js.

**Comment by yyyc514** [comment]
> So for example if my languages pack contains only lisp and bash I will want to use bash highlighting for zsh, fish and ksh and use lisp highlighting for elisp and maclisp,

That's a better question. :-)  Although I'm not sure if you're asking the same thing but giving me a better use case. :-)  But that's fine.  

There is no easy way to do that, since the aliasing is all internal to Highlight, but you can hack it be redefining new langauges:

```
var bash = hljs.requireLanguage("bash").rawDefinition();
bash.aliases.concat(["zsh","fish","etc"])
// push the new bash back overtop of the old one
hljs.registerLanguage("bash", bash)
```

**Comment by yyyc514** [comment]
ANOTHER easy way to do that that (since you have to write JS in any case) is just do the aliasing yourself, and then Highlight.js knows NOTHING about it... it's just all your own code and then the PROPER official name gets passed to HLJS when it's time to highlight.

**Comment by vonHabsi** [comment]
The `src-lang` is used by emacs for its own highlighting code in its own CSS files

Actually highlightjs recognizes `<pre class="src src-lisp">` as defining a language block from the first `src`, but it treats `src-lisp` as a language, and my understanding is that aliasing allows an expression like `src-lisp` to be mapped to a language it recognizes like `lisp`.

I modified one of the css files replacing `hljs` with `src` and that is when I realized that `src-` is the prefix for the CSS classes not from the language so I removed the `classPrefix` parameter as it was superfluous.

I think the confusion comes from the use of the term **aliases** in the documentation and I took it to mean that if the language dialect you want is not included in the pack you alias your language to the nearest one in the pack, eg from `scheme`  to `lisp`.

I have a feeling that is what the guys who wrote the doc meant , but it has seen so little use that it has been forgotten about, although the code that implements is still functional but not documented. Perhaps it has never been used because its usage hasn't not been documented in the first place.

I think I'm right as it makes perfect sense that the designers would conceive of such a possibility, after all **they ARE clever guys**.

`org-babel` executes code using interpreters based on those language prefixes, and will use the wrong interpreter if the language code is changed for convienence sake. If I were to change `elisp` to `lisp` in the original document, `org-babel` would use another lisp, so I can't do that.

I think this is what the aliasing does, allowing a little used dialect to use the highlighter of a better known language.

If I'm wrong about that then perhaps I should put in a feature request for that.

**Comment by vonHabsi** [comment]
> ```js
> var bash = hljs.requireLanguage("bash").rawDefinition();
> bash.aliases.concat(["zsh","fish","etc"])
> // push the new bash back overtop of the old one
> hljs.registerLanguage("bash", bash)
> ```

I have a feeling that the language aliasing if it is what I think it is, is implemented by your  code above :)

**Comment by yyyc514** [comment]
Actually highlightjs recognizes <pre class="src src-lisp"> as defining a language block from the first src...

I don't see how that's correct.  The code is literally:

`var blocks = document.querySelectorAll('pre code');`

If your'e using `highlightAuto` that is... if you're manually picking the blocks then of course it doesn't care...

> but it treats src-lisp as a language, and my understanding is that aliasing allows an expression like src-lisp to be mapped to a language it recognizes like lisp.

It's not aliasing that does that, it's the `classPrefex` feature, nothing to do with aliasing.

> I modified one of the css files replacing hljs with src and that is when I realized that src- is the prefix for the CSS classes not from the language so I removed the classPrefix parameter as it was superfluous.

OHHHHHH.... were talking about different things.  There is no way to assign arbitrary "prefixes" simply JUST for detection. You can use `lang-` or `language-`, those are built-in and hard coded.  It's be pretty easy to build your own custom library build to change those (it's a single regex), but it's not a feature.

> I think the confusion comes from the use of the term aliases in the documentation and I took it to mean that if the language dialect you want is not included in the pack you alias your language to the nearest one in the pack, eg from scheme to lisp.

Is there an exact bit of documentation you found especially confusing that we could perhaps take a look at?

> I think this is what the aliasing does, allowing a little used dialect to use the highlighter of a better known language.

Not really, it's to allow us internally to say that one language MIGHT be referred to in different ways, and in many cases we add the file extensions also... So "ruby" and "rb".

An external API to add arbitrary aliasing isn't the worst idea though... but that would be a feature request... if you want to do that please re-edit your original post and we'll rename this so that we have all this rich context here.

**Comment by yyyc514** [comment]
I think we'd also be posing to making the language prefix a configurable option, then if all you wanted was a prefix you could do that in one spot... the aliasing is another matter.

Existing code (hardcoded):

```
      languagePrefixRe = /\blang(?:uage)?-([\w-]+)\b/i,
```

**Comment by vonHabsi** [comment]
I got it working earlier by adding this code to emacs, but will change it not to replace the `src-xxxx` but add `xxxx` to the class in case some other software requires the `src-xxxx`

``` elisp
    (defun my/org-html-src-block (html)
      "Modify the output of org-html-src-block for highlight.js"
      (replace-regexp-in-string
       "<pre class=\"src src-" "<pre class=\"src "
       html))
    (advice-add 'org-html-src-block :filter-return #'my/org-html-src-block)
```
I have the block detection working via
```js
document.addEventListener('DOMContentLoaded', (event) => {
  document.querySelectorAll('pre.src').forEach((block) => {
    hljs.highlightBlock(block);
  });
});
```

**Comment by yyyc514** [comment]
That's one way to get it done... or you could just as easily do the same thing on the JS side with the DOM, but I presume you're more familiar with emacs scripting.

**Comment by vonHabsi** [comment]
> I think we'd also be open to making the language prefix a configurable option, then if all you wanted was a prefix you could do that in one spot... the aliasing is another matter.
> 
> Existing code (hardcoded):
> 
> ```
>       languagePrefixRe = /\blang(?:uage)?-([\w-]+)\b/i,
> ```
> 
> Though it would need a clearer name.

If additional prefixes like `src-`, `source-` were added how would `languagePrefixRe` look like?

**Comment by yyyc514** [comment]
You'd have to use regex `|`... https://www.regular-expressions.info/alternation.html

**Comment by yyyc514** [comment]
```
/\b(lang|src|source|code)-([\w-]+)\b/i,
```

**Comment by vonHabsi** [comment]
Coming to think of it would be better for my alias idea to be implemented with the intention of having `fish`, `zsh` as aliases for `bash` as an example.

Using `src-lisp`, `src-elisp` as aliases for `lisp` would an undocumented benefit, but an abuse of the concept.

**Comment by vonHabsi** [comment]
> There is no perfect way to do that, since the aliasing is all internal to Highlight, but you can hack it be redefining new languages based on the old ones.
> 
> ```js
> var bash = hljs.requireLanguage("bash").rawDefinition();
> bash.aliases.concat(["zsh","fish","etc"])
> // push the new bash back overtop of the old one
> hljs.registerLanguage("bash", bash)
> ```
> 
> You could also wrap that up nicely with a helper function of course.

I think this code should meet my needs.
