### ISSUE TITLE
(markdown) no support for 4 backticks to escape code including 3 backticks

### ISSUE THREAD

**Issue by cjh9** [highlightjs/highlight.js#2350]
Highlight version: 9.17.0
Built from source, last commit 701184e

### Input:
````
code = "Code
================================
``` py
a = 'This is a code block in python'
```
`this is inline code` in a paragraph

Questions
================================
"
````
### Output:
`hljs.highlight('markdown', code).value`

Results in output:

```
"<span class="hljs-section">Code
================================</span>
<span class="hljs-code">```</span> py
a = 'This is a code block in python'
<span class="hljs-code">```
`this is inline code` in a paragraph

Questions
================================
</span>"
```

**Comment by yyyc514** [comment]
Our rules say that the end quotes MUST start on a new line.  Is this not correct?

**Comment by cjh9** [comment]
In this case I'm surrounding the block with four backticks, and explaining markdown:
`````
```` md
Code
================================
``` py
a = 'This is a code block in python'
```
`this is inline code` in a paragraph

Questions
================================
````
````` 
But only the above goes into the highlighter.

**Comment by yyyc514** [comment]
I'd say the real problem is we don't support four backticks... so those are probably just registering as jumping in and out of normal strings, which is never going to work with. :-)

**Comment by yyyc514** [comment]
> In this case I'm surrounding the block with four backticks, and explaining markdown:

Is there someplace I can find this 4 backpack syntax documented?

**Comment by hlovdal** [comment]
The four (N+1) backticks syntax is supposed to make it easier to embed code with three (N) backticks inside.

<https://bookdown.org/yihui/rmarkdown/markdown-syntax.html>
<https://github.github.com/gfm/>

**Comment by joshgoebel** [comment]
Thanks, I've since used them. :-)  This should work find now since #2382.
