### ISSUE TITLE
Highlight keys in JSON with separate class and extracts text

### ISSUE THREAD

**Issue by hcsgzh** [highlightjs/highlight.js#2352]
Hi there,
I want to highlight my json keys with a separate class.
```
{
    "XXXuserId": {
        "XXXnumber": 123,
        "XXXlocation": "string",
        "XXXdate": 1579042434845
    },
    "password": "string",
    "login": "string",
}
```
All the keys starts with `XXX` will be bold. Other keys are not.
I can do it by changing the json.js file like below.
```
  var OBJECT = {
    begin: '{', end: '}',
    contains: [
      {
        className: 'doctag',
        begin: /"XXX/, end: /"/, excludeBegin:true,
        contains: [hljs.XXX_ESCAPE],
        illegal: '\\n',
      },
      hljs.inherit(VALUE_CONTAINER, {begin: /:/})
    ].concat(ALLOWED_COMMENTS),
    illegal: '\\S'
  };
```

However, I don't want the `XXX` character. How can I remove `XXX` from the keys of json. So the result will be like below.
```
{
    "userId": {   // key, userId is bold and the  `XXX` is removed from original json keys.
        "number": 123, // key, number is bold and the  `XXX` is removed from original json keys.
        "location": "string", // key, location is bold and the  `XXX` is removed from original json keys.
        "date": 1579042434845 // key, date is bold and the  `XXX` is removed from original json keys.
    },
    "password": "string", // key password is not bold.
    "login": "string", // key login is not bold.
}
```

Thanks in advance!

**Comment by yyyc514** [comment]
The code input is the code outputted (just highlighted).  There is no way to "remove" content.  It's possible you could do this AFTER highlighting with a clever regular expression since you know what the HTML will look like right before the XXX... Or if XXX is distinct enough just a `replace(XXX,"")` might get you by.

**Comment by yyyc514** [comment]
What is XXX? Ie, what is the real life use case here?

**Comment by hcsgzh** [comment]
XXX is a tag for the distinction of json keys.
In the real-life case, the distinction of json keys or fields will make the json intelligible. If I would change the font or colour of each field of json, or I would use a different background for a group of fields in json, that would be ideal. 
In my case, for now, using XXX or other tags to define different font or colour of keys in json, works for me. I can use `replace(XXX, "")` to solve my problem for now.
I think highlighting code is not just for beautiful but meaningful. 
Thanks for your response!

**Comment by yyyc514** [comment]
If you're doing this in the browser you an also add pure HTML to your block and style your tags however you want, if it's easy for you to do that BEFORE hand.

<pre><code>
boring json
<span class="OMG-look">interesting json</span>
boring json
</code></pre>
