### ISSUE TITLE
(cpp) Identifiers may not always be highlighted properly

### ISSUE THREAD

**Issue by yyyc514** [highlightjs/highlight.js#2353]
Egors quote from elsewhere:

> hljs.UNDERSCORE_IDENT_RE + '::' ?
Btw, I'm not 100% sure but looks like C++ allows underscore as the first character in identifiers, so maybe all (most?) instances of hljs.IDENT_RE below should really be hljs.UNDERSCORE_IDENT_RE. (This is not showstopper of course.)

**Worth looking into.**

**Comment by yyyc514** [comment]
@egor-rogov 

I think you may be technically correct here but there seem to be some actual usage rules that are pretty specific... **like _ is often reserved at top/global level but not inside namespaces**, etc... I asked someone the other day but just got more confused.  But this seems close to what we're already doing here anyways.

Unless you want to take this and do some more research I'm going to close it as a real issue until someone actually finds a problem with some real code that we aren't highlighting properly.

**Comment by egor-rogov** [comment]
It is reasonable. I've noticed this difference between our grammar and the formal language grammar, but since no one is complaining...
