### ISSUE TITLE
Fortran highlighter eats chars

### ISSUE THREAD

**Issue by dannysauer** [highlightjs/highlight.js#2355]
When a number is detected by the Fortran parser, if the number is immediately followed by a word character (alnum + underscore), the first digit of the number disappears.

This is, of course, not valid Fortran.  But when using something like RocketChat that auto-detects languages in code blocks, if Fortran is misidentified on some text (containing, for example, a product activation code along the lines of `temp-123abc`), the `1` just disappears. :)

It looks like 8951692cb8eaae388fb2ed7da026f15e485ac1ed may have introduced the assumption that a number is followed by either a word boundary or period.  I'm guessing that's related.

**Comment by yyyc514** [comment]
> the first digit of the number disappears.

The highlighting isn't correct (there is already an issue for this) but the numbers should NOT disappear anymore.  This was resolved a few versions ago.

Please show us a jsfiddle with a reproducible example of this happening on the latest Highlight.js version.  You can fork my template if that helps:

https://jsfiddle.net/ajoshguy/qhpL58ec/

I'm assuming (at this point) that your'e merely using an older version.

**Comment by dannysauer** [comment]
Yeah, definitely an older version shipped as a bundle.  None of my test cases which failed on the old version seem to be reproducible there.

Thanks!  Closing this issue. :)

**Comment by yyyc514** [comment]
Glad to help!
