### ISSUE TITLE
Consider: Fix "plain" and "text" to come in line with "plaintext" 

### ISSUE THREAD

**Issue by yyyc514** [highlightjs/highlight.js#2363]
Currently the `noHighlightRe` regex is:

```
  var noHighlightRe    = /^(no-?highlight|plain|text)$/i,
```

This means "plain" or "text" will result in skipping a block COMPLETELY, not applying ANY styling, not even the default "hljs" (codeblock) fg/bg styling.  We now also have "plaintext"... which applies no code-level styling BUT will still result in a HLJS styled code block.  IE, it's highlighted, but as "plaintext" vs not being highlighted at all.

To make this clearer I'd like to change the regex to match only "no highlight" or "no-highlight".  `plain` will simply disappear and `text` could move to become an alias for `plaintext`.

Since this could be (in some ways) considered a breaking change I'd like to include it in version 10 and also make the regex configurable... that way anyone desiring the "old" behavior could achieve it by modifying the regex - and since that's evaluated first, boom they get the old behavior.

I think this would simplify things and remove some ambiguity.  I've wanted to do this for a while but this issue prompted me to post: https://github.com/highlightjs/highlight.js/pull/2360

@egor-rogov Thoughts?

**Comment by egor-rogov** [comment]
I agree that this matter is very confusing. V10 looks like a right moment to change things, so I'm OK with it.
Maybe `plain` should also become an alias for `plaintext`, to be more consistent in a way.

**Comment by yyyc514** [comment]
If you INSIST I wouldn't argue, but to me "plain" doesn't really have a lot of meaning on it's own separate from "text"... so I'd wait and see if it proves to be necessary rather than add it preemptively.

**Comment by egor-rogov** [comment]
I have no strong opinion on that. Let it be `plaintext` and `text` then.
