### ISSUE TITLE
I used hightlight.js with Vue.js , but i allways got unformated value

### ISSUE THREAD

**Issue by Wiidz** [highlightjs/highlight.js#2364]
Here's my code. If I did smt wrong ?

```html
<pre>
  <code v-html="formatedCode"></code>
</pre>
```

```js
//js
import hljs from 'highlight.js';
import 'highlight.js/scss/default.scss'
...
mounted () {
  var code="<body><html><h1>Hello</h1><h2>World</h2></html></body>"
  hljs.configure({
        useBR: true
  })
  this.formatedCode = hljs.highlight('xml', code).value
  //console.log(code)
  // <span class="hljs-function"><span class="hljs-keyword">function</span> <span class="hljs-title">test</span>(<span class="hljs-params"></span>)</span>{<span class="hljs-built_in">console</span>.log(<span class="hljs-number">111</span>)}

  //this.formatedCode = hljs.fixMarkup(this.formatedCode)
  hljs.initHighlighting()
}
```
When i console.log this ,Here's no any 'br' !

**Comment by egor-rogov** [comment]
`useBR` option is for highlighting code in non-PRE containers. It has no effect at all for `highlight` function.
What problem are you trying to solve?

**Comment by Wiidz** [comment]
> `useBR` option is for highlighting code in non-PRE containers. It has no effect at all for `highlight` function.
> What problem are you trying to solve?

First, tks for your answering .
I saw these in the usage document :

**Comment by Wiidz** [comment]
> `useBR` option is for highlighting code in non-PRE containers. It has no effect at all for `highlight` function.
> What problem are you trying to solve?

First, tks for your answering .
I mean that can't hightlight.js format my code ?

for example, I put these in
```html
<html><body><h1>Hello</h1><h2>World</h2></body></html>
```
And I need this out:
```
<html>
    <body>
        <h1>Hello</h1>
       <h2>World</h2>
    </body>
</html>
```

**Comment by yyyc514** [comment]
Highlight.js merely highlights, it is not a source source beautification tool.   It will not add spacing or proper indentation to your code.

**Comment by Wiidz** [comment]
> Highlight.js merely highlights, it is not a source source beautification tool. It will not add spacing or proper indentation to your code.

Ohhhh, I see.
I misunderstood the word "format" .

**Comment by yyyc514** [comment]
If there is something in the docs or readme that is confusing wording please point us to it and we'd be happy to take a look.
