### ISSUE TITLE
Patch: Support hexadeciaml, octal, binary numbers in Delphi language

### ISSUE THREAD

**Issue by bttrx** [highlightjs/highlight.js#2368]
Hi!

I hope, syntax is fine, as I couldn't test it. (I hacked my delphi.min.js directly.)

````
--- delphi-original.js	Mon Jan 20 05:56:52 2020
+++ delphi.js	Sun Jan 26 20:56:09 2020
@@ -63,10 +63,31 @@ function(hljs) {
     keywords: KEYWORDS,
     illegal: /"|\$[G-Zg-z]|\/\*|<\/|\|/,
     contains: [
       STRING, CHAR_STRING,
       hljs.NUMBER_MODE,
+      {
+        // https://www.freepascal.org/docs-html/ref/refse6.html
+        className: 'numbers',
+        variants: [
+          {
+            // hexadecimal notation, e.g., $7F
+            begin: '\\$[0-9A-Fa-f]+',
+            relevance: 0
+          },
+          {
+            // octal notation, e.g., &42
+            begin: '\\&[0-7]+',
+            relevance: 0
+          },
+          {
+            // binary notation, e.g., %1010
+            begin: '\\%[01]+',
+            relevance: 0
+          }
+        ]
+      },
       CLASS,
       FUNCTION,
       DIRECTIVE
     ].concat(COMMENT_MODES)
   }; 
````

Cheers,
Robert

**Comment by yyyc514** [comment]
Are the `\\` necessary?  What are you escaping or ?  className should be `number` not `numbers`.

Otherwise, this looks reasonable if you wanted to turn it into an actual pull request.

**Comment by yyyc514** [comment]
If you'd like to submit a PR I'd be happy to work with you on getting this added but we really can't work with just patches submitted via issues.  Could you work on this a bit more and submit an actual PR?

**Comment by bttrx** [comment]
I will look into `\\`, but as long as these don't harm anything ... Better more than too less escaping.
Why can't you work with just patches? I would like to understand.
I'm still new to GitHub and pull requests. And I'm still on Windows XP x86. So I can't use GitHub Deskop. I have installed Git 2.10.0 and TortoiseGit 1.8.16.0 and was able to clone your repository.
What's next? Where do I enter my GitHub credentials?

**Comment by yyyc514** [comment]
> I will look into \\, but as long as these don't harm anything ... Better more than too less escaping.

No better just the right amount, if they aren't needed they will only confuse someone else in the future.

> Why can't you work with just patches? I would like to understand.

Lack of developer time. Plus many changes often go back and forth many times to make changes, fixes, automatically run CI tests, etc... there is a whole process in place that works well - the PR process.  If you can't do it that just means someone else has to do it... **everything ultimately goes thru the PR process one way or another**, and that does take some time and patients sometimes.

You'd need to fork the repo, clone that, make your changes, commit them... then make a pull-request of that branch (or even master).  You might try Googling something like "making your first pull request github"... there are lots of videos/tutorials.
