### ISSUE TITLE
(coffeescript) Freezing, poorly behaved regex to match regex.

### ISSUE THREAD

**Issue by xforce** [highlightjs/highlight.js#2375]
Tested in NodeJS 13 and Chrome 79 as well as v8 master.

Input text is around 5k.

In the attached file is a reproduction of a complete freeze when trying to highlight with coffeescript, this also affects auto language detection.
(Complete freeze in this case means, I killed the process after 10 minutes)

From debugging this a bit, it hangs in the exec of the coffeescript regex 
`var match = matcherRe.exec(s);`

I feel like it shouldn't hang and since this hang happens in v8 native code, I am not entirely sure this 
is actually an issue with highlightjs, so feel free to close this if appropriate.

Is it expected behavior for a browser to hang in such a case or abort after some amount of time? I am not entirely sure, would appreciate some info on this.

I was thinking about filing a but report on the v8 bug tracker but decided to hold off until I get some feedback here first.

[test.txt](https://github.com/highlightjs/highlight.js/files/4140031/test.txt)

**Comment by yyyc514** [comment]
Is this an actual real-life test case or is this from an attack or?  More context, please?

**Comment by yyyc514** [comment]
An attachment of just the code itself might also be helpful.

**Comment by yyyc514** [comment]
> Is it expected behavior for a browser to hang in such a case or abort after some amount of time? I am not entirely sure, would appreciate some info on this.

I'd say this is either a bug in Highlight.js or a poorly behaved regex combined with worst-case sample data.

**Comment by xforce** [comment]
Yes this was a real life case, we have chat application where we use highlight.js for syntax highlighting of code blocks in chat messages and someone pasted the output of some software snapshot creation, which is just a rather long base64 string.

The test.txt attach in the report contains nodejs code that when run will hang.

**Comment by yyyc514** [comment]
The more complex regex match is at fault:

```js
{
          // regex can't start with space to parse x / 2 / 3 as two divisions
          // regex can't start with *, and it supports an "illegal" in the main mode
          begin: /\/(?![ *])(\\\/|.)*?\/[gim]*(?=\W)/
        }
```

**Comment by yyyc514** [comment]
@xforce It should complete if you give it long enough, though it's hard to say how long that might be. :-)  I shortened it significantly and it only takes a second or two here in my testing.

I think this is comparable without the problem:

```js
/\/(?![ *]).*?(?![\\]).\/[gim]*(?=\W)/
```

@egor-rogov Thoughts?

**Comment by yyyc514** [comment]
Creating a new "hotfix" category and tagging accordingly.  Since this is a freeze/lockup issue I plan to back-port this to the current release series also (9.18).

**Comment by yyyc514** [comment]
@xforce If you're in a hurry you could hotfix your code with the PR I link to here... I'm waiting for @egor-rogov to review it.

It looks like this is a 6+ year old bug though, so can't just go back to a prior version or something.

**Comment by xforce** [comment]
@yyyc514 Thanks for the quick fix, I will be applying the PR later today and see how it goes.

**Comment by yyyc514** [comment]
**9.18.1 and 9-18-stable branch now includes this fix.**
