### ISSUE TITLE
(javascript) set as a variable name can conflict with set as keyword

### ISSUE THREAD

**Issue by deunlee** [highlightjs/highlight.js#2383]
From https://github.com/microsoft/vscode/issues/89760

When I use `set` word, the following codes don't seem to be highlighted properly.

Please test the code below.

+ Error : 
```js
const set = new Set([1, 2]);
for (const e of set)
console.log(e);
```

+ OK :
```js
const set1 = new Set([1, 2]);
for (const e of set1)
console.log(e);
```

**Comment by yyyc514** [comment]
This is really the same issue as: https://github.com/highlightjs/highlight.js/issues/1843

The problem is we don't have a great way to handle keywords that are also used as identifiers.  `set` is a keyword since ES2015 or so, so that's messing things up because we detect it as a keyword.

**Comment by yyyc514** [comment]
```
{
        beginKeywords: 'constructor get set', end: /\{/, excludeEnd: true
      }
```

I'm not sure why we couldn't just make them NORMAL keywords though... that would still miscolor it, but it wouldn't completely break the highlighting.

@egor-rogov Do you see a disadvantage to making these normal keywords?

**Comment by yyyc514** [comment]
Actually we could probably improve the get/set rules... they are pretty trivial to match (from MDN):

```
{get prop() { ... } }
{get [expression]() { ... } }
```

**Comment by egor-rogov** [comment]
+1 to improve get/set rules, unless it's too complicated (looks like it's not).

**Comment by yyyc514** [comment]
Well I don't know for sure about `[expression]` but we could just solve a few simples cases and then revisit it in the future if that fails to solve things.
