### ISSUE TITLE
npm does not have dist/highlight.pack.js or dist/highlight.min.js

### ISSUE THREAD

**Issue by jeremykentbgross** [highlightjs/highlight.js#2390]
According to the npm page, one should link to

```
<script src="/path/to/highlight.pack.js"></script>
```
while older (non npm) versions provided a highlight.min.js.  Neither of these exist in the npm installation.

At present, there is no compressed version for deployment to clients in npm.

For comparison I would point you to the 'ajv' or 'handlebars' packages, which both provide a '/dist' folder in the npm installation that can be served directly to clients, for minimized as well as optionally the normal (uncompressed) version.

**Comment by yyyc514** [comment]
Closing as duplication of #1250 or #678.

You can find the distributable files at https://github.com/highlightjs/cdn-release

We also plan to turn the assets into their own npm package in the near future.

**Comment by yyyc514** [comment]
If you want to drop your specific use case into either of those issues that might be helpful long-term.
