### ISSUE TITLE
4D Language

### ISSUE THREAD

**Issue by gkotulski** [highlightjs/highlight.js#2392]
Hello,
I have created a new repository for the 4d language for your new pipeline:
https://github.com/gkotulski/highlightjs-4d

Here are some examples of the 4D:
https://doc.4d.com/4Dv18/index.en.html

Is it possible for the organization highlightjs to host the repository as a 3rd party language?

**Comment by yyyc514** [comment]
Are you wanting us to be the canonical copy then?  If I create the repo can you get the source transferred over?

**Comment by gkotulski** [comment]
If you create a new repository, I can transfer the files.

**Comment by yyyc514** [comment]
Done.

https://github.com/highlightjs/highlightjs-4d-lang

Also please make a PR adding it to our README here in the main repo.

**Comment by yyyc514** [comment]
Renaming it to be consistent.
