### ISSUE TITLE
(python) Wrong highlight with inline comment.

### ISSUE THREAD

**Issue by marcosboggia** [highlightjs/highlight.js#2399]
Apparently, when an inline comment ( eg: `# this is a comment for better explanation` ) with a keyword, it gets highlighted in a wrong way.
![Screenshot from 2020-02-07 15-24-08](https://user-images.githubusercontent.com/18308502/74055239-61b3ab00-49be-11ea-9771-84f65fd45091.png)
In the image we can see the first inline comment, it contains the keyword `for` and it gets wrong highlight.
Then going down we can see a correct highlighted inline comment with no keywords.

**Comment by yyyc514** [comment]
Please include actual code that can be copy/pasted not just a screen capture.

**Comment by marcosboggia** [comment]
Yep, you are right. Sorry my mistake I over trusted the autodetect language hehe.
I specified python class in code tag and worked. Thank you very much for that fast response!
