### ISSUE TITLE
Proposal: JIT loading of Javascript grammars via CDN

### ISSUE THREAD

**Issue by joshgoebel** [highlightjs/highlight.js#2405]
The idea is to be able to have the largest assortment of languages on tap without greatly increasing the size of the core download - and without manually having to adding individual `script` tags to load via CDN.  This is great for use cases like one-off languages or blogs where every once in a while you pull in another language but most of the time you only use the core set.

I suggest we accomplish this with a configuration key for `AllowedCDNAddress` or something where you set the CDN prefix such as:

```js
configure({
  allowedCDNAddress: "https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.18.1/languages/"
})
```

Then whenever anyone specified an explicit language (ie, `lang-fortran77`) we'd probe the CDN and if the `.../languages/fortran77.min.js` file is available we'd fetch/load it - and after it loaded successfully we'd then queue the highlight to happen.  If the JS file can't be fetched, the highlight would fail and only the `hljs` style would be applied.

It might also be useful to allow the user to specify the list of approved languages to load:

```js
configure({
  allowedCDNAddress: "https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.18.1/languages/",
  allowedCDNLanguages: ["fortran77", "fortran90"]
})
```

This would have the side benefit of increasing security (although you shouldn't be using the CDN if you don't trust it anyways) and also then allowing the simpler `fortran77` class naming vs `lang-fortran77` - since we have a list on hand to check each class name against and see if it potentially MIGHT be a valid language.

I think this would be a pretty simple add actually and a fun little project if anyone wanted to tackle it.  Rough idea:

1. When `highlightBlock` is called, see if the language is available (or potentially available) and not loaded
2. Load/fetch it... (and here we're assuming it's one of our standard auto-registering CDN modules)
3. Add the block to a queue for the given language of "pending" highlights.
4. When `registerLanguage` is called, check the queue for the just registered language to see if any blocks are waiting.
.5 If there are any items in the queue, now `highlightBlock` can be called again and this time it will immediately work since the language is now loaded.

**Comment by taufik-nurrohman** [comment]
I think the current hook system is able to do  this task without having to touch the core library. I&rsquo;m thinking like this would be achieve-able:

~~~ .js
hljs.addPlugin({
    'before:highlightBlock': ({block, language}) => {
        if (!languageExistsFunc(language)) {
            let script = createScriptFunc(cdnPath + '/' + language + '.js');
            document.head.appendChild(script);
            script.addEventListener('load', () => {
                hljs.reinitialize();
            });
        }
    }
});

hljs.reinitialize = () => {
    codeElements.forEach(codeElement => {
        if (!codeElement.classList.contains('hljs')) {
            hljs.highlightBlockButDoNotFireTheHook(codeElement);
        }
    });
};
~~~

**Comment by taufik-nurrohman** [comment]
Inside the `cdnPath + '/' + language + '.js'` file, we have this:

~~~ .js
hljs.registerLanguage('foo-bar', self => { ... });
~~~

**Comment by yyyc514** [comment]
I like the thinking here, and we should continue this discussion.

>    hljs.initHighlightingButSkipAlreadyHighlighted();

Adding new API means this can't be done "with purely the hook/plugin system".  Is there a reason the plugin can't just call `highlightBlock` again recursively?  Once the language is loaded the behavior would be as expected.

The problem is right now I'm not sure we have a "do nothing" return value so that a plugin could essentially prevent highlighting and schedule it for later.

There is also the fact that `blockLanguage` is run BEFORE the before block highlight call... so I'd have to review that code to make sure it wouldn't break in light of an "unknown" language.

If you wanted to whip up a WORKING version of this and see what the real and imaginary issues are it'd be worth having a look at I think.

**Comment by yyyc514** [comment]
> Inside the cdnPath + '/' + language + '.js' file, we have this:

Yes, the existing CDN files should work "as is" for this type of system AFAIK.

**Comment by taufik-nurrohman** [comment]
>  Is there a reason the plugin can&rsquo;t just call `highlightBlock` again recursively.

Yes, but looks like current implementation doesn&rsquo;t care whether a code block is already highlighted or not.

> The problem is right now I&rsquo;m not sure we have a &ldquo;do nothing&rdquo; return value so that a plugin could essentially prevent highlighting and schedule it for later (or do it recursively).

So, need an extra check whether a block already has a `hljs` class or not here:

``` .js
hljs.initHighlightingButSkipAlreadyHighlighted = () => {
    document.querySelectorAll('pre code:not(.hljs)').forEach(hljs.highlightBlock);
};
```

**Comment by taufik-nurrohman** [comment]
> If you wanted to whip up a WORKING version of this and see what the real and imaginary issues are it&rsquo;d be worth having a look at I think.

let&rsquo;s see :wink:

**Comment by yyyc514** [comment]
> Yes, but looks like current implementation doesn’t care whether a code block is already highlighted or not.

So? That shouldn't matter... the default implementation only calls highlightBlock once for all blocks... if the plugin behavior is correct it should "just work".  It should just hook the load event... and then "do nothing"... then the load event fires, blockHighlight is called again and runs to competition.

> So, need an extra check whether a block already has a hljs class or not here:

This shouldn't be necessary. But I wonder if it's not an unreasonable idea. :-)

**Comment by taufik-nurrohman** [comment]
> So it can avoid trying to load more than once.

This should detect if language already registered. Once registered, no need to load the language file:

``` .js
if (!hljs.getLanguage(language)) { ... }
```

> But I wonder if it&rsquo;s not an unreasonable idea.

Because `scriptElement.addEventListener('load', () => { ... })` need a time, so we need a way to refresh the highlight task on every script-load event. Unless we have something like `async`, `await` system so that `initHighlighting()` can be executed after ALL language files has been loaded.

**Comment by yyyc514** [comment]
Still feel like you are WAY over thinking this problem:

```rb
# pseudocode
before("highlightBlock", [block, lang, etc] ) do
  return if languageLoaded(lang) # do normal thing
   
  loadLanguageFromURL(urlFor(lang)).then do 
    hljs.highlightBlock(block) # this will not work since language is loaded
  end  
end
```

Nothing regarding onload needs to change.  The plugin just needs to handle calling highlight block  itself once it's knows the language is loaded.

**Comment by taufik-nurrohman** [comment]
Ah, now I see that `before:highlightBlock` hook runs on every block, so no need to iterate over again :laughing:

``` .js
hljs.addPlugin({
    'before:highlightBlock': ({block, language}) => {
        if (!hljs.getLanguage(language)) {
            let scriptElement = createScriptFunc(cdnPath + '/' + language + '.js');
            document.head.appendChild(scriptElement);
            scriptElement.addEventListener('load', () => {
                hljs.highlightBlock(block);
            });
        } else {
            // Let `hljs.initHighlighting()` or `hljs.initHighlightingOnLoad()` do the job!
        }
    }
});
```

I&rsquo;ll try to make this plugin, maybe tomorrow.

**PS:** Making a line-numbers plugin shouldn&rsquo;t be difficult.

**Comment by taufik-nurrohman** [comment]
Done! :grin:

https://github.com/taufik-nurrohman/highlight.jit.js

FYI, `language` property returns `undefined` if no language is registered. So, in my plugin, I need to loop through the class name to temporarily treat them as a language name.

https://github.com/taufik-nurrohman/highlight.jit.js/blob/1ff338a22221967e7d168f6558b433d53608b347/highlight.jit.js#L21&L22

**Comment by yyyc514** [comment]
Pretty nice.

```
    hljs.currentLanguagePath = currentLanguagePath;
    hljs.currentStyle = currentStyle;
    hljs.currentStylePath = currentStylePath;
```

This makes me wonder if we should open up options somehow (to read), but you got by just fine without it...

**Comment by yyyc514** [comment]
> So, in my plugin, I need to loop through the class name to temporarily treat them as a language name.

Kind of the same way we go about it... Really you should **REQUIRE** `lang-` or `language-` prefix so that you aren't just loading random JS files based on EVERY class.  I could imagine some HTML with a crazy number of classes for some reason.  Making one web request for each class is a little crazy.

**Comment by yyyc514** [comment]
Just curious what is the point of the CSS loader?

**Comment by yyyc514** [comment]
Now we need to figure out how to link to 3rd party plugins like we link to 3rd party languages.

**Comment by taufik-nurrohman** [comment]
> This makes me wonder if we should open up options somehow (to read).

Related: https://github.com/highlightjs/highlight.js/issues/1969

> Really you should **REQUIRE** `lang-` or _language-_ prefix so that you aren&rsquo;t just loading random JS files based on EVERY class.

Already added to my TODO list.

> Just curious what is the point of the CSS loader?

Ahahahha, you don&rsquo;t like it? I should remove it then :laughing:

> Now we need to figure out how to link to 3rd party plugins like we link to 3rd party languages.

Isn&rsquo;t stacking the plugin files next to the core _HighlightJS_ file enough for us?

**Comment by taufik-nurrohman** [comment]
@yyyc514 Unfortunately, this line causes the `before:highlightBlock` to be discarded because the `language` variable returns `no-highlight`:

Here, `blockLanguage()` returns `no-highlight`:

https://github.com/highlightjs/highlight.js/blob/63f367c46f2eeb6f9b7a3545e325eeeb917f9942/src/highlight.js#L86

And so this:

https://github.com/highlightjs/highlight.js/blob/63f367c46f2eeb6f9b7a3545e325eeeb917f9942/src/highlight.js#L655

Which caused this condition to be `true`:

https://github.com/highlightjs/highlight.js/blob/63f367c46f2eeb6f9b7a3545e325eeeb917f9942/src/highlight.js#L657

---

Without `language-` prefix, result will be `undefined`, which is okay. Since no `language-` prefix was set, the `shouldNotHighlight(_class)` part will never be called (PS: this part should be safe to be removed):

https://github.com/highlightjs/highlight.js/blob/63f367c46f2eeb6f9b7a3545e325eeeb917f9942/src/highlight.js#L89-L91

---

**Bug:** https://taufik-nurrohman.js.org/highlight.jit.js/test/priority.html

**Comment by taufik-nurrohman** [comment]
@yyyc514 Is calling `highlightBlock()` within `before:highlightBlock` or `after:highlightBlock` will make that hook fired recursively?

I don&rsquo;t see that happen but based on the current `highlightBlock()` function, it should be.

**Comment by yyyc514** [comment]
> Ahahahha, you don’t like it? I should remove it then

Dude, your plugin. :-)  I was just asking what the purpose was?

> Isn’t stacking the plugin files next to the core HighlightJS file enough for us?

Stacking?

**Comment by taufik-nurrohman** [comment]
> Stacking?

~~~ .js
<script src="highlight.js"></script>
<script src="highlight.jit.js"></script>
<script src="highlight.ln.js"></script>
<script src="..."></script>
~~~

**Comment by yyyc514** [comment]
I meant we need to read me index for plug-ins so that users of the library know where they can find third-party plug-ins.

**Comment by joshgoebel** [comment]
> @yyyc514 Is calling highlightBlock() within before:highlightBlock or after:highlightBlock will make that hook fired recursively?

I think I missed this before?  Yes, you'd have to guard against that.  You may not be seeing an issue because the second time you are called the JS is already loaded?  But if someone called you too quickly then you might get "stuck".

I'm really not sure `highlightBlock` is intended to be hooked this way as it has no good way to say "pause and resume later"...  So right now using it this way is going to be pretty hacky.

**Comment by joshgoebel** [comment]
And I'd think the first highlight call would blow up with an error because the language wasn't found?

**Comment by joshgoebel** [comment]
Makes me wonder if we should perhaps expose "shouldNotHighlight" as a plugin callback... so a plugin would have a way of "rejecting" language and this could be used to build auto-load functionality... reject the first time (if language is missing), download it, when download complete, call highlightBlock again.

**Comment by taufik-nurrohman** [comment]
> And I'd think the first highlight call would blow up with an error because the language wasn't found?

[Yes.](https://github.com/highlightjs/highlight.js/issues/2405#issuecomment-639169230)

**Comment by joshgoebel** [comment]
I'm going to close this issue.  This was kind of my pet desire because I could use it in a project I was working on... but upon further reflection I'm not sure this belongs in core.  It's easy enough to do with a small wrapper (as you've shown).

**Comment by jimmywarting** [comment]
if there would have been any code splitting involved using async `import()` then we wouldn't have to specify a cdn library
the cdn would just import things relative to the cdn you are using...

**Comment by joshgoebel** [comment]
I still think some people might potentially want the files in other places... but you're saying you could simply have a CDN_LOCATION default value like `"./grammars` or some such and it would be local to the URL you fetched the library from?  That makes sense.
