### ISSUE TITLE
(armasm) Line comments do not seem to be handled correctly

### ISSUE THREAD

**Issue by TheYadda** [highlightjs/highlight.js#2408]
I was referred to make this bug report by Discord support after seeing this behavior in Discord, which uses highlight.js.

When highlighting ARM assembly, `# comments` and `// comments` are not treated as comments but instead as live code. This leads to incorrect highlighting that can span the entirety of the code, see the included screenshot.

[Example (from Discord)](https://i.imgur.com/o2DKPtC.png)

**Comment by yyyc514** [comment]
Please include raw Sample text here not just an image.

**Comment by TheYadda** [comment]
```
  //=================== YOUR CODE GOES IN THE SECTION BELOW ===================//

    # check for and handle zero
    orr r1, r0, #128            // r1 = r0 | 128
    cmp r1, #128                // if r1 == 128 {
    bne notZero                 // .
    bl zeroQuidFP2float         //          zeroQuidFP2float() }
    b end                       // else {

notZero:                        // .
    # extract fields from quidfp
    and r1, r0, #128            //          r1 = r0 & 128     // sign
    and r2, r0, #112            //          r2 = r0 & 112     // exponent
    and r3, r0, #15             //          r3 = r0 & 15      // mantissa

    # adjust for larger bias (add 32-bit bias - 8-bit bias << 4)
    add r2, r2, #1984           //          r2 = r2 + 1984

    # move fields into appropriate location for IEEE-754 single-precision fp
    lsl r1, r1, #24             //          r1 = r1 << 24
    lsl r2, r2, #19             //          r2 = r2 << 19
    lsl r3, r3, #19             //          r3 = r3 << 19

    # combine into r0
    orr r0, r1, r2              //          r0 = r1 | r2
    orr r0, r0, r3              //          r0 = r0 | r3 }

end:                            //  return r0

  //===========================================================================//
```

[Correctly highlighted by the ARM VSCode extension](https://i.imgur.com/BWItYwq.png) by @dan-c-underwood

[Incorrectly highlighted by highlight.js in Discord](https://i.imgur.com/LSA5fyN.png)

**Comment by yyyc514** [comment]
And how are # comments to be distinguished from numbers (`#24`) and label references (`{begin: '[=#]\\w+' }  //label reference`)?

**Comment by TheYadda** [comment]
Playing with the VSCode extension, # is only counted as the start of a comment if it's the first non-whitespace character on a line.
