### ISSUE TITLE
Pull request #2410 issue

### ISSUE THREAD

**Issue by TheYadda** [highlightjs/highlight.js#2411]
Hello!

So uh, I just made a bug report, #2408, which was fixed in #2410, and you just fixed it, and I see you, um... Just threw my entire sample code in as a test case.

One problem, that sample code was actually an assignment I just turned in for university. You probably want to come up with a novel test case, um, for two reasons.

A: this is an assignment that will likely be used in future quarters, and it'd probably not be good to have solution code for that floating around

B: there are some licensing questions as to whether anything made using UCSD resources is property of UCSD or not, and incorporating code I wrote for an assignment into your testing code sounds like a bad idea

**Comment by egor-rogov** [comment]
Hi @TheYadda,
probably you can come up with some other (short) example we can use as a test case?

**Comment by TheYadda** [comment]
I don't even know if this would execute as I expect it to because it's just something I came up with on the spot, but it demonstrates the issue.

[highlight.js version](https://i.imgur.com/nhGB5xh.png)
[VSCode version](https://i.imgur.com/jkZhspJ.png)

```
# logical operator demo (highlight.js arm comment test)
mov r0, #0x00F0     // r0 = 0x00F0
mov r1, #0x000F     // r1 = 0x000F
mov r2, #0xFF00     // r2 = 0xFF00
orr r3, r0, r1      // r3 = r0 | r1     // r3 = 0x00FF
and r4, r3, r2      // r4 = r3 & r2     // r4 = 0x0000
orr r5, r3, r2      // r4 = r3 | r2     // r5 = 0xFFFF
eor r6, r5, r2      // r6 = r5 ^ r2     // r6 = 0x00FF
```

**Comment by yyyc514** [comment]
> and I see you, um... Just threw my entire sample code in as a test case.

Actually I didn't, I included only a portion (snipping out the middle)... and to me the amount of code was so small as to not be an issue.  To me it looked like a small portion of something much larger, and hence a valid test case.

> and it'd probably not be good to have solution code for that floating around

Since it's not really labeled I'm not sure how someone would find it...

---

But since you raised this issue I guess it's really bothering you so we'll see if we can't swap it out with something else.
