### ISSUE TITLE
Dependency not found: 'highlight.js/lib/core'

### ISSUE THREAD

**Issue by harrisoff** [highlightjs/highlight.js#2418]
version 9.18.1
```js
import hljs from 'highlight.js/lib/core';
```
Throws error "This dependency was not found". There is no such file in node_modules:
![impicture_20200221_133706](https://user-images.githubusercontent.com/29137942/75007284-98ee8580-54af-11ea-9f59-589173387f72.png)

**Comment by yyyc514** [comment]
Lib/highlight.   Core is for 10.0.

**Comment by yyyc514** [comment]
See https://github.com/highlightjs/highlight.js/tree/9-18-stable README.
