### ISSUE TITLE
(clojure) does not highlight defn- properly

### ISSUE THREAD

**Issue by yyyc514** [highlightjs/highlight.js#2420]
Clojure does not highlight `defn-` as a keyword. The `-` is highlighted as part of the title instead.

You can find an example in markup `global_definition.txt`:

```
; private function
(defn- add [x y] (+ x y))
```

This might actually require a parser fix since the problem is word boundaries (which is how the parser handles beginKeywords) are funny in how they work with `-`.  So there is not actually a word boundary AFTER the `-` which is where you'd need it to work properly.

**Comment by yyyc514** [comment]
I propose a look-ahead that finds a word boundary OR a space.

```
mode.begin = '\\b(' + mode.beginKeywords.split(' ').join('|') + ')(?=\\b|\\s)';
```

This would work for identifiers that include "non-word" characters and hence don't end up word boundaries but rather on the boundary between the last character and whitespace... This does nothing to fix keywords that BEGIN with strange characters (we'd need look-behind) but I think that's a less common occurrence, so I'm not super worried about it until we have a real life example.

Thoughts? CC @egor-rogov

**Comment by egor-rogov** [comment]
It works fine it seems.

**Comment by yyyc514** [comment]
You mean you agree that my idea would work?

**Comment by egor-rogov** [comment]
Yes, I even tried it and it really works.

**Comment by yyyc514** [comment]
Oh, I tried it before I proposed it, lol... I was floating it just to see if there was anything I wasn't considering that someone else might think of - ie a good reason not to fix it that way.

**Comment by egor-rogov** [comment]
The best way to think of something is to try it... I can't see any objection.
