### ISSUE TITLE
(twig) common keywords not highlighted (and, or, same as, etc)

### ISSUE THREAD

**Issue by do-web** [highlightjs/highlight.js#2422]
"and", "or", "is empty", "same as","in" etc. not highlighting.

**Comment by yyyc514** [comment]
None of those are listed as keywords in our syntax.  Is there somewhere we could find a complete list of keywords?

**Comment by yyyc514** [comment]
Should we care that Twig's own documentation doesn't highlight some of these things?  

https://twig.symfony.com/doc/3.x/

Although we already highlight much more than the twig docs (they don't highlight functions, etc).

**Comment by do-web** [comment]
This are the operators. So highlight the operators like Prims do.

**Comment by yyyc514** [comment]
It looks like we would need to add `TESTS` and `OPERATORS` (only the word-based ones)... this could be done either with `keywords` or new modes.  I'd first prefer to see if keywords could be made to work.

Also wouldn't hurt to review the other lists, as I think they are outdated.

**Comment by yyyc514** [comment]
@do-web Any chance you're willing to work on a PR?

**Comment by florianjr** [comment]
If it's only updating the lists (tags, functions) and adding the suggested words, I'd do this.

**Comment by yyyc514** [comment]
That'd be a start I think.

**Comment by joshgoebel** [comment]
@florianjr Ping. :-)

**Comment by florianjr** [comment]
Thanks for the Ping :) I'm sorry, I totally forgot. I finished my work and opened a PR @joshgoebel

**Comment by joshgoebel** [comment]
> Should we care that Twig's own documentation doesn't highlight some of these things?

Since Twig's own docs don't highlight these and no one is prepared to push a PR all the way to competition I'm going to mark this issue as closed for now.
