### ISSUE TITLE
Greeting for the first-time contributors doesn't work

### ISSUE THREAD

**Issue by egor-rogov** [highlightjs/highlight.js#2446]
@yyyc514, see recent https://github.com/highlightjs/highlight.js/runs/480215481?check_suite_focus=true

~~Looks like GitHub tries to do something with the url mentioned in `pr-message` (https://github.com/highlightjs/highlight.js/labels/beginner%20friendly),~~ although I'm not sure what's going on there.

**Comment by yyyc514** [comment]
Yeah GitHub actions have been a big disappointment so far.

**Comment by yyyc514** [comment]
https://github.com/actions/first-interaction/issues/10

I've joined the thread to find out if this is just broken like labeler is... *sighs*

**Comment by yyyc514** [comment]
Remove this.
