### ISSUE TITLE
[GDScript]Sometimes highlight wrongly 

### ISSUE THREAD

**Issue by Merlin-Wilde** [highlightjs/highlight.js#2448]
Look like this ,highlight.js may highlight the comments and ignore the statements
![Snipaste_2020-03-04_18-10-46](https://user-images.githubusercontent.com/51823222/75868802-968f1280-5e43-11ea-8822-29bb3eb99dce.png)
![Snipaste_2020-03-04_18-10-59](https://user-images.githubusercontent.com/51823222/75868812-98f16c80-5e43-11ea-9531-c0653c1982e7.png)
![Snipaste_2020-03-04_18-11-13](https://user-images.githubusercontent.com/51823222/75868815-998a0300-5e43-11ea-92b5-32b70589b1db.png)

**Comment by yyyc514** [comment]
Please confirm you are manually specifying GDscript as the language and not using auto-detect.

**Comment by Merlin-Wilde** [comment]
> Please confirm you are manually specifying GDscript as the language and not using auto-detect. It looks like an auto-detect failure because of how many times you use "Call" and "function" in your comments... and if that's the case there isn't anything we can do about it - you'd need to manually specify that the language is GDscript rather than trying to let us guess.

yeah,I specify the language is GDScript

**Comment by yyyc514** [comment]
Please provide a JSFiddle the reproduces this problem outside your environment so we can see exactly what you're doing.

You can fork my example:
https://jsfiddle.net/ajoshguy/gfzujpyt/

> yeah,I specify the language is GDScript

Right now I'd say either you're mistaken or you're running into some weird issue with your environment, not Highlight.js.  That's very obviously not just confusing the comments but highlighting with an entirely different language, which is exactly what would happen if you were using highlightAuto.

**Comment by Merlin-Wilde** [comment]
&nbsp; &nbsp; This error happens in a software called vnote,a markdown editor.(https://github.com/tamlok/vnote)
&nbsp; &nbsp; The developer of vnote use highlight.js to highlight the code block in markdown files if users specify the language,otherwise,
Vnote won't try to highlight the code block.
&nbsp; &nbsp; The GDScript.md is the file I found highlight error,I delete other statements and save all code blocks,the two pictures is the highlight result on my computer.
&nbsp; &nbsp; The error may in vnote,I'll try to solve it with its developer.You can ignore it if it's not the wrong of highlight.js after you check it.


北溟
merlin_wilde@foxmail.com



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Josh Goebel"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月5日(星期四) 上午8:36
收件人:&nbsp;"highlightjs/highlight.js"<highlight.js@noreply.github.com&gt;;
抄送:&nbsp;"北溟"<Merlin_Wilde@foxmail.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [highlightjs/highlight.js] [GDScript]Sometimes highlight wrongly  (#2448)




Please provide a JSFiddle the reproduces this problem outside your environment so we can see exactly what you're doing.
 
You can fork my example:
https://jsfiddle.net/ajoshguy/gfzujpyt/
  
yeah,I specify the language is GDScript
  
Right now I'd say either you're mistaken or you're running into some weird issue with your environment, not Highlight.js.  That's very obviously not just confusing the comments but highlighting with an entirely different language, which is exactly what would happen if you were using highlightAuto.

**Comment by yyyc514** [comment]
That seems to be a third party language module.  If you're having a problem with it please report it to the modules author:

https://github.com/highlightjs/highlightjs-gdscript

**Comment by Merlin-Wilde** [comment]
Thanks.
