### ISSUE TITLE
([JavaScript]) Incorrect highlighting of code

### ISSUE THREAD

**Issue by Tejas2805** [highlightjs/highlight.js#2449]
**Describe the issue**
A clear and concise description of what the issue seems to be.

For some reason, its picking up code as regex and thats why coloring it differently.

**Which language seems to have the issue?**
Please specify exactly *which* language grammar you are using to highlight (`python`, `javascript`, etc.) or specify if you are using auto-detection.  If you are using auto-detection please first check to make sure the language you are expecting was properly detected.  If Highlight.js misidentifies the type of code - then the highlighting may be entirely incorrect - and there often isn't much we can do about that - auto-detection is only best-effort and can't guess right 100% of the time.

JavaScript

**Sample Code to Reproduce**
Please include text examples of the code that fails to highlight properly or can reproduce the bug.  You can attach a screenshot if you'd like, but the code is necessary because we may need to copy/paste it to help resolve the issue - or add it to a test.

![Screen Shot 2020-03-05 at 4 51 00 PM](https://user-images.githubusercontent.com/35946746/75964181-b84ecf00-5f01-11ea-8701-b799c7236654.png)

A jsfiddle can sometimes be even better.  You can fork an example test case:
https://jsfiddle.net/ajoshguy/gfzujpyt/

**Expected behavior**
A clear and concise description of what you expected to happen.  A screenshot might help here if another highlighting library gets it right, or is Github highlights it better/properly you can use a GitHub code block.

The font in green should be black too. 

**Additional context**

**Comment by yyyc514** [comment]
Java or JavaScript? Looks like Javascript code to me.

**Comment by Tejas2805** [comment]
Aah my bad. Sorry. Its Javascript.

**Comment by yyyc514** [comment]
Can you test this against `master`?  Pretty sure this is fixed in 10.0 already.

**Comment by Tejas2805** [comment]
How to test again master if I am using something like this?

`script(src="https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@9.18.1/build/highlight.min.js")`

**Comment by yyyc514** [comment]
You'd have to build it from source and test locally.  :-|

**Comment by Tejas2805** [comment]
Thanks for your help!

**Comment by yyyc514** [comment]
Closing as a dup of https://github.com/highlightjs/highlight.js/pull/2380

**Comment by yyyc514** [comment]
If you can test via NPM:

https://www.npmjs.com/package/highlight.js/v/10.0.0-beta.0
