### ISSUE TITLE
Is it possible to build a 3rd party (hosted in a distinct repo) language into the highlight.js build output?

### ISSUE THREAD

**Issue by DuncanmaMSFT** [highlightjs/highlight.js#2452]
Hey folks, this is a question not an issue, but I don't know how else to ask. On https://docs.microsoft.com we are using highlight.js as a single file reference (building the latest and deploying with our code), but now that some languages are distinct repos (like https://github.com/highlightjs/highlightjs-cshtml-razor) is there a way to still bundle that into a single file output like we were doing before with node tools/build.js -t browser ?

**Comment by yyyc514** [comment]
https://github.com/highlightjs/highlight.js/blob/master/extra/3RD_PARTY_QUICK_START.md

See that.  Basically check out the repos you want INSIDE the HLJS checkout, into the `extra` directory, then build as normal (you'll have to specify the languages unless you're building all) and it should all "just work".

**Comment by yyyc514** [comment]
```
./tools/build -t browser :common other_3rd_party_lang
```

Etc...
