### ISSUE TITLE
v10.0.0 Beta is available.

### ISSUE THREAD

**Issue by yyyc514** [highlightjs/highlight.js#2454]
## Needed: Help testing upgrading from v9 to v10 beta

We're now publishing betas to NPM.  If anyone would like to help test the beta, please help us do so.  Read the `VERSION_10*.md` documentation. There are breaking changes but for many people it should still largely be a drop-in upgrade.

For v10 and onward we're moving into the `highlightjs` npm organization to keep things grouped nicely (though HLJS keeps it's top-level URL):

https://www.npmjs.com/package/highlight.js
https://www.npmjs.com/package/@highlightjs/cdn-assets

In the future we many want to consider the labeling of pre-releases.  This release should be stable and production ready.  All tests are green.  We'd just like one last chance to see if their are an issues in the real world before we go wide.

**Comment by KingDarBoja** [comment]
This is my first time trying out the library by using [Teradata Covalent Text Editor](https://github.com/Teradata/covalent-text-editor-nightly) component and so far everything is working fine on a basic setup using Angular 9.

However, there are few issues with the library itself, as I had to dig into the options in order to provide some basic features.

**1.** The toolbar icons doesn't show if setting `toolbar: true`. Instead, I had to pass each icon name as **array of strings** instead of default ones.

The documentation stated:
> Below are the built-in toolbar icons (only some of which are enabled by default)

Maybe a bug?

**2.** Loading a style from the package does work **BUT** the background hasn't the correct css style.

The below image correspond to `atom-one-dark` css style being applied but notice the `code` tag has no html class.

![image](https://user-images.githubusercontent.com/30560560/76379946-7ec1fd80-631f-11ea-91e0-e0cd54af8d62.png)

If I add it to the `pre` tag, now the background css has the correct styling:

![image](https://user-images.githubusercontent.com/30560560/76380290-67374480-6320-11ea-9694-05d4656df5d5.png)

**Comment by yyyc514** [comment]
>  toolbar icons 

Sounds like your environment.  HLJS has no toolbar or toolbar icons.

>  BUT the background hasn't the correct css style.

Can you create a standalone simple HTML page that shows a reproducible problem or a jsfiddle... just HTML/CSS/library, not mixed with Angular or other libraries?

I just built the browser build quickly and pulled up the demo and all the styles seem to apply just fine... when HLJS first runs it should auto-add `hljs` to ever `pre code` that's not marked to be ignored.  Without further evidence I'd guess it's something in your environment.

**Comment by KingDarBoja** [comment]
@yyyc514 Ignore the first thing, I got confused with another library which makes use of HighlightJS (EasyMDE).

About the css style, I will provide a StackBlitz as requested as this could be related to Angular not properly applying the css style.

**Comment by yyyc514** [comment]
HTML takes control of the DOM itself (at least the `<pre><code>` pieces) so you might have to jump thru hoops to work with Vue, React, Angular... so that they don't just mess it up again.

**Comment by KingDarBoja** [comment]
Looks like there isn't any error after setting `hljs.debugMode()`, the only thing showing up is a marked warning.

```console
helpers.js:227 marked(): sanitize and sanitizer parameters are deprecated since version 0.7.0, should not be used and will be removed in the future. Read more here: https://marked.js.org/#/USING_ADVANCED.md#options
```

But once again, don't think it is related to highlight library.

What I find strange is that the css styling isn't being applied to `<pre><code>` pieces. I will try to find the root cause but besides that, everything seems to be fine!

**Comment by yyyc514** [comment]
Wouldn't surprise me if it working just fine is but Angular is changing it back when it does some other sort of dynamic update and redraws the content.  Not sure why the inner content would be immune though... but these rendering engines are complex and complicated beasts.

**Comment by KingDarBoja** [comment]
Being honest with you, I have no idea why it doesn't work on my [Example StackBlitz](https://stackblitz.com/edit/js-bvfxyk) 🙈 Not used to write JavaScript these days.

**Comment by yyyc514** [comment]
I have no idea.  Not familiar with that service and what it does.  Your HTML files is missing the key HTML tags, and has no script tags, etc... so hard to judge anything without seeing what is actually happening.  If the services makes it easy to see that, I didn't see anything...

And I never saw any output in console even if I added a manual log line, which is a bad sign.

**Comment by yyyc514** [comment]
I change this topic to make it more focused on "upgrading".

**Comment by KingDarBoja** [comment]
Sorry for the early code, I tested again and passed the generated HTML code and also printed out to the console.

![image](https://user-images.githubusercontent.com/30560560/76384864-1fb7b500-632e-11ea-980a-c7ac09b54acc.png)

I think this is what you were looking for.

**Comment by yyyc514** [comment]
It works if I add: 
```
var blocks = document.querySelectorAll('pre code');
blocks.forEach((b) => {
  console.log(b);
  hljs.highlightBlock(b);
})
```

Which is all the onload hook does... So I'd say Angular messes with the loading process and breaks things, so you'll have to do your own... which is also covered by the README.

**Comment by BoforsKing** [comment]
@yyyc514 Hey mate, I just wanted to let you know I solved the issue by following your suggestion, the library works like a charm within the others libraries that uses HighlightJS under the hood.

**Comment by KingDarBoja** [comment]
@yyyc514 Hey mate, I just wanted to let you know I solved the issue by following your suggestion, the library works like a charm within the others libraries that uses HighlightJS under the hood.

**Comment by yyyc514** [comment]
Great

**Comment by morgan3d** [comment]
With a clean checkout, I'm getting an error on rollup-plugin-commonjs when I build v10.0:

```
node tools/build.js -t browser :common
module.js:550
    throw err;
    ^

Error: Cannot find module 'rollup-plugin-commonjs'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (..../highlight.js/tools/build_config.js:1:81)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
```

I updated node and used npm to update all global packages, but that didn't help.

**Comment by morgan3d** [comment]
With a fresh clone, I get an error in which the fs module appears to be undefined (it is installed on my machine):

```node tools/build.js -t browser :common
Starting build.
Finished build.
Writing docs files.
Writing demo files.
Writing style files.
Preparing languages.
......................................
Building highlight.js.
(node:21703) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'writeFile' of undefined
    at buildBrowserHighlightJS (/Users/morgan/Projects/highlight.js/tools/build_browser.js:124:17)
    at <anonymous>
(node:21703) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:21703) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.```

**Comment by yyyc514** [comment]
What build command? What content in `extra`?

**Comment by yyyc514** [comment]
const fs = require("fs").promises;

You need promises.  If your Node is very old you might have a problem and need to update.

**Comment by yyyc514** [comment]
If you wanted to make a tiny contribution that throws an error when the node version is too old that'd be awesome.

**Comment by morgan3d** [comment]
Excellent, thank you!
