### ISSUE TITLE
How am i gonna use it in browser?

### ISSUE THREAD

**Issue by youyinnn** [highlightjs/highlight.js#2455]
![image](https://user-images.githubusercontent.com/23525754/76302907-c171de80-62fb-11ea-9cad-2ee557324605.png)

Can not find any message in your readme, please rewrite it nicely.

**Comment by yyyc514** [comment]
I take it you figure it out?  I think overall our README is actually pretty nice.  If you have any *specific* suggestions please share them or submit a PR and we'd be happy to consider it.

**Comment by yyyc514** [comment]
I'm guessing perhaps you had a custom build and did not build in Java support?

**Comment by youyinnn** [comment]
The main [README.md](https://github.com/highlightjs/highlight.js/blob/master/README.md) does not mention any installation method for Browser usage.

I found it myself by lucky glancing at the hole repo and found [README.CDN.md](https://github.com/highlightjs/highlight.js/blob/master/README.CDN.md).

That's how I solved the case.

**Comment by yyyc514** [comment]
To me there is no such thing as "browser usage" in the generic sense unless you literally mean a CDN (just the flat files)... there are probably 100 different ways to use HLJS in the browser though if you cunt server-side frameworks, asset build systems, packaging tools, etc... **The README has examples for browser usage though...** What exactly did you find lacking?

If you're just using the CDN assets via CDN there is nothing to install...

**Comment by youyinnn** [comment]
Let's say it in that way: I can't just download the zip and use the file in [src](https://github.com/highlightjs/highlight.js/tree/master/src) locally and then copy the script:

``` html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
	
    <link rel="stylesheet" href=".C:\Users\xxx\Desktop\demo\src\style\default.css">
    <script type="module" src="C:\Users\xxx\Desktop\demo\src\highlight.js"></script>
    <script>hljs.initHighlightingOnLoad();</script>
</head>

<body>
    <pre class="hljs"><code class="language-java hljs"><span class="hljs-function"><span class="hljs-keyword">public</span> <span class="hljs-keyword">int</span> <span class="hljs-title">uniquePaths</span><span class="hljs-params">(<span class="hljs-keyword">int</span> m, <span class="hljs-keyword">int</span> n)</span> </span>{
        <span class="hljs-keyword">int</span>[] pre = <span class="hljs-keyword">new</span> <span class="hljs-keyword">int</span>[n];
        <span class="hljs-keyword">int</span>[] now = <span class="hljs-keyword">new</span> <span class="hljs-keyword">int</span>[n];
        <span class="hljs-keyword">for</span> (<span class="hljs-keyword">int</span> i = <span class="hljs-number">0</span>; i &lt; m; i++) {
            <span class="hljs-keyword">for</span> (<span class="hljs-keyword">int</span> j = <span class="hljs-number">0</span>; j &lt; n; j++) {
                now[j] = j &gt; <span class="hljs-number">0</span> ? (now[j - <span class="hljs-number">1</span>] + pre[j]) : <span class="hljs-number">1</span>;
            }
            pre = Arrays.copyOf(now, now.length);
        }
        <span class="hljs-keyword">return</span> now[n - <span class="hljs-number">1</span>];
    }</code></pre>
</body>

</html>
```

and here is what I got:
![image](https://user-images.githubusercontent.com/23525754/76375027-c24c5400-637f-11ea-8a4c-da41ecac6170.png)

That's not a local version of your work.
And that's what I mean **browser usage** or as you said **just a flat files**. 
With your README.md, it's hard to startup immediately in local.

And what I mean **Installation**... you can refer to any other tools or js framework repo:

- [dayjs installation guide](https://day.js.org/docs/en/installation/installation)
- [KaTeX installation guide](https://katex.org/docs/browser.html)
- [popperjs installation guide](https://github.com/popperjs/popper-core#installation)
- [clipboardjs installation guide](https://github.com/zenorocha/clipboard.js#install)
- ....

**Comment by yyyc514** [comment]
Thanks - this is far more helpful feedback, I'll take a look at those other examples and see if it sparks any ideas.  Right from a packing perspective CDN is probably that answer.  You can also find it at https://github.com/highlightjs/cdn-release.  With v10 we're going to start making a NPM build of the CDN release.

But for someone who wanted a zip with built JS files in it, a zip from the CDN repo is probably the best bet... but perhaps we could find a better place to document that.

The official website also can generate custom builds easily.

**Comment by yyyc514** [comment]
> A clear installation guide is good for any level of developer, in my case, I don't want to run any building process or package manager for a quick startup of a new js framework.

I take your point though we're not shy about sharing the CDN urls... and they are only 1 fetch away with `curl`, `wget`, etc...

**Comment by youyinnn** [comment]
> or do you think perhaps that should just be explicitly stated vs implied?

That would be nice.

**Comment by youyinnn** [comment]
> sharing the CDN urls (they are in the readme).

Ah, I see it but the title **"[Getting The Libaray](https://github.com/highlightjs/highlight.js/tree/9-18-stable#getting-the-library)"** is kind of misguiding the point of **"Right out of the box"** so I didn't take it seriously. I thought it was about some dependencies or something else. Sorry about that.

**Comment by yyyc514** [comment]
We should remove that phrasing, it's entirely unclear what the "box" there is.

**Comment by youyinnn** [comment]
> what's might not be 100% clear is "where do I get the browser script"

That's what I suggest you adding some information to that.

**Comment by yyyc514** [comment]
Yeah, I'll see.  The whole section looks to be lacking now in what it promises to deliver now that I'm looking at it. :-)  The website is much better.

**Comment by yyyc514** [comment]
https://github.com/highlightjs/highlight.js/pull/2457

Specific feedback welcome.
