### ISSUE TITLE
Pre-release aware publish

### ISSUE THREAD

**Issue by isagalaev** [highlightjs/highlight.js#2459]
The build script on highlightjs.org needs to distinguish between pre-release and stable versions and only update the web site to the stable ones, while still publishing pre-release stuff to CDN and npm.

Bonus: https://highlightjs.readthedocs.io/ should show the docs for the latest stable release.

**Comment by yyyc514** [comment]
Any luck?

**Comment by yyyc514** [comment]
Ping.

**Comment by yyyc514** [comment]
Wait, can I still do an actual release then if I want? Did we get all the moving pieces there working?

**Comment by joshgoebel** [comment]
@allejo This would be a fun one to move to GHA first (and have immediate utility)... I think we'd just need to match a tag like `M.m.p-betaY` and then trigger an action to build and push an appropriate tagged NPM package.   We'd also have to look into our CDN repo and whether that would need to be included in this or not.  But even starting with just NPM alone would be useful.

And once this was done (and tested) making it work for production releases also would probably be a tiny change. (I'd guess)

**Comment by joshgoebel** [comment]
Closing via https://github.com/highlightjs/highlight.js/pull/2850
