### ISSUE TITLE
How to use it with HTML?

### ISSUE THREAD

**Issue by LuizGMX** [highlightjs/highlight.js#2461]
Hi i'm trying to use it with HTML but it's not working, it's rendering the HTMK instead of highlighting it

**Comment by yyyc514** [comment]
Did you read the README?  You'd have to show us exactly what you're doing.

A jsfiddle, etc. would be nice.  Here is a sample:

https://jsfiddle.net/ajoshguy/gfzujpyt/

**Comment by yyyc514** [comment]
>  it's rendering the HTMK instead of highlighting it

Your HTML needs to be escaped of course... ie `&gt;` not `>`, otherwise it will render as HTML, because it IS HTML.

**Comment by yyyc514** [comment]
@LuizGMX Does that help?

**Comment by LuizGMX** [comment]
Yes thx
