### ISSUE TITLE
how to use/implement input tags and custom jsx tag for syntax highlighting using Highlight.JS?

### ISSUE THREAD

**Issue by MeRahulAhire** [highlightjs/highlight.js#2462]
I was just searching around how to highlight code just like Text editors on website and I found some libraries and I liked `highlight.js` and started to play around with it.<br><br>
But to my sense it worked well except for the `<input/>`tags and custom react component tags doesn't get rendered well. <br><br>
I followed the documentation and [implement the code in following manner][1]:

    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.18.1/highlight.min.js"></script>
    <script>hljs.initHighlightingOnLoad();</script>
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.18.1/styles/night-owl.min.css">
    
    <div class="code-container" style="margin: auto; width: 50%;">
        <pre><code data-language="javascript">
            import React, { Component } from 'react'
            import './reg-style/Credentail.css'
            import 'react-phone-number-input/style.css'
            import PhoneInput from 'react-phone-number-input'
            export class Credential extends Component {
        continue = e => {
            e.preventDefault();
            this.props.nextStep();
          };
        
          back = e => {
            e.preventDefault();
            this.props.prevStep();
          };
        render() {
              const { values, handleChange } = this.props;
    
            return (
                        <div>
                            <Helmet>
                            <body className="form-bg-col"></body>
                          </Helmet>
                         
          
                          <div className="login">
                            <div className="reg-container">
                            <button onClick={this.back} className="col-form-prev"><i class="fa fa-chevron-left"></i></button>
                            <div className="user-detail email">
                                Email:
                                <input onChange={handleChange('Email')} defaultValue={values.Email}  type="email" placeholder="Enter your Email"/>
                            </div>
                            <div  className="user-detail ">
                                Phone:
                                <PhoneInput
                                onChange={handleChange('Phone')} defaultValue={values.Phone}
                                displayInitialValueAsLocalNumber
                                  placeholder="Enter phone number"
                                  defaultCountry="IN"
                                  />
                                
                            </div>
                            <div className="user-detail username">
                                Username:
                                <code><input onChange={handleChange('Username')} defaultValue={values.Username} type="text" placeholder="Select your unique Username" /></code>
                            </div>
                            <div className="user-detail password">
                                Password:
                                <input onChange={handleChange('Password')} defaultValue={values.Password} type="password" placeholder="Choose your Password" />
                            </div>
                                              
                            <button onClick={this.continue} className="col-form-next"><i class="fa fa-chevron-right"></i></button>
                            
                           
                            </div>
                              
                          </div>
                      </div>
                  
            )
        }
    }
    
    export default Credential
    
        </code></pre>
    
    </div>

and result was as following:<br><br> [![enter image description here][2]][2]
What should i do to rectify these issues?
<br>Thanks...

  [1]: https://codepen.io/rahulahire/pen/oNXdqyK
  [2]: https://i.stack.imgur.com/rN4Z0.png

**Comment by yyyc514** [comment]
First start by escaping your HTML properly in the browser... it should NEVER be rendering like that.  If you are including RAW HTML then it will of course be rendered, that's just what the browser does.  RAW HTML code inside a <code> tag isn't magically excluded from HTML parsing.

**Comment by MeRahulAhire** [comment]
to be honest, I have never worked with Regex but according to your suggestion, i tried using `&lt` and `&gt` and it was working very well but by this method i need to replace every `<` and `>` with previously mentioned. 

Can you please me any better way of do it all once and also possibly support regex for this type of case natively in your library in the improvement/next version so that it would be helpful for all of us

**Comment by yyyc514** [comment]
> but by this method i need to replace every < and > with previously mentioned.

**This is just how HTML works.**  If you want a *LITERAL* "less than" you have to encode it. It's fairly trivial in almost any language to find a prewritten HTML escape function you can use to escape your content properly.  If you don't escape it then it's HTML (not content) and your browser will render it as HTML.

You could also perhaps try to do this yourself client-side with Javascript by fetching `innerHTML` and then encoding it and placing it back as innerHTML, then highlighting.  That is a pretty ugly hack though and if this is user provided content that would open your site to potentially HUGE security holes and HTML injection of course - which is why you're supposed to escape it in the first place.

**Comment by yyyc514** [comment]
Closing as "existing behavior is correct".

**Comment by MeRahulAhire** [comment]
would you be supporting inbuilt regex in your library for future

**Comment by yyyc514** [comment]
I'm not sure what you are asking.

**Comment by yyyc514** [comment]
What you are asking can easily be achieved with a few lines of Javascript, but it is a potentially SERIOUS security issue to embed unescaped HTML on a webpage like you are suggested.  **It's not a behavior we are going to explicitly support or encourage.**

Google and read up on HTML injection attacks.  Even if you own 100% of the content this is a bad idea, and can result in very broken pages (like you're already seeing) if say your JS failed to load or hit an error.

**Comment by MeRahulAhire** [comment]
I meant instead of writing `&lt`/`&gt` every time manually could you implement a 
couple of more lines of JavaScript in your library so that it could find all the `<` and `>` brackets and replace it with it so that it can work smoothly without any changes to the code on user's side?

**Comment by yyyc514** [comment]
No.  You could do that yourself (easily), but as I said it's a VERY bad idea.

**Comment by MeRahulAhire** [comment]
I think yeah you're right I tried in vscode to replace all the tag by selecting all the `<` with `&lt` which was really easy.

Check the demo below
https://elastic-bell-f27c70.netlify.com/

Between, thanks for helping me. I really appreciate what you guys are doing and I do know that maintaining the open source project can be daunting as some time but even then you do really make life of thousands of developers easier impacting on our life and that's a really great thing.

Keep making progress and I'll also wait for more amazing themes in future 
Some of my favourite that I like: 

> 2077 vscode theme

> Abyss

> All material Themes

Thanks....

**Comment by yyyc514** [comment]
> I think yeah you're right I tried in vscode to replace all the tag by selecting all the < with &lt which was really easy.

There is probably a plugin for that kind of thing also.
