### ISSUE TITLE
Solved: Data loaded via AJAX must be highlighted manually with highightBLock()

### ISSUE THREAD

**Issue by R2h1** [highlightjs/highlight.js#2465]
请问为啥我在引入了defalut.css，也导入了highlight.js,代码却没有突出显示

**Comment by yyyc514** [comment]
Need more english, please?

**Comment by R2h1** [comment]
Defalut.css is introduced and highlight.js is imported, but the code is not highlighted. Why?

**Comment by yyyc514** [comment]
I dunno, you're going to have to provide more information or a reproducible sample.

**Comment by R2h1** [comment]
ok，My HTML is as follows:
<html>
<head>
<link rel="stylesheet" href="/css/styles/default.css">
</head>
<body>
<pre>
<code class="language-javascript">class Node{
    constructor(data){
        this.data = data;
        this.next = null;
    }
}</code></pre>
<script src="/js/highlight.js"></script>
</body>
</html>

**Comment by yyyc514** [comment]
Not sure why none of your tags are closed? Paste error?

That looks reasonable... any errors in console?

**Comment by R2h1** [comment]
It's actually closed, and I didn't shut it down on purpose because github doesn't support sending such messages

**Comment by yyyc514** [comment]
> github doesn't support sending such messages

What such messages? It works fine if you quote it properly (as I did when I edited it to fix the quoting).

**Comment by R2h1** [comment]
The truth is this：
<link rel="stylesheet" href="/css/styles/default.css">
<pre>
<code class="language-javascript">class Node{
    constructor(data){
        this.data = data;
        this.next = null;
    }
}</code></pre>
<script src="/js/highlight.js"></script>

请问我就是这样导入了所需的css和js，为什么不起作用呢？

**Comment by R2h1** [comment]
The truth is this：
<link rel="stylesheet" href="/css/styles/default.css">
<pre>
<code class="language-javascript">class Node{
    constructor(data){
        this.data = data;
        this.next = null;
    }
}</code></pre>
<script src="/js/highlight.js"></script>

I just imported the required CSS and js. Why didn't it work?

**Comment by yyyc514** [comment]
I asked: **any errors in console?**

**Comment by R2h1** [comment]
No problem pops out of the console

**Comment by yyyc514** [comment]
Did you read the readme?  You have to actually execute the library.

**Comment by R2h1** [comment]
how to execute the library?Just HLJS. InitHighlightingOnLoad (); Not enough, is it？

**Comment by yyyc514** [comment]
Well, that's close... the exact code is in the README.

**Comment by R2h1** [comment]
Do I need do this?
document.addEventListener('DOMContentLoaded', (event) => {
  document.querySelectorAll('pre code').forEach((block) => {
    hljs.highlightBlock(block);
  });
});

**Comment by yyyc514** [comment]
No, that's what `initHighlightingOnLoad` does if you call it.

**Comment by R2h1** [comment]
initHighlightingOnLoad  , I have done, anything else I should  do ?

**Comment by R2h1** [comment]
![image](https://user-images.githubusercontent.com/40930301/77250606-190d3400-6c84-11ea-8097-67591264c5b3.png)

**Comment by yyyc514** [comment]
That's the idea.

**Comment by R2h1** [comment]
That's what I did, but。。。

**Comment by R2h1** [comment]
Thank you very much ! I have known how to solve this problem. Because it Unable to highlight the code for fetching incoming documents from the back end of the interface.

**Comment by yyyc514** [comment]
Huh?

**Comment by R2h1** [comment]
Because I initialized it first, and the part of the document that includes the code is returned by ajax.

It is estimated that it is the data returned by ajax after the front end has been rendered, and the previous initialization will not work.
Thank you very much for your patience in answering my questions
My English is not very good, please forgive me

**Comment by yyyc514** [comment]
> It is estimated that it is the data returned by ajax after the front end has been rendered, and the previous initialization will not work.

Right then you'll need to write custom JS to do it afterwards, which the README also explains.
