### ISSUE TITLE
highlight.js/lib/languages/html not found

### ISSUE THREAD

**Issue by vasanthdeveloper** [highlightjs/highlight.js#2467]
**Describe the issue**
```
Cannot find module 'highlight.js/lib/languages/html'
```
The [README.md](https://github.com/highlightjs/highlight.js/blob/master/README.md) file gives the following example code to import HTML syntax highlighting:
```
const hljs = require("highlight.js/lib/core");  // require only the core library
// separately require languages
hljs.registerLanguage('html', require('highlight.js/lib/languages/html'));
```
Here are the language files installed by `npm` in my `node_modules` directory:

![discord](https://user-images.githubusercontent.com/24322511/77322926-7cf23400-6d3a-11ea-8a40-d20e2e155f7a.png)

As you can see there is no `html.js`. Also, I don't know why the date shows up as 1985 when I installed a minute ago.

**Additional context**
1. **GulpJS:** 4.0.2
2. **Browserify:** 16.5.0
3. **TerserJS:** 4.6.3

Here is the code I used to get `highlight.js` working:
```
const hljs = require('highlight.js/lib/core');

// require the languages we deal with
hljs.registerLanguage('html', require('highlight.js/lib/languages/html'));
hljs.registerLanguage('css', require('highlight.js/lib/languages/css'));
```

Any help would be greatly appreciated :smiley:

**Comment by yyyc514** [comment]
Oh yikes, when did we break that.  It should be `xml`.  We have no HTML syntax, `html` is only an alias for XML.

**Comment by yyyc514** [comment]
Closed by https://github.com/highlightjs/highlight.js/commit/166aa0afb7259c010e7cd05acda8a5d85a81c4db

**Comment by vasanthdeveloper** [comment]
@yyyc514 Can I send a pull request with the updated README.md? Also, the website has `html` instead of `xml`.

**Comment by vasanthdeveloper** [comment]
I still have to investigate on why the date shows up as 1985...

**Comment by yyyc514** [comment]
I already fixed it.  Lots of other issue flagged help welcome if you're looking for ways to contribute.

> Also, the website has html instead of xml.

The website won't be updated until the next library release, which is hung up waiting for server changes.

**Comment by yyyc514** [comment]
> I still have to investigate on why the date shows up as 1985...

No idea, id' suggest that's your own local problem.

**Comment by vasanthdeveloper** [comment]
Oh, this is the fastest response I ever got on GitHub! :astonished:

**Comment by yyyc514** [comment]
Fast response courtesy of your friendly neighborhood COVID-19 keeping me locked inside 24/7. 😜💀😭

**Comment by vasanthdeveloper** [comment]
:frowning_face: The situation is the same here. I hate my neighbor as much as you do.

**Comment by yyyc514** [comment]
I never said I hate my neighbors. :)

**Comment by vasanthdeveloper** [comment]
Still, I have been either writing code or making videos for 24x7 from the past year or so. So, there isn't much of a difference in my life...
