### ISSUE TITLE
[Request] Does version 9 support ES6?

### ISSUE THREAD

**Issue by elgs** [highlightjs/highlight.js#2473]
Does version 9 support ES6? The doc mentioned the `import` syntax. However, when I tried to `import` and use the library:
```javascript
import hljs from '../../../node_modules/highlight.js/lib/index.js';
import hljs from '../../../node_modules/highlight.js/lib/highlight.js';
```
I got the following error:
```
The requested module '../../../node_modules/highlight.js/lib/highlight.js' does not provide an export named 'default'
The requested module '../../../node_modules/highlight.js/lib/index.js' does not provide an export named 'default'
```

When I tried:
```javascript
import * as hljs from '../../../node_modules/highlight.js/lib/index.js';
```
I got:
```
Uncaught ReferenceError: require is not defined
```

Looking at the module code in node_modules, it seems I didn't see any `export` statement but I only saw `require` statements.

**Comment by yyyc514** [comment]
We're using `module.exports` in the NPM source.  If you want to use ES6 style imports you'll need to use a build system that can process understand `module.export` style exports, such as `rollup`, etc.

How are you using import anyways?  It's still experimental in Node itself.

**Comment by yyyc514** [comment]
If you wanted to make a PR adding a note to the docs that'd be great.

**Comment by elgs** [comment]
What I'm hoping is to avoid any build system. I use `<script type='module'>` in my html as entry point. Now as ES6 browser support is getting mature, a building system will become unnecessary for some small projects. But a building system will remain useful for doing things like minify code and tree shake.

My experience is the `require` and `import` ecosystems are not getting along well. Many modules have to maintain two separate packages, like lodash and lodash-es. Because `export const something` is not a legal syntax in the nodejs ecosystem, but I heard nodejs is doing something called mjs (I don't like their careless decision to add a new file extension) that will experimentally support import. So I think it makes sense for modules to move towards ES6.

I'm new to highlight.js. I think it will be a huge code find/replace to get an ES6 package ready to use. I will look into use, but I believe it will be a lot easier for someone who is familiar with the code to do it.

**Comment by elgs** [comment]
I just looked into the source code, and I found actually all the source code are using ES6 import/export, which is cool. Looks like the problem is the build product. I guess it will be easy to build an ES6 version of highlight.js. But I am not sure how to do it.

**Comment by yyyc514** [comment]
Is there a reason you can't just use the web build we provide?

**Comment by yyyc514** [comment]
> I just looked into the source code, and I found actually all the source code are using ES6 import/export, which is cool.

Yes, that's new. I just did that with version 10.  If you really want to use raw imports you'd have an easier time using the library raw from Github than using the NPM packages.

**Comment by elgs** [comment]
Yes, I want to:
1. streamline my process, I mean to use npm in the script;
2. not use any dependencies/build systems unless absolutely necessary;

**Comment by elgs** [comment]
> But I'm unsure how you're getting all this into your browser then?

I can. As long as the highlight.js code follows ES6 import/export stand, my code will be as easy as what I have shown at the top of this thread. I have successfully done it with many other packages, including lodash-es.

**Comment by yyyc514** [comment]
**Is there a reason you can't just use the web build we provide?**

**Comment by elgs** [comment]
> **Is there a reason you can't just use the web build we provide?**

Yes, I want to:

1. streamline my process, I mean to use npm in the script;
2. not use any dependencies/build systems unless absolutely necessary;

**Comment by yyyc514** [comment]
The web build does not require any build system.

**Comment by yyyc514** [comment]
>  As long as the highlight.js code follows ES6 import/export stand, my code will be as easy as what I have shown at the top of this thread

We make no guarantees about the stability of that code between releases (even minor ones) though. Our build products (npm, cdn, etc) are the releases we make guarantees about.  So it's very likely you will have files moved around, the structure of the directories, changed, etc... so you'd have to be very careful upgrading.

**Comment by elgs** [comment]
> The web build does not require any build system.

Thanks. I will try it.

**Comment by yyyc514** [comment]
The easiest thing might be just to modify our build process to kick out ES6 modules instead of require modules, it's probably only a few lines of code to change.  Then you'd have a "ES6 version of the library" you could do with as you please.

I'm not sure we're interested in shipping this ourselves though unless there was a lot more demand.  It's very easy for most to work around this with a build system.

**Comment by yyyc514** [comment]
Oh, just to full to answer the question though version 9 isn't ES6 modules at all under the covers... that all came with version 10.

**Comment by elgs** [comment]
Thank you @yyyc514! 🤞

**Comment by yyyc514** [comment]
Glad to help. Good luck.
