### ISSUE TITLE
(yaml) add support for dates/timestamps

### ISSUE THREAD

**Issue by tamlyn** [highlightjs/highlight.js#2475]
**Describe the issue**
Highlighting of YAML date/datetime objects is inconsistent.

<img width="479" alt="Screen Shot 2020-03-30 at 12 31 59" src="https://user-images.githubusercontent.com/115310/77907952-828fd280-7282-11ea-9596-fa1fca58679e.png">

Some things that are parsed by YAML as dates get highlighted partly as strings, some things that are parsed by YAML as strings get highlighted as dates (or maybe numbers).

**Which language seems to have the issue?**
yaml

**Are you using `highlight` or `highlightAuto`?**
`initHighlightingOnLoad` with a language classname (see codepen below).

**Sample Code to Reproduce**
https://codepen.io/tamlyn/pen/mdJvMYv

**Expected behavior**
I expect the highlighting to be consistent with YAML's complex datatype parsing. But given the highlighting rules are based on regexes, maybe I expect too much.

**Comment by yyyc514** [comment]
Reference: https://yaml.org/type/timestamp.html

Looks like we'd be able to do this, but currently we don't have any special recognition for dates at all.  What you're seeing is the number rule in action.
