### ISSUE TITLE
add support for ANSI escaped text

### ISSUE THREAD

**Issue by ssbarnea** [highlightjs/highlight.js#2476]
While `ANSI escaped` text is not a programming language by itself, being able to convert it to JavaScript would enable users to copy/paste terminal output in Markdown documents in order to document output without having to make screenshots.

This feature would be great for creating console output examples.

**Comment by yyyc514** [comment]
Either I'm not following you or I think you're confused about what we do.  We highlight source code.  If we were to highlight ANSI text we'd still show all the character sequences and escape codes, just we'd color them differently so they were easy to pick out from the rest of the content.

Parsing the ANSI codes and turning them into HTML that looks like the console is not at all what we do.

I think maybe you're looking for something like:
https://asciinema.org/

**Comment by ssbarnea** [comment]
I am not confused at all about what I describe but as I mentioned, is a little bit different. Still as a user that writes markdown with code blocks all the time, in a huge number of cases this code happens to be console output. This is why I would find very useful to be able to write somethign like:

```
'''ansi
Foo ^[33bar
'''
```

If "ansi" would be supported as a language, it would be very easy to colorize it, also to edit it.

Other approaches would require defining new syntax specially for ANSI blocks, which would require extra knowledge and it would be quite hard to implement in various tools.
I think that the ANSI escapes themselves can be made invisible.

**Comment by yyyc514** [comment]
I meant perhaps you were confused about what HLJS does (as a general rule), not what you're desiring.  I have no doubt that you clearly understand what you'd like it to do. :-)

> I think that the ANSI escapes themselves can be made invisible.

See that right there is what we don't do.  **We highlight, we don't render.** People sometimes also miss this distinction with Markdown.  We don't turn `**boo**` BOLD, we colorize it to indicate that it has special meaning in the markdown grammar.  _If someone wanted bold they would want a Markdown renderer, not highlighter._

If there was a grammar for ANSI then a sequence like `^[33` would be visible, but colored differently to indicate it was an escape sequence.

---

That said you're welcome to write a 3rd party grammar to highlight ANSI. You could *probably* even also use the new plugin support to "augment" said language to actually remove the escape sequences also if you really wanted to.

**Comment by ssbarnea** [comment]
@yyyc514 Thanks for clarifications on this. In fact there are several js tools able to perform ansi2html. The reason why I mentioned here was accessibility for the consumer. But it makes sense to do it as a 3rd party language.

**Comment by yyyc514** [comment]
> In fact there are several js tools able to perform ansi2html.

I'm not surprised. :)

> But it makes sense to do it as a 3rd party language.

If you decide to take the plunge, let us know.

**Comment by jayaddison** [comment]
@ssbarnea Adding a note that I'm interested in this kind of functionality as well (even if it is not within hightlightjs itself).  I'd be glad to hear of any tooling you find (or are developing).
