### ISSUE TITLE
Never language highlighter

### ISSUE THREAD

**Issue by smaludzi** [highlightjs/highlight.js#2479]
**Describe the issue**
I would like to add Never language syntax highlighter.
Please check the following repository:

https://github.com/never-lang/highlight-js-never

**Which language seems to have the issue?**
Never language

**Are you using `highlight` or `highlightAuto`?**
Sorry, I don't know...

**Sample Code to Reproduce**
None

**Expected behavior**
Never is integrated

**Additional context**
None

**Comment by yyyc514** [comment]
We don't merge languages into the core library anymore, but we'd be happy to have you listed in our comprehensive list of `SUPPORTED_LANGUAGES.md`... just make a pull request adding your language to the list in the proper order!
