### ISSUE TITLE
[Request] Windows Registry File Highlighting

### ISSUE THREAD

**Issue by xnaas** [highlightjs/highlight.js#2482]
**The solution you'd prefer / feature you'd like to see added...**
Looking for syntax highlighting for [Windows Registry (.reg) files](https://en.wikipedia.org/wiki/Windows_Registry#.REG_files). [GeSHi](http://qbnz.com/highlighter/) supports this, as a reference.

**Additional context...**
Add any other context or screenshots relating to the feature request here.

Example of syntax highlighting:

![reg example](https://xnaas.info/img/KnowingJitteryKittiwake.png)

**Comment by yyyc514** [comment]
Feel free to add this to the wiki: https://github.com/highlightjs/highlight.js/wiki/Grammar-Requests

From the docs:

> Highlight.js doesn't have a fundamental plan for implementing languages, instead the project works by encouraging development of 3rd party language grammars from contributors. We're also happy to host 3rd party language grammars at the `highlightjs` GitHub organization - no matter how obscure or weird.

> This means that there's no point in requesting a new language without providing an implementation for it. If you want to see a particular language included in highlight.js but cannot implement it, the best way to make it happen is to get another developer interested in doing so.

If you want to do the work we'd be happy to see a 3rd party grammar for the Windows Registry. :)

**Comment by joshgoebel** [comment]
Go to create a new issue and check the button about requesting 3rd party grammar repository....

**Comment by dannybeckett** [comment]
@kuenzign Were you ever able to submit the regedit grammar please? Thank you
