### ISSUE TITLE
how to represents new lin in code?

### ISSUE THREAD

**Issue by wenzi0github** [highlightjs/highlight.js#2485]
how to represents new lin in code. add a character `+`

for example:

```javascript
function add(a, b) {
+   a = Number(a);
    return a + b;
}
```

**Comment by taufik-nurrohman** [comment]
Use the _diff_ highlighter.

**Comment by yyyc514** [comment]
Yes to highlight diffs you want the `diff` language/grammar. Closing as asked and answered.

**Comment by wenzi0github** [comment]
thank you.
