### ISSUE TITLE
(yaml) Tags should allow non-word characters

### ISSUE THREAD

**Issue by pplantinga** [highlightjs/highlight.js#2486]
**Describe the issue**
YAML tags can include some non-word characters (e.g. period, dollar sign) but current highlighting only matches letters and underscores

**Which language seems to have the issue?**
YAML

**Sample Code to Reproduce**
https://jsfiddle.net/7ukmfhsv/

**Expected behavior**
![yaml-highlight](https://user-images.githubusercontent.com/4369106/78914522-824cbf80-7a58-11ea-9f7c-1dbd3bfdb108.png)

**Comment by yyyc514** [comment]
Confirmed. Should be a simple fix. PR welcome.

**Comment by yyyc514** [comment]
@pplantinga Any chance you'd be interested in https://github.com/highlightjs/highlight.js/issues/2475?  It's gotta be much simpler than this. :-)
