### ISSUE TITLE
(sql) highlight.js incorrectly detecting # as comments

### ISSUE THREAD

**Issue by GitClickOk** [highlightjs/highlight.js#2491]
**Describe the issue**
highlight.js incorrectly detecting # as comments, when the correct is -- (for inline) and /* */ for multilines

**Which language seems to have the issue?**
SQL

**Are you using `highlight` or `highlightAuto`?**
highlight

**Sample Code to Reproduce**
CodePen: [https://codepen.io/ClickOk/pen/BaoyeKo](https://codepen.io/ClickOk/pen/BaoyeKo)
Works wrongly:
```
<pre><code class="sql">SELECT TestId FROM #temp_table_with_tests WHERE someOtherColumn IS NOT NULL
</code></pre>

```
Works almost fine:
```
<pre><code class="sql">SELECT TestId 
FROM #temp_table_with_tests 
WHERE someOtherColumn IS NOT NULL
</code></pre> 
```
If you look in inspector, highlight.js is applying "hljs-comment" class to #temp_table_with_tests. And then the remaining of the line will be a comment. So, if I line break, the remaining code works fine.

**Expected behavior**
Comments must be only -- (for inline) and /* */ for multilines for SQL Language

**Comment by yyyc514** [comment]
https://github.com/highlightjs/highlight.js/commit/20c398158e82956997a2c37cda5b544eb2747ae5

In a previous revision this was:

```
var MYSQL_COMMENT_MODE = hljs.COMMENT('#', '$');
```

Is this a MySQL specific feature?

**Comment by yyyc514** [comment]
`SELECT TestId FROM #temp_table_with_tests`

I'm not familiar with this, what SQL dialect is this and what does that # do?

**Comment by GitClickOk** [comment]
@yyyc514 The dialect is TSQL (Transact-SQL from SQL Server). This is a "Local Temporary Table". With double hash (##) you get a "Global Temporary Table". You can see a nice explanation [here](https://www.red-gate.com/simple-talk/sql/t-sql-programming/temporary-tables-in-sql-server/).

**Comment by egor-rogov** [comment]
@GitClickOk For TSQL you should use TSQL language, available from this repo: https://github.com/highlightjs/highlightjs-tsql

**Comment by GitClickOk** [comment]
@egor-rogov Thank you very much, but how I do to include this language? In [main highlight.js download page](https://highlightjs.org/download/) does not appears TSQL in list, I can see only "SQL" and "PostgreSQL".

**Comment by yyyc514** [comment]
@GitClickOk You could file an issue over on their repository to add some instructions to their README. :-) Since they don't provide a `dist` you may have to build it from scratch:

Check out https://github.com/highlightjs/highlight.js/blob/master/extra/3RD_PARTY_QUICK_START.md 

That's basically the idea but you're using their repo, not making your own.

**Comment by GitClickOk** [comment]
@egor-rogov and @yyyc514 

Thanks for the help.

BTW, I found this another repo (https://github.com/red-gate/highlight.js). It is older (2-3 years ago) with the highlightjs 1.0.3 version, but it provided a working dist, and it worked very nicely for TSQL.

When I get some more time I will try follow your instructions for the updated version.

Best Regards
