### ISSUE TITLE
[Request] Adding CpcdosC+ support language.

### ISSUE THREAD

**Issue by Cpcdos** [highlightjs/highlight.js#2493]
Hi, we are a growing community around the Kernel Cpcdos project, we are using CpcdosC+ syntaxic language since 9 years. Now we'd love to port our language to highlight.js, you can find the repository [Here](https://github.com/SPinti-Software/highlightjs-cpcdos)

We are looking forward to hear about your opinion!
Sincerly yours,

SPinti Software,
Sébastien FAVIER

**Comment by yyyc514** [comment]
From our documentation

> Highlight.js doesn't have a fundamental plan for implementing languages, instead the project works by encouraging development of 3rd party language grammars from contributors.  We're also happy to host 3rd party language grammars at the ``highlightjs`` GitHub organization - no matter how obscure or weird.

> This means that *there's no point in requesting a new language without providing an implementation for it*. If you want to see a particular language included in highlight.js but cannot implement it, the best way to make it happen is to get another developer interested in doing so. Here's our :doc:`language-guide`.

If you're interested in developing your own 3rd party language module start with: https://github.com/highlightjs/highlight.js/blob/master/extra/3RD_PARTY_QUICK_START.md

We'd love to have you!

**Comment by yyyc514** [comment]
Oh you already did it! LOL.  

- Please consider building and adding the `dist` folder to your repository
- Please consider a much longer README along the lines of some of the other 3rd party languages (just click thru our organization to see example) with documentation explaining how to use your plugin

But regardless if you make a PR to add your language to the table in SUPPORTED_LANGUAGES.md we'll get it merged.

**Comment by Cpcdos** [comment]
Nice thank you !
We take care of all that ;)
