### ISSUE TITLE
highlightBlock(block) should have a 'languageSubset' parameter just like highlightAuto(code, languageSubset)

### ISSUE THREAD

**Issue by fferri** [highlightjs/highlight.js#2495]
Or how it is possible to exclude certain languages from auto detection...?
I only need few languages (python, cpp, cmake, lua, shell, matlab) but autodetection will detect very unlikely langs.

Adding a a `languageSubset` parameter to `highlightBlock(block)` would work just fine, and it would make it consistent with `highlightAuto(code, languageSubset)`.

**Comment by yyyc514** [comment]
You can configure this globally with `configure` and passing `languages`.

**Comment by fferri** [comment]
I guess `configure` works equally well. Thanks.
