### ISSUE TITLE
[Request] Support for MXML Language

### ISSUE THREAD

**Issue by carlosrovira** [highlightjs/highlight.js#2497]
**Is your request related to a specific problem you're having?**

I'm trying to use hljs to show AS3 and MXML. hljs right now supports ActionScript but not MXML
I can use XML for now, but would be better to have MXML supported

**Any alternative solutions you considered...**

I saw pygmentize has MXMLLexer, but would like to use hljs instead. Maybe that could be a starting point

Thanks in advance for the library

**Comment by yyyc514** [comment]
From our documentation

> Highlight.js doesn't have a fundamental plan for implementing languages, instead the project works by encouraging development of 3rd party language grammars from contributors.  We're also happy to host 3rd party language grammars at the ``highlightjs`` GitHub organization - no matter how obscure or weird.

> This means that *there's no point in requesting a new language without providing an implementation for it*. If you want to see a particular language included in highlight.js but cannot implement it, the best way to make it happen is to get another developer interested in doing so. Here's our :doc:`language-guide`.

If you're interested in developing your own 3rd party language module start with: https://github.com/highlightjs/highlight.js/blob/master/extra/3RD_PARTY_QUICK_START.md

We'd love to have you!

**Comment by carlosrovira** [comment]
Thanks Josh, thanks for the pointer, I'll take a look and see if I  have the time to contribute this :)
