### ISSUE TITLE
(java) Support for Hexadecimal Floating Point Literals

### ISSUE THREAD

**Issue by 0xflotus** [highlightjs/highlight.js#2507]
**Describe the issue**

**Which language seems to have the issue?**

According to [Oracle Blog](https://blogs.oracle.com/darcy/hexadecimal-floating-point-literals) Hexadecimal Floating Point Literals are supported in Java.

**Are you using `highlight` or `highlightAuto`?**

`highlight`

**Sample Code to Reproduce**

Cases _a-h_ are all legal literals in Java, tested on JShell Version 13.0.2

https://jsfiddle.net/ohqapxnc/

```java
a = 0x4fa6p2; // 81560.0
b = 0x.4p2; // 1.0
c = 0xa.ffp3f; // 87.96875
d = 0x1.0p2F; // 4.0
d2 = 0x1.p2; // 4.0
e = 0x1.0p2f; // 4.0
f = 0x1p1; // 2.0
g = 0x.3p4d; // 3.0
h = 0x1.2ep5D; // 37.75
```

**Expected behavior**

I would expect that all legal literals are highlighted as numbers.

**Comment by yyyc514** [comment]
Tagging beginner friendly as this is probably just finding the correct regex and adding another numeric variant.

**Comment by 0xflotus** [comment]
Maybe `0[xX](([a-fA-F0-9]+[a-fA-F0-9_]+[a-fA-F0-9]+|[a-fA-F0-9]+)?[\.])?([a-fA-F0-9]+[a-fA-F0-9_]+[a-fA-F0-9]+|[a-fA-F0-9]+)?[pP]([\d]+)[fF]?` could be a possible regex to solve this?
