### ISSUE TITLE
(javascript) (typescript?) setTimeout incorrectly detected as a setter

### ISSUE THREAD

**Issue by qWici** [highlightjs/highlight.js#2514]
<details>
  <summary>Screenshot of highlighted code</summary>

![image](https://user-images.githubusercontent.com/11472929/80415196-da9a1300-88da-11ea-8d2d-fd10cff05b7d.png)

</details>

<details>
  <summary>Screenshot of html output</summary>

![image](https://user-images.githubusercontent.com/11472929/80415307-0c12de80-88db-11ea-9207-4ec33022afdb.png)

</details>

It looks like this regexp wrong. 
https://github.com/highlightjs/highlight.js/blob/d4b047b4d89bcc302f50f079ba189b0ad0ccb91b/src/languages/javascript.js#L266

**Comment by yyyc514** [comment]
> It looks like this regexp wrong.

I concur with your conclusion.  Would you be willing to whip up a PR?  If so:

- Don't forget `CHANGES.md`
- We'll need to add a quick markup test for this.

It should likely be `\s+` me thinks.

**Comment by yyyc514** [comment]
This quite likely is also broken in typescript I'd guess.

**Comment by qWici** [comment]
@yyyc514 yeah, I tested it on [regex101](https://regex101.com/r/dgIXfJ/1). And I want to try to fix it.

**Comment by yyyc514** [comment]
Oh wow that site is super nice!

**Comment by qWici** [comment]
@yyyc514 ok, I fixed it. But I have 2 questions before PR.
1. Should these functions be highlighted? Because it's native JS functions (setTimeout, setInterval)
2. I don't see such a rule for typescript. I can add. Do I need to create a separate PR for this?

**Comment by yyyc514** [comment]
> Should these functions be highlighted? Because it's native JS functions (setTimeout, setInterval)

You could argue that either way.  We barely highlight any built in functions right now. Since those are more like window globals I wouldn't mind if we added them as built-ins.

> I don't see such a rule for typescript. I can add. Do I need to create a separate PR for this?

Oh, it doesn't have it.  I wouldn't.  Technically the rule would need to be a lot more complex in TypeScript with all it's type details... so unless you want to potentially tackle that I'd probably just focus on JS.

Long-term I'd like to see if we can find a way to build TS and JS on the same foundation since they are so similar (other than typing).

**Comment by qWici** [comment]
Something going wrong with name of my prev commit. So I remove the branch in my fork and [push another branch](https://github.com/highlightjs/highlight.js/pull/2515) with 2 commits.

**Comment by qWici** [comment]
@yyyc514 also I'm not sure if it's okay that my editor has replaced single quotes on double-quotes.

**Comment by yyyc514** [comment]
> @yyyc514 also I'm not sure if it's okay that my editor has replaced single quotes on double-quotes.

It's not great. :-)  I'd suggest turning off such features or scoping them to certain projects.  We don't have a firm policy on quotes yet but changing them randomly isn't beneficial.

**Comment by yyyc514** [comment]
Just the set/get incorrect highlighting portion of this has been fixed in a 10.0.3 release.
