### ISSUE TITLE
Add some type of look-behind support

### ISSUE THREAD

**Issue by joshgoebel** [highlightjs/highlight.js#2520]
**Is your request related to a specific problem you're having?**

Yes, there is no easy way to do look behind or to say: 

> match this, but only if immediately proceeded by that...

It's possible, but it gets ugly fast. For example here's how to match say `instanceof [class]` and do it _with no ambiguity_: (where [class] is the only part I want highlighted)

```js
      {
        begin: regex.concat('(?=', /\binstanceof /, IDENT_RE, ')'),
        contains: [
          { begin: /\binstanceof /,
            keywords: KEYWORDS,
            starts: {
              contains: [
                { begin: IDENT_RE, className: "title"}
              ],
            }
          },
        ],
      },
```

First we match the whole thing with a look-ahead... then our mode starts and our first rule has to re-include keywords from above (because now the context has changed), and then we have to match `instance of` and then start a new mode [for `IDENT_RE`] with `starts` to avoid the chance of our two expressions being similar enough that the first rule might fire for the second.

**The solution you'd prefer / feature you'd like to see added...**

Well if JS just supported look behind, we'd be all set but since it doesn't... Sample code from Javascript we're trying to match:

```js
if (str instanceof Token) { ...
// and
var token = new Token()
```

And how we might go about doing it:

```js
 { 
  skipBefore: /(\binstanceof[ ]+)/,
  begin: IDENT_RE,
  className: "title"
}, {
  skipBefore: /(\bnew[ ]+)/,
  begin: IDENT_RE,
  className: "title" 
},
// and for comparison: look-ahead, which is already possible;
{
  begin: regex.concat(IDENT_RE, /(?=\.(constructor|prototype))/),
  className: "title"
},
```

This is actually only a 5 line patch. Building this into the parser means the mode context doesn't change, so your existing keyword scope "just works"... and these become very simple rules.

**Potential Caveats**

1. It might have interactions with `returnBegin`... I'm not sure why you'd ever want to use them both... but we could either:
   - have `returnBegin` disable skipBefores "skip" ability, making it more of a "prefix"
   - throw an error for grammar developers and just say these two things don't mix.

2. The naming isn't perfect... technically this is `matchBeforeAndSkip`... I hesitate to name it `lookbehind` though because that's NOT what it's doing... it's still looking forward the whole time.  If another rule has consumed the content already this can't match it by "looking backwards", because there is no backwards looking going on.

**Any alternative solutions you considered...**

Writing code to write the complex version... but the keyword complexity and mode context switches make it a pain even if you had a helper, since you'd still have to pass in KEYWORDS from the parent context (as far as I can see)...

**Comment by yyyc514** [comment]
CC @egor-rogov  @allejo 

I started working on this after seeing how trivial some of these types of things are to do in Prism and how hard they are to do in Highlight.js.  Prism calls this feature `lookbehind`.

**Comment by yyyc514** [comment]
Ping. CC @egor-rogov @allejo

**Comment by egor-rogov** [comment]
It seems it would be nice to have some sort of look-behind / skip-before. The code snippet above makes sense for me.
Do you have some real use cases in mind?

**Comment by yyyc514** [comment]
The two cases shown above are all real.   `new instanceof` which in JS indicate that what follows is a class or class like constructor function (which we could then highlight with `title`).  I'm pretty sure this will have real applications everywhere in so many languages.

**Comment by joshgoebel** [comment]
https://github.com/highlightjs/highlight.js/pull/2680#issuecomment-707718580

```
\b boundary x 8,682 ops/sec ±1.25% (84 runs sampled)
negative lookbehind x 8,353 ops/sec ±1.52% (84 runs sampled)
hack with begin/end x 8,047 ops/sec ±0.56% (89 runs sampled)
with callback x 3,244 ops/sec ±0.64% (94 runs sampled)
```

Referencing some tests done elsewhere... Seems a manual implementation based on callbacks would be ~50-60% slower than the real thing.

**Comment by joshgoebel** [comment]
Now I'm wondering about the possibility of a `lookbehind` that we compiled into either an ACTUAL lookbehind or a virtual lookbehind...

```js
{
  lookbehind: [ /\bnew[ ]/, 4],
  lookbehind: { match: /(\bnew[ ]/), length: 4/ },
  lookbehind: "new ",
  lookbehind: {literal: "new "} ,
  begin: IDENT_RE,
  className: "title" 
},
```

We need the length because look-behinds typically need to be "pinned" (so they know the scope that they are working within).  A real regex engine analyzes the regex to determine the length, but I don't think we want to attempt that, so it would be necessary to specify the look behind length... OR perhaps if a string was provided we could assume a literal vs regex... though that would be different than how we typically handle strings.

**Comment by allejo** [comment]
> Now I'm wondering about the possibility of a `lookbehind` that we compiled into either an ACTUAL lookbehind or a virtual lookbehind... Safari is the only major engine right now that would need the virtual look-behind.

You caught my attention with this. How do envision this working? Take the performance hit on Safari only by using a fake lookbehind? So a function checking the browser support and returning a native regex with the lookbehind built-in or a hack otherwise?

```js
{
  // it's not clear what the 4 means in this case
  lookbehind: [ /\bnew[ ]/, 4],

  // please tell me this is a typo
  lookbehind: { match: /(\bnew[ ]/), length: 4/ },

  // you have my vote for this if this \/ is how it's ^ supposed to look
  lookbehind: { match: /(\bnew[ ])/, length: 4 },

  // meh...
  lookbehind: "new ",
  lookbehind: {literal: "new "} ,
  begin: IDENT_RE,
  className: "title" 
},
```

I'd prefer verbosity over simplicity. Language authors should know exactly what they're doing with the lookbehind, make them look up the spec and at least see the warning of a possible performance hit by using this feature.

**Comment by joshgoebel** [comment]
> Take the performance hit on Safari only by using a fake lookbehind? So a function checking the browser support and returning a native regex with the lookbehind built-in or a hack otherwise?

Yep. If you call using a callback function to perform the look behind a hack.

**Comment by allejo** [comment]
Then I like that solution. We shouldn't wait for Safari to catch up with the other two major browsers just for this feature.

**Comment by joshgoebel** [comment]
I just worry about someone writing a grammar naïvely and then it being 20 times slower in safari than anywhere else. 😬￼

**Comment by allejo** [comment]
What about adding a console warning when debug mode is activated and lookbehind is used on a browser that doesn't support native lookbehinds?

**Comment by joshgoebel** [comment]
No guarantee the person is even testing on Safari... I think the problem is that unless you really understand the engine it might just be too easy to write such a poor performing look-behind... so even if we spewed the warning everywhere someone isn't going to be able to figure it out or just ignore it and go "well it's fast enough"... now we can sort of guard the core library with detailed PR review but 3rd party languages that worked great but then randomly failed terribly on Safari isn't a great thing to create the possibility of.

There is a whole other approach here that involves rewriting some internals of the engine but seems like a poor idea given this is only a momentary problem and eventually time is going to fix it.

**Comment by allejo** [comment]
I agree that writing poor lookbehind code would be too easy. My only thought is do we keep blocking lookbehind support until Safari has support? Once the latest version of Safari has support, do older macOS versions upgrade or do they continue using older versions of Safari? i.e. Will there still be a longish delay while we wait for all Safari users to catch up or do we just break older Safari support at that point?

**Comment by joshgoebel** [comment]
I think if the operating system is still supported then it still getting safari updates. I'm on Mojave I skipped Catalina and Big Sur is about to come out and I'm pretty sure that I still see the occasional Safari update. 

But as far as exactly how long we wait I think we first need to see what the landscape looks like when safari finally adds support. ￼￼￼

**Comment by joshgoebel** [comment]
I think we should consider codifying this into a `fakeLookbehind` helper using just skip and starts.  It's not a true look-behind of course - it's a look-forward... but it works in any cases where there are no other rules eating the prior content... and this is almost exactly how we already do it in all the cases where it's hard coded.

IE:

```
hljs.fakeLookbehind{
  behind: "booger ",
  begin: "picking"
}
```

Which just compiles into a "first, then" style mode:

```
{
  begin: "booger ",
  starts: {
    contains: [
      begin: "picking",
      endsParent: true
    ]
}
```

And using `starts` and `endsParent` would be off-limits for lookbehind modes and be a hard error.  Though I wonder if we could find a better name than fake look-behind?

**Comment by joshgoebel** [comment]
R language has support for this now but it hasn't made it into the core compiler yet.
