### ISSUE TITLE
Add support for `registerAlias` similar to `registerLanguage`

### ISSUE THREAD

**Issue by wooorm** [highlightjs/highlight.js#2523]
**Is your request related to a specific problem you're having?**

Aliases are useful for example to support [GitHub’s names](https://github.com/github/linguist/blob/40992ba7f86889f80dfed3ba95e11e1082200bad/lib/linguist/languages.yml#L4987-L4991), and map them to highlightjs names.

**The solution you'd prefer / feature you'd like to see added...**

Such as like so: https://github.com/wooorm/lowlight#lowregisteraliasname-alias, but anything that allows mapping a new label to an (existing) language name.

**Any alternative solutions you considered...**

There is no access to `languages` or `aliases`, so it’s not possible to do this in userland.

**Additional context...**

n/a

**Comment by yyyc514** [comment]
FYI: You can do this now by just getting a languages raw interface and re-registering the language (which will update it's aliases).

I'm not opposed to a simple registerAlias method though:

```
registerAlias(name, alias|list)
```

I don't think the second form that you support is necessary at all since it seems an edge case and easy enough to write a loop.  And if we added this we'd of course need to add docs for it.

Want to make a PR?

**Comment by wooorm** [comment]
The reason for `registerAlias` as opposed to something else is that it aligns with `registerLanguage`, but I don’t feel strongly about that.

The reason for the other option is so that a module could expose that mapping between highlightjs names and GH aliases as an object, which could be required and then directly passed.

**Comment by yyyc514** [comment]
I don't love `register*` but as you say at least it's consistent. :-)

Sure, but you can write 2 lines of code to use `forEach` to do the same thing... :-)  I just think the core library should provide low-level APIs and integrators build on top of those.  Your library can support the more complex version if you think that's best, and then loop and hook into our lower-level method.

**Comment by yyyc514** [comment]
@wooorm You willing to whip up a PR for this one?

**Comment by wooorm** [comment]
I’m a bit swamped at the moment; if @taufik-nurrohman is interested, I would be grateful!

**Comment by yyyc514** [comment]
Closing as resolved by #2540
