### ISSUE TITLE
(javascript) Incorrect highlight after '/' symbol  

### ISSUE THREAD

**Issue by gdmfilippov** [highlightjs/highlight.js#2530]
**Describe the issue**
In some cases, the highlight is not correct after the '/' symbol.
Bellow is 2 examples.

*Which language seems to have the issue?**
`javascript`

**Are you using `highlight` or `highlightAuto`?**
`highlight`

**Sample Code to Reproduce**
Example 1:
```
const x = `${duration / 1000}`;
func();
```

Example 2:
```
a(b, /.*c.*/);
func();
```

**Expected behavior**
In the example 1, the text after the '/' symbol doesn't change highlight color (including the symbol itself)

In the example 2 highlight after regexp must be correct

**Additional context**
It seems, problem appears in 9.18.1. I can't reproduce the problem with 9.18.2

**Comment by yyyc514** [comment]
> It seems, problem appears in 9.18.1. I can't reproduce the problem with 9.18.2

Please confirm you are actually having this problem with the latest release, 10.0.2.

**Comment by yyyc514** [comment]
If you can test #2531, please do.

**Comment by yyyc514** [comment]
Nope that just shifts it, the problem is that value container and attr container are both fighting for this content...

**Comment by yyyc514** [comment]
Where else is ` ident:`as in `\b[ident][colon]` used in JS other than object keys?  If we just removed the attr container and looked for keys anywhere, what would that break?

**Comment by yyyc514** [comment]
Answer: ternary, lol.

```
key4: false ? undefined : true
```

Right there in the test file too, LOL.

**Comment by yyyc514** [comment]
FYI: Example 1 should not ben an issue in version 10, can you confirm?

**Comment by yyyc514** [comment]
```js
      { // object attr container
        begin: regex.concat(/[{,\n]\s*/,
          // we need to look ahead to make sure that we actually have an
          // attribute coming up so we don't steal a comma from a potential
          // "value" container
          regex.lookahead(regex.concat(
            // we also need to allow for multiple possible comments inbetween
            // the first key:value pairing
            /(\/\/.*\s*)*/,
            IDENT_RE + '\\s*:'))),
```

That's one way to get it done...

**Comment by yyyc514** [comment]
Probably also needs to check multi-line comments.

**Comment by gdmfilippov** [comment]
> FYI: Example 1 should not ben an issue in version 10, can you confirm?

Example 1 has an issue in version 10, but example - not:
Version 9.18.1: https://jsfiddle.net/j35arp2d/11/
Version 10.0.2: https://jsfiddle.net/2us07vdh/1/

> If you can test #2531, please do.
Will try to test in 24 hours

**Comment by yyyc514** [comment]
> Example 1 has an issue in version 10, but example 2 - not:

I see the opposite.  In version 10 example 1 looks great while example 2 is broken.
