### ISSUE TITLE
Propose: Better support Vue simple use cases

### ISSUE THREAD

**Issue by joshgoebel** [highlightjs/highlight.js#2535]
## Vue

The two examples I found fast:

- https://github.com/metachris/vue-highlightjs/blob/master/index.js
- https://github.com/ItsJimi/v-highlightjs/blob/master/index.js

Both use directives... wouldn't you really want a component for this though? What I have so far for Vue:

```html
<highlightjs language="javascript" code="var x = 5;" />
<highlightjs language="javascript" v-bind:code="sourceCode" ignore_illegals />
<highlightjs v-bind:code="sourceCode" />
<!-- or to be explicit -->
<highlightjs auto :code="sourceCode" />
<highlightjs autodetect :code="sourceCode" />
```
Using a slot for passing in code has all the same problems of using a non-PRE tag in HTML and many additional problems so that doesn't seem like a good route, so I've rule that out.

### Vue questions:

- Component vs directive.
- Dash or no dash or is that something that you should configure when you setup the plugin, ie using a custom tag name?
- Would people be expecting to configure the whole library via HTML "attributes" though?  I suppose you could have an options attribute thought that took an object...

**Comment by andrewQwer** [comment]
For React.js I use the following simple wrapper.
I can't use `highlightBlock` as it writes directly to DOM node's innerHTML, that is not React way.

```jsx
import React, { useState, useEffect } from 'react';
import PropTypes from 'prop-types';
import hljs from 'highlight.js/lib/core';
import excel from 'highlight.js/lib/languages/excel';

hljs.registerLanguage('excel ', excel);

const SyntaxHighlighter = ({ sourceCode }) => {
    const [parsedCode, setCode] = useState(null);

    useEffect(() => {
        function highlight() {
            let highlighted = hljs.highlight('excel', sourceCode);
            setCode(highlighted.value);
        }
        highlight(sourceCode);
    }, [sourceCode]);

    return (
        <div>
            <pre
                contentEditable={false}
                className="excel"
                dangerouslySetInnerHTML={{ __html: parsedCode }}
            />
        </div>
    );
};

SyntaxHighlighter.propTypes = {
    sourceCode: PropTypes.string,
};

SyntaxHighlighter.defaultProps = {};

export default React.memo(SyntaxHighlighter);
```

**Comment by yyyc514** [comment]
> I can't use highlightBlock as it writes directly to DOM node's innerHTML

Right, that's clear... support for these type of frameworks is going to be a module/component of whatever that builds on top of the base `highlight` method.  I'd just like to see if *perhaps* we could include the base component to give people a starting place.

**Comment by yyyc514** [comment]
@andrewQwer Moving you to a new React thread so this one can be Vue, probably never should have mixed them.
