### ISSUE TITLE
Excel like parser and keywords highlighting

### ISSUE THREAD

**Issue by andrewQwer** [highlightjs/highlight.js#2539]
I use excel like formula parser and have a similar set of keywords. I slightly adjusted existing excel language parser and added the following mode:

```
keywords: 'IF SWITCH OR AND NOT INT AVERAGE ... etc',
contains: [
           ...,
           {
                
                className: 'field-name',
                begin: /\w/,
                end: /[^\w]/,
                excludeEnd: true,
                relevance: 0,
            },
            ...
```
Usage example: 

`IF(some_field, "yes","no")`

According to this rule any word without whitespace can be treated as class 'field-name'. But in this case keywords are also highlighted by this rule because they match this rule.  What is the best way of prioritizing keywords over modes inside `contains` array?

**Comment by yyyc514** [comment]
Keywords are always processed last - in-between rule matches.  If you need them to instead SUPERCEED other matches then you need to not use `keywords` at all and just make them a manually written rule - and then you are in control of the ordering.  Put it at the top and it will match first.

But realize that rules "eat content" until keywords.  Keywords can match "inside" other matches (even their being/end content), but rules won't share the same space like that.

**Comment by yyyc514** [comment]
Or you could use the new callback `on:begin` to check if the match was a keyword and if so ignore it... that would allow keywords to see it again.  But then you'd need to match `\w+` most likely... and you wouldn't need `end` at all.

**Comment by andrewQwer** [comment]
After trying several solutions I moved these keywords to submodes of the root object and used `beginKeyword` option, so it started detect them first, but field-names that matches keywords names are recognized as keyword now. This is a rare case though and I can live with it :)  
Thank you.

**Comment by yyyc514** [comment]
Yeah beginKeyword works by making keywords their own mode, as I first suggested.  The more elegant solutions is my second suggestion.

> but field-names that matches keywords names are recognized as keyword now

Without more context I'm not sure you can have it both ways.
