### ISSUE TITLE
(javascript) 'get' in identifier highlighted as keyword

### ISSUE THREAD

**Issue by silverwind** [highlightjs/highlight.js#2542]
**Describe the issue**
`get` in a identifier like `getData()` is incorrectly identified as keyword in 10.0.2, which also seems to causes incorrect highlighting on following lines.

Example: https://jsfiddle.net/silverwind/afm4Lzyg/

**Comment by yyyc514** [comment]
Resolved with https://github.com/highlightjs/highlight.js/commit/ba2e65e43f047bd14becc12735d9acbab7c63d4e

Will be in 10.1 or you can build from master.
