### ISSUE TITLE
[Request] OCL language support

### ISSUE THREAD

**Issue by nhomble** [highlightjs/highlight.js#2546]
I followed the language contribution docs and created the extra lib in my own github account [highlightjs-ocl](https://github.com/nhomble/highlightjs-ocl)

I would like to see this added to the supported languages if everything looks good to you!

**Comment by yyyc514** [comment]
There is no `dist` folder making it easy for anyone to drop your language into their own website with one line...

**Comment by yyyc514** [comment]
If you run the build scripts with HLJS they should generate this file for you.

**Comment by nhomble** [comment]
Ah thanks for the advice! @yyyc514
