### ISSUE TITLE
(Dart) Support Dart's new Null Safety type system

### ISSUE THREAD

**Issue by srawlins** [highlightjs/highlight.js#2550]
**Describe the issue**

Dart's new [Null Safety language feature](https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md) introduces some new keywords and a new way to specify types:

* `late` and `required` are new keywords
* `Never` is a new type found in `dart:core`
* (almost) all types can be suffixed with a `?` to indicate a nullable type. For example, in:

  ```dart
  f(int x) { ... }
  g(int? x) { ... }
  ```

  `f` is a function which accepts a non-null `int` parameter, and `g` accepts a nullable `int` parameter.

**Which language seems to have the issue?**

Dart.

**Are you using `highlight` or `highlightAuto`?**

Either.

**Sample Code to Reproduce**

```dart
late int x;
f({required int? y}) {}
const List<Never> z = [];
```

**Expected behavior**

`late` and `required` should be highlighted as keywords. `int?` should highlight the same as `int`. `Never` should be highlighted like the other built-in types.

**Additional context**

**Comment by yyyc514** [comment]
Please add a usage of Never to your sample.

A PR would be welcome.  Tagging this as beginner friendly.

**Comment by srawlins** [comment]
Should the long list of built-in types just be duplicated to include, e.g. `int?`, `String?`, ... or is there a better way?

**Comment by yyyc514** [comment]
Duplication is probably best, but you can do it dynamically with JS... break out the types (or do all the Built-Ins count?) split them, then build a second set with `?` appended, add that to the first...

**Comment by yyyc514** [comment]
You'll need to add `?` to the keyboard $pattern... and is that going to cause any false positives with ternary?

**Comment by yyyc514** [comment]
Does this apply to user types as well? Is so might want to think about making it a mode instead that matches all `[identifier]?`, but again would need to consider false positives.

**Comment by srawlins** [comment]
> Please add a usage of Never to your sample.

Done.

> You'll need to add ? to the keyword $pattern... and is that going to cause any false positives with ternary?

It shouldn't; most Dart code is auto-formatted so that a ternary `?` has whitespace before it.

> Does this apply to user types as well? Is so might want to think about making it a mode instead that matches all [identifier]?, but again would need to consider false positives.

It does, but I think it would be more confusing to match `[identifier]?`, since that would match differently from `[identifier]`.

Although... it is exceedingly common practice to _only_ name types with a leading capital letter (and optional `_`) and to _only_ name variables, consts, fields, methods, etc with a leading lower case letter (and optional `_`); so that might be a nice improvement to make...

**Comment by yyyc514** [comment]
> [identifier]?, since that would match differently from [identifier].

Not sure what you mean?

**Comment by yyyc514** [comment]
@srawlins Any interest in taking a pass at the second part of this?

**Comment by srawlins** [comment]
Sorry, I dropped the thread here. I was getting at the idea that today we don't have any special mode for "types" that would include user types. For example:

```dart
int v1;
UserType v2;
```

`int` is in the list of `built_in`s in `KEYWORDS`, but `UserType` is not, and it matches no other mode. So `int` is highlighted as `hljs-built_in`, and `UserType` is not highlighted at all.

I think this is a fine. If user types should be highlighted separately from, say, functions and variables (e.g. display `UserType` and `v2` in two different ways), that's fine, but I don't think it would be required to close this issue.

I can mail a PR adding `int?` etc to the list of `built_in`s.
