### ISSUE TITLE
(PowerShell) highlight.js cannot render blocks with the "language-*" class

### ISSUE THREAD

**Issue by amyspark** [highlightjs/highlight.js#2557]
**Describe the issue**

highlight.js is unable to render blocks who have the `class="language-powershell"` attribute.
The same block is properly rendered if using the `class="powershell"` alternative.

**Which language seems to have the issue?**

PowerShell.

**Are you using `highlight` or `highlightAuto`?**

No.

**Sample Code to Reproduce**

https://jsfiddle.net/hf7xc03L/

**Expected behavior**

Both blocks are highlighted in the same way.

**Additional context**

N/A.

**Comment by yyyc514** [comment]
Please check the console output:

```
"Could not find the language 'powershell', did you forget to load/include a language module?"
"Falling back to no-highlight mode for this block."
```

In the case "powershell" there is no way to be 100% sure that is a language - since it's not loaded, so it's just finding some other language and using that to highlight.

**Comment by yyyc514** [comment]
Closing as not a bug.
