### ISSUE TITLE
(protobuf) Should highlight multiline comments as comments

### ISSUE THREAD

**Issue by Paxa** [highlightjs/highlight.js#2561]
protobuf supports comments like `/* bla bla */`, but they are not highlighted

<img width="743" alt="Screen Shot 2020-05-17 at 02 20 13" src="https://user-images.githubusercontent.com/26019/82128381-fb240180-97e4-11ea-8ae7-192cc4ddf8ad.png">

https://developers.google.com/protocol-buffers/docs/proto3#adding-comments

**Comment by yyyc514** [comment]
@Paxa Should be a simple one line patch, you up for making a PR?

**Comment by yyyc514** [comment]
Ping. @Paxa

**Comment by Paxa** [comment]
I can try

**Comment by yyyc514** [comment]
Awesome. Looking forward to seeing!
