### ISSUE TITLE
[Request] Support P4 language

### ISSUE THREAD

**Issue by zhankangbao** [highlightjs/highlight.js#2563]
**Is your request related to a specific problem you're having?**
I use Gerrit as Version control system,but it does not support p4 language

**The solution you'd prefer / feature you'd like to see added...**
add support for p4 language

**Comment by yyyc514** [comment]
Please see our documentation for language requests, which covers this and explains why I am closing this issue.

https://github.com/highlightjs/highlight.js/blob/master/docs/language-requests.rst
