### ISSUE TITLE
(Java) cannot reproduce the demo using manual highlight

### ISSUE THREAD

**Issue by wlnirvana** [highlightjs/highlight.js#2566]
**Describe the issue**

I've created a [pen](https://codepen.io/wlnirvana/pen/gOaQqjj) to demonstrate the issue. Note that the angle brackets in `<john.smith@example.com>` and `1 > 5` are rendered incorrectly.

It seems this issue only happens when manually rendering manually with `highlight` and `highlightAuto`. If `initHighlightingOnLoad` is used instead and brackets properly escaped, the issue disappears.

**Which language seems to have the issue?**

Java

**Are you using `highlight` or `highlightAuto`?**

Both.

**Comment by yyyc514** [comment]
This is a mis-understanding of the DOM API. If you want the text of the node you need to use `innerText`, not innerHTML.  If you use innerHTML to retrieve it then you are going to get exactly what it says, the HTML code which is exactly what you wrote... `&gt;`, etc... NOT the actual decoded source.

A correct example:

```
var ele = document.getElementById('code');
ele.innerHTML=hljs.highlight("java", ele.innerText).value;
```
