### ISSUE TITLE
Request: Add a Panda syntax highlighting like CodePen's

### ISSUE THREAD

**Issue by Lo-glitch** [highlightjs/highlight.js#2572]
###### Would appreciate that. ######

**Comment by yyyc514** [comment]
From our documentation:

This is a general answer to requests for adding new languages that appear from
time to time in the highlight.js issue tracker and discussion group.

>    Highlight.js doesn't have a fundamental plan for implementing languages,
    instead the project works by encouraging development of 3rd party language
    grammars from contributors.  We're also happy to host 3rd party language
    grammars at the ``highlightjs`` GitHub organization - no matter how obscure
    or weird.

>    This means that *there's no point in requesting a new language without
    providing an implementation for it*. If you want to see a particular language
    included in highlight.js but cannot implement it, the best way to make it
    happen is to get another developer interested in doing so. See our
    `language-guide`.

If you might be interested in contributing a 3rd party language grammar you can start at: 

https://github.com/highlightjs/highlight.js/blob/master/extra/3RD_PARTY_QUICK_START.md
