### ISSUE TITLE
Why do SQL keywords show up in my compiled javascript?

### ISSUE THREAD

**Issue by raniesantos** [highlightjs/highlight.js#2578]
This is the code I use to register languages.

```js
import hljs from 'highlight.js/lib/core';

[
    'xml', 'css', 'scss', 'javascript', 'json',
    'php', 'php-template', 'apache', 'yaml',
    'markdown', 'handlebars', 'bash', 'shell',
].forEach((language) => {
    hljs.registerLanguage(language, require(`highlight.js/lib/languages/${language}`));
});

hljs.initHighlightingOnLoad();
```

This is a screenshot of the content of the compiled js file.

![Screenshot from 2020-05-26 14-32-41](https://user-images.githubusercontent.com/8528269/82867667-d6a2f480-9f5d-11ea-8481-03cd1d7510c7.png)

**Comment by yyyc514** [comment]
Are you referring to just COMMENT?  Rest of it looks pretty normal to me.

**Comment by yyyc514** [comment]
Wait is that a screen shot of a text editor or how HLJS is highlighting the content? That's unclear from your phrasing.

**Comment by raniesantos** [comment]
2nd is a text editor screenshot.

**Comment by raniesantos** [comment]
Basically, I took a peek at the compiled js and saw that this block of code is there even though I didn't register pgsql.

**Comment by yyyc514** [comment]
We can't highlight SQL if we don't include a list of keywords in the compile Javascript.  That is normal.

**Comment by raniesantos** [comment]
I don't have SQL in the languages I looped through though. Why is that?

**Comment by yyyc514** [comment]
Hard to say.  I'd say you are pulling in the whole shebang somewhere else in your build process.

**Comment by yyyc514** [comment]
Try removing pieces one by one and see if you can find what element is pulling it in.

**Comment by raniesantos** [comment]
Yeah I'll double check later, I'm not at my machine at the moment.

**Comment by yyyc514** [comment]
Sorry for being so spacey at first I didn't read your question clearly. :)

**Comment by raniesantos** [comment]
Removing the loop and having multiple language registration lines fixed it.

But it bothers me that I can't loop this repeating code.

I'm going to try other ways of looping through it for now.

**Comment by yyyc514** [comment]
It's possible your build system can't deal with the dynamic way you're loading that... many of them just statically analyze the code... so you can't "run" a loop during compiling.

**Comment by yyyc514** [comment]
Closing.  Doesn't not seem to be a Highlight.js specific issue (looks like build system issue).  If you learn more, we can re-open.

**Comment by yyyc514** [comment]
If you just want a custom build (in on JS file) you can use the normal build process (see the docs) then you can load that into your build process.

But really writing them out by hand (or writing a program to write them by hand) isn't terrible for a small list.
