### ISSUE TITLE
[Request] Add SPICE (Simulation Program with Integrated Circuit Emphasis) highlight

### ISSUE THREAD

**Issue by pmendessantos** [highlightjs/highlight.js#2588]
**Is your request related to a specific problem you're having?**
I'm thankful for all the work done, but couldn't find the highlighting for this so old and so useful language.

**The solution you'd prefer / feature you'd like to see added...**
I thought maybe it could be possible to adapt the solution from these repos, although they were not designed for your specific language (I think):
.lang type: https://github.com/thomasysliu/Gedit-SPICE-syntax-highlighting
.lang type: https://github.com/abhijit86k/Gedit-SPICE-syntax-highlighting
.xml type: https://github.com/hildogjr/Notepad-plus-plus--languages
.YAML-tmLanguage type: https://github.com/leoheck/sublime-spice
.vim type: https://github.com/1995parham/vim-spice
.json/.cson type: https://github.com/gaku/language-spice
.json/.cson type: https://github.com/timerg/language-spice 

**Any alternative solutions you considered...**
The aforementioned ones are my best shots. Unfortunately, I'm new to this. Meanwhile, I'll try to reach a syntax highlight using .Rmd based solution.

**Additional context...**
That's all for now. Thank you for your attention. Best regards, Patrick.

**Comment by yyyc514** [comment]
From our documentation:

This is a general answer to requests for adding new languages that appear from
time to time in the highlight.js issue tracker and discussion group.

>    Highlight.js doesn't have a fundamental plan for implementing languages,
    instead the project works by encouraging development of 3rd party language
    grammars from contributors.  We're also happy to host 3rd party language
    grammars at the ``highlightjs`` GitHub organization - no matter how obscure
    or weird.

>    This means that *there's no point in requesting a new language without
    providing an implementation for it*. If you want to see a particular language
    included in highlight.js but cannot implement it, the best way to make it
    happen is to get another developer interested in doing so. Here's our
    :doc:`language-guide`.

If you might be interested in contributing a 3rd party language grammar you can start at: 

https://github.com/highlightjs/highlight.js/blob/master/extra/3RD_PARTY_QUICK_START.md

**Comment by yyyc514** [comment]
Doesn't look like a super hard grammar, but someone would need to put in the effort to write a HLJS version.

**Comment by pmendessantos** [comment]
No, it's not hard. Few commands and structures. I don't have any knowledge on .js files an how to pack the solution yet. I was just trying to use the spice highlight inside a webpage I'm building with blogdown in R. I'll try to learn how to do it following the links you've provided. Too many languages...

Thank you for your attention and your time. Best regards, Patrick.
