### ISSUE TITLE
(javascript) Weird font sizes and no indenting

### ISSUE THREAD

**Issue by gunar** [highlightjs/highlight.js#2590]
**Describe the issue**
Weird font sizes and no indenting.

**Which language seems to have the issue?**
JavaScript

**Are you using `highlight` or `highlightAuto`?**
highlight

**Sample Code to Reproduce**
Please check out the problem here: https://gunargessner.com/code-interview

**Expected behavior**
Nice formatting.

![image](https://user-images.githubusercontent.com/7684574/83677651-69820580-a5d4-11ea-8bdf-d0b86830b7b7.png)

Any idea what might be causing this?

**Comment by yyyc514** [comment]
Use chrome developer tools or the whatever equivalent in the browser you’re using. I would imagine you have some CSS that is using the same Class names as highlight JavaScript.

**Comment by yyyc514** [comment]
Your CSS rule:

```
    * {
        font-family: "Open Sans", serif;
    }
```

Is breaking lots of stuff. You're applying YOUR styles after our styles, therefore breaking ours. Simply applying our styles last might resolve a lot.

**Comment by gunar** [comment]
Got it! Thank you very much @yyyc514.

#notabug
