### ISSUE TITLE
[Request] Effective in testing Html, not valid in Gerrit. How do I locate the problem

### ISSUE THREAD

**Issue by zhankangbao** [highlightjs/highlight.js#2591]
highlight.min.js was replaced on lib/highlightjs/，and build a new gerrit.war.but it doesn't work for me
![企业微信截图_20200604104940](https://user-images.githubusercontent.com/39553841/83835031-52e9c480-a722-11ea-8a12-95445c709648.png)
![企业微信截图_20200604105058](https://user-images.githubusercontent.com/39553841/83835033-54b38800-a722-11ea-8e7b-fcd511742049.png)

**Comment by yyyc514** [comment]
What doesn’t work?  Please clearly explain your issue. I don’t know what these are screen captures of.

**Comment by yyyc514** [comment]
Ping.

**Comment by zhankangbao** [comment]
> What doesn’t work? Please clearly explain your issue. I don’t know what these are screen captures of.

I use the Gerrit code review system.
Want to highlight P4 language.
After checking the information, I learned that Gerrit uses highlightjs as a highlighting tool.
I modified the highlightjs project to support p4, include JS in the tested HTML, and display the annotation class='p4', it will be highlighted.
But after replacing highlightjs on Gerrit, the p4 related files are not highlighted, I don't know how to locate this problem.
I tried to remove support for java in highlightjs, packaged Gerrit after deletion, Gerrit did cancel the highlighting of java

**Comment by yyyc514** [comment]
Use ‘language-p4’ instead. See if you have any console errors

**Comment by yyyc514** [comment]
Ping.

**Comment by zhankangbao** [comment]
It may be a problem with the version of Gerrit I use. It currently supports two UIs. Only one of them uses Highlightjs as a highlighting tool. After I put another UI and also support P4 language (using codemirror), Gerrit supports P4. thx

**Comment by yyyc514** [comment]
Glad you got it working.
