### ISSUE TITLE
(csharp) Declaration for generic functions does not highlight

### ISSUE THREAD

**Issue by djoyman** [highlightjs/highlight.js#2596]
**Describe the issue**
Declaration for generic methods does not highlight

**Which language seems to have the issue?**
C#

**Are you using `highlight` or `highlightAuto`?**
highlight

**Sample Code to Reproduce**
<pre><code class="csharp">
  ObjectType FindObject&lt;ObjectType&gt;(
    Criteria criteria
  )
</code></pre>

**Expected behavior**
highlight like visual studio
![image](https://user-images.githubusercontent.com/28087745/84023309-8467c780-a990-11ea-8697-a80f8921b794.png)

**Comment by yyyc514** [comment]
And how are we currently highlighting the same code?

**Comment by djoyman** [comment]
This code is not highlighted at all:

![image](https://user-images.githubusercontent.com/28087745/84039016-4cb94980-a9a9-11ea-965c-7cef783f3132.png)

**Comment by yyyc514** [comment]
Yeah, I don't think templates are supported in function declarations right now at all.

**Comment by yyyc514** [comment]
@djoyman Any chance you want to take a try at making a PR?

**Comment by djoyman** [comment]
Not now, maybe later. If I am going to fix, I will write

**Comment by yyyc514** [comment]
Closing per #2599.  @djoyman
