### ISSUE TITLE
[Request] Adding `record` as keyword to Java

### ISSUE THREAD

**Issue by 0xflotus** [highlightjs/highlight.js#2604]
**Is your request related to a specific problem you're having?**
According to [JEP 359](https://openjdk.java.net/jeps/359) since Java 14 `record` is a new kind of type declaration, so it should be a keyword like `enum`?
Currently `record` is not in the list of keywords in java.js

See https://github.com/highlightjs/highlight.js/blob/b1bce6e3ada485b89696f554878b2ef44a73d94a/src/languages/java.js#L13-L17

**The solution you'd prefer / feature you'd like to see added...**
Adding `record` to list of keywords

**Example Code**

<em>Added by Josh Goebel</em>

```java
record Range(int lo, int hi) {
  public Range {
    if (lo > hi)  /* referring here to the implicit constructor parameters */
      throw new IllegalArgumentException(String.format("(%d,%d)", lo, hi));
  }
}
```

**Comment by yyyc514** [comment]
Sounds right. PR?

**Comment by joshgoebel** [comment]
Probably very similar to https://github.com/highlightjs/highlight.js/pull/2660

**Comment by joshgoebel** [comment]
@0xflotus Can you take a look at this and see what you think?

**Comment by 0xflotus** [comment]
> @0xflotus Can you take a look at this and see what you think?
> ![Screen Shot 2020-09-11 at 10 04 06 AM](https://user-images.githubusercontent.com/6473/92934962-25de3980-f416-11ea-9b70-2b185ce64392.png)

I think it looks right. record as kind of class, similar to enum
