### ISSUE TITLE
[Request] Repo for highlightjs-octave

### ISSUE THREAD

**Issue by apjanke** [highlightjs/highlight.js#2621]
Hi, Highlight.js folks,

I've written a 3rd party language definition for GNU Octave (at https://github.com/apjanke/highlightjs-octave) and I'd like to host this repo under the highlightjs organization. I hope this is the right place to request this.

This is an alternative to https://github.com/highlightjs/highlight.js/pull/2620, which adds an Octave definition to Highlight.js itself. I think maybe doing it as a 3rd party definition would be better, because then it could work with older versions of Highlight.js too, and I could iterate on the definition without having to do PRs to the core `highlight.js` repo?

**Comment by yyyc514** [comment]
>  I think maybe doing it as a 3rd party definition would be better, because then it could work with older versions of Highlight.js too, and I could iterate on the definition without having to do PRs to the core highlight.js repo?

Well, the backwards compatibility will be limited by which features you use - as we do continue to ad new features to newer versions, but for "general" things and simple rulesets backwards compatibility is pretty decent.

**Comment by yyyc514** [comment]
https://github.com/highlightjs/highlightjs-octave

**Comment by yyyc514** [comment]
@apjanke For maximum ease of use you should probably build the `dist` folder that the build process generates for you.

**Comment by apjanke** [comment]
Thanks!

I'm primarily interested in being backward compatible to the version of Highlight.js that Discourse has installed, so we can use it right away, and am willing to restrict myself to whatever features are available in that version of Highlight.js.

**Comment by apjanke** [comment]
> For maximum ease of use you should probably build the dist folder that the build process generates for you.

Will do! This may take me a bit to figure out, because I am a total Node newbie.

**Comment by yyyc514** [comment]
> the version of Highlight.js that Discourse has installed

Do you know what version that is? :-)

**Comment by yyyc514** [comment]
> Will do! This may take me a bit to figure out, because I am a total Node newbie.

If you have your repo in the extra folder (it does not have to be a sub-module or sub-repo or anything, it just has to be there) and build the CDN build then the `dist` folder will be created for you as part of the build process.

**Comment by apjanke** [comment]
> Do you know what version that is? :-)

Umm, they're referencing this commit in their `package.json` file:

```
    "highlight.js": "https://github.com/highlightjs/highlight.js#d72f0817aaab8187711fca7c608f5272ea5147f6",
```

I don't know how to search GitHub to locate a particular commit hash in a project's history though.

**Comment by yyyc514** [comment]
```
commit d72f0817aaab8187711fca7c608f5272ea5147f6 (tag: 9.18.1, upstream/9-18-stable, pp/9-18-stable, hmmwhatsthisdo/9-18-stable, 9-18-stable)
Author: Josh Goebel <me@joshgoebel.com>
Date:   Sat Feb 1 12:43:27 2020 -0500

    release 9.18.1
```

**Comment by apjanke** [comment]
Thanks!

**Comment by apjanke** [comment]
All good. I can push to the new repo. Working on getting the `dist/` stuff set up now. Thanks for your help!
