### ISSUE TITLE
Add cURL grammar

### ISSUE THREAD

**Issue by jf990** [highlightjs/highlight.js#2625]
Proposal to add `curl` grammar to the library.

Implementation is here: https://github.com/jf990/highlightjs-curl

request to move it to the highlightjs org and host it here.

**Comment by yyyc514** [comment]
Could you please add the standard `dist` folder to provide a ready to go CDN module that anyone can easily use without needing to compile anything?

**Comment by jf990** [comment]
@yyyc514 take a look now and let me know if the `dist` folder is what you are expecting. I wasn't exactly sure what the requirements for the distributable are.

**Comment by yyyc514** [comment]
If it's the auto-generated stuff it's perfect. :-)

**Comment by yyyc514** [comment]
https://github.com/highlightjs/highlightjs-curl

**Comment by ZinoKader** [comment]
Issue is closed but I see no pull request - how's this coming along? :)

**Comment by jf990** [comment]
@ZinoKader We have the grammar set up at https://github.com/highlightjs/highlightjs-curl, but I am unsure what the next step in the process is.

**Comment by yyyc514** [comment]
Make a PR to add it to SUPPORTED_LANGUAGES.md.
