### ISSUE TITLE
[Request] Line numbering support

### ISSUE THREAD

**Issue by sbrl** [highlightjs/highlight.js#2628]
**Is your request related to a specific problem you're having?**
When highlighting larger blocks of code that are part of a wider article, it's difficult to refer to a specific line number in the code from the article when the highlighted code block doesn't have line numbers.

**The solution you'd prefer / feature you'd like to see added...**
I suggest adding support for line numbers down the left-hand-side of the code block.

**Any alternative solutions you considered...**
I considered adding some site-specific CSS to do this, but unfortunately the output of highlight.js (or rather [highlight.php](](https://github.com/scrivo/highlight.php/), [ref](https://github.com/scrivo/highlight.php/blob/master/CONTRIBUTING.md#updates-from-highlightjs)) isn't grouped by line - e.g. something like this:

```html
<pre><code>
<span>line 1 text text text text</span>
<span>line 2 text text text text</span>
<span>line 3 text text text text</span>
</code></pre>
```

**Additional context...**
I searched the pre-existing issues, but couldn't find it suggested. I find it very difficult to believe that it hasn't been suggested before, so I'm guessing that I've missed something somewhere.

**Comment by yyyc514** [comment]
https://github.com/highlightjs/highlight.js/blob/master/docs/line-numbers.rst

Answered in the docs. This is pretty easy to do with just HTML and CSS and a small snippet of JS.

**Comment by taufik-nurrohman** [comment]
In progress &rarr; https://github.com/taufik-nurrohman/highlight.ln.js

**Comment by sbrl** [comment]
Ah I see! Thanks for the info @yyyc514. I came here from the website, and did not notice the docs there - otherwise I would have found that.

An interesting point about usability research. If I could think of a suitable and unbiased test, I might be able to carry out such research if I could find some participants lol :P

Either way, the plugin that @taufik-nurrohman links to might do the trick (though I'd have to port it to server-side PHP).

**Comment by yyyc514** [comment]
It's not my philosophy personally as a maintainer (that line #s are evil), but it's so easy to do with a plugin or a small snippet of custom JS that I just don't see any need to add it to the core library.  See the other issue thread about embracing "plugin culture" or making it easy for people to extend without needing to "own" all the extensions ourself.
