### ISSUE TITLE
[Request] Add lang detection API (getLanguageFromCode) without highlighting

### ISSUE THREAD

**Issue by emanuelb** [highlightjs/highlight.js#2630]
Please add API like `getLanguageFromCode(code, languageSubset)` which will work as currently available `highlightAuto(code, languageSubset)` but without the highlighting (will not return `value` which contain HTML string with highlighting markup) thus will run faster and it will be useful for using the auto-detection mechanism.

also support `getLanguageFromCode(code)` which will act as `languageSubset` contain all available/supported languages

**Comment by yyyc514** [comment]
Great idea, though I don't believe it would actually run that much faster (in the real world)... Also, if you really need this behavior you can already achieve it easily enough with a custom emitter (that emits nothing)... so this isn't a feature we need to add to core.

You can find the default tree emitter:

https://github.com/highlightjs/highlight.js/blob/master/src/lib/token_tree.js

**Most importantly we are a highlighter, not a language classifier.**  The core library will stay focused on highlighting.  If you (or anyone else) would like to write a small plug-in that uses our grammars for classification that'd be great - although there also plenty of existing libraries out there that already do classification.
