### ISSUE TITLE
(Python) Better support for Python Type Hints

### ISSUE THREAD

**Issue by Lemmingh** [highlightjs/highlight.js#2633]
## Describe the issue

**Python Type Hints** (PEP 484) has been widely adopted. And many other syntax highlighters, such as [Magic Python](https://github.com/MagicStack/MagicPython), already handle it pretty well.

However, **highlight.js** provides a very limited support according to <https://github.com/highlightjs/highlight.js/commit/07e30ad6f725e2a24193c378ede5e1ff7f0b5b88> which is not useful at all.

## Which language seems to have the issue?

`python`

## Are you using `highlight` or `highlightAuto`?

`highlight`

https://github.com/microsoft/vscode/blob/bbe787ac280cab75002b71460a93ab725d810e80/extensions/markdown-language-features/src/markdownEngine.ts#L330

## Sample code to reproduce

```python
class Solution:
    mapping = None  # type: Dict[int, Any]

    def averageOfLevels(self, root: TreeNode) -> List[float]:
```

## Expected behavior

It would be great to be as good as **Magic Python**:

![](https://magicstack.github.io/MagicPython/example.png)

**Comment by yyyc514** [comment]
Can you be more specific, are you referring to the types in the source code, or the types in the comments - or both?  I think both I'm just wanting to clarify.

https://github.com/highlightjs/highlight.js/commit/07e30ad6f725e2a24193c378ede5e1ff7f0b5b88 would be very easy to extend.

I'd say all of this looks quite possible.  @Lemmingh Interested in working on a PR?

**Comment by yyyc514** [comment]
You'd need to:

- Add a new comment rule to match `# type:` comments, then search for types as keywords
- Expand the return type ` -> ` rule to use the same list of types
- Add these same types to the keywords for the argument list (to avoid mis identifying variable names you might need a more complex rule here to match `:` and end on perhaps `,` or `)` so that only types after a : are matched.

**Comment by Lemmingh** [comment]
> are you referring to the types in the source code, or the types in the comments - or both?

**Both**.
Annotations (the types in the source code) at least.

As you can see, Magic Python and GitHub highlight *function annotations* (PEP 3107) and *variable annotations* (PEP 526), besides, Magic Python highlights *type comments*.

> Interested in working on a PR?

Sorry. I'm afraid I'm a little bit busy this month.

---

Here are a few more complex cases:

```python
mapping = None  # type: Dict[int, Any]

co = None  # type: Coroutine[List[str], str, int]  # Introduced in version K.

u, v, w = [], [], []  # type: List[int], List[int], List[str]
x, y, z = [], [], []  # type: (List[int], List[int], List[str])
a, b, *c = range(5)   # type: float, float, List[float]

stats: ClassVar[Dict[str, int]] = {}  # PEP 526

def average(root: TreeNode,
            depth: int = 2
            ) -> List[float]:
```

**Comment by yyyc514** [comment]
Thanks for more samples!

**Comment by joshgoebel** [comment]
I wonder if some of our "built_ins" should move to "type" such as str, int, etc?

**Comment by joshgoebel** [comment]
<img width="689" alt="Screen Shot 2021-01-13 at 1 56 43 PM" src="https://user-images.githubusercontent.com/6473/104496595-2eeb3d00-55a7-11eb-9762-c4be29c4dc48.png">

**Comment by joshgoebel** [comment]
@Lemmingh Any thoughts?

**Comment by Lemmingh** [comment]
> move to "type" such as str, int

Do you mean to move `complex`, `float`, `int`, `str`, [etc.](https://docs.python.org/3/library/stdtypes.html) from `BUILT_INS` to `TYPES`?

Sounds **nice**.

Looks like this can make your implementation simpler and **clearer**. And generally speaking, "assigning different styles to different kinds of built-ins" itself should produce a good result.

**Comment by joshgoebel** [comment]
In Python (like in Ruby) is it pretty safe to assume by convention that CamelCase named identifiers refer to a class/type?

**Comment by Lemmingh** [comment]
**Probably**. I didn't pay much attention to how others code in Python, only remember to see *few* people break the convention (PEP 8).

Perhaps @yzhang-gh has more experience in it and could help with this.

**Comment by yzhang-gh** [comment]
> In Python (like in Ruby) is it pretty safe to assume by convention that CamelCase named identifiers refer to a class/type?

As far as I can tell, it is true 😉
