### ISSUE TITLE
Doesn't highlight HTML on core

### ISSUE THREAD

**Issue by tyrw** [highlightjs/highlight.js#2635]
When importing the core library, it doesn't seem like basic HTML highlighting is supported.

This results in unhighlighted HTML:

```js
import hljs from "highlight.js/lib/core";
hljs.highlightBlock();
```

This results in an error message because `html.js` is not included in the library:

```js
import hljs from "highlight.js/lib/core";
import hljsHtml from "highlight.js/lib/languages/html";
hljs.registerLanguage("html", hljsHtml);
hljs.highlightBlock();
```

The best we seem to be able to do is xml like this:

```js
import hljs from "highlight.js/lib/core";
import hljsXml from "highlight.js/lib/languages/xml";
hljs.registerLanguage("html", hljsXml);
hljs.highlightBlock();
```

Which of course highlights as XML, not HTML, and misses things like `<script>` blocks.

Is there a way to get the normal HTML highlighting by using the core library instead of the full one?

**Comment by yyyc514** [comment]
`core` contains nothing.  You have to add languages one by one if you use core.   If you want ALL the languages you can load index, see README.

There is "html", it's only an alias to "xml", so loading XML is proper.

`xml` definitely does handle script blocks, etc... if your'e having issues please make a JSFiddle showing them.

You can fork my sample:

https://jsfiddle.net/ajoshguy/2bmdswn6/27/

**Comment by tyrw** [comment]
Thanks for providing the sample.  It looks like there is some discrepancy between the CDN files and the NPM ones.

This one shows no highlighting of the JS inside the script tag:

https://codesandbox.io/s/musing-keldysh-vho37?file=/src/index.js

**Comment by yyyc514** [comment]
>  It looks like there is some discrepancy between the CDN files and the NPM ones.

There is no "core" for CDN, it would make no sense, instead you get a common set of bundled languages.

> This one shows no highlighting of the JS inside the script tag:

It can't highlight JS if you haven't loaded the `javascript` syntax.  Load the `javascript` language also and it'll work just fine.

Closing as resolved.

**Comment by tyrw** [comment]
It would be helpful to have this behavior documented somewhere since it's non-obvious that you have to load both `html` and `javascript` when using core, but only have to load `html` when using CDN.

**Comment by yyyc514** [comment]
> non-obvious that you have to load both html and javascript when using core

You have to load any language you want first to highlight it. You can't highlight javascript without loading javascript. About XML needing JS to highlight embedded JS... I'm not sure where to document that or perhaps it already is. If you have a specific suggestion please share. 

> but only have to load html when using CDN. 

Untrue. XML and Javascript are both built in to the common CDN build. You don't have to load anything else. Perhaps I'm misunderstanding you. 

> Also, that you can't load html with import since that one doesn't exist, but instead have to namespace it from xml manually.

I think this is pretty clear in our list of supported languages. If you have an idea how to make it clearer let us know...
