### ISSUE TITLE
highlight.js 10.1.1 (0f5c28a4) cannot work in IE11

### ISSUE THREAD

**Issue by LittleNewton** [highlightjs/highlight.js#2637]
Hi, I am developing a small **plugin/Add-in** for Microsoft Word.

## **I need a code highlighter**
I want to develop a new code highlighter by myself. After several days' attempt, I find it was so difficult to support multi language and multi styles. 

So I turned into highlight.js. After 3 days learning about JS and HTML, now I can read and edit the developer.html by myself. I have develop a very simple but nice JS highlighter using **highlight.js**.

However, the Win Form's webBrowser object in .Net was awful. I cannot call my JS code from C# easily. After a lot of browsing on google, it turned that the built-in webBrowser class in C# was the same as IE11 so it cannot support the newer JS.

My code: https://github.com/LittleNewton/Equation_and_Codebox

You can see my JS file in `src/highlight/` folder and the main JS function is in `callee.html`.

`callee.html` work very well in Chromium Edge browser. However when I open the HTML file in IE11, exception occured.

```
SCRIPT1002: syntax error
highlight.js (31,3)
SCRIPT5009: “hljs” was undefined
callee.html (32,4)
```

callee.html was showed like below:

``` HTML
<!DOCTYPE html>
<html lang="en">
<head>
	<meta http-equiv="X-UA-Compatible" content="IE=11">
	<meta charset="utf-8">
	<title>Callee</title>
	<link rel="stylesheet" href="./vs.css">

	<style>
		body {
			padding: 0px;
			font-family: sans-serif;
		}
		.editor textarea {
			display: block;
			width: 100%;
			height: 30em;
		}
		pre code,
		pre output {
			display: block;
			padding: 0px !important;
		}
	</style>

	<script src="./highlight.js"></script>
	<script>
		// 1. 高亮函数
		function HighlightCode(language, source) {
			var editor = document.getElementById("myEditor");
			var source = document.getElementById("mainTextArea");
			var result = hljs.highlight('cpp', source.value, true);
			// var result = hljs.highlight(language, source, true);
			document.getElementById("codes").innerHTML = result.value;
		}

		// 2. 以元素 ID 为选择器，将内容复制到剪贴板
		function CopyToClipboard(element) {
			var doc = document
			, text = doc.getElementById(element)
			, range, selection;

			if (doc.body.createTextRange) {
				range = doc.body.createTextRange();
				range.moveToElementText(text);
				range.select();
			} else if (window.getSelection) {
				selection = window.getSelection();
				range = doc.createRange();
				range.selectNodeContents(text);
				selection.removeAllRanges();
				selection.addRange(range);
			}
			document.execCommand('copy');
			window.getSelection().removeAllRanges();
		}

		// 3. 点击按钮的综合行为
		function DoAllActions() {
			HighlightCode();
			CopyToClipboard('codes');
		}
	</script>
</head>
<body>
	<div class="editor" id="myEditor">
		<textarea id="mainTextArea"></textarea>
		<p><button id="btn_Highlight_and_Copy" onclick="DoAllActions()">渲染代码并将其复制到剪贴板</button></p>
		<pre><code class="hljs" id='codes'>渲染后的代码</code></pre>
	</div>
</body>
</html>
```

**Comment by yyyc514** [comment]
https://github.com/highlightjs/highlight.js/issues/2501

We don't support IE 11 anymore. Too old. 


You could try version 9 which still worked with 11.
