### ISSUE TITLE
It won't highlight on QtWebkit

### ISSUE THREAD

**Issue by beckorz** [highlightjs/highlight.js#2638]
**Describe the issue**
QtWebkit engine (e.g. [wkhtmltopdf](https://wkhtmltopdf.org/)) is not highlighted in the browser.
(The environment is Windows 10 Pro)

This may not be a bug in highlight.js, but in the QtWebkit engine.

**Sample Code to Reproduce**

```bat
wkhtmltoimage https://highlightjs.org test.png
wkhtmltopdf https://highlightjs.org test.pdf
```

![test.png](https://user-images.githubusercontent.com/790009/88477182-ce286380-cf78-11ea-988f-f407ba591e07.png)

**Additional context**
- The same thing happened with the other QtWebkit browsers, Midori (v0.5.11).

**Comment by yyyc514** [comment]
What version of Javascript does QtWebkit support?  Does it include all the new ES6 stuff and ES2018 stuff that's in most modern browsers?

**Comment by yyyc514** [comment]
```
% wkhtmltoimage  --debug-javascript  https://highlightjs.org test.png                                           2.7.1
Loading page (1/2)
Warning: https://highlightjs.org/static/highlight.site.pack.js:6 SyntaxError: Parse error
Warning: https://highlightjs.org/:10 SyntaxError: Parse error
Rendering (2/2)
Done
```

Likely that QtWebkit doesn't support all features of modern Javascript that most browsers do these days.  If someone wanted to build a better test case (without a packed lib) and get a line number that would tell us exactly what.

**Comment by beckorz** [comment]
Thanks for the reply.

The Qt engine in wkhtmltopdf seems to use 4.8.
One possible factor is that the Qt engine is an older version and may not be able to support it.
If you look at https://en.wikipedia.org/wiki/Qt_version_history, it is not modern. It seems to be a factor that the version of ECMAScript supports the older version with it.

In addition, I used "highlight.js" for the code highlighting part using wkhtmltopdf in markdown to pdf.
The highlighting is fine for Chrome and Firefox.
highlight.js is very useful.

Thank you for being able to isolate the cause of the problem.

**Comment by yyyc514** [comment]
If you are building your own project you could try version 9, which does work in some older browsers (IE11) - though I can't speak for QtWebkit... but yeah it sounds like this is a ECMAScript issue with Qt just not supporting the more modern stuffs.

**Comment by beckorz** [comment]
In fact, I've been aware of the lack of support for highlight.js since v9.

If wkhtmltopdf can get wkhtmltopdf to adopt v5 of the Qt engine, it still seems to be a possibility, so I'd like to check with wkhtmltopdf as well.

Thanks for the confirmation.
(Now it looks like it would be good to have something from the Chronium engine, not QtWebkit, since the Chronium forces are strong.)

**Comment by yyyc514** [comment]
Feel free to share anything useful you learn!
