### ISSUE TITLE
Not found hljs.vuePlugin reference in index.d.ts. 

### ISSUE THREAD

**Issue by simuhunluo** [highlightjs/highlight.js#2647]
I try to use it in my Vue project. This morning I found out that the Vue component was updated, so I cloned master branch and built it myself, but the API (hljs.vuePlugin) was not found in index.d.ts, so I want to ask for help , Where is the problem? 

 Screenshot below:
![image](https://user-images.githubusercontent.com/22125687/89491100-0897c900-d7e1-11ea-8edf-09dbcf1d0959.png)

@joshgoebel 

By the way, do you need Chinese Readme Doc, I'm glad to do this translation.
> Because I am not a professional front-end developer, but a server-side developer, so I don't know much about it.

**Comment by simuhunluo** [comment]
> I try to use it in my Vue project. This morning I found out that the Vue component was updated, so I cloned master branch and built it myself, but the API (hljs.vuePlugin) was not found in index.d.ts, so I want to ask for help , Where is the problem?
> 
> Screenshot below:
> ![image](https://user-images.githubusercontent.com/22125687/89491100-0897c900-d7e1-11ea-8edf-09dbcf1d0959.png)
> 
> @joshgoebel
> 
> By the way, do you need Chinese Readme Doc, I'm glad to do this translation.
> 
> > Because I am not a professional front-end developer, but a server-side developer, so I don't know much about it.

**Comment by simuhunluo** [comment]
![image](https://user-images.githubusercontent.com/22125687/89491557-1bf76400-d7e2-11ea-99c5-3c6644599984.png)

When I use it, it will give such a tip

**Comment by joshgoebel** [comment]
Ah we need to add that. :-)

**Comment by joshgoebel** [comment]
Give it another shot now from master!

**Comment by simuhunluo** [comment]
Thanks for your help !

**Comment by anrananran** [comment]
missing vuePlugin on NPM, has the latest version been published? In my project
```javascript
vue.runtime.esm.js?0261:5106 Uncaught TypeError: Cannot read property 'install' of undefined
```

**Comment by joshgoebel** [comment]
There has not been a release yet. You'll have to build from source if you want to use the new Vue stuff now.

**Comment by zymergen-stian** [comment]
Could you please make a release soon? I find it very confusing that the feature is advertised in README but not actually shipped (or in this case, included in built bundle)
