### ISSUE TITLE
[Request] (typescript) Do not require downstream users to add "dom" to their TS lib declaration

### ISSUE THREAD

**Issue by Gerrit0** [highlightjs/highlight.js#2648]
**Is your request related to a specific problem you're having?**

[TypeDoc](https://typedoc.org/) uses highlight.js to highlight code samples in documentation, I recently tried to upgrade from version 10.0.0 to 10.1.2. Between these versions, the typings were changed to use `HTMLElement`, which is only defined if the downstream user's tsconfig specifies "dom" in their lib declaration. Since TypeDoc runs purely in node, without access to the browser API, I shouldn't need to specify this.

```
node_modules/highlight.js/types/index.d.ts:12:31 - error TS2304: Cannot find name 'HTMLElement'.

12     highlightBlock: (element: HTMLElement) => void
                                 ~~~~~~~~~~~

node_modules/highlight.js/types/index.d.ts:118:31 - error TS2304: Cannot find name 'HTMLElement'.

118 type HighlightedHTMLElement = HTMLElement & {result?: object, second_best?: object, parentNode: HTMLElement}
                                  ~~~~~~~~~~~

node_modules/highlight.js/types/index.d.ts:118:97 - error TS2304: Cannot find name 'HTMLElement'.

118 type HighlightedHTMLElement = HTMLElement & {result?: object, second_best?: object, parentNode: HTMLElement}
 ```

**The solution you'd prefer / feature you'd like to see added...**

Fixing this should be relatively easy. TypeScript doesn't have [forward declarations for types](https://github.com/microsoft/TypeScript/issues/31894) yet, but the `declare global` with an empty interface should work in this case.

**Any alternative solutions you considered...**
For now, I've pinned the version to 10.0.0, but would like to be able to upgrade.

**Comment by joshgoebel** [comment]
Should we add lib to our compile options, would that help at all?  I'm not certain since we only use TS for linting and not for compiling the actual project.

```
"compilerOptions": {
        "lib": [
            "es2016",
            "dom"
        ]
```

> For now, I've pinned the version to 10.0.0, but would like to be able to upgrade. 
> which is only defined if the downstream user's tsconfig specifies "dom" in their lib declaration. 

So to be clear you're saying you're *choosing* not to upgrade because you don't want to add `lib` to your own declaration?

> Since TypeDoc runs purely in node, without access to the browser API, I shouldn't need to specify this.

I find this irrelevant.  There is only a single compiled library.  The HTMLElement it refers to is indeed the DOM's HTMLElement whether or not you use that code or not - and it's certainly possible on the server-side with JSDOM, etc (though I'm not sure why one might do that outside of testing).

It seems the "correct" solution here (if available) would me for us to add an "include" or some such to our type file to say that we need to pull in the "dom" types and that what we refer to in the file are indeed dom types... is there some way to do this?

**Comment by Gerrit0** [comment]
> Should we add lib to our compile options, would that help at all? I'm not certain since we only use TS for linting and not for compiling the actual project.

This won't have any effect, your config only<sup>1</sup> affects type checking within your project.

> So to be clear you're saying you're choosing not to upgrade because you don't want to add dom to your own declaration?

Yes. "dom" should only be necessary for TypeScript projects which will be run within a browser (unfortunately, it is also required for some JSX targets... but that's not an issue here). If a project which only runs on Node adds "dom" to its config, then it opens up the possibility of accidentally using browser APIs without TypeScript warning that they do not exist.

> It seems the "correct" solution here (if available) would be for us to add an "include" or some such to our type file to say that we need to pull in the "dom" types and that what we refer to in the file are indeed dom types... is there some way to do this?

The old way, which I was familiar with, was to make a global declaration that would be merged with the official dom types. Apparently, since TS 3.0, there is a better way of doing this using [triple slash directives](https://www.typescriptlang.org/docs/handbook/triple-slash-directives.html#-reference-lib-). I tested locally, and it seems to work properly.

```ts
/// <reference lib="dom" />
```

With this line included, TS users with "dom" in their lib declaration will see no difference, while users without it will be able to compile without adding it. It does not prevent the following edge case, if "dom" is not included, but this appears to be the norm for projects which require dom nodes for some functions.

```ts
import * as H from 'highlight.js'
H.highlightBlock({}) // no error if "dom" is not in lib, but will error if it is
```


---
<sup>1</sup> This isn't quite true, if a library uses `esModuleInterop`, it effectively forces all users to also include that option... but I believe it is true for every other option.

**Comment by joshgoebel** [comment]
> I tested locally, and it seems to work properly.

Could you make a PR please?
