### ISSUE TITLE
(parser) continueScanAtSamePosition can break highlighting if no other matches are found

### ISSUE THREAD

**Issue by pkaminski** [highlightjs/highlight.js#2649]
**Describe the issue**
When accessing a reflected class object using `.class`, a string following it doesn't get highlighted as such.

**Which language seems to have the issue?**
java

**Are you using `highlight` or `highlightAuto`?**
highlight

**Sample Code to Reproduce**
For example, `ImmutablePair.of(stuff, "bar")` works fine, but `ImmutablePair.of(Stuff.class, "bar")` doesn't highlight `"bar"` as a string.  There's a live repro using highlightjs 10.1.2 here:  https://jsfiddle.net/chmxa1ze/

**Expected behavior**
The string should be highlighted as such.

**Additional context**
This may be related to #2428 and/or its fix.

**Comment by joshgoebel** [comment]
Yikes. :-/

**Comment by joshgoebel** [comment]
What do you think about https://github.com/highlightjs/highlight.js/pull/2650?

**Comment by pkaminski** [comment]
Not sure if "you" meant me above, but if so I'm the wrong person to ask.  :)  I only have surface knowledge of language definitions, and no idea at all about the engine itself.

**Comment by pkaminski** [comment]
@joshgoebel I don't think this is quite fixed yet.  The specific repro I posted above is now working, but this one is broken:  https://jsfiddle.net/zxbtunvy/1/  Could you please have one more go at it?  Thanks!

**Comment by joshgoebel** [comment]
Related: https://github.com/highlightjs/highlight.js/pull/2678
