### ISSUE TITLE
(php) Support indented heredoc closing marker

### ISSUE THREAD

**Issue by oadam** [highlightjs/highlight.js#2651]
Indented closing markers are [valid in heredoc strings since PHP version 7.3
](https://laravel-news.com/flexible-heredoc-and-nowdoc-coming-to-php-7-3)

Here is a fiddle that reproduces the issue : https://jsfiddle.net/ywhrtvzo/
The string mode should end at the second `EOTEXT` marker

I've checked the code to see if I could fix it myself, and the [END_SAME_AS_BEGIN](https://github.com/highlightjs/highlight.js/blob/a010c151328b8944a7a03e5335956de8baf63295/src/lib/modes.js#L157) used in the ruby language for heredoc seems very promising, but I was not able to figure out how to adapt the php mode.
If I understand it well, a capturing group in the `begin` regex could be used for the `end` matching, which would be perfect !

**Comment by joshgoebel** [comment]
> If I understand it well, a capturing group in the begin regex could be used for the end matching, which would be perfect !

Yes, the first capture group in both the being and end is what is used by default with END_SAME_AS_BEGIN... looks like it'd be a fairly straight forward PR.

You'd just need to add the match groups and remove the `^` from the end regex.

We've a love a PR!

**Comment by eytienne** [comment]
I am working on a PR but sadly, it is not as simple as you said, look at the this for the details : https://wiki.php.net/rfc/flexible_heredoc_nowdoc_syntaxes
It will need a bit of custom code, but maybe I am confusing an highlighter with a parser.

**Comment by joshgoebel** [comment]
What seems to be the problem?  We just have to match the beginning and ending.  We already do it for "normal" heredocs (although poorly since we're not even making sure the end tag matches, etc).

So you just need to edit the `end` rule to match ANYWHERE (not just at the start/end of a line) and then use a END_SAME_AS_BEGIN to make sure the end is the same as the beginning...

If you make a PR of what you have so far I can take a look.

**Comment by eytienne** [comment]
#2658

**Comment by eytienne** [comment]
I followed your advice, I was too focused on the rfc but we only need the level of precision of an highlighter.

**Comment by eytienne** [comment]
Closed by #2658
