### ISSUE TITLE
enh(objective-c ) add `objective-c++` alias

### ISSUE THREAD

**Issue by rene-aguirre** [highlightjs/highlight.js#2652]
Thanks for this project!

This is a simple request: use existing `objective-c` syntax highlighting also for `objective-c++`

`objective-c++` (mm file extension files in xcode projects, supports `objective-c` and `c++` semantics) could be supported as an alias to existing `objective-c`, while not ideal this might be good enough for most cases.

New proposed aliases:
* `objective-c++`
* `obj-c++`
* `objc++`

References to other highlighters with `objective-c++` support:
 * https://pygments.org/docs/lexers/
 * kde editor objective-c++ definition: https://invent.kde.org/frameworks/syntax-highlighting/-/blob/master/data/syntax/objectivecpp.xml

Thanks in advance :-)

**Comment by joshgoebel** [comment]
I'd be open to a PR adding:

- objective-c++
- obj-c++

To `cpp` I am assuming?

**Comment by rene-aguirre** [comment]
No @joshgoebel , actually to `objective-c`

**Comment by rene-aguirre** [comment]
src/languages/objectivec.js

These are the current ones:
```
 aliases: ['mm', 'objc', 'obj-c'],
```

**Comment by joshgoebel** [comment]
Ah, yes duh... PR please. :)

**Comment by joshgoebel** [comment]
Ping. Would you be able to make a quick PR for this?
