### ISSUE TITLE
TypeError: hljs.SHEBANG is not a function

### ISSUE THREAD

**Issue by amits97** [highlightjs/highlight.js#2654]
I started getting this error in my application once I updated to highlight.js 10.1.2.

```
TypeError: hljs.SHEBANG is not a function
javascript
node_modules/highlight.js/lib/languages/javascript.js:269
  266 | name: 'JavaScript',
  267 | aliases: ['js', 'jsx', 'mjs', 'cjs'],
  268 | keywords: KEYWORDS$1,
> 269 | contains: [
      | ^  270 |   hljs.SHEBANG({
  271 |     binary: "node",
  272 |     relevance: 5
```

I'm using `react-lowlight` to do code highlighting. This is the code I have in my project:

```js
import React from 'react';
import PropTypes from 'prop-types';
import Lowlight from 'react-lowlight';
import shallowCompare from 'react-addons-shallow-compare';
import js from 'highlight.js/lib/languages/javascript';
import nginx from 'highlight.js/lib/languages/nginx';

Lowlight.registerLanguage('js', js);
Lowlight.registerLanguage('nginx', nginx);

var createReactClass = require('create-react-class');
const CodeBlock = createReactClass({
    displayName: 'CodeBlock',
    propTypes: {
        value: PropTypes.string,
        language: PropTypes.string,
        inline: PropTypes.bool
    },

    shouldComponentUpdate(nextProps, nextState) {
        return shallowCompare(this, nextProps, nextState);
    },

    render: function() {
        let language = 'js';
        if(this.props.value && this.props.value.length > 0) {
            language = this.props.language;
        }

        return (
            <Lowlight
                language={language || 'js'}
                value={this.props.value || ''}
                inline={this.props.inline}
            />
        );
    }
});

export default CodeBlock;
```

I had to downgrade to highlight.js 10.0.2 to get my application to work.

**Comment by joshgoebel** [comment]
![Screen Shot 2020-08-14 at 6 16 19 PM](https://user-images.githubusercontent.com/6473/90296716-45effc80-de5a-11ea-9bc4-3ed9676e57d5.png)

I'm open to a JSFiddle reproducing this outside your environment, but testing with 10.1.2 here I see no issues.

**Comment by joshgoebel** [comment]
I'd suggest this is very likely an upstream issue with Lowlight as SHEBANG is kind of new feature.  If you can provide a JS Fiddle reproducing this with ONLY HLJS then we can always reopen this.

Closing as this is a Lowlight issue, not HLJS.

**Comment by wooorm** [comment]
@amits97 Can you provide an example of the input text?

Can you confirm whether this is a problem without react-lowlight? It might be that. Or indeed, lowlight?

**Comment by joshgoebel** [comment]
A full stack trace might help also.

**Comment by amits97** [comment]
Here is the stack trace

```
javascript.js:269 Uncaught TypeError: hljs.SHEBANG is not a function
    at javascript (javascript.js:269)
    at High.registerLanguage (core.js:118)
    at Function.push../node_modules/react-lowlight/src/Lowlight.js.Lowlight.registerLanguage (Lowlight.js:70)
    at Module../src/renderers/code-renderer.js (code-renderer.js:8)
    at __webpack_require__ (bootstrap:784)
    at fn (bootstrap:150)
    at Module../src/containers/NewPost.js (NewPost.css?c4da:45)
    at __webpack_require__ (bootstrap:784)
    at fn (bootstrap:150)
    at Module../src/Routes.js (App.js:164)
    at __webpack_require__ (bootstrap:784)
    at fn (bootstrap:150)
    at Module../src/App.js (App.css?4433:45)
    at __webpack_require__ (bootstrap:784)
    at fn (bootstrap:150)
    at Module../src/index.js (index.css?f3f6:45)
    at __webpack_require__ (bootstrap:784)
    at fn (bootstrap:150)
    at Object.1 (serviceWorker.js:135)
    at __webpack_require__ (bootstrap:784)
    at checkDeferredModules (bootstrap:45)
    at Array.webpackJsonpCallback [as push] (bootstrap:32)
    at main.chunk.js:1
```

Sorry, I could not get a JSFiddle up, this is my code: https://github.com/amits97/amitsn-blog/blob/master/src/renderers/code-renderer.js

**Comment by amits97** [comment]
![screencapture-localhost-3000-blog-how-to-generate-a-sitemap-for-your-react-website-with-dynamic-content-2020-08-17-15_21_28](https://user-images.githubusercontent.com/1595593/90449971-652a9c00-e09d-11ea-8d8d-1364b8eaef3b.png)

**Comment by joshgoebel** [comment]
And what versions of all these libraries?  Are you somehow using a newer version of Highlight.js with an older version of Lowlight?  That's not gonna work.

**Comment by wooorm** [comment]
I do not get a problem for the reduced example on `lowlight@1.14.0` (latest on npm) and `highlight.js@10.1.2` (latest on npm):

```js
var low = require('./lib/core')
var nginx = require('highlight.js/lib/languages/nginx')

low.registerLanguage('nginx', nginx)

low.highlight('nginx', 'qwerty')
```

(using `javascript`/`js` works fine too)

---

@amits97 This is 99% an issue with react-lowlight not getting in update in the last three years, and defining a peer dependency of [hljs@9](https://github.com/rexxars/react-lowlight/blob/451786039f4d572f48fdfa3889b676b7ca721257/package.json#L53). Different package managers deal with peer deps differently, so you might have luck a) getting react-lowlight to update (probably takes a while as it is abandoned), b) switching from npm to yarn or vice versa, c) clearing package locks and reinstalling.
