### ISSUE TITLE
(handlebars) block `if` and `else` render strangely

### ISSUE THREAD

**Issue by chriskrycho** [highlightjs/highlight.js#2659]
**Describe the issue**

The current syntax for Handlebars is broken for fairly normal Glimmer templates, e.g. block `if` statements.

**Which language seems to have the issue?**

`hbs`

**Are you using `highlight` or `highlightAuto`?**

`highlight`

**Sample Code to Reproduce**

```
{{#if this.userData.isLoaded}}
  {{this.userData.value.userName}}
{{else if this.userData.isError}}
  Whoops, something went wrong!
{{/if}}
```

Here’s how it renders on my blog:

<img width="593" alt="code example from Chris Krycho’s blog" src="https://user-images.githubusercontent.com/2403023/90522722-4eca2200-e129-11ea-9691-6dc1dfea4afc.png">

**Expected behavior**

- values and keywords should be highlighted distinctly
- values should be highlighted consistently

Here’s how GitHub highlights the same (it’s not great, but it’s definitely *better*):

```hbs
{{#if this.userData.isLoaded}}
  {{this.userData.value.userName}}
{{else if this.userData.isError}}
  Whoops, something went wrong!
{{/if}}
```

**Additional context**

In general, Glimmer templates likely need their own syntax definition at this point, but we can come back to that later (we need to do some work on the Ember/Glimmer side first, I think).

**Comment by joshgoebel** [comment]
@nknapp Any thoughts?

**Comment by joshgoebel** [comment]
I'd say this rule needed to be extended to allow for the possibility of `else if`

```
      {
        className: 'template-tag',
        begin: /\{\{(?=else\}\})/,
        end: /\}\}/,
        keywords: 'else'
      },
```

Care to take a pass at a PR?

**Comment by chriskrycho** [comment]
Sure! Thanks for digging up that rule, that should make it pretty straightforward!

**Comment by joshgoebel** [comment]
Any interesting in trying to make a PR?

**Comment by chriskrycho** [comment]
I am! Apologies for the delay here. I will try to get to this and polish up the other PR I have open sometime in the next couple days.

**Comment by thomasmichaelwallace** [comment]
@chriskrycho - would you mind if I took this off you, I've hit this exact problem and will need to patch our build, so I might as well share that; unless you've started already?

**Comment by thomasmichaelwallace** [comment]
☝️ this is the patch I ended up using; obviously I won't be offended if you ditch my PR because something else was in the pipeline.

**Comment by chriskrycho** [comment]
I haven’t gotten there; I’m glad someone else did!
