### ISSUE TITLE
(C++) Bare open braces generating incorrect HTML

### ISSUE THREAD

**Issue by jshagam** [highlightjs/highlight.js#2662]
**Describe the issue**

When there's a bare open brace on a line by itself, it gets some invalid HTML.

**Which language seems to have the issue?**

C++

**Are you using `highlight` or `highlightAuto`?**
`highlight`

...

**Sample Code to Reproduce**

```javascript
hljs = require('highlight.js');
content = `
#include <iostream>
#include <conio.h>
#include <stdlib.h>
using namespace std;

int main()
{
	char name[50];
	cout << "What is your name, warrior?" << endl;
	cin.getline(name, 50);
	cout << "You better move fast, " << name << ". The goblins are attacking the city." << endl;
	cout << "\\n----------------------Press any key to continue----------------------" << endl;
	_getch();
	return 0;
}
`;
console.log(hljs.highlight('c++', content).value);
```

Resulting output, on highlight.js 10.1.2:

```html
<span class="hljs-meta">#<span class="hljs-meta-keyword">include</span> <span class="hljs-meta-string">&lt;iostream&gt;</span></span>
<span class="hljs-meta">#<span class="hljs-meta-keyword">include</span> <span class="hljs-meta-string">&lt;conio.h&gt;</span></span>
<span class="hljs-meta">#<span class="hljs-meta-keyword">include</span> <span class="hljs-meta-string">&lt;stdlib.h&gt;</span></span>
<span class="hljs-keyword">using</span> <span class="hljs-keyword">namespace</span> <span class="hljs-built_in">std</span>;

<span class="hljs-function"><span class="hljs-keyword">int</span> <span class="hljs-title">main</span><span class="hljs-params">()</span>
</span>{
	<span class="hljs-keyword">char</span> name[<span class="hljs-number">50</span>];
	<span class="hljs-built_in">cout</span> &lt;&lt; <span class="hljs-string">&quot;What is your name, warrior?&quot;</span> &lt;&lt; <span class="hljs-built_in">endl</span>;
	<span class="hljs-built_in">cin</span>.getline(name, <span class="hljs-number">50</span>);
	<span class="hljs-built_in">cout</span> &lt;&lt; <span class="hljs-string">&quot;You better move fast, &quot;</span> &lt;&lt; name &lt;&lt; <span class="hljs-string">&quot;. The goblins are attacking the city.&quot;</span> &lt;&lt; <span class="hljs-built_in">endl</span>;
	<span class="hljs-built_in">cout</span> &lt;&lt; <span class="hljs-string">&quot;\n----------------------Press any key to continue----------------------&quot;</span> &lt;&lt; <span class="hljs-built_in">endl</span>;
	_getch();
	<span class="hljs-keyword">return</span> <span class="hljs-number">0</span>;
}
```

**Expected behavior**

Note the line which is `</span>{` -- it should be just `{`.

**Additional context**

**Comment by jshagam** [comment]
Never mind, I see what's going on - there's an extra layer of nesting on the `<span class="hljs-function">`, which is what's getting closed at the start of the new line. Where this was causing problems is I am splitting the output string into an array based on newlines, so that I can add some per-line markup for formatting purposes. I'll look for an alternate approach to this.

**Comment by jshagam** [comment]
In this case it actually is affecting my visual output, since I'm using CSS counters to number lines and in a context where I don't have complete control over the input, and the only way I could figure out to do that consistently was with some annoying hacks that involve `display:table` and the like. It was working great until I ran into this spot where highlight.js was splitting a token across multiple lines. :)

**Comment by jshagam** [comment]
What's the rationale for having a multi-level nesting on some token types? For example, in the above, having `function` wrapping the `keyword`, `title`, and `params` tokens. This seems unnecessary, and I can't think of any context in which I'd want to have different highlight rules for a keyword when it's inside a function declaration vs. inside a code statement, for example.

I very much want to be able to split the highlight.js output line-by-line, and having tokens nest when some can span multiple lines makes this quite difficult without doing an extra layer of HTML parsing and manipulation.

Thanks!

**Comment by joshgoebel** [comment]
>In this case it actually is affecting my visual output

Your output, not ours. ;-)  The easiest way to add lines (if you don't need to wrap) is just with a second block you position right next to the first and put the line numbers there.


What's the rationale for having a multi-level nesting on some token types? For example, in the above, having function wrapping the keyword, title, and params tokens. This seems unnecessary, and I can't think of any context in which I'd want to have different highlight rules for a keyword when it's inside a function declaration vs. inside a code statement, for example.

_It's just the way our parser works._  Some themes might want to highlight the whole function header differently, etc.

> I very much want to be able to split the highlight.js output line-by-line, and having tokens nest when some can span multiple lines makes this quite difficult without doing an extra layer of HTML parsing and manipulation.

Lots of things can span multiple lines (comments, strings, etc) so this is a problem you have to deal with in any case.  You may want to look at the tree representation of the data and use that instead to render your own HTML.

**Comment by jshagam** [comment]
Ah, multi-line comments are a fair point that I hadn't considered. That makes sense.

>  The easiest way to add lines (if you don't need to wrap) is just with a second block you position right next to the first and put the line numbers there.

Yeah, this is probably what I'll do, although it would be nice to have wrapping work correctly. I was hoping to make my solution as pure-CSS as possible but that's something for another day.
