### ISSUE TITLE
(javascript) some content trigger regexp catastrophic backtracking 

### ISSUE THREAD

**Issue by jiaoyin** [highlightjs/highlight.js#2664]
**Describe the issue**
Using highlightBlock API in the web editor, some content similar to the following will make the browser unresponsive. After analysis, such content may trigger a disastrous regular expression backtracking

**Which language seems to have the issue?**

javascript

**Are you using `highlight` or `highlightAuto`?**
use highlightBlock actually uses highlightAuto

**Sample Code to Reproduce**
<pre id="test"><code> 
///////////////////////////////////////// 长连接按照 ServiceID 分开用不同的类处理 ///////////////////////////////////////////

@protocol HTSWebSockectServiceHandler 

- (void)handleWithPushMessage:(PushMessageBaseObject * _Nonnull)frame;

@end

/// 
@interface HTSWebSockectServiceCommonHandler : NSObject
<
HTSWebSockectServiceHandler
>

@end

///
@interface HTSWebSockectServiceGeckoHandler : NSObject 
<
HTSWebSockectServiceHandler
>

@end

/// Add More...

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
<code><pre>

 hljs.highlightBlock(document.querySelector('#test'));

**Expected behavior**

Although the code is not actually javascript, I hope to highlight the corresponding keywords correctly, at least not to block the browser.

**Additional context**
version 10.1.2
javascript language actually use regexp is  `const  reg = /(^#![ ]*\/.*\bnode\b.*)|(^\s*['"]use (strict|asm)['"])|(')|(")|(html`)|(css`)|(`)|(\/\/)|(\/\*\*)|(\/\*)|(\b(0[bB][01]+)n?)|(\b(0[oO][0-7]+)n?)|((-?)(\b0[xX][a-fA-F0-9]+|(\b\d+(\.\d*)?|\.\d+)([eE][-+]?\d+)?)n?)|([{,\n]\s*(?=(((\/\/.*)|(\/\*(.|\n)*\*\/))\s*)*[A-Za-z$_][0-9A-Za-z$_]*\s*:))|((!|!=|!==|%|%=|&|&&|&=|\*|\*=|\+|\+=|,|-|-=|\/=|\/|:|;|<<|<<=|<=|<|===|==|=|>>>=|>>=|>=|>>>|>>|>|\?|\[|\{|\(|\^|\^=|\||\|=|\|\||~|\b(case|return|throw)\b)\s*)|(\b(function)(?=\b|\s))|(\$[(.])|(\.\s*[a-zA-Z_]\w*)|(\b(class)(?=\b|\s))|(\b(constructor)(?=\b|\s))|((get|set)\s+(?=[A-Za-z$_][0-9A-Za-z$_]*\())|(#(?!!))/gm`
reg.exec above content can reproduce

**Comment by egor-rogov** [comment]
Looks like the same as #2656. Has been fixed recently in #2657.

**Comment by joshgoebel** [comment]
Will try to push a new release this week.
