### ISSUE TITLE
IE11 Syntax Error

### ISSUE THREAD

**Issue by Mcdonamj087** [highlightjs/highlight.js#2665]
I seem to be getting a Syntax Error in IE11 off of a fairly simple implementation (see below):

<img width="479" alt="Screen Shot 2020-08-25 at 4 42 15 PM" src="https://user-images.githubusercontent.com/17895186/91230873-f16a3e00-e6f1-11ea-86af-de4ff8d5e416.png">

Here are the screenshots of the errors, which I know won't be of much help (i'm using BrowserStack on Mac).  

<img width="423" alt="Screen Shot 2020-08-25 at 4 40 18 PM" src="https://user-images.githubusercontent.com/17895186/91231225-810fec80-e6f2-11ea-9069-4e9d77f3f5f1.png">
<img width="1041" alt="Screen Shot 2020-08-25 at 4 40 09 PM" src="https://user-images.githubusercontent.com/17895186/91231238-853c0a00-e6f2-11ea-875e-2886a22c2f09.png">

We use Webpack and Babel with browserslist config: 

"browserslist": [
    "> 1%",
    "last 2 versions",
    "IE 11"
  ]

Not sure what else to do :(.  Everything works fine in Chrome, Safari, Firefix, Edge.  It's just IE11.  I have verified if i remove the import, scripts written after Highlight.js will run again.

Here is a live page where you can find the error:  https://www.dropbox.com/lp/developers/reference/dbx-file-access-guide.  

Let me know if i can provide any further info!  Really appreciate any sort of help you can provide here!!

**Comment by GuoweiYangGitHub** [comment]
I also encountered the same problem.

**Comment by joshgoebel** [comment]
IE11 is no longer supported. https://github.com/highlightjs/highlight.js/blob/master/VERSION_10_BREAKING_CHANGES.md
