### ISSUE TITLE
Request for repository for Raku

### ISSUE THREAD

**Issue by finanalyst** [highlightjs/highlight.js#2666]
I've read the documentation for starting a new language definition.
I've consulted with others in the Raku  community, and hope to get some help going forward.

I plan to set up Raku (aka Perl 6) initially based on the Perl language definition, but it will have three sublanguages for the Raku braids of Regex, POD6 and the quoting constructs.

I can be reached to my email: rnhainsworth (at sign) gmail etc

**Comment by joshgoebel** [comment]
https://github.com/highlightjs/highlightjs-raku

You've been invited.
