### ISSUE TITLE
(shell) Shell tokenization doesn't treat hyphens as parts of words

### ISSUE THREAD

**Issue by sirosen** [highlightjs/highlight.js#2668]
**Describe the issue**

I've run into a case similar to #1740 and other issues. In my case, we had `--enable-foo` on our site, and highlightjs thinks that `enable` is a keyword.

**Sample Code to Reproduce**

<details><summary>minimal full reproduction</summary>

```html
<!DOCTYPE html>
<html lang="en">
<head>
<link rel="stylesheet"
      href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.2/styles/github.min.css">
<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.2/highlight.min.js"></script>
</head>
<body>

<pre class="highlightjs highlight"><code data-lang="sh" class="language-sh hljs">--enable-https</code></pre>

<script>hljs.initHighlightingOnLoad()</script>

</body>
</html>
```

</details>

**Expected behavior**

In this specific case, highlightjs shouldn't treat `enable` as a keyword. More generally, when parsing shell scripts, I believe that `-` should be considered a "word character".
I'm aware from reading previous issues that when this comes up there's hesitance to try to do much with the bash parsing unless someone is ready to write a real parser. But I think hyphenate commands and options are a common case. Even if there are cases this might start to fail on which worked before (I can't think of any, but maybe that's my limited imagination), they're probably much more exotic than `--set-foo`, `--enable-bar`, and, `cmd-case-while-blahblahblah`.

**Additional context**

I'm okay with the idea of highlightjs closing out this issue if it's just too much the same as its predecessors.

If backwards compatibility is a major concern, perhaps this could be an option which is set by the user somehow?
`hljs.SetParserOption("shell", "hyphens-are-wordchars")`? (I have very little notion of how highlightjs works on the inside and how configurable the parsers are or ought to be by design.)

**Comment by joshgoebel** [comment]
I'd be open to a patch with a few tests that changes the keyword $pattern to include "-" which I think would resolve this for most common cases... and we'll see if it conflicts with any existing tests or edge cases.

It looks like perhaps we already do this for "." and "_"... since none of our keywords have . or _ in them.

@sirosen Want to make PR? :)

**Comment by sirosen** [comment]
I can try to take a crack at it, but I warn you that I have very little JS background! 😄
