### ISSUE TITLE
(css) Nesting Function-Like Bug

### ISSUE THREAD

**Issue by taufik-nurrohman** [highlightjs/highlight.js#2674]
**Describe the issue**

Pattern like `rgb(var(--r), var(--g), var(--b))` does not count the first `var()` as another CSS function.

**Which language seems to have the issue?**

`css`

**Are you using `highlight` or `highlightAuto`?**

`highlight`

**Sample Code to Reproduce**

~~~ .css
body {
  text-align: left;
  font-size: 16px;
  background: linear-gradient( var(--black), var(--white) );
  color: rgb(var(--r), var(--g), var(--b));
}
~~~

https://jsfiddle.net/f27o1gyt/

**Comment by joshgoebel** [comment]
If anyone wants to take a pass at this it should be built on top of our long lived CSS branch:

https://github.com/highlightjs/highlight.js/tree/css_consistency

**Comment by khamer** [comment]
Here's a PR that addresses this. It's not my favorite implementation even though it's only a single line of code, but it does effectively support FUNCTION_LIKE having a self-reference as a 'grandchild.' I played around with trying to flatten this structure, but ran into issues with `url()`.

**Comment by joshgoebel** [comment]
@taufik-nurrohman I think this is fixed now in all the CSS grammars.  Could you please confirm when you have time?

**Comment by taufik-nurrohman** [comment]
Will reopen this when there is a bug.
