### ISSUE TITLE
(Fortran) FORTRAN 77 style comments

### ISSUE THREAD

**Issue by interkosmos** [highlightjs/highlight.js#2677]
**Describe the issue**
Two comment styles are supported, old `C` (FORTRAN 77) and new `!`. Syntax starting with `C`/`c` in column 1 are treated as comments. The `^C` comment indicator should be better replaced with `^C ` (appended whitespace) as a workaround.

**Which language seems to have the issue?**
Fortran.

**Are you using `highlight` or `highlightAuto`?**
`highlight`

**Sample Code to Reproduce**
```fortran
module test
    implicit none
    public :: foo
contains ! <-- is treated as comment because of `c` in first column
    function foo()
        integer :: foo
        foo = 1
    end function foo
end module test
```

**Expected behavior**
Syntax starting with character `c` should not be treated as comments.

**Additional context**
The comments in `fortran.js` are defined as:

```js
  const COMMENT = {
    variants: [
      hljs.COMMENT('!', '$', {relevance: 0}),
      // allow Fortran 77 style comments
      hljs.COMMENT('^C', '$', {relevance: 0})
    ]
  };
```
Perhaps, it is sufficient to replace `^C` with `^C ` or `^C\s`.

**Comment by joshgoebel** [comment]
Longer discussion: https://github.com/highlightjs/highlight.js/issues/2310

The space variant doesn't work because evidently `C====` is a style some use... and one could imagine other variants... perhaps `\b` would be better... but would anyone use `CCCCCCC`?

This is hard because really these should likely be two separate languages, not one.

Are you perhaps someone with a deep understanding or Fortran and the various commenting styles someone uses within the scope of the actual rules?

**Comment by interkosmos** [comment]
I agree, it’s a tricky question. Perhaps, it is better to split between FORTRAN 77 and modern Fortran, and remove the `C` comment indicator entirely. I’ll try to work on `fortran77.js` language configuration file in near future.

**Comment by joshgoebel** [comment]
@interkosmos Would you want to make a PR where we extend this to `C\s` and see how it goes?  I'm not opposed to trying it.

>  I’ll try to work on fortran77.js language configuration file in near future.

Would it be that different from Fortran 90?  Are these really two entirely different langauges?

**Comment by interkosmos** [comment]
> Would you want to make a PR where we extend this to C\s and see how it goes? I'm not opposed to trying it.
Yeah, why not.

> Would it be that different from Fortran 90? Are these really two entirely different langauges?
FORTRAN 77 is written in fixed-source format, with the first six columns of a row being reserved for comments, format descriptors, line break indications, and so on. Fortran 90 changed to free-source format, without such restrictions.

**Comment by joshgoebel** [comment]
> FORTRAN 77 is written in fixed-source format, with the first six columns of a row being reserved for comments, format descriptors, line break indications, and so on. Fortran 90 changed to free-source format, without such restrictions.

Sounds about like my understanding... but *for highlighting purposes* how are they any different other than the ambiguity with comments?

**Comment by interkosmos** [comment]
Yes, I don’t see any edge case at the moment. So, if `^C\s` checks out you would rather keep a single language file?

**Comment by nathanweeks** [comment]
FWIW, in free source form (Fortran >= 90),`call SOME_SUBROUTINE` is also currently treated as a comment when the `call` statement begins in the first column.

**Comment by joshgoebel** [comment]
Pretty sure this also resolves that no?

**Comment by nathanweeks** [comment]
Yes, it seems like it should. Looking forward to seeing it merged!
