### ISSUE TITLE
(C#) Keyword before tuple return type is highlighted as a method name

### ISSUE THREAD

**Issue by Youssef1313** [highlightjs/highlight.js#2681]
**Describe the issue**

![image](https://user-images.githubusercontent.com/31348972/92743289-b2d6b380-f380-11ea-9073-b947eac94ed3.png)

See https://docs.microsoft.com/en-us/dotnet/csharp/discards#tuple-and-object-deconstruction for example.

**Which language seems to have the issue?**

C#

**Sample Code to Reproduce**

```csharp
private static (int, int) GetOriginCoordinates()
{
    return (0, 0);
}
```

**Expected behavior**

static should be highlighted as a keyword (i.e. `hljs-keyword`), not as a function name (i.e. `hljs-title`)

To avoid merge conflicts, this should wait until https://github.com/highlightjs/highlight.js/pull/2679 is merged.

**Comment by IEvangelist** [comment]
I'm assuming that the title mechanism is based on a `RegExp` that scan for the first occurrence on a line with the opening parenthesis `(`.  This would cause the return tuple types to cause any keyword before to be treated as a `hljs-title`, not just `static`.

**Comment by joshgoebel** [comment]
I'd guess `TYPE_IDENT_RE` isn't wide enough to know what a tuple type is.  PR would be welcome. :)

**Comment by joshgoebel** [comment]
Can tuples include other advanced types also such as `Vector<string>[]` or whatever? (I don't know c# types)

**Comment by Youssef1313** [comment]
@joshgoebel Here are some different variations:

```csharp
using System.Collections.Generic;

public class C
{
    private static (int, int) GetOriginCoordinates()
    {
        return (0, 0);
    }

    private static (int X, int Y) GetOriginCoordinates2()
    {
        return (0, 0);
    }
    
    private static Dictionary<string, (int, int)> GetCoordinates()
    {
        return new Dictionary<string, (int, int)>
        {
            { "Origin", (0, 0) },
            { "One_One", (1, 1) }
        };
    }
    
    private static Dictionary<string, (int X, int Y)> GetCoordinates2()
    {
        return new Dictionary<string, (int X, int Y)>
        {
            { "Origin", (0, 0) },
            { "One_One", (1, 1) }
        };
    }
    
    private static (int DivisibleBy, List<int> Numbers) DivisiblesByTwo()
    {
        return (2, new List<int> { 2, 4, 6, 8, 10 });
    }
}
```

**Comment by joshgoebel** [comment]
@joshgoebel Can a tuple include a tuple?

**Comment by Youssef1313** [comment]
@joshgoebel Yes they can be nested to multiple levels.

**Comment by joshgoebel** [comment]
https://github.com/highlightjs/highlight.js/pull/2683/commits/e8eef17183d978f2e0f480ac0636dd8380dbaf4c#diff-8b07d3d641e06fd8cbdabdf8115c0ddeR121

Any other leading keywords I'm not thinking of we should add?

**Comment by Youssef1313** [comment]
`internal` and `protected`.

Pinging @IEvangelist to confirm if I'm not missing any others.

Also this change is for C# not Java

**Comment by IEvangelist** [comment]
How would `async` be treated? Is that something that is separate? It too would be a keyword that is valid before the return type is defined in a method signature in C#. In fact there are lots of modifiers that could appear before the return type:

- `abstract`
- `async`
- `extern`
- `override`
- `unsafe`
- `virtual`

Are these what you're after?

**Comment by joshgoebel** [comment]
> In fact there are lots of modifiers that could appear before the return type:

Why wouldn't we want to add the full list - so they would be detected as keywords and never as the accidental name of a function?

**Comment by joshgoebel** [comment]
@IEvangelist Why would "async" be special?

Again, the context here is "preventing keywords from being falsley detected as name of function"... one easy way to do that (given a finite set) is to just exclude them all and tell it they are modifiers...

**Comment by IEvangelist** [comment]
I guess I was confused by how this all comes together, I'm *not* really sure how it works internally - I was more or less stating that there are additional keywords that come before return types in C#. All of these keywords are already captured in my previously merged PR, so why is this change necessary?

**Comment by joshgoebel** [comment]
Because: 

```
        v ----- this looks TOO much like a function named `unsafe`
private unsafe (int, int) GetOriginCoordinates()
```

So we need a safe list of modifier words to prevent them from being wrongly detected as function names.

**Comment by IEvangelist** [comment]
Ah, ok. Thank you for the added context, that is really helpful. I agree. Then the safe list of modifiers would be something like:

- `abstract`
- `async`
- `extern`
- `override`
- `unsafe`
- `virtual`
- `private`
- `protected`
- `internal`
- `public`
- `static`

What do you think @Youssef1313?

**Comment by Youssef1313** [comment]
> 
> 
> Ah, ok. Thank you for the added context, that is really helpful. I agree. Then the safe list of modifiers would be something like:
> 
>     * `abstract`
> 
>     * `async`
> 
>     * `extern`
> 
>     * `override`
> 
>     * `unsafe`
> 
>     * `virtual`
> 
>     * `private`
> 
>     * `protected`
> 
>     * `internal`
> 
>     * `public`
> 
>     * `static`
> 
> 
> What do you think @Youssef1313?

That list looks great and adds many many that dropped of my mind. Probably add "new" (when used for shadowing base class method) to this list too.
