### ISSUE TITLE
Typescript cannot locate the type information of the core module.

### ISSUE THREAD

**Issue by hallaji** [highlightjs/highlight.js#2682]
Hi there 👋

I'd like to import the core and only necessary language files. I tried as below but then realised that there is something wrong in package regarding typings.

```
import hljs from 'highlight.js/lib/core'
import javascript from 'highlight.js/lib/languages/javascript'
```
```
Could not find a declaration file for module 'highlight.js/lib/core'. 
```

I have not imported the index module i.e. `import hljs from 'highlight.js`. So, typescript can't locate the type information for the core module from a subfolder. I believe the solution might be creating `.d.ts` file for every subfolder and file in your case. 

I quickly fixed this issue locally by creating a `core.d.ts` file under `lib` directory. So, I guess we need to declare the entire API that the library exposes.

**Comment by joshgoebel** [comment]
> I quickly fixed this issue locally by creating a core.d.ts file under lib directory.

Is there any easy way we can tell it that that is essentially the same as importing the whole library at least from a types perspective?

>  I believe the solution might be creating .d.ts file for every subfolder and file in your case.

This isn't going to happen.

**Comment by hallaji** [comment]
Well, really quick solution would be to move/declare your types to `./lib/core.d.ts` and then just reference the core in `./lib/index.d.ts` or do the opposite.

```
highlight.js
├── lib
│   ├── languages
│         └── ...
│   ├── core.d.td
│   ├── core.js
│   ├── index.d.ts
│   └── index.js
```

**core.d.td**
```
declarations here
```

**index.d.ts**
```
/// <reference path="./core.d.ts" />
```

**Comment by joshgoebel** [comment]
```
│   ├── languages
│         └── ...
```

Why include this at all?  No changes need to be made here, correct or no?  Did you include it just for "context"?

**Comment by hallaji** [comment]
You've already declared `languages/*` modules in core. 
Correct, I assume we have to import at least one of the `core` or `index` modules in order to benefit from `highlight.js`. So Typescript will find `languages/*` there.

**Comment by joshgoebel** [comment]
> Of course with this fix "types": "./lib/index.d.ts" in package.json.

And I assume my VS Code "intelligence" for all things type related (even though our project is annotated JS) will continue to just work since I think it's all predicated upon this magic line in package.json, right?

If so I think a PR for this would be more than welcome.

**Comment by hallaji** [comment]
Sure, I will. 
When someone imports the library, `types` in package.json tells the TS compiler where to look for your library’s types. I believe there is nothing to worry about vs intelligence.

**Comment by thealjey** [comment]
you cannot import anything that is in a sub-folder because typescript is not able to locate the type definitions
the only good solution is for the "types/index.d.ts" file to be moved into the root of the project

for now, the only solution that worked for me is a reference comment like this:
```ts
/// <reference path="../../node_modules/highlight.js/types/index.d.ts" />
```

**Comment by joshgoebel** [comment]
I'm just waiting for a simple PR to solve this. @hallaji Made it sound pretty trivial... If someone could provide a small repository test project with steps to reproduce the issue it'd be much easier to test the fix when someone makes a PR. @thealjey IE, if you're saying the proposed fix won't work then having a simple test case would go a long ways toward helping us find a proper fix.

**Comment by joshgoebel** [comment]
> you cannot import anything that is in a sub-folder because typescript is not able to locate the type definitions

Why? Isn't this the whole purpose of `types` in package.json?

> the only good solution is for the "types/index.d.ts" file to be moved into the root of the project

I don't find any improvement after moving the file.

**Comment by joshgoebel** [comment]
I don't understand why this seems to work for faker, but not us:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/a92542482f08238ece6650ccbd68815d5b33a9cd/types/faker/index.d.ts

As far as I can tell we're following the exact same pattern with `declare module`.

**Comment by joshgoebel** [comment]
@hallaji Could not find a declaration file for module 'highlight.js/lib/core'. 

Did you try `npm install @types/highlight.js`?  That fixes the issue for me.

I'm not sure why tsk needs a stub package to work properly though.

**Comment by firelizzard18** [comment]
> Did you try `npm install @types/highlight.js`? That fixes the issue for me.

This does not fix the issue for me. `node_packages/@types/highlight.js` only contains `LICENSE`, `README.md`, and `packages.json`, so adding it shouldn't do anything. The package file doesn't have anything useful in it.

**Comment by joshgoebel** [comment]
`@types/highlight.js` includes a type file that imports then re-exports our own types.

**Comment by firelizzard18** [comment]
I believe you, but the version NPM pulled for me today doesn't:

```shell
# npm install @types/highlight.js

up to date, audited 165 packages in 840ms

17 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
# ls node_modules/@types/highlight.js 
LICENSE       README.md     package.json
```

It may not be what you're looking for as a test case, but I have a pretty simple real-world use case here: https://gitlab.com/ethan.reesor/vscode-notebooks/simple-renderers/-/blob/master/src/highlight/main.ts

The `/// <reference path="..." />` workaround works for me, so I'm not too concerned.

**Comment by joshgoebel** [comment]
DO you need to be inside a TS project or something?  Not sure but I saw this yesterday but today in my test project it works fine:

```
~/w/tmp_app(main|✚3…1) % rm -rf node_modules/@types/highlightjs/           2.7.1
~/w/tmp_app(main|✚3…1) % npm install @types/highlightjs                    2.7.1

added 1 package, and audited 12 packages in 707ms

found 0 vulnerabilities
~/w/tmp_app(main|✚3…1) % ls node_modules/@types/highlightjs/               2.7.1
LICENSE       README.md     index.d.ts    package.json
```

**Comment by joshgoebel** [comment]
```
% npm -v                                           
7.6.3
~/w/tmp_app(main|✚3…1) % tsc -v                                            
Version 4.2.3
```

**Comment by firelizzard18** [comment]
```
% npm -v 
7.6.3
% tsc -v
Version 4.0.5
```

**Comment by firelizzard18** [comment]
OK wow...

```diff
- @types/highlight.js
+ @types/highlightjs
```

As far as I'm concerned, that solves my problem.

**Comment by joshgoebel** [comment]
Oh yikes and that's not even the correct name either.  ugh.  Lets see if I can fix this now. :)

**Comment by joshgoebel** [comment]
@hallaji Please try:

```
npm install @types/highlight.js
npm install @types/highlightjs
```

Right now you should need `highlightjs` but that's incorrect so I'm working to see if we can get the naming fixed.  If I don't hear back from you I will assume this is resolved.

**Comment by joshgoebel** [comment]
>  that solves my problem.

And now I'm even more confused how TS finds the types... does it just load EVERYTHING with `@types` magically regardless of naming?

**Comment by firelizzard18** [comment]
> does it just load EVERYTHING with @types magically regardless of naming?

It must, unless it does something like compare after removing all non-alphanumeric characters. I wonder if Typescript's normal type resolution (`types:` in `package.json`) only works in the simple case of the base import, e.g. `from 'highlight.js'` and not `from 'highlight.js/some/path'`.

Either way, this issue is pretty frustrating (from your perspective) - the `@types` package just imports and reexports HLJS...

```typescript
import highlightjs = require('highlight.js');

export = highlightjs;
```

If that works, why don't the definitions in your package. Maybe this is a `tsc` issue.

**Comment by joshgoebel** [comment]
> I wonder if Typescript's normal type resolution (types: in package.json) only works in the simple case of the base import, e.g. from 'highlight.js' and not from 'highlight.js/some/path'.

Indeed. But seems pretty silly since it's easy to see that the longer strings points into a package and therefore it could use the package type modules to potentially help resolve the reference. Not sure why that would be a bad thing to try.

**Comment by joshgoebel** [comment]
@firelizzard18 @hallaji 

I'm still running this down (to see what we might want to change but seems you can also fix this simply by importing the top-level package) though I'm not sure what _packaging_ implications that might have (if any):

```ts
import 'highlight.js' // this line makes the following line know where the types are
import hljs from 'highlight.js/lib/core'
```

This is really all the `@types/highlightjs` stub is accomplishing anyways.  Right now it seems there should be no `@types` package at all, so in the end there will likely be no @types package to install.  We'll either change our codebase slightly (splitting types into multiple files) or change our guidance to recommend the above or adding us to `typeRoots`.

**Comment by joshgoebel** [comment]
@andrewbranch If we just go ahead and add `core.t.ds` and `common.t.ds`, etc... should those import and re-export types  from `types/index.t.ds`, should `types/index.t.ds` reference core?  or is the top-level typing no longer necessary at that point?  I'm a bit confused on best practices on where the canonical types go.

We have a lot of imports that are effectively the same:

```
import "highlight.js" // full library all grammars
import "highlight.js/lib/core" // just the engine, no grammars
import "highlight.js/lib/common" // engine plus our "common" group of grammars
```

All of these export the same thing: `core`... just the amount of grammars they add vary greatly

**Comment by andrewbranch** [comment]
Yeah, I think importing from index.d.ts would make sense in this case.

**Comment by joshgoebel** [comment]
And index.d.ts can still live in the `types` folder with a reference in package.json `types` then?

**Comment by joshgoebel** [comment]
@andrewbranch Would you mind having a look at https://github.com/highlightjs/highlight.js/pull/3073

Nothing seems to work, or it only half works... I have:

```
import hljs from 'highlight.js/lib/core'
import javascript from 'highlight.js/lib/languages/javascript'

// javascript()
hljs.highlight("test","test")
```

IN a test project but I keep getting:

```
% rsync -r ../highlight.js/build/ node_modules/highlight.js/ && tsc b.ts --strict --esModuleInterop
b.ts:7:24 - error TS7016: Could not find a declaration file for module 'highlight.js/lib/languages/javascript'. '/Users/jgoebel/work/tmp_app/node_modules/highlight.js/lib/languages/javascript.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/highlight.js` if it exists or add a new declaration (.d.ts) file containing `declare module 'highlight.js/lib/languages/javascript';`

7 import javascript from 'highlight.js/lib/languages/javascript'
                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error.
```


I don't understand WHERE it wants the ambient export or what is even loaded at this point (ie I don't know what triggers the ambient exports to "count")... Right now I have the ambient export in BOTH index and core, and still it doesn't work.

**Comment by joshgoebel** [comment]
OK the only way I've gotten it to work so far is:

- index is NOTHING but ambient modules (no top-level declarations other than `declare module`, which means it declares `highlight.js` also...
- core is just `import x from `highlight.js`; export x`

I'll push what I have... is this the right track?

**Comment by joshgoebel** [comment]
@firelizzard18 @hallaji Any chance either of you could test the changes in the linked PR?

**Comment by firelizzard18** [comment]
@joshgoebel It works for `import hljs from 'highlight.js/lib/core'`, though I had to add `build/` to the path in order to use the MR branch directly. `import xml from 'highlight.js/lib/languages/xml'` still does not work unless I create `build/lib/languages/xml.d.ts` as a copy of `core.d.ts`.

**Comment by joshgoebel** [comment]
```
import hljs from 'highlight.js/lib/core'
import javascript from 'highlight.js/lib/languages/javascript'

hljs.highlight("test","test")
```

In my sample project that works.  `core` imports `highlight.js` so the ambient modules should be registered so that the language import works.  Your might not be working because you're adding build.  You need to actually COPY the build into node_modules to properly test it.

**Comment by firelizzard18** [comment]
@joshgoebel When I ran `cp -r /tmp/highlight.js/build ./node_modules/highlight.js`, it worked

**Comment by joshgoebel** [comment]
Sounds about right.  TS is picky. :)

**Comment by joshgoebel** [comment]
Closing via #3073.

**Comment by joshgoebel** [comment]
*sigh* And upon moving all the types into `declare module 'highlight.js' {` now my type checking in VS Code is entirely broken... it no longer "automagically" finds any of the types as it did when they were declared at the top-level of index.d.ts... and that's the only reason I added the types in the first place...

Is there some way to fix this?

**Comment by blujedis** [comment]
FYI setting reference seems to play nice as near as I can tell. 

In my case the file importing core is in src/filename.ts

```ts
/// <reference path="../node_modules/highlight.js/types/index.d.ts" />
import hljs from 'highlight.js/lib/core';
```

From there register your languages:

```ts
import typescript from 'highlight.js/lib/languages/typescript';
hljs.registerLanguage('typescript', typescript);
```
