### ISSUE TITLE
[Request] HLSL and ShaderLab support.

### ISSUE THREAD

**Issue by uGuardian** [highlightjs/highlight.js#2690]
It would be nice to have HLSL support in particular.
It would be especially good for people discussing Unity.

Github highlighting supports both of these, maybe you can pull from there?

**Comment by joshgoebel** [comment]
From our documentation:

This is a general answer to requests for adding new languages that appear from
time to time in the highlight.js issue tracker and discussion group.

>    Highlight.js does not have a fundamental plan for implementing new languages
    - i.e., the core team doesn't usually develop new languages. The core team
    instead focuses on parser development, bugs, and supporting the existing
    languages. They also currently does not have time to review, merge and
    maintain any additional languages (fixing bugs, dealing with issues, etc).

>    Instead, the project works by encouraging 3rd party language grammars from
    contributors willing to help develop and maintain them. We're also happy to
    host those 3rd party language grammars at the ``highlightjs`` GitHub
    organization - no matter how obscure or weird. Or you're wlecome to host it
    yourself - we're still happy to link to it.

>    This means that *there's no point in requesting a new language without also
    providing a 3rd party implementation* (we'll simply close "Please support
    language Xyz" issues with a link to this explanation). If you'd like to see
    a particular language available but cannot implement it, the best way to
    make it happen is to find another developer interested in doing so.

>    For more info on actually developing a language see our :doc:`language-guide`,
    and for information on how to properly package your 3rd party language module
    see :doc:`language-contribution`.

If you might be interested in contributing a 3rd party language grammar you can start at: 

https://github.com/highlightjs/highlight.js/blob/master/extra/3RD_PARTY_QUICK_START.md
