### ISSUE TITLE
FYI: Firefox 80 / macOS / OS X / Source Code Pro font black on dark grey text, incorrect rendering.

### ISSUE THREAD

**Issue by kneufeld** [highlightjs/highlight.js#2694]
This is not a bug or feature request, just a bit of knowledge to maybe help the next person who runs into the same problem as I did...

All of a sudden code snippets on the web had black on dark grey and they were all using highlight.js so I naturally assumed that highlight.js was to blame. It wasn't.

It turns out that if you're using Firefox 80 on OSX with the font Source Code Pro then you'll hit bug

https://bugzilla.mozilla.org/show_bug.cgi?id=1520157

and my original bug:

https://bugzilla.mozilla.org/show_bug.cgi?id=1665427

It turns out that highlight.js is really popular and this bug showed itself all over the place...

Anyhow, feel free to close this, hopefully the google machine will index it soon.

**Comment by joshgoebel** [comment]
Thanks for the info!

**Comment by joshgoebel** [comment]
Will auto-close this in 2021 since there is no action we can take... do they have any plans to fix?
