### ISSUE TITLE
(Mathematica) Anonymous function parameters not highlighted

### ISSUE THREAD

**Issue by b3m2a1** [highlightjs/highlight.js#2695]
Beyond the fact that the Mathematica keywords need a version bump (they're on `12.1`, but it's probably worth waiting for their `12.2` release), the anonymous function syntax isn't being highlighted.

E.g. in Mathematica you can have

```mathematica
Map[# * 2 &, Range[5] + ns]
```

and in this context `#` should be highlighted. Wolfram's "canonical" highlighter will color the `#`, but not the `&`, but also only in the case that `#` is inside the scope of the `&`. 

I don't know how sophisticated highlight.js is, so resolving that kind of scoping question may be outside of its abilities, but if that can be added, it would make Mathematica  highlighting look "right" to people who are used to what WRI provides.

Here's a sandbox to see what WRI does, if that's helpful: https://sandbox.open.wolframcloud.com/app/view/newNotebook?_view=frameless

**Comment by joshgoebel** [comment]
You might have to explain the whole expression first (and how # is an anonymous function), sorry.   Pretend I know nothing about Mathematica.

Typically we do not highlight operators (which is what this looks like at a glance), but I'm open to changing that moving forward, so lets understand how this expression should be understood then see what is possible.

The current mathematica ruleset looks VERY basic.

**Comment by joshgoebel** [comment]
Ping.

**Comment by b3m2a1** [comment]
Yeah I figure it's only possible via parsing, but thought it worth putting out there just in case. There's unfortunately a detailed precedence table that'd be needed to know if `#` should be highlighted or not. The general workaround might be to treat it as punctuation that's always highlighted outside of strings and comments, but not critical enough to really be worth messing with I think.

**Comment by joshgoebel** [comment]
> Yeah I figure it's only possible via parsing,

Quite possible. 

> but not critical enough to really be worth messing with I think.

Closing for now then.
