### ISSUE TITLE
Syntax highlight of C/C++ code blocks in Markdown incomplete #107071 

### ISSUE THREAD

**Issue by arttet** [highlightjs/highlight.js#2696]
**The keywords `final`, `override` are not highlighted.**

https://en.cppreference.com/w/cpp/keyword

**Which language seems to have the issue?**

C++

**Sample Code to Reproduce**

```cpp
class Book final
{
public:
  std::string const& contents();
private:
  std::string contents_;
}
```

![2020-09-19_19-58-21](https://user-images.githubusercontent.com/51746822/93685866-02bd2500-fabb-11ea-9259-dbde7e2d4f91.png)

P.S.  https://github.com/microsoft/vscode/issues/107071

**Comment by joshgoebel** [comment]
Please provide an example that also includes "override".

**Comment by arttet** [comment]
```cpp
class Book final : public IBook
{
  ~Book() override;
public:
  std::string const& contents() const override final;
private:
  std::string contents_;
};
```

![2020-09-19_23-04-29](https://user-images.githubusercontent.com/51746822/93688162-859aab80-facc-11ea-8e55-534d7abc7cbc.png)

**Comment by joshgoebel** [comment]
I see them all highlighted (though final in one place is incorrectly flagged as a name).  Are you sure your highlight.js is setup correctly or is this the issue you were referring to?

![Screen Shot 2020-09-21 at 8 48 09 AM](https://user-images.githubusercontent.com/6473/93768297-31381e80-fbe7-11ea-807b-bf300258d5f4.png)

**Comment by arttet** [comment]
Yes, this is an issue. The word `final` should be a keyword in the first line.

**Comment by joshgoebel** [comment]
"an issue" or the issue here?  If there are additional issues, lets enumerate them please. :)

**Comment by arttet** [comment]
No, we can use only the `final` keyword.
