### ISSUE TITLE
(fsharp) `(*)` operators uncorrected detected as multi-line comment

### ISSUE THREAD

**Issue by Eliemer** [highlightjs/highlight.js#2697]
**Describe the issue**
Using Discord's codeblock i posted a short snippet of F# code in which i used the Operators.(*) function. This led the highlighter to believe that the rest of the codeblock was part of a multiline comment. In F# a multi-line comment is writting with (* Comment Here *). 

**Which language seems to have the issue?**
fsharp and fs both produce this bug.

**Sample Code to Reproduce**
```fsharp
let decimator str =             
    match String.length str with
    | 0 -> ""                   
    | 1 -> str                  
    | len ->                    
        let index =             
            len 
            |> float        
            |> Operators.(*) 0.1          
            |> ceil             
            |> int              
            |> Operators.(+) 1            
            |> Operators.(-) len          
        str.[..index] 
printfn "%A" (decimator "1234567890") // => "123456789"
printfn "%A" (decimator "1234567890AB") // => "1234567890"
printfn "%A" (decimator "123") // => "12"
;;
```

**Expected behavior**
I expect there to be no highlighted comments in this code, aside from the inline comments in the last 3 lines.

**Additional context**

![image](https://user-images.githubusercontent.com/21344441/93733234-9ae20980-fba2-11ea-9fcc-bda1d7be40ca.png)

**Comment by joshgoebel** [comment]
We simply match patterns... can you point me (or explain) F#'s grammar rules here?  I just looked at their own spec and they clearly say `(*` beings a new multi-line comment... they don't seem to show the grammar for the whole top-level (which would be super helpful).

How would we (since we're just pattern matching) know that this is NOT a comment?  How does F#?

**Comment by Eliemer** [comment]
Im pretty new to F# but a multi-line should be like

(*
My comment
*)

With a closing *). I have no idea how F# would distinguish from a
multi-line and say mutliplying twice

1
|> (*) 2
|> (*) 4

Since that does have an apparent closing *).

Idk much more about the language but github seems to highlight it properly
when i wrote it for this issue.

**Comment by joshgoebel** [comment]
Is this a valid comment:

```
(*)
My comment
(*)
```

**Comment by Eliemer** [comment]
It shouldnt be, no. (*) is a function so it should evaluate it. Then try to
evaluate the "My" symbol and throw an error because its not defined
probably.

**Comment by joshgoebel** [comment]
>  If more than one token can match a sequence of characters in the source file, lexical processing always forms the longest possible lexical element.

Ah I think that explains it... So the trick is indeed it needs to be "isolated" so the lexer sees it as it as a comment start/end instead of something else (like a function).

**Comment by joshgoebel** [comment]
@Eliemer Any thoughts on #2704?
