### ISSUE TITLE
(LaTeX) Backslashes should be highlighted as part of the control sequence

### ISSUE THREAD

**Issue by schtandard** [highlightjs/highlight.js#2708]
**Describe the issue**
In LaTeX, backslashes (`\`) are used to denote control sequences like macro names. highlight.js does not include the backslash into the resulting control sequence, i.e. the backslash in `\foo` does not receive the same markup as the `foo` does. This is confusing, because in the language, `\foo` is _one token_, the backslash is not a separate thing. The confusion gets especially bad with the macro `\\`, where highlight.js styles the second backslash differently from the first.

Here are some screenshots showing the issue on the [official demo][demo]:

![demo-output](https://user-images.githubusercontent.com/23075534/94273283-7e4c2580-ff44-11ea-84b4-7a5587b8d4db.png)

[demo]: https://highlightjs.org/static/demo/

**Sample Code to Reproduce**
Here's the code from the demo site:

```latex
\documentclass{article}
\usepackage[koi8-r]{inputenc}
\hoffset=0pt
\voffset=.3em
\tolerance=400
\newcommand{\eTiX}{\TeX}
\begin{document}
\section*{Highlight.js}
\begin{table}[c|c]
$\frac 12\, + \, \frac 1{x^3}\text{Hello \! world}$ & \textbf{Goodbye\~ world} \\\eTiX $ \pi=400 $
\end{table}
Ch\'erie, \c{c}a ne me pla\^\i t pas! % comment \b
G\"otterd\"ammerung~45\%=34.
$$
    \int\limits_{0}^{\pi}\frac{4}{x-7}=3
$$
\end{document}
```

**Expected behavior**
The whole token should be parsed together, i.e. including the leading backslash.

**Additional context**
highlight.js has recently been adopted by the Stack Exchange network. [TeX - LaTeX Stack Exchange][tex.se] has been _the_ place to get support around TeX and TeX-adjacent software. This design decision (I suppose the current behavior is by design) makes reading some of the answers there much harder and I believe the tex.sx community would be very thankful for a change.

[tex.se]: https://tex.stackexchange.com/

**Comment by joshgoebel** [comment]
>  This design decision (I suppose the current behavior is by design)

Well, it's definitely intentional, but I'm not sure I'd say it's "by design"...  At first glance I agree with you completely - and seems we should change this.  I imagine this looks better on some themes than others (and could look amazing if it was subtle) but without forcing a "tag" and "subtle tag" theme design (which we don't) - I can see how this would work pretty poorly a lot of the time - and why treating it as a single unit makes sense.

At best I'd consider our Latex support to be more of a "placeholder" than a real grammar... if someone could help contribute to it that would be great.  This is probably easier to fix than your other issue.

**Comment by egor-rogov** [comment]
I agree we should change it. I use LaTeX and it seems to me we have many things to change in the grammar (I have never used highlight.js for LaTeX and was unaware of the problems).
I'll try to come up with some variant.

**Comment by schtandard** [comment]
@egor-rogov I'm working on a pull request right now, hoping to have a first draft ready later today. If you want, you can wait for that and then provide some feedback.

**Comment by egor-rogov** [comment]
@schtandard Great! I'll take a look as soon as it is ready.
