### ISSUE TITLE
(LaTeX) There is no code highlighting inside braces (most of the time)

### ISSUE THREAD

**Issue by schtandard** [highlightjs/highlight.js#2709]
**Describe the issue**
It seems like braces in LaTeX are treated like string literals by highlight.js, i.e. their content is treated as one group that is highlighted uniformly, regardless of content. This is _not correct_! While braces are an important syntactical element in TeX, their content is normal TeX code, just like outside of braces. They can contain anything that is allowed in the language. Consequently, their content should be highlighted normally.

Since braces are such a frequent occurrence in TeX, this behavior can easily leave half the code that should be highlighted un-highlighted.

Here is a part of the [official demo][demo]. The macros `\eTiX` and `\TeX` in the first line as well as `\!` and `\~` in the last are not recognizable as such. As I said above, syntactically there is no need to treat the content of braces any different from normal code at all.

![output](https://user-images.githubusercontent.com/23075534/94275695-8f4a6600-ff47-11ea-9c51-6eb36cf8e0b2.png)

Here are some examples from [a tex.sx post][tex.sx-post]. Somehow, the behavior is not totally consistent here as some things in the braces are highlighted. It may have something to do with the fact that `\hbox` is a primitive command and may be treated as a "reserved word". However, the same should not be true about `\,`. Maybe it's just a bug in a bug.

![tex.sx-output-1](https://user-images.githubusercontent.com/23075534/94276251-43e48780-ff48-11ea-8f77-0894ff08e374.png)

![tex.sx-output-2](https://user-images.githubusercontent.com/23075534/94276360-6d051800-ff48-11ea-9bf2-0d35838097b0.png)

[demo]: https://highlightjs.org/static/demo/
[tex.sx-post]: https://tex.stackexchange.com/a/22375/48973

**Sample Code to Reproduce**
The code from the demo page (with two more lines than the screenshot in order to complete the `table` and `document` environments):
```latex
\newcommand{\eTiX}{\TeX}
\begin{document}
\section*{Highlight.js}
\begin{table}[c|c]
$\frac 12\, + \, \frac 1{x^3}\text{Hello \! world}$ & \textbf{Goodbye\~ world} \\\eTiX $ \pi=400 $
\end{table}
\end{document}
```

The code from the tex.sx post:
```latex
\newcommand{\opncls}[2]{%
  \ooalign{$#1\subseteq$\cr
  \hidewidth\raisefix{#1}\hbox{$#1#2\mkern.5mu$}\cr}}
```
```latex
$
\mathcal{F}_x:=
  \frac{\bigsqcup\{\mathcal{F}(U);\, x\in U \opn X\}}
  {\exists x\in W \opn U\cap U'\!:s|_W=s'|_W}
$
```

**Expected behavior**
Parse code inside of braces the same as code outside them.

**Comment by joshgoebel** [comment]
At best I'd consider our Latex support to be more of a "placeholder" than a real grammar... if someone could help contribute to it that would be great. 

> Somehow, the behavior is not totally consistent here as some things in the braces are highlighted.

Because we don't support "nesting" of any type... so sometimes the nested `}` will cause the rule to terminate early allowing it to match again... it's not matching "inside" though... it's just the pattern terminating early because we don't handle nesting.  Of course we definitely could... that's what we have "self" for.

If someone would like to pitch in here to help I'd be more than happy to answer any HLJS specific questions about our grammars, etc.

**Comment by schtandard** [comment]
Ok, I will give it a shot.

**Comment by joshgoebel** [comment]
Check out `tools/developer.html`... can be a real help. (you'll need to first build a browser build)

**Comment by egor-rogov** [comment]
At first glance it looks like we should just ignore braces altogether. Just like we ignore parenthesis in expressions in other languages.

**Comment by joshgoebel** [comment]
> At first glance it looks like we should just ignore braces altogether.

Well I thought the goal was to color them like strings or something (in which case we'd have to match them nested, etc)... I don't know LaTex at all...
