### ISSUE TITLE
ScriptError: Data storage error

### ISSUE THREAD

**Issue by viadean** [highlightjs/highlight.js#2710]
"ScriptError: Data storage error",  which occurred and I don't know why?

**Comment by joshgoebel** [comment]
What browser and version?

Will need more context on this one... can you reproduce with jsfiddle or prove this isn't your own JS code causing this issue or give me a line number or which part of the source is throwing the error?

**Comment by viadean** [comment]
Thank you for your email. The issue has been resolved.

**Comment by joshgoebel** [comment]
Care to share the fix?

**Comment by viadean** [comment]
It's not my work for issue, which gets fixed automatically. I don't know
why.
