### ISSUE TITLE
Bug: Building demo with `--no-minify` does not include correct highlight.js

### ISSUE THREAD

**Issue by halirutan** [highlightjs/highlight.js#2711]
When building the demo for local testing/debugging without minifying the js

```
node tools/build.js -t browser --no-minify
```

copying the [demo index.html](https://github.com/highlightjs/highlight.js/blob/master/demo/index.html#L50) does not adapt the included `highlight.min.js` to use the un-minified version.

Would it be possible to make this dynamic so that building and testing work out of the box even for the un-minified version?

**Comment by joshgoebel** [comment]
Perhaps, but minified or not should have zero impact on testing... so I'm wondering if there is really a different problem here...

**Comment by halirutan** [comment]
Yes, I needed to debug it and I thought using the un-minified version is the best approach to see where exactly things go wrong. Is there a better alternative?

**Comment by joshgoebel** [comment]
Sure, we could fix... I thought I fixed this kind of thing long ago, but perhaps that was something different.


But what are you trying to debug exactly though?  _You shouldn't need to live debug the library JS to solve problems with grammars..._

**Comment by halirutan** [comment]
> You shouldn't need to live debug the library JS to solve problems with grammars.

Yep, that is probably my inexperience. I ran into the "0 match" problem you explained somewhere here on GitHub. I wasn't where exactly the problem was so I wanted to look at the compiled regex and what the matcher actually tries to do. So I debugged through the demo-page and inspected the JS objects.

But since you asked: Let's say someone used `regex.join(...)` under the impression that (per default) it really just "joins" regexes and not concatenates them with `|`. This person was sure `join` does the right thing because he has seen `regex.either()` before and though `join` must do the right thing. So the final regex is not what this person assumed.
How would you debug this without actually debugging it and inspecting the final regex that hightlight.js uses? :smile:

**Comment by joshgoebel** [comment]
You mean "'0 width match regex'"?  You have a regex with something optional that can potentially match an empty string... that is a no no because it would lock up the match loop in an infinite loop.   An example is making a regex with ALL components optional:

```
optional(ABC)optional(DEF)
```

_This can match absolutely nothing, which is bad._

---

> So the final regex is not what this person assumed.  How would you debug this without actually debugging it and inspecting the final regex that hightlight.js uses? 😄

Ok you got me. :-)  Guess I'm just too familiar with the internals and helpers.  So 99% of the time it's debugging the grammar itself, not the resulting regexes built with helpers.

> Let's say someone used regex.join(...) under the impression that (per default) it really just "joins" regexes and not concatenates them with |. This person was sure join does the right thing because he has seen regex.either() before and though join must do the right thing

Ah, this issue is documented somewhere... `join` should be renamed with version 11 to avoid this confusion.  It's really more for internal usage by the parser. **Your grammar should not use `join`.**

**Comment by joshgoebel** [comment]
This could be fixed by passing in a flag to `renderTemplate`... if you wanted to make a PR... :-)

**Comment by joshgoebel** [comment]
@halirutan Also I'd suggest using `tools/developer` for debugging, not demo... it also doesn't ahve this problem as it uses the non minified by default. :-)

**Comment by halirutan** [comment]
@joshgoebel Great job. Haven't tried it but I definitely saw your commit that fixed this. Thanks for that!
