### ISSUE TITLE
hljs.COMMENT gives the word 'a' the relevance 1

### ISSUE THREAD

**Issue by schtandard** [highlightjs/highlight.js#2712]
Use of the recommended function `hljs.COMMENT` leads to every occurrence of the word `a` in any comment to be given the relevance 1. I don't see how this makes any sense.

**How to reproduce:**
Create a new language definition file, say `src/languages/test.js`, with the following content:
```javascript
export default function(hljs) {
  return {
    name: 'testlanguage',
    contains: [
      hljs.COMMENT(
        '#',
        '$',
        {
          relevance: 0
        }
      )
    ]
  };
}
```
Next, build using `node tools/build.js -n test` and open `tools/developer.js`.
In the Code field, write
```text
# a
```
A relevance of 1 is displayed.

If you add more `a`s (separated by spaces), the relevance increases accordingly.
Other words do not have this effect (as far as I tried).

**Comment by schtandard** [comment]
After a review of the code, this is clearly by design and supposed to improve language recognition.

**Comment by joshgoebel** [comment]
Correct.
