### ISSUE TITLE
Question: How to implement with vue ?

### ISSUE THREAD

**Issue by iNeoO** [highlightjs/highlight.js#2718]
Hi,
I have a file highlight.js // 10.2.0
```javascript
import Vue from 'vue';
import hljs from 'highlight.js';
import javascript from 'highlight.js/lib/languages/javascript';

hljs.registerLanguage('javascript', javascript);
Vue.use(hljs.vuePlugin);
```
imported in main.js
```javascript
import '@/plugins/highlight';
new Vue({
  render: (h) => h(App),
}).$mount('#app');
```
The component is used in app.vue
```html
<template>
  <div>
    <highlightjs language='javascript' code="var x = 5;" />
  </div>
</template>
```

but i have a hljs is not defined
```
vue.runtime.esm.js?2b0e:1888 ReferenceError: hljs is not defined
    at VueComponent.highlighted (core.js?1020:1242)
    at Watcher.get (vue.runtime.esm.js?2b0e:4479)
    at Watcher.evaluate (vue.runtime.esm.js?2b0e:4584)
    at Proxy.computedGetter (vue.runtime.esm.js?2b0e:4836)
    at Proxy.render (core.js?1020:1271)
    at VueComponent.Vue._render (vue.runtime.esm.js?2b0e:3548)
    at VueComponent.updateComponent (vue.runtime.esm.js?2b0e:4066)
    at Watcher.get (vue.runtime.esm.js?2b0e:4479)
    at new Watcher (vue.runtime.esm.js?2b0e:4468)
    at mountComponent (vue.runtime.esm.js?2b0e:4073)
```

I made a codesandbox https://codesandbox.io/s/relaxed-proskuriakova-e5mt2?fontsize=14&hidenavigation=1&theme=dark

**Comment by joshgoebel** [comment]
```
import hljs from "highlight.js"
window.hljs = hljs
```

Not sure if that helps.  The browser build (build yourself, download from website, or fetch via CDN) is intended to be used in a web browser, not the Node.js build.  The `window.hljs` global needs to be created.

**Comment by joshgoebel** [comment]
Perhaps the Node build should detect the window object and then define `hljs` as well? (though I think most poeple don't expect modules to behave in such a fashion)  I'm not sure since the library has been around a long time and you're the first person to raise this sort of issue.

Perhaps we merely need to update the README to be clearer? Thoughts?

**Comment by iNeoO** [comment]
Hi, hi tried to set up the hljs in the window, but I still had an error. (I'm on holliday and I will be able to test Monday). Yeah update the readme could be a good things

Thx

**Comment by joshgoebel** [comment]
> Hi, hi tried to set up the hljs in the window, but I still had an error.

I'd think perhaps you didn't do it correctly somehow - that is the issue here... that `hljs` isn't defined globaly... if you define it globally (or use the browser build which does this for you) then it will work just fine.

**Comment by iNeoO** [comment]
Ok the second error was mine (value undefined)

**Comment by PlutoZX** [comment]
> I made the error go away with:
> 
> ```
> import hljs from "highlight.js"
> window.hljs = hljs
> ```
> 
> Not sure if that helps. The browser build (build yourself, download from website, or fetch via CDN) is intended to be used in a web browser, not the Node.js build. The `window.hljs` global needs to be created.



> I made the error go away with:
> 
> ```
> import hljs from "highlight.js"
> window.hljs = hljs
> ```
> 
> Not sure if that helps. The browser build (build yourself, download from website, or fetch via CDN) is intended to be used in a web browser, not the Node.js build. The `window.hljs` global needs to be created.

Oh, thank you very much, this worked for me, my Vue project was generated by Vue-cli, I am not sure if this is the cause of the problem, but I did encounter the hsjs undefine error

**Comment by joshgoebel** [comment]
> I am not sure if this is the cause of the problem, but I did encounter the hsjs undefined error

It's because you're using Highlight.js from `npm`.  The Node build is meant to be used on the server-side, not in the browser.  The browser build (which you can build yourself, fetch via CDN, etc...) includes that line, the server build does not.
