### ISSUE TITLE
Error when compiling a language that requires another language

### ISSUE THREAD

**Issue by schtandard** [highlightjs/highlight.js#2725]
**How to reproduce**
Create a language `testa.js`
```javascript
/*
Language: testa
Requires: testb
*/

export default function(hljs) {
  return {
    name: 'testa'
  };
}
```
that requires a language `testb.js`
```javascript
/*
Language: testb
*/

export default function(hljs) {
  return {
    name: 'testb'
  };
}
```
Then compile `testa`
```shell
node .\tools\build.js -n testa
```
You will receive the following messages on the terminal:
```text
Starting build.
Finished build.
... testa requires testb
(node:3900) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'requires' of undefined
    at filter (D:\Projekte\highlight.js_parser\highlight.js\tools\lib\dependencies.js:74:10)
    at Object.buildBrowser [as build] (D:\Projekte\highlight.js_parser\highlight.js\tools\build_browser.js:25:15)
    at async doTarget (D:\Projekte\highlight.js_parser\highlight.js\tools\build.js:87:3)
(node:3900) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:3900) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Trying to use the languages in `tools/developer.html` shows that the compilation indeed did not succeed.

**Comment by joshgoebel** [comment]
No idea without more context.

```
Starting build.
Finished build.
[INFO] Adding testb... testa requires testb.
Writing docs files.
Writing demo files.
Writing style files.
Preparing languages.
..
Building highlight.js.
-----
Core                : 68124 bytes
Languages           : 198 bytes
highlight.js        : 68697 bytes
highlight.js.gz     : 19851 bytes
-----
```

**Comment by joshgoebel** [comment]
Unusual because every language defines `requires`...

**Comment by joshgoebel** [comment]
What version of npm and node.js?

**Comment by schtandard** [comment]
Hmm, strange. I am on Windows 10 and running `npm` version `6.14.6` and `node` version `v12.18.4`.

**Comment by joshgoebel** [comment]
No idea unless you can debug a bit more and maybe find something... `tools\lib\dependencies.js` is a good place to start.

**Comment by joshgoebel** [comment]
Can anyone else reproduce this? @allejo @egor-rogov Either of you on windows?

**Comment by allejo** [comment]
I can replicate this behavior on Windows 10 and Node 13.10.1. I'll take a closer look in the morning

**Comment by joshgoebel** [comment]
@allejo thanks!

**Comment by allejo** [comment]
https://github.com/highlightjs/highlight.js/blob/7905f46f7f6a0bc1361d4f9c59f3b34cde6b303c/tools/lib/language.js#L8-L10

@joshgoebel the problem resides here. It's not picking up the CR in CRLF so the `\r` gets carried over into the language definitions. So in the `filter()` function,

https://github.com/highlightjs/highlight.js/blob/7905f46f7f6a0bc1361d4f9c59f3b34cde6b303c/tools/lib/dependencies.js#L73-L80

it's failing because it's actually evaluating `languages.find((el) => el.name == 'testb\r')` where `el.name = "testb"`.

**Comment by joshgoebel** [comment]
> Adding \r? to those regex solves the problem for me.

Stupid line endings.  Can you make a PR? :-)
