### ISSUE TITLE
(javascript&typescript) Right curly brace inside template literal expression makes highlighter think expression has ended

### ISSUE THREAD

**Issue by cxcorp** [highlightjs/highlight.js#2748]
**Describe the issue**
Right curly braces inside a template literal's expression seem to confuse the highlighter into thinking that the expression has ended, which causes rest of the expression to be highlighted as a string. If the expression after the right curly brace includes a nested template literal, that seems to be treated as the terminator for the parent template literal.

**Which language seems to have the issue?**
`javascript` and `typescript`

**Are you using `highlight` or `highlightAuto`?**
I'm using `highlight`.

**Sample Code to Reproduce**
```js
const foo = tag`hello ${args > 0 ? { foo: 1 } : { bar: 2 }}!`;
const foo = tag`hello ${(args) => (args > 0 ? { foo: 1 } : { bar: 2 })}!`;
const foo = tag`hello ${({ args }) => args.name}!`;
const foo = tag`hello ${({ args: { name } }) => name}!`;

const Button = styled.button`
  background: transparent;

  ${({ primary }) =>
    primary &&
    css`
      background: palevioletred;
      color: white;
    `}
`;
```

This snippet produces the following in Highlight.js 10.2.1 (in [this snippet](https://jsfiddle.net/7uL93kga/4/)):

![image](https://user-images.githubusercontent.com/21111572/95691014-7b2f8580-0c24-11eb-90e3-dd791b78d5c4.png)

**Expected behavior**
This screenshot is from VS Code. Notice how the parts after the right curly brace are correctly highlighted.
![image](https://user-images.githubusercontent.com/21111572/95691021-87b3de00-0c24-11eb-9eed-8c566264f6d8.png)

**Additional context**
While functions are usually pretty rare inside template literals, they're used extensively in e.g. [Styled Components](https://styled-components.com/) which is a popular CSS-in-JS library for React.

**Comment by joshgoebel** [comment]
I don't know about highlighting inline functions, but I do think we can quite easily fix the original bug.  We just need to handle recursive `{}` inside template literal subst blocks.
