### ISSUE TITLE
(C) \ not respected

### ISSUE THREAD

**Issue by QH4OS** [highlightjs/highlight.js#2757]
**Describe the issue**

**Which language seems to have the issue?**

`C`

**Are you using `highlight` or `highlightAuto`?**
`highlight`

**Sample Code to Reproduce**

https://jsfiddle.net/gm16s8nf/
```c
// this is a comment, but since I added a slash, \
this is part of it too
```

**Expected behavior**

In C, a '\\' character extends the current lined (effectively negating the following `\n` )
Since the second line is also part of the comment, it should be highlighted as such.

**Additional context**

**Comment by joshgoebel** [comment]
I would presume this also applies to C++?

**Comment by joshgoebel** [comment]
Now we have the added problem that MANY languages use the common C_LINE_COMMENT_MODE rule... but I'm not sure how many of them support this `\` mechanic... although it does seem like the kind of that that might not hurt anything if it's added to a few more languages than necessary...

**Comment by joshgoebel** [comment]
@QH4OS Is this common though?  I wonder why someone wouldn't use a block comment in that case...

**Comment by joshgoebel** [comment]
@klmr Probably an easy one if you're still wanting to help.

**Comment by klmr** [comment]
It’s more than that: the sequence `\<newline` is replaced by the empty string by the C preprocessor *even inside individual tokens*.

The following program is valid C and prints “`a = "1"`” when executed:

```c
#include <stdio.h>

int main () {
  /\
* this is a comment *\
/
  /\
/ so is this \
and this
  int a = 0;
  a+\
+;
  prin\
tf("a = \"%d\\
"\\
n", a);
}
```

**Comment by joshgoebel** [comment]
HAHAHAHA.

> Handling single-line comments only should be sufficient.

Wholly agree - lets fix the reported problem. :-)  The rest is outside scope.  Do you have any thoughts on negative impact that might have on other languages using the C rule but NOT fully complying?  I'm guessing it would be minimal (or zero impact) and therefore ok to add this to our `C_` modes (esp. since that is their name).

**Comment by klmr** [comment]
Hmmm. `C_LINE_COMMENT_MODE` is used in 65 language definitions. As far as I know (might be wrong), no languages other than C and C++ actually support line continuations though. And while rare I don’t think it’s unthinkable that somebody is using `\` at the end of their line, e.g. as an ornamental border. I think it would be best if we kept `C_LINE_COMMENT_MODE` unchanged and used something different for `c-like`. The name is a bit odd then, but *not really*; these *are* C-style line comments, after all.
