### ISSUE TITLE
(ruby) numeric literals with suffixes (exponent, real, imaginary) not highligted

### ISSUE THREAD

**Issue by joshgoebel** [highlightjs/highlight.js#2766]
**Describe the issue**

In Ruby, float, rational, and complex literals do not highlight the textual portion of the literal. 

```
3.5e4
2r
6i
```

The `e4`, `r`, and `i` remain unhighlighted.

**Which language seems to have the issue?**

Ruby.

**Expected behavior**

The textual portion should also be highlighted as `number`, as the Python grammar and others do.

**Comment by khamer** [comment]
I think I can sort this out - adding support for all of the following:

- 3.5e4, 3.5E4, 1_2.3_4e1_0
- 2r, 1_2.3_4r
- 6i, 1_2.3_4i, 3.5e4i

Doesn't look like ruby supports combining the real number suffix with exponential notation, although it does for imaginary numbers. I also noticed that the existing support for underscores in highlightjs _could_ get a few things wrong, but I don't think it's worth fixing unless you do - stuff like leading/trailing underscores (`1_`, `1_.0`, `1._0`, etc.) That seems like an edge case worth ignoring to keep the regex simpler, but I think I could make a separate regex constant for handling that structure if you'd rather.

**Comment by khamer** [comment]
Let me know if this works or you're looking for something else. Happy Hacktoberfest!

**Comment by joshgoebel** [comment]
@khamer You have more examples here than in your tests! ;-)
