### ISSUE TITLE
Is it possible to prevent highlighting of a specific portion of code?

### ISSUE THREAD

**Issue by romach** [highlightjs/highlight.js#2772]
Is it possible to prevent highlighting of a specific portion of code in the code block?

For example, I have code:

```
<pre>
  <code class="html">
    let a = 1; <span>Without highlight</span>
  </code>
</pre>
```
I want that all content in the `span` tag should be ignored by highlightjs.

**Comment by taufik-nurrohman** [comment]
Add special comment to that tag. Example:

~~~ .html
<span class="hljs-inherit"> ... </span>
~~~

Then using CSS, inherit all styles to the code block:

~~~ .css
.hljs-inherit,
.hljs-inherit span[class] {
  background: none !important;
  font: inherit !important;
  color: inherit !important;
}
~~~

**Comment by joshgoebel** [comment]
@taufik-nurrohman Is that going to work for deeply nested groupings also? 

Roughly:

```
<code>
<function><params/><title class='inherit'></params></function>
</code>
```

Is title going to inherit the style of params or code?  Or the magic trick the full CSS rulle `.hljs-inherit span[class]`?

If so I just learned something new and can't believe I never knew that. :-)

**Comment by joshgoebel** [comment]
But yes this is the only simple way to do anything like that... you manually apply styles to make your code in question look as "reasonable" as possible... if inherit doesn't work than you may need to manually match the CSS theme you are using by hand.

**Comment by taufik-nurrohman** [comment]
@joshgoebel the second selector will inherit each other recursively unless I add `>` between them :)

**Comment by joshgoebel** [comment]
I'm asking about how inherit works... I always thought it inherited from the parent... it doesn't climb the tree to find "code", etc... so I think it's possible your code wouldn't work at all if the parent was not the `code` element.  Am I mistaken?

**Comment by taufik-nurrohman** [comment]
> I always thought it inherited from the immediate parent.

Yes it does.

But imagine this:

~~~ .html
<code class="hljs">
  aaa
  <span class="hljs-inherit">
    <span class>
      <span class>aaa</span>
    </span>
  </span>
</code>
~~~

The `.hljs-inherit` part will have the color from its direct parent which is the `.hljs` element.

The `.hljs-inherit span[class]` will have the same color as `.hljs-inherit` which already inherit to the `.hljs`.

But remember that selectors separated by spaces don&rsquo;t care about leveling. It will match anything below the parent element. So `.hljs-inherit span[class]` will select any `span[class]` element inside `.hljs-inherit` no matter how deep they are.

The case will be different if I use `.hljs-inherit > span[class]` selector. It will not reach other `span[class]` below the first level of `span[class]`.

Another example can be found in common navigation CSS:

~~~ .css
nav ul {}

nav li {
  position: relative;
}

/* sub-menus should be in absolute position */
nav ul ul {
  position: absolute;
  top: 100%;
  left: 0;
}

/* sub-sub-menus should be pushed to the right */
nav ul ul ul {
  top: 0;
  left: 100%;
  /* no need to declare absolute position here */
}
~~~

**Comment by joshgoebel** [comment]
Oh I see now, but this doesn't work because you can't guarantee the placement of the inherit tag... (unless you're very careful)... it could just end up inside it's own tag:

```
<code class="hljs">
  a = "
  <span class="hljs-inherit">
    <span class>
      <span class>aaa</span>
    </span>
  </span>
  "
</code>
```

Now inherit will just be whatever colors a string is because of the `"..."`... Doesn't someone really need to redefine the `hljs` class separate with just the color/background/emphasis and then use that:

```
.hljs-normal span[class] {
  background:#333 !important; /* hard code the theme background */
  color: #eee !important; /* hard code the theme default */
  font-weight: normal; /* hard code the theme default */
}
```

Etc?

**Comment by joshgoebel** [comment]
Your right if you were careful and always placed it at the top-level that would work... there has been talk of adding something like this to the default themes in any case so that a mode could revert to normal text inside of a parent mode...

**Comment by taufik-nurrohman** [comment]
> But this doesn&rsquo;t work because you can&rsquo;t guarantee the placement of the inherit tag.

Ah, I see.

**Comment by joshgoebel** [comment]
Solve the problem how?

**Comment by taufik-nurrohman** [comment]
> It’s used for parsed sections within strings and almost always should be reset to the default color.

https://highlightjs.readthedocs.io/en/latest/style-guide.html#subst

I mean, instead of using `.hljs-inherit`, you could use `.hljs-substr`. So, no need to add custom styles.

**Comment by joshgoebel** [comment]
First of all I don't actually think that's true despite that being in the docs. And secondly "almost always" is not the same thing as "always". 😎￼

**Comment by taufik-nurrohman** [comment]
Okay then.

**Comment by joshgoebel** [comment]
I think there is enough information here to close this.  The simple answer is use CSS to re-style the "unhighligted" portion of the text back to the "default" (which you may need to manually copy from the `.hljs` rule if `inherit` doesn't work for you)
