### ISSUE TITLE
[Proposal] add unpkg cdn

### ISSUE THREAD

**Issue by luiscobits** [highlightjs/highlight.js#2774]
There is a cdn for everything on npm: [unpkg](https://unpkg.com/)

This are some [data](https://twitter.com/mjackson/status/1315718264035573761) from last month:

The past month, http://unpkg.com served
- 50 billion requests
- 2.4 billion unique users
- 550 TB of data
- 99.8% cache hit rate

Since highlight.js can be installed from npm or yarn.

I would like to add instructions to use the cdn in the readme.

**Comment by joshgoebel** [comment]
We have a section for CDNs. 

https://github.com/highlightjs/highlight.js/#cdn-hosted

A PR would be welcome.

**Comment by christyram99** [comment]
Hi @luiscobits , I would like to work on this issue.

**Comment by joshgoebel** [comment]
@chriseidhof Go for it, a simple example like for the other two CDNs is all I think we'd need?
