### ISSUE TITLE
PHP no variable highlighting

### ISSUE THREAD

**Issue by afilina** [highlightjs/highlight.js#2778]
**Describe the issue**
PHP variables are not highlighted. Most of my code snippets are quite unreadable because of that.

**Which language seems to have the issue?**
PHP

**Expected behavior**
(ignore the background)
![image](https://user-images.githubusercontent.com/199835/96727760-6c15a980-1381-11eb-8d0d-c98bd86bf738.png)

**Actual behavior**
![image](https://user-images.githubusercontent.com/199835/96727836-818ad380-1381-11eb-84d6-1302754afbcb.png)

**Additional context**
I can live without semicolons, but variables in PHP are critical.

**Comment by joshgoebel** [comment]
A PR would be welcome, this should be a one line fix.
