### ISSUE TITLE
(llvm) types and blocks are parsed incorrectly

### ISSUE THREAD

**Issue by gnzlbg** [highlightjs/highlight.js#2782]
**Describe the issue**

The LLVM types and blocks are parsed incorrectly.

**Which language seems to have the issue?**
LLVM

**Are you using `highlight` or `highlightAuto`?**
No

**Sample Code to Reproduce**

```llvm
;; foooo
define i32 @mul_add(i32 %x, i32 %y, i32 %z) {
  entry:
    %tmp = mul i32 %x, %y
    %tmp2 = add i32 %tmp, %z
    %tmp3 = add i32 %tmp, 0
    ret i32 %tmp3
}
```

**Expected behavior**
I expect:

- [x] `define` to be a `.hljs-keyword` 
- [ ] `i32` to be a `.hljs-type` (its parsed as a keyword, all types are described here:  https://llvm.org/docs/LangRef.html#type-system)
- [x] `@mul_add` to be a `.hljs-title` (its a function name)
- [x] all the `%...` to be `.hljs-symbol` 
- [ ] `0` to be a `.hljs-literal`
- [x] `mul`, `add`, `ret` to be `.hljs-built_in` or `.hljs-keyword` (these are parsed as keywords)
- [ ] `entry:` is a block, so i'd expect this to be maybe a `.hljs-section` ? not sure 
- [x] `;; fooo` to be a comment

**Comment by joshgoebel** [comment]
Why is 0 a literal and not a number?  `literal` is typically reserved for built-in literal values in a language, ie: `NULL`, `true`, `false`, etc...

Tagging beginner friendly. 

- We don't really match types now at all over than i* (as keyword)... I assume that rule was added to match i32, i8, i64, etc...  so it'd be nice to have an explicit types list (for accuracy if nothing else).  
- For the label I'd suggest `meta` I think. In other languages we use symbol but we're using that for "%identifier"... are these symbols or variables?

**Comment by joshgoebel** [comment]
I see string are permittable (in the grammar)... is an empty string allowed? ie, `""`?

**Comment by joshgoebel** [comment]
Ping.

**Comment by joshgoebel** [comment]
Ping.

**Comment by allejo** [comment]
The closest thing I can find about `0` being a "literal" is when it's preceded by a `!`...? For example, in llvm's ["Module Structure" example snippet](https://llvm.org/docs/LangRef.html#module-structure).

```llvm
; Named metadata
!0 = !{i32 42, null, !"string"}
!foo = !{!0}
```

With PR #2830, I see the following difference in our highlight:

![image](https://user-images.githubusercontent.com/1246453/99038655-b7634800-253a-11eb-9cd0-ff0f8534bc89.png)

**Comment by joshgoebel** [comment]
Thanks for that example. That looks wrong. I’m also not sure I’d call that a literal though. But it seems perhaps the exclamation rule should come before the number rule.

**Comment by allejo** [comment]
Yea, I wouldn't call it a literal either. That usage is the closest thing I could find to it being considered something _other_ than a number.

**Comment by joshgoebel** [comment]
Fixed.
