### ISSUE TITLE
(Javascript) JSX syntax is parsed incorrectly while using `highlight` line by line

### ISSUE THREAD

**Issue by Suevily** [highlightjs/highlight.js#2787]
**Describe the issue**

JSX cannot be parsed as XML syntax correctly while using `highlight` line by line with the fourth parameter `continuation`

**Which language seems to have the issue?**

Javascript or JSX

**Are you using `highlight` or `highlightAuto`?**
I'm using `highlight`

**Sample Code to Reproduce**

```javascript
var result1 = hljs.highlight('Javascript', 'return (', true)
var result2 = hljs.highlight('Javascript', '<div>xxx</div>', result1.top)
```
execute the above code, result2 may be like this:
![image](https://user-images.githubusercontent.com/16059608/97104484-31986d80-16ef-11eb-83ad-9e52f9046b1b.png)
`<div>xxx</div>` has not been parsed as XML, which is unexpected

however, if I call like this:
```javascript
var result3 = hljs.highlight('Javascript', 'return (\n<div>xxx</div>', true)
```
result3 is like this:
![image](https://user-images.githubusercontent.com/16059608/97104557-be432b80-16ef-11eb-9366-19f6fa61580c.png)
`<div>xxx</div>` has been parsed as XML, which is expected

**Expected behavior**

`<div>xxx</div>` can be parsed as XML while using `highlight` line by line with `continuation`

**Additional context**

**Comment by joshgoebel** [comment]
Closing #wontfix.

Please see https://github.com/highlightjs/highlight.js/issues/2259.

_Continuation is simply NOT intended to be used in this fashion._  It's really not intended to be consumed by external users at all, honestly.  In version 11 we may consider removing it from the public API.  It's certainly not intended to drive line by line highlighting.  If you need a line by line optional your best bet is to write a custom Emitter (see `TokenTreeEmitter`) or walk the tree generated by the built-in emitter post generation and build a line-by-line version of the output.  See `_walk`.

Note, this is all private API but expected to be mostly stable in the 10.x series.

**Comment by joshgoebel** [comment]
Related: https://stackoverflow.com/questions/64280814/how-can-i-correctly-highlight-a-line-by-line-code-using-highlight-js-react

**Comment by iamunadike** [comment]
it does not work 
it is always inline and does not break code as expected 
window.addEventListener('popstate', function (event) {// React to the URL change...}); Example this is how it shows up on mine
 
pls fix the issue , the complain is since 2015

**Comment by joshgoebel** [comment]
> This issue was opened in 2020.

No idea what you might be referring to.  This issue was closed as using our library "line by line" is not supported.  If you are reporting a different issue please open a new issue.
