### ISSUE TITLE
js  partial syntax highlighting

### ISSUE THREAD

**Issue by GurovDmitriy** [highlightjs/highlight.js#2789]
**Describe the issue**

js  partial syntax highlighting

**js**

js  partial syntax highlighting

**Are you using `highlight` or `highlightAuto`?**

no

**Sample Code to Reproduce**

no error:
```
  /* svg minify */

  gulp.task('svgMin', function() {
    return gulp.src('source/image/*.svg')
      .pipe(image({svgo: ['--enable', 'cleanupIDs', '--disable', 'convertColors']}))
      .pipe(gulp.dest('source/image'));
  });
```
error:
```
  /* svg sprite end inject */

  gulp.task('svgSprite', function() {
    const svgs = gulp.src('source/image/*.svg', {base: 'source/image'})
      .pipe(rename({prefix: 'icon-'}))
      .pipe(svgstore({inlineSvg: true}));

    function fileContents(filePath, file) {
      return file.contents.toString();
    }

    return gulp.src('source/**/*.html')
      .pipe(inject(svgs, {transform: fileContents}))
      .pipe(gulp.dest('source'));
  });
```
https://drive.google.com/file/d/17vO81oRGZxXrVwKp_Sc0-b4opXsyfUWb/view?usp=sharing

**Expected behavior**

Problem with any styles

**Additional context**
problem star with:
```
    const svgs = gulp.src('source/image/*.svg', {base: 'source/image'})
      .pipe(rename({prefix: 'icon-'}))
      .pipe(svgstore({inlineSvg: true}));
```

**Comment by joshgoebel** [comment]
<img width="816" alt="Screen Shot 2020-10-25 at 4 40 05 PM" src="https://user-images.githubusercontent.com/6473/97118528-c34cae80-16e0-11eb-84bc-e769431c3e6d.png">

Can you confirm this on the latest master?  I'm seeing no issues.

**Comment by joshgoebel** [comment]
10.2.0 had a bug that would result in this... so if you're seeing this on StackOverflow or a site using an older version of the library, that's likely what is going on here.  Upgrading to the latest version should resolve.

**Comment by GurovDmitriy** [comment]
I'm uploading a file from offic site. 

I have little experience. I don’t understand how to compile from sources for github

**Comment by joshgoebel** [comment]
![Screen Shot 2020-10-29 at 7 59 37 AM](https://user-images.githubusercontent.com/6473/97566114-b53aae80-19bc-11eb-93cf-93e7c06130a6.png)

Maybe we're talking about different things?  Looks fine to me.

**Comment by joshgoebel** [comment]
@GurovDmitriy Your code is being detected as Bash.  Auto-detect is not 100% accurate.  For 100% accuracy you need to manually tell us what type of code you are highlighting.  You need to manually specify the language in of your code blocks:

```
<pre class="lang-javascript"><code>...
</code></pre>
```

**Comment by GurovDmitriy** [comment]
when i insert
<pre class = "lang-javascript"> <code> ...
</code> </pre>
or
<pre> <code> ...
</ code class = "lang-javascript"> </pre> - no highlighting. now removed the tips, the bash was highlighted. 1 minute updating the site..
![Screenshot_1](https://user-images.githubusercontent.com/26795848/97573565-04073900-19fb-11eb-9357-279defad718e.png)
![Screenshot_2](https://user-images.githubusercontent.com/26795848/97573591-0ec1ce00-19fb-11eb-8a12-f4580940ec92.png)

**Comment by GurovDmitriy** [comment]
In the first picture, the pipe of different blocks is highlighted, but the other does not

**Comment by joshgoebel** [comment]
Your Highlight.js build does not include Javscript language support: https://www.typenote.io/js/highlight.js  Use the default build or create a new build that includes JS support.  JS can't be highlighted if you don't build support for it into your library.

**Comment by GurovDmitriy** [comment]
I didn’t find it listed for individually assembling. I thought it was turned on by default. is she on the list ...?

**Comment by joshgoebel** [comment]
> I didn’t find it listed for individually assembling. I thought it was turned on by default. is she on the list ...?

Well now - **it's missing**, that's incredibly annoying. :-)

**Comment by GurovDmitriy** [comment]
P.S. If you need a layout, tell me, I'm a beginner web developer. I work for thanks)))

**Comment by joshgoebel** [comment]
@GurovDmitriy It's back in the list now if you build a new version you should get it.

**Comment by GurovDmitriy** [comment]
thank you so much

**Comment by GurovDmitriy** [comment]
I set everything up. updated. Working!
