### ISSUE TITLE
(python) Decorator syntax breaks comment formatting

### ISSUE THREAD

**Issue by textbook** [highlightjs/highlight.js#2804]
**Describe the issue**
If you have a comment on the same line as a decorator, the whole line gets the `hljs-meta` class; the comment section (`#` onwards, see examples below) should be `hljs-comment` instead.

**Which language seems to have the issue?**
`python`

**Are you using `highlight` or `highlightAuto`?**

Based on https://meta.stackoverflow.com/a/401590/3001761 I believe it's using `highlight`, as the Python tag enables the language selection.

**Sample Code to Reproduce**

Spotted on: https://stackoverflow.com/q/38031066/3001761 _(I've added an extra comment on the line below to highlight the expected formatting more clearly)_:

![Screenshot 2020-10-30 at 11 30 06](https://user-images.githubusercontent.com/785939/97700244-67e53c80-1aa3-11eb-9313-c8a907c0d85d.png)

Code:

```python
@pytest.mark.asyncio  # note use of pytest-asyncio marker
async def test_async_for():  # but this comment works 🤔
    async for _ in TestImplementation():
        pass
```
JSFiddle: https://jsfiddle.net/zfe9r6w5/1/

**Expected behavior**
Comment is greyed out on _both_ lines; GitHub gets this right, as shown in the code sample above.

**Additional context**
N/A

**Comment by textbook** [comment]
Looking at [the current implementation][1], it's assumed that any line starting `@` will be _meta_ throughout:

```javascript
      {
        className: 'meta',
        begin: /^[\t ]*@/, end: /$/
      },
```

  [1]: https://github.com/highlightjs/highlight.js/blob/deea7b7ed8f8e62b38b2eb07c935af5592850c9c/src/languages/python.js#L276-L279

**Comment by joshgoebel** [comment]
Yep, should be a pretty easy fix (allows comments inside that rule)... want to try a PR?

**Comment by joshgoebel** [comment]
Actually what we really may want is the ending to just end if it sees a comment upcoming:

```
 { 
   className: 'meta', 
   begin: /^[\t ]*@/, end: /$|(?=#)/ 
 }, 
```

Or some such

**Comment by joshgoebel** [comment]
Can it be like:

```
@1 + 2 * 6
```

Then?  Or it's gotta be a name or function type expression?

**Comment by textbook** [comment]
It used to need to be _"a dotted name, optionally followed by a single call"_ per [the grammar][2]:

```
decorator: '@' dotted_name [ '(' [arglist] ')' ] NEWLINE
decorators: decorator+
```

From Python 3.9, though, as [PEP 614][1] relaxed the rules, it can be any expression per [the new grammar][3]:

```
decorators: ('@' named_expression NEWLINE )+ 
```

  [1]: https://www.python.org/dev/peps/pep-0614/
  [2]: https://docs.python.org/3.8/reference/grammar.html
  [3]: https://docs.python.org/3.9/reference/grammar.html

**Comment by joshgoebel** [comment]
If you have a grasp on this I'll just wait to see the PR and markup tests (of which I hope there will be quite a few variants)... but if it truly can be any old expression I'm worried it could be a bit complex...  although perhaps all we really need is a simple mode that allows for strings, comments, and then this simply solves itself.

Although I'm curious about the meta styling fighting with the other styles, but we can talk about that once we have a PR I suppose. :)
