### ISSUE TITLE
(Swift) Incorrect highlighting of raw strings

### ISSUE THREAD

**Issue by svanimpe** [highlightjs/highlight.js#2819]
[Editor: Dropping some notes for whoever picks this up] 

This needs to also take into account: 

- [x] SUBST (inline code) inside raw strings
- [x] the different forms of escaping inside raw strings
- [x] the different syntax of variable substitution (we should probably highlight this, right?)
- [x] extend the string markup tests quite a bit to go along with this
- [ ] could we handle arbitrary number of #### with END_SAME_AS_BEGIN? Worth it?

---

The following is a single raw string:

```swift
##"Use #" and "# to delimit a raw string."##
```

However, it's incorrectly highlighted as two separate strings. My guess is that highlight.js thinks the quotes in the middle close a string, then start a new one?

In general, the hashes around raw strings aren't highlighted in the same color as the string, so perhaps raw strings aren't supported at all yet?

**Comment by joshgoebel** [comment]
> so perhaps raw strings aren't supported at all yet?

And we have a winner - seems not to be. :-)  Want to work on a PR? :-)

**Comment by joshgoebel** [comment]
> Can I just add new files to test/markup/swift,

Yes, you may want to consider renaming `multiline-string` to just `strings` and making it more general.

>  And how do I run tests 

`npm run build && npm run test-markup`

**Comment by joshgoebel** [comment]
Note: The PR in #2820 is not a bad start.

**Comment by svanimpe** [comment]
To make it even more complex, escapes (such as `\#t`) and substitutions (such as `\#(variable)`) should also have the same number of hashes as the raw string delimiters used.

So `#"something \#t and \#(variable) something"#` contains a tab and a substitution, whereas `##"something \#t and \#(variable) something"##` is fully raw (no tab and no substitution).

**Comment by joshgoebel** [comment]
Annoying, but doable if we're only supporting a few specific variants... vs any number of ##### - which may not actually be possible given the contextual constraints you just mentioned.

**Comment by svanimpe** [comment]
Just FYI: I'm picking this up again. Expect a pull request soon!
