### ISSUE TITLE
(Swift) Incorrect highlighting floating-point literals

### ISSUE THREAD

**Issue by svanimpe** [highlightjs/highlight.js#2824]
The regular expression for matching numbers doesn't seem to handle exponents properly. For example, `1e-10` is a valid floating-point literal, but only the `10` highlights as a number.

I'm not entirely familiar with your regex syntax, but my guess is that this part: `[\\d_]+(\\.[\\deE_]+)?` means "one or more digits, followed by an optional part containing a decimal point and one or more digits or the letter `e`".  If that's correct, that  would explain why `12.1e12` does highlight correctly.

There may be a few more issues with this regex:

- Does it handle negative exponents?
- It seems to allow multiple letters `e/E` mixed in with the decimals. There should be only one `e/E` between the base and the exponent.

For reference, here is the grammar on floating-point literals:
https://docs.swift.org/swift-book/ReferenceManual/LexicalStructure.html#ID416

**Comment by joshgoebel** [comment]
> I'm not entirely familiar with your regex syntax

It's not "our syntax" per se...  It's just JavaScript's RegExp support... but I think it's generally standard-ish as far as RegEx goes... at least all the common things.

**Comment by gibson042** [comment]
Yeah, this looks doable. And thanks for the ping!

**Comment by svanimpe** [comment]
Thank you for fixing this!
