### ISSUE TITLE
[question] How do I render line numbers on the server-side?

### ISSUE THREAD

**Issue by Roki100** [highlightjs/highlight.js#2837]
is there a way to add line count when i use hljs in node.js? (it can be anything, plugins, code or whatever that works)

**Comment by taufik-nurrohman** [comment]
https://github.com/taufik-nurrohman/highlight.ln.js

Let me see if I can add support for Node.js

**Comment by taufik-nurrohman** [comment]
@joshgoebel to add support for Node.js, do I need to install [jsdom](https://www.npmjs.com/package/jsdom) and then define `window` and `document` variable from there? Or, is it okay to just add UMD pattern in my plugin?

**Comment by joshgoebel** [comment]
I don't know.  That is a *very* unusual way to use Highlight.js - I wouldn't encourage it.  The best way to do *complex* line numbers is to walk the parse-tree (or provide an alternative emitter - see `lowlight`) and then render the line numbers side by side with the original content.  But first I'd find out what the real requirements are here.  **MANY, many users don't need mixed output at all**... a block of line numbers and a block of code (separately) just styled smartly with CSS do the job... and this is usually only a few lines of JS to build the line numbers.

For example a one-liner (though not guaranteed to be performant, a loop would be better) to generate the HTML:

```js
"<code class='hljs linenumber'>" + new Array(lines).fill().map((x,i) => `${i}`).join("\n") + "</code>"
```

And then use something like flexbox to do the CSS positioning...

**Comment by joshgoebel** [comment]
Ok, after glancing at your plugin again, you do that... you just use the DOM.  I personally would forget about the DOM and just render the HTML as a string.  So your plugin would add a method for users who wanted to generate html and it would return raw code... and you'd alter your plugin calls to just call that method and then have 1-2 lines of glue to add it to the DOM, IE:

```
// add a new function
highlightWithLineNumbers(...)
```

That's just off the top of my head.

**Comment by taufik-nurrohman** [comment]
So, something like `code.innerHTML = lines + code.innerHTML` is good to go?

I wonder how you make `hljs.initHighlightingOnLoad()` to make it work in Node.js, since they have document event listener and document query selector. Or, are you guys just don&rsquo;t care it that much?

**Comment by joshgoebel** [comment]
**None of that matters inside Node.js...** inside Node.js there is no DOM, there is no browser...  Someone is going to call a function you provide and expect some HTML, you give them that HTML.  You're done.  IE, perhaps you give them:

```
<code>line numbers</code>
<code>real code</code>
```

Then the plugin portion of your code calls that function ALSO, and your plugin shrinks to something like:

```
let html = generateHTMLWithLineNumbers(code, language)
block.innerHTML = html
```
May be a little more complex setting CSS classes on the parent node, etc... but again you're already doing it... just most of the code needs to move inside `generateHTMLWithLineNumbers` and you need to work with strings not DOM.  Only using DOM at the very end (for the plugin portion).

**Comment by joshgoebel** [comment]
Closing as asked and answered. :)
