### ISSUE TITLE
(website) `C-like` should not show up on the "Common" list on the website Downloads page

### ISSUE THREAD

**Issue by obnoxiousorc** [highlightjs/highlight.js#2840]
I noticed there were several inconsistencies in alias definitions:

- Some aliases conflict with other languages. For example, "c" has alias "h" but "c-like" has both "c" and "h" as aliases. If I read the code right, whichever language registers it last gets priority.
- YAML has alias "YAML" when other similar names like TOML, JSON, etc. are using only lowercase versions
- PHP has "php6", PHP 6 was never formally released
- Some, but not all, languages include the original language name (ex. "c" has the alias "c" but "css" doesn't have the alias "css")

**Comment by joshgoebel** [comment]
- C-like is a foundational grammar for others to build on. So it’s not a duplicate. 
- YAML and php6 could not be changed until a major release because those would be potentially breaking changes. 
- The last item could probably be addressed via PR.  In general the alias list should not include the primary name. 

Interested in making a PR?

**Comment by joshgoebel** [comment]
Also just to be clear duplicates aren’t strictly disallowed although it does become ambiguous. A lot of people only build a subset of languages so really duplicates aren’t a problem at all unless someone builds a subset of languages with duplicate aliases.

So I believe that we actually have entirely different languages that share aliases in a few cases. So if someone was going to completely address this issue it would require figuring out what to do about that. I think there was another issue for that a while back but I can’t remember now.

**Comment by obnoxiousorc** [comment]
@joshgoebel That makes sense - I mostly just wanted to bring attention to the inconsistencies in case there was something that could be done to fix them. I can do a PR for the last thing, though, that shouldn't be too hard :)

**Comment by joshgoebel** [comment]
It shouldn't be directly used, we have C and C++ grammars which inherit from it.  Honestly it should probably be moved into `languages/lib` but it's too late now since it's out in the wild and some people MAY be using it as-is... so that would be a breaking change. :)

**Comment by obnoxiousorc** [comment]
Got it, that makes sense! Could I update the docs to clarify that, perhaps?

**Comment by joshgoebel** [comment]
Where would you put that?  It's kind of an edge case...

**Comment by obnoxiousorc** [comment]
I was thinking on the download page by its checkbox, but I guess that depends on whether it needs to be installed for C and the other grammars that build on it.

**Comment by joshgoebel** [comment]
Oh that wouldn't be a doc fix, we'd fix that on the website itself... do you know Python? :)

>  on whether it needs to be installed for C and the other grammars that build on it.

For 10.3, yes, for 10.4 no... but the website already handles that automatically.

**Comment by joshgoebel** [comment]
This will remove it from the common list at least: https://github.com/highlightjs/highlight.js/commit/04f210dfa5fbe08ec82413f9d959c1508c98ebb8

**Comment by obnoxiousorc** [comment]
I do know Python, and I have used Django before too, as it happens, so I'll submit a PR there in the next few days sometime 👍

**Comment by joshgoebel** [comment]
I think it might be as simple as manually filtering it out here:

https://github.com/highlightjs/hljs_org/blob/master/hljs_org/lib.py#L149

**Comment by joshgoebel** [comment]
@obnoxiousorc Were you going to work on a fix for this at the website level?

**Comment by joshgoebel** [comment]
Closing this since the original issue is resolved and just listing `clike` in the bottom list isn't worth holding an issue open indefinitely if there is no wanting to contribute a fix.
