### ISSUE TITLE
Styles once deployed are different than locally

### ISSUE THREAD

**Issue by nelsynelz** [highlightjs/highlight.js#2842]
**Describe the issue**
The style I'm using is working correctly in local development, everything looks great. However once I deploy to Netlify it seems like the style is not being applied correctly. The background color is correct, but nothing else is remotely the same. The pattern seems to be the same regardless of which style I use.

**Additional context**
I'm using VueJS (Nuxt technically), I'm initializing highlightJS manually after receiving data from my server. 

```javascript
initializeHighlightJs() {
      if(process.browser) {
        document.querySelectorAll('pre code').forEach((block) => {
          hljs.highlightBlock(block);
        });

        document.querySelectorAll("code").forEach((block) => {
          block.setAttribute("style", "border-radius: 0.375rem;")
        });
      }
    }
```

I'm importing the style manually as well...
```javascript
import hljs from 'highlight.js'
import 'highlight.js/styles/shades-of-purple.css';
```

Here are the screenshots of both sites.

**Local**
![image](https://user-images.githubusercontent.com/41842184/98708895-adc9bc80-234f-11eb-981c-a9802ec89004.png)

**Deployed**
![image](https://user-images.githubusercontent.com/41842184/98708934-bae6ab80-234f-11eb-81c7-b05b0fd1de96.png)

I copied each element and compared them side by side in vscode and there were no differences...
![image](https://user-images.githubusercontent.com/41842184/98709023-d2be2f80-234f-11eb-88e8-4322c192e655.png)

There are also no errors in the console nor are there any network errors.

**Comment by joshgoebel** [comment]
No idea, this is something you should debug using browser tools.  Is the CSS loaded?  Is the code block being converted into tagged HTML, etc... sounds perhaps either you aren't loading the CSS or you aren't running the highlighter at all...

**Comment by nelsynelz** [comment]
Is the CSS Loaded? - The CSS has to be loading in order for the background to change and for the syntax highlighting it is doing

Is the code being converted to tagged HTML? - I supplied a screenshot showing the tagged HTML, it was identical from local to my deployed site. 

I guess I'll try to do more debugging on my own, just not sure what I need to do next given what I just mentioned. Was kind of hoping you guys have seen this before and would have a quick answer.

**Comment by joshgoebel** [comment]
Oh so sorry... I should have looked at the pictures more.   I'd suggest actually you aren't loading the CSS or your build system is breaking it somehow (or loading conflicting CSS).  Right click one of the keywords and choose "Inspect" and your browser will tell you where those styles are coming from.

In Safari (but all modern browsers have similiar ability):

<img width="871" alt="Screen Shot 2020-11-10 at 5 39 16 PM" src="https://user-images.githubusercontent.com/6473/98742008-ac15ee00-237b-11eb-9707-41aad7acfa12.png">

**Comment by nelsynelz** [comment]
No problem and thank you for being more specific. 

Okay, so it seems in the deployed version it's using the default css file.
![image](https://user-images.githubusercontent.com/41842184/98742102-d667ab80-237b-11eb-860c-fe77586ba0e7.png)

Locally the same element  has the correct source css file.
![image](https://user-images.githubusercontent.com/41842184/98742216-09aa3a80-237c-11eb-8d5c-1851821b1f8f.png)


I'll have to figure out why that's the case. I have a feeling it's because of where I'm importing the modules and the css file specifically. It's not being included properly in the build process. 

Thanks again!

**Comment by joshgoebel** [comment]
> Many people set a default background on pre/code so that they look nice 

Which it seems your doing because default background is by default white, not dark. :-)  Or else you're loading BOTH stylesheets and they are somehow mixing/fighting with each other in some weird way.  

Good luck!  Glad to help.

**Comment by joshgoebel** [comment]
> Locally the same element has the correct source css file.

FYI: Locally it looks like you're loading both, which is also broken.  You should really only load a single theme at a time.

**Comment by nelsynelz** [comment]
Got it working!

What I discovered:
1. Importing the CSS (via ES6 module method) directly into the Vue component does not work
2. Importing the CSS into the CSS section of the Nuxt.config to be included in the build process does not work
3. Importing the CSS via CDN within the Nuxt.config does work

I know that is hyper specific to Nuxt, but maybe it'll help somebody in the future. 

```javascript
head: {
  title: "App Name",
  meta: [
    { charset: 'utf-8' },
    { name: 'viewport', content: 'width=device-width, initial-scale=1' }
  ],
  link: [
    { rel: 'stylesheet', href: 'https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.3.2/styles/shades-of-purple.min.css' },
  ]
}
```

**Comment by joshgoebel** [comment]
Thanks for the update!  I'd suppose there is some way to make 1 and 2 work also, even if right now we don't know what it is.  If you're importing CSS with your build process itself (with ES6 modules [option #1]) it's quite likely you haven't configured the output side of that equation properly.  Although I can't think of any reason "default" (it's just a name) would be imported by default if you didn't actually specify it anywhere in your build.

So if someone else shows up who has the answer, please educate us. :)
