### ISSUE TITLE
(VB.Net) Incorrect highlighting of Rem Comments

### ISSUE THREAD

**Issue by Greedquest** [highlightjs/highlight.js#2851]
**Describe the issue**
The legacy [Rem/REM statement](https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/statements/rem-statement) is an alternative to the `'` apostrophe literal for single line comments

**Are you using `highlight` or `highlightAuto`?**
Using `highlight` (via tag associations on SO)

**Sample Code to Reproduce**
https://jsfiddle.net/zv9k1hox/

**Expected behavior**
Rem is treated as a comment and doesn't affect highlighting of subsequent lines:
```vbnet
     Rem Tab to be replaced with \t
    If InStr(Content, vbTab) > 0 Then Content = Replace(Content, vbTab, "\t")
    
    Rem Double quote to be replaced with \"
    If InStr(Content, Chr(34)) > 0 Then Content = Replace(Content, Chr(34), "\" & Chr(34))
    Set EscapeJSON = Self
End Property

Public Function ToString(Optional ContentWrapper As String = "") As String
        ToString = ContentWrapper & this.Content & ContentWrapper
End Function

Public Property Get Content() As String
    Content = this.Content
End Property

Public Property Let Content(ByVal Value As String)
    this.Content = Value
End Property
```

**Additional context**
Triggered by [this](https://codereview.stackexchange.com/q/251995/146810) question on Code Review

**Comment by joshgoebel** [comment]
Confirm.  We don't know about `REM` at all.  Looks like there are a few rules:

- A space is required between the REM keyword and comment.
- You can put a REM statement alone on a line, or you can put it on a line following another statement. The REM statement must be the last statement on the line. If it follows another statement, the REM must be separated from that statement by a space.

Interested in perhaps contributing a PR?
