### ISSUE TITLE
(Swift) left and right keywords and precedencegroup highligthing

### ISSUE THREAD

**Issue by svanimpe** [highlightjs/highlight.js#2856]
Highlight.js highlights `left` and `right` as keywords. It's true that they have some special meaning (see https://docs.swift.org/swift-book/ReferenceManual/Declarations.html#grammar_precedence-group-declaration), however, they aren't reserved keywords, so 99% of the time, they will just be variables.

What is the policy regarding keywords? Should only reserved words be highlighted as keywords?

**Comment by joshgoebel** [comment]
I don't know there is a strict policy. :-)  In this case it sounds like they should be removed from keywords or possibly a contextual rule highlighted (so they are only highlighted as keywords in that context).  This type of fancy highlighting might be too much though... so at this point I'd be happy if we simply removed them and then see if anyone pushes back. 

It looks like we're missing quite a few of the precedencegroup keywords though.  Swift's own highlighting marks them as keywords.  It'd be nice if when we resolve this we could add them also.

<img width="865" alt="Screen Shot 2020-11-13 at 9 57 00 AM" src="https://user-images.githubusercontent.com/6473/99085918-cd065b00-2596-11eb-9a07-5d675702c20f.png">
