### ISSUE TITLE
[MQL5 Support] ...

### ISSUE THREAD

**Issue by marco2030-hub** [highlightjs/highlight.js#2864]
Consider adding MQL5 support for highlighting.
It is a C/C++ variety.

**Comment by joshgoebel** [comment]
> It is a C/C++ variety.

Some quickly googling seems to indicate it's a scripting language similar to C++:

> MetaQuotes Language 5 (MQL5) is a high-level language designed for developing technical indicators, trading robots and utility applications, which automate financial trading. MQL5 has been developed by MetaQuotes Software Corp. for their trading platform. The language syntax is very close to C++ enabling programmers to develop applications in the object-oriented programming (OOP) style.

> Consider adding MQL5 support for highlighting.

See [On requesting new languages](https://github.com/highlightjs/highlight.js/blob/master/docs/language-requests.rst)... the short answer is that the core team doesn't add support for new languages.  The long answer is - well go read it. :-)  If you wanted to contribute a 3rd party grammar for MQL5 support that'd be awesome.

But a more practical question:  Why not just use the C++ grammar to highlight MQL5 code if they are so close?

**Comment by joshgoebel** [comment]
Closing per explanation in documentation.
