### ISSUE TITLE
Chore: Setup users/accounts for automation security context

### ISSUE THREAD

**Issue by joshgoebel** [highlightjs/highlight.js#2866]
Security items related to the new GitHub action for releases:

- [x] Setup 1Password account for team member shared secrets
- [x] Create email account to associate with users
- [x] Create GitHub user (for repo push token) (highlightjs-bot)
- [x] Create NPM user (for publish token) (highlightjs_bot)
- [x] Use new npm token
- [x] Use new GitHub personal token
- [x] Get free credit for 1Password Teams because we're Open Source

---

![Screen Shot 2020-11-11 at 11 23 54 PM](https://user-images.githubusercontent.com/6473/98895425-12326c00-2475-11eb-9ec4-1efcd3ef3082.png)

I'm not sure if we just use github action or if we need to create a whole new GitHub identity for this... it bothers me a little that the personal token I had to use to get this to work belongs to me personally... I think for best practices sake we'd want a token from a user that ONLY had access to the single repo `cdn-assets`, right?  If we do create a whole new identify then it might make sense to use that for these commits.

The same problem seems to exist for NPM where tokens are also per-person.  

If we start needing a few more things like this is anyone opposed to 1Password?  https://github.com/1Password/1password-teams-open-source  Then anyone needing access to these things could be added to 1Password and any team secrets would be stored there.  I don't expect this to be a frequent need at all, just I hate to own all the secrets myself or have them tied to me personally.

Thoughts?

_Originally posted by @joshgoebel in https://github.com/highlightjs/highlight.js/issues/2850#issuecomment-725827813_

**Comment by joshgoebel** [comment]
**Comments from allejo on that thread:**

+1

Personal Access Tokens (PATs) are tied to your account so if ever stolen it'll have access to all other orgs you belong to. So definitely in favor of a dedicated service account.

I'm cool with using 1Password for Open Source! I didn't know they offered this ❤️

**Comment by joshgoebel** [comment]
Everyone should have 1password invite in your email.

**Comment by egor-rogov** [comment]
Thanks!

**Comment by joshgoebel** [comment]
Egor you may also want to download an emergency kit and keep it somewhere safe for a rainy day.

https://support.1password.com/emergency-kit/#get-your-emergency-kit

Marking this complete since we were just granted our first free year!
