### ISSUE TITLE
(asciidoc) Section titles level 5 (i.e. using 6 "=" characters)

### ISSUE THREAD

**Issue by Mogztter** [highlightjs/highlight.js#2868]
**Describe the issue**

Section titles level 5 (i.e. using 6 "=" characters) are not recognized as section titles.

**Which language seems to have the issue?**

`asciidoc`

**Sample Code to Reproduce**

```
= Document Title (Level 0)

== Level 1 Section Title

=== Level 2 Section Title

==== Level 3 Section Title

===== Level 4 Section Title

====== Level 5 Section Title

== Another Level 1 Section Title
```

https://asciidoctor-docs.netlify.app/asciidoc/current/sections/titles-and-levels/#section-level-syntax

**Expected behavior**

`====== Level 5 Section Title` should be highlighted as a section title.

**Additional context**

For reference:

- Asciidoctor regular expression: https://github.com/asciidoctor/asciidoctor/blob/697d7171830f3dc757175bc29b7eb528d4cdb4b5/lib/asciidoctor/rx.rb#L239
- AsciiDoc documentation: https://asciidoctor-docs.netlify.app/asciidoc/current/sections/titles-and-levels/#section-level-syntax

**Comment by joshgoebel** [comment]
This one looks super easy, you want to try a PR? :-)

**Comment by Mogztter** [comment]
I will ask in the Asciidoctor Gitter channel, maybe someone will be interested in making a (first-time) contribution to Highlight.js.

**Comment by joshgoebel** [comment]
If you get frustrated on the other come solve this, should be easy. :)

**Comment by Mogztter** [comment]
> If you get frustrated on the other come solve this, should be easy. :)

Ah ah ah! I'm trying to keep my sanity but it's hard!
You can quickly lose your mind while working on regular expressions 🤪🤪🤪

I admire your bravery!
