### ISSUE TITLE
(Swift) Shorthand parameter names are highlighted as numbers

### ISSUE THREAD

**Issue by svanimpe** [highlightjs/highlight.js#2871]
As you can see, highlight.js highlights the 0 and 1 in `$0` and `$1` as numbers, even though those are parameter names:

<img width="435" alt="Screen Shot 2020-11-15 at 22 45 01" src="https://user-images.githubusercontent.com/1496250/99197680-399a7900-2794-11eb-98a1-46da4fbd407b.png">

I assume this isn't intended? Does the new regex for numbers fix this, or does it need extra work?

For reference, Xcode doesn't highlight those shorthand parameter names at all. VS Code does:

<img width="589" alt="Screen Shot 2020-11-15 at 22 47 20" src="https://user-images.githubusercontent.com/1496250/99197738-87af7c80-2794-11eb-9e2b-e9485417471e.png">

**Comment by joshgoebel** [comment]
> I assume this isn't intended? Does the new regex for numbers fix this, or does it need extra work?

I can't see how.  There is a word boundary between $ and \d so the digit rules would match.  This is likely a case where we just need a separate rule earlier in the list to highlight `$\d`, though I'm not sure what to call those right now?  Perhaps `variable` highlighting?

**Comment by svanimpe** [comment]
Fixed in https://github.com/highlightjs/highlight.js/pull/2908
