### ISSUE TITLE
(vb.net) Comments need to be reworked - `<` in comment breaks highlighting

### ISSUE THREAD

**Issue by pcr-coding** [highlightjs/highlight.js#2875]
**Describe the issue**
A simple comment including a smaller than sign `<` will make all following code lines formatted as comments.

**Which language seems to have the issue?**
The issue is with VB.NET (probably but not tested the same issue with vbscript).

**Are you using `highlight` or `highlightAuto`?**
Using highlight (via tag associations on SO)

**Sample Code to Reproduce**
```vb
'rule 1: column A allows only text length < 9
Set AffectedCells = Intersect(Target, Target.Parent.Range("A:A"))
```
as shown in this filddle: https://jsfiddle.net/pcrcoding/4bcxaot0/

**Expected behavior**
I expect lines that start with a `'` or `REM ` to handle the entire line until line break as coment and end comment formatting at the line break. The expected behaviour would be the one seen in this post at *"Sample Code to Reproduce"*

**Additional context**
Also check https://github.com/highlightjs/highlight.js/issues/2851 for the `REM `.

**Comment by joshgoebel** [comment]
Confirm. It’s seen as the opening of a doctag which is never closed.  Probably still should terminate at line end either way.

**Comment by joshgoebel** [comment]
Right now at a glance I'd say we're doing comments all wrong in VB.net.  Since doctags really only exist inside `'''` comments, correct?

**Comment by pcr-coding** [comment]
@joshgoebel If you are talking about the XML documentation comments, yes they all start with `'''` and end with the line break.
I linked the documentation below:
https://docs.microsoft.com/en-us/dotnet/visual-basic/programming-guide/program-structure/documenting-your-code-with-xml
