### ISSUE TITLE
Discuss: Official deprecation and security policy for older releases

### ISSUE THREAD

**Issue by joshgoebel** [highlightjs/highlight.js#2881]
In light of our v9 deprecation having a [few bumps](https://github.com/highlightjs/highlight.js/issues/2877) I'd like to start a discussion about how we handle this in the future.

Some background:

- v9 has been mostly dormant since April when v10 was released.
- v9 has been "sorta supported" since April really only in the sense that if a major security issue came up, we'd fix it if was reasonable to do so (effort wise).  Support for IE11 was pretty much dropped with v10.  That was the only real reason anyone should have kept using v9 (IMHO) rather than upgrading.
- It's seen a few security updates and hasn't been TOO much of a burden... but...
- Our release system was never really setup for maintaining multiple major branches.
- The core team doesn't really have time to focus on two major release. (even back-porting security or major reliability issues can become a real burden since the parser engine has changed so much from v9 to v10)

Now 10 -> 11 may not be like 9 -> 10, but I see two potential ends of the spectrum.  And I feel they both point to a very limited "dual major version" window of any kind.

**Easy migration.** If 10 -> 11 is a super easy migration with very few breaking changes - then why do we need to support 10 at ALL?  Rather the same policy might apply as currently applies with minor releases.  If you have a problem/bug/security issue with 10, upgrade to 11, period.  IE, 11 deprecates 10.  (or a very short window)

**Hard migration.**  On the other side... lots of breaking changes, lots of codebase changes, things are very different.  In this case the effort of back-porting things is also much higher making it very expensive and inefficient to maintain the older branch even if there might be some need for it.

Either way is seems the goal should be to get the most people on 11 as soon as possible.  Having some way in advance to track dependents who are unmaintained or who aren't keeping regularly updated might also be helpful to know in advance.

I feel we could have done a better job with our v9 deprecation communication, but it seems we currently have very limited tools for reaching our users (releases, post-install scripts, NPM deprecations, GitHub issues?)... I'd be curious to hear how other libraries handle this... or perhaps other libraries just care less about people using old versions?

**Note:** Not that I'm in a big hurry to get to v11.  I'm thinking sometime in 2021, but v10 has legs I feel.  

---

Things to discuss

- [x] How long do we support a prior release?
- [x] In what ways do we support a prior release?
- [x] Does the length of that window depend on the # of breaking changes?
- [ ] How do we notify users of these things? 
- [ ] How to better communication with users in general?

**Comment by joshgoebel** [comment]
It seems clear we could draw a better distinction in the future to various groups of users:

- direct dependency
- indirect dependency

Perhaps even figure out the dependency and craft a custom message suggesting they go ping that maintainer for an upgrade.  

Also worth thinking about web users... all those people who "download" the file and copy it into their project/site... are they just a lost cause for upgrades?  They probably need critical fixes less than other people, but still is it great if they're using say version 8 forever?

**Comment by joshgoebel** [comment]
Copying this over from another thread because it seem quite relevant and probably should have been posted here:

---

If you have any specific thoughts (or articles) on how to clearly communicate EOL to users of NPM packages and wanted to share on that thread we're very willing to learn for when the 10 -> 11 transition comes around. I'm not sure that's even really a thing in the NPM/Node.js culture though. deprecate seems not much used and the API buggy in my experience. I look on NPM and find packages (including our own) with versions going back years and years - some with serious (and not so serious security issues). We still had our 1.0.0 on there until just the other day.

Yesterday I deprecated everything except for our newest releases (that we actively support here via issues, etc).

And while we could perhaps issue CVEs (or just advisories) against old versions - that's a bit more nebulous (correct me if I'm wrong) when we're confident there are issues (or strong potential issues) but you don't know exactly what they are.

Plus my feeling is saying "upgrade now things are going to get bad later" is better than proving it by dropping a bunch of security advisories on people at a later date - with no fixes forthcoming. IE, if we have a chance to provide some warning - that seems better. Perhaps you disagree?

**Comment by joshgoebel** [comment]
Some thoughts on this.

> How long do we support a prior release?  In what ways do we support a prior release?

- ~3 months for critical security updates only (core team if feasible, PRs always welcome)
- ~3 months for major bugs [crash, infinite loops, etc] (core team if feasible, PRs always welcome)
- Grammar issues are not unsupported in prior releases.

Future migrations should be cleaner than the 9 => 10 transition. (no IE11 worries, hopefully most huge regex security issues behind us, etc). The idea remains that upgrades should be "mostly painless" and that backporting of bug fixes is not a good use of the core teams time - but if others want to contribute PRs for major bugs, ok.

> Does the length of that window depend on the # of breaking changes?

I don't think so.  Typically unless you're hacking our internals (in which case you're on your own) even _most_ of our breaking changes should require minimal developer effort.  Major key API changes are likely to be supported for 2 cycles, giving plenty of time for this paying attention.  This is always something we could adjust as necessary in real time also.

Other general thoughts on dos/dont's of prior release management:

- No more npm post-install scripts. This seems to be an anti-pattern now.
- No more `logger.warn` (writing to STDERR, potential breaking automation)... if it's decided a warning is truly needed `logger.notice` or `logger.deprecated` will be used. npm deprecation will be preferred though vs adding notices to older releases.
- Old releases will stay around forever on npm provided there are no security issues.
- Old releases with security issues will be deprecated on npm.

> How do we notify users of these things? How to better communication with users in general?

Still worth discussion. @isagalaev Could we add the highlight.js twitter credentials to our core team 1Password account so that we could use it for news, announcements, etc?

CC @egor-rogov @allejo

**Comment by allejo** [comment]
> * ~3 months for critical security updates only (core team if feasible, PRs always welcome)
> * ~3 months for major bugs [crash, infinite loops, etc] (core team if feasible, PRs always welcome)
> * Grammar issues are not supported at all in prior releases. (PRs not welcome)

:+1: I like this timeline, it'd be similar in concept to policies that other OS projects have with their LTS timelines. I think the shorter timespan adequately represents the scope of this project and how much time maintainers have available.

> Also worth thinking about web users... all those people who "download" the file and copy it into their project/site... are they just a lost cause for upgrades? They probably need critical fixes less than other people, but still is it great if they're using say version 8 forever?

Unless we have some type of analytics _in_ the library itself that could be used for pinging highlight.js for newer versions (which I'd be against in the first place), we've lost them. I think for the custom build process, we can have a message above the download button that says they're opting out of notice of updates and security patches and point them to our Twitter account. And also point them to better approaches than downloading custom builds.

> Does the length of that window depend on the # of breaking changes?

plzno. This thought reminds me of a worst-case scenario of Python 2 vs 3.

> Major key API changes are likely to be supported for 2 cycles, giving plenty of time for those paying attention. This is always something we could adjust as necessary in real time also.

I personally love how the Symfony community handles updates. They have a final `*.4` LTS release and then bump major versions. So, for example `4.4` is LTS and the next release is `5.0`. `5.0` is identical to `4.4` with the exception that deprecations were removed. Now, in order update from `4.4` to `5.0`, all you need to do is fix deprecation warnings and then the upgrade is flawless. I don't think we _need_ to support 2 cycles if we have a smooth transition process between major bumps.

**Comment by allejo** [comment]
As for handling updates on npm, so long as we publish CVEs and security information, then `npm` and `yarn` should pick up those notices and notify uses and package maintainers for vulnerable dependencies. There are plenty of measures to notify uses of security notices, heck even Dependabot (provided by GitHub) is easy to configure.

The only time I think we should deprecate packages is when we have a major bump or right before it. So v11 to v10, deprecate all of the 10.x packages on npm so that uses can do some research and see that they now have less than 3 months before their HLJS version is EOL'd. If you want to give people a longer heads up, if 10.9 is the last planned version of HLJS (hypothetically) for the 10.x series, then deprecate all packages prior to that to get people's attention to get rid of deprecation messages. Once they've gotten rid of deprecation messages, they are ready to ugprade from 10.9 to 11 in the coming weeks/months, both easily and safely.

**Comment by joshgoebel** [comment]
>  I don't think we need to support 2 cycles if we have a smooth transition process between major bumps.

I'll give this some thought... less is more after all. :)

> So, for example 4.4 is LTS and the next release is 5.0. 5.0 is identical to 4.4 with the exception that deprecations were removed.

I don't think that works for everything since not everything is an API call or an API deprecation.  As v11 gets closer you can review the full breaking changes list and then we can focus on how the individual items (that aren't API deprecations) might fit into this kind of plan (if at all).

**Comment by joshgoebel** [comment]
Related: Dropping support for v12 Node today since Node.js has also dropped support (and `jsdom` as well).

Closing this issue as resolved for now.
