### ISSUE TITLE
Please allow "make" as alias for "makefile"

### ISSUE THREAD

**Issue by tripleee** [highlightjs/highlight.js#2883]
Could you please allow ` ```make` as a convenient shorthand for ` ```makefile`? This is definitely more guessable than the [currently supported](https://github.com/highlightjs/highlight.js/blob/master/SUPPORTED_LANGUAGES.md) aliases ` ```mk` and ` ```mak`, and the name of the actual command you use to run a `Makefile`.

**Comment by joshgoebel** [comment]
Hmmmm... are there any other makes our there other than GNU make that would make "make" ambiguous?

**Comment by tripleee** [comment]
The original `make` from 1976 is the lowest common denominator here; GNU `make` significantly extends the syntax in ways which are incompatible with e.g. BSD `make` and `nmake` but that is really beside the point here. All of these use `make` as the command name (at least as an option; I suppose `nmake` is most commonly invoked with that name) and `Makefile` as the standard input file name, with random `.mk` and probably occasionally `.mak` files as a common convention for nonstandard input files. For more background, see https://en.wikipedia.org/wiki/Make_(software)

**Comment by joshgoebel** [comment]
@allejo Any thoughts?  I don't think I'm opposed to this.  We'd need:

- [ ] Update SUPPORTED_LANGUAGES
- [ ] Update makefile.js

**Comment by joshgoebel** [comment]
@tripleee Are you wanting to pull together a small PR for this if we green light?

**Comment by tripleee** [comment]
I can try to step in if there's nobody around who is familiar with Javacript in general and this project in particular.

**Comment by joshgoebel** [comment]
No one is around if everyone asks that first. ;-)  "Be the change you want to see in the world." - Gandhi

Plus I always try to encourage new contributors - doubly so for easy things.  If you cut your teeth on just adding an alias then perhaps when you see how deficient the Makefile grammar is you'll be more tempted to come back and make a contribution to improve it. :-)  That's just a hope of course. :-)
