### ISSUE TITLE
Scheme -  inconsistent highlighting

### ISSUE THREAD

**Issue by johbra** [highlightjs/highlight.js#2890]
The highlighting of the Scheme function
`(define add-point
    (lambda [p1 p2]
      (make-point
        (+ (point-x p1) (point-x p2))
        (+ (point-y p1) (point-y p2)))))`
using the following HTML document
`<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8"/>
        <link rel="stylesheet"
              href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.4.0/styles/default.min.css">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.4.0/highlight.min.js"></script>
        <script charset="UTF-8" src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.4.0/languages/scheme.min.js"></script>
        <script>hljs.initHighlightingOnLoad();</script>
    </head>
    <body>
        <h2>Code example</h2>
        <pre><code class="scheme">(define add-point
  (lambda [p1 p2]
    (make-point
      (+ (point-x p1) (point-x p2))
      (+ (point-y p1) (point-y p2)))))
        </code></pre>
    </body>
</html>
`
yields inconsistent highlighting: The fourth line of the function had to be highlighted exactly as the fifth line. But that's not the case.

**Comment by joshgoebel** [comment]
<img width="667" alt="Screen Shot 2020-11-23 at 9 31 53 PM" src="https://user-images.githubusercontent.com/6473/100039477-5279de80-2dd3-11eb-8573-b7521c55fd88.png">

Strange indeed.

**Comment by joshgoebel** [comment]
May need a language champion for Scheme to sort this out.  This type of syntax just give me a headache. :)

```
  var LAMBDA = {
    className:"lambda",
    begin: /lambda/,
    endsWithParent: true, returnBegin: true,
    contains: [
      NAME,
      {
        begin: /\(/, end: /\)/, endsParent: true,
        contains: [IDENT],
      }
    ]
  };
```

Our grammar expects a lambda to have a "name" and then parens and a list of "idents" (which we don't color).

So it seems that first ( and then does nothing until it finds the first closing ), which snaps it back out of lambda and normal highlighting resumes.

**Comment by joshgoebel** [comment]
Is there another form where you pass the lamba arguments with `()` vs `[]`?

**Comment by johbra** [comment]
Maybe, the problem is that I'am using a variant of Scheme (Racket) where (x) can be replaced by [x] or {x} everywhere. So the expressions `(lambda [x] (* x x))`  and `(lambda (x) (* x x))` are equivalent, for example.

**Comment by joshgoebel** [comment]
Is that a popular variant?  Is that the only difference?

**Comment by johbra** [comment]
All I can say: [Racket](https://racket-lang.org) became popular by the well known text book [How to design programs](https://htdp.org).

I am not sure but I don't know any further syntactical differences.

**Comment by joshgoebel** [comment]
What are () and {} used for in typical scheme?

**Comment by johbra** [comment]
All but simple expressions like numbers or symbols are enclosed in (). [] and {} aren't used at all.

**Comment by joshgoebel** [comment]
Think it would be helpful if we had another Scheme person to weigh in on this.

Isn't `[]` a list in Scheme?

**Comment by lechten** [comment]
I'm not a Scheme person, I use Emacs Lisp. 

No, lists in Scheme are defined with round parentheses. Square brackets are allowed in some implementations, but they are reserved for future use, see there: http://community.schemewiki.org/?scheme-faq-language#H-yoyi82

They are still reserved in [R7RS](https://small.r7rs.org/attachment/r7rs.pdf).
