### ISSUE TITLE
SyntaxError: Unexpected token 

### ISSUE THREAD

**Issue by jduval23** [highlightjs/highlight.js#2904]
The following change:
https://github.com/highlightjs/highlight.js/commit/373b9d862401162e832ce77305e49b859e110f9c#diff-a22d79c61d34b336a15f45f37dd494693dc3fe5aadc5f85e05b3c97e65075f2bR162

Is causing the following error:

/node_modules/highlight.js/lib/languages/perl.js:186
           ),
           ^
 SyntaxError: Unexpected token )
     at createScript (vm.js:56:10)
     at Object.runInThisContext (vm.js:97:10)

**Comment by joshgoebel** [comment]
Node version?

**Comment by jduval23** [comment]
node v6.11.0 (npm v3.10.10)

**Comment by jduval23** [comment]
We upgraded to v10 and all is well
