### ISSUE TITLE
0 width match regex

### ISSUE THREAD

**Issue by svanimpe** [highlightjs/highlight.js#2906]
Hi,

I'm trying to create a `LITERAL` mode that can match any literal, so that I can easily include literals in other modes.

I tried the following:

```
  const LITERAL = {
    keywords: SWIFT_KEYWORDS.literal,
    variants: [
      NUMBER,
      STRING,
    ]
  };
```

Unfortunately, that doesn't work. When I run the developer tool, I see a "0 width match regex" error in the console.

What am I doing wrong?

**Comment by svanimpe** [comment]
Is this because NUMBER and STRING already have variants? If so, is this a bug, and how do I work around it? I'm pretty much stuck until I can get around this, as I have to implement a lot of grammars with options like this.

**Comment by joshgoebel** [comment]
> Is this because NUMBER and STRING already have variants? 

That's definitely one issue. `variants` don't nest. 

> I'm trying to create a LITERAL mode that can match any literal

We have no concept of "grouping" like this (we don't tend to group modes at this abstraction level)... typically you'd just put all the modes into an array and then include it in an appropriate `contains` block.

```js
LITERALS = [STRING, NUMBER, etc]
blah.contains = [].concat(LITERALS, ...)
```

**Comment by joshgoebel** [comment]
> Is this because NUMBER and STRING already have variants?

Yes, what is happening is that because there is no nesting then NUMBER and STRING end up being "empty" rules which match nothing (0 width)... hence the error you're seeing.

**Comment by svanimpe** [comment]
Thanks, that explains it!
I think I can work around these issues now. I just have to stop myself from overcomplicating the grammar 😅 I still think too much in terms of an actual language grammer, instead of a highlighting grammar.
