### ISSUE TITLE
Javascript not always recognized

### ISSUE THREAD

**Issue by step135** [highlightjs/highlight.js#2910]
Example:
```
var f=45
new OptimizeCSSPlugin({
cssProcessorOptions: config.build.productionSourceMap
? { safe: true, map: { inline: false } }
: { safe: true }
})
```

**Comment by joshgoebel** [comment]
Auto detection is best effort and not guaranteed. The problem is that it’s not a large enough sample to accurately determine the language.

**Comment by step135** [comment]
Should your reaction be understood that you don't care about this feature anymore?

**Comment by joshgoebel** [comment]
Not at all.  Read CHANGES.md.  We make improvements to auto-detect regularly.  It's a key differentiating feature, but it is not magic.  At best it's accurate 80-90% of the time when given a large enough snippets of text (and when the languages used for auto-detect are scoped narrowly).  Using only a few languages will have better results than using the default web build, but even that will have better results than just loading the whole library (and all languages) via Node, etc.

What you are seeing here (with this small JS snippet) is merely the limits of the existing auto-detect system - not a "bug" (ie there is nothing immediately to "fix"), which is what my original response tried to state clearly and directly.

If every issue like this was left open we'd just have a forum full of "hey auto-detect doesn't work on my small snippet".

Context:
https://github.com/highlightjs/highlight.js/issues/1213

**Comment by joshgoebel** [comment]
For *many* use cases where it's hard or impossible to manually identify the code snippet auto-detect can be quite useful even when making a "best guess"... and sometimes that doesn't work well at all... that's par for the course.

If you have experience with such things and think you could help improve them, we're all ears, but it's a non-trivial problem.  Also auto-detect is not our -primary- use case - that is highlighting.

**Comment by joshgoebel** [comment]
@allejo @egor-rogov It's also possible there is room for a docfix here, though this issue doesn't come up so commonly anymore.

**Comment by allejo** [comment]
I do have a [warning in `highlight.php`](https://github.com/scrivo/highlight.php#automatic-language-detection-mode) about autodetection not being magic. I don't think there'd be any harm in making that clear in highlight.js

**Comment by joshgoebel** [comment]
I'd be fine with some verbiage along those lines somewhere in the readme. :)  @step135 Would that have helped you though?  I always wonder about just adding things to the README how many people actually read it. :)
