### ISSUE TITLE
[Request] Support word diff (--word-diff)

### ISSUE THREAD

**Issue by sgkoishi** [highlightjs/highlight.js#2911]
**Is your request related to a specific problem you're having?**
The `diff` support currently is at the line level (lines that start with -/+). It would be great to support word diff (via `git show --word-diff`).

| diff | word diff |
|:-|:-:|
| `-The quick brown fox jumps over the lazy dog`<br>`+A quick brown fox jumps over the lazy dog` | `[-The-]{+A+} quick brown fox jumps over the lazy dog` |

**The solution you'd prefer / feature you'd like to see added...**
The word diff is an extension of `diff`, so `[-The-]{+A+} quick brown fox jumps over the lazy dog` will have different meaning for diff and word diff. It might be better to add a modified version of `diff` called `worddiff` as a new language option.

**Comment by joshgoebel** [comment]
Yes, it seems clear worddiff and diff are different grammars.  

Our policy on language requests:

https://github.com/highlightjs/highlight.js/blob/master/docs/language-requests.rst

Closing this issue per policy.  If you’d like to make a third-party grammar for this though that would be awesome.

**Comment by RokeJulianLockhart** [comment]
@joshgoebel, I see that [`blob/e056e2d229cf1b263e42a772d79b1da29a4b1e64/docs/language-requests.rst?plain=1#L13C14-L23C58`](https://github.com/highlightjs/highlight.js/blob/e056e2d229cf1b263e42a772d79b1da29a4b1e64/docs/language-requests.rst?plain=1#L13C14-L23C58:~:text=the%20project%20works%20by%20encouraging,developer%20interested%20in%20doing%20so.) states:

https://github.com/highlightjs/highlight.js/blob/e056e2d229cf1b263e42a772d79b1da29a4b1e64/docs/language-requests.rst?plain=1#L13-L23

Does this mean that we need to locate a reference implementation, like [`github-linguist/linguist/issues/7134`](https://github.com/github-linguist/linguist/issues/7134#issue-2679560304) suggests, or must we state that we are willing to maintain it here, too? I ask per [`meta.discourse.org/387410/3`](https://meta.discourse.org/t/the-syntax-highlighter-doesnt-support-word-diff-s/387410/3?u=rokejulianlockhart), which is affected downstream by this.
