### ISSUE TITLE
(CPP) The highlighter doesn't support variadic templates/parameter packs

### ISSUE THREAD

**Issue by mortie** [highlightjs/highlight.js#2917]
**Describe the issue**

This is valid C++ syntax:

``` C++
template<typename... T>
void foo(const T &... args) {}
```

Yet, when highlighting with `highlight`, the returned object's `illegalBy.msg` is `Illegal lexeme "." for mode "function"`.

**Which language seems to have the issue?**

`cpp`

**Are you using `highlight` or `highlightAuto`?**

`highlight`

**Sample Code to Reproduce**

Here's a modified version of the example JSFiddle: https://jsfiddle.net/dueh84nq/1/ - I changed it to display the illegal/illegalBy values.

**Expected behavior**

Since the syntax is legal, I would expect it to be highlighted somehow, not rejected as illegal.

**Additional context**

Here's some info on C++'s parameter packs: https://en.cppreference.com/w/cpp/language/parameter_pack

**Comment by joshgoebel** [comment]
```
illegal: /[^\w\s\*&:<>]/,
```

Dropping `.` into this list of what is valid (since it's negated) would likely resolved.  Want to try making a PR?
