### ISSUE TITLE
C/C++ Incorrect highlighting for LL suffix

### ISSUE THREAD

**Issue by phuclv90** [highlightjs/highlight.js#2919]
**Describe the issue**
Only the first `L` is highlighted when the `LL` integer literal suffix is used

**Which language seems to have the issue?**
C and C++

**Are you using `highlight` or `highlightAuto`?**
I don't know. I've just seen the issue on StackOverflow
...

**Sample Code to Reproduce**

No code, but some questions where the issue occurs

- https://stackoverflow.com/questions/15575054/what-does-ll-mean
- https://stackoverflow.com/questions/33377358/integer-overflow-in-boolean-expressions/33377537#33377537
- https://stackoverflow.com/questions/65318714/expression-evaluation-in-32-bit-cpu

Screenshot:

[![Screen Shot 2020-12-16 at 3 36 59 PM](https://user-images.githubusercontent.com/9285512/102324824-f14dc100-3fb4-11eb-9b5e-42e8f5d6ace8.png)](https://stackoverflow.com/questions/33377358/integer-overflow-in-boolean-expressions/33377537)
 
**Expected behavior**
Both Ls should be highlighted

**Additional context**

**Comment by joshgoebel** [comment]
Never hard of `LL` before... shouldn't be a hard fix I don't think.  Care to try for a PR?

**Comment by phuclv90** [comment]
It's the suffix for `long long` which existed as an extension for decades, and was [officially added to C99](https://en.cppreference.com/w/c/language/arithmetic_types) more than 20 years ago

**Comment by joshgoebel** [comment]
Good to know.  Want to try contributing a PR? :)

**Comment by phuclv90** [comment]
Sorry I haven't looked at the source code of highlight.js yet, and currently I don't have enough time to look through it. May be at the weekend

**Comment by joshgoebel** [comment]
Current rule:

```
begin: '(-?)\\b([\\d\']+(\\.[\\d\']*)?|\\.[\\d\']+)(u|U|l|L|ul|UL|f|F|b|B)'
```
