### ISSUE TITLE
(properties) Incorrect handling of trailing escaped backslash

### ISSUE THREAD

**Issue by Hirse** [highlightjs/highlight.js#2922]
**Describe the issue**
Properties files support multi-line values by using a `\` to escape the newline. This works correctly for most cases, but breaks when the last character is an escaped `\` (i.e. `\\`), which might be the case in a Windows path (`folder-path = C:\\some\\path\\`)

![image](https://user-images.githubusercontent.com/2564094/102387378-27734c80-3f85-11eb-8a85-ee4efdf5ab04.png)

**Which language seems to have the issue?**
`properties`

**Are you using `highlight` or `highlightAuto`?**
highlight

**Sample Code to Reproduce**
```properties
a = a1\
    a2
b = b\\
c = c
```

**Expected behavior**
![image](https://user-images.githubusercontent.com/2564094/102387448-3fe36700-3f85-11eb-9826-24299046da62.png)

**Comment by joshgoebel** [comment]
Thanks, I feel like we've fixed something like this in other grammars... probably just a matter of adding a separate rule to silently eat `\\` so it's not counted by the `\` before the end of line rule?

Haven't looked just guessing.
