### ISSUE TITLE
Introducing highlight.js-screenshot

### ISSUE THREAD

**Issue by GerbenRampaart** [highlightjs/highlight.js#2929]
Is you want to take screenshots of the code highlighted by highlight.js, you can now use highlight.js-screenshot!

https://www.npmjs.com/package/highlight.js-screenshot

This will use highlight.js to highlight your code and then screenshot it with puppeteer. This is useful for when you want images of example code for i.e. documentation purposes servers-side.

In other words, you can nodejs with highlight.js to generate code images without using a client browser.

**Comment by GerbenRampaart** [comment]
Closing because it's not an actual issue obviously.

**Comment by joshgoebel** [comment]
> This package needs at least nodejs 8.10.x or higher

We don't officially support anything below 10, just FYI.  But it may work.

**Comment by GerbenRampaart** [comment]
Hi josh thanks for the pointer. I’ll release the package with a 10 minimum as well to keep in line with highlight.js. I’d say no one is using it yet so I won’t be breaking anything.

**Comment by GerbenRampaart** [comment]
Updated. Now requires node 10. See Changelog 
https://github.com/GerbenRampaart/highlight.js-screenshot/blob/master/CHANGELOG.md
