### ISSUE TITLE
Troubles with building a syntax file

### ISSUE THREAD

**Issue by miken32** [highlightjs/highlight.js#2931]
I'm attempting to write a syntax file for Laravel Blade to contribute, and I am coming up against a wall trying to get single word directives like `@continue` to highlight, which seems like it should be simple enough. 

Additionally there are more complex directives like `@for($i = 0; $i < 2; $i++)` which I want highlighted and their contents treated like PHP.

I've posted a question on SO, but figured it was pretty niche and posting here might help get some eyeballs on it.

https://stackoverflow.com/questions/65364723/having-trouble-capturing-blade-directives-with-highlight-js

And here's the code I have so far, in case someone doesn't like external links:
```javascript
export default function(hljs) {
  const EXPRESSION_DIRECTIVES = {
    $pattern: /@[a-zA-Z]+/,
    'template-tag': [
      'case', 'each', 'elseif', 'empty', 'env', 'error', 'extends', 'for', 'foreach', 'forelse',
      'hasSection', 'if', 'include', 'includeFirst', 'includeIf', 'includeUnless', 'includeWhen',
      'inject', 'isset', 'method', 'prepend', 'section', 'sectionMissing', 'stack', 'switch',
      'unless', 'while', 'yield'
    ].map(v => '@' + v).join(" ")
  };

  const STANDALONE_DIRECTIVES = {
    $pattern: /@[a-zA-Z]+/,
    'template-tag': [
      'auth', 'break', 'continue', 'csrf', 'default', 'else', 'endauth', 'endempty', 'endenv',
      'enderror', 'endfor', 'endforeach', 'endforelse', 'endguest', 'endif', 'endisset', 'endphp',
      'endprepend', 'endproduction', 'endpush', 'endsection', 'endswitch', 'endunless', 'endwhile',
      'guest', 'once', 'parent', 'php', 'production', 'props', 'push', 'show'
    ].map(v => '@' + v).join(" ")
  };

  return {
    name: 'Blade',
    case_insensitive: true,
    subLanguage: 'xml',
    contains: [

      hljs.COMMENT(/\{\{--/, /--\}\}/),

      // output with HTML escaping
      {
        className: 'template-variable',
        begin: /\{\{/,
        starts: {
          end: /\}\}/,
          returnEnd: true,
          subLanguage: 'php',
        },
      },
      {
        className: 'template-variable',
        begin: /\}\}/,
      },

      // output with no HTML escaping
      {
        className: 'template-variable',
        begin: /\{!!/,
        starts: {
          end: /!!\}/,
          returnEnd: true,
          subLanguage: 'php',
        },
      },
      {
        className: 'template-variable',
        begin: /!!\}/,
      },

      // directly inserted PHP code
      {
        className: 'template-tag',
        begin: /@php/,
        starts: {
          end: /@endphp/,
          returnEnd: true,
          subLanguage: 'php',
        },
        relevance: 10
      },

      // directives with arguments like @yield('foo')
      {
        begin: /@([a-zA-Z]+)\s*\(/,
        keywords: EXPRESSION_DIRECTIVES,
        starts: {
          end: /\)/,
          returnEnd: true,
          subLanguage: 'php'
        }
      },

      // directives without arguments like @section
      {
        begin: /@([a-zA-Z]+)/,
        keywords: STANDALONE_DIRECTIVES,
      },

    ]
  };
}
```

**Comment by joshgoebel** [comment]
That will never work because @ isn't in the default `$pattern`.  

You may want to checkout:

- $pattern - https://highlightjs.readthedocs.io/en/latest/mode-reference.html#lexemes-now-keywords-pattern
- `beginKeywords` might also help you

**Comment by joshgoebel** [comment]
You should also know we don't merge new grammars into the project currently (maintainers don't have time to review or maintain them)... but you're more than welcome to publish your grammar as a 3rd party grammar when finished.

https://highlightjs.readthedocs.io/en/latest/language-contribution.html

**Comment by joshgoebel** [comment]
If you get `keywords` right though you shouldn't even need a rule for simple things like `@section`.

**Comment by joshgoebel** [comment]
Those relevances are pretty scary if you ever plan to participate in auto-detection.  Mostly you should not use relevance (other than to set it to 0).  The only thing I see here that might deserve a 10 is `@php` - though `@phpend` would be far better to give the points too, since it's longer and more specific.

**Comment by miken32** [comment]
@joshgoebel thanks for the tips. I've removed the relevance definitions altogether. By adding `$pattern: /@[a-zA-Z]+/` to the keyword objects and moving the rules for the less-specific "standalone" directives below those for the "expression" directives, I was able to get it 95% of the way there. (Clearly, getting `keywords` "right" is beyond me as I haven't been able to avoid having a rule block!)

Now I'm just trying to figure out how to break out of the PHP mode after an expression directive. Relying on `)` as an end marker isn't great since that could be part of some valid PHP code, so in its simplest form like `@foreach ($foo as $bar)` it works fine, but `@if ($foo * (12 + $i) > 245)` breaks. Any thoughts on how to manage it?

**Comment by joshgoebel** [comment]
> Now I'm just trying to figure out how to break out of the PHP mode after an expression directive. Relying on ) as an end marker isn't great since that could be part of some valid PHP code,

Yeah, that's very hard... we don't have great tools for this.  You hope that either:

- The end tag is VERY unique and never naturally occurs inside the sublangage.
- Or that when it does you can "match around it"... for example `?>` in PHP could appear inside a string so `php-template` has to match strings and SKIP them to avoid the mode ending prematurely.

But for something like `)` this gets very hard without being able to parse the language... you could try to write a regex that counts parens, but that would also need to take strings and other things into account.

**Comment by joshgoebel** [comment]
> Clearly, getting keywords "right" is beyond me as I haven't been able to avoid having a rule block!)

Keywords are matched last "inside modes"... so if you have a mode that matches on "start ... stop":

```
{
begin: /start/,
end: /stop/,
keywords: // ...
}
```

Then anything INSIDE that is what keywords are applied to including the start/stop itself (because it's part of the "buffer")... this is why we have things like excludeEnd and excludeBegin to keep them out of the buffer for various reasons.

**Comment by joshgoebel** [comment]
Closing this as an issue but if you have any questions you can still feel free to ask.

**Comment by miken32** [comment]
I did manage to get the keyword stuff working without explicit definitions. I gave up on the PHP parsing inside parentheses as it was too complicated, but I don't think that's a show-stopper. Can we get this set up as a third-party plugin?

**Comment by joshgoebel** [comment]
Just make a PR adding a link to the repo to SUPPORTED_LANGUAGES.  I'd recommend the repo follow the template of our many other 3rd party grammar repos with a nice README, `dist/grammar.js` CDN pre-built asset, etc.

**Comment by miken32** [comment]
Ok will do. I noticed the others in the list were all hosted under highlightjs organization and wasn't sure if you did external ones.

**Comment by joshgoebel** [comment]
>  I noticed the others in the list were all hosted under highlightjs organization and wasn't sure if you did external ones.

Not all. There are some externals ones.  Up to you.
