### ISSUE TITLE
Raku language support

### ISSUE THREAD

**Issue by melezhik** [highlightjs/highlight.js#2933]
Hi! Is it possible to add Raku language support. So far highlight.js consider my code as a `javascript` or `Perl` which is of course is not true.

Examples:

* https://sparrowhub.io/plugin/ambari-hosts/0.000001

* https://sparrowhub.io/plugin/ado-permissions-calculator/0.000006

**Comment by joshgoebel** [comment]
Please see our docs:

- https://highlightjs.readthedocs.io/en/latest/language-contribution.html
- https://highlightjs.readthedocs.io/en/latest/language-requests.html

Short answer is we don't currently add languages to the core library but anyone can easily publish 3rd party add-ons that are super easy to use to extend Highlight.js, such as adding entirely new grammars, etc.

**Comment by joshgoebel** [comment]
Also maybe: https://github.com/highlightjs/highlightjs-raku

**Comment by melezhik** [comment]
Thank you!
