### ISSUE TITLE
IE11 Object doesn't support property or method 'forEach'

### ISSUE THREAD

**Issue by limonte** [highlightjs/highlight.js#2940]
Since https://github.com/highlightjs/highlight.js/commit/3198e92629c8c09f9372e279dd833884e4edb839 the highlighting in IE11 is broken:

> SCRIPT438: Object doesn't support property or method 'forEach'

The reason:

https://github.com/highlightjs/highlight.js/blame/82f7a68cef989d2de3aa2b02faf2f80f6ce7ee60/src/highlight.js#L746-L747

The solution: 

```js
Array.from(NodeList).forEach(...)
```

**Comment by joshgoebel** [comment]
We purposely do not support IE11 and have not since version 10.  Sorry.
