### ISSUE TITLE
Moderate severity security issue for v9

### ISSUE THREAD

**Issue by limonte** [highlightjs/highlight.js#2942]
Because of https://github.com/highlightjs/highlight.js/issues/2501 I have to stick to v9

Unfortunately, there's a security issue with v9: https://github.com/advisories/GHSA-7wwv-vh3v-89cq

@joshgoebel I understand that the support of v9 is stopped, but are you may be planning to fix security vulnerabilities?

**Comment by limonte** [comment]
For the record: for my project, I use `10.4.1` because it seems to still work in IE11 and there are no security issues.

**Comment by joshgoebel** [comment]
> Unfortunately, there's a security issue with v9: GHSA-7wwv-vh3v-89cq

Yes, I mentioned that when I suggested 9 - it all depends on how you are using it.  _No, v9 is *entirely unsupported* and security issues will not be fixed._  All security issues are resolved in v10 and the correct fix for 99% of users is to upgrade to v10.

> For the record: for my project, I ended up using 10.4.1 because it seems to still work in IE11 

Awesome.  Glad you found a solution.  10.4.1 is certainly much nicer than a very old 9.

**Comment by limonte** [comment]
Thank you for the prompt and detailed answer @joshgoebel!

**Comment by joshgoebel** [comment]
Out of curiosity what is the nature of your use case that prevents you from dropping IE11 support entirely?

**Comment by limonte** [comment]
> Out of curiosity what is the nature of your use case that prevents you from dropping IE11 support entirely?

I'm STILL seeing people using IE11 very often. More often than I'd like to :) E.g. in schools or government structures like the tax administration. For schools, it's the lack of resources I guess, but for the tax administration office, it's the security. The first rule of sysadmins is: if it ain't broke, don't fix it. IE11 works for them for ages and they do not want to change it because of 1. security and 2. people already familiar with IE11 for ages.

**Comment by joshgoebel** [comment]
I'm not sure security is ever a word I'd associate with IE11, but perhaps it's gotten better since it's popularity has waned.  I still remember when ME was releasing security fixes for IE like every single week. :)

**Comment by limonte** [comment]
> I'm not sure security is ever a word I'd associate with IE11

IE11 is part of the operating system. Any other browser is the _additional software_ which needs to go through the process of security review. Many people blindly trust Google these days, IMHO that's a bad idea.

**Comment by joshgoebel** [comment]
> IE11 is part of the operating system. 

I get that, but that doesn't make it secure. :)  I'm pretty sure no browser will ever be fully secure, but now we're off into a huge discussion. :)  I take your point though about "each piece of added software".

I'm just glad I don't have to deal with IE11 anymore.
