### ISSUE TITLE
[Request] Expose TypeScript types.

### ISSUE THREAD

**Issue by gluons** [highlightjs/highlight.js#2945]
**Is your request related to a specific problem you're having?**
Sometime I want to use some type from Highlight.js internal types. e.g. `Language`, `LanguageFn`.  
But I can't use it now.

**The solution you'd prefer / feature you'd like to see added...**
Expose all internal TypeScript types from `highlight.js`.  
So I can use it for more typing.

**Any alternative solutions you considered...**
No.

**Additional context...**
Types should be able to import like this.

```ts
import { LanguageFn, Language } from 'highlight.js';
```

**Comment by joshgoebel** [comment]
I'm not sure we can easily add additional exports using `declare module`... I really am not familiar with the type publishing types side of this equation. 

Do you know what that would look like?

**Comment by joshgoebel** [comment]
Also, please provide a list.  We're not going to export purely *internal* types because we do *not* wish to encourage their use, as anything that is not public API is subject to change at any time - and if you're consuming it then you do so at your own risk. 

Things I see that might be useful for plugin/grammar authors (at a quick glance):

- HLJSOptions
- Language
- LanguageFn
- Mode
- ModeCallback

**Comment by joshgoebel** [comment]
Though if we export them, do we then need to namespace them?  If so can we have them namespaces only externally?  These are the things I don't know and it would be great to have a TypeScript expert to help with.

**Comment by gluons** [comment]
The types that we may face are types that used in end-user functions.  
I think it's here.

- Mode
- HighlightResult (From `highlight`)
- AutoHighlightResult (From `highlightAuto`)
- HLJSOptions
- LanguageFn
- Language
- HLJSPlugin (From `addPlugin`)
- VuePlugin (From `vuePlugin`)

May need?
- Emitter (From `HighlightResult.emitter`)
- CompiledMode (From `HighlightResult.top`)
- illegalData (From `illegalBy`)

**Comment by gluons** [comment]
Typing is not easy for me. 😅  
I usually write code with TypeScript and let it generate types for me.  
Hope someone can help. 🥺

**Comment by joshgoebel** [comment]
> VuePlugin (From vuePlugin)

This is just the type we use for our VuePlugin... I'm not sure it's something we should expose.  Someone writing their own Vue plugin probably wants to declare their own type or use a built-in one in Vue maybe.

> HighlightResult (From highlight)
> AutoHighlightResult (From highlightAuto)

Don't you get these for free just by using the public API?  Why might someone need to declare one of these from scratch?  Perhaps one or two of the APIs allow the result to be replaced?  I'll check.  If so then this makes sense.

> Emitter (From HighlightResult.emitter)

Psuedo-private/beta... probably going to keep internal.

> CompiledMode (From HighlightResult.top)

CompiledModes are technically internal and subject to change at any moment.  Only compiler extensions should care about this and for now our guidance is those aren't really intended for 3rd party use.  Perhaps we need a way to flag things on `result` that are more for internal/debugging uses... (which is the intention of top)  Code that depends on it's internal structure is likely to be fragile.

> illegalData (From HighlightResult.illegalBy)

Same thought: debugging/internal usage.  Open to suggestions on how to flag these in the future, perhaps they should change to `_` prefix or some such?

**Comment by gluons** [comment]
> VuePlugin (From vuePlugin)

Yes. This type seems unnecessary.  
Vue already provides [`PluginObject`](https://github.com/vuejs/vue/blob/v2.6.12/types/plugin.d.ts#L5-L8) for plugin object (`{ install: (....) => {} }`).

<br>

> `Emitter`, `CompiledMode`, `illegalData`

Agree. Internal uses. May be unnecessary to use from public API.

<br>

> `HighlightResult`, `AutoHighlightResult`

May be used in function that accept result from Highlight.js.
e.g.

```ts
function processSomeResult(result: HighlightResult) {
	// ...
}
```

**Comment by joshgoebel** [comment]
Can you test our project from a checkout of Highlight.js from Git?  And just add export to a few lines and see if that magically does what you hope?

**Comment by gluons** [comment]
From master, right?

**Comment by joshgoebel** [comment]
Yes.

**Comment by gluons** [comment]
<details>
<summary>My edit</summary>

```diff
/* eslint-disable no-unused-vars */
/* eslint-disable no-use-before-define */
// For TS consumers who use Node and don't have dom in their tsconfig lib, import the necessary types here.
/// <reference lib="dom" />

/* Public API */

// eslint-disable-next-line
declare const hljs : HLJSApi;

type HLJSApi = PublicApi & ModesAPI

interface VuePlugin {
    install: (vue: any) => void
}

interface PublicApi {
    highlight: (languageName: string, code: string, ignoreIllegals?: boolean, continuation?: Mode) => HighlightResult
    highlightAuto: (code: string, languageSubset?: string[]) => AutoHighlightResult
    fixMarkup: (html: string) => string
    highlightBlock: (element: HTMLElement) => void
    configure: (options: Partial<HLJSOptions>) => void
    initHighlighting: () => void
    initHighlightingOnLoad: () => void
    registerLanguage: (languageName: string, language: LanguageFn) => void
    listLanguages: () => string[]
    registerAliases: (aliasList: string | string[], { languageName } : {languageName: string}) => void
    getLanguage: (languageName: string) => Language | undefined
    requireLanguage: (languageName: string) => Language | never
    autoDetection: (languageName: string) => boolean
    inherit: <T>(original: T, ...args: Record<string, any>[]) => T
    addPlugin: (plugin: HLJSPlugin) => void
    debugMode: () => void
    safeMode: () => void
    versionString: string
    vuePlugin: () => VuePlugin
}

interface ModesAPI {
    SHEBANG: (mode?: Partial<Mode> & {binary?: string | RegExp}) => Mode
    BACKSLASH_ESCAPE: Mode
    QUOTE_STRING_MODE: Mode
    APOS_STRING_MODE: Mode
    PHRASAL_WORDS_MODE: Mode
    COMMENT: (begin: string | RegExp, end: string | RegExp, modeOpts?: Mode | {}) => Mode
    C_LINE_COMMENT_MODE: Mode
    C_BLOCK_COMMENT_MODE: Mode
    HASH_COMMENT_MODE: Mode
    NUMBER_MODE: Mode
    C_NUMBER_MODE: Mode
    BINARY_NUMBER_MODE: Mode
    CSS_NUMBER_MODE: Mode
    REGEXP_MODE: Mode
    TITLE_MODE: Mode
    UNDERSCORE_TITLE_MODE: Mode
    METHOD_GUARD: Mode
    END_SAME_AS_BEGIN: (mode: Mode) => Mode
    // built in regex
    IDENT_RE: string
    UNDERSCORE_IDENT_RE: string
    NUMBER_RE: string
    C_NUMBER_RE: string
    BINARY_NUMBER_RE: string
    RE_STARTERS_RE: string
}

-type LanguageFn = (hljs?: HLJSApi) => Language
+export type LanguageFn = (hljs?: HLJSApi) => Language
type CompilerExt = (mode: Mode, parent: Mode | Language | null) => void

-interface HighlightResult {
+export interface HighlightResult {
    relevance : number
    value : string
    language? : string
    emitter : Emitter
    illegal : boolean
    top? : Language | CompiledMode
    illegalBy? : illegalData
    sofar? : string
    errorRaised? : Error
    // * for auto-highlight
    second_best? : Omit<HighlightResult, 'second_best'>
    code?: string
}
-interface AutoHighlightResult extends HighlightResult {}
+export interface AutoHighlightResult extends HighlightResult {}

interface illegalData {
    msg: string
    context: string
    mode: CompiledMode
}

type BeforeHighlightContext = {
  code: string,
  language: string,
  result?: HighlightResult
}
type PluginEvent = keyof HLJSPlugin;
-type HLJSPlugin = {
+export type HLJSPlugin = {
    'after:highlight'?: (result: HighlightResult) => void,
    'before:highlight'?: (context: BeforeHighlightContext) => void,
    'after:highlightBlock'?: (data: { result: HighlightResult}) => void,
    'before:highlightBlock'?: (data: { block: Element, language: string}) => void,
}

interface EmitterConstructor {
    new (opts: any): Emitter
}

-interface HLJSOptions {
+export interface HLJSOptions {
   noHighlightRe: RegExp
   languageDetectRe: RegExp
   classPrefix: string
   tabReplace?: string
   useBR: boolean
   languages?: string[]
   __emitter: EmitterConstructor
}

interface CallbackResponse {
    data: Record<string, any>
    ignoreMatch: () => void
}

/************
 PRIVATE API
 ************/

/* for jsdoc annotations in the JS source files */

type AnnotatedError = Error & {mode?: Mode | Language, languageName?: string, badRule?: Mode}

type ModeCallback = (match: RegExpMatchArray, response: CallbackResponse) => void
type HighlightedHTMLElement = HTMLElement & {result?: object, second_best?: object, parentNode: HTMLElement}
type EnhancedMatch = RegExpMatchArray & {rule: CompiledMode, type: MatchType}
type MatchType = "begin" | "end" | "illegal"

 interface Emitter {
    addKeyword(text: string, kind: string): void
    addText(text: string): void
    toHTML(): string
    finalize(): void
    closeAllNodes(): void
    openNode(kind: string): void
    closeNode(): void
    addSublanguage(emitter: Emitter, subLanguageName: string): void
 }

/* modes */

 interface ModeCallbacks {
     "on:end"?: Function,
     "on:begin"?: ModeCallback
 }

-interface Mode extends ModeCallbacks, ModeDetails {
+export interface Mode extends ModeCallbacks, ModeDetails {

}

interface LanguageDetail {
    name?: string
    rawDefinition?: () => Language
    aliases?: string[]
    disableAutodetect?: boolean
    contains: (Mode)[]
    case_insensitive?: boolean
    keywords?: Record<string, any> | string
    compiled?: boolean,
    exports?: any,
    classNameAliases?: Record<string, string>
    compilerExtensions?: CompilerExt[]
    supersetOf?: string
}

-type Language = LanguageDetail & Partial<Mode>
+export type Language = LanguageDetail & Partial<Mode>

interface CompiledLanguage extends LanguageDetail, CompiledMode {
    compiled: true
    contains: CompiledMode[]
    keywords: Record<string, any>
}

type KeywordData = [string, number];
type KeywordDict = Record<string, KeywordData>

type CompiledMode = Omit<Mode, 'contains'> &
    {
        contains: CompiledMode[]
        keywords: KeywordDict
        data: Record<string, any>
        terminatorEnd: string
        keywordPatternRe: RegExp
        beginRe: RegExp
        endRe: RegExp
        illegalRe: RegExp
        matcher: any
        compiled: true
        starts?: CompiledMode
        parent?: CompiledMode
    }

interface ModeDetails {
    begin?: RegExp | string
    match?: RegExp | string
    end?: RegExp | string
    className?: string
    contains?: ("self" | Mode)[]
    endsParent?: boolean
    endsWithParent?: boolean
    endSameAsBegin?: boolean
    skip?: boolean
    excludeBegin?: boolean
    excludeEnd?: boolean
    returnBegin?: boolean
    returnEnd?: boolean
    __beforeBegin?: Function
    parent?: Mode
    starts?:Mode
    lexemes?: string | RegExp
    keywords?: Record<string, any> | string
    beginKeywords?: string
    relevance?: number
    illegal?: string | RegExp | Array<string | RegExp>
    variants?: Mode[]
    cachedVariants?: Mode[]
    // parsed
    subLanguage?: string | string[]
    compiled?: boolean
    label?: string
}

// deprecated API since v10
// declare module 'highlight.js/lib/highlight.js';

declare module 'highlight.js' {
    export = hljs;
}

declare module 'highlight.js/lib/core' {
    export = hljs;
}

declare module 'highlight.js/lib/core.js' {
    export = hljs;
}

declare module 'highlight.js/lib/languages/*' {
    export default function(hljs?: HLJSApi): LanguageDetail;
}
```

</details>

---

It seems work on main module but it breaks `/lib/core` module. 😞

![ภาพ](https://user-images.githubusercontent.com/4688092/103434865-d37d8e80-4c39-11eb-91b1-6400bdba8c3c.png)

![ภาพ](https://user-images.githubusercontent.com/4688092/103434821-1b4fe600-4c39-11eb-9205-df770c1f1d74.png)

![ภาพ](https://user-images.githubusercontent.com/4688092/103434886-0889e100-4c3a-11eb-9293-d3f7ed6cc797.png)

**Comment by joshgoebel** [comment]
I don't think this can work because we purposely use default export for highlight.js. IE:

```
import hljs from 'highlight.js';
```

This is fundamentally incompatible with named exports.  I'd be curious to know how other libs do this.

**Comment by peterblazejewicz** [comment]
@joshgoebel 

the `index.d.ts` could export types/interfaces, it does not impact es6 exports.
you could, for example:

```ts
declare const hljs : HLJSApi;

export type HLJSApi = PublicApi & ModesAPI
..
..
..
export default hljs;

declare module 'highlight.js/lib/core' {
    export = hljs;
}

declare module 'highlight.js/lib/core.js' {
    export = hljs;
}

declare module 'highlight.js/lib/languages/*' {
    export default function(hljs?: HLJSApi): LanguageDetail;
}
```

and in other file:
```js
/**
 * @typedef {import('../types/index').HLJSPlugin} HLJSPlugin
 * @typedef {import('../types/index').Language} Language
 * @typedef {import('../types/index').HLJSApi} HLJSApi
 * @typedef {import('../types/index').HLJSOptions} HLJSOptions
 */
 ```
or via regular DT resolution.
the point is, the file has nothing exported, IMO
hth

**Comment by joshgoebel** [comment]
Anytime an export is added it breaks the declare modules with:

> module "highlight.js/lib/core"
Invalid module name in augmentation. Module 'highlight.js/lib/core' resolves to an untyped module at '/Users/jgoebel/work/highlight.js/build/lib/core.js', which cannot be augmented.ts(2665)

**Comment by peterblazejewicz** [comment]
IMO you don't have there anything, there is nothing to augment: (there is no `highlight.js/lib/core'):
https://github.com/highlightjs/highlight.js/tree/main/src/lib

**Comment by joshgoebel** [comment]
Ok, maybe that's an error that doesn't matter... `lib/core` exists in our final builds, but not our source tree.

But now if I add exports in the main body:

```
export type Language = LanguageDetail & Partial<Mode>
```

It still can't be imported later:

```
b.ts:1:22 - error TS2305: Module '"highlight.js"' has no exported member 'Language'.

1 import { LanguageFn, Language } from 'highlight.js';
```

I assume it's because it's not mentioned in our `declare module`:

```
declare module 'highlight.js' {
    export = hljs;
}
```

Which leads me back to... how can we tell TS that we're exporting the object (`hljs`) but also export types? Or perhaps that isn't possible because our source is JS, not TS?

**Comment by peterblazejewicz** [comment]
> b.ts:1:22 - error TS2305: Module '"highlight.js"' has no exported member 'Language'.

one needs to add explicit export here:
```ts
export type Language = ...
```
your current `.d.ts` has no explicit exports, only single top level object export. It won't auto export types, unless you introduce a namespace afaik.

**Comment by joshgoebel** [comment]
> one needs to add explicit export here:

_I added that locally, it make no difference._

I assume the `declare module` is overriding everything.

**Comment by joshgoebel** [comment]
> It won't auto export types, unless you introduce a namespace afaik.

I don't mind flagging what needs to be exported myself, I just have no idea how to do it.

**Comment by peterblazejewicz** [comment]
is this to be used within project itself, or for consumption by users? (kind of @types/higlight.js)

**Comment by joshgoebel** [comment]
Both.  I use it for inside editor Linting but it should also work in place of `@types/higlight.js` (all @types/highlight.js is re-export us).

**Comment by peterblazejewicz** [comment]
so your project looks different once built and published. there are `lib/core/index.js` and `lib/core.js`. The old DT would also incorporate 'index.d.ts' on the root level to just re-export main objet and - important - to define and export shared types. Then within `lib` declarations people are just importing types from root definition for consumption. I'll check this tmrw. Also, you could also raise that topic on the TypeScirpt discord. A lot of people knows higliht.js: https://discord.gg/UHDsndNs

**Comment by joshgoebel** [comment]
>  there are lib/core/index.js...

No, but there is `lib/core.js` and `lib/index.js` and soon `lib/common.js`.  Which all just include a different # of languages (0, common, all) and re-export the main object.

> also incorporate 'index.d.ts' on the root level

Are you saying the file must be at the top of the package?  Is this not what package.json `types` is for to allow placement of this main file anywhere?

Most of what you said is greek to me, sorry.  I really need a specific example or PR I think.

**Comment by joshgoebel** [comment]
@gluons Can you see if this helps?

**Comment by peterblazejewicz** [comment]
@joshgoebel #3075 sample for showing the possible iteration.
This one is based on the consumption in local project (TS/TSC)

**Comment by joshgoebel** [comment]
That's about the same as what I did in #3073 but using multiple files, right?

**Comment by peterblazejewicz** [comment]
Yes, + named export for global, non module, usage (if you care about those users)

**Comment by gluons** [comment]
OK. I'll try at weekend.

**Comment by gluons** [comment]
@joshgoebel I've tested #3073 with fresh project.  
Types can be imported. it works very well.  
But `highlight.js/lib/core` can't be imported.

![ภาพ](https://user-images.githubusercontent.com/4688092/113508803-46214180-957c-11eb-8a74-3f4cb7c10cea.png)

![ภาพ](https://user-images.githubusercontent.com/4688092/113508870-9dbfad00-957c-11eb-87fc-e5bc8ddc9edc.png)

**Comment by joshgoebel** [comment]
Can you zip your project or push it to a GitHub repo so I can pull it as-is?

**Comment by gluons** [comment]
@joshgoebel Here. I used local dependency that clone from #3073.

[hljs-test.zip](https://github.com/highlightjs/highlight.js/files/6259073/hljs-test.zip)

---

I don't know why it doesn't work. I've seen `src/core.d.ts` from #3073.  
I've tried to run `npm run build` in cloned repo but it doesn't generate `lib` directory.  
Is it unusual?

**Comment by joshgoebel** [comment]
> I've tried to run npm run build in cloned repo

The build artifacts are in `build`.

**Comment by joshgoebel** [comment]
I updated the relative path in package.json but it builds fine for me with 0 errors:

```
tsc src/*.ts
```

**Comment by gluons** [comment]
> The build artifacts are in `build`.

OK. Maybe my mistake.

![ภาพ](https://user-images.githubusercontent.com/4688092/113673081-b944c800-96e2-11eb-95dc-eb01fb2354dd.png)
![ภาพ](https://user-images.githubusercontent.com/4688092/113673143-ccf02e80-96e2-11eb-9ca0-02ee95a57c2a.png)

---

I've copied all build artifacts into new `highlight.js` directory as local dependency.  
It works very. Thank you.

![ภาพ](https://user-images.githubusercontent.com/4688092/113673941-cb733600-96e3-11eb-940c-39fbed926154.png)
![ภาพ](https://user-images.githubusercontent.com/4688092/113674091-fb223e00-96e3-11eb-9957-e9e643a85493.png)
![ภาพ](https://user-images.githubusercontent.com/4688092/113674337-489eab00-96e4-11eb-8ef7-0d9df5285d7b.png)

**Comment by joshgoebel** [comment]
Awesome!
