### ISSUE TITLE
How to add a button that can copy text in the code block?

### ISSUE THREAD

**Issue by awnawnawn** [highlightjs/highlight.js#2946]
I used **highlight.js** in **hexo**. I want to add a **copy** `code` text `button` to the **code block** in the article. How should I modify the `dom` structure?
![Snipaste_2021-01-04_22-58-06](https://user-images.githubusercontent.com/47672657/103548197-62abd000-4ee0-11eb-994a-6cb292153896.jpg)

**Comment by joshgoebel** [comment]
Just insert a `<div>` or `<button>` or whatever inside the `<pre>` and style it accordingly.  To fetch the raw text you'll want the `innerText` or `textContent` attribute of the `code` element.

**Comment by joshgoebel** [comment]
This would be easy pickings for someone to write a tiny plugin...

**Comment by bric3** [comment]
For reference I found a small plugin that seems to do that : https://github.com/arronhunt/highlightjs-copy
