### ISSUE TITLE
(VB and Objective-C) Unable to highlight

### ISSUE THREAD

**Issue by RanX12** [highlightjs/highlight.js#2949]
I use highlight + marked to display my code on the page. I have a total of 28 languages, among which VB and Objective-C cannot be highlighted. I have screenshots:
VB:
![image](https://user-images.githubusercontent.com/46048444/103723475-21650e80-500d-11eb-8ff5-deaed560ebaf.png)

--------

Objective-C:
![image](https://user-images.githubusercontent.com/46048444/103723547-478aae80-500d-11eb-95d3-c3b062229a94.png)

Other languages are possible, such as ```Java```

------

Java:

![image](https://user-images.githubusercontent.com/46048444/103723897-12329080-500e-11eb-9359-53a23ae7de6e.png)

I have tried here ([https://jsfiddle.net/RanX12/mh02yvzg/4/](https://jsfiddle.net/RanX12/mh02yvzg/4/)), they can be highlighted,

The version I use is 10.5.0

**Comment by joshgoebel** [comment]
> The version I use is 10.5.0

I'm not sure you were. Your fiddle was using 10.4.x.  The jsfiddle isn't really designed for testing multiple languages, but since `objectives` is built-in it will work when including vbnet as the grammar loaded via CDN:

https://jsfiddle.net/ajoshguy/srbh9z36/3/ (corrected Fiddle using 10.5)

---

Since the Fiddle seems to be working fine I would supposed the issue is with our project or website... quite possible the Highlight.js you are using does not have all your languages build in?  Are there any errors in your console? Add `hljs.debugMode()`... are there any errors in your console?

**Comment by RanX12** [comment]
w

> > 我使用的版本是10.5.0
> 
> 我不确定你是不是。您的小提琴使用的是10.4.x。jsfiddle并不是真正为测试多种语言而设计的，但是由于它`objectives`是内置的，因此当将vbnet包含为通过CDN加载的语法时，它将起作用：
> 
> https://jsfiddle.net/ajoshguy/srbh9z36/3/（已使用10.5纠正了Fiddle）
> 
> 由于小提琴似乎运行良好，所以我认为问题出在我们的项目或网站上……您使用的Highlight.js很可能没有内置所有语言？浏览器控制台中是否有任何错误？添加`hljs.debugMode()`到您的项目...控制台中是否有任何错误？

Thanks for your reply, I added ```highlight``` in ```marked.setOptions```, so I am not sure where ```hljs.debugMode()``` should be placed. When I did not add ```hljs.debugMode()```, there is no error message in my console.

![image](https://user-images.githubusercontent.com/46048444/103736524-66983900-502b-11eb-8505-17a5569cec44.png)

**Comment by joshgoebel** [comment]
Add `h.debugMode()` after you import `h`.

**Comment by joshgoebel** [comment]
<img width="645" alt="Screen Shot 2021-01-06 at 2 56 07 AM" src="https://user-images.githubusercontent.com/6473/103743829-be528800-4fca-11eb-9f5e-6d8060fcd802.png">

If marked was somehow incorrectly passing `language` here then it would stop working and break as you're seeing, perhaps adding some logging to make sure language is always correct would help?

Perhaps also log the FULL output of the `highlight()` call before returning just `value`.

**Comment by joshgoebel** [comment]
This will auto-close soon if we don't have any reproducible samples, exact steps to reproduce, etc.

**Comment by joshgoebel** [comment]
This can always be reopened if additional detail or a reproducible sample is provided.

**Comment by RanX12** [comment]
@joshgoebel hi, I didn’t have time to look at this recently. I took a look today. My version is indeed 10.5.0. At the same time, I also used your demo. It’s ok. I found that I can just delete a part of the code below. Successfully rendered,

```vb
' 必须定义一个 `Sub Main` 方法在顶层模型
Module ShowMeBug
  Sub Main()
    Console.WriteLine ("Hello, World")
    Dim Numlist() As Integer = {7, 8, 9, 4, 3, 2, 1, 5, 6}
    ' write your code here

    For i = 0 To Numlist.Length - 1
      Console.WriteLine(Numlist(i))
    Next
  End Sub
End Module
```
```Dim Numlist（）As Integer = {7，8，9，4，4，3，2，1，5，6} -->(change) Dim Numlist（）As Integer```
Then mine can be rendered successfully, as shown in the figure：
![image](https://user-images.githubusercontent.com/46048444/105679147-ff362080-5f28-11eb-8a3c-872624c90ace.png)

![image](https://user-images.githubusercontent.com/46048444/105679014-d0b84580-5f28-11eb-9de6-7d65c8910763.png)

**Comment by joshgoebel** [comment]
Please provide a jsfiddle with JUST a single example (your VB example would be great) that reproduces the problem.  

**I cannot reproduce this.**

<img width="532" alt="Screen Shot 2021-01-25 at 10 16 20 AM" src="https://user-images.githubusercontent.com/6473/105724982-6d152480-5ef6-11eb-9d65-b175fb7c2a41.png">

Works fine here.
