### ISSUE TITLE
(Ruby) Character literal notation not supported for some cases

### ISSUE THREAD

**Issue by Hirse** [highlightjs/highlight.js#2950]
**Describe the issue**
Only some cases of [Character Literals](https://docs.ruby-lang.org/en/3.0.0/doc/syntax/literals_rdoc.html) seem to be supported.
Support is missing for the following groups of cases (in decreasing importance):
- Single slash character (`?/`), breaks following lines as it gets treated as starting a regex
- Escaped backslash character (`?\\`)
- Non-ascii character (`?あ`)
- Unicode using curly-bracket notation (`?\u{1AF9}`)
- Control and Meta characters (`?\C-a`)

![Ruby Character Literals - Actual](https://user-images.githubusercontent.com/2564094/103803917-25d9f900-5006-11eb-9f32-744eafdd2946.png)

**Which language seems to have the issue?**
`ruby`

**Are you using `highlight` or `highlightAuto`?**
`highlight`

**Sample Code to Reproduce**
```ruby
c = ?a       #=> "a"
c = ?abc     #=> SyntaxError
c = ?\n      #=> "\n"
c = ?\s      #=> " "
c = ?\\      #=> "\\"
c = ?\u{41}  #=> "A"
c = ?\C-a    #=> "\x01"
c = ?\M-a    #=> "\xE1"
c = ?\M-\C-a #=> "\x81"
c = ?\C-\M-a #=> "\x81", same as above
c = ?あ      #=> "あ"


c = ?/          #=> /
c = ?\123       # octal bit pattern, where nnn is 1-3 octal digits ([0-7])
c = ?\xA1       # hexadecimal bit pattern, where nn is 1-2 hexadecimal digits ([0-9a-fA-F])
c = ?\uAF09     # Unicode character, where nnnn is exactly 4 hexadecimal digits ([0-9a-fA-F])
c = ?\cx        # control character, where x is an ASCII printable character
c = ?\c\M-x     # meta control character, where x is an ASCII printable character
c = ?\c?        # delete, ASCII 7Fh (DEL)
c = ?\C-?       # delete, ASCII 7Fh (DEL)
```

**Expected behavior**
![Ruby Character Literals - Expected](https://user-images.githubusercontent.com/2564094/103804513-19a26b80-5007-11eb-9a72-2e8b175f17f4.png)

**Additional context**
Seen in this StackExchange/CodeGolf answer: https://codegolf.stackexchange.com/a/217367/25026
```ruby
->(n,g=->c,d{(1..n).map{|i|" "*(n-i)+d+" "*2*(n+i-1)+c}},l=g[?/,e=?\\].reverse){[" "*n+?_*n*2,g[e,?/],l[0..-2],l[-1].sub(/ +(?=\/)/,?_*n*2)]}
```
![image](https://user-images.githubusercontent.com/2564094/103803726-d09de780-5005-11eb-895b-93988c9a95a4.png)

**Comment by joshgoebel** [comment]
Good find.  How did you get the expected behavior shot? :)  Is there a PR forthcoming? :)

**Comment by Hirse** [comment]
Agreed, most should be a simple regex change, though I don't quite understand why the single unicode char (`あ`) is not supported currently.

I might look into a PR later, but for the expected image I manually hacked the html. :D

**Comment by joshgoebel** [comment]
> I don't quite understand why the single unicode char (あ) is not supported currently.

It's not in the regex?

```
        begin: /\B\?(\\\d{1,3}|\\x[A-Fa-f0-9]{1,2}|\\u[A-Fa-f0-9]{4}|\\?\S)\b/
```

**Comment by Hirse** [comment]
`\S` seems to match unicode:
![image](https://user-images.githubusercontent.com/2564094/103816702-4449ef80-501a-11eb-9c79-bb11a1e44e2a.png)
https://regexr.com/5jodu

**Comment by joshgoebel** [comment]
Ah, but that character does not form a word boundary so `\b` will abort the match.

If we're going to fix this we need variants, not one big regex. :)
