### ISSUE TITLE
Hightlight commands in Dockerfile

### ISSUE THREAD

**Issue by jigarius** [highlightjs/highlight.js#2959]
Say, I use highlight-js with the contents of a `Dockerfile`. The main command keywords should be highlighted, e.g. `WORKDIR`, `COPY`, `RUN`, `ADD`, `EXPOSE`, etc.

**Comment by joshgoebel** [comment]
See `dockerfile.js`.  These are all already handled.

**Comment by joshgoebel** [comment]
If you're having a specific issue you'll need to provide more details or a JSFiddle to reproduce.

**Comment by jigarius** [comment]
Hi. Thank you for the quick response. I just took a look at the demo page one more time and I see that the strings are highlighted, but not those special keywords.

![Screen Shot 2021-01-12 at 9 21 40 AM](https://user-images.githubusercontent.com/4286033/104326298-975af100-54b7-11eb-968e-953706082d1a.png)

In the above screenshot, I was expecting to see a highlight on words like `MAINTAINER`, `WORKDIR`, `ENV`, `ARG`, `RUN`, and `CMD`.

**Comment by joshgoebel** [comment]
**They **are** indeed highlighted (in bold), try a different theme for a different appearance.**    Every theme is different.
