### ISSUE TITLE
Acces to props with vue component in callbacks

### ISSUE THREAD

**Issue by iNeoO** [highlightjs/highlight.js#2964]
Hi,

I'm using callback 'after:highlight' to add line number. is there a way in this callback to access to component props ?

Atm i m adding line number to every component highlighjs, i would like a way to pass a boolean or something from the component to conditionally add line numbers in the callback after:highlight

```html
      <highlightjs
        meta="test"
        title="test"
        test="test"
        language="x86asm"
        :code="hexa" />
```

```javascript
hljs.addPlugin({
  'after:highlight': (settings) => console.log(/* a way to access props */),
});
```

**Comment by joshgoebel** [comment]
I think you want `after:highlightBlock` and then just use the DOM to look at the attributes, no?

https://highlightjs.readthedocs.io/en/latest/plugin-api.html#after-highlightblock-block-result-text

**Comment by iNeoO** [comment]
i tried these callback (after:highlightBlock and before:highlightBlock) but in my case they are never triggered duno why 

```
    "highlight.js": "^10.5.0",
```

```javascript
import Vue from 'vue';
import hljs from 'highlight.js';
import x86asm from 'highlight.js/lib/languages/x86asm';

const AddLineModule = (result) => {
  const code = result.value;
  const codeWithNumber = code.split('\n').map((line, index) => `<tr><td class="hljs__line"><span>${index + 1}</span></td><td class="hljs__code">${line}</td></tr>`).join('\n');
  result.value = `<table class="hljs__table">${codeWithNumber}</table>`;
};

window.hljs = hljs;
hljs.registerLanguage('x86asm', x86asm);
hljs.addPlugin({
  'after:highlightBlock': AddLineModule,
});
Vue.use(hljs.vuePlugin);
```

maybe i did something the wrong way

**Comment by joshgoebel** [comment]
> but in my case they are never triggered duno why.

_My apologies_, I steered you down a dead-end there.  Easy to think of this as a "block" or HTML element being highlighted but it's not at all... it's component being rendered hence only `highlight` is ever called.

The Vue component was only recently added but I think long-term we may pull it out of core and into a separate repository (or at least a tiny separate library).  So I think going too deep on how it interacts (or doesn't) with plugins might be a little out-of-scope.  In any case it was always intended to be "bare-bones", just enough to get someone started and show them how they might do it themselves.

So I see three ways forward here:

- Do whatever you need to do with raw JavaScript (find all the pre/code blocks, examine them, take some action, etc) after the page is rendered (and forget about the plugin callbacks). 
- Perhaps use a Vue lifecycle hook (like `mounted` vs and after hook) on the component.  Not sure if this would require extending the component or not.
- Write a custom Vue plugin from scratch (though you could start with ours and modify it)

**Comment by joshgoebel** [comment]
>  So I think going too deep on how it interacts (or doesn't) with plugins might be a little out-of-scope.

I say this meaning Vue is not a core part of our library (and hence why it should probably be separated out as a mini lib)... so `highlight` has no way to know about the Vue component, or it's props, or even the webpage at all - _nor should it_. Since highlight does not run inside the context of a webpage.  It just takes text and outputs HTML.

Now one could argue that perhaps the plugin itself should simply render an unhighlighted block and then call `highlightBlock` to do the heavy lifting... that *might* be a more holistic approach (in a Vue centric world).  It does not seem 100% clear to me though that one approach is preferable vs another.

If someone wanted to make that argument, I'd be willing to listen (out of curiosity) and perhaps that is a change that could be considered for the plugin in the future (whether it stays in or moves out).

**Comment by iNeoO** [comment]
Hi, ok thanks for your help, i will stay like this for the moment and try to find a way with a new composent based on yours

**Comment by joshgoebel** [comment]
Good luck.  The component is quite simply and should be pretty easy to enhance... perhaps to add an after callback to it directly if such a thing is require.
