### ISSUE TITLE
Grunt build-minify fails on local Highlight.js file

### ISSUE THREAD

**Issue by kell18** [highlightjs/highlight.js#2966]
Hello,
The library fails with `grunt build-minify` command:
```
JS_Parse_Error {
  message: 'SyntaxError: Unexpected token: punc ())',
  filename: 'highlight.min.js',
  line: 7,
  col: 48,
  pos: 200,
  stack: 'Error\n' +
    '  at new JS_Parse_Error (<anonymous>:1545:18)\n' +
    '  at js_error (<anonymous>:1553:11)\n' +
    ...
SyntaxError: Unexpected token: punc ()).
Line 7 in dist/n/js/external_lib/highlight/highlight.min.js
```

Any ideas on how to fix it?

Thank you!

**Comment by joshgoebel** [comment]
Nope, sorry.  I would recommend using the file "as is" or building it via concatenation (no other changes).  Our existing minified file is not intended to be the target of additional transformations.  

Curious: Does using the un-minified file work?

**Comment by joshgoebel** [comment]
One note: Our final build asset does potentially include ES6 syntax... so if your parser is older and can't support that then that might be the issue you're running into.  In which case you could use a build tool that can understand ES6 or consider one of my other suggestions.

**Comment by kell18** [comment]
Thank you for your reply!
I minify it once more because of the build pipeline in the project which I don't own and just need to extend a bit. I tried to include the source using http link, but it fails due to violation of Content Security Policy.
Hm, I didn't find the un-minified version of the library anywhere... Could you link it?

**Comment by joshgoebel** [comment]
https://github.com/highlightjs/cdn-release/tree/master/build

Both the minified and un-minified are published to all our CDN sources as well. (the CDNs are sourced from the repo I just linked you to)

**Comment by joshgoebel** [comment]
> I tried to include the source using http link, but it fails due to violation of Content Security Policy.

You may need to serve the JS file from your own host then, rather than via CDN if you have a very tight CSP policy.

**Comment by joshgoebel** [comment]
>  because of the build pipeline in the project which I don't own

FYI most build pipelines have a `concat` option... and if not it's usually trivial to add... even after the build stop with just `cat`, etc...

**Comment by kell18** [comment]
Got it, thanks a lot @joshgoebel! I build one myself and it worked fine. I'll close the issue then.
