### ISSUE TITLE
I would like a custom language repository, please, to support Finite State Language

### ISSUE THREAD

**Issue by StoneCypher** [highlightjs/highlight.js#2971]
Hello.  I am the author of FSL ([Finite State Language](http://fsl.tools/)) and its main implementation JSSM ([Javascript State Machine](https://github.com/StoneCypher/jssm/)), and I've written a small highlighter for highlight.js.

I would like to contribute, please.  Thanks.

![image](https://user-images.githubusercontent.com/77482/105443591-ee339980-5c20-11eb-98eb-f4f7679d0896.png)

**Comment by joshgoebel** [comment]
https://github.com/highlightjs/highlightjs-fsl

Done.
