### ISSUE TITLE
Method invocation parser  (Java)

### ISSUE THREAD

**Issue by kratoon3** [highlightjs/highlight.js#2974]
Hi!

Is there any option to parse the method name that's being invoked?

e.g. parse `println` from `System.out.println('something')`

Thanks!

**Comment by joshgoebel** [comment]
Not sure what you are asking exactly. More context?

**Comment by kratoon3** [comment]
My mistake, sorry

**Comment by kratoon3** [comment]
Hi @joshgoebel 

I'm trying to write custom language (similar to java).

I have this sample code

```java
  public void moveTo(int x, int y, int z) {
    _ai = null;
    System.out.println("Something");
    log("Else");
    if (1 > 5) { // wtf!?
      return;
    }
  }
```
with desired output containing this:

```html
<span class="hljs-keyword">null</span>;
System.out.<span class="hljs-invocation">println</span>("Something");
<span class="hljs-invocation">log</span>("Else");
```

This is the closest I could come up with, but the non-capturing groups are not supported I guess. https://highlightjs.readthedocs.io/en/latest/language-guide.html#regular-expression-features
```js
{
    className: "invocation",
    begin: /(?:\.\s*?)([a-zA-Z][a-zA-Z0-9_]+)(?:\s*?\()/,
}
``` 

Sorry if this kind of questions is not supposed to be here.

Thanks

**Comment by joshgoebel** [comment]
Well you really need look-behind to do this right, but see our own `r.js` and the `beforeMatch` compiler extension (you could add it to your grammar also - though eventually it will find it's way into core most likely). Or can do the same thing with `starts` manually, that's the only way we currently have to do "one thing follows another" if you don't want both highlighted.

Oh there is also the begin/end trick where you:

- Use begin to match the WHOLE expression (with a look-ahead for the actual match)
- Use `excludeBegin: true` to skip the begin ( the `.` in this case)
- Use `end` to do your actual match (with a lookahead for the `(`)

For the `(` which you don't want highlighted just use a look-ahead. (to avoid it being part of the match).

**Comment by joshgoebel** [comment]
>  non-capturing groups are not supported 

Capturing or non-capturing there is no difference unless you're using callbacks, which will of course only have access to the captured groups.

**Comment by kratoon3** [comment]
Thanks a lot @joshgoebel 

Works great!
It's much simper than I thought :)

**Comment by joshgoebel** [comment]
Which way did you go?
