### ISSUE TITLE
[Request] Arduino Dark theme

### ISSUE THREAD

**Issue by BelKed** [highlightjs/highlight.js#2975]
**Is your request related to a specific problem you're having?**
I would like to highlight _Arduino_ source code with dark theme.
It's really nice theme for highlighting Arduino code.

**The solution you'd prefer / feature you'd like to see added...**
I would like to request to add _Arduino dark theme_ based on _One Dark Pro_ – https://github.com/konrad91/OneDarkArduino.

**Additional context...**
Here is sample image of code highlighted by that theme:
![Arduino Dark Theme](https://user-images.githubusercontent.com/66956532/105686996-36400e00-5ef8-11eb-81eb-e45796482ece.png)

This feature request is related to [that one](https://github.com/yusanshi/embed-like-gist/issues/11)...

**Comment by joshgoebel** [comment]
The core library team doesn't handle theme development.  Would you be willing to work on this theme yourself and make a PR?

**Comment by BelKed** [comment]
I don't know, which files I should change... So, please, could you write, which I should change? And also variables, which I should change...

**Comment by joshgoebel** [comment]
Take a look at `arduino-light.css` and perhaps https://highlightjs.readthedocs.io/en/latest/css-classes-reference.html.

You'll just be adding a `arduino-dark.css` and adding appropriate styles...

**Comment by BelKed** [comment]
I tried to add `arduino-dark.css` and it does look like I want (upper is by `highlightjs` and lower is html export from Arduino):
![Screen Shot 2021-01-27 at 10 26 40](https://user-images.githubusercontent.com/66956532/105971052-599ac280-608a-11eb-9659-442b73c4be4a.png)

**Comment by joshgoebel** [comment]
Please make a PR and I can review.

**Comment by BelKed** [comment]
There is an _Atom dark theme_, as @joshgoebel mentioned. I close this issue.
