### ISSUE TITLE
"hljs is not defined" with 10.5.0

### ISSUE THREAD

**Issue by RPJOF** [highlightjs/highlight.js#2980]
Hello, I have a problem when inserting highlight.js. When I want to make it work, here's what it shows me:
```
VM4799:5 ReferenceError: hljs is not defined
```
Here's my code: (insertion is done from a php `insert`)

load_art.php : 
```php
<link rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.5.0/styles/monokai-sublime.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.5.0/highlight.min.js"></script>
<script>
	hljs.initHighlightingOnLoad();
</script>
```
The page with the code : 
```php
<pre>
				<code class="html">
					&lt;!DOCTYPE html&gt;
	&lt;html&gt;
		&lt;head&gt;
			&lt;meta charset="utf-8"&gt;
			&lt;title&gt;Site de test !&lt;/title&gt;
		&lt;/head&gt;
		&lt;body&gt;
		&lt;h1&gt;Bienvenue&lt;/h1&gt;
		&lt;p&gt;Les codes de meteoff seront affichés comme sur cette exemple. Le language est écris sous le code.&lt;/p&gt;
		&lt;/body&gt;
	&lt;/html&gt;
				</code>
			</pre>
```

Thank you to the people who will help me! Have a nice day!

**Comment by joshgoebel** [comment]
I would guess you aren't truly loading the JS file (even if you think you are) - perhaps it's not loading, perhaps your aren't generating the HTML you think you are, etc.  This is the most basic usage of Highlight.js there is, so pretty sure the problem is with your page, not the library - since we've had almost 0 reported issues with 10.5. 

 I'd try to use the developer tools in your browser to find out what is happening.

**Comment by RPJOF** [comment]
Thank you very much for your response!
Still, I have the impression that the file loads well (HTTP 200): Thank you for your response!
![image](https://user-images.githubusercontent.com/60546959/106301367-eb0b5f80-6257-11eb-9d3b-58ec359659ea.png)

**Comment by joshgoebel** [comment]
No idea then... If you can make a reproducible case on a small webpage (with just Highlight.js and no other JavaScript) that seems to indicate it's our library then I could take a closer look. Otherwise I'm not sure what the problem could be.

**Comment by RPJOF** [comment]
Okay !
It works on an empty page! Thank you very much, I will try to find the problem! Have a good day and thank you for your ...
