### ISSUE TITLE
(powershell) Three official-approved VALID_VERBS not been highlighted

### ISSUE THREAD

**Issue by davidhcefx** [highlightjs/highlight.js#2981]
**Describe the issue**
In the list of the [official-approved verbs](https://docs.microsoft.com/en-us/powershell/scripting/developer/cmdlet/approved-verbs-for-windows-powershell-commands?view=powershell-7.1), there are three of them not included in the `VALID_VERBS`:

https://github.com/highlightjs/highlight.js/blob/1e0cc762076faf49de3fe8324345085d2581f0af/src/languages/powershell.js#L27-L39

Those are:
- `Mount`
- `Build`
- `Deploy`

By the way, the provided link doesn't work anymore. Please change to a workable link, for instance: https://docs.microsoft.com/en-us/powershell/scripting/developer/cmdlet/approved-verbs-for-windows-powershell-commands

**Which language seems to have the issue?**

`powershell`

**Are you using `highlight` or `highlightAuto`?**

**Sample Code to Reproduce**

```
Mount-DiskImage -ImagePath "E:\ISO-Files\My US Visit Fall 2010 Pictures.iso"
```

**Expected behavior**

- `Mount-DiskImage` being recognized as a whole `built-in`:
```powershell
Mount-DiskImage -ImagePath "E:\ISO-Files\My US Visit Fall 2010 Pictures.iso"
```

**Additional context**

**Comment by joshgoebel** [comment]
Thanks.  Looks like a good first issue.  Would you like to try making a PR?

**Comment by davidhcefx** [comment]
Done.
BTW, when building the code with docker, I found a typo in the [document](https://highlightjs.readthedocs.io/en/latest/building-testing.html#testing-markup):

> If your preference is for another port, you can do that too:
> `docker run -d --name highlight-js --rm -p 80:8080 highlight-js`

To my understanding, I think it should be `8080:80` instead? The first number is for the host, and I think most people would change that part to 8080.
