### ISSUE TITLE
May I have a custom language repository to support Riscript?

### ISSUE THREAD

**Issue by Real-John-Cheung** [highlightjs/highlight.js#2988]
Hello, I am a contributor of the [Rita](https://rednoise.org/rita/) project, which is a toolkit for computational literature. We have a simple scripting language called [RIscript](https://rednoise.org/rita/reference/riscript.html), and I am now writing a little highlighter for it.

If it is possible, I would like to have a repository to host it. Thanks!

**Comment by joshgoebel** [comment]
https://github.com/highlightjs/highlightjs-riscript

**Comment by Real-John-Cheung** [comment]
Thank you!
