### ISSUE TITLE
Question about CDN hosted CSS

### ISSUE THREAD

**Issue by Geobm** [highlightjs/highlight.js#2990]
Hi, first of all thank you for this great project.

**Is your request related to a specific problem you're having?**
Yes, since the project couldn't be built from source, I'm implementing prebuilt version of Highlight.js hosted by [CDN](https://github.com/highlightjs/highlight.js#cdn-hosted). More precisely `default.min.css`. The specific problem I'm facing is not a repo's code issue as such.
Moreover, I'm using `<pre>` tags to display code on a webapp I'm working on, but I have a css rule that the color of my `<pre>` tag insn't set to `#ffffff`, but kind of gray (`#f7f7f7`). 

When using `<code>` tag to detect the code, the background of the hosted `default.min.css` is set to with its own padding. Now here is where I have a problem. In this example I'm showing a curl command, but if the line is larger it does not cover all the `<pre>` tag.
![image](https://res.cloudinary.com/dxbnpu2rx/image/upload/v1612547710/code_wmzlid.png)

And here the normal view:
![image2](https://res.cloudinary.com/dxbnpu2rx/image/upload/v1612548041/code_jrvptj.png)

**The solution you'd prefer / feature you'd like to see added...**
Since it is not supposed to [work from source](https://github.com/highlightjs/highlight.js/issues/1156#issuecomment-212630768) (and certainly I don't know how hard can be to built it from source), is not possible to modify css rules. So I don't know if a feature could be added.

**Any alternative solutions you considered...**
My solution as far is to limit the length of the code, by this way it won't hover the tag.

**Additional context...**
Solution as far:
![image3](https://res.cloudinary.com/dxbnpu2rx/image/upload/v1612548871/code_ltirdr.png)

Any suggestion will be appreciated.

**Comment by joshgoebel** [comment]
For CSS/styling issues like you're talking about here (you need to look at all the CSS options for wrap, overflow, etc) you can either:

- Provide your own CSS file (just copy the default one and change it)
- Provide a second CSS file (or inline CSS) to override the styles in the CDN version
- Use `!important` if it's necessary.
