### ISSUE TITLE
(ecmascript) Missing BigInt type

### ISSUE THREAD

**Issue by Hirse** [highlightjs/highlight.js#2992]
**Describe the issue**
`BigInt` is not highlighted as type the same way `Number` is.
![Actual: BitInt not recognized](https://user-images.githubusercontent.com/2564094/107255765-81c0e480-69ed-11eb-9366-65953663ae66.png)

**Which language seems to have the issue?**
`ecmascript` and therefore also `javascript`

**Sample Code to Reproduce**
```js
let bi = BigInt('1');
```

**Expected behavior**
![Expected: BitInt recognized](https://user-images.githubusercontent.com/2564094/107255874-9ef5b300-69ed-11eb-9c2f-5bc43dfc0245.png)

**Additional context**
Also seems to be missing `BigInt64Array` and `BigUint64Array`.
See [List of built-ins](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects).

**Comment by joshgoebel** [comment]
We should added these missing types to `ecmascript#TYPES`.
