### ISSUE TITLE
(php) Anonymous functions without {} block not highlighted correctly

### ISSUE THREAD

**Issue by Hirse** [highlightjs/highlight.js#2995]
**Describe the issue**
Highlighter seems to expect a title in PHP arrow functions, even though they are intentionally anonymous.
![Actual: Incorrect title recognized](https://user-images.githubusercontent.com/2564094/107443068-f29af600-6aec-11eb-8b2a-b6f01744f300.png)

**Which language seems to have the issue?**
`php`

**Sample Code to Reproduce**
```php
<?php
$fn1 = fn($x) => $x + $y;
```

**Expected behavior**
![Expected: Variables](https://user-images.githubusercontent.com/2564094/107443233-4e657f00-6aed-11eb-8413-d5e4c970147c.png)

**Additional context**
Found in an [Code-Golf answer](https://codegolf.stackexchange.com/a/218815/25026), but also reproduces in the ungolfed version:
```php
fn( $s ) => 
    ( $l = strlen( $s ) ) > 1 ?             // is input longer than one char?
        max( count_chars( $s ) ) > 1 ?      // has more than 1 of any single char?
            'Bunny'                         // if so, contains dupes so... Bunny it is
        :                                   // else, no dupes
            [
                'T' => [ 'Ka',  'Hu'  ],    // two dimensional associative
                'C' => [ 'Rai', 'Do'  ],    //   array containing handsign 
                'J' => [ 'Hyo',  'Sui' ]    //   and length as indexes
            ]
            [ $s[-1] ]                      // access array by last letter and
            [ $l % 2 ]                      //   length mod 2 (2 == 0, 3 == 1)
            . 'ton'                         //   and append "ton"
    :                                       // finally...
    'Fuma Shuriken'                         // input length was only one char
```

![Context: Code Golf source](https://user-images.githubusercontent.com/2564094/107443454-b7e58d80-6aed-11eb-9c3a-6be57d434d20.png)
The comments are colored orange because they are considered `title`.

**Comment by joshgoebel** [comment]
> The comments are colored orange because they are considered title.

I wonder if this should not be dealt with as a separate fix (still part of this issue).  IE, fix comments THEN fix the function detection.

Confirm the overall issue.  PHP has no real awareness of anonymous functions. (though it may work if you use `{`, etc...  I wonder if we just shouldn't add `endsParent` to the `=>` rule?

**Comment by Hirse** [comment]
> >    The comments are colored orange because they are considered title.
> 
> I wonder if this should not be dealt with as a separate fix (still part of this issue). IE, fix comments THEN fix the function detection.

I meant to say that the comments don't get recognized correctly because of the arrow-function.
The comments look correct if I remove the first line of the example:

![Comments without arrow-function](https://user-images.githubusercontent.com/2564094/107474168-bab0a480-6b26-11eb-8090-cf1ae2bc02af.png)

**Comment by joshgoebel** [comment]
Yes, I understand, but line comments are technically possible anywhere, even in the middle of a function definition I would assume... just because the scope changes doesn't mean everything should be a title - comments should still be recognized as comments.  To me this is a separate bug/issue.

**Comment by il3ven** [comment]
```diff
{
  className: 'function',
  relevance: 0,
  beginKeywords: 'fn function', end: /[;{]/, excludeEnd: true,
  illegal: '[$%\\[]',
  contains: [
    hljs.UNDERSCORE_TITLE_MODE,
    {
      begin: '=>', // No markup, just a relevance booster
+    endsParent: true,
    },
    {
      className: 'params',
      begin: '\\(', end: '\\)',
      excludeBegin: true,
      excludeEnd: true,
      keywords: KEYWORDS,
      contains: [
        'self',
        VARIABLE,
        hljs.C_BLOCK_COMMENT_MODE,
        STRING,
        NUMBER
      ]
    }
  ]
}
```

The above code does solve the problem and all the existing test also pass. 
![image](https://user-images.githubusercontent.com/4337699/107857760-87d41c80-6e56-11eb-9830-7d437bb16d6d.png)

Shall I create a pull request?

**Comment by Hirse** [comment]
@il3ven Can you check if it also fixes this edge case:
```php
$fn2 = function ($x) use ($y) {
    return $x + $y;
};
```
`use` is supposed to be a keyword here.
See https://www.php.net/manual/en/functions.arrow.php

**Comment by joshgoebel** [comment]
@Hirse If not I think only this would need to be added, no?  To add the `use` keyword in the function scope.

```js
keywords: 'fn function use'
```

**Comment by il3ven** [comment]
![image](https://user-images.githubusercontent.com/4337699/107859629-ac34f680-6e60-11eb-8d8c-57c57ddb2907.png)

It is correct. Right?

**Comment by joshgoebel** [comment]
Oh, title will match it... so you'd just need a special case rule inside `contains` to explicitly handle `use` and mark it as a keyword... I'm assuming use is not a valid function name.

**Comment by il3ven** [comment]
> Oh, title will match it... so you'd just need a special case rule inside contains to explicitly handle use and mark it as a keyword... I'm assuming use is not a valid function name.

This does it.

![image](https://user-images.githubusercontent.com/4337699/107859758-a55ab380-6e61-11eb-8601-84c5071eaabf.png)
