### ISSUE TITLE
Add 'plain-text' or 'text' language option.

### ISSUE THREAD

**Issue by DanielGibbsNZ** [highlightjs/highlight.js#301]
As many tools use highlight.js for highlighting code blocks in Markdown documents, it would be nice to be able to specify the language as plain text to get the code block style but without any highlighting.

**Comment by iurisman** [comment]
@DanielGibbsNZ no-highlight also disables the horizontal scroll bar. At least not for me. Would be cool to have that preserved, with no highlighting.  I am going to stop short of reopening this though.

**Comment by yyyc514** [comment]
I don't see how... no-highlight essentially does NOTHING at all.

```
  function highlightBlock(block) {
    var node, originalStream, result, resultNode, text;
    var language = blockLanguage(block);

    if (isNotHighlighted(language))
        return;
```

**Comment by yyyc514** [comment]
- "nohighlight" means leave this block alone completely
- "plaintext" means style it according to theme colors (background, foreground, etc), but otherwise no highlighting of any specific items/keywords, etc.

**Comment by isagalaev** [comment]
> It's probably your own CSS disabling it.

Not exactly disabling but not applying, because all highlight.js styles are meant to apply to something with the class "hljs" on it, and "no-highlight" prevents it from appearing.

My recommendation would be either to copy the contents of the `.hljs` rule from the highlight.js style file to plain `pre code` in the user styles, or manually add `hljs` to the elements that you want to look like code blocks.

**Comment by yyyc514** [comment]
> My recommendation would be either to copy the contents of the .hljs rule from the highlight.js style file to plain pre code in the user styles, or manually add hljs to the elements that you want to look like code blocks.

If that was the desired behavior they should just use the new plaintext grammar. That’s why we added it. 

I think they think HLJS is mucking with their styles when it Most likely is not.

**Comment by marcospgp** [comment]
Is there any chance `language-text` can be added as an alias for `language-plaintext`? I have used the former for code blocks in my site, which I think is generally the more accepted variant (see https://github.com/jincheng9/markdown_supported_languages for example)

**Comment by joshgoebel** [comment]
There is already a `text` alias.

**Comment by marcospgp** [comment]
My issue seems related to how Jekyll/Rouge will add the `language-<language>` class to a parent div of the `<pre>` and `<code>` elements, which causes highlight.js to auto detect the language and add its own `language-<language>` class to the `<code>` element (as it doesn't see the class added by Jekyll/Rouge.

Is there a fix for this or some misconfiguration that I'm not seeing?

For the time being, I asked ChatGPT to write this plugin that copies `language-<language>` classes to child elements:

```ruby
# Written by ChatGPT.
#
# Adds the "language-<language>" class from "<pre>" elements to any child
# "<code>" elements.
# This is needed because Jekyll/Kramdown/Rouge add the class to "<pre>" elements
# when generating code blocks, but highlight.js looks for the class in the
# "<code>" element - and if it's not there, auto detects the language.

module Jekyll
  module TransferLanguageClass
    Jekyll::Hooks.register [:pages, :documents], :post_render do |doc|
      # We'll add a temporary marker to each div with a language class to help identify the current language context.
      nested_language = nil
      doc.output = doc.output.gsub(/<div[^>]*class="([^"]*)"/) do |div_tag|
        # Check if the div has a language class and capture it
        match = div_tag.match(/language-[\w-]+/)
        nested_language = match ? match[0] : nested_language

        # Include the language as a data attribute if found
        if nested_language
          "#{div_tag} data-language=\"#{nested_language}\""
        else
          div_tag
        end
      end

      # Now, adjust the <code> tags within these divs
      doc.output.gsub!(/<code( class="([^"]*)")?/) do |code_tag|
        existing_classes = $2
        if nested_language
          existing_classes = existing_classes ? "#{existing_classes} #{nested_language}" : nested_language
          "<code class=\"#{existing_classes}\""
        else
          code_tag
        end
      end

      # Remove the temporary data attributes to clean up
      doc.output.gsub!(/ data-language="[^"]*"/, '')
    end
  end
end
```

**Comment by joshgoebel** [comment]
> but highlight.js looks for the class in the "<code>" element

Yes, so you can either put it there at build time (as your plugin is doing) or do the same thing by writing a custom version of `highlightAll()` that loops over the higher level div elements, then finds the inside `<code>` tag, etc... all using the DOM.
