### ISSUE TITLE
enh(c) Update keyword list for C11/C18

### ISSUE THREAD

**Issue by joshgoebel** [highlightjs/highlight.js#3010]
Pulling this out because we should eventually apply this to our `C` grammar (removing the C++ keywords and types, etc).

---

The full list of *keywords* for C11/C18 is

```
                auto                          if                             unsigned
                break                         inline                         void
                case                          int                            volatile
                char                          long                           while
                const                         register                       _Alignas
                continue                      restrict                       _Alignof
                default                       return                         _Atomic
                do                            short                          _Bool
                double                        signed                         _Complex
                else                          sizeof                         _Generic
                enum                          static                         _Imaginary
                extern                        struct                         _Noreturn
                float                         switch                         _Static_assert
                for                           typedef                        _Thread_local
                goto                          union
```

_Originally posted by @ztane in https://github.com/highlightjs/highlight.js/issues/2973#issuecomment-779284055_

**Comment by il3ven** [comment]
These keyword just need to be added in `c.js`? I was confirming before opening a PR.

**Comment by joshgoebel** [comment]
Well really someone with a larger knowledge of C could really help here.  Hopefully a PR here will do more than just replace `KEYWORDS#keyword`.  There are related connections also to:

- https://github.com/highlightjs/highlight.js/pull/3005 (though eventually I'll get to this).  
  - More important that we just get a correct list of `built_in` (ie, removing any `cpp` ones) for starters... 
- Even the above keywords need to be split between `keyword` and `type`
- Review the rest of the syntax (for wrong modes like `class` and `decltype`, etc)

So that would be my hope here.

**Comment by joshgoebel** [comment]
@klmr Does modern C have namespaces?

**Comment by joshgoebel** [comment]
There is also `begin: '\\b(deque|list|queue|priority_queue|pair|stack|vector|map|set|bitset|multiset|multimap|unordered_map|unordered_set|unordered_multiset|unordered_multimap|array)\\s*<',` which I dunno if it applies to C as well as C++ or not.

**Comment by klmr** [comment]
No namespaces, no.

And that `begin` rule is pure C++, not C.

**Comment by joshgoebel** [comment]
What are  _Bool and _Imaginary?  Should we flag them as types?

**Comment by klmr** [comment]
They’re types, yes, but they’re also keywords (unlike e.g. `bool`, which in C is an alias for `_Bool`, but only if the `stdbool.h` header is included — otherwise it’s just any old identifier). https://en.cppreference.com/w/c/keyword is a good reference.

(Apologies for the radio silence, I’m still snowed under with two other projects that unfortunately take priority and take up all my nominal “free time”.)
