### ISSUE TITLE
Consider a Cobalt theme

### ISSUE THREAD

**Issue by alvarotrigo** [highlightjs/highlight.js#3016]
Cobalt looks quite good and I would love to see it added on the list of available themes:
![image](https://user-images.githubusercontent.com/1706326/108513750-4c58a880-72c3-11eb-9810-47851c6500ea.png)

![image](https://user-images.githubusercontent.com/1706326/108513797-5a0e2e00-72c3-11eb-8f91-1b0b36776f92.png)

Refences:
- https://github.com/wesbos/cobalt2
- https://marketplace.visualstudio.com/items?itemName=wesbos.theme-cobalt2

**Comment by joshgoebel** [comment]
_Looks pretty._

See language requests: https://github.com/highlightjs/highlight.js/blob/master/docs/language-requests.rst

Same policy applies to theme requests. The core team doesn't add themes and we don't leave themes requests open as issues (typically people don't just come along and implement them).  If you'd like to implement the theme yourself though we'd be happy to have a PR!

**Comment by alvarotrigo** [comment]
Cobalt is not a language but a theme instead? :)

**Comment by alvarotrigo** [comment]
> If you'd like to implement the theme yourself though we'd be happy to have a PR!

Got it! Thanks!
