### ISSUE TITLE
(md/html/etc) Parsing of spacing characters

### ISSUE THREAD

**Issue by Gedili** [highlightjs/highlight.js#3017]
**Describe the issue**

**Which language seems to have the issue?**
Apparently most, only tried with md and html

**Are you using `highlight` or `highlightAuto`?**
I don't directly use the library myself. That problem occurs on discord when using blocks of code. It used to work fine until about a week ago, but not anymore, so I figure they must have updated to this new hihlight.js v10 version, which caused this change of behavior.
...

**Sample Code to Reproduce**

```md
test <test>
test <test test>
test <test test test>
12. test <test test test>

1. Ship Name <FleetName - 5685 trophies>
2. Ship Name <Fleet Name - 5685 trophies>
3. Ship Name <Fleet⠀Name - 5685 trophies>
4. Ship Name <Fleet Name>
5. Ship Name < Fleet Name >
```

**Expected behavior**

In example 3, the regular space character between "Fleet" and "Name" (as in example 2) was replaced by a special unicode spacing character ([U+2800 - Braille Pattern Blank](https://www.compart.com/fr/unicode/U+2800)). This trick, with the previous version of highligh.js, used to interpret "Fleet⠀Name" as a unique continuous string, therefore displaying in in blue, and then what followed (" - 5685 trophies") in yellow. Not anymore.

In example 5, using a standard space character after the opening "<" used to put all the text following in yellow, but now it's not highlighted anymore.

Would it be possible to restore those previous behaviors?

![image](https://user-images.githubusercontent.com/45516124/108600694-5c31c480-7377-11eb-88b3-3e3893350884.png)

**Comment by joshgoebel** [comment]
Recently the XML grammar was improved to prevent false positives and now it actually attempts to match tag names with regex, where-as it never did before.  This change has caused the change in behavior you are seeing.  Like many other grammars (see #2756) we're using a simplified matcher (A-Z, etc) when it seems the actual spec is MUCH, much broader:

```
'<' Name (S Attribute)* S? '>' A Name consists of:

NameStartChar (NameChar)* A NameStartChar consists of:

":" | [A-Z] | "_" | [a-z] | [#xC0-#xD6] | [#xD8-#xF6] | [#xF8-#x2FF] | [#x370-#x37D] | [#x37F-#x1FFF] | [#x200C-#x200D] | [#x2070-#x218F] | [#x2C00-#x2FEF] | [#x3001-#xD7FF] | [#xF900-#xFDCF] | [#xFDF0-#xFFFD] | [#x10000-#xEFFFF] A NameChar consists of:

NameStartChar | "-" | "." | [0-9] | #xB7 | [#x0300-#x036F] | [#x203F-#x2040]
```

That is it's own problem, but *I'm not seeing where #2800 is a valid character for an XML tag name at all.* (nor does it really make sense as that would be very hard to read).

**That would mean the prior behavior was broken and the new behavior is correct.** 

Interpreted as HTML, `Fleet` is tag name, and `Name` is an attribute. Spaces are not allowed.
