### ISSUE TITLE
(Kotlin) kts is not recognized

### ISSUE THREAD

**Issue by AlexCzar** [highlightjs/highlight.js#3021]
**Describe the issue**
`hljs.getLanguage("kts")` cannot find Kotlin language.

**Which language seems to have the issue?**
`Kotlin`

**Are you using `highlight` or `highlightAuto`?**

`highlight`

**Sample Code to Reproduce**
```js
hljs.getLanguage("kt"); // works
hljs.getLanguage("kotlin"); // works
hljs.getLanguage("kts"); // doesn't work
```
example:
https://jsfiddle.net/tao605qL/55/

**Expected behavior**
`hljs.getLanguage("kts");` should return "Kotlin" language.

**Comment by joshgoebel** [comment]
PR welcome.

**Comment by AlexCzar** [comment]
Thanks. If I knew tests were not required, I would've submitted the PR myself :D

**Comment by joshgoebel** [comment]
We don't require tests for adding a single new alias.
