### ISSUE TITLE
(css) -webkit-font-smoothing: antialiased; are not highlight correctly

### ISSUE THREAD

**Issue by AndyKIron** [highlightjs/highlight.js#3027]
Trying to highlighting syntax for css line -webkit-font-smoothing: antialiased;
![image](https://user-images.githubusercontent.com/18393324/109486226-3f8a4080-7a8b-11eb-9576-20469ec99902.png)

![image](https://user-images.githubusercontent.com/18393324/109486395-7ceece00-7a8b-11eb-83d3-79f440eb1bae.png)

To reproduce:
https://codesandbox.io/s/wonderful-meninsky-vsj7y?file=/index.html:632-668

**Comment by joshgoebel** [comment]
Pretty sure this attribute needed to be added (in alpha order) in `css-shared.js`. (without the prefix)
