### ISSUE TITLE
Grammar module naming convention

### ISSUE THREAD

**Issue by jf990** [highlightjs/highlight.js#3032]
Regarding https://github.com/highlightjs/highlight.js/blob/master/extra/3RD_PARTY_QUICK_START.md

The two examples,

```html
<script type="text/javascript" src="/path/to/highlight.min.js"></script>
<script type="text/javascript" src="/path/to/highlightjs-robots-txt/dist/robots-txt.min.js"></script>
<script type="text/javascript" src="/path/to/highlightjs-cypher/dist/cypher.min.js"></script>
```

however on https://github.com/highlightjs/highlight.js/blob/master/SUPPORTED_LANGUAGES.md package names (3rd column) use the `highlightjs-grammar` convention.

Should we require the grammars modules use a standard naming convention with `highlightjs-` prefix?

```html
<script type="text/javascript" src="/path/to/highlight.min.js"></script>
<script type="text/javascript" src="/path/to/highlightjs-robots-txt/dist/highlightjs-robots-txt.min.js"></script>
<script type="text/javascript" src="/path/to/highlightjs-cypher/dist/highlightjs-cypher.min.js"></script>
```

@joshgoebel

**Comment by joshgoebel** [comment]
> Should we require the grammars modules use a standard naming convention with highlightjs- prefix?

The naming convention is that the package name should should be `highlightjs-[grammar]`, not the distributable (or npm library filename) - which is expected to be simply `[grammar]`.  This is as intended.  If someone is copying this file into their own larger project I'd likely recommend it be placed in a  `grammars` or `hljs` folder for some context.

I do sort of see your point if the file is just thrown in an empty folder with no context... (ie, the file itself is treated as the entire "distribution")... but I'm not sure this is worth forcing everyone to change conventions midstream.

@highlightjs/core Further thoughts on this?

**Comment by joshgoebel** [comment]
It's worth remembering a larger project might easily have multiple grammars... so repeating the name over and over vs just putting them in a folder for easy grouping seems a bit redundant and annoying to me.

**Comment by jf990** [comment]
> The naming convention is that the package name should should be highlightjs-[grammar], not the distributable (or npm library filename) - which is expected to be simply [grammar]. This is as intended.

I'm ok with that, just wanted it to be officially stated as I want to make sure my 3rd party contributions are hitting the right conventions.

**Comment by jf990** [comment]
The question is answered.

* .js file name matches language name.
* packagename is `highlightjs-` + language-name
