### ISSUE TITLE
<pre> CSS overflow-x behavior on iPad

### ISSUE THREAD

**Issue by walterandreas** [highlightjs/highlight.js#3037]
Hi!
Unfortunately I had to find out that the line breaks on Apple's PadOS (version 14.4 for me) don't work. Everything looks fine on a Windows PC with Google Chrome, but in Safari on the iPad the marked line is not appended to the end and a vertical scroll bar is not displayed, instead it breaks into the next line. For comparison, I have put the code below in a normal \<pre\> tag.
Am I using something wrong?
![IMG_6797](https://user-images.githubusercontent.com/30598361/109771446-1984ad80-7bfd-11eb-9d20-42fd75420f60.jpeg)

I'm using Javascript and the call `hljs.initHighlighting();` after the site has loaded.

Here my code:
```
<pre><code class="hljs language-javascript">var brd = JXG.JSXGraph.initBoard(BOARDID, {boundingbox:[-2,2,2,-2]});
var A = brd.create('point', [-1,-1]),
    B = brd.create('point', [1,-1]),
    C = brd.create('point', [0,1]),
    alpha = brd.create('angle', [B,A,C], {type:'sector', orthoType:'square', orthoSensitivity:2, radius:0.5}),
    beta = brd.create('angle', [C,B,A], {type:'sector', orthoType:'sectordot', orthoSensitivity:2, radius:0.2});</code></pre>
```

**Comment by joshgoebel** [comment]
You may want to play around with your CSS.  All our theme stylesheet's will set `overflow-x: auto;` on the `.hljs` element... it may be you want a different setting or a media query that only changes that properly for the iPad.  Sounds like perhaps a quirk in the iPad's rendering behavior for pre and overflow-x?

**Comment by walterandreas** [comment]
I am of the opinion that the desired behavior is not showed. In the standard configuration, it is added `overflow-x: auto` to `.hljs` in my example. However, this has no effect on the iPad. Actually, that is my problem. Even if I change `owerflow-x` to `scroll` for `.hljs` by hand, long lines are not scrolled, but continued in the next line ...

**Comment by walterandreas** [comment]
Hurray, I've found the neuralgic point: it's bootstrap. I reproduced the problem in the following jsFiddle:
Here with Bootstrap: https://jsfiddle.net/andreas_walter/9aw5s0qz/20/
Here without: https://jsfiddle.net/andreas_walter/eh4Laun6/1/
The error occurs on iOS devices.

**Comment by walterandreas** [comment]
Hooray, I've found the neuralgic point: it's Bootstrap. Bootstrap defines a css attribute `word-wrap` for the object `code`. This only seems to be interpreted by the iPad because none of my browsers could reproduce the error.
Adding
```
code.hljs {
  word-wrap: normal;
}
```
 solves the problem. Maybe you can add this to your css files.

**Comment by joshgoebel** [comment]
**Awesome, glad you fixed it!**

I don't feel the current behavior is necessarily broken.  I think the wrapping might be a better choice.  This would also be a breaking change - breaking any websites relying on the existing behavior.  So I think we will leave the existing behavior in place and anyone who needs to change it can easily do so via CSS.
