### ISSUE TITLE
C comments different colors depending on where they are placed on StackOverflow

### ISSUE THREAD

**Issue by drankinatty** [highlightjs/highlight.js#3040]
The implementation of highlightjs on StackOverflow is rendering C comments in two different colors depending on what the comment follows. This should not happen. C comments should be rendered in a single color regardless what they follow. 

Specifically, when the comment follows a header include, it is rendered in the header color while comments in the body are rendered in normal comment color. I have opened a bug on MetaStackOverflow as [Highlightjs C comments rendered in different colors after header](https://meta.stackoverflow.com/questions/405746/highlightjs-c-comments-rendered-in-different-colors-after-header) which includes a screenshot of the problem.

**Comment by joshgoebel** [comment]
I think this resolves.

**Comment by joshgoebel** [comment]
Please do use our regular bug report templates next time for reporting grammar highlighting issues.
