### ISSUE TITLE
Blank line in start

### ISSUE THREAD

**Issue by stargazer36** [highlightjs/highlight.js#3054]
![blank_highlight](https://user-images.githubusercontent.com/30208266/111591248-36200880-87ed-11eb-8f51-6247a94625c1.png)

blank line - above the code snippet
. . My sample code
```
<pre><code class="language-css">
	.class{
	font-size: 0.85rem;
	font-weight: 600;
	font-family: monospace;
	}
	h1 .header{
	font-size: 1.5rem;;
	font-family: Arial;
	}
	</code></pre>
```

**Comment by joshgoebel** [comment]
```
<pre><code class="language-css">
	.class{
```

You added the new line right there.  If you don't want a newline then `.class` needs to *immediately* follow the `<code>` tag.

**Comment by stargazer36** [comment]
The code will be added by Gutenberg block, so there have to be added additional settings, maybe changing React, Gutenberg plugins. 
 - is there any highlight-js settings, which can resolve this.

**Comment by joshgoebel** [comment]
No.  _We purposely do not modify the content._  If someone wants space at the beginning, they can have it.  

You could write a tiny plugin:

https://highlightjs.readthedocs.io/en/latest/plugin-api.html#before-highlightelement-el-language

Just before the highlighting trim the whitespace yourself by modifying the DOM...

**Comment by stargazer36** [comment]
![spacing_line-number](https://user-images.githubusercontent.com/30208266/111634681-bf026880-881c-11eb-8e3d-2a026d4ee50d.png)

**How to have spacing** between line numbers and the code

**Comment by joshgoebel** [comment]
I'd say that's just a CSS question... hot a Highlight.js question.  Do purposely don't support line numbers out of the box...

**Comment by stargazer36** [comment]
figured out ```
td.hljs-ln-line.hljs-ln-code{
.padding-left: 0.75rem;
}
```
But - spacing issue will just add more troubles for me, more stackoverflow - **Downvotes**

**Comment by joshgoebel** [comment]
> trimming first line will just add more troubles for me, more stackoverflow - Downvotes

There is a reason we don't trim. :) We trust users to put line breaks if they want them, and to not if they don't.  That makes it very clear whose fault it is. :-)  And the behavior is always 100% clear.  As said it's easy to add this functionality, but it's not always clear that isn't desirable. :)

**Comment by joshgoebel** [comment]
Closing this as asked and answered since the original request has been resolved.

**Comment by stargazer36** [comment]
Hey is there any previous solution for this  - there would be others faced this?

**Comment by joshgoebel** [comment]
I already offered the solution: https://github.com/highlightjs/highlight.js/issues/3054#issuecomment-801916563

IF you want to strip the space then either use a plugin (see documentation) OR simply loop over the DOM yourself and strip the space from every code block before you even ask us to highlight them.
