### ISSUE TITLE
An internal server error occurred while downloading the custom bundle

### ISSUE THREAD

**Issue by w0r1dhe110** [highlightjs/highlight.js#3061]
An internal server error occurred while downloading the custom bundle
![ffff](https://user-images.githubusercontent.com/35865922/111903125-a04ddd00-8a7b-11eb-8c70-0518a70cba4f.png)

**Comment by joshgoebel** [comment]
Confirm and assigning for resolution.

**Comment by isagalaev** [comment]
Fixed via https://github.com/highlightjs/hljs_org/commit/3653e72ceb44a40107e5b7ecc9ac1e6c76825037

**Comment by joshgoebel** [comment]
@w0r1dhe110 Thanks for letting us know!  Should be all good now.
