### ISSUE TITLE
Invalid rendering in Java after .class element in function arguments

### ISSUE THREAD

**Issue by gquintana** [highlightjs/highlight.js#3063]
**Describe the issue**

The var args attributes of Map.of(...) function containing a ` .class`  are not properly rendered.

**Which language seems to have the issue?**
Java language

**Are you using `highlight` or `highlightAuto`?**

I don't know, I am using highlight.js with @asciidoc/reveal.js module

**Sample Code to Reproduce**

```java
    Map<String, Object> producerConfig = Map.of(
      BOOTSTRAP_SERVERS_CONFIG, "localhost:9092",
      ACKS_CONFIG, "1",
      KEY_SERIALIZER_CLASS_CONFIG, IntegerSerializer.class,
      VALUE_SERIALIZER_CLASS_CONFIG, StringSerializer.class
    );
```
Renders as
![Firefox_Screenshot_2021-03-21T14-19-39 454Z](https://user-images.githubusercontent.com/755587/111908521-e3975400-8a59-11eb-9195-db8103a38aa8.png)

The problem seems to be related to the ` .class` element, replacing `IntegerSerializer.class` by a String fixes the problem.

**Expected behavior**
The last Map element should be rendered as the previous one.

**Additional context**

Highlight.js 10.7.1 in Chrome with Github Theme

**Comment by joshgoebel** [comment]
<img width="537" alt="Screen Shot 2021-03-21 at 11 56 32 AM" src="https://user-images.githubusercontent.com/6473/111911558-80e38f80-8a3c-11eb-88aa-3468c639b230.png">

Please reproduce in isolation.  Here is Java, it shows none of the issues you are seeing in your setup.

https://jsfiddle.net/ajoshguy/cjhvre2k/2/

**Comment by gquintana** [comment]
On the pointed fiddle the `Map<String,Object>` is rendered as `Map` (generics are removed), so it's even worse.

Is it possible to check at runtime which Highlight JS release is used?

**Comment by joshgoebel** [comment]
Oh that's just because I didn't properly escape the HTML.

> Is it possible to check at runtime which Highlight JS release is used?

`hljs.versionString`

**Comment by joshgoebel** [comment]
It really looks like you're using some OTHER language than Java, whether you think you are or not - in which case you're quite likely to get poor results - like what is shown in your snap.

**Comment by gquintana** [comment]
The Highlight JS version used is not the one I thought. My bad, it is 9.18.1.
https://jsfiddle.net/83dzw1ux/1/

This issue seems to be fixed in recent releases.

**Comment by joshgoebel** [comment]
I would recommend upgrading, lots of potential security issues in those old versions.

**Comment by gquintana** [comment]
Thank you very much for your help and your quick answers.

I manage to  upgrade for real ;-)
