### ISSUE TITLE
(properties) Keys with `.` in them are highlighted differently

### ISSUE THREAD

**Issue by gquintana** [highlightjs/highlight.js#3064]
**Describe the issue**

When the key part doesn't contain a dot it's rendered as other properties

**Which language seems to have the issue?**

Properties

**Are you using `highlight` or `highlightAuto`?**

I don't know, I am using @asciidoc/reveal

**Sample Code to Reproduce**

```properties
listeners=CLIENT://192.168.0.1:9092,CLUSTER://192.168.3.1:9093
advertised.listeners=CLIENT://public:9092,CLUSTER://private:9093
listener.security.protocol.map=CLIENT:PLAINTEXT,CLUSTER:PLAINTEXT
inter.broker.listener.name=CLUSTER
```

is rendered as 
![Firefox_Screenshot_2021-03-21T15-03-52 516Z](https://user-images.githubusercontent.com/755587/111909820-0d06ae80-8a5f-11eb-836f-ed12b29d8cc6.png)

**Expected behavior**

`listeners=` should be rendered as `advertised.listeners=`

**Additional context**

Highlight.js 10.7.1 in Chrome with Github theme

**Comment by joshgoebel** [comment]
@egor-rogov This one is for you... you committed our Properties support. You seem to make a very purposeful distinction between alphanumeric keys and "other" keys yet none of our tests or sample data have anything other than alphanumeric keys... what were you going for with "other" keys, and is this behavior what you intended?

**Comment by joshgoebel** [comment]
@egor-rogov Ping. Any thoughts?

**Comment by egor-rogov** [comment]
Hmm... Returning back to this, I couldn't find any solid reason for separating non-alphanumeric keys, other then relevance balancing game. Anyway using `meta` class looks plain wrong.
I'm going to try to get rid of non-alphanumeric case and see if it's okay from autodetection point of view. If not, I'll leave it be and will just replace className.

**Comment by joshgoebel** [comment]
And is `.` supposed to be treated differently for some reason or should that be included in alphanumeric keys?  What other keys are there?  Could we get some examples in the tests?  Right now I have no idea what an example of a non-alphanumeric key even is or what's allowed.

**Comment by egor-rogov** [comment]
Looks like there are no any restrictions, you can use whatever characters you like for keys. No special cases, dot is just like any other character.
I think my thoughts were like this: "in all examples of .properties files I've ever seen the keys were alphanumeric; so if we encounter something strange (@#$ = foo) we'd better use zero relevance". And then I made this special case and somehow managed to use different class name for it. It's a 100% bug.
I've just checked: it's OK to flatten he grammar to just keys (making no distinction for character classes).

**Comment by joshgoebel** [comment]
> so if we encounter something strange (@#$ = foo) we'd better use zero relevance"

Ah, that's worth some thought.  The wider the rule gets the more careful we need to be with relevance.  Thanks for the fix though.  I'll review it later and see if I think we need any relevance tweaks.  If we do I think we can do it a simpler way than having two entirely different modes like that.

**Comment by joshgoebel** [comment]
@gquintana Thanks!  In version 11 these keys should render exactly the same as the first.

**Comment by gquintana** [comment]
Thank you @joshgoebel  and @egor-rogov
