### ISSUE TITLE
(chore) Throttle logging of deprecation messages

### ISSUE THREAD

**Issue by joshgoebel** [highlightjs/highlight.js#3069]
Would it maybe make sense to throttle logging the same deprecation messages? We're using highlight.js as a dependency of another dependency so can't directly update the deprecated code. The console is simply drowned in the exactly same deprecation message. Once would suffice, IMO, so we could alert the dependency to change it.

_Originally posted by @mihkeleidast in https://github.com/highlightjs/highlight.js/issues/2277#issuecomment-805046833_

**Comment by allejo** [comment]
👍 for throttling deprecation messages. I would imagine it'd cause havoc on the hljs website if it weren't using `highlightAll()` for example (probably logging a deprecation message ~190 times).

**Comment by joshgoebel** [comment]
@mihkeleidast Would you want to contribute a small PR against our `logger` code to this effect?

**Comment by mihkeleidast** [comment]
I'll try to come up with something :)

**Comment by joshgoebel** [comment]
I'd just use a simple object literal keyed on the message and and version.

```
seenDeprecations[`${version}-${msg}`] = true
```
