### ISSUE TITLE
New language request: GraphQL

### ISSUE THREAD

**Issue by jf990** [highlightjs/highlight.js#3076]
Proposal to add GraphQL grammar

https://github.com/jf990/highlightjs-graphql

this isn't perfect but it seems to be a small improvement over some of the suggested implementations. My team needs needs this so we would like to get it included in the CDN distribution.

**Comment by joshgoebel** [comment]
README looks awesome.  We def need to add this to SUPPORTED_LANGUAGES.  

>  My team needs needs this

What is stopping you from using it now?

**Comment by jf990** [comment]
@joshgoebel really nothing, but from a production process having the location of the distributable in the right location means we don't have to revisit it again. I can leave it in my jf990 or we can move it to highlightjs - that's the decision that needs to be made.

**Comment by jf990** [comment]
@joshgoebel for example, this line: https://github.com/jf990/highlightjs-graphql#using-directly-from-the-unpkg-cdn

**Comment by joshgoebel** [comment]
Are you asking about the repository location (jf990 vs highlightjs org) or asking that GraphQL be added to the core distribution?

**Comment by joshgoebel** [comment]
?

**Comment by joshgoebel** [comment]
Closing inactivity.

**Comment by kdawgwilk** [comment]
I am using https://deckset.com which uses this library and unfortunately does support GraphQL because this library does not support it.  I still think this is a valuable issue and would for it to be reopened

**Comment by jf990** [comment]
@kdawgwilk I had started a GraphQL highlighter and we are using it for our documentation, it works OK. I can work with @joshgoebel to see if we can move it to the highlight-js organization.
