### ISSUE TITLE
highlightAuto() detecting wrong language (JavaScript as SQL)

### ISSUE THREAD

**Issue by dexterthemsb** [highlightjs/highlight.js#3091]
I'm trying to get the auto detected language for a code snippet (could be anything).

When I'm trying to enter console.log("Hello"); as code snippet it's detecting it as SQL.

```
const a = hljs.highlightAuto(code); // code = 'console.log("Hello");'
console.log(a.language); // sql
```

Is there any way I can solve this problem?

**Comment by joshgoebel** [comment]
See 03a9232c. (which shifts the favor back to JS, but only by luck)

But truly auto-detect is not reliable with such small snippets and you should manually specify the language.
