### ISSUE TITLE
Discuss: Should 3rd party language grammars be version tagged?

### ISSUE THREAD

**Issue by joshgoebel** [highlightjs/highlight.js#3096]
We're just about to introduce some nice new features in version 11 (such as [multi-class modes](https://github.com/highlightjs/highlight.js/issues/2838), `beforeMatch`, etc).  These improvements should make doing some complex things much simpler than it was previously - including some things that were perhaps impossible before.  Grammars using these (or other future) new features would then no longer be backwards compatible with version 10.  

If so, should this just break silently or with a strange JS error (whatever it might be)?  Or should we add some sort of version info to the language definitions:

```
{
name: "SmartSQL",
requiresVersion: "11.0.0",
}
```

If we did this, what would the expected behavior be?  Would older grammars result just result is us `console.error` logging that the grammar was incompatible with the current version?

---

Also, our build system makes no accounting for different distributable assets, but I imagine someone wanting to live in the new world could just rename `smart_sql.min.js` to `smart_sql_v10.min.js` and update the README accordingly.

I guess mostly I'm talking about the "simple" CDNs + static distributable use cases... On the NPM side this could all be dealt with by correct version pinning and that's indeed what should happen for NPM packaging I think.  If you make a change to your library that requires version 11, then you should indicate that in your `package.json`.  I'm not sure we've encouraged grammars to have us as an official dependency in the past (since technically we aren't), but this may be something we need to change.  Although perhaps we should be using `peerDependencies`?  I'm not 100% sure.

_This same issue would also apply to plugins as well._

Open to thoughts and feedback here.

@highlightjs/core @highlightjs/grammar-maintainers

**Comment by StoneCypher** [comment]
This is a welcome addition in every place I've ever seen it.  Strongly supported.

**Comment by joshgoebel** [comment]
Although I was just thinking `hljs` is exposed to languages - and that includes the version info... so they could also perhaps do a check themselves against `versionString` (though perhaps we'd expose a nicer API).  A grammar (since it's run-time code)  could even detect if it was running on v10 or v11 and then adjust itself to provide the best results for either... so I think that actually might complicate the matter just a bit more.

Although I suppose we could have it both ways... a grammar could say `requiredVersion: "*"` or some such if it wanted to try to handle the versioning info itself.

**Comment by Serhioromano** [comment]
Version tagging sounds nice. Lets say the major version should always conform the major version of hljs. For instance my version would be 10.0.1 now. And when I make something that require 11 at least then 11.0.0 and so on...

**Comment by joshgoebel** [comment]
Yeah I would probably support/require all 3 digits and then you could say "I support >10.2.0" or I support ">11.1"... that doesn't cover us removing features in a major version, but I'm not sure it's within scope to cover all possibilities.  At this point I'm more worried about grammars using new feature on old engines.  I'm also fine with this remaining a discussion for a while and waiting to see if it's a real issue in practice before we jump to solving it.  I just wanted to start the discussion early.

**Comment by StoneCypher** [comment]
My opinion is that if you do this, which I support, that you should use the
semver stuff from the standard library. Principle of least surprise, and
all that jazz

**Comment by joshgoebel** [comment]
>  from the standard library.

What standard library?  `semver`?  I'd have to look at how much code it pulls in.

https://packagephobia.com/result?p=semver%407.3.3

All together that's a HUGE dependency when generally we believe in 0 dependencies.  I honestly don't WANT us specifying versions with such insane specificity.  If that is required, we've broken something badly.  If that was required then I'd just push it back onto the packager and say if people need maximum compatibility guarantees to use npm/yarn for dependency management rather than rebuild the same thing ourselves.  So what we do has to be *simple and useful and minimal*.

**Comment by allejo** [comment]
:+1: for adding basic semver support. I don't think it's necessary to bring in the `semver` package; on the Node.js side, we can encourage `peerDependencies`.

Now, for internal and CDN use. What if we supported something super simple like this:

```
10.7.0|11
```

This would mean:

- it will support every minor and patch release in the 10.x series after 10.7.0 (inclusive)
- it will also support everything in the 11.x series starting at 11.0.0

When we release a hljs 12, the core library will throw a warning that a specified language has not been tested on the 12.x series (with a way to silence these warnings).

**Comment by joshgoebel** [comment]
I'm thinking rather than force everyone to manage this (bump versions, keep track of what is compatible with what) that perhaps the library should just do some stronger checks at grammar compile time.  Examples:

- If a `scope` key exists but v10 doesn't know what that is, error.
- If `match` is an array but v10 expects it to be a string/regex, then error.

Generally breaking changes with grammars are changes to the keys and/or "shape"/types of the data allowed... so it should be possible to detect incompatible grammars merely by looking for unexpected keys or values.  Thoughts?

**Comment by StoneCypher** [comment]
1. There will be times at which you won't be able to detect.
    1. Occasionally those will be problematic
1. You can just make it optional.  Most people will skip it.
1. People who need to constrain the floor version because of support, and know that, will be glad the facility exists.
1. If you look at it the way node looks at engine, then it's generally an at-author-time one-time thing; as the library increments we have no maintenance cost.
    1. We don't have to keep track of anything or bump anything; we just say something like "my highlighter needs at least v9."  That won't change in v10.

You could do it yourself, but it's a big burden on you, and it's just as good to make this optional and leave it a once-write, IMO.

**Comment by joshgoebel** [comment]
Good thoughts.

> You can just make it optional. Most people will skip it.

I feel like that's a point for the auto-detection though.  If most just skip it then people just randomly find grammars that don't work anyways - and that was exactly the kind of thing we were trying to avoid. :-)  Mostly here I'm just trying to avoid the urge to solve problems that really don't exist (or won't exist) in the real world.  I feel like this is maybe a good idea, but how many people is it helping, how much time is it really saving vs investment, etc?

There is also a chicken/egg problem here in that anything we add doesn't exist in v10.  So it actually doesn't help ANY existing users... of course we could add it to the very latest v10 release... but that doesn't help anyone running prior versions of 10.  But again I worry this actually isn't a huge problem to begin with.  If anything right now I'd start with:

```
requiresVersion: 11
```

Integer. No semver, no nuance, just a big flag drawing a line from 10 to 11.  But adding this isn't at the top of the list.

**Comment by joshgoebel** [comment]
Nothing official made it into 11 but we'll keep an eye on this as we go thru the 10 -> 11 transition and perhaps by the time 12 rolls around (or sooner) we'll have  a better idea of what is needed here.

**Comment by joshgoebel** [comment]
Closing for now, can be reopened in the future if necessary.
