### ISSUE TITLE
New Language Repository Request: ZenScript

### ISSUE THREAD

**Issue by jaredlll08** [highlightjs/highlight.js#3104]
It is currently hosted here:
https://github.com/CraftTweaker/highlightjs-zenscript

But I would like a repository under the HighlightJS organisation please (something along the lines of "highlightjs-zenscript").

I also believe that I have setup the template repository right (based off of highglithjs-robots-txt), but if there is anything wrong please let me know and I'll fix it.

Thanks

**Comment by joshgoebel** [comment]
Looks good.  Your second mention of `hljs.initHighlightingOnLoad();` should really be `highlightAll()` now.

**Comment by joshgoebel** [comment]
https://github.com/highlightjs/highlightjs-zenscript

invite sent.
