### ISSUE TITLE
textproto support

### ISSUE THREAD

**Issue by hickford** [highlightjs/highlight.js#3111]
Support for textproto https://stackoverflow.com/questions/18873924/what-does-the-protobuf-text-format-look-like

**Comment by hickford** [comment]
Closing per https://highlightjs.readthedocs.io/en/latest/language-requests.html

> This means that *there's no point in requesting a new language without also providing a 3rd party implementation* (we'll simply close "Please support language Xyz" issues with a link to this explanation). If you'd like to see a particular language available but cannot implement it, the best way to make it happen is to find another developer interested in doing so.

> For more info on actually developing a language see our :doc:`language-guide`, and for information on how to properly package your 3rd party language module see :doc:`language-contribution`.

**Comment by joshgoebel** [comment]
We already support `protobuf`.  Please check the list of supported languages.
