### ISSUE TITLE
SQL update contains whitespace. Does not recognize 

### ISSUE THREAD

**Issue by follestad** [highlightjs/highlight.js#3113]
Any reason for why «update» contains trailing whitespaces. Highlight wasn't able to colour «UPDATE» until i removed the trailing spaces.

https://github.com/highlightjs/highlight.js/blob/2b9007e2da0488d4e5d7cb408fe947e845a04f95/src/languages/sql.js#L447

**Comment by joshgoebel** [comment]
Oh yikes that would be a mistake. PR welcome.

**Comment by follestad** [comment]
Also, I believe the word "explain" also should be within the RESERVED_WORDS list.

**Comment by joshgoebel** [comment]
>  I believe the word "explain" also should be within the RESERVED_WORDS list.

Pretty sure that's not in the SQL spec, but we could start a COMMON_WORDS list since I think EXPLAIN is pretty universal (despite being implemented differently).

**Comment by joshgoebel** [comment]
8ba1bfc6a1511cf8d14bbde714fa1e6216e42e38
