### ISSUE TITLE
Request for JCL"Language" support (z/OS)

### ISSUE THREAD

**Issue by db0x** [highlightjs/highlight.js#3127]
JCL is missing :)

https://en.wikipedia.org/wiki/Job_Control_Language

Then there will probably only be one person who uses it, but he would use it: D

**Comment by joshgoebel** [comment]
Closing per our policy on language requests.  https://highlightjs.readthedocs.io/en/latest/language-requests.html

You're welcome to add your request to the wiki (with a link to this issue), but generally nothing comes of doing so. https://github.com/highlightjs/highlight.js/wiki/Grammar-Requests

If you'd be interested in working on this yourself and contributing a 3rd party grammar we'd be happy to have it!  Looks like it might be a pretty simple grammar as far as such things go.
