### ISSUE TITLE
search and highlight by text

### ISSUE THREAD

**Issue by dudif91** [highlightjs/highlight.js#3128]
Hi is there a way to highlight specific text in the code?

like if I have a json: 
![image](https://user-images.githubusercontent.com/57500905/114362786-65bdf880-9b80-11eb-91b6-1a075c5fb3b7.png)

thanks

**Comment by taufik-nurrohman** [comment]
Current version should be able to preserve HTML tags in code snippet. To highlight a text, use `<mark>` tag:

~~~ .html
<pre><code class="json">{
  &quot;foo&quot;: 1,
  <mark>&quot;bar&quot;</mark>: [true, false]
}</code></pre>
~~~

**Comment by dudif91** [comment]
@taufik-nurrohman i'm using vue.js so my code looks like that:

                <highlightjs
                    language="json"
                    :code="code"
                />

do you have any suggestions on how to implement that HTML mark tag?

**Comment by taufik-nurrohman** [comment]
Put the `:code` value in a variable maybe?

~~~ .js
let sourceCode = `{
   "foo": 1,
   <mark>"bar"</mark>: [true, false]
}`;

<highlightjs language="json" :code={{sourceCode}} />
~~~

Unless the result will be HTML-escaped :\

**Comment by dudif91** [comment]
@taufik-nurrohman yes that was my first try but the result is just a simple json 

![image](https://user-images.githubusercontent.com/57500905/114380872-36fd4d80-9b93-11eb-93de-bf02f9bb4759.png)

**Comment by taufik-nurrohman** [comment]
It is because `hljs.highlight()` method does not care about child nodes and treat the input as plain text. You will need to use `hljs.highlightBlock()` but that is outside the scope of Vue plugin.

**Comment by joshgoebel** [comment]
There is no way to do this with the Vue plugin because it uses `highlight` internally (which only works with raw strings, not HTML)... the "magic" only exists in `highlightBlock`... you'd need to write a custom component that rendered the HTML block *unhighlighted* and then called `highlightBlock` to highlight it afterwards.  At that point I'm not sure you'd need a Vue component at all - depending on what you are doing.

This capability is being removed entirely in version 11 though so I'd suggest perhaps you come up with a custom solution... perhaps a "magic tag"... `<mark>` works if it's not actually ever going to exist verbatim...

- Render the component
- Grab it's inner HTML
- Replace `<mark>` and `</mark>` with your custom HTML

**Comment by joshgoebel** [comment]
Closing. Inactivity + asked and answered.

**Comment by dobromir-hristov** [comment]
Hey @joshgoebel , I just got a similar case, where I need to `mark` a search match, in the already highlighted text.

I can probably easily wrap my matched `string` inside the raw code, before highlighting, with some `magic` strings like what you suggested, but I am worried that I could break an html element, when I replace the `magic` string with a `span` or `mark`, post highlighting.

For example if we match `function(foo` inside  the snippet below

```js
function(foo, bar){...}
```

we will probably get:

```html
<span class="func"><mark>function <span class="params">(foo, </mark>bar)</span>{ ... }</span>
```

Any suggestions how to mitigate that?

**Comment by joshgoebel** [comment]
I don't think there is a great solution to that, certainly not off the top of my head.  Even the prior code that did this would have that problem IIRC - all is did was place tags exactly back in the positions they were originally I think. Ref: https://github.com/highlightjs/highlight.js/issues/2889

**Comment by dobromir-hristov** [comment]
Just want to mention for other people who search for this, using special symbols to mark your matches, like `!~~`, or `{-`, or any of the like, was causing Swift to detect those and tried to highlight them, splitting up `!~` and `~` for example. Using just a sequence of letters like `mArK` and `KrAm` proved to be less error prone so far.
