### ISSUE TITLE
Processing not highlighting with PDE

### ISSUE THREAD

**Issue by DylanMcBean** [highlightjs/highlight.js#3142]
**Describe the issue**
Processing doesnt doesn't get highlighted with `pde` shorthand

**Which language seems to have the issue?**
the language that is effect here is the Processing language

**Are you using `highlight` or `highlightAuto`?**
im not sure what discord uses specifically
...

**Sample Code to Reproduce**
No code needed

**Expected behavior**
I think Processing should highlight with `processing` aswell as `pde`, the reasoning behind this is well Javascript highlights with `javascript` and `js`, js being the javascript file extension. so Processing highlighting with `pde` would make sense since it is the file extension used by processing

**Additional context**
None Needed

**Comment by joshgoebel** [comment]
A PR would be accepted for this.
