### ISSUE TITLE
(Ruby) Heredoc without interpolation ending isn't highlighted correctly

### ISSUE THREAD

**Issue by JamesPaden** [highlightjs/highlight.js#3153]
**Describe the issue**
Ruby heredocs without interpolation have slightly different openings and closings and are not being highlighted correctly.

**Which language seems to have the issue?**
Ruby

**Are you using `highlight` or `highlightAuto`?**
highlight

**Sample Code to Reproduce**

```
# standard heredoc
message = <<-MESSAGE
  This looks good
MESSAGE

# heredoc without interpolation
message = <<-'MESSAGE'
  This isn't highlighted correctly
MESSAGE

def not_a_string_anymore()
end

```

Screenshot
<img width="377" alt="Screen Shot 2021-04-19 at 10 22 08 PM" src="https://user-images.githubusercontent.com/297533/115327884-ba074080-a15d-11eb-82c3-05ed21739f23.png">

**Expected behavior**
The entire heredoc should be highlighted as a string, with the ending detected. 

**Additional context**
Ruby documentation:
https://ruby-doc.org/core-2.5.0/doc/syntax/literals_rdoc.html#label-Here+Documents

**Comment by joshgoebel** [comment]
@JamesPaden Does that look about right?

**Comment by JamesPaden** [comment]
@joshgoebel Looks great. Thanks for the quick fix!!!
