### ISSUE TITLE
Can't bind to 'highlight' since it isn't a known property of 'code'.

### ISSUE THREAD

**Issue by paulovich10** [highlightjs/highlight.js#3172]
**Describe the issue/behavior that seems buggy**

Hi, I'm trying to highlight some logs, and it's giving the following error _Can't bind to 'highlight' since it isn't a known property of 'code'._
 his is my html

 but even when I display as in the stackblitaz declaring the code const, it won't work. I imported the modules, declared imports, and provider with the core module and it doesn't work.

![Screenshot 2021-04-28 at 17 50 08](https://user-images.githubusercontent.com/45339575/116434063-5e6a4080-a84a-11eb-954d-ad2f913ca7fd.png)

Also, I get the following message in the console:

<img width="1017" alt="Screenshot 2021-04-28 at 18 06 44" src="https://user-images.githubusercontent.com/45339575/116436360-a12d1800-a84c-11eb-83e8-193789b47d25.png">

**Sample Code or Instructions to Reproduce**

**Expected behavior**

**Additional context**

**Comment by joshgoebel** [comment]
Looks like a problem with your application or environment or whatever module is bundling us - you may want to ask them directly for help.  This does not appear to be a Highlight.js issue.
