### ISSUE TITLE
[Request] export styles in package.json in version 11.0.0-alpha1

### ISSUE THREAD

**Issue by strrchr** [highlightjs/highlight.js#3174]
I need import some css files like the following:
import xcodeCSS from "highlight.js/styles/xcode.css"

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './styles/xcode.css' is not defined by "exports" in ******\node_modules\highlight.js\package.json

**Comment by joshgoebel** [comment]
Is that truly necessary even for Just css files?  I think that might really turn me off to the whole exports idea. 😐

**Comment by joshgoebel** [comment]
What packaging/build system are you using that's throwing that error?

**Comment by joshgoebel** [comment]
@aduh95 Does this sound right to you?  I never even gave this a moments thought during the whole discussion because I thought the idea was to scope the loading of *CODE* modules not just random assets (images, CSS, etc)...

**Comment by aduh95** [comment]
Hum I didn't realize bundlers were also doing package encapsulation.. I think you should opt-out of it for non-JS folders, PR is on its way.

**Comment by joshgoebel** [comment]
Oh I think I forgot you could just do that, but don't we need sub-path patterns now?

https://nodejs.org/api/packages.html#packages_subpath_folder_mappings

**Comment by joshgoebel** [comment]
@strrchr Could you build `main` as of https://github.com/highlightjs/highlight.js/commit/bcc116c468573c37f6b6e90c4e8702f390fad9dd and test that this resolves your problem?
