### ISSUE TITLE
Strings(arguments) in local encoding doesn't marked (PHP)

### ISSUE THREAD

**Issue by WinterSilence** [highlightjs/highlight.js#3190]
Snippet: https://codepen.io/WinterSilence/pen/PopzBwK

Source code: `'Войти', 'Enter',`
Highlighted code: `('Войти', '<span class="hljs-title">Enter</span>',`

**Comment by joshgoebel** [comment]
Behavior is by design.  `php` is incorrect, you should use `php-template` for FULL templates vs just PHP code outside of a template.  This is correctly highlighted when using `php-template`.

**Comment by WinterSilence** [comment]
@joshgoebel thanks, i don't see that's solution on site
