### ISSUE TITLE
(powershell, ps1) Flag highlighted incorrectly

### ISSUE THREAD

**Issue by ANF-Studios** [highlightjs/highlight.js#3201]
**Describe the issue**
Double flag is highlighted incorrectly (`--flag` is wrong, `-flag` is right though).

**Which language seems to have the issue?**
PoweShell

**Are you using `highlight` or `highlightAuto`?**
I don't really know, I just saw it on Discord, but I'm guessing `highlight`.

**Sample Code to Reproduce**
I don't have a jsfiddle account, but I can show a screenshot:
![image](https://user-images.githubusercontent.com/68814933/118899244-5dbe4a80-b8dc-11eb-8321-01e622784e6c.png)

**Expected behavior**
It's supposed to highlight dual flag contents.

**Additional context**
See this image from PowerShell Core 7.1.3, which *highlights* both:
![image](https://user-images.githubusercontent.com/68814933/118899375-96f6ba80-b8dc-11eb-86a5-11fbac3f19bb.png)

Now, if this issue is by any chance, going to get closed because PowerShell's standard library use one hyphen flags, I think it shouldn't because if PowerShell's team decided to highlight dual hyphen flags because they know that it is going to be widely used as PowerShell is more than just that.

Anyhow, hope that information is sufficient.

**Comment by joshgoebel** [comment]
This seems like it would be a reasonable addition.

**Comment by Patil2099** [comment]
@joshgoebel  I would love to solve this issue. Can you guide me in closing this issue?

**Comment by joshgoebel** [comment]
Did into the grammar and find the mode that deals with flags (it should be sorta obvious)... recompile, test. `powershell.js`.  There are docs for how to build and test.

**Comment by ANF-Studios** [comment]
@joshgoebel, sir, I have a complaint/request here. Could these `-`/`--` flags be highlighted instead of just dropping their highlighting? That's not quite what I imagined (in terms of the highlighting) in perspective of that PowerShell flag image shown in the first issue comment of mine.

Just to be clear, this is how it currently looks on my end (with the template):
![image](https://user-images.githubusercontent.com/68814933/122858546-701b1200-d2e8-11eb-8204-6602891c0f1a.png)
Not quite what it looks compared to that, of course not comparing the color.

**Comment by joshgoebel** [comment]
That is not the behavior. I'd guess you aren't using powershell at all but perhaps another grammar. 

Are you over hundred percent sure you have loaded powershell? It's not included but default.
