### ISSUE TITLE
Add support for .edn / EDN syntax (identical to Clojure)

### ISSUE THREAD

**Issue by stelcodes** [highlightjs/highlight.js#3205]
Hello! I'm a Clojure programmer, and it seems like highlight.js could easily support EDN syntax highlighting by adding "edn" to the Clojure aliases. EDN is to Clojure what JSON is to JS. The syntax highlighting is equivalent. Is this reasonable? I use Gitea and the EDN files do not get any syntax highlighting.

https://github.com/highlightjs/highlight.js/blob/8358762bbf3f92bd45919a7893071944fc8574fd/src/languages/clojure.js#L146

**Comment by joshgoebel** [comment]
Perhaps.  Is this an official part of Clojure or some 3rd party library? Please provide a link so I could learn more.  

It's easy enough to add your own aliases though:

```js
hljs.registerAliases(["end"],{ languageName: "clojure" })
```

**Comment by stelcodes** [comment]
Hi! Yes I can provide more info. I didn't know that about JSON syntax being way different from JS! Maybe not a good comparison at all. I was just trying to say it's a subset of Clojure syntax.

EDN is definitely an official part of Clojure. [Here is the official specification](https://github.com/edn-format/edn) from the core clojure team. Clojure has [built in support](https://clojure.github.io/clojure/clojure.edn-api.html) for working with it. Here is the overview from the offical spec:

> edn is an extensible data notation. A superset of edn is used by Clojure to represent programs, and it is used by Datomic and other applications as a data transfer format. This spec describes edn in isolation from those and other specific use cases, to help facilitate implementation of readers and writers in other languages, and for other uses.

**Comment by joshgoebel** [comment]
At a glance it seems this is indeed a subset of Clojure so I think this is something we could do.  A PR would be welcome.
