### ISSUE TITLE
(Elixir) Function capture breaks further code highlighting

### ISSUE THREAD

**Issue by angelikatyborska** [highlightjs/highlight.js#3206]
**Describe the issue**

When I try to highlight an Elixir snippet that includes capturing a function (`&function_name/arity`), it seems to treat the `/` as something else until the next `/`. That's my guess... I find it hard to describe what exactly happens, so here's a screenshot:

<img width="732" alt="Screen Shot 2021-05-29 at 10 38 48" src="https://user-images.githubusercontent.com/7852553/120064146-27669500-c06b-11eb-9f62-0922e96a554a.png">

**Are you using `highlight` or `highlightAuto`?**

`highlight`

**Sample Code to Reproduce**

JS Fiddle: https://jsfiddle.net/angelikatyborska/yvd8apxo/

**Expected behavior**

I would expect the function capture `&letter?/1` to be completely white and the rest of the code colored like this:

<img width="734" alt="Screen Shot 2021-05-29 at 10 41 18" src="https://user-images.githubusercontent.com/7852553/120064174-46652700-c06b-11eb-8657-08a26ff15d76.png">

This snippet works exactly the same as the problematic one, except that instead of capturing the existing `letter?` function via `&letter?/1`, it creates an anonymous function with 1 argument that calls the function `letter?` - `&letter?(&1)`

**Comment by joshgoebel** [comment]
So are naked regex (`/blah/` without any type of sigil, etc)) even allowed in Elixir?  We seem to allow for that (which causes this problem) but I can't find any docs showing that in actual usage.

I also find the `%r` variant in addition to `~r` but can't find much on that... can anyone clear this up a bit?

**Comment by ynfle** [comment]
`regex` is basically a type of sigil

See:
 - https://elixir-lang.org/getting-started/sigils.html#regular-expressions
 - https://elixirschool.com/en/lessons/basics/sigils/

**Comment by angelikatyborska** [comment]
> So are naked regex (`/blah/` without any type of sigil, etc)) even allowed in Elixir? 

No, that's not a thing in Elixir.

What @ynfle said. The most common way of writing a regex literal in Elixir is the regex sigil.

`~` starts a sigil. The type of the sigil follows, which is a single letter, e.g. `~r` for regular expressions, `~s` for strings, `~w` for lists of strings etc. Each sigil can use any of the 8 different allowed delimiters:

```elixir
~r/hello/
~r|hello|
~r"hello"
~r'hello'
~r(hello)
~r[hello]
~r{hello}
~r<hello>
```

On top of that, sigils can have modifiers (letters) after the closing delimiter, e.g. `~r|hello|i` is a case-insensitive regex.

> I also find the %r variant in addition to ~r but can't find much on that... can anyone clear this up a bit?

`%r` does not start regex sigil. On its own, it's not even a valid expression. The only usage of `%` that comes into my mind is to either define or pattern-match maps and structs. `Regex` is a struct, so you technically you could define it like this: `%Regex{source: "hello", opts: "i"}` (equals `~r/hello/i`) but that's super rare. The only usage of `%` followed by a lowercase letter would be to pattern-match a struct name, e.g. 

```elixir
iex(9)> %r{} = ~U[2020-03-02 12:40:00Z]
~U[2020-03-02 12:40:00Z]
iex(10)> r
DateTime
```

(That's an example of a yet another sigil, one that creates a DateTime struct)

**Comment by joshgoebel** [comment]
@angelikatyborska Thanks for all the detail.  We have two variants now:

```js
        variants: [
            {
              begin: '/',
              end: '/[a-z]*'
            },
            {
              begin: '%r\\[',
              end: '\\][a-z]*'
            }
```

- naked `/regex/`
- `%r[regex]`

It seems that both of these are either outdated or simply wrong... our Elixir grammar could really use some love.  I'll rip these out then and we'll simplify.

**Comment by joshgoebel** [comment]
@angelikatyborska Could you have a look at my PR? The meat is in https://github.com/highlightjs/highlight.js/pull/3207/commits/6ac21f15a7856248fcac494abbace8dc72427147 though I'd welcome your thoughts on the `char.escape` commit as well and my understanding of escaping... is it contextual based on the type of sigil delimiter?  None of the sigil delimiters themselves are in the official list of escapable characters.

**Comment by angelikatyborska** [comment]
@joshgoebel I'll try to help but my own regex skills are very limited 🙈

> my understanding of escaping... is it contextual based on the type of sigil delimiter?

Yes. The closing delimiter needs to be escaped if it were to appear in the regular expression, for example those pairs of values are equal:
```elixir
iex()> ~r(foo_[az]) == ~r[foo_[az\]]
true

iex()> ~r(hell(o\)) == ~r/hell(o)/
true
```

**Comment by joshgoebel** [comment]
Can you really just throw a `\` in front of most anything to escape it, even if it doesn't need to be? Or will that cause trouble?

**Comment by angelikatyborska** [comment]
I'm not sure if I can answer that question well. Maybe somebody else can help here? Here's what I know:

> Can you really just throw a \ in front of most anything to escape it?

Definitely not in this regular expression:

```elixir
iex()> ~r(hell\o)
** (Regex.CompileError) missing opening brace after \o at position 5
    (elixir 1.12.0) lib/regex.ex:220: Regex.compile!/2
    (elixir 1.12.0) expanding macro: Kernel.sigil_r/2
    iex:40: (file)

iex()> ~r(hel\lo)
** (Regex.CompileError) PCRE does not support \L, \l, \N{name}, \U, or \u at position 4
    (elixir 1.12.0) lib/regex.ex:220: Regex.compile!/2
    (elixir 1.12.0) expanding macro: Kernel.sigil_r/2
    iex:42: (file)
```

In a string, there are some predefined escape codes (https://elixir-lang.org/getting-started/sigils.html#interpolation-and-escaping-in-string-sigils) so using those changes the meaning and sometimes causes compilation errors if not used correctly, e.g. for `\u` and `\x`. The rest of the letters can be escaped without a need and it doesn't do anything.
```elixir
iex()> ~s(\u)
** (ArgumentError) invalid Unicode escape character, expected \uHHHH or \u{H*} where H is a hexadecimal digit
    (elixir 1.12.0) src/elixir_interpolation.erl:106: :elixir_interpolation.unescape_string/2
    (elixir 1.12.0) expanding macro: Kernel.sigil_s/2
    iex:48: (file)

iex()> ~s(\x)
** (ArgumentError) invalid hex escape character, expected \xHH where H is a hexadecimal digit
    (elixir 1.12.0) src/elixir_interpolation.erl:106: :elixir_interpolation.unescape_string/2
    (elixir 1.12.0) expanding macro: Kernel.sigil_s/2
    iex:48: (file)

# without u and x
iex() ~s(\a\b\c\d\e\f\g\h\i\j\k\l\m\n\o\p\q\r\s\t\v\w\y\z)
"\a\bc\d\e\fghijklm\nopq\r \t\vwyz"
```

**Comment by joshgoebel** [comment]
> Definitely not in this regular expression:

Oh yeah for sure, I think I was slightly switching topics to string sigils more broadly.  Sorry for confusion. :)  

Right now we just assume `\[anything]` is a character escape - which works for 99% of things... it'll probably stay that way for now unless someone wants to invest more time in it... I tried to make it tighter but then ran into the problem that technically the escapes need to change _change per sigil_ (to include the sigil end character escape), which makes it all much more of a pain to deal with. :-)  IE, the escape detection regex has to be unique for every each type of sigil...
