### ISSUE TITLE
(chore/fix) Elixir keywords need some serious help

### ISSUE THREAD

**Issue by joshgoebel** [highlightjs/highlight.js#3210]
I know that this PR merely reformats the list, but it caught my attention because there are a lot of keywords in it that I have never seen in Elixir. Also let my starts by saying that I am not sure if there is a formal definition of a "keyword". I'm using that term rather intuitively.

As far as I know, those are not Elixir keywords at all:
- `begin`
- `break` (`Inspect.Algebra.break/1` is a function in the standard lib, but it has nothing to do with breaking out of loops like it might do in other languages)
- `defined`
- `ensure`
- `include`
- `module`
- `next` (`OptionParser.next/2` is a function in the standard lib, it has nothing to do with skipping to another iteration in a loop like it might do in other languages)
- `redo`
- `retry`
- `return`
- `until`
- `while`

I'm unsure about:
- `self`. It exists, but IMO it is a normal macro, not a keyword. I wouldn't expect it to be colored differently than other normal macros (like `rem`, `round`, `trunc` etc).
- `then`. It's a new macro added in Elixir 1.12 together with `tap`, I don't think those are keywords.
- `with|0`. I'm not sure what the pipe and zero mean here. `with` on its own is definitely a keyword.

Missing IMO:
- if `case`, `cond`, and `unless` qualify as keywords, `if` and `else` should too.
- if `quote` qualifies as a keyword, `unquote` and `unquote_splicing` should too.
- `receive`/`after` https://hexdocs.pm/elixir/Kernel.SpecialForms.html#receive/1
- `try`/`rescue`/`catch`/`after` https://hexdocs.pm/elixir/Kernel.SpecialForms.html#try/1
- `raise` https://hexdocs.pm/elixir/Kernel.html#raise/1
- `reraise` https://hexdocs.pm/elixir/Kernel.html#reraise/2

_Originally posted by @angelikatyborska in https://github.com/highlightjs/highlight.js/pull/3207#discussion_r642070670_

**Comment by joshgoebel** [comment]
> there are a lot of keywords in it that I have never seen in Elixir.

I'm starting to think this grammar may just have been borrowed/copied from another long ago (as often happened)... it seems based on this feedback that it has many flaws.

> with|0. I'm not sure what the pipe and zero mean here. with on its own is definitely a keyword.

The `|0` is a signal that the keyword should have 0 relevance (vs the default of 1) because it's too common.  This is to aid auto-detection of languages (which is something I don't think Exercism cares much about, but we do).

**Comment by joshgoebel** [comment]
@angelikatyborska  Willing to whip up a PR based on your observations just to cleanup the keyword list (on top of the work in the PR that led us to this discussion)?

**Comment by angelikatyborska** [comment]
@joshgoebel Yes, I can help out with this issue. I can start today, but if I don't finish until the end of the day, it will probably wait until next weekend (UTC+2 time).

**Comment by joshgoebel** [comment]
There is no rush unless you're in a hurry. :)  Looking forward to it whenever.
