### ISSUE TITLE
VueJS interpolation

### ISSUE THREAD

**Issue by victorcngo** [highlightjs/highlight.js#3214]
hello there,

i'm using vue-highlight.js and everything was working well so far except when i want to display interpolations (the Mustache syntax).

i would like, just like the Vue.js official doc, to be able to display : {{ message }} in a code snippet. when i do that, Vue returns me an error saying :

  ": Interpolation inside attributes has been removed. Use v-bind or the colon shorthand instead. For example, instead of <div id="{{ val }}">, use <div :id="val">.

i don't want Vue to read and interpret this variable, i just want to display it with hljs!

here's my code ;

```
<highlight-code
        class="code-snippet"
        lang="vue"
        code="
        <template>
        <div class='content'>
            <p>{{ message }}</p>
        </div>
        </template>

        <script>
        export default : {
            data() {
                return : {
                    message: 'Hello, world!'
                }
            }
        }
        </script>

        <style scoped>
        .content {
            font-size: 16px;
        }
        </style>
        "
>
</highlight-code>
```

**Comment by joshgoebel** [comment]
This is a Vue specific question, not related to Highlight.js itself.    I'll leave it open a bit if someone steps up quickly to answer it, that's fine, but you may want to ask for help elsewhere.  Tagging to auto-close.
