### ISSUE TITLE
"Usage" page is mostly empty

### ISSUE THREAD

**Issue by rmcloughlin** [highlightjs/highlight.js#3215]
https://highlightjs.org/usage/ is mostly empty.  It only contains a link to the main page.

![Screen Shot 2021-05-31 at 5 50 44 PM](https://user-images.githubusercontent.com/4472381/120244656-d3a9a680-c238-11eb-9951-2685e1aaeb3e.png)

**Comment by joshgoebel** [comment]
Usage has been repaired.
