### ISSUE TITLE
Lots of 404 responses on main page

### ISSUE THREAD

**Issue by rmcloughlin** [highlightjs/highlight.js#3216]
Lots of 404 responses on main page (https://highlightjs.org/):

![Screen Shot 2021-05-31 at 5 53 37 PM](https://user-images.githubusercontent.com/4472381/120244811-3a2ec480-c239-11eb-92ab-abc025b34c67.png)

**Comment by isagalaev** [comment]
Fixed and updated the site. Thanks for reporting it!
