### ISSUE TITLE
Version 9 of Highlight.js has reached EOL and is no longer supported

### ISSUE THREAD

**Issue by sowousmane** [highlightjs/highlight.js#3224]
Hell sorryy to bother you I saw a lot of thing above but I can't understand thing so can anyone telle me how to  solve this please ?

```
npm run start

> @ start C:\Users\gigabyte\Documents\developer_site\website
> docusaurus-start

LiveReload server started on port 35729
Docusaurus server started on port 3000
Version 9 of Highlight.js has reached EOL and is no longer supported.
Please upgrade or ask whatever dependency you are using to upgrade.
https://github.com/highlightjs/highlight.js/issues/2877
```

I am really new to this and the first person who made the project is no longer here

_Originally posted by @sowousmane in https://github.com/highlightjs/highlight.js/issues/2877#issuecomment-853904541_

**Comment by joshgoebel** [comment]
Duplicate issue.  I responded in the other thread.
