### ISSUE TITLE
[Request] Add button for selecting all languages on website

### ISSUE THREAD

**Issue by AgentSmith0** [highlightjs/highlight.js#3228]
Hello.
A button for selecting all languages on the website (https://highlightjs.org/download/) for downloading would be nice to have.

**Comment by joshgoebel** [comment]
Why do you think you need them all?  99% of the time this is NOT desirable and it's not what we recommend.  One should only choose languages they actually expect as the FULL package is huge and also much worse at auto-detection than a smaller package.

**Comment by AgentSmith0** [comment]
Okay, then I will build it from source. Anyway, thank you.

**Comment by joshgoebel** [comment]
Glad to help.  I'd seriously suggest choosing just those you have a need for though.  Many reasons: auto-detect, speed, download size, security, etc.
