### ISSUE TITLE
Option to not escape

### ISSUE THREAD

**Issue by dirslashls** [highlightjs/highlight.js#3229]
**Is your request related to a specific problem you're having?**
I already use DOMPurify to sanitize the string which is then passed to highlightjs. The sanitized string already escapes for example '<' to '&lt;'. Then is then converted to '&amp;lt' by highlightjs resutling in the final display of '&lt' in the UI instead of '<'.

**The solution you'd prefer / feature you'd like to see added...**
It would be good to be able to optionally disable the escaping done by highlightjs.

**Any alternative solutions you considered...**
I may have to look into double escape patterns and convert them back but it may be error prone.

**Additional context...**
I am using highlightjs to highlight SQL. The SQL itself is dynamically constructed which includes user input data. Hence it is explicitly being sanitized using DOMPurify. One option is to avoid using DOMPurify completely and rely only on highlightjs but I am concerned that may not be as secure.

**Comment by joshgoebel** [comment]
An option to disable security and generate un-sanitized HTML sounds ill-advised. 

>  and rely only on highlightjs but I am concerned that may not be as secure.

How so? If you have a specific concern, please share it.  We escape all 5 characters that are the least bit problematic for HTML.  This is fairly straightforward and easy to verify in our source.  The HTML we generate is perfectly safe.

I feel like perhaps you're overcomplicating your own use case?

**Comment by dirslashls** [comment]
Thanks for the quick response @joshgoebel . Please note that the user input has to be sanitized whether or not highlightjs is used as it is consumed by multiple systems and only the sanitized values are persisted. So, let me say that I don't have control on the resulting string which is guaranteed to be already safe and my request is how can I ensure an already safe string is highlighted without further escaping?

**Comment by joshgoebel** [comment]
>  Please note that the user input has to be sanitized whether or not highlightjs is used as it is consumed by multiple systems and only the sanitized values are persisted

We should be careful with terminology.  Escaping and sanitizing are entirely different things.  Input is sanitized, HTML output is escaped (before sending to a browser).  https://blog.presidentbeef.com/blog/2020/01/14/injection-prevention-sanitizing-vs-escaping/

>  my request is how can I ensure an already safe string is highlighted without further escaping?

You can't.  _The idea is fundamentally broken._  We need the source code to highlight it. The input is code, the output is HTML. IE:

- `"` starts a string.  
- `<` is an operator, etc.  
- `&quot` and `&lt;` in code are meaningless (or an error) other than in HTML.

If your values are truly HTML escaped then you need to unescape them... it makes no sense for us to do that for you. This is an application concern.  Something like Python's `HTML.unescape` (https://docs.python.org/3/library/html.html) is what you want to use.

Closing as #wontfix, existing behavior is correct.

**Comment by dirslashls** [comment]
Thank you. I swapped the order of highlighting and running it through DOMPurify and it seems to be working as expected.

**Comment by joshgoebel** [comment]
I might be worried about DOMPurify double escaping things, but if you have it working great!
