### ISSUE TITLE
[Request] Add line numbering

### ISSUE THREAD

**Issue by elbertv** [highlightjs/highlight.js#3238]
Hi, 
It is easy to explain, it would be great to put numbers to the lines of the code, like VSCode. 

Thanks. 

![image](https://user-images.githubusercontent.com/8054217/121770799-be7e2300-cb28-11eb-8e0e-cf51452d3cf4.png)

**Comment by thanoskrg** [comment]
Hi @elbertv, there is an explicit page [here](https://highlightjs.readthedocs.io/en/latest/line-numbers.html) explaining why line numbers are not implemented in this library.

tl;dr:
> Highlight.js’ notable lack of line numbers support is not an oversight but a feature

**Comment by joshgoebel** [comment]
I do wish someone would make a really nice plugin for this, but that's also part of the problem.  There are 2-3 different ways to approach line numbering from the trivial to the complex - and one size does not fit all use cases... still it's very easy to build out this sort of thing with a plugin - and we encourage it. https://github.com/highlightjs/highlight.js/issues/2225

But as already answered, it's not something that needs to be part of the core library.

**Comment by KonnorRogers** [comment]
@joshgoebel I actually have a use-case for line numbering :) My case is specifically for building a syntax-highlighted textarea with an overlaid `<pre>`

Right now I'm hacking it by just splitting at every new line and wrapping in a span.

It fails when you nest JS inside of HTML for example 

```html
<pre><code class='language-html'>
<script>
   console.log("hello world")
</script>
</code></pre>
```

Gonna see if I can hack together a line number plugin, but figured I'd throw my hat in the ring for a use-case.

<img width="968" alt="Screenshot 2023-11-19 at 2 43 05 AM" src="https://github.com/highlightjs/highlight.js/assets/26425882/a04af259-a116-4f3f-af3e-de79ca7ba390">

^ The above editor is using Highlight.js for highlighting and I really don't want to move to PrismJS, but it makes it much easier to apply line highlighting.
