### ISSUE TITLE
Formatting (newlines and indentation) lost after parsing

### ISSUE THREAD

**Issue by wolfiex** [highlightjs/highlight.js#3242]
**Describe the issue/behavior that seems buggy**
The newline formatting and indentation of the code is lost after parsing with hilight. 

**Sample Code or Instructions to Reproduce**
Starting with a string literal:
```  south_row = i
  north_row = num_rows
  DO i = num_rows, 1, - 1
    IF (ANY(frame_mask(:, i))) THEN
      EXIT
    END IF
  END DO
```

I run the following 
```
code.innerHTML = hljs.highlight(data.code, {language: 'f90'}).value
```

which results in no newlines and a loss of indentation. 

I am able to fix the newlines by appending `.replace(/\n/g,' <br> ')` to the end, but have had no such luck regarding the initial indentation. 

#### Update: 
Inline indentation can be achieved through 
```
hljs.highlight(data.code.replace(/  /g,' --- '), {language: 'f90'}).value.replace(/\n/g,' <br>').replace(/ --- /g,'&nbsp;&nbsp;')
```
It almost feels like this should be done in the background, with a possible argument/switch.

```

**Comment by joshgoebel** [comment]
Are you putting this content in `<pre><code>` block?  That is the happy path.  If you're doing something else then yes you need to jump thru a lot of hoops to deal with spacing and newlines and things you get for "free"  when on the happy path.

*Indents*

We do no special processing of tabs (or spacing)... if you want to convert them to spaces, you need to do that yourself.  If you want to style them with CSS (usually simpler) you can use `tab-size`.

> code.innerHTML 

**Newlines mean nothing in HTML outside of `<pre>` .**   If you're having to add `<br>` yourself then I'd guess you're not using `<pre>`, in which case -yes, that's just what you must do.

**Comment by wolfiex** [comment]
I was using the code block but has forgotten the preformatted text element. 

Thanks
