### ISSUE TITLE
Building extra languages on Windows fails

### ISSUE THREAD

**Issue by allejo** [highlightjs/highlight.js#3248]
**Describe the issue/behavior that seems buggy**

In this example, I'm adding [cshtml-razor](https://github.com/highlightjs/highlightjs-cshtml-razor) to the `extras` folder and it builds successfully on *nix. However, on Windows it fails with the following output:

```
Starting build.
Finished build.
Writing docs files.
Writing demo files.
Writing style files.
Preparing languages.
................................................................................................................................................................................................
Building highlight.js.
'C:Users
eposhighlight.jsextracshtml-razorsrclanguagescshtml-razor.js' is imported by builtInLanguages, but could not be resolved – treating it as an external dependency
No name was provided for external module 'C:Users
eposhighlight.jsextracshtml-razorsrclanguagescshtml-razor.js' in output.globals – guessing 'C_Users_jimenezsource_eposhighlight_jsextracshtmlRazorsrclanguagescshtmlRazor_js'
-----
Core                : 82385 bytes
Core (min)          : 19743 bytes
Languages (raw)     : 1128664 bytes
highlight.js        : 1556501 bytes
highlight.min.js    : 961240 bytes
highlight.min.js.gz : 278920 bytes
-----
```

**Sample Code or Instructions to Reproduce**

N/A

**Expected behavior**

It compiles successfully.

**Additional context**

I've tracked down this bug to `LanguagePackage::trySrcLanguages()`. It's using `process.cwd()` which ultimately results in rollup trying to do `import ... from 'C:\username\...\extra\cshtml-razor\...'`. Node doesn't like this.

https://github.com/highlightjs/highlight.js/blob/50a680877b2777ce2fe30f083037652f9decb5c9/tools/lib/external_language.js#L14-L24

I was able to fix the above by changing it to,

```js
this.files = languages.map(fn => './' + fn);
```

I'm not sure what the purpose of `process.cwd()` serves here since there are explicit references to `./src/languages` and `tools/build.js` doesn't work unless it's from the root directly (unless you force it to). Is there a better way of fixing it?

**Comment by joshgoebel** [comment]
>  there are explicit references to ./src/languages

Where?

> and tools/build.js doesn't work unless it's from the root directly

I've used it outside before IIRC.

---

What is the value of `this.dir`?  It seems everything should just be written in relation to that, as with `markupTestPaths`, `detectTestPaths`, etc...

**Comment by allejo** [comment]
> > there are explicit references to ./src/languages
> 
> Where?

e.g.

https://github.com/highlightjs/highlight.js/blob/50a680877b2777ce2fe30f083037652f9decb5c9/tools/lib/language.js#L72-L83

https://github.com/highlightjs/highlight.js/blob/50a680877b2777ce2fe30f083037652f9decb5c9/tools/lib/language.js#L104-L108

> > and tools/build.js doesn't work unless it's from the root directly
> 
> I've used it outside before IIRC.

```
C:\Users\vjimenez\source\repos\highlight.js\extra>node ..\tools\build.js -t browser
Starting build.
Finished build.
C:\Users\vjimenez\source\repos\highlight.js\node_modules\del\index.js:37
                throw new Error('Cannot delete files/directories outside the current working directory. Can be overridden with the `force` option.');
                      ^

Error: Cannot delete files/directories outside the current working directory. Can be overridden with the `force` option.
    at safeCheck (C:\Users\vjimenez\source\repos\highlight.js\node_modules\del\index.js:37:9)
    at C:\Users\vjimenez\source\repos\highlight.js\node_modules\del\index.js:108:4
    at Array.map (<anonymous>)
    at AsyncFunction.module.exports.sync (C:\Users\vjimenez\source\repos\highlight.js\node_modules\del\index.js:104:29)
    at clean (C:\Users\vjimenez\source\repos\highlight.js\tools\lib\makestuff.js:9:7)
    at doTarget (C:\Users\vjimenez\source\repos\highlight.js\tools\build.js:89:9)
    at doBuild (C:\Users\vjimenez\source\repos\highlight.js\tools\build.js:103:5)
    at Object.<anonymous> (C:\Users\vjimenez\source\repos\highlight.js\tools\build.js:110:1)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)

C:\Users\vjimenez\source\repos\highlight.js\extra>
```

> What is the value of `this.dir`? It seems everything should just be written in relation to that, as with `markupTestPaths`, `detectTestPaths`, etc... if they already are is it possible the map isn't needed at all?

In `getThirdPartyPackages`, this is what I end up as the `LanguagePackage`. See how it's a full Windows path?

![image](https://user-images.githubusercontent.com/1246453/122473854-432ccf00-cf77-11eb-87a3-78bc79fa6582.png)

Updating the `map` to prepend `./` makes this work in a sane manner.

![image](https://user-images.githubusercontent.com/1246453/122474037-7ec79900-cf77-11eb-865c-2c79a1fee674.png)

The map for a `./` is needed however because of this block:

https://github.com/highlightjs/highlight.js/blob/50a680877b2777ce2fe30f083037652f9decb5c9/tools/lib/language.js#L72-L83

If there's no `./` it'll try to assume that extra paths are in `./src/languages/extra/cshtml-razor/src/languages/...`

**Comment by joshgoebel** [comment]
>  if (path.isAbsolute(filename) || filename.startsWith(".")) 

Is this truly necessary at all? Seems to work fine for me if we just remove this and assume all paths are relative... then the `map` operations seems unnecessary.  Thoughts?

It looks like this is expecting "basic.js" as filename but we never pass that... the relative location is always used (as far as I can see)

**Comment by allejo** [comment]
I can confirm that the `else` condition is never hit in my testing on both macOS and Windows. However, it seems the `map` operation is still necessary; the `glob` call will return `extra/cshtml-razor` instead of `./extra/cshtml-razor` (i.e. the `./` is necessary for me on Windows with Node 16). I'll submit a PR with this change

**Comment by joshgoebel** [comment]
How does it fail without the .  Those should be essentially equivalent.

**Comment by allejo** [comment]
Without the `./`, it fails at the Rollup step on Windows.

```
C:\Users\vjimenez\source\repos\highlight.js>node tools/build.js -t browser
Starting build.
Finished build.
Writing docs files.
Writing demo files.
Writing style files.
Preparing languages.
...........................................................................................................................................................................................
.....
Building highlight.js.
'extra/cshtml-razor/src/languages/cshtml-razor.js' is imported by builtInLanguages, but could not be resolved – treating it as an external dependency
No name was provided for external module 'extra/cshtml-razor/src/languages/cshtml-razor.js' in output.globals – guessing 'cshtmlRazor_js'
```
