### ISSUE TITLE
Child tags like ins/del not reserved when highlighted

### ISSUE THREAD

**Issue by chadluo** [highlightjs/highlight.js#3253]
**Describe the issue/behavior that seems buggy**

Some tags like ins/del are not reserved when the code is highlighted.

**Sample Code or Instructions to Reproduce**

Please refer to https://codepen.io/chadluo/pen/gOmJWae

**Expected behavior**

The ins/del tags should be reserved when highlighted.

**Additional context**

Version 10.7.2 is working as expected but 11.0.1 is not.

**Comment by chadluo** [comment]
Sorry haven't read #2886, but is it possible if we allow some certain HTML tags?

My use case is to support syntax highlight for BitBucket pull request (https://gist.github.com/chadluo/c526b1a32d8f985df99e2f159c37c0a4), and since it's showing code diff it comes with `ins`s and `del`s. It would be really good if we can reserve even only these tags without compromising security.

**Comment by joshgoebel** [comment]
This is correct behavior and exactly as intended.  If someone wishes to merge in HTML automatically they will now need to use a plugin to do so - a partially written plugin can be found in that issue (though it will no longer work without some modifications). The best thing would be for someone to take that (or write a simpler alternative if possible) and publish (and maintain) an official plugin.
