### ISSUE TITLE
[Request] [julia-repl] Class name for prompt

### ISSUE THREAD

**Issue by fredrikekre** [highlightjs/highlight.js#3261]
I would like style the prompt in the `julia-repl` language separately. Currently it is styled as `meta`, https://github.com/highlightjs/highlight.js/blob/55f68f72be2cb69d14561353ad851d6b2242dfcc/src/languages/julia-repl.js#L30 which seems to match what e.g. `python-repl` also do. I wonder if it would be welcome (welcome as in would such a PR be accepted) to also add `keyword` (or something more appropriate?) to this so that it is possible to style the prompt with e.g.
```css
.hljs-meta .hljs-keyword {
    /* stuff */
}
```
? I don't think anything else in the julia grammar uses that, so should be no difference for existing themes.

cc @mortenpi

**Comment by joshgoebel** [comment]
> so that it is possible to style the prompt ...  to also add keyword ...

Generally this is not how we think about theming.  The parsers/grammar goal is to classify the text, the CSS/themes job is to highlight it.  We try to not classify based on what the *output* should *look* like.  So it it's not semantically a keyword without a meta block, then that's a no go.  If you wanted to target only _top-level_ `meta` tags in `python-repl`, you should be able to already do this with perhaps `code.language-python-repl > span.hljs-meta`, or similar CSS. Would that not work to target prompts?

I will agree though that `meta` isn't the best classification (as it's overly broad and a bit fuzy)... but that's legacy, before my time as maintainer - and it's going to take a bit of long-term effort to turn the ship there.

> (or something more appropriate?)

One could perhaps make a reasonable case for a `meta.prompt` scope (though the patch would be much larger and target EVERY grammar with a repl prompt, and likely shells also, etc.). We also should look at how Textmate grammars and Prism categorize such things to see if a better scope name might present itself (perhaps there is something better than meta). [Related: #2500]   I'm not 100% opposed to this idea, but I do lean against it _slightly_ if the use case can already be solved with existing scopes and simple CSS. KISS and all.

**Comment by joshgoebel** [comment]
I'll give you a chance to respond first but I think this will end up being closed as a dup of the newly created #3265.  While `meta.prompt` (on it's own) isn't a super exciting task, properly fixing the entire meta namespace is something I think we should clearly do - and it would make sense to figure out how to properly classify prompts as part of that effort.

I'm pretty sure #3265 covers your actual underlying issue, let me know if I'm mistaken.

**Comment by fredrikekre** [comment]
> If you wanted to target only top-level meta tags in python-repl, you should be able to already do this with perhaps code.language-python-repl > span.hljs-meta, or similar CSS.

Yes, this does what I want, thanks.

> Generally this is not how we think about theming. The parsers/grammar goal is to classify the text, the CSS/themes job is to highlight it. We try to not classify based on what the output should look like.

Right. I guess part of the problem is that prompts are not really part of the language, so they don't really have natural classification I suppose.

> I'll give you a chance to respond first but I think this will end up being closed as a dup of the newly created #3265.

Yea, sounds good. My (immediate) needs are satisfied with that CSS you proposed.

**Comment by joshgoebel** [comment]
> My (immediate) needs are satisfied with that CSS you proposed.

Awesome!

> ..part of the problem is that prompts are not really part of the language, so they don't really have natural classification I suppose.

They are if you think about the "language"/grammar really begin Julia+REPL, not Julia... and in the REPL `^julia>` has a very clear semantic meaning, it's the REPL prompt. :-)  The problem is just that we don't have a *separate* scope to classify it. :-)

**Comment by joshgoebel** [comment]
@fredrikekre FYI this is happening in #3490

**Comment by fredrikekre** [comment]
Thanks for the ping, thats great news!
