### ISSUE TITLE
(javascript) Strange highlighting for defining a sequence of constants

### ISSUE THREAD

**Issue by njlarsson** [highlightjs/highlight.js#3262]
Hi. I'm including a screenshot of the result on highlighting code with `hljs.highlight(raw, { language: 'js' })` If I switch to `hljs.highlightAuto(raw)`, it looks fine, but the detected language is not javascript, but coffeescript in this version where I deleted an initial license comment block, and java if I don't delete the license comment. In both cases, the result looks fine.

**Sample Code to Reproduce**

    import { listenForEvents } from './device_input.js';

    // Set up to control players from my Rega CD remote control. Edit it to make it
    // work for some other remote.
    export const setupNumpad = (numpadDev, eventSizes, getIntf, playStream) => {
        const KEY_BACKSPACE  = 14;
        const KEY_TAB        = 15;
        const KEY_ENTER      = 28;
        const KEY_KPASTERISK = 55;
        const KEY_KP7        = 71;
        const KEY_KP8        = 72;
        const KEY_KP9        = 73;
        const KEY_KPMINUS    = 74;
        const KEY_KP4        = 75;
        const KEY_KP5        = 76;
        const KEY_KP6        = 77;
        const KEY_KPPLUS     = 78;
        const KEY_KP1        = 79;
        const KEY_KP2        = 80;
        const KEY_KP3        = 81;
        const KEY_KP0        = 82;
        const KEY_KPDOT      = 83;
        const KEY_KPSLASH    = 98;

        listenForEvents(numpadDev, eventSizes, getIntf, [
            [1, KEY_KP1, 1, () => { playStream('p1') }],
            [1, KEY_KP2, 1, () => { playStream('p2') }],
            [1, KEY_KP3, 1, () => { playStream('p3') }],
            [1, KEY_KP4, 1, () => { playStream('p2m') }],
            [1, KEY_KP0, 1, (intf) => { if (intf && intf.quit) { intf.quit() } }],
            [1, KEY_KPDOT, 1, (intf) => { if (intf && intf.toggle_pause) { intf.toggle_pause() } }]
        ]);
    }

**Additional context**

This is an ES6 style module that I run with Node.js version v14.17.0, which has no problem with it. The package.json file needs to contain a `"type": "module"` to make Node.js handle .js files as modules.
<img width="762" alt="Screenshot 2021-07-05 at 14 16 29" src="https://user-images.githubusercontent.com/745608/124471707-7ce63e00-dd9d-11eb-8ddb-f4bdec5865d4.png">

**Comment by njlarsson** [comment]
… More specifically: the problem seems to be that identifiers ending with a digit are not recognized. I tried adding one called `SOMETHING4`, and it came out black also.

**Comment by joshgoebel** [comment]
Yes. That would likely be the problem. A PR would be welcome as this is something we should fix.

**Comment by joshgoebel** [comment]
Resolved via 5befcb1b
