### ISSUE TITLE
Undocumented breaking change in 11.0: location of themes changed

### ISSUE THREAD

**Issue by bakkot** [highlightjs/highlight.js#3266]
https://github.com/highlightjs/highlight.js/pull/3139 moved the directories of some themes. Since the recommended way to include a theme is by adding it by path as in `https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.5.0/styles/solarized-light.min.css`, that means that simply bumping the version number will give you a 404 (the correct URL is now `https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.0.1/styles/base16/solarized-light.min.css` - note the addition of `base16`). This should probably be noted in the [upgrade guide](https://github.com/highlightjs/highlight.js/blob/1cb086b9509aa6af65e09a8936c5d93c9fe8178b/VERSION_11_UPGRADE.md).

**Comment by joshgoebel** [comment]
Closed via ca331e9f

**Comment by joshgoebel** [comment]
Thanks for reporting.
