### ISSUE TITLE
before:highlight and after:highlight not fire on highlightAuto function

### ISSUE THREAD

**Issue by kadircancetin** [highlightjs/highlight.js#3268]
**Describe the issue/behavior that seems buggy**

- `highlightAuto` function not fire plugin hooks.

**Sample Code or Instructions to Reproduce**

- you see alert (code block has class `language-python`) : https://jsfiddle.net/kahredici/cvt6o95L/2/
- you don't see alert : https://jsfiddle.net/kahredici/cvt6o95L/3/

**Expected behavior**
- fire hooks

**Comment by joshgoebel** [comment]
This is by design, `highlight != highlightAuto`.  HighlightAuto calls `highlight` (internally) potentially 200 times then uses the "best one", they are not necessarily very similar for callback purposes.

What are you trying to accomplish with your plugin?

**Comment by kadircancetin** [comment]
I am trying to write plugin that use deprecated custom html modification. In #2889 your suggestion was get data from before highlight hook.

I am an actually backend developer and my js knowladge is limited. I will use this plugin for just readonly purpose so I don't have any security problem.

**Comment by joshgoebel** [comment]
Can you use `highlightBlock` and it's associated callbacks instead?

**Comment by joshgoebel** [comment]
Also I forgot about #2768, though that's not an immediate help.

**Comment by joshgoebel** [comment]
Closing this as a dup of #2768, which should resolve this when implemented.
