### ISSUE TITLE
(javascript) console.log doesn't highlight correctly

### ISSUE THREAD

**Issue by nollexu** [highlightjs/highlight.js#3271]
![image](https://user-images.githubusercontent.com/34390589/125474620-a760aada-f47d-49eb-beef-5b0ed02c71e2.png)
![image](https://user-images.githubusercontent.com/34390589/125474669-650219c8-885c-4daa-9800-f0680677281b.png)
![image](https://user-images.githubusercontent.com/34390589/125474939-47b54760-1b39-452e-808c-7c4b35044dd2.png)
The first chapter is my own display effect. The second picture is the effect on the official website. The third picture is my code. Why is the `log` not highlighted?

**Comment by joshgoebel** [comment]
My guess would be you're using a theme that doesn't highlight function invitation perhaps?  What is the generated HTML?

**Comment by joshgoebel** [comment]
Log the result of highlight to console and see if that provides any clues.

**Comment by nollexu** [comment]
> My guess would be you're using a theme/CSS that doesn't highlight function invokation perhaps? What is the generated HTML?
> 
> Perhaps your code is not detected as JS or you're using an older version of the library? I'm not sure marked has been updated?

Thank you for answering my question.And the following two images are the generated HTML and the version number.
![image](https://user-images.githubusercontent.com/34390589/125551237-5a52986a-dee0-4f54-a419-b7925832c458.png)
![image](https://user-images.githubusercontent.com/34390589/125551281-d006deed-cb23-4812-9fff-eb9226191078.png)

**Comment by joshgoebel** [comment]
_Please attach raw text of the code in question._

**Comment by joshgoebel** [comment]
Sorry I see now. With 11.1 locally:

<img width="834" alt="Screen Shot 2021-07-14 at 4 38 45 PM" src="https://user-images.githubusercontent.com/6473/125689762-3a754e8a-a0ac-44aa-802a-9765a1b7320e.png">

It's hard to surmise anything other than you're using an incorrect/older version despite you thinking you're using the latest...
