### ISSUE TITLE
(TypeScript) Generics with extends broken from 10.3.0

### ISSUE THREAD

**Issue by jaybeeuu** [highlightjs/highlight.js#3276]
**Describe the issue**

Generic types using the `extends` keyword break subsequent highlighting.

![image](https://user-images.githubusercontent.com/2077433/125857694-b04f2efe-a0d2-41f7-a955-d99162837aa4.png)

I bisected a bit and tracked it down to a change between [10.2.1 and 10.3.0](https://github.com/highlightjs/highlight.js/compare/10.2.1...10.3.0)

Could be [this](https://github.com/highlightjs/highlight.js/commit/f5e24b9413265fe76ff24244e2642f47d722a8e4) commit? (only because It's the only one in there marked typescript that I could see.)

**Which language seems to have the issue?**
TypeScript

**Are you using `highlight` or `highlightAuto`?**
I've definitely seen it with `hljs.highlightBlock` and `hljs.highlight` in my code.

**Sample Code to Reproduce**

http://jsbin.com/tutirup/edit?html,output

```ts
interface Prefixer<Something extends string> {
  (): `other__${Something}`;

  parse: <From extends string>(
    value: From
  ) => number;
}

const cloneWith = <T, A extends keyof T, V>(
  i: T,
  a: A,
  value: V
): Omit<T, A> & {[K in A]: V} => ({
  ...i,
  [a]: value,
});

const source = { name: 'bob', age: 90 };
const result = cloneWith(source, 'age', 'old!');
type TestSource = typeof source.age // number
type TestResult = typeof result.age // string
```

**Expected behavior**

Switching back to 10.2.1 gives this:

![image](https://user-images.githubusercontent.com/2077433/125858275-4952da72-a336-48c6-85b5-19b46f1f04bc.png)

**Additional context**

I've seen this in a couple of places... my blog, VSCode's markdown preview and found an issue in [SO meta](https://meta.stackoverflow.com/questions/407040/typescript-syntax-highlighting-seems-broken-in-this-question) (i stole some code from the question linked there for this repro).

**Comment by joshgoebel** [comment]
Just to be clear is this an issue with latest v11 also then?

**Comment by jaybeeuu** [comment]
Ahh sorry, yes the wasn't very clear.

I found the problem in 11.1.0.

10.3.0 only came up because that was the first version I could find which showed the problem.

**Comment by joshgoebel** [comment]
Isn't `<>` typecasting deprecated in favor of `as`?

```
  parse: <From extends string>(
    value: From
  ) => number;
```

I'm not sure I'm even following what this is doing sytantically.

**Comment by jaybeeuu** [comment]
:) it is pretty contrived for sure. looking now I'm not sure I can even make up a reason someone would want a type like that. but the syntax is valid. It's not a typecast:, it's a [generic type](https://www.typescriptlang.org/docs/handbook/2/generics.html#generic-type).

Thanks for looking at the problem! If there's any thing i can do to help get that PR over the line then please let me know.

**Comment by joshgoebel** [comment]
@jaybeeuu 

If we deal with `<Something extends ...` as a special case, will that solve things or are there other variants of types that will also look like html? (I mean technically it could still be HTML, but that's a smaller edge case IMHO)

`<T, A extends keyof T, V>`

This is easy to handle because `,` is not valid HTML - so we can immediately bail.

**Comment by jaybeeuu** [comment]
Hey, yeah I think even for a proper parser its a headache to tell the difference. I'm pretty sure that's why why typescript requires the use of the .tsx extension to enable jsx. I think it puts the parser into a different mode. Certainly on things like arrow functions in .tsx files it seems to assume jsx before generic so you need to do things like add commas to tell it to stop.

To my knowledge the only things that can follow the name of a type argument in a to generic are

* ,
* extends
* >

I dont think there's any other keywords or operators, and a quick scroll through the docs confirms that.

I reckon you're right that handling extends as a special case would be ok. 

(Next issue is bound to be someone saying their jsx with `extends` boolean prop has stopped highlighting... but at least i'll be happy.... :D )
