### ISSUE TITLE
Alias `language-http` removed => List of aliases removed

### ISSUE THREAD

**Issue by AltarBeastiful** [highlightjs/highlight.js#3277]
**Describe the issue/behavior that seems buggy**
Before 11.0 I could highlight HTTP using the `language-http` tag.
Now I have to use `protocol-http`.

**Sample Code or Instructions to Reproduce**
https://codepen.io/altarbeastiful/pen/mdmmOmN

**Expected behavior**
I understand the semantic of removing the language alias, and you mentioned it in the CHANGES.md. But, can you point me where I can find the full list of aliases removed, so I can correctly update my application.

**Comment by joshgoebel** [comment]
> Before 11.0 I could highlight HTTP using the language-http tag. Now I have to use protocol-http.

`protocol-http` does nothing, so it's just ignored.

Please see: https://github.com/highlightjs/highlight.js/blob/main/VERSION_11_UPGRADE.md#built-in-set-of-common-languages

`http` is no longer included in the default build.  You'll need to:

- build your own (see documentation on building)
- download a custom build from the website
- load the `http.js` grammar separately, see instructions in README
