### ISSUE TITLE
Language detected is wrong when using comments inside the block

### ISSUE THREAD

**Issue by luispcosta** [highlightjs/highlight.js#3282]
**Describe the issue/behavior that seems buggy**

Whenever a code block contains code in comments, the CSS class(es) applied to the code block is of a different language which will naturally screw up the syntax and the visual apparence of the text.
I could reproduce this issue with, at least, objectivec and swift.

**Sample Code or Instructions to Reproduce**

When writing:

![Screenshot 2021-07-22 at 09 12 50](https://user-images.githubusercontent.com/7049711/126608426-f01ba6c2-06eb-4000-b40e-867998192658.png)

And:

![Screenshot 2021-07-22 at 09 13 09](https://user-images.githubusercontent.com/7049711/126608463-efabeef2-5518-479d-b9b4-018924acecb1.png)

It produces the wrong highlighting:

![Screenshot 2021-07-22 at 09 14 10](https://user-images.githubusercontent.com/7049711/126608589-84f84698-01bd-4b51-9057-d70c9a88a8f7.png)

If we take a look at the classes added:

For the Objective-C block:
![Screenshot 2021-07-22 at 09 17 38](https://user-images.githubusercontent.com/7049711/126609042-e43cbd0f-a9f2-4c93-b44d-478c42d57c6e.png)

It's identifying the block as an SQL code block...

For the Swift Block:
![Screenshot 2021-07-22 at 09 18 04](https://user-images.githubusercontent.com/7049711/126609093-7e0a8693-7f42-4f47-9eb1-a448c3758744.png)

It's identifying the block as a bash code block...

If we remove the comments from the markdown

![Screenshot 2021-07-22 at 09 21 17](https://user-images.githubusercontent.com/7049711/126609552-7e6788a6-efcb-4d5e-8a6a-aab0ee48ea22.png)

**Expected behavior**
I expected the code blocks to appear correctly with the comment syntax.

**Additional context**
* I'm using [mkdocs](https://www.mkdocs.org/) to process my markdown.
* I'm using version `11.1.0` of highlightjs

**Comment by joshgoebel** [comment]
I'm confused because I don't see any Highlight.js specific CODE here... We highlight markdown, but we do not sub-highlight code blocks.  Something such as:

````
```basic
10 PRINT "HELLO"
```
````

Would be highlighted as:

````
<span class="hljs-code">
```basic
10 PRINT "HELLO"
```
</span>
````

It is our policy to highlight Markdown NOT render/parse it... which means that all back-block are nothing more than code to us, not specific types of code that need their own highlighting.  I think perhaps you issue is with mkdocs, not us.

**Comment by joshgoebel** [comment]
Ping. can you provide additional detail?

**Comment by luispcosta** [comment]
Turns out it was a problem on our end, on the way we were using our stylesheets :) Nothing to do with highlightjs, sorry for the false ticket!
