### ISSUE TITLE
v11.1 themes are missing styles from examples on site

### ISSUE THREAD

**Issue by bgp1** [highlightjs/highlight.js#3284]
Hello,

I recently updated to v11.1 and noticed all of the highlight.js blocks now have incorrect/broken styles. The examples on the website all look correct. When I check the theme files from the npm package (and the src folder in this repo) vs the dist files that are on the highlight.js examples page I see the theme files are all missing the following:

```
pre code.hljs {
    display: block;
    overflow-x: auto;
    padding: 1em
}

code.hljs {
    padding: 3px 5px
}
```

Once I manually added this to my code base everything looked as I would expect.

**Comment by joshgoebel** [comment]
Ah, nice catch.  We now need to process/build CSS for Node the same way we do for our web builds...

**Comment by joshgoebel** [comment]
I think this fixes it.  After it's merged I'll issue a point release with the fix.
