### ISSUE TITLE
(Javascript) Slashes in template literal break parsing

### ISSUE THREAD

**Issue by bergus** [highlightjs/highlight.js#3288]
**Describe the issue**

A slash inside a template literal, after a slash inside an interpolation expression inside the template literal, breaks the recognition of the template literal end delimiter. This doesn't happen if there is no slash in the expression, or if the string slash comes before the interpolated expression.

**Which language seems to have the issue?**

Both JavaScript and TypeScript. Also when autodetected.

**Are you using `highlight` or `highlightAuto`?**

I dunno, I've come across this [somewhere on StackOverflow](https://stackoverflow.com/questions/68521841/catch-doesnt-work-when-the-api-cant-be-reached) - but specifying the language of the code block didn't help either. In the sample code below, I tried to make a minimal reproducible example, which might not autodetect as JS - but if you put that snippet in a larger code block that *is* successfully autodetected as JS, the same problem occurs.

**Sample Code to Reproduce**

```js
`${dividend/divisor} / `;
const oops = 1;
```
![Screenshot from output of above code, rendered on StackOverflow](https://user-images.githubusercontent.com/1146478/126911611-02b70c3a-3185-41e2-abfb-4f93706a4f15.png)

**Expected behavior**

Github gets it right - the template literal ends with the `` ` ``, and the next line is highlighted normally not seen as a continuation of the template string. The `const` declaration should be recognised, such as in the following example:

![same code with ellipsis instead of slash](https://user-images.githubusercontent.com/1146478/126911711-c08f834d-3a04-41b6-aac2-b959f9b9d74b.png)

**Comment by joshgoebel** [comment]
I'm not quite sure how to fix this without removing REGEX mode complete from inside subst... which I'm not sure would be a huge loss, but that's what is happening here... the `/` is seen as the beginning of a regular expression.
