### ISSUE TITLE
[Request] Line numbers plugin for the latest highlight.js verison

### ISSUE THREAD

**Issue by AgentSmith0** [highlightjs/highlight.js#3291]
I searched for a plugin that adds line numbers to highlight.js. I read the following article: https://highlightjs.readthedocs.io/en/latest/line-numbers.html and I found this library: https://github.com/wcoder/highlightjs-line-numbers.js But this library is not compatible with the latest highlight.js version (11.1).

Do you know any other plugin that adds line numbers and works with the latest version?

**Comment by taufik-nurrohman** [comment]
https://github.com/taufik-nurrohman/highlight.ln.js

Is this compatible?

**Comment by AgentSmith0** [comment]
Thank you very much, this is working!
