### ISSUE TITLE
(CSS) Inline comments are not highlighted correctly (regression between 10.5.0 and 10.6.0)

### ISSUE THREAD

**Issue by deniskovalchuk** [highlightjs/highlight.js#3299]
**Describe the issue**

Inline comments are not highlighted correctly starting from hljs 10.6.0 (new `highlightAll` API).

**Which language seems to have the issue?**

CSS

**Are you using `highlight` or `highlightAuto`?**

`highlightAll`

**Sample Code to Reproduce**

Version 11.1.0 (using `highlightAll`):
https://jsfiddle.net/7eu8pdkx/

Version 10.5.0 (using `initHighlighting`):
https://jsfiddle.net/3brz5gk9/

**Expected behavior**

![expected](https://user-images.githubusercontent.com/15797194/127864480-f3f86d2e-d82d-4060-b1ac-cd79e6c4b93a.png)

**Actual behavior**

![actual](https://user-images.githubusercontent.com/15797194/127864600-624f6d0c-1d9e-46e5-8d6d-66e1dd0f93ac.png)

**Comment by joshgoebel** [comment]
Could you have a look at #3301?

**Comment by deniskovalchuk** [comment]
I've tested #3301 in my production environment and it fixes the issue for me, thanks.

**Comment by joshgoebel** [comment]
Thanks, assigned it for review.
