### ISSUE TITLE
(CSS) Prefixed properties are not highlighted correctly (regression between 10.5.0 and 10.6.0)

### ISSUE THREAD

**Issue by deniskovalchuk** [highlightjs/highlight.js#3300]
**Describe the issue**

Prefixed properties are not highlighted correctly starting from hljs 10.6.0 (new `highlightAll` API).

**Which language seems to have the issue?**

CSS

**Are you using `highlight` or `highlightAuto`?**

`highlightAll`

**Sample Code to Reproduce**

Version 11.1.0 (using `highlightAll`):
https://jsfiddle.net/grbtnsdp/

Version 10.5.0 (using `initHighlighting`):
https://jsfiddle.net/0kxoqjfv/

**Expected behavior**

![expected](https://user-images.githubusercontent.com/15797194/127875387-a020215d-c2dd-40a5-87e9-75a9b3dda84b.png)

**Actual behavior**

![actual](https://user-images.githubusercontent.com/15797194/127875552-c9d130cc-746b-4c51-aed1-4871e8cfc721.png)

**Comment by joshgoebel** [comment]
This was intentional. Prefixes are vendor specific and not part of the official name.
