### ISSUE TITLE
ESM Import from "/highlight.js/es/index.js" Fails.

### ISSUE THREAD

**Issue by theengineear** [highlightjs/highlight.js#3304]
:wave: — Hello there! I'm having trouble importing files via an ESM import. I'd expect the following to work:

```js
import hljs from 'https://unpkg.com/highlight.js@11.2.0/es/index.js';
// Uncaught (in promise) SyntaxError: The requested module '../lib/index.js' does not provide an export named 'default'
```

Here's a [JSFiddle](https://jsfiddle.net/theengineear/a9oLwmv3/latest) which reproduces this error. As a workaround, I'm using [your minified code](https://unpkg.com/@highlightjs/cdn-assets@11.2.0/es/highlight.min.js) for now.

Happy to provide more context if that's helpful!

**Comment by joshgoebel** [comment]
Our main node npm package is purposely not for raw web usage. Please use our cdn-assets npm package instead if you want web ready ESM assets that can be pulled right odd a CDN.

**Comment by theengineear** [comment]
Thanks for the fast response @joshgoebel! Apologies, I should have realized I could just install `@highlightjs/cdn-assets`! Works like a charm and is _exactly_ what we need.

**Comment by joshgoebel** [comment]
Awesome. Is there some particular place in the docs you think perhaps we could stick this info where you might have found it?

**Comment by theengineear** [comment]
I think I went astray when I read the section about `ES6 Modules / import`. Perhaps an additional note in there might help?

**Comment by joshgoebel** [comment]
Would you mind making a quick PR?
