### ISSUE TITLE
Some style sheets incorrectly delivered as `text/plain`

### ISSUE THREAD

**Issue by j9t** [highlightjs/highlight.js#3305]
At least one, maybe more of the highlight.js style sheets are delivered with the wrong MIME type (`text/plain` instead of `text/css`). Eventually this is a problem limited to unpkg.com.

Example: [solarized-light.min.css](https://unpkg.com/@highlightjs/cdn-assets@11.2.0/styles/solarized-light.min.css), as shown in this [test through Security Headers](https://securityheaders.com/?q=https%3A%2F%2Funpkg.com%2F%40highlightjs%2Fcdn-assets%4011.2.0%2Fstyles%2Fsolarized-light.min.css) (“Content-Type”).

For other style sheets, like atom-one-light.min.css, the MIME type is correct (see [the respective check](https://securityheaders.com/?q=https%3A%2F%2Funpkg.com%2F%40highlightjs%2Fcdn-assets%4011.2.0%2Fstyles%2Fatom-one-light.min.css)).

I’m not familiar with the highlight.js code base to tell where this is controlled, but maybe there’s a quick way of making sure all style sheets are delivered as `text/css`.

**Comment by joshgoebel** [comment]
You URL you provided is a 404 hence text not CSS. Some paths have changed with v11. Are you upgrading from 10?

**Comment by joshgoebel** [comment]
That theme is now in the base16 folder.

**Comment by j9t** [comment]
🤦‍♂️ Yikes. Testing different styles I must have missed that. Thanks. Yes, it seems to be all fine here.
