### ISSUE TITLE
[Request] Does it support typing effects?

### ISSUE THREAD

**Issue by auula** [highlightjs/highlight.js#3306]
I want to develop a code template with automatic typing effects,I used `type.js` to achieve but lost the highlighting, how can I solve it, I am a rookie programmer😭

**Comment by joshgoebel** [comment]
Sorry I do not understand what you are trying to ask.

**Comment by auula** [comment]
> Sorry I do not understand what you are trying to ask.

Sorry! I want the code block to have a dynamic effect of keyboard typing displayed, can this be supported?

**Comment by auula** [comment]
For example, the effect of this project.[https://github.com/mattboldt/typed.js/](https://github.com/mattboldt/typed.js/)

**Comment by joshgoebel** [comment]
We do not support this in the library, no.  Though we just generate raw HTML, perhaps you could use some library after we generate the HTML to then slowly display it however you wish?  If so then I imagine one could theoretically write a plugin that would do this also.

**Comment by auula** [comment]
> We do not support this in the library, no. Though we just generate raw HTML, perhaps you could use some library after we generate the HTML to then slowly display it however you wish? If so then I imagine one could theoretically write a plugin that would do this also.

thank you.
