### ISSUE TITLE
[Request] Please support vue syntax

### ISSUE THREAD

**Issue by jumodada** [highlightjs/highlight.js#3331]
```
highlightJs.configure({
  languages: ['js', 'html', 'vue'],
})
```

i can use it like this

*```vue*

*```*

**Comment by joshgoebel** [comment]
https://github.com/highlightjs/highlightjs-vue

Someone should make sure it's still compatible with v11 and if so we should add it to SUPPORTED_LANGUAGES, not sure why it's not on the list already.

**Comment by jumodada** [comment]
thanks
