### ISSUE TITLE
Undocumented css files moved

### ISSUE THREAD

**Issue by GrosSacASac** [highlightjs/highlight.js#3332]
**Describe the issue/behavior that seems buggy**

In the upgrade guide https://github.com/highlightjs/highlight.js/blob/main/VERSION_11_UPGRADE.md#styles-and-css

it is not mentioned that highlight.js/styles/solarized-dark.css was moved

**Comment by joshgoebel** [comment]
> All Base16 themes now live in the styles/base16 directory - this means some CSS files have moved. Please confirm themes you use reference the new locations.

**Comment by GrosSacASac** [comment]
My bad, but it might not be obvious to everyone what a base16 theme is
