### ISSUE TITLE
(go) built-in types need to be split out, `error` should be added

### ISSUE THREAD

**Issue by milutin** [highlightjs/highlight.js#3334]
**Describe the issue**
error is highlighted inconsistently

**Which language seems to have the issue?**
go

**Sample Code to Reproduce**
http://jsfiddle.net/2z05gxnk/

**Expected behavior**
 the error type should be highlighted consistently

**Additional context**
I am reporting this for user using code review Gerrit, that uses highlightjs. I am not familiar with go language.

**Comment by joshgoebel** [comment]
It would be helpful if someone from Go showed up and could help us divide our keyword list into built-in types and keywords... and perhaps it looks like we need to add `error`?

**Comment by bitfield** [comment]
Here's all the information you could ever want (and perhaps a little more): https://golang.org/ref/spec

**Comment by joshgoebel** [comment]
@bitfield Thanks, I skimmed very quickly.  Any chance you could take a quick look at #3335?  It looks like we have most of the types from my quick skimming.  I added error.

**Comment by bitfield** [comment]
Looks good from here! It's worth mentioning that types are just one subset of the [predeclared identifiers](https://golang.org/ref/spec#Predeclared_identifiers) in Go; the others are:

```
Constants:
	true false iota

Zero value:
	nil

Functions:
	append cap close complex copy delete imag len
	make new panic print println real recover
```

I don't know whether you need to do anything special to take account of these, or if they're already highlighted correctly.

**Comment by joshgoebel** [comment]
The first 4 are all scoped as `literal`. And those functions are scoped as `built_in`.
