### ISSUE TITLE
Selecting text in highlighted code blocks unexpectedly hides certain contents

### ISSUE THREAD

**Issue by ltrujello** [highlightjs/highlight.js#3338]
**Describe the issue/behavior that seems buggy**

By default, in the base-16 themes, highlighting text (in the click and drag sense) hides some of the code. The problem is caused by the  `.hljs ::selection` css rules in the files. It seems like they should be deleted. 

**Sample Code or Instructions to Reproduce**

Try highlighting the code in [this jsfiddle](https://jsfiddle.net/vw2dpxfc/), which loads Material Darker. 

Here's a screenshot for what it looks like for Material Darker.

![current](https://user-images.githubusercontent.com/40614638/134450276-5e74db03-2bae-473f-8c81-b5cb18a30637.png)

**Expected behavior**

Here is what I expected (I achieved this by removing the style rule in Material Darker)

![expected](https://user-images.githubusercontent.com/40614638/134450144-b8b441df-61fa-47c5-b367-e743b5517c5b.png)

Here is how highlighting code via mouse works on Github, for example.

![github_sample](https://user-images.githubusercontent.com/40614638/134450160-69c00ffe-4c10-4ac0-a8b6-c4cf9288d9c5.png)

Here is how it looks on other base 16 themes. This one is Black Metal Burzum. The second picture is what happened when I removed the css rule from the browser files.

![black_metal_burzum](https://user-images.githubusercontent.com/40614638/134450202-0b654ff6-8089-4acd-9bb4-56ec65af3a9c.png)
![black_metal_burzum_expected](https://user-images.githubusercontent.com/40614638/134450208-1c4e66b4-3b44-4ef4-9680-42268112dda9.png)

**Additional context**

This is a very good and widely used project, so perhaps this is on purpose and I hope I am not misunderstanding something. However, code tends to be highlighted/selected for the purpose of copying to the clipboard, so if you are user and are trying to select up to say a specific character of text, it becomes a poor user experience if some of if it randomly disappears/becomes hard to see.

**Comment by joshgoebel** [comment]
At first glance it looks like we should change this:

```
.hljs ::selection {} /* existing rule */
.hljs::selection {} /* add this rule */
```

The problem now is only the children get the rule applied not content from the code block itself that has no other highlighting applied.  Can you confirm?

**Comment by ltrujello** [comment]
Do you mean for example changing 
```
.hljs ::selection {
  color: #353535;
}
```
to 
```
.hljs::selection {
  color: #353535;
}
```
If so, it seems that change would still have the problem, this time only it hides non syntax-highlighted text, which actually hides more content. Here is what it looks like on my end for example:

![suggested_change](https://user-images.githubusercontent.com/40614638/134594530-1bb73b49-f421-443c-83a5-3a2c84ce17ab.png)

I think it makes sense to just delete the `::selection` rule, if possible.

**Comment by joshgoebel** [comment]
> Do you mean for example changing ... to ...

No, BOTH rules are necessary and in my tested it looked great.

**Comment by joshgoebel** [comment]
@highlightjs/core  Any philosophical thoughts on whether a theme should be able to change selection color - as a matter of policy?  If we wanted to be picky we could decide this "hurts usability" or violates the users choice in some way and just disallow it... but I think technically this can be fixed as I already mention above.

**Comment by ltrujello** [comment]
Nothing changes on my end when I add them both, and I think that's because adding both rules is actually just what was originally the problem: only the syntax highlighted content gets the rule, not the content which has no highlighting, and because the `::selected` color is very similar to the color of the background, it hides the syntax-highlighted content.

If possible, this rule should just be taken out. The default blue colors that browsers provide are perfectly fine and are what users naturally expect. Additionally, when one is selecting code via click and drag, they are probably focused and in the middle of a more important task, hence they don't need to be distracted by a random color or inconvenienced by text disappearing for a task that should be really short and simple. That's probably why most websites with syntax-highlighted code, like Github or StackOverflow, don't have any interruption or fancy coloring in the selection highlighting.

**Comment by joshgoebel** [comment]
> Nothing changes on my end when I add them both

https://jsfiddle.net/pz2wkuya/

Working properly with both Safari and Chrome here.  You can disagree with the visual merits, but I'm more concerned with the technical problem you first raised, which seems solvable.  Now, it's worth asking if the *intention* of `::selected` is to use the `background-color`, rather than `color`... and if so, then that's a mistake on my part I think - and something we should indeed fix (which might address some of your concerns).  But these are themes - a great many of them are already a matter of personal taste, and "selection color" is an official part of the Base16 spec.  _If you don't like it, then don't use a base16 theme, or modify the CSS to remove `::selection`._  

So:

- We'll fix the CSS bug.
- We'll see if the actual intention was `background-color` (vs color), which seems obvious now in hindsight.

We'll change those two things and think that will improve the situation greatly and get us back to what the them authors originally intended.

**Comment by ltrujello** [comment]
The linked fiddled works and looks great! It has different CSS syntax than what one would get by just applying your initial suggestion, hence why I did not see a difference (i.e.., Material Darker's `::selection` does not have a `background-color` value and the `color` value is not `inherent`). This works great for me though.

**Comment by joshgoebel** [comment]
@ltrujello You want to poke around in the `base16-highlightjs` repo and see if that looks good to you?  If things are all good now we'll copy these newer versions over for the next release.

**Comment by ltrujello** [comment]
Yes these look great! Personally I stuck with `color: inherit` suggestion instead of a fixed color, so the text selection preserves the syntax highlighting, but that is just a matter of preference. Thanks for the help!

**Comment by joshgoebel** [comment]
934f2e78 Should land in 11.3
