### ISSUE TITLE
(Java) Java 17 sealed keywords not implemented

### ISSUE THREAD

**Issue by thiccaxe** [highlightjs/highlight.js#3346]
With the release of Java 17 being an **LTS**, it seems proper to support the new `sealed` keyword.
However, the new `non-sealed` keyword brings some issues, that [while I have attempted to fix](https://github.com/thiccaxe/highlight.js/commit/e285198f222a48a363338b54e3c077b6a18db18d), seem best suited for someone more familiar with the highlightjs library.

**Sample Code or Instructions to Reproduce**
[sample js fiddle](https://jsfiddle.net/Lv2hmbpt/2/)

**Expected behavior**
the `sealed` keyword should be highlighted, and as more hyphenated keywords may come to java in the future, some structure
 may be useful for `non-sealed` and the like.

**Comment by joshgoebel** [comment]
I think what you have already can be converted into a workable PR.

**Comment by joshgoebel** [comment]
Ping.

**Comment by joshgoebel** [comment]
Ping.
