### ISSUE TITLE
[Request] Make your website readable

### ISSUE THREAD

**Issue by tem-tem** [highlightjs/highlight.js#3359]
**Is your request related to a specific problem you're having?**
my eyes hurt reading your site

**The solution you'd prefer / feature you'd like to see added...**
just change the background color jesus christ

**Any alternative solutions you considered...**
this repo

**Additional context...**
not needed

**Comment by joshgoebel** [comment]
This is quite rude.

---

It's our branding, sorry you don't like it.  I just checked and it's quite accessible.

<img width="260" alt="Screen Shot 2021-10-17 at 9 20 42 AM" src="https://user-images.githubusercontent.com/6473/137628876-8f897c72-0b78-48fc-80e0-67ea3a90eee5.png">
