### ISSUE TITLE
(CSS) hex alpha color

### ISSUE THREAD

**Issue by ierehon1905** [highlightjs/highlight.js#3360]
https://github.com/highlightjs/highlight.js/blob/7cb4e3d14a4ce579dc093836d9b29ee165b1553c/src/languages/lib/css-shared.js#L10

Hello, thank you for your hard work. I noticed some issues with highlighting in css colors, specifically in those with alpha channel. According to MDN hex representation [both short and long have optional alpha channel](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value#rgb_colors).

This breaks the highlighting giving the last symbols another color

**Comment by taufik-nurrohman** [comment]
@ierehon1905

~~~ .js
'#([0-9a-fA-F]{1,2}){3,4}'
~~~

**Comment by ierehon1905** [comment]
> ```js
> #([0-9a-fA-F]{1,2}){3,4}
> ```

It seems like `#f1f1f10` passes too, but it is not a valid color.

**Comment by ierehon1905** [comment]
I have come up with a less pretty pattern.
```regex
#(([0-9a-fA-F]{3,4})|(([0-9a-fA-F]{2}){3,4}))\b
```
[regex 101 link](https://regex101.com/r/Oqbaye/1)

<img width="493" alt="image" src="https://user-images.githubusercontent.com/31146334/137586003-442fa174-95ee-44ba-8bdc-21865cb8bc00.png">

**Comment by ierehon1905** [comment]
Created a pull request https://github.com/highlightjs/highlight.js/pull/3362
