### ISSUE TITLE
The download version is not the latest

### ISSUE THREAD

**Issue by Vanessa219** [highlightjs/highlight.js#3364]
**Describe the issue/behavior that seems buggy**

Click the download button from https://highlightjs.org/download/, the version is 11.0.1.

**Expected behavior**

Click the download button from https://highlightjs.org/download/, the version is the latest.

**Comment by joshgoebel** [comment]
@isagalaev I think this might have to do with us using stable-11 as the branch on CDN now instead of main?

**Comment by Vanessa219** [comment]
It has been fixed, thanks!
