### ISSUE TITLE
Fiddles in the docs are outdated

### ISSUE THREAD

**Issue by wjandrea** [highlightjs/highlight.js#3379]
In [`CONTRIBUTING.md`](https://github.com/highlightjs/highlight.js/blob/main/CONTRIBUTING.md#reporting-issues), the [fiddle](https://jsfiddle.net/ajoshguy/2bmdswn6/) uses HLJS 10.7.3, which is older.

In [`.github/ISSUE_TEMPLATE/1_incorrect-syntax-highlighting.md`](https://github.com/highlightjs/highlight.js/blob/main/.github/ISSUE_TEMPLATE/1_incorrect-syntax-highlighting.md?plain=1), the [fiddle link](https://jsfiddle.net/ajoshguy/gfzujpyt/) is dead.

Here's [a new fiddle using 11.3.1](https://jsfiddle.net/8juy7c5t/) that you can fork and insert into those if you want. I would do a PR, but the existing fiddle in `CONTRIBUTING.md` is owned by you, and I assume that's by design.

**Additional context**
This was confusing to me because I assumed the fiddle had the latest version, and so I thought #3378 was an issue with Stack Exchange so [reported the problem to them first](https://meta.stackoverflow.com/questions/412707/wrong-syntax-highlighting-halfway-through-a-python-identifier) before someone pointed out the version.

**Comment by joshgoebel** [comment]
Thanks, I should have an updated Fiddle somewhere... I'll see about getting this fixed.

**Comment by joshgoebel** [comment]
c100a39f
