### ISSUE TITLE
[Request] Module exports for CDN-hosted libraries

### ISSUE THREAD

**Issue by VictorWesterlund** [highlightjs/highlight.js#3383]
**Is your request related to a specific problem you're having?**
The [CDN-hosted libraries](https://highlightjs.org/usage/#importing-the-library) does not provide ECMAScript 6 module exports even thought they are included in the source here on GH. Possibly for compatibility- or some other logical reason, I can't say for sure without delving deeper into the code.

```js
import hljs from "https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.3.1/highlight.min.js";
```
*Will throw a `SyntaxError` due to a missing `export` on the requested resource.*

**The solution you'd prefer / feature you'd like to see added...**
CDN-hosted ECMAScript 6 modules. 
The actual implementation/CDN-provider doesn't really matter as long as it's `import`able.

**Any alternative solutions you considered...**
GH Pages provides its own CDN and could be set up to serve JS files directly from this repo.
[Some restrictions apply](https://docs.github.com/en/pages/getting-started-with-github-pages/about-github-pages#usage-limits) but requires relatively low maintenance and initial effort. For small-scale, not-at-all business critical projects it's more than acceptable that the file isn't pre-processed (minified etc.).

```js
import hljs from "https://highlightjs.github.io/highlight.js/src/highlight.js";
```
*A dyslectic nightmare to look at, but it would get the job done*

**Additional context...**
N/A

**Comment by zarianec** [comment]
Hey @VictorWesterlund! The CDN-prebuilt library already includes bundled ESM version and it could be used over the CDN if it supports proxying files on GitHub.

This is the ESM example from the docs used with a [jsDelivr hosted library](https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@11.3.1/build/es/):

```javascript
import hljs from 'https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@11.3.1/build/es/core.js';
import javascript from 'https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@11.3.1/build/es/languages/javascript.min.js';
hljs.registerLanguage('javascript', javascript);
```

jsDelivr doesn't have the limitations you mentioned for GitHub Pages and it can minify any js/css files on the fly.

**Comment by VictorWesterlund** [comment]
Ah look at that, thanks a lot.

I guess the `/usage/` doc could make a quick mention that modules can be imported in this way.

**Comment by joshgoebel** [comment]
ES6 is already mentioned under usage... perhaps (since we ship ES6 specific modules now) those paths mentioned under **ES6 Modules / import** should simply be changed to reference the new `es` folders?

**Comment by joshgoebel** [comment]
I suppose I'd also be open to a PR adding ES6 examples to the CDN section for every CDN... since we already write out full examples for CJS CDN usage for each CDN endpoint.

**Comment by VictorWesterlund** [comment]
> ES6 is already mentioned under usage... perhaps (since we ship ES6 specific modules now - and didn't in the past) those paths mentioned under ES6 Modules / import should simply be changed to reference the new es folders?

The "ES6 Module / import" section is only mentioning imports from self-hosted modules (relative path) at the moment. 

It's not immediately obvious that their CDN counterparts can be imported this way too. Especially not when the relative paths aren't "hot swappable" with the CDN URLs (but require the `es` folder).

---

> I suppose I'd also be open to a PR adding ES6 examples to the CDN section for every CDN... since we already write out full examples for CJS CDN usage for each CDN endpoint.

I second this. And/or add an example/text note under "ES6 Module / import" as well.
