### ISSUE TITLE
exports in package.json break dynamic imports with webpack

### ISSUE THREAD

**Issue by azul** [highlightjs/highlight.js#3384]
**Describe the issue/behavior that seems buggy**

Webpack currently does not understand wildcard exports when processing dynamic imports.
This is a [bug in webpack](https://github.com/webpack/webpack/issues/13865).

Trying to build a package that uses dynamic imports from `highlights.js` from version 11 on will result in
```
Module not found: Error: Package path ./lib/languages is not exported from package <path_to_proj>/node_modules/highlight.js (see exports field in <path_to_proj>/node_modules/highlight.js/package.json)
```

**Sample Code or Instructions to Reproduce**

This was already reported [here](https://github.com/highlightjs/highlight.js/issues/3223#issuecomment-886143417) but i think it's unrelated to the bug report it was submitted to.

Attempting to build this code with webpack will result in the error emssage mentioned above:
```
await import(
  /*
   webpackInclude: /(java|javascript|latex|markdown|python|ruby|typescript|xml|yaml)/,
   webpackChunkName: "lang-[request]"
   */
   `highlight.js/lib/languages/${lang}.js`
)
```

**Expected behavior**
The build should succeed providing the languages as separate artifacts to be dynamically imported.

**Additional context**

It looks like webpack currently does not implement handling the combination of exports specified in `package.json` and dynamic imports at all. So it might take some time until this is fixed on the webpack side of things. That's why i am proposing to look into a workaround in `highlight.js` as dynamic imports seem very relevant given the large number of language files.

**Comment by joshgoebel** [comment]
@azul What about your own easy workaround you posted in the other thread?  Did you find an issue with it?  I would have expected to have seen it attached to this issue if it's a work-around.

**Comment by joshgoebel** [comment]
What are all other Webpack uses doing?  We have been using `exports` since v11, seems hard to believe no one has successfully upgrade until now?  As a work-around (if there are no others) I would suggest using a pre-built version of Highlight.js and just throwing that into the build system whole rather than trying to let webpack understand the entire structure of the library of 250 independent files.

Of course as mentioned this is truly a Webpack bug and needs to just be fixed on that side.

**Comment by joshgoebel** [comment]
Ping.

**Comment by azul** [comment]
Thanks for the reminder.
I found a workaround for the builds by using relative paths in the import statement: https://github.com/nextcloud/text/pull/1942#pullrequestreview-801973544.
It's ugly but it did the trick.

There are other dependency issues between version 11 of highlight js and tiptap1 that mean we need to stick to version 10 until we managed to migrate to tiptap 2. But that's unrelated so i'll close this issue.

**Comment by Hypnosphi** [comment]
@azul unfortunately this doesn't work for libraries, because npm can flatten packages:
```
App
  node_modules
    library
      node_modules
        // no highlight.js here
    highlight.js
```

**Comment by Hypnosphi** [comment]
> We have been using exports since v11, seems hard to believe no one has successfully upgrade until now? 

I can't upgrade because I use dynamic imports

**Comment by Hypnosphi** [comment]
@joshgoebel no, but they weren't asking how people deal with it
