### ISSUE TITLE
Add a latest release as a "classic" webjar to Maven

### ISSUE THREAD

**Issue by bsanchezb** [highlightjs/highlight.js#3388]
Hello,

Is it possible to add the latest release as a classic "webjar" to maven https://mvnrepository.com/artifact/org.webjars/highlightjs ?
The latest available release is 10.1.2 which is a bit outdated and has some reported vulnerabilities (e.g. [ReDoS attack](https://snyk.io/vuln/SNYK-JAVA-ORGWEBJARSNPM-1048677)).
Unfortunately we do not use preprocessors in our project and we are not able to build an npm version, aslo available on maven. Of course, we could use js/css files extracted from the repository directly, but it is not as comfortable as to use a Maven dependency.

Thank you for your work!

Best regards,
Aleksandr.

**Comment by joshgoebel** [comment]
I see there is already https://mvnrepository.com/artifact/org.webjars.npm/highlight.js

Though perhaps this is what you refer to when you say:

>  are not able to build an npm version

_There is NO build step for our npm release - it's flat files._ (intended for use by a backend such as Node, Deno, etc)  Obviously you'd have to download and extract the npm, but there is no "build" step.  We also publish a CDN release of our "web ready" assets that is available via 3 different CDNs (see our README) and can be fetched via Git as well via the [cdn-release](https://github.com/highlightjs/cdn-release) repository.

> we could use js/css files extracted from the repository directly,

Without knowing anything about Maven or the ecosystem (and how it interfaces with JS) this is exactly what I'd likely suggest - either extracting files from our NPM package (tagged via npm versioning) or our con-release package, tagged with Git tags.  


The core team provides what we consider essential for the JS ecosystem:

- a NPM release (both ESM and CJS libs)
- a web/CDN release (both ESM and CJS libs)

The core team has no time to create/package/maintain additional releases for other ecosystems at this time.  If someone has a question about how to build the library (that isn't covered by our docs) I'm happy to answer if I know.

_Perhaps you'd be willing to step up and package and maintain a Highlight.js Maven "webjar" yourself for your and your communities usage?_ 🙂

**Comment by bsanchezb** [comment]
Hello,

Thank you for your quick reply. Firstly I was thinking that is you who make the maven releases, but now I see that I was mistaken.
By the way, I have found a repository responsible for the "classic" packaging : https://github.com/webjars/highlightjs . I contacted him.

Thank you!

Best regards,
Aleksandr.
