### ISSUE TITLE
Issue: <br> tags no longer work. 

### ISSUE THREAD

**Issue by djpic** [highlightjs/highlight.js#3398]
**Is your request related to a specific problem you're having?**
I was using version 10.2.0 and now when trying to jump to the latest version, my &lt;br&#62; tags no longer work.  I use this to keep my code clean.

**The solution you'd prefer / feature you'd like to see added...**
I have read that not allowing html tags is a security problem, but having an option to 'whitelist' tags would very helpful.   By default, tags can be removed, but having the ability to add a "whitelist" in the configuration options would be awesome.

**Any alternative solutions you considered...**
I have tried to use all variations of the white-space CSS property.  An option that I want doesn't exist.  I need an option that will no wrap text except line breaks and collapse sequences of whitespace.

**Additional context...**

**Comment by joshgoebel** [comment]
>  I use this to keep my code clean.

Not sure what this means at all?

> ... but having the ability to add a "whitelist" in the configuration options would be awesome.

This ship has sailed, but anyone is welcome to add this feature via a 3rd party plugin... https://highlightjs.readthedocs.io/en/latest/plugin-api.html

> I have tried to use all variations of the white-space CSS property.

Please show us a JS Fiddle of the HTML/CSS your'e using that is not working...  seems to work fine to me with just `white-space: pre` as mentioned in docs.

![Screen Shot 2021-11-09 at 10 03 25 PM](https://user-images.githubusercontent.com/6473/141042029-832328c1-baa8-4568-b285-aed0caaf68a4.png)

**Comment by djpic** [comment]
Here is a JS Fiddle example.  Of course you may need to adjust the screen resolution to make the text wrap or not wrap.

https://jsfiddle.net/jorykwhs/14/

**Comment by joshgoebel** [comment]
![Screen Shot 2021-11-10 at 9 15 13 AM](https://user-images.githubusercontent.com/6473/141129135-eca3b57a-0b14-441f-9afc-f191de5d981e.png)

In your last example the line breaks are handled properly and rendered in HTML exactly as they are in the source (the behavior `pre` provides by default).  Where you would normally use a `<br>`, use a real line break instead.  IE, if you just include normal source code (with normal line breaks) as-is, it "just works".

If you are wanting something else I'm sorry but I'm failing to understand what you are wanting.

**Comment by djpic** [comment]
It is the auto wrapping of text.  There is no option that does not auto-wrap text but honors line breaks. The only way to not auto wrap text also ignores the line breaks and <br> Is the only way to carry to a new line in that scenario.  But highlight.js causes the <br> not to work.

**Comment by joshgoebel** [comment]
The last example is not auto-wrapped at all.

**Comment by joshgoebel** [comment]
The whole point of `<pre>` (and `white-space:pre`) is to leave your text alone and render it exactly as you've written it in the HTML source.  That is what I see happening here.

**Comment by djpic** [comment]
I will check again when I am in front of a computer.  Right now you are correct, the bottom one is working how I would like.

**Comment by djpic** [comment]
Yes, correct.  The bottom one is working how I would like with the exception of not ignoring the whitespace.  The code doesn't go with the layout which is why I want to ignore the sequenced whitespace.  For example, the source code looks like this:

`        <code style="white-space: pre">
I hope this makes sense as it seems every possible senario/combination is accounted for in the white-space property, except the one for no wrap and honor line-breaks.
          
Ignoring the sequences of whitespace is the key to making the code look good in the background, otherwise the code will look like this, and this is ugly!
        </code>`

Instead, to keep with he formatting of the source code, it would need to look like this:

`        <code style="white-space: pre">
            I hope this makes sense as it seems every possible senario/combination is accounted for in the white-space property,
            except the one for no wrap and honor line-breaks.
          
            Ignoring the sequences of whitespace is the key to making the code look good in the background, otherwise the code                 
            will look like this, and this is ugly!
        </code>`


It is much cleaner to read the code in the second example when you are looking at the source code vs in the first example.   But with the "pre" whitespace, this will display all those extra formatting spaces.

Do you follow me?  Also, I do appreciate the support.  Maybe I am thinking of all this wrong, but I tend to be pretty detail oriented.  If there is a better way to use pre and keep your backend source code looking good, please let me know.

**Comment by joshgoebel** [comment]
> Instead, to keep with he formatting of the source code

I'd forget about that.  You're fighting against `pre` (whose sole job is to precisely preserve whitespace), and that's just asking for pain.  Personally I would just give up on this desire (for your code blocks) and call it a day.   

If you really want embedded HTML you'll need to write a plugin for that.

---

One alternative idea might be to pre-process - count the amount of whitespace before every line, find the minimum amount, and then trim that from the start of every line.  That would give you "free indents"... you could do that either in a plugin or with your own JS perhaps.
