### ISSUE TITLE
(js) Async arrow function should be highlighted as function

### ISSUE THREAD

**Issue by jebarjonet** [highlightjs/highlight.js#3405]
**Describe the issue**
Async arrow function should be highlighted as function, instead it is not highlighted at all. This is the most used shape for functions in modern Javascript syntax (instead of `function name() {}`)

**Which language seems to have the issue?**
js / ts

**Are you using `highlight` or `highlightAuto`?**
`highlight` specifically asking for `javascript` language

**Sample Code to Reproduce**

In the examples below, `init` is a function name. The function is declared as arrow function in Javascript.

**✅  Example without `async` (works well) :**

```ts
const init = () => {
  // something
}
```

<img width="208" alt="Screen Shot 2021-11-21 at 22 31 56" src="https://user-images.githubusercontent.com/4401230/142779828-f7cdb0d2-acd7-422d-a382-014ff5ba8994.png">
<img width="308" alt="Screen Shot 2021-11-21 at 22 31 56" src="https://user-images.githubusercontent.com/4401230/142779830-d681f1e5-fbb8-48cc-9fdf-ee649f44018a.png">

**❌ Example with `async` (does not recognize function name) :** 

```ts
const init = async () => {
  // something
}
```

<img width="234" alt="Screen Shot 2021-11-21 at 22 32 35" src="https://user-images.githubusercontent.com/4401230/142779844-2f0a40d4-cd48-41b0-bacc-42c753539b67.png">
<img width="292" alt="Screen Shot 2021-11-21 at 22 32 30" src="https://user-images.githubusercontent.com/4401230/142779846-01a6079a-386e-444d-bbd0-5683dee55d60.png">

**Expected behavior**
The presence or absence of `async` should not change function identification. In the example above, `init` should be colored blue in both cases.

**Comment by joshgoebel** [comment]
Please provide **textual** examples that can be easily but and paste.

**Comment by jebarjonet** [comment]
@joshgoebel done ✅

**Comment by joshgoebel** [comment]
Can async we used with the old syntax at all?

**Comment by jebarjonet** [comment]
Sure, like so : 

```ts
// not async
function myFunction() {
  // ...
}

// async
async function myFunction() {
  // ...
}
```

Thank you very much for your reactivity ! 🥇

**Comment by joshgoebel** [comment]
Which we already support because it's just a keyword there that needs no special coding.
