### ISSUE TITLE
(json) JSON snippet detected as CSS

### ISSUE THREAD

**Issue by ushkal** [highlightjs/highlight.js#3406]
**Describe the issue**
`JSON` code is detected as `CSS`.

**Which language seems to have the issue?**
`JSON`

**Are you using `highlight` or `highlightAuto`?**
`hihjlightAuto`
...

**Sample Code to Reproduce**

JSFiddle: https://jsfiddle.net/zf72nht1/

A sample is
```
{
    "agent" : "Fivetran Google Cloud Functions Connector/<external_id>/<schema>",
    "state": {
        "cursor": "2020-01-01T00:00:00Z"
    },
    "secrets": {
        "apiToken": "fake_api_token"
    }
}
```

**Expected behavior**

It should be detected as JSON

**Additional context**

We are using v11.2 and in this case the detected language is Smalltalk. But the issue is reproducing in the latest version

**Comment by joshgoebel** [comment]
The relevance scoring here is close (8 vs 9, JSON vs CSS)... Sadly, auto-detect is "best effort" and not perfect. #1213  Cases like this are expected and not considered a bug.  To always get 100% correct highlighting you need to manually specify the grammar.
