### ISSUE TITLE
(PowerShell) Specific elements not being identified for highlighting

### ISSUE THREAD

**Issue by Ayanmullick** [highlightjs/highlight.js#3418]
**Describe the issue**

Syntax highlighting isn’t working for some elements of PowerShell. I think the PowerShell language grammar to identify certain elements needs to be updated.

![image](https://user-images.githubusercontent.com/17693249/144551035-3f57725b-0417-4105-b74d-47abde6a0fd5.png)

1.	The entire line after a `#` sign is commented even if there no space after `#`
2.	The Noun part of the cmdlet isn’t highlighted
3.	The parameter name isn’t highlighted
4.	PowerShell parameter arguments don’t need to be in quotes unless there is a space in between

**Are you using `highlight` or `highlightAuto`?  `highlight`

...

**Sample Code to Reproduce**

```html
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@11.3.1/build/styles/atom-one-dark.min.css">
<script src="https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@11.3.1/build/highlight.min.js"></script>
<script>hljs.highlightAll();</script>

<pre><code class="pwsh">
    #Locate SQL image
    Get-AzVMImagePublisher -Location 'southcentralus'|? PublisherName -Like *sql*
    Get-AzVMImageOffer -Location southcentralus -PublisherName MicrosoftSQLServer
</code></pre>   
```

CodePen link to reproduce issue: https://codepen.io/ayanmullick/pen/YzrPobY

**Expected behavior**

**Screenshot**: 
<img width="678" alt="image" src="https://user-images.githubusercontent.com/17693249/144552256-3c0e2a22-ce63-4af7-ae2b-a97f0307ec01.png">

**Library**: This screenshot is from PowerShell ISE. One could export the theme XML from `Tools`-`Options`-`Manage themes`-`Export`
One gets similar highlighting experience on Discord too.

**Additional context** : NA

**Comment by joshgoebel** [comment]
Powershell is not included in the default build - so highlighting is going to be entirely random (whatever is auto-detected).  Please load the JS module for powershell first and if you still see issues this can be reopened.

**Comment by Ayanmullick** [comment]
Thanks for pointing out, @joshgoebel. I loaded powershell.min.js. However, these tree issues are still there.

![image](https://user-images.githubusercontent.com/17693249/144555629-a902c677-524f-47eb-81f4-78e049b6f9e5.png)

1. PowerShell parameter values don’t need to be in quotes unless there is a space in between
2. `?` is an Alias for `Where-Object` and should have the same highlighting as the cmdlet.
3. The operator and the argument should have different highlighting

<details>

<summary>Updated code </summary>

```html
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@11.3.1/build/styles/atom-one-dark.min.css">
<script src="https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@11.3.1/build/highlight.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.3.1/languages/powershell.min.js"></script>
<script>hljs.highlightAll();</script>

<pre><code class="pwsh">
    #Locate SQL image
    Get-AzVMImagePublisher -Location 'southcentralus'|? PublisherName -Like *sql*
    Get-AzVMImageOffer -Location southcentralus -PublisherName MicrosoftSQLServer
 </code></pre> 
```

</details>

**CodePen link**: https://codepen.io/ayanmullick/pen/YzrPobY

**Comment by joshgoebel** [comment]
1. Yet if unquoted they are not a _quoted_ string, and hence unhighlighted.  The highlighting is based on the quotes, not the context, which we cannot fully understand.
2. I'm not sure this 100% follows, but possibly. I'm trying to think of an equivalent from other grammars.  Is the `?` only valid after a pipe?
3. `-Like` is correctly scooped as `operator`, but not all themes support this.  Use a different theme or modify your CSS/theme to add support.

**Comment by Ayanmullick** [comment]
1. PowerShell does not need a quoted string to pass as a parameter value. Could highlight.js use the grammar exported from PowerShell ISE to fully understand the context?
2. `?` Is an [alias](https://ilovepowershell.com/2011/11/03/list-of-top-powershell-alias/) for Where-Object. Yes, it's [mostly used after a `|`.](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/where-object?view=powershell-7.2#examples) 
3. Yes, the **default** theme is highlighting the operator and value differently. Should one look for the repository of a specific theme to submit feedback?
<details>

<summary>Updated code </summary>

```html
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@11.3.1/build/styles/default.min.css">
<script src="https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@11.3.1/build/highlight.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.3.1/languages/powershell.min.js"></script>
<script>hljs.highlightAll();</script>

<pre><code class="pwsh">
    #Locate SQL image
    Get-AzVMImagePublisher -Location 'southcentralus'|? PublisherName -Like *sql*
    Get-AzVMImageOffer -Location southcentralus -PublisherName MicrosoftSQLServer
 </code></pre>   
```

</details>

<details>

<summary>Screenshot </summary>

![image](https://user-images.githubusercontent.com/17693249/144670491-cd8eb15b-1d7a-4ae8-a276-5a7b876cfea2.png)


</details>

**Comment by joshgoebel** [comment]
> Could highlight.js use the grammar exported from PowerShell ISE to fully understand the context?

Doubtful, we use our own grammar language (see the docs) to describe grammars, and we [often] aren't interested in contextual highlighting because it's [quite often] an impossible (or very hard) problem to solve without a full parser (which is not what our engine is designed to do).

I've tried to encourage several people to work on a plugin that would allow us to piggy back/integrate [Code Mirror 6 grammars](https://lezer.codemirror.net) - which are much, much more fully featured.  But no one has taken me up on it yet, and it would probably involve writing a CodeMirror 6 Lezer grammar from scratch as well.  I have little interest in the Code Mirror 5 stuff (which is where most of the supported languages still are).

>  Just remembered, it's recommended to avoid aliases for purposes of syntax highlighting.

And probably readability in general... :-)

> Should one look for the repository of a specific theme to submit feedback?

For our Base16 themes, yes.  But base16 don't believe in highlighting operators it seems - so that's an uphill battle.

```
base05  #{{base05-hex}}  Default Foreground, Caret, Delimiters, Operators
```

...for 1st party themes (if you have a good eye) you could open a PR, but I'm not going to allow "please add operators to this theme" style issues... I'd close them as dups of #2500.  This lack of support affects many themes and is a known problem.

Or we could debate whether these are operators at all... but I tend to go into such discussions based on semantics - not the desired highlighting result... so we choose what's best semantically - even if the highlighting is poor.  Those who want the VERY best highlighting should use a custom theme for whichever languages they plan to highlight most since there is no much variation among languages.

**Comment by Ayanmullick** [comment]
Thanks for the detailed explanation, @joshgoebel .

> What does Microsoft themselves call -Like (and friends) grammatically?

`-Like` is a comparison operator
https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_operators?view=powershell-7.2#comparison-operators

**Comment by joshgoebel** [comment]
> -Like is a comparison operator

Then I'd say `operator` is correct and we just need to wait for themes to catch up - and those who truly care right now need to tweak their own CSS to better support operators.  I'd also say base16 themes may not be best-suited to grammars that use "keyword like" operators, like Powershell.

**Comment by Ayanmullick** [comment]
Operator highlighting is working fine with the `atom-one-dark-reasonable` theme. :smile:
