### ISSUE TITLE
Repetivie script HTTP loading and browser crash with worker system

### ISSUE THREAD

**Issue by soullivaneuh** [highlightjs/highlight.js#3421]
**Describe the issue/behavior that seems buggy**

Following your advices on #954, I use the worker system to load the highlight.js process in background and avoid browser freeze on huge piece of codes.

This works great. However, I recently discovered this loads the worker source code and the minified library logic **at each parsed code block**:

![image](https://user-images.githubusercontent.com/1698357/144874137-c82bf688-ea81-4c0c-a941-c97b264393b1.png)

On a page with a hundred of code block, you will have a `STATUS_BREAKPOINT` on Chrome. Firefox works but with a lot a difficulties.

**Sample Code or Instructions to Reproduce**

The highlight.js init script:

```javascript
class HighlightJs {
  static render($element) {
    const worker = new Worker(
      document.body.dataset.highlightJsWorkerPath,
    );

    worker.onmessage = (event) => {
      $element.html(event.data);
    };

    worker.postMessage({
      // We have to give the script path here because the worker does not have access to the DOM.
      script: document.body.dataset.highlightJsPath,
      content: $element.text(),
    });
  }
}

(function init($) {
  $('.hljs').each((index, element) => {
    HighlightJs.render($(element));
  });
  $(document).arrive('.hljs', (element) => {
    HighlightJs.render($(element));
  });
}(jQuery));
```

The worker script:

```javascript
var onmessage = function(event) {
    importScripts(event.data.script);
    var result = self.hljs.highlightAuto(event.data.content);
    postMessage(result.value);
};
```

**Expected behavior**

The HTTP javascript loading code should be done only once.

**Additional context**

According to our analysis, this looks to be caused by the `importScripts` function called on the worker, loading the full compacted library.

If we remove it and return a fake text content on `postMessage`, we don't have any performance issue anymore.

We may (surely?) wrongly did the setup. However, we didn't find any other manner to implement the worker with multiple code blocks, and your documentation does not give any working sample for that kind of case.

Currently using v9.16.2.

**Comment by joshgoebel** [comment]
> The HTTP javascript loading code should be done only once.

You're the one calling `importScripts` over and over for each request...  I would suggest only calling `importScripts` a single time (the first time) or adding the highlight.js source code to your original worker download to begin with (avoiding the need to import anything at all).

>  Currently using v9.16.2.

Very old and with very serious security issues.  Please upgrade to v11.

https://github.com/highlightjs/highlight.js/security/advisories?state=published

**Comment by joshgoebel** [comment]
Closing as asked and answered.
