### ISSUE TITLE
wrong usage instructions

### ISSUE THREAD

**Issue by digininja** [highlightjs/highlight.js#3424]
**Describe the issue/behavior that seems buggy**

Your usage instructions here - https://highlightjs.org/usage/ - contain this line:

```
<link rel="stylesheet" href="/path/to/styles/default.css">
```

But you don't include a default.css, it is `default.min.css`.

The reference is correct on the download page - https://highlightjs.org/download/

**Comment by joshgoebel** [comment]
I don't think the intention was the example was meant to be taken 100% literally, but I've changed this with 0bf3ade.
