### ISSUE TITLE
Unexpected token 'export' when used in NextJs

### ISSUE THREAD

**Issue by azharzaman1** [highlightjs/highlight.js#3435]
When I import Themes inside NextJs application from themes directory('react-syntax-highlighter/dist/cjs/styles/hljs') as:

```
import { atomOneDark, atomOneLight } from "react-syntax-highlighter/dist/cjs/styles/hljs";
```

It throws a syntax ERROR as 
```
Unexpected token 'export'
```

I looked for some solution from Internet, at tried dynamic import as:
```
import dynamic from 'next/dynamic'

const { atomOneDark, atomOneLight } = dynamic(
  () => import('react-syntax-highlighter/dist/cjs/styles/hljs'),
  { ssr: false }
)
```
And,
```
import dynamic from 'next/dynamic'

const atomOneDark = dynamic(
  () => import('react-syntax-highlighter/dist/cjs/styles/hljs/atom-one-dark'),
  { ssr: false }
)
```

Still not solved.
Then I tried to simpley import individual theme directly from theme file, fortunately it works for me;
```
import atomOneDark from "react-syntax-highlighter/dist/cjs/styles/hljs/atom-one-dark";
import atomOneLight from "react-syntax-highlighter/dist/cjs/styles/hljs/atom-one-light";
```
Please have a look at it.

**Comment by joshgoebel** [comment]
Please raise this issue against `react-syntax-highlighter`, that's not our package.

**Comment by azharzaman1** [comment]
Okay, my bad. Thanks Sent from Mail for Windows From: Josh GoebelSent: 26 December 2021 16:08To: highlightjs/highlight.jsCc: Azhar Zaman; AuthorSubject: Re: [highlightjs/highlight.js] Unexpected token 'export' when used in NextJs (Issue #3435) Please raise this issue against react-syntax-highlighter, that's not our package.—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***>
