### ISSUE TITLE
html elements within code pre area are removed, possible to ignore them ?

### ISSUE THREAD

**Issue by Daedra22** [highlightjs/highlight.js#3439]
Hi guys, I am trying to use input fields within a pre code area when highlighting it with highlight.js, but the highlighter seems to remove them
Is there a solution to make highlight.js ignore <input/> fields within pre code ?
So that it looks like this?

![grafik](https://user-images.githubusercontent.com/1364346/147664470-fecac291-084e-4521-a917-14a9abbde983.png)

**Comment by joshgoebel** [comment]
No, we do not allow this.  99% of the time this is NOT what people want and it opens people up to security issues (via code injection attacks).  The content inside `<pre><code>` should be ONLY text (in our humble opinion)... so we strip any HTML and throw a warning to the console.  In the next version this may even be a hard error that will break all highlighting on the page - not just strip the HTML.

This type of thing could technically be done with a plugin though: strip the HTML before highlighting, highlight the plain text, insert HTML back at exactly the right spot in the generated markup.  

But this functionality purposely does not existing in core.

**Comment by Daedra22** [comment]
Thank you @joshgoebel for the fast response, I wrote now a function which replaces a specific string with input fields to achieve it.
