### ISSUE TITLE
`dart` & `armasm` languages not found

### ISSUE THREAD

**Issue by fishcharlie** [highlightjs/highlight.js#3440]
**Describe the issue/behavior that seems buggy**

When viewing [this page](https://blog.charlie.fish/posts/2021/12/hello-world-in-every-language) I get errors about how highlight.js can't find `dart` & `armasm` languages.

<img width="1721" alt="Screen Shot 2021-12-29 at 1 07 40 PM" src="https://user-images.githubusercontent.com/860375/147699590-2ca727ba-40ee-41c3-9b2c-a1fe9737f5ae.png">

However, when you look at the [Supported Languages page](https://github.com/highlightjs/highlight.js/blob/main/SUPPORTED_LANGUAGES.md) both of those are supported languages.

**Sample Code or Instructions to Reproduce**

```html
                            <code class="language-dart">main() {
                            	print("Hello World!");
                            }
                            </code>

                            <code class="language-armasm">//
                            // Assembler program to print "Hello World!"
                            // to stdout.
                            //
                            // X0-X2 - parameters to linux function services
                            // X16 - linux function number
                            //
                            .global _start             // Provide program starting address to linker
                            .align 2

                            // Setup the parameters to print hello world
                            // and then call Linux to do it.

                            _start: mov X0, #1     // 1 = StdOut
                                    adr X1, helloworld // string to print
                                    mov X2, #13     // length of our string
                                    mov X16, #4     // MacOS write system call
                                    svc 0     // Call linux to output the string

                            // Setup the parameters to exit the program
                            // and then call Linux to do it.

                                    mov     X0, #0      // Use 0 return code
                                    mov     X16, #1     // Service command code 1 terminates this program
                                    svc     0           // Call MacOS to terminate the program

                            helloworld:      .ascii  "Hello World!\n"
                            </code>
```

```js
hljs.highlightAll()
```

**Expected behavior**

No errors for valid languages.

**Additional context**

Posted on Discord last week with no reply: https://discord.com/channels/810874741370912799/828016175735767070/923749226662481950

**Comment by joshgoebel** [comment]
Not every supported language is bundled in the default distribution and many supported languages are published by third parties and will need to be installed separately.

You can build from source or you can use our website to build a custom bundle with your own choice of languages. Or you can use the default distribution and then add the languages are missing one at a time by including those JavaScript files. 

See the readme for instructions.

**Comment by joshgoebel** [comment]
Closing as this is expected behavior.

**Comment by fishcharlie** [comment]
@joshgoebel Thanks so much for your help. That worked perfectly. Might be worth it to add information to the [Supported Languages page](https://github.com/highlightjs/highlight.js/blob/main/SUPPORTED_LANGUAGES.md) about what languages are included in the default `https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.3.1/highlight.min.js` script.

**Comment by joshgoebel** [comment]
It already says that right at the top.
