### ISSUE TITLE
Relevance issues

### ISSUE THREAD

**Issue by jf990** [highlightjs/highlight.js#3443]
I was wondering if there is a change of behavior in version 11 regarding `relevance`, and if any final decision was made regarding https://github.com/highlightjs/highlight.js/issues/2826. When running the local tests I am now seeing lots of false grammar matches causing many test failures due to the wrong grammar being matched. I am able to solve it by running through my grammar and adding `relevance: 0` rather systematically until I get my grammar to no longer falsely match. I never had to do this before 11, but also I haven't updated in quite a few versions so that may be irrelevant.

I was wondering if we could consider a mode _dont auto-match this grammar_ to bypass auto-detection on specific grammars?

@joshgoebel

**Comment by joshgoebel** [comment]
Yes, _Score based on width, not depth._ via #3129   This prevents many false positives in cases when one is using a variable in a snippet that happens to be a keyword in another language... now that relevance stops adding up after 5 or 6 which lets the rest of the language shine thru properly.

I can't really think of any other huge changes.  Relevancy has been tuned here and there, but all our internal languages still maintain their relevancy relationships with each other (see `checkAutodetct.js`).


> I am able to solve it by running through my grammar and adding relevance: 0 rather systematically 

Many rules should be 0, things that don't match key languages features.  Also over-using rules vs keywords is broken in that the #3129 changes don't apply to rules, only `keywords` in the specific sense.  The best tips on relevancy is to make the same things (or same looking) relevant as we do by default (see `modes.js`)... IE, strings have a relevance of 1... so every grammar should gives strings a relevancy of 1.  Number have no relevance by default, etc.

Claiming relevancy for things that we DON'T typically give relevance for is the key to heartache here... such as `punctuation` or `operators` which should have 0 relevance, etc.

> I was wondering if we could consider a mode dont auto-match this grammar to bypass auto-detection on specific grammars?

It's easy to opt-out... `disableAutodetect` at the grammar level.

**Comment by jf990** [comment]
I didn't know about `disableAutodetect` I'll consider it if I run into a wall. Right now I was able to get all the grammars to play nice with the detection tests so we're good.

> Many rules should be 0

this sounds like 0 should be the default, not 1, and the rules opt-in to the relevance that is important to them.

**Comment by joshgoebel** [comment]
Can this be closed now?

> this sounds like 0 should be the default, not 1, and the rules opt-in to the relevance that is important to them.

I think that's just too overwhelming a project to change across 200 grammars... so not a priority.

**Comment by jf990** [comment]
yes it was answered above. thanks.
