### ISSUE TITLE
HTML/JS: Highlighting breaks when `class` extends a function call with string argument

### ISSUE THREAD

**Issue by danstewart** [highlightjs/highlight.js#3451]
**Describe the issue**
Highlighting breaks when a JavaScript class extends from a function call that contains a string argument.

**Which language seems to have the issue?**
`html` highlighting of JavaScript within a script tag.
It works when using the `javascript` highlighter. 

**Are you using `highlight` or `highlightAuto`?**
`hljs.highlightAll();`

**Sample Code to Reproduce**
https://jsfiddle.net/z7ugqk3x/

```html
<script type="module">
class SomeClass extends makeClass("abc") {
  constructor() {
    super();
    console.log(this.value);
  }
}
</script>
```

**Expected behavior**
It should highlight the same as the JavaScript highlighter does.

**Comment by joshgoebel** [comment]
Working here in 11.3, please update your fiddle to 11.3 and we can reopen if there is still an issue. v10 is no longer supported.

![Screen Shot 2022-01-04 at 9 30 13 AM](https://user-images.githubusercontent.com/6473/148074209-74b5adb8-ca45-4c18-9887-9dba00e23358.png)

**Comment by danstewart** [comment]
Sorry, didn't realise I was using an old version :man_facepalming: 
Thank you.
