### ISSUE TITLE
Was zenburn intentionally removed from the repo & cdn-assets?

### ISSUE THREAD

**Issue by coolaj86** [highlightjs/highlight.js#3461]
Zenburn was in the latest v10.x cdn release:
https://unpkg.com/browse/@highlightjs/cdn-assets@10.7.3/styles/

It's absent starting with the earliest v11.x release:
https://unpkg.com/browse/@highlightjs/cdn-assets@11.0.0/styles/

It seems to also be absent from the repo:
https://github.com/highlightjs/highlight.js/tree/main/src/styles

Latest discussion seems to include zenburn:
https://github.com/highlightjs/highlight.js/issues/3118

**Comment by joshgoebel** [comment]
It's part of the `base16` scheme set now and can be found in the `styles/base16` folder.

**Comment by coolaj86** [comment]
For reference: https://unpkg.com/browse/@highlightjs/cdn-assets@11.0.0/styles/base16/
