### ISSUE TITLE
Uncaught SyntaxError: Unexpected token )

### ISSUE THREAD

**Issue by ethaniel** [highlightjs/highlight.js#3463]
I log JavaScript errors and noticed that some clients are showing this error: "Uncaught SyntaxError: Unexpected token )" (user_agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/38.0.2125.104 Safari/537.36)

The block of code that the error is referring to is right in the beginning of the js file (after e.set).
![image](https://user-images.githubusercontent.com/941973/149822667-9d99cc28-98de-497f-b2cf-06665d266b30.png)

Any ideas why this could be triggered?

**Comment by joshgoebel** [comment]
Chrome 38 is crazy old... and doesn't support ES6, which is required now.

https://caniuse.com/?search=()%20%3D%3E

**Comment by ethaniel** [comment]
What is the last version of highlightjs without ES6?

**Comment by joshgoebel** [comment]
We dropped support for "legacy browsers" with version v10, and there are serious security issues with older versions, so I wouldn't recommend that.  If you must support such old browsers I might suggest perhaps maintaining a fork with an alternative build system and perhaps uses Babel to back-fill the missing ES6 features, but that is a moving target and could require maintaining other patches as well.  At least one other person was doing this a year or so ago though to support IE11.
