### ISSUE TITLE
highlight.min.js

### ISSUE THREAD

**Issue by stvowi** [highlightjs/highlight.js#3465]
I've installed highlight.js with npm but there is no highlight.min.js in the package,
Thats confusing because it was writen. in the website...

<link rel="stylesheet" href="/path/to/styles/default.min.css">
<script src="/path/to/highlight.min.js"></script>
<script>hljs.highlightAll();</script>

How about it with a dist folder/ production version?

**Comment by joshgoebel** [comment]
The NPM package is for building or server-side use... if you want prebuilt web assets use our CDN package instead: https://www.npmjs.com/package/@highlightjs/cdn-assets
