### ISSUE TITLE
Requesting a visible highlight color for 'googlecode'[Request] Short description of the new feature...

### ISSUE THREAD

**Issue by alemlakes** [highlightjs/highlight.js#3469]
**Is your request related to a specific problem you're having?**
A clear and concise description of the problem itself. Ex. I'm always frustrated when [...]

**The solution you'd prefer / feature you'd like to see added...**
A clear and concise description of how you imagine we might solve this (if you have any ideas).

**Any alternative solutions you considered...**
A clear and concise description of any alternative solutions or features you may have considered.

**Additional context...**
Add any other context or screenshots relating to the feature request here.

**Comment by alemlakes** [comment]
Hello, apologies if this isn't quite the right setting for this question. I am trying to use the googlecode coloration. For a long time I thought that the highlighting was broken, but recently discovered that it highlights in white. That's not a highlight that is visible in practice, so it is very confusing. 

My goal is to nicely highlight code in a new Open-Access book I am editing. It's for using Google Earth Engine, a satellite imagery-analysis platform used for detecting deforestation, etc. Our book has hundreds/thousands of snippets of code. We use a google code editor that looks just like your googlecode code coloration. So using the googlecode setting (in CodeBlocks II) would be ideal. Right now we use atelier-forest-light from CodeBlocks 1. There, the background is good but the code color doesn't match what they see. Is there a way that you could add a visible background (atelier-forest-light's tone would be perfect) to the googlecode code coloration?

Thousands of people around the world will download this book (for free!) to help save the Earth. I'd like to code in the book to be maximally helpful for them. Could you help me?  You can contact me at alemlakes@gmail.com or jeffrey.cardille@mcgill.ca as needed. Thank you!!

**Comment by joshgoebel** [comment]
Would need more details to even begin to address this... a screen snap, the name of the scope or class in question that you believe is highlighting incorrectly, etc... a textual code sample, etc...

**Comment by alemlakes** [comment]
Sure, I'd be happy to.  Hopefully this makes enough sense- let me know if not
![Screen Shot 2022-01-25 at 2 01 22 PM](https://user-images.githubusercontent.com/5034703/151041848-42cbd15e-f1a5-498f-b8b3-180a2be3a217.png)
!

**Comment by joshgoebel** [comment]
I think this issue is outside our scope of support and perhaps better asked in CodeBlocks support channels?  If you were working directly with the library then I'd suggest you just open up the CSS and change the colors (fg, bg, etc) to whatever you want them to be... we don't force anyone into any custom color choices.  That's why we offer multiple themes and someone can easily provide their own theme.

Whether or not this is possible with CodeBlocks I have no idea.

**Comment by joshgoebel** [comment]
Closing as this sounds more like a CodeBlocks question than a Highlight.js question.  The Highlight.js answer is "just modify the CSS to change the background color".

**Comment by alemlakes** [comment]
Ok thank you very much, that is great to know. I really appreciate your time on it even though it was out of scope. Thanks!
