### ISSUE TITLE
[Request] Allow italics in highlighted text

### ISSUE THREAD

**Issue by calgary34** [highlightjs/highlight.js#3472]
**Is your request related to a specific problem you're having?**
Often, I want to have some of the code be italic so that people can know that it's a placeholder. However, when I try to use the `<i>` tag, the code isn't italicized.

**The solution you'd prefer / feature you'd like to see added...**
Allow the `<i>` and `<em>` tags to be used in highlighted text.

**Any alternative solutions you considered...**

**Comment by joshgoebel** [comment]
For security reasons, this is not something we support.  There is an old plugin to do this, but it's not maintained:

https://github.com/highlightjs/highlight.js/issues/2889

To do this you pretty much have to:

- Remove the HTML before highlighting 
- Highlight
- Merge the HTML back into the string in the correct positions. (taking account for tags the highlighting itself added)
