### ISSUE TITLE
Specifying the language doesn't seem to work with custom HTML

### ISSUE THREAD

**Issue by doerwalter** [highlightjs/highlight.js#3474]
**Describe the issue/behavior that seems buggy**

I'm trying to use custom HTML with `highlight.js` and want to specify the language of the code block (because `highlight.js` seems to guess wrong). This doesn't seem to work, as `highlight.js` add a seconds `language-...` class.

**Sample Code or Instructions to Reproduce**

```html

I'm activating `highlight.js` with the following code:

<script>
	document.addEventListener('DOMContentLoaded', (event) => {
		document.querySelectorAll('pre, code').forEach(el => {
			hljs.highlightElement(el);
		});
	});
</script>
```

The HTML for the code block looks like this:

```html
<pre class="language-html">&lt;p&gt;
	&lt;a class="la-look-dangerbutton" href="#"&gt;
		&lt;i class="far fa-check la-lpad"&gt;&lt;/i&gt;Save
	&lt;/a&gt;
	&amp;nbsp;
	&lt;a class="la-look-button" href="#"&gt;
		&lt;i class="far fa-undo la-lpad"&gt;&lt;/i&gt;Cancel
	&lt;/a&gt;
&lt;/p&gt;</pre>
```

**Expected behavior**

The DOM after `highlight.js` has done the highlighting looks like this:

```html
<pre class="language-html hljs language-xml"><span class="hljs-tag">&lt;<span class="hljs-name">p</span>&gt;</span>
	<span class="hljs-tag">&lt;<span class="hljs-name">a</span> <span class="hljs-attr">class</span>=<span class="hljs-string">"la-look-dangerbutton"</span> <span class="hljs-attr">href</span>=<span class="hljs-string">"#"</span>&gt;</span>
		<span class="hljs-tag">&lt;<span class="hljs-name">i</span> <span class="hljs-attr">class</span>=<span class="hljs-string">"far fa-check la-lpad"</span>&gt;</span><span class="hljs-tag">&lt;/<span class="hljs-name">i</span>&gt;</span>Speichern
	<span class="hljs-tag">&lt;/<span class="hljs-name">a</span>&gt;</span>
	<span class="hljs-symbol">&amp;nbsp;</span>
	<span class="hljs-tag">&lt;<span class="hljs-name">a</span> <span class="hljs-attr">class</span>=<span class="hljs-string">"la-look-button"</span> <span class="hljs-attr">href</span>=<span class="hljs-string">"#"</span>&gt;</span>
		<span class="hljs-tag">&lt;<span class="hljs-name">i</span> <span class="hljs-attr">class</span>=<span class="hljs-string">"far fa-undo la-lpad"</span>&gt;</span><span class="hljs-tag">&lt;/<span class="hljs-name">i</span>&gt;</span>Abbrechen
	<span class="hljs-tag">&lt;/<span class="hljs-name">a</span>&gt;</span>
<span class="hljs-tag">&lt;/<span class="hljs-name">p</span>&gt;</span></pre>
```

i.e. `highlight.js` has added an additional `language-xml` CSS class. Does this mean that `highlight.js` hasn't recognized my `language-html` class?

I would have expected that the result would start with:

```html
<pre class="language-html hljs">
	...
```

**Comment by joshgoebel** [comment]
There is no 'html" language.  HTML is an alias for `xml`.  When highlighting the canonical language name is always added, so in this case you have both - which causes no harm.  If you only want one switch your code to use the `xml` instead of `html`.

**Comment by doerwalter** [comment]
This is almost entirely true, but not totally:

* HTML has predefined entity references for characters (like `&mdash;` etc.), XML doesn't.
* Some HTML elements are predefined to have a CDATA content model (for example `<script>`, so
   ```html
   console.log("&amp;");
   ```
   will log `&amp;` not `&`.

But I discovered something else: `xml` mode doesn't mark up custom processing instructions (only `<?xml ...?>` is marked up (as `meta`)). Should I open a separate issue for that?

**Comment by joshgoebel** [comment]
> There is no 'html" language. HTML is an alias for xml.

To be clear I was speaking only in terms of how Highlight.js handles them. I am aware that they are not exactly the same. 

> Should I open a separate issue for that?

Yes please.

**Comment by doerwalter** [comment]
> > > [XML processing instructions]
> > Should I open a separate issue for that?
> 
> Yes please.

Done: https://github.com/highlightjs/highlight.js/issues/3474
