### ISSUE TITLE
Syntax Error when load on Firefox Browser v.77.0.1 (64-bit)

### ISSUE THREAD

**Issue by ioofy** [highlightjs/highlight.js#3476]
Hello i have some problem on Firefox browser, my code runs fine in all browsers except Firefox which is

InvalidIdentity in Regular Expression, you can look at this image

![image](https://user-images.githubusercontent.com/77242429/153013960-06db7c48-e6fa-40a7-ab4c-d232881de797.png)

On console
![image](https://user-images.githubusercontent.com/77242429/153014240-908fd475-b7ee-480f-9989-4e8c5d2f4629.png)

My code

```ts
//[slug].tsx

import React, { useEffect } from "react";
import { GetStaticPaths, GetStaticProps, InferGetStaticPropsType } from "next";
import { serialize } from "next-mdx-remote/serialize";
import { MDXRemote, MDXRemoteSerializeResult } from "next-mdx-remote";
import { Container } from "@styles/global.styles";
import fs from "fs";
import path from "path";
import matter from "gray-matter";
import BlogHeader from "@components/BlogHeader";
import BlogWrapper from "@components/BlogWrapper";
import hljs from "highlight.js";
import "highlight.js/styles/tomorrow-night-bright.css";

type Params = {
  [param: string]: any;
};

type ArticleProps = {
  source: MDXRemoteSerializeResult<Record<string, unknown>>;
};

export default function Article({
  source,
}: ArticleProps): InferGetStaticPropsType<typeof getStaticProps> {
  const {
    scope: { dateString, mainImageUrl, title, excerpt, longtimeRead, altImage },
  } = source;

  useEffect(() => {
    hljs.highlightAll();
  }, []);

  return (
    <Container>
      <BlogHeader
        altImage={altImage}
        longtimeRead={longtimeRead}
        excerpt={excerpt}
        title={title}
        dateString={dateString}
        mainImageUrl={mainImageUrl}
      />
      <BlogWrapper>
        <MDXRemote {...source} />
      </BlogWrapper>
    </Container>
  );
}

export const getStaticPaths: GetStaticPaths = async () => {
  const articleDirectory = path.join("__articles");
  const articleFiles = fs.readdirSync(articleDirectory);
  const paths = articleFiles.map((fileName: string) => ({
    params: {
      slug: fileName.replace(".mdx", ""),
    },
  }));

  return {
    paths,
    fallback: false,
  };
};

export const getStaticProps: GetStaticProps<Params> = async ({
  params: { slug },
}: Params) => {
  const articleFile = fs.readFileSync(path.join("__articles", slug + ".mdx"));
  const { data: metaData, content } = matter(articleFile);
  const mdxSource = await serialize(content, { scope: metaData });

  return { props: { source: mdxSource } };
};
```

If i'm comment all from module highlight.js its running.
Any solutions?

**Comment by joshgoebel** [comment]
Closing as a dup of https://github.com/highlightjs/highlight.js/issues/3387.  This is a #wontfix.  Firefox 77/78 is over 1.5 years (18 releases!) old now and no longer supported by Highlight.js. You can read the other issue for more context.

**Comment by ioofy** [comment]
I see. Thanks sir👍

**Comment by iMrDJAi** [comment]
> 1.5 years

@joshgoebel A 1.5 years old browser isn't old at all btw. A browser from 2015 is still a modern browser! I think your browser support polity is broken 👎

Developers have no control over what client users have. Imagine someone attempts to visit your website and it ends up broken because of one stupid regex error 🤒

Anyway, to which version of highlight.js do you suggest I downgrade?

**Comment by joshgoebel** [comment]
We never suggest users run older versions.  What we do suggest is already documented in #3387 and this issue is already talked out there.

**Comment by joshgoebel** [comment]
> We also can't suggest users run newer browsers. 

While it may be impossible to guarantee I certainly don't see why it couldn't be at least _suggested_.  A browser that is 18 releases behind on critical bugfixes and security updates is not a good thing in the world.
