### ISSUE TITLE
XML mode doesn't highlight processing instructions

### ISSUE THREAD

**Issue by doerwalter** [highlightjs/highlight.js#3479]
`highlight.js` does not highlight processing instructions in XML mode (except for the pseudo processing instruction `<?xml ...?>`)

I am using `highlight.js` 11.4.0 and the following HTML code:

```html
<pre class="language-xml">
&lt;?ul4 langs(*names)?&gt;
&lt;?whitespace strip?&gt;
&lt;?doc Languages?>
&lt;ul>
	&lt;?for n in names?>
		&lt;li>
			&lt;?printx n?>
		&lt;/li>
	&lt;?end for?>
&lt;/ul> 
</pre>
```

I include `highlight.js` like this (in the `<head>`):

```html
<script src="/static/highlight.js/11.4.0/highlight.min.js"></script>
```

I activate `highlight.js` by the following `<script>` at the end of the `<body>`:

```html
<script>
	document.addEventListener('DOMContentLoaded', (event) => {
		document.querySelectorAll('pre, code').forEach(el => {
			hljs.highlightElement(el);
		});
	});
</script>
```

The only highlighted parts in the result however are the start and end tags. None of the processing instructions get hightlighted:

![Bildschirmfoto 2022-02-14 um 11 55 36](https://user-images.githubusercontent.com/1387028/153851134-1c02ef70-037f-4bd1-9aba-de8872fa43f8.png)

For information about XML processing instructions see: https://www.w3.org/TR/REC-xml/#sec-pi

**Comment by joshgoebel** [comment]
![Screen Shot 2022-02-25 at 11 35 59 AM](https://user-images.githubusercontent.com/6473/155752380-d4554eb9-3c59-4031-a3ce-4043f572e983.png)

Looks kind of blah if one has tons of processing instructions.
