### ISSUE TITLE
Version 11.4.0 not working in Safari 15.x

### ISSUE THREAD

**Issue by GonzaloHirschToptal** [highlightjs/highlight.js#3487]
I'm using a self-hosted version of the library just for highlighting Solidity code (with Vue 3 + Vite) and it works perfectly for Chrome, Edge, and Firefox, but in Safari I get the following error:

```
Unhandled Promise Rejection: SyntaxError: Invalid regular expression: invalid group specifier name
```

Which points to the following line in the minified file:
```
o && (r.begin || (r.begin = /\B|\b/), a.beginRe = t(a.begin), r.end || r.endsWithParent || (r.end = /\B|\b/),
```

I'm calling the `highlightElement` method like this:
```
hljs.highlightElement(contractCode.value);
```
**Sample Code or Instructions to Reproduce**
1. Import the self hosted version of the library in the index.html at the bottom of the `body` tag:
```
<script src="/js/highlight.min.js"></script>
```
2. Have a `ref` in Vue to the `code` tag element that will have the highlight:
```
<template>
<pre>
        <code ref="contractCode" class="language-solidity">code...</code>
</pre>
</template>
<script setup>
import { ref } from 'vue';

const contractCode = ref(null);
const formatCode = () => {
    if (hljs) {
        hljs.highlightElement(contractCode.value);
    }
};
formatCode();
</script>
```

**Expected behavior**
It should highlight properly in Safari, but it's not.

**Additional context**
Vue version: ^3.2.20
Vite version: ^2.6.13

**Comment by joshgoebel** [comment]
https://www.npmjs.com/package/highlightjs-solidity is a 3rd party package and not supported by the core team.  Please show that this is reproducible with only Highlight.js (and one of the built-in grammars) and we'd be happy to take a closer look.  A JSFiddle that reproduces the issue would be great.

Everything is working fine here in Safari 14.

**Comment by joshgoebel** [comment]
@GonzaloHirschToptal Very likely this is because `solidity` is using negative look-behind (which we do not recommend as Safari doesn't support it yet)... so you may want to re-open this issue against Solidity's grammar...

**Comment by joshgoebel** [comment]
If I prove to be mistaken on that this issue can be reopened. :)
