### ISSUE TITLE
[Request] Use `&#34;` instead of `&quot;`

### ISSUE THREAD

**Issue by dosisod** [highlightjs/highlight.js#3498]
**Is your request related to a specific problem you're having?**

Not exactly: Although the outputted HTML is very small already, it could be made slightly smaller by using a a different representation for quotes (saves 1 byte per quote character). I am using this library to generate HTML for a static site, so storage is more of a "concern" (if you can call 1 byte concerning).

**The solution you'd prefer / feature you'd like to see added...**

* Update [this line](https://github.com/highlightjs/highlight.js/blob/fd307015164c05b191156efc378622293089c616/src/lib/utils.js#L10) directly (which would break all of the tests)
* A flag/optional argument to replace `&quot;` with `&#34` once the HTML has been generated
* A plugin of sorts which would do the same thing as above

**Any alternative solutions you considered...**

You can run `sed` to just replace it after the fact, but it would be nice to have it built in.

**Additional context...**

Although this is super minor, it would be cool to try and shrink the size of the exported HTML, even by a little bit. I don't know if the size of the exported HTML is a priority/concern, so I thought I would ask! Any feedback would be great, Thanks!

**Comment by joshgoebel** [comment]
Most HTML content served on the web should be gzipped (or better) so there's actually going to be zero effective difference in size between both approaches. 

If you really still think this is a good idea in your own processing/build phase you should simply call `replace` after highlighting to swap the sequence yourself.  It's one line of code.
