### ISSUE TITLE
(F#) Single quote chars highlighted as type variables in Discord code block

### ISSUE THREAD

**Issue by Eliemer** [highlightjs/highlight.js#3502]
**Describe the issue**
Using discord code blocks, highlights single quotes as type variables and ignores the closing single quote.

**Which language seems to have the issue?**
This is F#

**Are you using `highlight` or `highlightAuto`?**
Im specifiying F# with `fs` in the discord codeblock

**Sample Code to Reproduce**

\`\`\`fs
let myChar = 'a' // highlights 'a, but ignores the closing '
let myString = "a" // correctly highlights string
let myFun (x : 'a) : 'b = ... // correctly highlights type variables `a` and `b`
\`\`\`

example screenshot
![image](https://user-images.githubusercontent.com/21344441/156804715-cf3e1375-8ed0-4c70-959d-96268129d793.png)

**Expected behavior**
`'a'` should highlight differently to `'a`
```fs
// character literals
let rec numVowels L = 
  function
  | ('a'|'e'|'i'|'o'|'u')::tail -> 1 + numVowels tail
  | _ -> 0 
  
// type variables
type MyList<'a> =
  | Nil
  | Cons of 'a * MyList<'a>
```

**Comment by joshgoebel** [comment]
It looks to me like perhaps you're not using the library with `fsharp` included as it highlights correctly for me here with no issues:

![Screen Shot 2022-03-04 at 12 09 40 PM](https://user-images.githubusercontent.com/6473/156809489-fc0a1e9a-a348-42f7-be15-c7ca88dbcbdf.png)

If you can reproduce with a standalone install of 10.4 with no other code I can take a closer look... here is a jsfiddle you can start with:

https://jsfiddle.net/ajoshguy/cjhvre2k/24/

**Comment by Eliemer** [comment]
https://jsfiddle.net/sp57L1ua/
Its replicable in 10.4.
11.4 highlights correctly

**Comment by joshgoebel** [comment]
[10.x hasn't been supported for quite some time.](https://github.com/highlightjs/highlight.js/blob/main/SECURITY.md)  Now that you mention it I do think someone did a large chunk of work on F# grammar just a little while back.  Seems they fixed the issue!

Time to beg Discord to upgrade?

_Closing as already resolved in latest version._
