### ISSUE TITLE
sideEffect: false, stops webpack importing css

### ISSUE THREAD

**Issue by domarmstrong** [highlightjs/highlight.js#3504]
**Describe the issue/behavior that seems buggy**

In 11.5.0, `sideEffects: false` was added to the `package.json`. This has stopped the styles being imported by webpack which now sees it as an unused zero side effect file. See https://github.com/webpack-contrib/mini-css-extract-plugin/issues/102#issuecomment-384947142.

**Comment by joshgoebel** [comment]
History #3396. @shakyShane Any thoughts?  Do we instead need something like `sideEffects: ["*.css"]`?  I'm not really familiar with this in detail.

**Comment by verhovsky** [comment]
could I get a 11.5.1 release just with this change please? everyone who uses webpack (the most popular build tool) for their website that upgrades highlight.js will brake their site.

**Comment by joshgoebel** [comment]
Pushing 11.5.1 now.

**Comment by limonte** [comment]
Confirming that the fix is working 🎉
