### ISSUE TITLE
(cmake) Multiline commands cannot be highlighted correctly

### ISSUE THREAD

**Issue by cngzhnp** [highlightjs/highlight.js#3509]
**Describe the issue**

`Cmake `commands highlighted perfectly fine when they are described or written in one line. 

However, if `cmake` command takes a lot of parameters or arguments, we do not want to compress them into one line. So, the problem starts here, if you write down multiline `cmake `command, highlight feature does not work properly as expected.

**Which language seems to have the issue?**

`Cmake`

**Are you using `highlight` or `highlightAuto`?**

`highlight.js 11.5.0`

**Sample Code to Reproduce**
```
set_target_properties(myTarget PROPERTIES
                               CXX_STANDARD 11 
                               CXX_STANDARD_REQUIRED YES 
                               CXX_EXTENSIONS NO
                               )
```

![image](https://user-images.githubusercontent.com/4690241/159738239-018f4c87-d8d8-442c-b989-03e00ac8b6f5.png)

**Expected behavior**

Highlight neat even though it is written in multi-line.

**Comment by joshgoebel** [comment]
Can't reproduce.
![Screen Shot 2022-03-29 at 8 41 33 AM](https://user-images.githubusercontent.com/6473/160613449-cae51709-6c09-4b8f-83d1-5c15b8774096.png)

Please provide a JSFiddle that reproduces the issue to confirm it's not your stack somehow.

You can fork: https://jsfiddle.net/ajoshguy/cjhvre2k/25/

**Comment by joshgoebel** [comment]
I'd suggest it's possible you aren't truly using `cmake` at all - it's not built in by default... I'd triple check.

**Comment by cngzhnp** [comment]
Thanks for the reply, I thought that it was not working standalone `highlight.js` but seems that it is broken when `reveal.js` is in the game. I can close the issue by verifying that it is working properly.

**Comment by joshgoebel** [comment]
Please file an issue against reveal.js and cross-link here. I'd love to track this one on their end. 

If you're certain you have the cmake grammar loaded then this is (I'm guessing) almost definitely an issue of reveal.js breaking the parser by trying to "drive" it line-by-line which has never worked properly (tons of edge cases) despite many people doing it.
