### ISSUE TITLE
(CSS) highlight incorrectly: A string within parentheses

### ISSUE THREAD

**Issue by Zuoqiu-Yingyi** [highlightjs/highlight.js#3514]
**Describe the issue**

![image](https://user-images.githubusercontent.com/49649786/161419104-e5bacabb-b4ee-4b54-b246-c480cb68646f.png)
**Which language seems to have the issue?**

`CSS`

**Are you using `highlight` or `highlightAuto`?**

`highlight` v11.5.0

**Sample Code to Reproduce**

```css
:root {
    --custom-background-image-1: url('/appearance/themes/Dark+/image/background (01).jpg');
    --custom-background-image-2: url('/appearance/themes/Dark+/image/background (02).jpg');
    --custom-background-image-3: url("/appearance/themes/Dark+/image/background (03).jpg");
    --custom-background-image-4: url("/appearance/themes/Dark+/image/background (04).jpg");
}
```
**Expected behavior**

When `)` appears in the string, it should not take precedence over `'` or `"` for matching.

**Additional context**

**Comment by taufik-nurrohman** [comment]
_Highlight.js_ has its own way to construct regular expression. If you are okay with plain regex, then I would recommend this:

~~~ js
const STR_REGEX = new RegExp("(?:\\\\.|[^"])*"|\'(?:\\\\.|[^\'])*\'');
~~~

**Comment by taufik-nurrohman** [comment]
Try to include the `STRINGS` regex here:

https://github.com/highlightjs/highlight.js/blob/d64f68e8aabc67820eec2459bff9a7a0fcc06b95/src/languages/css.js#L85-L94

~~~ js
contains: [
  ...STRINGS, // <-- this!
  {
    className: "string",
    // any character other than `)` as in `url()` will be the start
    // of a string, which ends with `)` (from the parent mode)
    begin: /[^)]/,
    endsWithParent: true,
    excludeEnd: true
  }
]
~~~

**Comment by joshgoebel** [comment]
Indeed, this is the correct fix:

```
--- a/src/languages/css.js
+++ b/src/languages/css.js
@@ -83,6 +83,7 @@ export default function(hljs) {
             relevance: 0, // from keywords
             keywords: { built_in: "url data-uri" },
             contains: [
+              ...STRINGS,
               {
                 className: "string",
                 // any character other than `)` as in `url()` will be the start
```

There are some other CSS consistency issues here though so I'll take this one myself.
