### ISSUE TITLE
(mysql) not working highlight

### ISSUE THREAD

**Issue by dimaslanjaka** [highlightjs/highlight.js#3517]
https://codepen.io/dimaslanjaka/pen/qBpYPPM

```html
<pre><code class="language-mysql">CREATE USER 'dimaslanjaka'@'%' IDENTIFIED VIA mysql_native_password USING '***';GRANT ALL PRIVILEGES ON *.* TO 'dimaslanjaka'@'%' REQUIRE NONE WITH GRANT OPTION MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;GRANT ALL PRIVILEGES ON `dimaslanjaka\_%`.* TO 'dimaslanjaka'@'%';
</code></pre>

<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/11.5.0/styles/default.min.css">
<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/11.5.0/highlight.min.js"></script>
<script>
  (function() {
    hljs.highlightAll();
  })();
</script>
```

**Comment by joshgoebel** [comment]
Please see the console where the error is quite clear:

```
"WARN: Could not find the language 'mysql', did you forget to load/include a language module?"
```

There is no `mysql` language.  We ship a `sql` language but it is not always necessarily a good choice, hence there is not an alias from `mysql` to `sql`.

For the canonical list please see:

https://github.com/highlightjs/highlight.js/blob/main/SUPPORTED_LANGUAGES.md

**Comment by parallels999** [comment]
> Sadly there is not yet a MySQL grammar.

@joshgoebel hi,  are PRs accepted for that?

**Comment by joshgoebel** [comment]
No, but we'd love to see a 3rd party MySQL grammar: https://highlightjs.readthedocs.io/en/latest/language-contribution.html

And we're accept a PR to add it to SUPPORTED_LANGUAGES so people can find it.

**Comment by angeljqv** [comment]
> hi, are PRs accepted for that?
>> No

😕😭😭

**Comment by dimaslanjaka** [comment]
auto highlight.js loader support mysql https://www.webmanajemen.com/page/highlight-js.html
