### ISSUE TITLE
(markdown) List items inside blockquotes/HTML comments aren't highlighted correctly

### ISSUE THREAD

**Issue by double-beep** [highlightjs/highlight.js#3519]
Consider this markdown:

```
> * One (this point is italic)
> * Two
> * Three

This is italic, and because of a lack of termination (#21), everything after is italic

<!-- * but a comment terminates the italic -->

Regular text
```

It gets highlighted like this:

![incorrect markdown highlighting](https://user-images.githubusercontent.com/38133098/162748778-fc67956b-3e09-4571-a052-a9889aaa5fb8.png)

----

It is, however, valid markdown:

> * One (this point is italic)
> * Two
> * Three

This should not be italic

Regular text

---

Compare with the following markdown:

```
> - One
> - Two
> - Three

some text
```

that gets highlighted like this:

![correct markdown highlighting](https://user-images.githubusercontent.com/38133098/162749255-d6f246da-27ae-4a93-a7cf-682264a758fc.png)

or this:

```
* One
* Two
* Three

some text
```

which gets highlighted like this:

![correct markdown highlighting](https://user-images.githubusercontent.com/38133098/162750227-148e5915-df39-42db-a903-1bedbaa86872.png)

**Comment by joshgoebel** [comment]
Hmmm... How does a typical Markdown parser know this isn't the beginning of italics (which can span lines typically, no?)... are the rules for italics different inside quotes?  What would this be:

```
> * One (this point is italic) *
> * Two *
> * Three *
```

Or this:

```
> *One (this point is italic)*
> *Two*
> *Three*
```

Is there a difference?

**Comment by double-beep** [comment]
I believe that in lists a space between the `-`/`*`/... character and the list content is necessary, while in italic/bold there must be no space between `**`/`__`/... and the emphasised content.

The [CommonMark](https://spec.commonmark.org/0.30/#emphasis-and-strong-emphasis) specification has more examples than the [original MD syntax](https://daringfireball.net/projects/markdown/syntax#em).

**Comment by joshgoebel** [comment]
I think the attached PR fixes the false positive, but I'm not sure how to detect the bullets in blockquotes... we don't have sequencing abilities for nesting so there is no way to match the block quote then say "match a bullet only if it begins the quote"...
