### ISSUE TITLE
Syntax highlighting overrides HTML formatting inside code blocks

### ISSUE THREAD

**Issue by gparyani** [highlightjs/highlight.js#3524]
**Describe the issue/behavior that seems buggy**

When a code block that uses the HTML `<pre><code>` tags contains HTML formatting such as `<b>` or `<s>`, and the block is highlighted using highlight.js, any such formatting is overridden. Such formatting should be retained whenever possible, and in cases where it clashes with formatting applied by highlight.js (happens most commonly when highlighting Markdown), the type specified in the HTML tags should take precedence.

**Sample Code or Instructions to Reproduce**

The following code contains `<strike><b>` tags to make part of it struck out and bolded. This works when the HTML elements `<pre><code>` are used:

```
<pre><code>...
GROUP BY model.name, attempt.type, <strike><b>attempt.result</b></strike>
...</code></pre>
```

When the highlighting is performed, it incorrectly looks like:

```
...
GROUP BY model.name, attempt.type, attempt.result
...
```

(when seen through a black-and-white camera)

**Expected behavior**

The part surrounded by `<strike><b>` tags should be bold and struck out. This is how the code block looks like when not highlighted:

<pre><code>...
GROUP BY model.name, attempt.type, <strike><b>attempt.result</b></strike>
...</code></pre>

**Additional context**

This issue was discovered on Stack Exchange. [This](https://meta.stackexchange.com/questions/378134/html-formatting-inside-code-blocks-doesnt-work-if-syntax-highlighting-is-being) is the Meta Stack Exchange bug report; the above code samples came from there. I should also note that this behavior works properly in the previous highlighter Stack Exchange formerly used,  [Prettify](//github.com/googlearchive/code-prettify).

**Comment by joshgoebel** [comment]
We call this kind of thing "HTML merging".  This is intentionally no longer supported as in our opinion 98% of the time this is done inadvertently and only leaves users open to HTML injection attacks.  This type of functionality can easily be added via plug-in for users who understand what they are doing:

https://github.com/highlightjs/highlight.js/issues/2889

I'd raise the issue with StackOverflow technical team if you think they should support this.
