### ISSUE TITLE
[Request] Include code in 'extra' directory in developer.html language list

### ISSUE THREAD

**Issue by dschach** [highlightjs/highlight.js#3532]
**Is your request related to a specific problem you're having?**
I'm trying to use developer.html to figure out why my code registers as Apex (what I'm working on creating) there but as typescript at other times. I want to highlight my test code using more than the default languages in the picklist

**The solution you'd prefer / feature you'd like to see added...**
1. Better documentation on what I need to run when using developer.html (it seems I need to compile browser, since build cdn and node apparently erase everything that page needs.
2. Automatic searching in the extra folder for the language being developed so it is automatically included
3. Maybe include EVERY language in the main repository, as there are far more than the ones in the picklsit.

**Any alternative solutions you considered...**
I thought about editing the javascript that collects languages, but it seems it only looks in specific places, and that's a rat-hole.
I also thought about manually adding the language in the extra folder, but that won't include it in the page showing the score for the new language.

**Additional context...**
I'd just say that in general, knowing which build to use isn't very well documented. And I can't figure out how to use illegals properly so my language is skipped completely if, say, it has any word that starts with _ (just as an example).

**Comment by joshgoebel** [comment]
The developer tool just uses the most recent `browser` build, so include whatever languages you wish to test/play with:

```
# build just common set
./tools/build -t browser :common
# build common set + 3rd party `abc` and `def` from extra
./tools/build -t browser :common abc def
# build everything (including all in extra)
./tools/build -t browser 
```

If any illegal matches (for the current scope) then that fires the illegal signal.  For auto detection that means the languages is a non-match.  In other cases this can be ignored and queried with `ignoreIllegal`.

Word boundary followed by _word:

```js
illegal : [
  /\b_\w+/
]
```

**Comment by dschach** [comment]
Thanks! That worked - I'll submit my Salesforce Apex highlighting repo soon.
