### ISSUE TITLE
(MATLAB block in MarkDown) Highlighting totally messes up in classdef block

### ISSUE THREAD

**Issue by Silver-Fang** [highlightjs/highlight.js#3533]
**Describe the issue**

Highlighting in *classdef* block is messed up.
**Which language seems to have the issue?**

MATLAB code block in MarkDown
**Are you using `highlight` or `highlightAuto`?**
I'm using VS Code.
...

**Sample Code to Reproduce**

```MATLAB
classdef ShowProgress<ParallelComputing.BlockRWStream
	methods(Access=protected)
		function NextObject(obj)
			%先调用基类，执行该方法必要的基本功能
			obj.NextObject@ParallelComputing.BlockRWStream;
			%然后输出进度
			Index=obj.ObjectsRead+1;
			fprintf('文件%u/%u：%s\n',Index,obj.NumObjects,obj.RWObjects(Index));
		end
	end
	methods
		function obj=ShowProgress(RWObjects,GetRWer)
			obj@ParallelComputing.BlockRWStream(RWObjects,GetRWer);
		end
	end
end
```
![image](https://user-images.githubusercontent.com/33191697/167379294-bf25042e-71f9-4cad-a749-468eafbba6b0.png)

**Expected behavior**

**Additional context**

VS Code version:
版本: 1.67.0-insider (user setup)
提交: 57fd6d0195bb9b9d1b49f6da5db789060795de47
日期: 2022-05-04T12:03:42.454Z
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Windows_NT x64 10.0.22616

**Comment by joshgoebel** [comment]
![sample](https://user-images.githubusercontent.com/6473/167485851-63a2f8bb-626c-4a9a-b878-99f8a803f3d0.png)

Looks fine here, are you certain you're actually highlighting using `matlab`? It's not part of the default bundle.

**Comment by Silver-Fang** [comment]
> ![sample](https://user-images.githubusercontent.com/6473/167485851-63a2f8bb-626c-4a9a-b878-99f8a803f3d0.png)
> 
> Looks fine here, are you certain you're actually highlighting using `matlab`? It's not part of the default bundle.

Not sure. I ask here because the last time I had a highlighting problem I submitted an issue at VS Code repository but was redirected here. In your screenshot, I can't tell if you're also using the MarkDown editor of VS Code, as my context.
I may also create an issue at VS Code again.

**Comment by Silver-Fang** [comment]
VS Code seems to have admitted that it is their problem.
