### ISSUE TITLE
[Request] Python3.10 match case syntax highlighting

### ISSUE THREAD

**Issue by Auxtal** [highlightjs/highlight.js#3537]
**Is your request related to a specific problem you're having?**
No

**The solution you'd prefer / feature you'd like to see added...**
Syntax highlighting for python3.10 match case

**Any alternative solutions you considered...**
N/A

**Additional context...**
N/A

**Comment by joshgoebel** [comment]
So we just need to add match and case?

**Comment by Auxtal** [comment]
Yep ;)
