### ISSUE TITLE
highlightBlock: add option to configure the language

### ISSUE THREAD

**Issue by rauschma** [highlightjs/highlight.js#354]
Currently, `highlightBlock` determines the language via class names such as `javascript`. If that isn’t what you want then you have no way of changing it.

**Comment by luckydonald** [comment]
This does not work anymore.

**Comment by luckydonald** [comment]
Workaround-workaround:
```js
var text = node.innerText;
var lol = hljs.highlight(language, text);
node.innerHTML = lol.value;
```
