### ISSUE TITLE
Repository for new Salesforce Apex parser

### ISSUE THREAD

**Issue by dschach** [highlightjs/highlight.js#3545]
**Is your request related to a specific problem you're having?**
I have been working on an Apex highlighter, and I think it's ready for v1 release. It's currently at [https://github.com/dschach/highlightjs-apex](https://github.com/dschach/highlightjs-apex)

**The solution you'd prefer / feature you'd like to see added...**
Let's open a private repo that I can contribute to. 

**Any alternative solutions you considered...**
I'd rather not self-host it in my account because I want it auto-updated to CDN when I make changes

**Additional context...**
I have a sample implementation of an early version I made at [https://dschach.github.io/salesforce-trigger-framework/](https://dschach.github.io/salesforce-trigger-framework/). I think it's pretty good. 
I'd like to get this into the standard ApexDox VSCode extension, and then to get most of the official Salesforce repos using highlight.js instead of the current Prism usage.

**Comment by joshgoebel** [comment]
> because I want it auto-updated to CDN when I make changes

What does that have to do with where it's hosted?

> Let's open a private repo that I can contribute to.

It wouldn't be private... if your grammar isn't ready yet - continue developing in your own [private] repo.  When it's ready I'm happy to create a public repo for it heere.

**Comment by dschach** [comment]
It's ready now. I don't know how to upload to CDN, and I assumed that repos in this organization were automatically added to the CDN. That would be a pretty cool service - including repos within this organization in the CDN uploads.
Anyway, I'm ready to go with it.

**Comment by joshgoebel** [comment]
That is a huge list of illegals, was auto-detect super imporatnt to you?

**Comment by joshgoebel** [comment]
https://github.com/highlightjs/highlightjs-apex

**Comment by joshgoebel** [comment]
> I don't know how to upload to CDN,

I don't know how to either, that stuff was setup long ago... publish an NPM package and you'll get into one of the CDNs by default... but no - there is nothing magical about the repository being in our organization other than higher visibility - there is no special automation we provide to 3rd party repos.

**Comment by dschach** [comment]
@joshgoebel Yes, because Apex has some weird idiocyncracies that make it look like a lot of other languages, I went with a long list of illegals. It might have been my sample code used for detection, but I figured it can't hurt to be safe.
