### ISSUE TITLE
GitLab code snippets get highlighted by hljs when they shouldn't be

### ISSUE THREAD

**Issue by Pistrie** [highlightjs/highlight.js#3548]
**Describe the issue/behavior that seems buggy**

hljs.highlightAll() combined with GitLab code snippets causes those GitLab code snippets to also be highlighted. This should obviously not happen because GitLab is already making sure that the code gets proper highlighting.

**Sample Code or Instructions to Reproduce**

1. Import hljs and start it with `<script>hljs.highlightAll();</script>`
2. Create and embed a GitLab snippet

![image](https://user-images.githubusercontent.com/39904003/171927724-27ed1dd1-7c19-42b5-aa7c-a5a16c6660f4.png)
Snippet with hljs enabled
![image](https://user-images.githubusercontent.com/39904003/171929841-9c4bd47a-4cfc-44f5-89b4-6e55b3929834.png)
Snippet without hljs

Code used:
```html
<link
  rel="stylesheet"
  href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/11.5.1/styles/default.min.css"
/>
<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/11.5.1/highlight.min.js"></script>
<script>hljs.highlightAll();</script>
```
```html
<script src="https://gitlab.com/Pistrie/opdracht-gun-file-upload/-/snippets/2342584.js"></script>
```

**Expected behavior**

The GitLab snippet should not be touched by hljs

**Comment by joshgoebel** [comment]
https://highlightjs.readthedocs.io/en/latest/api.html#configure

See `noHighlightRe`... if GitLab applies a certain class then you can modify the regex to match that class and tell us to magically exclude those code snippets.  If not then you'd have to go a layer lower and write your own `highlightAll` with custom detection code to decide which blocks to skip and which to highlight.

**Comment by joshgoebel** [comment]
Also perhaps `cssSelector` might be of interest if you could try some sort of negative match rule against a higher level parent in the HTML.

**Comment by Pistrie** [comment]
I've made it work by adding `highlight` to `noHighlightRe`.
![image](https://user-images.githubusercontent.com/39904003/171992288-1158146d-104c-4c7b-a245-404f105f5f2a.png)

```html
<script>
  hljs.configure({
    noHighlightRe: /^highlight$/i,
  });
  hljs.highlightAll();
</script>
```
Here is a screenshot of the entire structure of the snippet. Would there be a more 'elegant' way to do this, or is using `highlight` fine as it is?
![image](https://user-images.githubusercontent.com/39904003/171992356-4d688449-04e1-494e-acbc-8590a8421076.png)

**Comment by joshgoebel** [comment]
If GitLab uses `highlight` by default I'd say that's about perfect.

**Comment by joshgoebel** [comment]
I mean you may want a more flexible regex in the future allowing for your own excludes, but otherwise looks good.

```js
// highlighted by GitLab or we manually say "nohighlight"
/^highlight|nohighlight$/i
```
