### ISSUE TITLE
Request: Java generics could be highlighted?

### ISSUE THREAD

**Issue by illuminator3** [highlightjs/highlight.js#3554]
**Describe the issue**

Java generics are not being highlighted

**Which language seems to have the issue?**

Java

**Are you using `highlight` or `highlightAuto`?**

highlight

**Sample Code to Reproduce**

```
class Foo {
    void bar() {
        Foo<Bar> buzz;
    }
}
```

**Expected behavior**

Showing the diamond operator

**Additional context**

**Comment by joshgoebel** [comment]
How could we be certain those aren't greater then and less than comparison operators?

**Comment by illuminator3** [comment]
> How could we be certain those aren't greater then and less than comparison operators?
The problem is not that it's not highlighted, but rather that they are not shown at all. The diamond operator alone (e.g. in `new ArrayList<>()`) is displayed.

**Comment by joshgoebel** [comment]
![Snap_2022-06-12_484x243](https://user-images.githubusercontent.com/6473/173236985-c29cf4cd-9bc2-4ee7-9935-25d55d584470.png)

Looks fine to me?

**Comment by joshgoebel** [comment]
Ping.

**Comment by illuminator3** [comment]
turns out it was an issue with my JS code... this is awkward, lol
