### ISSUE TITLE
(Kotlin) Retrieving value from map with class reference key

### ISSUE THREAD

**Issue by kkangmj** [highlightjs/highlight.js#3556]
**1. Which language seems to have the issue?** 

- Kotlin

<br>

**2. Describe the issue**

[Code block in markdown file]
<img width="494" alt="image" src="https://user-images.githubusercontent.com/52561963/170910035-7c73d9a5-ac73-4f43-8970-a16f4ff3f0b0.png">

[Actual Preview]
<img width="573" alt="image" src="https://user-images.githubusercontent.com/52561963/170910148-dafaa896-b93b-4ab6-b4cb-ca584640231b.png">

[What I've expected]
<img width="573" alt="170910148-dafaa896-b93b-4ab6-b4cb-ca584640231b (1)" src="https://user-images.githubusercontent.com/52561963/170910873-8edfb3f2-2e79-4469-9992-30fbee47f425.png">

<br>

**3. Are you using `highlight` or `highlightAuto`?**
- I'm not sure but this issue occurs in Visual Studio Code markdown preview.

<br>

**4. Sample Code to Reproduce**

````
```kotlin
val validators = mutableMapOf<KClass<*>, FieldValidator<*>>()
validators[String::class] = DefaultStringValidator
validators[Int::class] = DefaultIntValidator
```
````

**Comment by joshgoebel** [comment]
I can confirm your other two issues, _but not this one._  This is sloppy and not the kind of mistake we'd typically make - perhaps the VS Code plugin is interfering with our generated HTML somehow.    If you believe this is truly an issue with our library please submit a stand-alone JSFiddle that reproduces this issue with only our code and I've be happy to have a closer look.

Also possible this has been fixed already but not yet released.
