### ISSUE TITLE
(Kotlin) Parentheses close with annotation

### ISSUE THREAD

**Issue by kkangmj** [highlightjs/highlight.js#3558]
**1. Which language seems to have the issue?** 

- Kotlin

<br>

**2. Describe the issue**

[Actual Preview in VSCode]
![image](https://user-images.githubusercontent.com/52561963/173721584-54bc58f7-d0cb-4a6e-ab2a-27c98a8270f7.png)

[What I've expected]
![image](https://user-images.githubusercontent.com/52561963/173721799-56548fdf-3eb0-4469-84ca-4d7528069244.png)

<br>

**3. Are you using `highlight` or `highlightAuto`?**
- I'm not sure but this issue occurs in Visual Studio Code markdown preview.

<br>

**4. Sample Code to Reproduce**

````
```kotlin
@Deprecated("Use removeAt(index) instead.", ReplaceWith("removeAt(index)"))
fun remove(index: Int) { ... }
```
````

**Comment by joshgoebel** [comment]
bae95901
