### ISSUE TITLE
(language name) Short description of issue...

### ISSUE THREAD

**Issue by Alexey-T** [highlightjs/highlight.js#3562]
**Describe the issue**
Pascal code has HEX notation: `$ab`, but github site don't support this. 
Eg here
https://gitlab.com/freepascal.org/lazarus/lazarus/-/commit/f737b23e7c36fefb16b14600c8dc79979213d8e0

**Which language seems to have the issue?**
Pascal.

**Are you using `highlight` or `highlightAuto`?**
I use the GH site.

...

**Sample Code to Reproduce**
```
function UnicodeToISO_8859_7(Unicode: cardinal): integer;
begin
  case Unicode of
    0..$A0,
    $A3, $A6..$A9, $AB..$AE,
    $B0..$B3, $B7, $BB, $BD,
    $D2, $FF: Result:= Unicode;
    $2BD: Result:= $A1;
    $2BC: Result:= $A2;
    $20AC: Result:= $A4;
    $20AF: Result:= $A5;
    $37A: Result:= $AA;
    $2015: Result:= $AF;
    $384..$386, $388..$38A, $38C,
    $38E..$3A1, $3A3..$3CE: Result:= Unicode-($384-$B4);
    else Result:= -1;
  end;
end;
```

**Expected behavior**
Highlighted hex numbers.

**Additional context**
n/a.

**Comment by joshgoebel** [comment]
GitLab does not use Highlight.js for highlighting.   Highlight.js does include highligthing $ literals already.
