### ISSUE TITLE
(bash) Bash being recognized as SQL

### ISSUE THREAD

**Issue by gabrielcursino** [highlightjs/highlight.js#3574]
**Describe the issue**
Bash being recognized as SQL

**Which language seems to have the issue?**
Auto-detection

**Are you using `highlight` or `highlightAuto`?**
highlightAuto

**Sample Code to Reproduce**
```html
<!DOCTYPE html>
<html>
<head>
<title>Page Title</title>
<link rel="stylesheet"
      href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/11.5.1/styles/default.min.css">
<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/11.5.1/highlight.min.js"></script>
</head>
<body>
	<script>
    	var a = hljs.highlightAuto('wget -qO - https://www.mongodb.org/static/pgp/server-5.0.asc | sudo apt-key add -');
        var b = hljs.highlightAuto('echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/5.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-5.0.list');
        var c = hljs.highlightAuto('sudo apt update');
        var d = hljs.highlightAuto('sudo apt install mongodb-org');
        var e = hljs.highlightAuto('sudo systemctl start mongod');
        var f = hljs.highlightAuto('sudo systemctl enable mongod');
        
        console.log(a);
        console.log(b);
        console.log(c);
        console.log(d);
        console.log(e);
        console.log(f);
    </script>
</body>
</html>
```

**Expected behavior**
a- Bash, not SQL or second best CPP
b- Bash, ok!
c- Bash, not SQL
d- Bash, not Plain text, second best Bash, ok!
e- Bash, not SQL
f- Bash, ok!

**Comment by joshgoebel** [comment]
_Auto-detect is best effort not best in class._    It's a known issue that auto-detect fails (often spectacularly) on small snippets and this is to be expected.  If accuracy is needed, specify the language manually.

Closing as dup of #1213.

**Comment by joshgoebel** [comment]
v12 will change auto-detect greatly but I don't expect it to be lot better for tiny snippets like this... I'll see if I can't find somewhere in the docs to explain that it's not magic and often has poor outcomes.

**Comment by gabrielcursino** [comment]
Ok, i understand
