### ISSUE TITLE
Please make it work while editing the content

### ISSUE THREAD

**Issue by kopyl** [highlightjs/highlight.js#3583]
It's not currently possible to highlight the text on the fly.

If I enter [this](https://i.imgur.com/bXwUxvY.png) text into contenteditable <code> field, then run this code:

```
hljs.registerLanguage('terraform', window.hljsDefineTerraform);
hljs.highlightAll();
```

I get this result: https://i.imgur.com/pYe2l91.png

**Comment by kopyl** [comment]
The HTML becomes this after "highlighting":

https://i.imgur.com/Q6MQL30.jpg

**Comment by joshgoebel** [comment]
Live editing is not a supported use case.  There are already a plethora of great code editors out there, https://codemirror.net/ just to name one... this is not a category we're interested in competing in as the requirements are very different than what we do so well now.

It's possible this feature could be added using a 3rd party plugin and if so we'd encourage that approach and encourage you (or anyone else to explore it).  If someone wishes to publish and support a plugin to allow this type of thing we'd be more than happy to link to it.

https://highlightjs.readthedocs.io/en/latest/plugin-api.html
