### ISSUE TITLE
(CMake) Multi-line comments aren't supported properly

### ISSUE THREAD

**Issue by thatbakamono** [highlightjs/highlight.js#3591]
**Describe the issue**
Multi-line comments aren't supported properly, highlight.js seems to treat them like single-line comments which start similarly (`#`)

**Which language seems to have the issue?**
CMake

**Are you using `highlight` or `highlightAuto`?**

highlight

**Sample Code to Reproduce**
```html
<!DOCTYPE HTML>
<html>
	<head>
		<link rel="stylesheet" href="https://unpkg.com/@highlightjs/cdn-assets@11.6.0/styles/default.min.css">
		<script type="module">
			import hljs from 'https://unpkg.com/@highlightjs/cdn-assets@11.6.0/es/highlight.min.js';
			import cmake from 'https://unpkg.com/@highlightjs/cdn-assets@11.6.0/es/languages/cmake.min.js';

			hljs.registerLanguage('cmake', cmake);
			hljs.highlightAll();
		</script>
	</head>

	<body>
		<pre>
			<code class="language-cmake">
				#[[test
				test
				test]]
			</code>
		</pre>
	</body>
</html>
```

**Expected behavior**
Everything from `#[[` to `]]` is treated like a multi-line comment and grayed out

**Additional context**
![image](https://user-images.githubusercontent.com/13699966/182623099-978c96c2-671e-4d6f-ae85-099db66f2561.png)

**Comment by joshgoebel** [comment]
@thatbakamono Confirmed, we simply don't know anything about multi-line comments in the grammar currently... this is something that should be super easy to add (there are tons of multi-line comment examples to be found in other grammars)...

If you wanted to take a pass at submitting a PR to resolve this, it'd be very welcome.  I've tagged this appropriately.

**Comment by joshgoebel** [comment]
Would you like to make a pass at a PR?
