### ISSUE TITLE
Highlight.js strips whitespace in pre tag

### ISSUE THREAD

**Issue by Martmists-GH** [highlightjs/highlight.js#3593]
**Describe the issue/behavior that seems buggy**

When calling hljs.highlightElement, it strips all whitespace.

**Sample Code or Instructions to Reproduce**
```kotlin
fun `editor$transformer`() {  // called on page load
    document.querySelector<HTMLDivElement>(".md-editor")?.let { editor ->
        val input = editor.querySelector<HTMLTextAreaElement>(".md-editor-input")!!
        val code = editor.querySelector<HTMLElement>(".md-editor-code")!!

        input.addEventListener<InputEvent>("input") {
            var text = input.value
            if (text.isNotEmpty() && text.last() == '\n') {
                text += " "
            }
            println(text)
            code.innerText = text
            hljs.highlightElement(code)  // Removing this keeps whitespace as intended
            Unit
        }
    }
}
``` 
```html
            <div class="row md-editor">
                <div class="col-7">
                    <div class="content md-editor-out">
                    </div>
                </div>
                <div class="col-5">
                    <div class="content md-editor-wrapper">
                        <textarea class="md-editor-input" spellcheck="false"></textarea>
                        <pre class="md-editor-highlight" aria-hidden="true"><code class="md-editor-code language-markdown"></code></pre>
                    </div>
                </div>
            </div>
```

**Expected behavior**
Highlight.js correctly keeps spaces.

**Additional context**
Disabling highlighting preserves spaces.

**Comment by joshgoebel** [comment]
It's the APIs you are using. Use textContent instead of innerText.

**Comment by Martmists-GH** [comment]
using textContent preserves spaces but still strips newlines.
I also tried using innerHTML and replacing spaces with &nbsp; and newlines with <br />, both of which are stripped by highlight.js

**Comment by joshgoebel** [comment]
>using textContent preserves spaces but still strips newlines.

Please provide a jsfiddle demonstrating this and I will review.

**Comment by Martmists-GH** [comment]
Unfortunately JSFiddle does not support Kotlin/JS, so that's impossible...

**Comment by joshgoebel** [comment]
> using textContent preserves spaces but still strips newlines.

It does not when they are textual (`\n`)... as I stated earlier `<br>` is not supported or will need to be handled by you manually if you need to support `<br>`, ie replace then with `\n` before highlighting, etc...

**Comment by joshgoebel** [comment]
> JSFiddle does not support Kotlin/JS, so that's impossible...

We are a pure JS library, if there is a bug with the library itself then it should be possible to reproduce it with just JS (and JSFiddle) - no need for Kotlin.  But as mentioned, I think you're seeing the expected behavior here...

**Comment by joshgoebel** [comment]
Closing until a test JSFiddle case can be provided.  Right now this sounds like expected behavior that can be resolved by using clean text (no HTML) inside the block and using the `textContent` API exclusively. 

If you truly need BR, consider the use of a plugin: https://github.com/highlightjs/highlight.js/issues/2559
