### ISSUE TITLE
HTML language definition not included inside NPM package

### ISSUE THREAD

**Issue by jianmin-chen** [highlightjs/highlight.js#3594]
Version: `11.6.0`

I'm using Highlight.js with `lowlight` and neither has an HTML language definition, although I believe that Highlight.js has the HTML language definition in its CDN. I've checked inside `node_modules/highlight.js/lib/languages` and can't find an HTML language defintion. I'm not sure if this is a bug?

**Comment by joshgoebel** [comment]
xml

**Comment by jianmin-chen** [comment]
Would it not be more concise to have an HTML one?

**Comment by joshgoebel** [comment]
XML is already aliased to HTML if you check supported languages.
