### ISSUE TITLE
(language name) Instructions unclear for how to import library missing files

### ISSUE THREAD

**Issue by velara3** [highlightjs/highlight.js#3595]
**Describe the issue**
I am attempting to add syntax highlighting to a project in UXP (browser like environment) and I don't see many of the files mentioned in the install documentation. I don't see hightlight.min.js or styles/default.min.css. I don't have "lib/core" for individual languages. 

I downloaded the repository and trying to add this to a project. Do I include the entire repository or the src folder? I can't see how to import this project. 

**Which language seems to have the issue?**
Not this far

**Are you using `highlight` or `highlightAuto`?**
Not this far
...

**Sample Code to Reproduce**

//const {highlight} = require("highlight.js/src/highlight.js");
const hljs = require('highlight.js'); // Plugin Error: Module not found: "highlight.js". Parent module folder was: "/".

**Expected behavior**
Library included

**Additional context**

**Comment by velara3** [comment]
I think what I want is this: 

<img width="1009" alt="image" src="https://user-images.githubusercontent.com/1084127/183764438-85842e24-8a58-4436-986b-d144d02fa669.png">

Link https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@latest/build/

Is there a place to download this folder?

**Comment by joshgoebel** [comment]
https://github.com/highlightjs/cdn-release/tree/11-stable

**Comment by joshgoebel** [comment]
https://highlightjs.readthedocs.io/en/latest/building-testing.html
