### ISSUE TITLE
What is the style that is in Chrome Debugger tools and can it be added if not available? 

### ISSUE THREAD

**Issue by velara3** [highlightjs/highlight.js#3596]
What is the theme that is in the Chrome Debugger tools? Shown below: 
<img width="778" alt="image" src="https://user-images.githubusercontent.com/1084127/184012355-c058a5bf-e388-4d41-8573-2b185790da58.png">

You can also open Chrome based browser and open Web Inspector Tools or CMD + SHIFT + I to see the theme. 

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/1084127/184012658-a2bd0cf2-3a5a-406b-acee-a6d74d759eb0.png">

**Comment by joshgoebel** [comment]
If Highlight.js is powering Chrome's debugger view that would come as a big surprise to me... so I have no idea what theme they are using - probably one of their own devising.

We have a TON of existing themes though - did you flip thru them all to see if there was anything similar?  

New themes are always welcome: https://highlightjs.readthedocs.io/en/latest/theme-guide.html

**Comment by alystair** [comment]
They use CodeMirror, see https://github.com/ChromeDevTools/devtools-frontend/blob/9d96d182261c33bd3b9133f9ed9ca25138f327c6/front_end/ui/components/code_highlighter/CodeHighlighter.ts

**Comment by joshgoebel** [comment]
@alystair Thanks!
