### ISSUE TITLE
Weird glitch with contenteditable

### ISSUE THREAD

**Issue by CrazeXD** [highlightjs/highlight.js#3598]
**Describe the issue/behavior that seems buggy**

A code block that is `contenteditable` and highlighted is making new entered text go to the beginning of the div and in reverse.

**Sample Code or Instructions to Reproduce**

```
<script>hljs.highlightAll();</script>
<pre><code contenteditable id="editor">print("Hello world!")</code></pre>
<script>
document.getElementById("editor").addEventListener("input", function() {
document.querySelectorAll('pre code').forEach((el) => {
hljs.highlightElement(el);
}); }, false);
</script>
```

**Expected behavior**

Highlights text as you type it in.
**Additional context**

**Comment by joshgoebel** [comment]
We do not support `contenteditable` or using Highlight.js as a "live editor"... there are other tools that solve that problem very well, we're not trying to compete in that market.

I'm not saying it's impossible - I have no idea - but it's not something we support.
