### ISSUE TITLE
the text order is reversed when using `highlightElement()`. <code> with `contenteditable` attribute.

### ISSUE THREAD

**Issue by Laaouatni** [highlightjs/highlight.js#3607]
**Describe the issue/behavior that seems buggy**

❌ when typing it adds the text/code in **reverse** when typing.

![ezgif-4-883a8c0c6e](https://user-images.githubusercontent.com/87947051/187923182-dad55a41-bc8a-4196-be47-3c5847468bb1.gif)

**Sample Code or Instructions to Reproduce**

when using [`contendeditable`](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Editable_content) attribute in the `<code>` HTML tag element.

```html
<pre>
   <code contenteditable="true"></code>
</pre>
```

with an [`input`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/input_event) event listener 

```javascript
const code = document.querySelector("code");

code.addEventListener("input", () => {
    hljs.highlightElement(code);
    // other code logic (mostly saving to localStorage)
}
```

> like you saw in every typed letter I will add the highlight functionality, 
> <br> but seems that completely breaks the typing direction

> and yes, input events also work for not \<input\> tags if they have that attribute (contenteditable)
> <br> docs: https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/input_event

## source code:
https://jsfiddle.net/20zpL5bk/

----

- also another bug is that we can't go down the line break. (only if there is `hljs.highlightElement(code);`)

✅ here without `hljs.highlightElement(code);` is super fluid and can't do everything (but not syntax highlight):

![ezgif com-gif-maker (66)](https://user-images.githubusercontent.com/87947051/187930544-22dcaaa4-f533-43b1-b392-98c90bd103f5.gif)

> (how can I have fluid, normal writing with also syntax highlighting in real-time (input event)?
> <br> is my code wrong for some reason?)
----

**Expected behavior**

> ✅ how should be: `<div></div>` or `hello world`

> ❌ how it is now: `>vid/<>vid<` or `dlrow olleh`

**Additional context**

I tried to write the code in reverse myself manually `>vid/<dlrow olleh>vid<`,  and yes the highlighting works.
![image](https://user-images.githubusercontent.com/87947051/187928460-0b7c765b-c319-4ac3-87b1-f1d736002828.png)

but the direction is always the wrong way. (also deleting isn't possible)

- another interesting thing is if you copy and paste <kbd>(CTRL+V)</kbd> the correct code `<div>hello world</div>` it works fine. (but still remain in the same line, no multiple lines)

- also the cursor of the input doesn't move with the text but remains at the start

---------

## source code:
https://jsfiddle.net/20zpL5bk/

**Comment by Laaouatni** [comment]
solved one problem of the 2 ones:
-  the reversed text input.

-----

this is happen because every time that `input` event fires, 
<br>it will reset the `contenteditable` input.

by resetting, I mean that the caret position is set to `0`.

so technically, every time a letter is pressed it is added at the start and not at the end.

like you see here:
![187923182-dad55a41-bc8a-4196-be47-3c5847468bb1](https://user-images.githubusercontent.com/87947051/187957212-07fa6dbf-7d75-4992-a54b-3f2c775f8d5a.gif)

-----

so the solution is to move the cursor to the end.

this is the solution: https://stackoverflow.com/a/69727327/17716837

```javascript
function setEndOfContenteditable(code) {
    let sel = window.getSelection()
    sel.selectAllChildren(code)
    sel.collapseToEnd()
}
```

and adding this functionality to the end of the input event 

```javascript
code.addEventListener("input", () => {
    hljs.highlightElement(code);
    setEndOfContenteditable(code);
});
```

-------

however, still wondering why this bug happens with the `hljs` method and without it not happen.

**Comment by joshgoebel** [comment]
**Guess:** Swapping out the content is resetting the cursor (to the beginning)... so you'd need to save and restore the cursor position "properly" before/after calling `highlightElement`.  Just a guess.

_This isn't something we officially support though_ - it usually leads to all sorts of glitches, like the one you're seeing - but I'll leave this open a a little while to see if anyone else wants to jump in and help you.

**Comment by Laaouatni** [comment]
@joshgoebel thanks
