### ISSUE TITLE
Support or guidance for Vue SFC "Language" needed.

### ISSUE THREAD

**Issue by suterma** [highlightjs/highlight.js#3614]
I have read https://highlightjs.readthedocs.io/en/latest/language-requests.html and it's a somewhat special but I guess common issue, so I raise it here, as it mainly concerns Vue users.

**How to highlight code for a Vue Single File Component (SFC)?**

This is quite tricky because it can contain up to three languages

 - HTML as the outer shell
 - Javascript or Typescript in the script section
 - CSS in the style section

I was looking for a "Vue" or "SFC" language with highlight.js, but did not find one. So I wonder how best represent an SFC component, without splitting the code display.

Even if there is no plan or possibility to implement such a mixed-language, I would suggest addressing this issue and offering guidance somewhere. I searched quite around and found no mention of this in the official documentation.

**Comment by joshgoebel** [comment]
I moved this as a question about a Vue grammar really has no relation to our Vue component.

---

This is easy.  See https://highlightjs.readthedocs.io/en/latest/mode-reference.html and `sublanguage`.  Our `xml` grammar is a great example as it can include bounded CSS, JavaScript, etc... So you'd just need a rule to recognize each section and sublanguage them for the individual highlighting.

**Comment by joshgoebel** [comment]
Were you planning to work on a 3rd party grammar module for Vue SFC?

**Comment by suterma** [comment]
I am not. I was trying to write up some examples for my "Vue-peaks" SFC component and was wondering what the best/simplest/most common way was to achieve that. Here's the current public state of my docs, if you are interested, with the code examples currently still boring: https://suterma.github.io/vue-peaks/

**Comment by joshgoebel** [comment]
I wonder did you try highlighting as xml?

**Comment by suterma** [comment]
Sort of. Here's my main.ts file: https://github.com/suterma/vue-peaks/blob/94dc78eaf54dc8711e1418719efd05054df3ece7/src/main.ts

Actually, I have not yet been in the need to show a full SFC all at once, so I helped myself out with parts having the appropriate language set. I opened this issue because I believe many would be in a similar position and would benefit from some general guidance.

I had a brief look into the link with the sublanguage explained. However, without much time and dedication to get into this right now, I did not grasp it, and I will stick to what I have so far for now.

**Comment by joshgoebel** [comment]
Vue SFC looks a lot like XML to me. Our existing xml grammar may just work out of the box. You'll have to try it.

**Comment by suterma** [comment]
Basically, it's HTML, which is also XML (mostly...) :-). Using the XML language works for the most part for me (locally on my machine), but then it seems to mess up the specific script tag which is used with the Vue3 composition API:

    <script setup lang='ts'>
    // -> here: typescript content which is considered plain text
    </script>

The script content is not recognized as typescript, but just as a single text blob. This could be some kind of "bug" or missing detection.

The following screenshot shows the situation:
![Screenshot from 2022-09-11 22-19-47](https://user-images.githubusercontent.com/11473920/189547326-e10bc6d8-277e-4bfe-9bba-6fc52c74109b.png)

**Comment by joshgoebel** [comment]
Are you using a version of HLJS with `javascript` built-in/loaded?

**Comment by joshgoebel** [comment]
>  so I guess no languages are imported by default. I have the main.ts currently like this:

You'll have to use `javascript` with `xml`... TypeScript isn't valid in HTML - it only supports JavaScript inside `<script>`... if you need Typescript you'll need to create your own custom grammar as I was suggesting earlier.

**Comment by joshgoebel** [comment]
Yes, but it doesn't look like it's actively maintained - but you could probably hack it to get it to work - it's about what I expected.

> Maybe this is just missing by mistake or just was forgotten?

If someone was to bring it up to our modern build standards we could most definitely add it to the list.

**Comment by joshgoebel** [comment]
Closing as that plugin looks like exactly what you need.

**Comment by suterma** [comment]
> If someone was to bring it up to our modern build standards we could most definitely add it to the list.

This sounds like a worthwhile investment. I will put it on my list. However, there are other projects on top still.
