### ISSUE TITLE
Answer: For background processing, use a web worker...

### ISSUE THREAD

**Issue by velara3** [highlightjs/highlight.js#3616]
**Is your request related to a specific problem you're having?**
I would like to show users a progress bar when there is a lot of code that is being processed. 

**The solution you'd prefer / feature you'd like to see added...**
I'd like see events dispatched for progress. 

- start event
- progress events
- complete event

**Any alternative solutions you considered...**
I don't see any workarounds at this point

**Additional context...*
The HTML page that I'm highlighting can be significant. 

Here is my example code: 

```
// current
var htmlValue = hljs.highlight(htmlOutput, {language: 'html'}).value;
htmlField.innerHTML = event.htmlValue;

// using events 
hljs.addEventListener("start", updateUI);
hljs.addEventListener("progress", updateUI);
hljs.addEventListener("complete", updateUI);

function updateUI(event) {
    if (event.type=="start") {
       // start progress bar
       progressbar.style.width = 0;
    }
    if (event.type=="progress") {
       // update progress bar
       progressbar.style.width = event.progress + "%";
    }
    if (event.type=="complete") {
       // update html field
      htmlField.innerHTML = event.htmlValue;
    }
}
```

**Comment by joshgoebel** [comment]
IMHO the correct solution here is to use HLJS in a background worker and just do the work on another thread... (to avoid blocking the main UI)... callbacks like this make no sense when the code in CPU bound... _your UI would never get updated because the main browser thread would still be blocked the whole time with JS._

https://github.com/highlightjs/highlight.js#using-web-workers

**Comment by joshgoebel** [comment]
You could probably hack in support for % events (for your unique use case) with the background worker, or just use an indeterminate progress bar - even large documents shouldn't take THAT long to highlight on most systems.

**Comment by joshgoebel** [comment]
> The HTML page that I'm highlighting can be significant.

Detailed stats size / timing / etc would be appreciated just for my curiosity.

**Comment by joshgoebel** [comment]
I should also point out our plug-in API already DOES support start/finish callbacks, though that doesn't address the middle part of your question.
