### ISSUE TITLE
Last line not getting tokenized after upgrade of highlight.js

### ISSUE THREAD

**Issue by BWotka** [highlightjs/highlight.js#3624]
**Describe the issue/behavior that seems buggy**

The last line of code does not get highlighted correctly.
The issue persists in at least Java and Python, I suspect the issue will appear in any code.
I suspect the API has changed since the code I'm working with was written.

**Sample Code or Instructions to Reproduce**

```
let tokenized = hljs.highlight(codeContent, {language}).value;
this.note = this.note.replace('{content}', '<pre>' + tokenized + '</pre>');
```
The end of note later looks like this:
```
<span class="hljs-built_in">print</span>(<span class="hljs-string">&quot;Hallo Welt&quot;</span>)
x = <span class="hljs-built_in">input</span>(<span class="hljs-string">&quot;Mach mal&quot;</span>)
doSomething()
</pre></body></html>
```
With everything except the last line being formatted.

**Expected behavior**

The last line should be parsed into at least one span.
**Additional context**

I am updating a typescript program which used highlight.js 9.10.0 before and now uses 11.6.0.
I looked in the breaking changes but could not figure out what was going wrong.

**Comment by joshgoebel** [comment]
> The last line should be parsed into at least one span.

Why?

**Comment by BWotka** [comment]
Because this:
![image](https://user-images.githubusercontent.com/39100641/190387049-931dcbb9-6191-4ab9-ae94-701c5d60a1ec.png)
is what the input is.
Don't you agree that the last line should be parsed?

**Comment by joshgoebel** [comment]
No. Many grammars don't highlight function calls.  Try different content, like adding a keyword.

**Comment by BWotka** [comment]
Tried it, it was indeed as you said. Is there any way I could add some flag/span to apply custom rendering for these cases?
My extension currently works by replacing stuff in the tags, but the function calls don't have any tags.
The other option would be to look for anything not formatted by spans and create a custom default span.

**Comment by joshgoebel** [comment]
There is no guarantee of highlighting on every line, it just depends on the source code.

It's not clear to me at all what you're trying to accomplish or what your plugin hopes to do.

**Comment by BWotka** [comment]
My plugin exports code to Microsoft OneNote with highlighting. 
This is what is currently being sent to OneNote:
![image](https://user-images.githubusercontent.com/39100641/190478594-afc1c30a-1672-45f9-a346-8f1dc224c30d.png)
The line has nether the correct font nor the correct size.
My goal would be to have a span around everything, so I could set those values by string.replace() as I do for all the other spans.
The only way I can think of right now is having a regex that finds /w between a closing and an opening span, but not between an opening and a closing span. If not every line gets a span, that is probably what I will do.
I will close this issue since the behavior is already correct.

**Comment by BWotka** [comment]
This actually worked perfectly, thank you for the answer and the advice.
