### ISSUE TITLE
(request org repo) highlightjs-func

### ISSUE THREAD

**Issue by sobolevn** [highlightjs/highlight.js#3629]
I would like to request the creation of a `highlightjs-[my-grammar]` repository for my 3rd party grammar.

- [x] I have an existing personal repository ready to go

### Metadata

- Grammar Name: FunC
- Link to repo: https://github.com/sobolevn/highlightjs-func

### Requirements

- [x] I've read the [language Contributor Checklist](https://highlightjs.readthedocs.io/en/latest/language-contribution.html)
- [x] I've read the [Language Contribution Guide](https://github.com/highlightjs/highlight.js/blob/main/extra/3RD_PARTY_QUICK_START.md)
- [x] I'm currently willing to support and maintain this grammar over time
- [x] That repo includes a `dist` folder with CDN-ready `CJS` and `ESM` builds
- [x] That `README.md` includes examples of simple web usage
- [x] That `README.md` includes examples of Node.js usage

### Afterwards

Submit a PR that:

- [x] adds mention of your new language to `CHANGES.md`
- [x] updates `SUPPORTED_LANGUAGES.md` in the main library

### Personal feedback

Thanks a lot for making this such an easy process! 
Everything is documented, everything has examples.
Great work!

**Comment by Hiyorimi** [comment]
👀

**Comment by joshgoebel** [comment]
**Sure.**

Some quick thoughts:

- `puncuation` typo
- Use `scope`, not `className`, class name is deprecated
- `variable.constant` is meant to be applied to the names of variables, not the keywords... `const` and `global` are likely just `keyword`s
- you don't have to quote keynames in JS, this isn't JSON
- I'd suggest removing the 10 relevance hinting

**Comment by joshgoebel** [comment]
https://github.com/highlightjs/highlightjs-func

**Comment by sobolevn** [comment]
Thanks!

> you don't have to quote keynames in JS, this isn't JSON

This is our styleguide :)
https://github.com/wemake-services/wemake-frontend-styleguide

**Comment by joshgoebel** [comment]
If that's just your style we'll just agree to disagree. 🙂. Was just mentioning it in case you didn't know.
