### ISSUE TITLE
Is there a way to reuse Highlight.js theme in the react-prism library

### ISSUE THREAD

**Issue by 1alexvash** [highlightjs/highlight.js#3632]
I mean, I can't just bluntly copy CSS, as some of those style classes are different between libraries

**Comment by joshgoebel** [comment]
You might see the whole discussion in #3619 which is related, but right now if you like one of our styles and wanted to use it with an entirely different engine - yes you'd have to do the work to hand convert it to that engine's desired CSS classes.
