### ISSUE TITLE
highlights.js for offline 

### ISSUE THREAD

**Issue by Neodevils** [highlightjs/highlight.js#3633]
###### Hello, there wasn't a discussion tab so I had to make a new issue.

Is there any way to use highlights.js for offline? I want to use GitHub-Dark theme for my editor while it is offline.

**Comment by joshgoebel** [comment]
Not sure what you are asking. If you have the JS loaded (perhaps cached or local on disk, etc) it should work, you don't need to be online.

**Comment by Neodevils** [comment]
> Not sure what you are asking. If you have the JS loaded (perhaps cached or local on disk, etc) it should work, you don't need to be online.

It is not stored on my phone's store. Whenever I try to run it while offline, it does not show up as highlighted.

**Comment by joshgoebel** [comment]
You'd need to embed it in your app or HTML page?  Still not completely sure what your asking.

**Comment by Neodevils** [comment]
> You'd need to embed it in your app or HTML page? Still not completely sure what your asking.

**HTML page. I'll run my local file and syntax highlight will work even there's no internet connection.**

That's what I am trying to do.

**Comment by joshgoebel** [comment]
If the JS is local (filesystem, etc) or built into the webpage itself then it should work just fine.

**Comment by Neodevils** [comment]
> If the JS is local (filesystem, etc) or built into the webpage itself then it should work just fine.

I just did it somehow. Thank you.
