### ISSUE TITLE
Webpack error: cannot dynamically import styles

### ISSUE THREAD

**Issue by thet** [highlightjs/highlight.js#3634]
**Describe the issue/behavior that seems buggy**
When trying to dynamically import a theme, webpack fails with an error saying that `./styles` is not in the exported field of package.json.

**Sample Code or Instructions to Reproduce**

With a webpack setup try to import a style in an async methods like so:

```
    test() {
        const theme = "github";
        import(`highlight.js/styles/${theme}.css`);
    }
```

Webpack fails with this error:
```
ERROR in ./src/pat/syntax-highlight/syntax-highlight.js 35:4-46
Module not found: Error: Package path ./styles is not exported from package /home/_thet/data/dev/syslab/REPOS/patternslib/Patterns/node_modules/highlight.js (see exports field in /home/_thet/data/dev/syslab/REPOS/patternslib/Patterns/node_modules/highlight.js/package.json)
 @ ./src/patterns.js 54:0-49
 @ ./src/index.js 5:0-20

webpack 5.74.0 compiled with 1 error in 769 ms
```

This does work though:
```
    test() {
        import(`highlight.js/styles/github.css`);
    }
```

Removing the `exports` field in `package.json` also lets me to import the styles dynamically.

**Expected behavior**
I expect to be able to import anything within highlight.js dynamically.

**Comment by thet** [comment]
Same goes for dynamically importing languages:
```
async function test() {
    const language = "xml";
    const lang = (await import(`highlight.js/lib/languages/${language}`)).default;
}
```

Here webpack fails with:
```

WARNING in ./src/pat/syntax-highlight/syntax-highlight.js 71:37-86
Module not found: Error: Package path ./lib/languages is not exported from package /home/_thet/data/dev/syslab/REPOS/patternslib/Patterns/node_modules/highlight.js (see exports field in /home/_thet/data/dev/syslab/REPOS/patternslib/Patterns/node_modules/highlight.js/package.json)
 @ ./src/patterns.js 54:0-49
 @ ./src/index.js 5:0-20

webpack 5.74.0 compiled with 1 warning in 15060 ms

```

**Comment by joshgoebel** [comment]
I'm current considering this a bug in webpack (until someone can link me to an issue filed against webpack that says otherwise).  _We already do wildcard exports for these paths._. It seems so far to only be webpack can't figure it out when the paths are dynamic...

https://github.com/highlightjs/highlight.js/blob/main/tools/build_node.js#L104_

Closing as a dup of #3384.   Please file an issue against webpack and link to this issue.

**Comment by thet** [comment]
Thanks for pointing that out!
