### ISSUE TITLE
[UI/UX] Dropdown for language and style.

### ISSUE THREAD

**Issue by adsingh14** [highlightjs/highlight.js#3640]
**Describe the issue/behavior that seems buggy**

On homepage snippet box [^1], both language and style links should have dropdown. It's not a bug but inconvenient. 

**Sample Code or Instructions to Reproduce**

1. Visit https://highlightjs.org
2. Click on either language or style
3. It change language/style instead of showing dropdown

**Expected behavior**

It would be great to have a dropdown button for both options. 

**Additional context**

[^1]: ![image](https://user-images.githubusercontent.com/35252877/196739892-5b71c77e-0bbe-4e66-9576-869cf9719386.png)

**Comment by adsingh14** [comment]
On second thought, adding a dropdown button on the right side of it could also a better option.  I'm interested to contribute.

**Comment by joshgoebel** [comment]
Please see #3611.  Any feedback on the website should be addressed to the new version, not the old.
