### ISSUE TITLE
Cloudflare isn't serving ES version

### ISSUE THREAD

**Issue by russellbeattie** [highlightjs/highlight.js#3658]
**Describe the issue/behavior that seems buggy**

In the documentation, you have this example: 

`import hljs from 'https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.6.0/es/highlight.min.js';`

However, that URL is currently returning a 404.

**Comment by joshgoebel** [comment]
https://github.com/cdnjs/packages/pull/1395

**Comment by joshgoebel** [comment]
The next release will include these files.  I'll see if I can get to it in the next few days before the holidays.

**Comment by joshgoebel** [comment]
11.7.0 includes `es` folders.  Evidently it's not possible to go back and fix this for prior releases.
