### ISSUE TITLE
(python) `->` deemed an illegal char combination

### ISSUE THREAD

**Issue by Keyacom** [highlightjs/highlight.js#3659]
**Describe the issue**

Python uses `->`, but its definition file specifies `->` as an illegal character combination outside of strings.

**Which language seems to have the issue?**

`python`

**Are you using `highlight` or `highlightAuto`?**

This is only reproducible if `highlightAuto` is used.

**Sample Code to Reproduce**

```py
# How `getattr` works (approximately)
from typing import Any
def getattr(obj, name, default=None, /) -> Any:
    return type(obj).mro()[0].__getattr__(obj, name, default)
```

https://jsfiddle.net/Keyacom/guL8xaw5/8/

**Expected behavior**

The expected behavior is that `->` is recognized as valid Python syntax. It's used in function definitions for type hints of the function's return type. This only affects language autodetection.

**Additional context**

**Comment by joshgoebel** [comment]
Curious: Is `->` a recent addition to Python?

**Comment by Keyacom** [comment]
> Curious: Is `->` a recent addition to Python?

It's not that recent, it was added in Python 3.0. The semantics were left undefined until 3.5.

**Comment by joshgoebel** [comment]
Interesting in making a quick PR for this one?
