### ISSUE TITLE
(vala) Recognize also vapi files

### ISSUE THREAD

**Issue by lw64** [highlightjs/highlight.js#3662]
**Describe the issue**
Currently `.vapi` files don*t get highlighted.

**Expected behavior**
Recognize also `.vapi` files as vala files and highlight them accordingly.

**Comment by joshgoebel** [comment]
Could you please elaborate on your request? We do not highlight "file types" nor do we look at extensions - we deal only in the raw text code - we have no idea what the filename or extension or something is.

**Comment by joshgoebel** [comment]
Closing due to lack of response from requestor.

**Comment by lw64** [comment]
Sorry for not responding. I actually wanted to close the issue as it doesn't make sense, but forgot about it. Thank tou!
