### ISSUE TITLE
(powershell) Nested comments are not recognized

### ISSUE THREAD

**Issue by Keyacom** [highlightjs/highlight.js#3663]
**Describe the issue**

PowerShell supports nested comments, but Highlight.js seems to be unaware of that.

**Which language seems to have the issue?**

`powershell`

**Are you using `highlight` or `highlightAuto`?**

This is reproducible with both methods, but I used `highlight`.

**Sample Code to Reproduce**

```ps1
<# Some <# nested #> comment #> Get-ChildItem C:\Windows\Fonts -Recurse | 
Where -Match ".*\.fon" | ForEach-Object { Remove-Item $_.name }
# short form
ls \Windows\Fonts -rec | ? -m ".*\.fon" | % { rm $_.name }
```

https://jsfiddle.net/Keyacom/qvm7p3bx/14/

**Expected behavior**

The part `comment #>` should also be highlighted as a comment, but `Get-ChildItem C:\Windows\Fonts -Recurse |` should not.

**Additional context**

Even GitHub's syntax highlighter gets this wrong, but another syntax highlighting library that's used in some places on the Web (and written in Python), Pygments, gets this right.

**Comment by joshgoebel** [comment]
Confirm, would you be interested in working on a PR for this?

**Comment by Keyacom** [comment]
I was fooled by the fact `#>` can both start an inline comment thanks to `#`, and end a multiline comment, but as it turns out, comments cannot be nested in PowerShell.
