### ISSUE TITLE
(sql) code snippet parameter rendering problem

### ISSUE THREAD

**Issue by HaoDong108** [highlightjs/highlight.js#3664]
![屏幕截图 2022-11-17 092810](https://user-images.githubusercontent.com/60975172/202331998-f56fbdac-63df-4f75-a0c4-6f4156f95452.png)

**Comment by HaoDong108** [comment]
Highlight.js v11.6.0 (git: bed790f3f3)

**Comment by joshgoebel** [comment]
Looks like variable regex needs `_` added to it.  Would you want to help out with a PR to fix this?

**Comment by joshgoebel** [comment]
Resolved with 2fa5786c
