### ISSUE TITLE
C++ : missing 'cpp' alias

### ISSUE THREAD

**Issue by GuillaumeDua** [highlightjs/highlight.js#3671]
**Describe the issue/behavior that seems buggy**

While `hljs.getLanguage('cpp')` works as intended, the result's value `.aliases` member-variable does not contains the `'cpp'` alias by default.

**Sample Code or Instructions to Reproduce**

```js
hljs.getLanguage('cpp').name
> "C++"
hljs.getLanguage('cpp').aliases
> Array(7) [ "cc", "c++", "h++", "hpp", "hh", "hxx", "cxx" ]
```

**Expected behavior**

```js
hljs.getLanguage('cpp').aliases
> Array(8) [ "cc", "cpp", "c++", "h++", "hpp", "hh", "hxx", "cxx" ]
//                          ^^^
```

**Additional context**

Also, providing a way to expose using hljs.getLanguage the following information would be convenient :

- The matching `hljs-<language_name>` style class

Such as :

```js
hljs.getLanguage('c++).style_className
> 'language-cpp'
```

**Comment by joshgoebel** [comment]
This is correct behavior. `cpp` is the canonical name, NOT an alias.

**Comment by joshgoebel** [comment]
> The matching hljs-<language_name> style class

What is the use case where you don't already know this and instead need to gather it only from the alias?  Typically this is soothing you hard-code in your CSS once and then never change.

**Comment by GuillaumeDua** [comment]
> This is correct behavior. `cpp` is the canonical name, it is NOT an alias.

Is there a way to retrieve such information ?

> What is the use case where you don't already know this and instead need to gather it only from the alias? Typically this is soothing you hard-code in your CSS once and then never change.

Perhaps I misunderstood some part of the documentation.  
I'm looking for a way to choose/force which language `hljs.highlightElement(e)` will select on a particular element,  
so it avoids using the wrong languages.

For instance, some of my `cpp` code tends to be highlighted with `c`, or even more often `bash` `hljs-<name>` class;  
which is the behavior I'm willing to avoid.

**Comment by joshgoebel** [comment]
`listLanguages` will give you the list of canonical names...

> I'm looking for a way to choose/force which language 

You don't need the canonical name for that, any of the aliases will work just as well.  You'll need to use `hightlightAuto` and do the DOM manipulation yourself afterwards if you want a way to better control the auto-detection. Or see `configure` which has a `languages` option, but that will affect the entire library, not just `highlightElement`.

https://highlightjs.readthedocs.io/en/latest/api.html#configure

**Comment by GuillaumeDua** [comment]
Thanks for the infos.

Then why does `hljs.getLanguage(...).name` does not return the canonical name (for cpp for instance, it returns `C++`) ?

**Comment by joshgoebel** [comment]
I should have said canonical id, ie the filename in source.  .name is the "pretty name" for knowledge or display purposes.

**Comment by joshgoebel** [comment]
You'd have to open a second issue for the other thing if indeed that's valid C++ now.

**Comment by joshgoebel** [comment]
> It's up to you, only my opinion.

Technically that would possibly be a breaking change (change in behavior), so it'd have to wait for v12.  Without anyone else asking for this though I'm inclined to just leave the existing behavior - as it's easy enough to find the "full list" programmatically if you truly need to.
