### ISSUE TITLE
[Request] Alternate output formats, including SVG, images

### ISSUE THREAD

**Issue by getify** [highlightjs/highlight.js#3682]
**Is your request related to a specific problem you're having?**

I'd like to be able to produce syntax highlighting of code that is able to display in places where custom html/css is not allowed... for example inside of markdown on github. Additionally: inside PDFs, in comments on reddit/stackoverflow, etc.

As such, it'd be preferable if there was an alternate output mode besides the default.

**The solution you'd prefer / feature you'd like to see added...**

If this library could produce SVG (with all the colors/styling included inline), that SVG output could be sent to a `.svg` file, which could then be displayed in these places. For markdown display, the solution I've seen in other places is including the image itself and then right below it, a `<details>` element (collapsed by default) with a code block in it, to be able to easily copy-paste the code that was rendered in the image.

Additionally, an image rendering library could be included/used to produce a .PNG file equivalent of the syntax highlighting. Again, the `<details>` trick for markdown makes the text still accessible/copy-paste'able.

**Any alternative solutions you considered...**

Converting the HTML/CSS to SVG is possible, but it seems to be rather messy in my early experiments.

**Additional context...**

I have designed a new programming language, and written my own tokenizer logic (in JS). Right now, I can output HTML/CSS for syntax highlighting. But I don't yet have a way for my syntax highlighting to be shown on markdown pages/etc.

While I was exploring just building this SVG output capability into my own tool, I decided to explore if perhaps this could just be something that the popular syntax highlighter tools (HighlightJS, PrismJS) could support.

That way, I could use the same tool/workflow for producing syntax highlighting of *my* language, but other languages as well (JS, Haskell, etc). This would be useful in showing people comparisons of the same code snippet equivalent in various languages.

I searched and didn't find anyone talking about this type of alternate output. Apologies if I missed prior support/discussions of such capabilities.

**Comment by joshgoebel** [comment]
This request sounds out of scope for the core library, but it could make a great add-on or plugin.  If you wanted to explore you might want to check out the (now private) `__emitter` configuration API, allowing you to replace our emitter with your own. https://github.com/highlightjs/highlight.js/blob/main/src/lib/token_tree.js#L123. The API is trivial.

All you get is a tagged/scoped token stream though... you'd still have to render the actual SVG - plus load and parse CSS to gain access to color schemes, etc...

There are plans to make the emitter API public in the next release as well as to allow creating new instances of HLJS... that is all one would need to build an add-on that used our parsing engine to output any number of other formats easily...


> Converting the HTML/CSS to SVG is possible, but it seems to be rather messy in my early experiments.

I bet this is far simpler. What's that really nice site that does this already? Is it OSS?

**Comment by getify** [comment]
Just curious: can you explain why html/css output is considered "core" scope of this library, but svg/css output wouldn't be? I think an argument could be made that svg/css might even be the preferable output for a library like this (since it works in html fine in almost every place html/css are rendered, but is perhaps more universal than html/css).

**Comment by joshgoebel** [comment]
Largely, history (our historical scope).  And my opinion/experience as maintainer.  Any new features need to be something we can feasibly maintain across time with our very tiny core team.  Typically any feature that's trivial to add as a plug-in (outside of core) does not belong in core.  For a long time now our goal has been making the library easier to *extend* and keeping the core as small as possible. (see long-lived thread on Plugin culture).  

_So the first step **in any case** would be for someone to build this as a plugin._  If said plugin was simple enough, desired by a majority of users, and looked like it would be easy to maintain then perhaps we would consider it for core at that time.

**Comment by joshgoebel** [comment]
> svg/css

I did forget momentarily that CSS can target SVG... so that makes one part a bit simpler... so you'd just need a custom SVG renderer/emitter... But at that point I'm not sure how that's better than HTML/CSS... seems like it'd just be a lot larger (much more markup for the same ultimate result).

**Comment by getify** [comment]
> But at that point I'm not sure how that's better than HTML/CSS...

I'm not sure it's absolutely true that there would be a lot more markup, but... here's several points off to consider:

1. SVG (with inline styles/css) can be put into an image file and loaded via <img> tag or via `background-image` in CSS for any elements. Again, SVG markup can be used in a lot of other places than HTML (PDFs, slide decks, etc), so SVG is more flexible/useful.

2. To the point of (1), since SVG is an image format, you could import the syntax highlighting "file" into a vector graphics program, and then apply visual augmentation (circling expressions, blurring, highlighting, etc). I often those sorts of visual things on top of PNG image screenshots of highlighted code, but it'd be a LOT nicer to be able to do so with the direct 

3. SVG can embed fonts as vector shapes, so in some cases a syntax highlighting along with a custom font could be more portable than HTML/CSS requiring an external font file.

4. I've read before that in some cases, SVG is easier for browsers to optimize the rendering performance (like via hardware acceleration). I don't have a lot of details on that, but it's worth at least looking into whether displaying a huge syntax-highlighted code file in a page via SVG might perform better than the equivalent in HTML.

**Comment by lublak** [comment]
@getify i was also searching for a nodejs module which supports svg output (pdf export).
I found https://github.com/shikijs/shiki
It's not that well known and I don't know how widespread it is.
But I think it should be able to do a lot. :)
highlightjs of course has the advantage with auto detection and would also prefer it. But currently I will try shiki for now.

**Comment by lublak** [comment]
@joshgoebel when will the new release with the public api avaible?

**Comment by joshgoebel** [comment]
Uncertain, but for testing purposes everything necessary is in the current build. They key is simply named `__emitter` vs `emitter` to denote it's privateness.

**Comment by joshgoebel** [comment]
Closing for now, recommend that this functionality be added via a plugin rather than core.
