### ISSUE TITLE
Add `python3` alias for `python`

### ISSUE THREAD

**Issue by rafrafek** [highlightjs/highlight.js#3685]
I think it would be nice to add `python3` alias for `python`.

**Comment by KuryKat** [comment]
but then what if someone writes a Python 2 code inside it? would it break? XD

Jokes aside, I understand the idea but I don't think would be really necessary, since is just a matter of getting used to just writing "py" or "python"

**Comment by rafrafek** [comment]
I have markdown documents with ` ```python3 ` blocks and it works in GitHub.

**Comment by joshgoebel** [comment]
I think python is python... we don't have multiple versions of parsers/highlighters and don't desire to.  If you want another alias, it's trivial to add one for `python3`:

```js
hl's.registerAliases("python3", {languageName: "python"})
```

https://highlightjs.readthedocs.io/en/latest/api.html#registeraliases
