### ISSUE TITLE
(diff) Support diff-highlight for patches

### ISSUE THREAD

**Issue by Qeole** [highlightjs/highlight.js#3687]
I use the library to colour patches, with the `diff` language. This renders updated/added lines in green, deleted lines in red. However, I would love the library to be able to highlight the precise part of the line that changes. Here is an illustration (not involving the library: calling `git diff` without and with [delta](https://github.com/dandavison/delta), which emulates [diff-highlight](https://github.com/git/git/tree/master/contrib/diff-highlight)):

![image](https://user-images.githubusercontent.com/8324081/211297719-dfa5f322-68c7-45bb-93d7-9f32ba9eef53.png)

Note the accent on the background colour.
Another example is GitHub doing the same when looking at the changes in a commit.

As far as I know, there is nothing of the like in highlight.js at the moment.

**Comment by joshgoebel** [comment]
This is out of scope.  We are a highlighter, not a diff utility.  We highlight keywords (and patterns) that are *known in advance*.  We do not analyze a line to see how it compares to the previous/next and then highlight based on that - that is what a good diff tool does.

Now if you had a diff format that included formatting for line changes:

```diff
- old line
+ new line ++adds more text++
```

Such that the literal text added was `adds more text`, then one could imagine a grammar that highlighted everything in-between sets of `++` with bright green, and then we'd be highlighting... but that's not what you're asking for...

**Comment by Qeole** [comment]
I suspected so, thought I would ask just in case. Thanks for taking the time to reply!

One more question if you don't mind, do you know if this is something that I could possibly implement as a plugin (`hljs.addPlugin()`)? I haven't experimented with those yet. I'm thinking of running the algorithmic part to detect the changes on the line and mark them after highlighting additions/deletions, to add emphasis on the relevant chunks?
