### ISSUE TITLE
[Violation] 'DOMContentLoaded' handler took 167ms          highlight.min.js:280

### ISSUE THREAD

**Issue by y377** [highlightjs/highlight.js#3688]
**Describe the issue/behavior that seems buggy**

Originally used well, today I added an anchor point JS library and a bootstrap-IE11 compatible JS library, there is this problem

**Sample Code or Instructions to Reproduce**
#### note:  _[Violation] 'DOMContentLoaded' handler took 167ms          highlight.min.js:280_
> 
![DL@6PWKVZ}RFY(%R`4}W8LS](https://user-images.githubusercontent.com/58632405/211556283-ebd00674-c409-425a-9ee8-3b58b152b797.png)

#### Excluded JS code
```js
    <script nomodule crossorigin="anonymous" src="https://polyfill.io/v3/polyfill.min.js?features=default%2CNumber.parseInt%2CNumber.parseFloat%2CArray.prototype.find%2CArray.prototype.includes">
    </script>
    <script nomodule>
    window.MSInputMethodContext && document.documentMode && document.write('<script src="https://cdn.jsdelivr.net/combine/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js,npm/ie11-custom-properties@4,npm/element-qsa-scope@1"><\/script>');
    </script>
```
_and_
```js
document.addEventListener("scroll", function(e) {
    const scrollTop = document.documentElement.scrollTop || document.body.scrollTop;
    const scrollHeight = document.documentElement.scrollHeight;
    const clientHeight = document.documentElement.clientHeight;
    const myJd = document.getElementById("read_pro_inner");

    myJd.style.width = +(scrollTop / (scrollHeight - clientHeight)).toFixed(2) * 100 + "%";
    // myJd.insertAdjacentHTML('beforeend', myJd.style.width);
    myJd.textContent = myJd.style.width;
});
```
**Expected behavior**

Understand the news
**Additional context**

#### Problem code
**Page added this mixing progress bar prompt percentage, will prompt, the following code**

I don't know if the problem is highlight itself or what, if so, please tell me how to troubleshoot the problem

The 280 content is: 
```js
undefined"! =typeof window&&window.addEventListener&&window.addEventListener("DOMContentLoaded",(()=>{
...Posterior ellipsis
```

**Comment by joshgoebel** [comment]
Sorry, but I'm not sure why it's a problem that the handler took 167ms...

**Comment by joshgoebel** [comment]
Ping.

**Comment by y377** [comment]
No matter, later I have new discoveries, I will update

**Comment by joshgoebel** [comment]
Closing from inactivity.  When you have time to work with us on this we'd be happy to reopen.
