### ISSUE TITLE
[Request] Show example styles in the readme

### ISSUE THREAD

**Issue by 0xhiro** [highlightjs/highlight.js#3689]
Thanks for this awesome project. Could you add some screenshots of certain styles that may be used? Having to go through every style one by one is rather tedious.

**Comment by joshgoebel** [comment]
I think you want: https://highlightjs.org/static/demo/

?

**Comment by 0xhiro** [comment]
Oh thanks!

**Comment by 0xhiro** [comment]
Maybe add a link in the Readme or something
