### ISSUE TITLE
(request org repo) highlightjs-lang

### ISSUE THREAD

**Issue by AdamRaichu** [highlightjs/highlight.js#3690]
I would like to request the creation of a `highlightjs-lang` repository for my 3rd party grammar.

- [x] I have an existing personal repository ready to go

### Metadata

- Grammar Name: `lang`
- Link to repo: https://github.com/AdamRaichu/highlightjs-lang

### Requirements

- [x] I've read the [language Contributor Checklist](https://highlightjs.readthedocs.io/en/latest/language-contribution.html)
- [x] I've read the [Language Contribution Guide](https://github.com/highlightjs/highlight.js/blob/main/extra/3RD_PARTY_QUICK_START.md)
- [x] I'm currently willing to support and maintain this grammar over time
- [x] That repo includes a `dist` folder with CDN-ready `CJS` and `ESM` builds
- [x] That `README.md` includes examples of simple web usage
- [x] That `README.md` includes examples of Node.js usage

### Afterwards

Submit a PR that:

- [x] adds mention of your new language to `CHANGES.md`
- [x] updates `SUPPORTED_LANGUAGES.md` in the main library

**Comment by joshgoebel** [comment]
Done.

https://github.com/highlightjs/highlightjs-lang
