### ISSUE TITLE
Different mark up even though same contents

### ISSUE THREAD

**Issue by jiheapark** [highlightjs/highlight.js#3691]
I use highlight.js as syntax code in modal.
Event though my code is same, it show different markup (with different style).

this is the mark up that i opened my modal at first
<img width="1595" alt="스크린샷 2023-01-17 오후 12 51 01" src="https://user-images.githubusercontent.com/26865541/212806027-c5f785b0-4975-4aa5-b867-fde7682b3e52.png">

And this is the mark up that I opened at secode.
<img width="1596" alt="스크린샷 2023-01-17 오후 12 51 16" src="https://user-images.githubusercontent.com/26865541/212806068-ceff5627-c7a3-4081-86df-0563a998841c.png">
From the second time on, it continues to be the same.
Only at First, it had different markup/style.
I want to get same markup/style at anytime.

what should I do?
Please help me.

**Comment by joshgoebel** [comment]
Are you running Highlight.js every time the modal is opened?  **You don't want to actually run highlight more than once.**. Just a guess.

**Comment by jiheapark** [comment]
@joshgoebel 
yes, I run highlight.js every time the modal is opened.
should I run only once?

**Comment by joshgoebel** [comment]
I dunno depends on if the modals stays in the DOM or not - you shouldn't highlight the same exact element multiple times.

**Comment by jiheapark** [comment]
@joshgoebel 
When modal closed, it removed on DOM. 
So I think It would not hightlight the same element muliptle times.

**Comment by joshgoebel** [comment]
No idea then.  I've never seen such behavior though and at this point I'd guess it's something about your implementation rather than a bug in the library. Exactly what, it's hard to say... if you can reproduce the problem in a small JSFiddle example I'd be happy to take another look.

For best results though, don't use `autoHighlight`... that would be one easy way to solve your problem.

**Comment by jiheapark** [comment]
I think the problem is even though same contents, get different markup. because highlight.js style wroks by markup.
Why I get different markup with same contents???

**Comment by joshgoebel** [comment]
Yes, I understand what you are seeing.  As I said: **No idea then.** 

If you reproduced this with a simple JSFiddle test case that showed the same problem I could take another look.
