### ISSUE TITLE
(all languages inside blockquote) Highlight.js has some compatibility problems with markdown's blockquote

### ISSUE THREAD

**Issue by SakuraWald** [highlightjs/highlight.js#3692]
**Describe the issue**
If you use `code fence` inside `blockquote`, then highlight.js will behave differently than expected.

**Which language seems to have the issue?**
all the languages in this case.

**Are you using `highlight` or `highlightAuto`?**
no.
...

**Sample Code to Reproduce**
The example codes is like: 
```
>```mermaid
>graph TD;
>      A-->B;
>      A-->C;
>      B-->D;
>      C-->D;
>```
```
![image](https://user-images.githubusercontent.com/10484271/212821530-bdfd579c-327c-42d7-ad34-26f7ddc6f63c.png)

**Expected behavior**

![image](https://user-images.githubusercontent.com/10484271/212821919-37fd9359-68bf-4e9a-aaa1-43ec2cb28a1a.png)

**Additional context**
![image](https://user-images.githubusercontent.com/10484271/212821815-44c02f3b-28e5-453a-a423-99501e548809.png)

![image](https://user-images.githubusercontent.com/10484271/212822220-27d952df-be16-40e2-9e06-55cf8ddd52e2.png)

**Comment by joshgoebel** [comment]
> then highlight.js will behave differently than expected.

**I'm not sure exactly what you are showing here.**  None of the above "expectations" looks like Highlight.js output.  **Highlight.js does not render Markdown**, it merely highlights it. If your input is the example above then your output (visually) will always be exactly:

````
>```mermaid
>graph TD;
>      A-->B;
>      A-->C;
>      B-->D;
>      C-->D;
>```
````

Just some portions may be colored differently - that's the highlighting.  For example here is our output of that snippet:

<img width="393" alt="Screen Shot 2023-01-17 at 7 26 58 PM" src="https://user-images.githubusercontent.com/6473/213046886-caa172c3-f6e5-4edc-b8cb-7892a681c0a5.png">

Now that isn't perfect - it doesn't know the `>` are part of the block quote, not the code itself ...but without a full parser when we see a `>` inside a code block it's hard for us to know whether it's a block quote or part of the code block.

It's possible we could recognize this with some smart mode nesting... I'll leave this open for a bit to see if anyone wants to take a crack at it.

**Comment by SakuraWald** [comment]
> > then highlight.js will behave differently than expected.
> 
> **I'm not sure exactly what you are showing here.** None of the above "expectations" looks like Highlight.js output. **Highlight.js does not render Markdown**, it merely highlights it. If your input is the example above then your output (visually) will always be exactly:
> 
> ```
> >```mermaid
> >graph TD;
> >      A-->B;
> >      A-->C;
> >      B-->D;
> >      C-->D;
> >```
> ```
> 
> Just some portions may be colored differently - that's the highlighting. For example here is our output of that snippet:
> 
> <img alt="Screen Shot 2023-01-17 at 7 26 58 PM" width="393" src="https://user-images.githubusercontent.com/6473/213046886-caa172c3-f6e5-4edc-b8cb-7892a681c0a5.png">
> 
> Now that isn't perfect - it doesn't know the `>` are part of the block quote, not the code itself ...but without a full parser when we see a `>` inside a code block it's hard for us to know whether it's a block quote or part of the code block.
> 
> It's possible we could recognize this with some smart mode nesting... IE, you'd have a rule that matched `` >``` `` And then inside that sub-matched on `>.*` using a multi-matching to scope the first past of the line differently than the code body... you'd need rulesets for every possible nesting level we wanted to support though.
> 
> I'll leave this open for a bit to see if anyone wants to take a crack at it.

I have found that this is the bug of the render of hexo.
The render gives the in-correct inputs.
