### ISSUE TITLE
[Request] Improve the markup test harness

### ISSUE THREAD

**Issue by thecodewarrior** [highlightjs/highlight.js#3697]
#### Is your request related to a specific problem you're having?
While working on highlightjs-vue I wanted to write unit tests, but I found the existing test harness unwieldy for writing many small unit tests, and it's hard to visually inspect the highlighting from the raw HTML

#### The solution you'd prefer / feature you'd like to see added...
It would be great if highlight.js had a first-party test fixture, possibly even published as a package so other language definitions can use it. The key features I would want are:
- The ability to create many small unit tests which have long, descriptive names
- Some way of previewing the test results, including both the expected and actual highlighting for comparison

Refactoring/improving infrastructure code is one of my favorite parts of programming, so I dove in and created a prototype test harness that performs the tests and then writes the output to an HTML file where you can preview the source code, the expected output, and the actual output. [Here's an example of the resulting HTML](https://gistpreview.github.io/?6a7ea3ebc0309666f2969ab73055c73b). The code is an absolute mess at the moment (I miss typescript 😭) so if you think this is a good idea I'll definitely be doing some polishing.

The test structure is similar to the existing infrastructure, as in it reads the source from a file, highlights it, then compares it to an expected file, but instead of scanning the directory for test files, you list the tests manually, which means you can add much more meaningful names to them. The details of setting up the fixture need a lot of polish (e.g. you shouldn't have to manually add an after hook to write the file), but this is the idea:

```js
const fixture = new HighlightJsTestFixture({suite: this, dir: path.join(__dirname, "markup"), ext: ".vue", lang: "vue"})

describe("<script> tags", () => {
  it('should highlight <script> using javascript', fixture.validateFile("script-tag/plain"))
  it('should highlight <script setup> using javascript', fixture.validateFile("script-tag/plain-setup"))
  // ...
})
describe("<style> tags", () => {
  it('should highlight <style> using css', fixture.validateFile("style-tag/plain"))
  it('should highlight <style scoped> using css', fixture.validateFile("style-tag/plain-scoped"))
  // ...
})

after(async () => {
  await fixture.writeDemoHtml(path.join(__dirname, "demo.html"))
})
```

#### Any alternative solutions you considered...
- I considered writing the test code inline in the javascript, but that would quickly become unmanageable
- Initially I was scanning the directory for tests, but for small unit tests it's important to have a clear description of what they're testing, and that's difficult to get across in a filename

#### Undecided details
- How opinionated should the fixture be? Should you be able to fully customize the input and output files, or should it be fixed?
- Should the fixture be published as a package? Doing it that way grants a lot more freedom in terms of organizing the code, because if it's just going to be copied and pasted into each project we'll want it to be a single file, and it means other projects can more easily utilize it.

**Comment by joshgoebel** [comment]
I do agree that testing could possibly be improved, but I'm not sure labeling your test files in a 3rd location using a mapping table is the correct approach.  Current we often do this just using comments from the source language in the test input:

```js
// this is a tricky anonymous function
var a = () => { hi() }

// this is a normal function
function a() { hi() }
```

This of course also results in the comments being in the test results, but that hasn't been so terrible in real world usage.  A special syntax for such comments might be nicer, but it's hard to have a universal syntax that also supports ALL POSSIBLE grammars...

---

Originally it bothered me that test cases were spread across two files - making it very hard to write them by hand side-by-side... but over time I've realized I never write tests by hand... I let the test engine generate the output then I scan it for correctness - and after it's locked in it serves as a regression test against future issues.

**Comment by thecodewarrior** [comment]
Having the test name in the file would actually be pretty easy, basically just use the first line as the test name, maybe removing common comment characters from the beginning and end of the line. 

Also same here, I didn't write the tests by hand, I just let the test fail and then copied the actual value after verifying that it was correct.

**Comment by joshgoebel** [comment]
I could imagine that, sure, but I'm not sure what the big win would be?   I actually think the broad "category" names we already use are pretty descriptive at the "grouping of tests" level (which is what these files **typically** are - or what we'd prefer them to be)... such as say `functions`, `strings`, `types`, etc... 

What is the advantage of taking that filename and ALSO moving it into the first line of the file?

**Comment by thecodewarrior** [comment]
> which is what these files typically are - or what we'd prefer them to be

Ah, I guess it's a difference in testing philosophy. If you prefer using fewer and larger test files then that's true, using the file name is fine. The way I was approaching things would have many more much smaller tests. Closer to unit tests than end-to-end tests. 

I'm curious why the preference for fewer, larger test files though. Having more, smaller tests helps pinpointing what exactly is broken, and the exercise of writing them can be helpful for finding edge cases. I'm a bit of a testing fiend though, and they do definitely take more time to write.

**Comment by joshgoebel** [comment]
There is a sweet spot where "a reasonable number of tests" is way better than 1 huge test or 100 small tests.  Esp when it comes to finding "where do I add/find this test"... it sounds like you want **very** small tests.  I don't see any advantage to that (for these types of tests).

Hence for more complex languages "strings" is a reasonable level of granularity... there might be multiple types, quoted, unquoted, heredocs, etc... but all of them under `strings`.  For a language with only one type of string, `"hello"` this would be overkill to have a single file test.

>  smaller tests helps pinpointing what exactly is broken

I'll simply disagree.  The brokeness is always in the Highlight.js grammar/engine... whether the test is 100 files or 1 file doesn't help pinpoint what is broken.  And if you mean just literally "[pinpoint] what test is failing" I think our test suite already does a reasonable enough job showing that when tests fail. 

> and the exercise of writing them can be helpful for finding edge cases.

I don't know that this is exclusively true of small tests...

---

**I find it helpful to see all related test/syntax cases on a single screen to more easily make sure we've covered them all.**

**Comment by joshgoebel** [comment]
Out of curiosity, is there a reason you filed this issue as "improve the markdown harness" vs "improve test harnesses"?  Do you have some special interest in markdown over the other grammars?

**Comment by thecodewarrior** [comment]
Yeah I can see the value in larger tests. Larger tests also help make sure there aren't any issues that span across bits of code (think a string not ending correctly). 

As I mentioned I'm a bit of a testing fiend and several past projects have pretty much desensitized me to having too many tests.

Regarding your markdown question, I think you misread "mark**up**" as "markdown". The particular tests I'm talking about are all in the markup tests directory.

One thing the new tests do is instead of everything being txt files, you can (optionally) use the appropriate file extension for your inputs and html for the output, that way you get IDE syntax highlighting, if available.

**Comment by joshgoebel** [comment]
> I think you misread "markup" as "markdown". 

Ah, sorry I did.  If your interest had been in Markdown I was going to point you to some interesting work. :-)

>  that way you get IDE syntax highlighting, 

That would certainly be doable with the existing suite, though I'm not convinced it's a big win.  Often the tests include *incorrect* syntax also, in which case editor highlighting can sometimes be a nuisance.

> I'm changing the implementation I'm working on

I'll be curious to see what you propose then...

**Comment by thecodewarrior** [comment]
Well fuck, going to write docs on it I just *now* discovered the developer.html file (which is mentioned in CONTRIBUTING.md, a file it seems I should've read more carefully), which makes the only real improvement to the test harness (the ability to view the expected/actual highlighting, which is mostly useful for previewing highlighting in general) pretty much moot. I have a bad habit of jumping headfirst into projects without doing proper research on their existing solutions, and it often bites me exactly like this.

Thanks for your time :)
