### ISSUE TITLE
Add TypeScript `.mts` and `.cts` file extensions

### ISSUE THREAD

**Issue by qtiki** [highlightjs/highlight.js#3706]
Add `.mts` and `.cts` file extensions for TypeScript: https://www.typescriptlang.org/docs/handbook/esm-node.html#new-file-extensions

https://github.com/highlightjs/highlight.js/blob/2f3d5ff18ef6dffe25ef38dd1fad7d73061e2122/src/languages/typescript.js#L106-L109

**Comment by joshgoebel** [comment]
PR welcome.
