### ISSUE TITLE
(javascript) highlight error

### ISSUE THREAD

**Issue by neveler** [highlightjs/highlight.js#3708]
**Describe the issue**
![image](https://user-images.githubusercontent.com/55753029/216796258-0f8a19ab-c3e1-4262-b1f6-ae70f594b58e.png)
![image](https://user-images.githubusercontent.com/55753029/216796297-65e9f8a0-4bf7-486d-b482-4c432ae55195.png)

**Which language seems to have the issue?**
`javascript`

**Comment by joshgoebel** [comment]
And what exactly is the issue here again?

**Comment by joshgoebel** [comment]
`window` is a JS (browser) built-in variable and is being highlighted as such. There has been some discussion in the past of allowing for more dynamic changes to keywords, but currently that isn't easily possible... (there are various ways you might dynamically alter/monkey patch a grammar, but that's a bit out of scope for discussion here) 

I don't think we want to ship a "browser JS" vs "non-browser JS" grammar... I suppose you could try and make the case that we should remove all browser specific globals from the highlighter - and then I'd also presume we should remove Node specific variables like `global` as well...?

I'm willing to listen - but as you're the very first person to ever raise this as an issue right now I'd have to consider that you are likely in the minority... that the majority of users are benefiting from this behavior.

But perhaps you're very pursuasive?  Want to make the case?
