### ISSUE TITLE
Error: Failed to resolve module specifier "highlight.js" in ES6 module compiled from TS

### ISSUE THREAD

**Issue by MrDiamondDog** [highlightjs/highlight.js#3711]
**Describe the issue/behavior that seems buggy**

Getting `Uncaught TypeError: Failed to resolve module specifier "highlight.js". Relative references must start with either "/", "./", or "../".` in ES6 modules compiled from TS.

**Sample Code or Instructions to Reproduce**

`highlight.ts`
```
import hljs from "highlight.js";

hljs.highlightAll();
```
`tsconfig.json`
```
{
    "compilerOptions": {
        "target": "ES2017",
        "module": "ES2022",
        "esModuleInterop": true,
        "forceConsistentCasingInFileNames": true,
        "strict": true,
        "skipLibCheck": true,
        "outDir": "js",
        "rootDir": "ts",
        "moduleResolution": "node",
        "baseUrl": ".",
        "paths": {
            "highlight.js": ["./node_modules/@types/highlight.js"]
        }
    },
}
```

**Expected behavior**

No error

**Additional context**

I'm very new to modules like this, and have found no results on how to fix it.

**Comment by joshgoebel** [comment]
Is highlight.js installed as a dependency?
