### ISSUE TITLE
Simple PHP snippets not highlighted as PHP

### ISSUE THREAD

**Issue by remcokalf** [highlightjs/highlight.js#3714]
**Describe the issue**
We have many simple PHP snippets on our site and prefer to use them without <?php tags. As I understand it, the "php" grammar should recognize simple pure PHP snippets like below examples  as PHP, but for some it does not.

**Which language seems to have the issue?**
PHP

**Are you using `highlight` or `highlightAuto`?**
I use it like this: 

```
// first, find all the div.code blocks
document.querySelectorAll('div.code').forEach(el => {
  // then highlight each
  hljs.highlightElement(el);
});

```
As described here:
https://github.com/highlightjs/highlight.js#using-custom-html

**Sample Code to Reproduce**

```
add_action( 'pre_get_posts', function( $query ) {
  if ( $query->is_category() && $query->is_main_query()  ) {
    $query->set( 'posts_per_page', 20 );
  }
});

```

```
add_action( 'pre_get_posts', function( $query ) {
  if ( $query->is_home() && $query->is_main_query() ) {
    $query->set( 'post_type', [
      'post',
      'product'
    ] );
    $query->set( 'orderby', 'title' );
    $query->set( 'order', 'ASC' );
  }
```

```
add_action( 'pre_get_posts', function( $query ) {
  if ( $query->is_category() && $query->is_main_query()  ) {
    $query->set( 'orderby', [
      'date'  => 'DESC', // Primary sort: by post date
      'title' => 'ASC'   // Secondary, fallback sort: by post title
    ] );
  }
} );
```

**Expected behavior**
The above examples render like bash, looking like this:
https://d.pr/i/POHPLB

I'd expect or would like to render them as PHP, not bash or something else.

**Additional context**
When I add <?php it is highlighted as expected. But from another issue I understand that the PHP grammar should render/recognize these simple non-mixed PHP code examples as PHP. But it does not.
Why we need it without <?php is because beginning dev users paste these snippets in WP functions.php and don't understand you'd have to remove the <?php part.

**Comment by joshgoebel** [comment]
Auto-detect is more of a toy than a tool, and it's possible we'll even relegate it to a plugin in the future - removing it from core.  Please tag your code snippet explicitly rather than trying to let us "recognize" it...

```
<pre><code class="language-php">...</code></pre>
```

**Comment by remcokalf** [comment]
Thanks for pointing me in the direction of explicitly setting that class, that fixes at least part of our issues.

**Comment by joshgoebel** [comment]
Glad to help!
