### ISSUE TITLE
custom package, it does not work

### ISSUE THREAD

**Issue by letochagone** [highlightjs/highlight.js#3724]
I wanted to download highlight.js selecting only CSS, HTML and Javascript

![image](https://user-images.githubusercontent.com/7129968/222172236-5ba829cf-8050-4c45-bedb-62d527185d0e.png)

Then I click on the "download" button,
but then, the highlight.zip file contains all the languages...

![image](https://user-images.githubusercontent.com/7129968/222173572-68ca91d8-cafb-4b4c-90af-39408f8507fe.png)

![image](https://user-images.githubusercontent.com/7129968/222173795-8116985a-f5be-42fc-82ec-13fbe48dc313.png)

![image](https://user-images.githubusercontent.com/7129968/222173891-eedfb30c-7e56-4dec-9b94-18e9b85caed9.png)

**Comment by joshgoebel** [comment]
Yep, the only thing that changes is the size of `highlight.js` in the root and what's "built into" that file.  All the other languages come along just incase you need them individually.
