### ISSUE TITLE
[Request] add language ejs, nunjucks

### ISSUE THREAD

**Issue by dimaslanjaka** [highlightjs/highlight.js#3733]
**Is your request related to a specific problem you're having?**
Iam building blog with niche programming, and some language used are nunjucks. i also building `hexo` plugins with documentation of nunjucks shortcode usages.

**The solution you'd prefer / feature you'd like to see added...**
I need highlightjs to highlighting those languages

**Comment by joshgoebel** [comment]
Please see our policy:

https://highlightjs.readthedocs.io/en/latest/language-requests.html
