### ISSUE TITLE
prompt-with-tilde.expected.txt should be named prompt-with-tilde.expect.txt

### ISSUE THREAD

**Issue by alexeyinkin** [highlightjs/highlight.js#3737]
To align with other golden tests, the file should end with `.expect.text`.

Can we also make sure we detect that in future? This inconsistency breaks my external tool.

**Comment by joshgoebel** [comment]
> Can we also make sure we detect that in future? 

I'd need some evidence this is likely to reoccur before I'd want to spend much time trying to prevent it. Feels more like a "one off" to me... thoughts?
