### ISSUE TITLE
(JS) Not detecting .find function 

### ISSUE THREAD

**Issue by alvarotrigo** [highlightjs/highlight.js#3743]
**Describe the issue**

Having something like this:

```js
  const optionToSelect = $options.find(item => item.text ===text);
```

The `class="hljs-keyword"` gets applied to the whole ` optionToSelect = $options.find(` without separating the `find` function.

Picture:
<img width="633" alt="image" src="https://user-images.githubusercontent.com/1706326/227317321-56725f80-ff4f-41ce-80cb-e37b6ccfacc2.png">

<img width="470" alt="image" src="https://user-images.githubusercontent.com/1706326/227318761-b5cef894-cb52-4508-9366-83d335bd0a80.png">

**Which language seems to have the issue?**
Javascript. 
NOT using auto-detection

**Are you using `highlight` or `highlightAuto`?**
I'm using [a WordPress plugin](https://github.com/westonruter/syntax-highlighting-code-block) using Highlight.js on the server side.

**Sample Code to Reproduce**

This is how jsfiddle shows it:
<img width="895" alt="image" src="https://user-images.githubusercontent.com/1706326/227317965-af02698d-04c9-4987-a83b-57af25f7d98b.png">

This is how Prism.js shows it:
<img width="630" alt="image" src="https://user-images.githubusercontent.com/1706326/227318330-85bb901f-7098-479c-9886-fed43ef4f392.png">

-->

**Expected behavior**
It should look more like this:
<img width="895" alt="image" src="https://user-images.githubusercontent.com/1706326/227317965-af02698d-04c9-4987-a83b-57af25f7d98b.png">

<img width="436" alt="image" src="https://user-images.githubusercontent.com/1706326/227318434-f7f79e4e-7917-407f-9718-214d81d40d08.png">

**Comment by joshgoebel** [comment]
<img width="987" alt="Screen Shot 2023-03-24 at 9 07 27 PM" src="https://user-images.githubusercontent.com/6473/227673732-70472e79-7cc2-425e-9e9d-50b914bc5359.png">

You are reading the developer tools wrong.  `span.keyword` is correctly wrapping ONLY the const, as it should.

**Comment by joshgoebel** [comment]
Please take another careful look using the latest version of the library.  If you still feel there is a problem a jsfiddle that provides a reproducible example using the latest library would be great appreciated.

Also using a different theme might help... not all themes choose to highlight all tokens.

And if some portion of your issue here isn't "this is broken" but rather "it should look nicer" that would be a duplicate of #2500.

**Comment by alvarotrigo** [comment]
Yeap, the problem is on the PHP port rather than on highlight.js 
Thanks for your insights!

I've opened and issue on [the repository of the PHP port](https://github.com/scrivo/highlight.php/issues/105).
