### ISSUE TITLE
Advise on how to contribute CUDA C++ highlighting

### ISSUE THREAD

**Issue by gonzalobg** [highlightjs/highlight.js#3745]
I'd like to contribute highlighting for the CUDA C++ language.

It includes all of C++, and some language extensions on top (some new keywords and syntax).

What would be the preferred way to contribute that? 
Should I add this as a new language, e.g., `cuda`, or should I add this functionality to the `cpp` language to avoid duplication?

**Comment by joshgoebel** [comment]
The contributor docs in general:  https://highlightjs.readthedocs.io/en/latest/language-contribution.html

> Should I add this as a new language, e.g., cuda, or should I add this functionality to the cpp language to avoid duplication?

Regarding extension vs starting over... you can find a few examples of us building on top of our own grammars in core (TS on JS, etc)... but it's not particular easy and there aren't any out of the box tools to help you.

If you wanted to try and start that way (and see how far you get or if you like it) you could try.  Or it might be easier to just fork `cpp`, hard to say.  We no longer recommend runtime extension though vs pulling in everything at compile time... so it that sense you don't "save any space" or "avoid duplication"... in the final build, only in the raw source.
