### ISSUE TITLE
Docs use 11.8.0 for CDN when it should be 11.7.0

### ISSUE THREAD

**Issue by alvarotrigo** [highlightjs/highlight.js#3746]
Importing the library from a CDN following [the docs](https://www.jsdelivr.com/package/npm/highlight.js#:~:text=out%3Dhighlight.js-,Fetch%20via%20CDN,-A%20prebuilt%20version) won't work:

```html
<!-- and it's easy to individually load additional languages -->
<script src="https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@11.8.0/build/languages/go.min.js"></script>
```

It should be using version 11.7.0:
https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@11.7.0/build/languages/javascript.min.js

**Comment by joshgoebel** [comment]
Sorry, I'll try to fix this over the weekend - I bumped the version but then it's taken a few days longer to release 11.8.0 than I realized.  All will be well again after the release.  Until then, use the 11.7 URLs.
