### ISSUE TITLE
Display code in TEXTAREA instead of PRE CODE not working

### ISSUE THREAD

**Issue by boiteasite** [highlightjs/highlight.js#3755]
**Describe the issue/behavior that seems buggy**

Hi,
I would like to use highlight.js to edit code in a TEXTAREA so I can modify it and save it.
I tried this but it doesn't work :
		hljs.configure({cssSelector:'textarea',languages:['js','php','css','html']});
		hljs.highlightElement(t);

Is it possible to do this with Highlight.js

Regards

**Sample Code or Instructions to Reproduce**

**Expected behavior**

**Additional context**

**Comment by joshgoebel** [comment]
Nope.

Highlight.js is not a live text editor, nor does it wish to be.  This is unsupported.

**Comment by boiteasite** [comment]
Thanks.
