### ISSUE TITLE
language aliases c++ and h++ are not treated as C++ but C

### ISSUE THREAD

**Issue by ITcarrot** [highlightjs/highlight.js#3762]
**Describe the issue/behavior that seems buggy**

When I specify a piece of C++ code using the language name "c++" or "h++", it treats it as a piece of C code. 

**Sample Code or Instructions to Reproduce**

Here's a piece of html:
```html
<pre><code class="language-c++">using namespace std;</code></pre>
```
After executing `hljs.highlightAll();`, it becomes:
```html
<pre><code class="language-c++ hljs language-c">using namespace <span class="hljs-built_in">std</span>;</code></pre>
```
Same thing happens with h++

**Expected behavior**

It should become:
```html
<code class="language-c++ hljs language-cpp"><span class="hljs-keyword">using</span> <span class="hljs-keyword">namespace</span> std;</code>
```

**Additional context**

**Comment by joshgoebel** [comment]
https://github.com/highlightjs/highlight.js/blob/main/src/highlight.js#L73

Our language detection regex doesn't allow for `+` characters in language names.  PR would be welcome.

**Comment by santi4o** [comment]
hello! I would like to help, can I work on this?

**Comment by joshgoebel** [comment]
Go for it!

**Comment by joshgoebel** [comment]
Sorry, I just realized... is `language-c++` even a valid CSS class name?  I'm not sure sure `+` is valid in class names... and if it's not a valid class name then I don't think we need to match against it - and instead just encourage users to use `cpp` when embedding the name in HTML.

Thoughts?

**Comment by joshgoebel** [comment]
Per last comment we'll keep our own internal aliases simple as `[a-z-]`, same as our filenames; if someone wants this behavior in their own use case it's easy to achieve with the `addAliases` API.
