### ISSUE TITLE
(request org repo) highlightjs-iptables

### ISSUE THREAD

**Issue by Checconio** [highlightjs/highlight.js#3771]
I would like to request the creation of a highlightjs-iptables repository for my 3rd party grammar.

- [X] I have an existing personal repository ready to go

### Metadata

- Grammar Name: Iptables
- Link to repo: [Checconio/highlightjs-iptables](https://github.com/Checconio/highlightjs-iptables)

### Requirements

- [X] I've read the [language Contributor Checklist](https://highlightjs.readthedocs.io/en/latest/language-contribution.html)
- [X] I've read the [Language Contribution Guide](https://github.com/highlightjs/highlight.js/blob/main/extra/3RD_PARTY_QUICK_START.md)
- [X] I'm currently willing to support and maintain this grammar over time
- [X] That repo includes a `dist` folder with CDN-ready `CJS` and `ESM` builds
- [X] That `README.md` includes examples of simple web usage
- [X] That `README.md` includes examples of Node.js usage

### Afterwards

Submit a PR that:

- [ ] adds mention of your new language to `CHANGES.md`
- [ ] updates `SUPPORTED_LANGUAGES.md` in the main library

**Comment by joshgoebel** [comment]
Ok, happy to go this route!

**Comment by joshgoebel** [comment]
https://github.com/highlightjs/highlightjs-iptables
