### ISSUE TITLE
line breaks are no longer respected

### ISSUE THREAD

**Issue by Raf-sns** [highlightjs/highlight.js#3772]
Hi,
I have a problem with line breaks.

When I load the pages in AJAX and apply the hljs.highlightAll();
the code is correctly highlighted and line breaks are respected.

But when I load the pages by URL call and once the DOM is fully loaded I apply hljs.highlightAll(); , line breaks are no longer respected and the code, although highlighted, is rendered entirely inline.

I don't understand where the error comes from.

You can see an example online with this address: https://placido-shop.com/Documentation/How-to-set-your-favicons-package

When you follow his link, the code will be rendered online,
if you click on another link/button and go back in the history, the line breaks will be rendered correctly.

Thanks for your help !

Cordially

**Comment by joshgoebel** [comment]
This is almost always a problem of either:

- The line breaks in your new content are really HTML `<br>` tags - this isn't supported, they will be stripped.
- You're using the wrong DOM method to inject your content into the DOM... for example `innerText`, `innerHTML`, and `textContent` are all VERY, VERY different.  I think `textContent` is what you want.

**Comment by joshgoebel** [comment]
`hljs.highlightAll()`

You shouldn't call this method over and over, it doesn't keep track of state - so it can mess up things it's highlighted in the past... you should rather find text blocks in the newer inserted content only and call `highlightElement` instead.

**Comment by Raf-sns** [comment]
Hi, thank you for your answer but it does not correspond to my case:
 - There is no <br> tag in the code snippets : 
 `<pre>
    <code class="html">&lt;!-- FAV icons --&gt;
        &lt;link rel=&quot;apple-touch-icon&quot; sizes=&quot;180x180&quot; href=&quot;FAV/apple-touch-icon.png&quot;&gt;
        &lt;link rel=&quot;icon&quot; type=&quot;image/png&quot; sizes=&quot;32x32&quot; href=&quot;FAV/favicon-32x32.png&quot;&gt;
        &lt;link rel=&quot;icon&quot; type=&quot;image/png&quot; sizes=&quot;16x16&quot; href=&quot;FAV/favicon-16x16.png&quot;&gt;
        &lt;link rel=&quot;mask-icon&quot; href=&quot;FAV/safari-pinned-tab.svg&quot; color=&quot;#e2e2e2&quot;&gt;
        &lt;link rel=&quot;shortcut icon&quot; href=&quot;FAV/favicon.ico&quot;&gt;
        &lt;meta name=&quot;msapplication-TileColor&quot; content=&quot;#2d89ef&quot;&gt;
        &lt;meta name=&quot;msapplication-config&quot; content=&quot;FAV/browserconfig.xml&quot;&gt;
        &lt;meta name=&quot;theme-color&quot; content=&quot;#e2e2e2&quot;&gt;
    </code>
</pre>`

- Also it works great when I call page sections with AJAX and insert them to DOM.
- I tested the method which is given as an example with `highlightElement`, but nothing works anymore...

Thanks for reading and responding.

**Comment by joshgoebel** [comment]
_Your raw HTML literally includes no line breaks..._ we can't preserve them if you never include them.  It's just as jumbled if I turn off JS entirely... ie, it's broken before Highlight.js is even called.

```
 <code class="html">&lt;!-- FAV icons --&gt; &lt;link rel=&quot;apple-touch-icon&quot; sizes=&quot;180x180&quot; href=&quot;FAV/apple-touch-icon.png&quot;&gt; &lt;link rel=&quot;icon&quot; type=&quot;image/png&quot; sizes=&quot;32x32&quot; href=&quot;FAV/favicon-32x32.png&quot;&gt; &lt;link rel=&quot;icon&quot; type=&quot;image/png&quot; sizes=&quot;16x16&quot; href=&quot;FAV/favicon-16x16.png&quot;&gt; &lt;link rel=&quot;mask-icon&quot; href=&quot;FAV/safari-pinned-tab.svg&quot; color=&quot;#e2e2e2&quot;&gt; &lt;link rel=&quot;shortcut icon&quot; href=&quot;FAV/favicon.ico&quot;&gt; &lt;meta name=&quot;msapplication-TileColor&quot; content=&quot;#2d89ef&quot;&gt; &lt;meta name=&quot;msapplication-config&quot; content=&quot;FAV/browserconfig.xml&quot;&gt; &lt;meta name=&quot;theme-color&quot; content=&quot;#e2e2e2&quot;&gt; </code>
```

**Comment by Raf-sns** [comment]
Hi,

so sorry ...

"_Your raw HTML [from the server] includes no line breaks..._ we can't 
preserve them if you never include them."

-> I haven't seen anywhere that I should/can insert _line breaks_ tags 
in the text of the code... I will try like that, there was a 
misunderstanding,

I see now why I did not understand your previous answer.

Thanks for the feedback, I'll give it a try.

Cordially.
