### ISSUE TITLE
Incorrect type of `LanguageDetail.keywords`

### ISSUE THREAD

**Issue by alexeyinkin** [highlightjs/highlight.js#3778]
`LanguageDetail.keywords` are currently defined as

https://github.com/highlightjs/highlight.js/blob/cc93b0e6d9209924e2ec2d55648a1e74a757a40c/types/index.d.ts#L172

But we have at least 3 formats:

1. Whitespace-separated string as in [Cos](https://github.com/highlightjs/highlight.js/blob/cc93b0e6d9209924e2ec2d55648a1e74a757a40c/src/languages/cos.js#L32).
2. `string[]` as in [Dockerfile](https://github.com/highlightjs/highlight.js/blob/cc93b0e6d9209924e2ec2d55648a1e74a757a40c/src/languages/dockerfile.js#L12).
3. `Record<string, string | string[]>` (plus optional `$pattern`) as in [Dart](https://github.com/highlightjs/highlight.js/blob/cc93b0e6d9209924e2ec2d55648a1e74a757a40c/src/languages/dart.js#L195).

The 2nd one is illegal in that definition. And the 3rd one is not as specific as it can be.

Should the correct one be `string | string[] | Record<string, string | string[]>` ?

Same goes for `ModeDetail`.

Since we are here, must we really support that variety of definitions? Is there a performance difference in loading that? Or is there no reason to prefer whitespace-separated string over `string[]`? Could we change to something like `Record<string, string[]>` in version 12? (plus some provision for `$pattern: string`, not sure how to code that correctly).

The reason I care is that I am porting your package to Dart, and the porting script for diverse definitions is harder to maintain.

**Comment by joshgoebel** [comment]
> `string | string[] | Record<string, string | string[]>`

Yes, I believe that was the intent.   PR would be welcome.
