### ISSUE TITLE
Code not highlighted

### ISSUE THREAD

**Issue by GrandStrateguerre** [highlightjs/highlight.js#3780]
Hi,

**Describe the issue/behavior that seems buggy**
-Javascript code
output :
![image](https://user-images.githubusercontent.com/86523070/236290162-4128d0b2-e473-42de-834c-a50016d1b241.png)
declaration in html :
![image](https://user-images.githubusercontent.com/86523070/236290644-9d89bf01-2e9e-4850-bda4-9b526e41cb82.png)
In script side, we get the code element :
![image](https://user-images.githubusercontent.com/86523070/236291711-470c9ef6-b815-4a4c-ab63-34d19e2f4004.png)
We apply the instruction :
![image](https://user-images.githubusercontent.com/86523070/236292019-39dd7157-de74-4651-b647-3e0326652456.png)
The result is that the code is not highlighted

**Sample Code or Instructions to Reproduce**
Use VS Code last version + vite for the local server for running the project in the zip file below :
[ThreeJS-Tutorials.zip](https://github.com/highlightjs/highlight.js/files/11400274/ThreeJS-Tutorials.zip)
Npm package installed :
![image](https://user-images.githubusercontent.com/86523070/236294939-79d768fa-7f3c-46eb-9c0b-006da679a6c9.png)
for running vite local server :
![image](https://user-images.githubusercontent.com/86523070/236295382-514bef9d-9adf-4bf7-aed5-97de20100ada.png)
![image](https://user-images.githubusercontent.com/86523070/236295590-6626108e-762a-41e6-bfb7-5b78f527ec3d.png)
instruction for the launch.json :
![image](https://user-images.githubusercontent.com/86523070/236296067-2da98b5d-3ab8-4cec-bf6c-4774cc7ef9aa.png)

For going into the javascript side click on :
![image](https://user-images.githubusercontent.com/86523070/236297016-6daf62e5-4f41-45a5-b90c-121a52af924a.png)
![image](https://user-images.githubusercontent.com/86523070/236297233-67a25faf-f165-4b66-b652-bfd9f3592880.png)

**Expected behavior**

The code should be highlighted with color synthax ?
when we apply :
![image](https://user-images.githubusercontent.com/86523070/236297703-c043c6b9-9ffa-4cd3-9524-686138b992c0.png)

**Additional context**

Best regards

**Comment by joshgoebel** [comment]
If you're debugging why not step into our function and see what it's doing?

Are you loading a theme CSS file?  If there isn't an error most of the time someone had forgotten to load the CSS, etc.

**Comment by GrandStrateguerre** [comment]
hi @joshgoebel ,

yes, you're right , I've forgotten the style sheet :)
I put it :
![image](https://user-images.githubusercontent.com/86523070/236433800-f4ecd811-3e6c-47e0-8f8b-ed54f3319b5d.png)
and now I can see some code highlighted :
![image](https://user-images.githubusercontent.com/86523070/236434196-dd901bb5-adc4-4aba-8f3a-8b830ab123cf.png)
