### ISSUE TITLE
(shell.js) Use of eval in "node_modules/lottie-web/build/player/lottie.js" is strongly discouraged as it poses security risks and may cause issues with minification.

### ISSUE THREAD

**Issue by kvengerov** [highlightjs/highlight.js#3781]
vue v3 + vite v4.2.1

"highlight.js": "^11.8.0",

Use of eval in "node_modules/lottie-web/build/player/lottie.js" is strongly discouraged as it poses security risks and may cause issues with minification.

<img width="1063" alt="Screenshot 2023-05-05 at 16 25 45" src="https://user-images.githubusercontent.com/12641942/236470021-22b52391-0c6b-4825-936d-ada102fb55d0.png">

**Comment by joshgoebel** [comment]
I don't think that message is related to us?
