### ISSUE TITLE
(C)C language code highlighting does not support microcontroller development, and some statements cannot be highlighted

### ISSUE THREAD

**Issue by Dustin-Hayes-Hong** [highlightjs/highlight.js#3782]
Just like
![image](https://user-images.githubusercontent.com/78560143/236629952-1697caab-ecd5-4f29-bed1-2654b6345431.png)
I hope to achieve highlighting like this
![image](https://user-images.githubusercontent.com/78560143/236630008-4ed00c4c-b34e-49c4-9868-820efd08b227.png)

**Comment by joshgoebel** [comment]
We would be open to highlighting the property accesses there (and perhaps we already do but your theme doesn't support it)... ie the `.propertyAccess` pieces... that work is welcome (if not already finished) and this would be considered a dup of the larger #2500.

If you specifically want to support STM's many constants though, that's a harder ask... they obviously don't belong in C proper... and I don't think the "uppercase implies class/constant" rule applies strongly enough to C to auto-highlight anything uppercase a certain way as we do in other languages where this is baked in, such as Ruby, Wren, etc...

So I think you perhaps want to create a 3rd party grammar for STM or "microcontroller" development and add all these keywords there... you can find documentation on doing this: https://highlightjs.readthedocs.io/en/latest/language-contribution.html

The core team largely maintains the library and parser, we don't accept requests for new grammars.  That said if you want

**Comment by joshgoebel** [comment]
We would be open to highlighting the property accesses there (and perhaps we already do but your theme doesn't support it)... ie the `.propertyAccess` pieces... that work is welcome (if not already finished) and this would be considered a dup of the larger #2500.

If you specifically want to support STM's many constants though, that's a harder ask... they obviously don't belong in C proper... and I don't think the "uppercase implies class/constant" rule applies strongly enough to C to auto-highlight anything uppercase a certain way as we do in other languages where this is baked in, such as Ruby, Wren, etc...

So I think you perhaps want to create a 3rd party grammar for STM or "microcontroller" development and add all these keywords there... you can find documentation on doing this: https://highlightjs.readthedocs.io/en/latest/language-contribution.html

The core team largely maintains the library and parser, we don't accept requests for new grammars.  That said if you want to publish one as a 3rd party grammar we'd love to have you and add you to the official list of supported grammars across the whole ecosystem.

**Comment by joshgoebel** [comment]
Closing as either a dup of #2500 or a request for new grammar.
