### ISSUE TITLE
(Scala) Comments in constructor arguments not highlighted correctly

### ISSUE THREAD

**Issue by nihil-admirari** [highlightjs/highlight.js#3784]
**Describe the issue**
```scala
// Some comment
/* Some other comment */
case class Test(
    // Field 1
    field1: Int,
    /* Field 2 */
    field2: String
)
```

is highlighted as

![test](https://github.com/highlightjs/highlight.js/assets/50202386/983157d9-b3f2-411a-93f5-500d95906ee6)

**Which language seems to have the issue?**
Scala

**Are you using `highlight` or `highlightAuto`?**
`highlightAuto`

**Comment by joshgoebel** [comment]
Thanks for report... but it seems also sometimes `[]` are used after a "class object trait type"... what does that look like syntacticly and could comments appear there also?

**Comment by nihil-admirari** [comment]
These are generics: https://docs.scala-lang.org/scala3/book/types-generics.html, and comments are allowed:

``` scala
trait AbstractMap[
    K, // The type of key.
    /* The type of value. */ V
]:
    def get(k: K): V

class Map[K, V] extends AbstractMap[K, V]:
    def get(k: K): V = ???

type MapFromString[V] = Map[String, V]
```

However, generic objects probably don't exist: https://stackoverflow.com/questions/29653838/type-parametrized-object-in-scala.

**Comment by joshgoebel** [comment]
So the fix here needs to allow for comments in both `()` and `[]` pairs when it comes to templates.

**Comment by nihil-admirari** [comment]
Yes.
