### ISSUE TITLE
Haskell syntax highlighting correctly after quote in char '"' (ES6 modules)

### ISSUE THREAD

**Issue by j-erasmus** [highlightjs/highlight.js#3786]
**Describe the issue**
Haskell syntax highlighting is not always highlighting as expected.

 I have a construction of char " which is '"' in haskell. But highlighter thinks it's the start of a string. (But it isn't).

**Which language seems to have the issue?**
Haskell

**Are you using `highlight` or `highlightAuto`?**

`hljs.highlightAll();`

**Sample Code to Reproduce**
### [Codepen](https://codepen.io/jerasmus123/pen/zYmaNNZ?editors=1111)

(ES6 modules)

![Screenshot 2023-05-12 at 11 48 12](https://github.com/highlightjs/highlight.js/assets/14160322/1a5e35d4-1908-4bed-9b12-5509b6d62c76)

![Screenshot 2023-05-12 at 11 55 25](https://github.com/highlightjs/highlight.js/assets/14160322/e1ad3c98-9673-4327-af6f-3934e3acfb13)

**Expected behavior**

`-- some comment` should be treated as a comment, etc.

(CommonJS via CDN)

![Screenshot 2023-05-12 at 11 54 24](https://github.com/highlightjs/highlight.js/assets/14160322/19254b48-80c9-4fd5-901e-6c4755bdd8c8)

![Screenshot 2023-05-12 at 11 55 55](https://github.com/highlightjs/highlight.js/assets/14160322/4a1acc37-48d5-4b19-87f9-25208045826d)

**Additional context**

I used ES6 modules to reproduce the bug, everything seems to work correctly when using CommonJS via CDN.

**Comment by joshgoebel** [comment]
The syntax highlighting in both those examples is way different.  I'd guess you're ES6 example isn't loading Haskell and isn't actually using the Haskell grammar at all but rather some other grammar - that is resulting in the entirely different highlighting.

**Comment by j-erasmus** [comment]
> I'd guess you're ES6 example isn't loading Haskell

In [this example](https://codepen.io/jerasmus123/pen/zYmaNNZ?editors=1111) I'm loading Haskell from the [CDN](https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.7.0/es/languages/haskell.min.js) but highlighting still seems to break after the `'"'`. If I remove `'"'` from the Haskell code in that example the highlighting works as expected.

**Comment by joshgoebel** [comment]
<img width="563" alt="Screen Shot 2023-05-18 at 6 00 08 PM" src="https://github.com/highlightjs/highlight.js/assets/6473/841014e8-d169-4d24-a0f6-71194c1499ac">

Looks correct If you bump to 11.8 vs 11.7.

**Comment by j-erasmus** [comment]
Thanks @joshgoebel, I can confirm upgrading to 11.8 fixes the issue 👍
