### ISSUE TITLE
Publish non-minified styles to CDN

### ISSUE THREAD

**Issue by mvorisek** [highlightjs/highlight.js#3797]
Please build both minified/non-minified styles and publish them on npm/`@highlightjs/cdn-assets`.

We use the npm package to bundle some external libraries - https://github.com/atk4/ui/tree/4.0.0/public/external - and non-minified files are preferred for debugging and diffing changes.

Thank you.

**Comment by joshgoebel** [comment]
That flag goes back 9 years, I'm wondering if we should just remove it and always build both.  It's really an edge case to not prefer the minified builds, I can't think of why having them present is ever actively harmful.
