### ISSUE TITLE
(Python) or"string" highlights the raw string instead of `or` operator

### ISSUE THREAD

**Issue by IamMusavaRibica** [highlightjs/highlight.js#3798]
**Describe the issue**
Incorrect highlighting of python `or` operator preceded by string without whitespace, highlight.js treats the string as a raw string (with `r` prefix)

**Which language seems to have the issue?**
Python

**Are you using `highlight` or `highlightAuto`?**
highlight

**Sample Code to Reproduce**
https://jsfiddle.net/beh3j1nw/

**Expected behavior**
This is valid Python code
```py
print(test()or'string')
```
![image](https://github.com/highlightjs/highlight.js/assets/65848142/c7c53741-7793-4478-8440-51e3518ce790)

**Comment by joshgoebel** [comment]
Probably just a matter of adding a `\bor` rule prior to the string rule... or would it be simpler to add `\b` to the string prefixes perhaps, forcing them to stand on their own?

**Comment by MohamedAli00949** [comment]
I have read the Python highlighting script and found the solution: string highlighting the prefixes such as (r, u, b, f) and I will fix it now.
After solving it, I will submit my PR.

**Comment by joshgoebel** [comment]
Solved by #3897.
