### ISSUE TITLE
[Request] Control tab width

### ISSUE THREAD

**Issue by karchung0930** [highlightjs/highlight.js#3801]
When I look for the indentation in the code, it looks the below:

```
<p></p>
whitespace
<p></p>
```

Or sometimes the `whitespace` is not even exist and I don't know how it indent.

I try to use the CSS `tab-size` on the `pre` element, not working.

I have also look for an option to customize / control the the tab width in the documention and the core API, nothing too.

So is this option available now but I cannot find it, or this is not possible?

**Comment by joshgoebel** [comment]
> I try to use the CSS tab-size on the pre element, not working.

It most certainly works *if* your content includes actual ASCII tab characters (byte value: 9). Mozilla includes an example of this working in the docs: https://developer.mozilla.org/en-US/docs/Web/CSS/tab-size. If this doesn't work in your browser then there is a problem with your browser and we can't help with that.  If it does work in your browser but just not with Highlight.js you could provide a JSfiddle that reproduces the problem and we can take a closer look.

If `tab-size` does nothing it's likely you're using spaces (not tabs), and there are no built-in features to control tab width when the tabs are composed of individual spaces.

**Comment by joshgoebel** [comment]
We used to have an option for replacing tabs with a number spaces: https://github.com/highlightjs/highlight.js/issues/2874

It was removed, in favor of using the newer CSS features.

**Comment by joshgoebel** [comment]
Closing as #wontfix.
