### ISSUE TITLE
[Request] Support for Terraform code highlighting 

### ISSUE THREAD

**Issue by brittandeyoung** [highlightjs/highlight.js#3806]
**Is your request related to a specific problem you're having?**
We use Azure DevOps Wiki which states it uses this project for code highlighting in markdown. Currently there is no code highlighting with terraform code. 

**The solution you'd prefer / feature you'd like to see added...**
Terraform code highlighting could be implemented into this project.

**Any alternative solutions you considered...**
None

**Additional context...**
<img width="716" alt="image" src="https://github.com/highlightjs/highlight.js/assets/32572259/09990a45-ae4d-4765-93d2-71486c7128d5">

**Comment by joshgoebel** [comment]
Please see our policy on this:

https://highlightjs.readthedocs.io/en/latest/language-requests.html

There is a page on the wiki though just to give such requests a place to "live" long-term:

https://github.com/highlightjs/highlight.js/wiki/Grammar-Requests

**Comment by joshgoebel** [comment]
Closing, per policy we don't accept language requests as issues.
