### ISSUE TITLE
the invalid regular expression in this line

### ISSUE THREAD

**Issue by iLaus** [highlightjs/highlight.js#3820]
https://github.com/highlightjs/highlight.js/blame/e5e0220052bcf778fa93efcd007d47fb1dffab6b/src/languages/python.js#L10

**Comment by joshgoebel** [comment]
You'll need to use a newer browser or JS engine.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Regular_expressions/Unicode_character_class_escape

**Comment by iLaus** [comment]
this line has error for syntaxError,

when you packeted it , you will get  language definition for "python" could not be registered.

couse of  the unicode and the '\p' has conflict.

alouth I can't understand this  regular. but it actually happen.

the same error happened in “xml” language. 

![WechatIMG1136](https://github.com/highlightjs/highlight.js/assets/13331694/88c88da9-55ed-461c-a146-39951aafaf98)

**Comment by iLaus** [comment]
this line has error for syntaxError,

when you packaged it , you will get error:  "language definition for "python" could not be registered".

couse of the unicode and the '\p' has conflict.

alouth I can't understand this regular. but it actually happen.

the same error happened in “xml” language.



the error same as :

Language definition for 'xml’could not be registered.
SyntaxError: Invalid regular expression: /[/p{L}_]/: Invalid escape
	at xml (D:......\node_modules\highlight.js\lib\languages\xml.js:18:29)
	at Object.registerLanguage (D:......\node_modules\highlight.js\lib\languages\core.is:2405:14)
	at Object.<anonymous>(D:......\node_modules\highlight.js\lib\languages\lib\index.js:14:6)

**Comment by iLaus** [comment]
it used gu not u.

**Comment by joshgoebel** [comment]
What version of Node.js?

**Comment by iLaus** [comment]
> What version of Node.js?
U are right， when I use version 9.11.0 node， this error disappear. 

I'm sorry for my silly~
