### ISSUE TITLE
(CSS) custom property `--_margin-top: 1rem`, `top` gets wrongly highlighted

### ISSUE THREAD

**Issue by miragecraft** [highlightjs/highlight.js#3823]
**Describe the issue**

In CSS,  custom property such as `--_margin-top: 1rem`, `top` gets wrongly highlighted

It seems to be caused by some kind of interaction between the underscore and hyphen.

**Which language seems to have the issue?**

CSS, I'm using `language="css"` and NOT using auto-detect.

**Sample Code to Reproduce**

```
.example {
    --_margin-top: 1rem;
}
```

**Expected behavior**

`--_margin-top` should be treated as an atomic unit of text for highlighting purposes.

**Comment by joshgoebel** [comment]
`-` is a word boundary, so the rule matches:

```
      {
        className: 'attribute',
        begin: '\\b(' + css.ATTRIBUTES.join('|') + ')\\b'
      },
```

One fix here might be to use a multi-matcher. (example: https://highlightjs.readthedocs.io/en/latest/mode-reference.html#beginscope). You'd first match `\s` (with no scope) and then match the attribute... that's the closest we can currently get to a negative look-behind, which we don't support yet because Safari is still slow to that party.

A PR would be welcome here if you hav time.

**Comment by akhtarmdsaad** [comment]
I am Workin on it

> `-` is a word boundary (`\b`), so the rule matches:
> 
> ```
>       {
>         scope: 'attribute',
>         match: '\\b(' + css.ATTRIBUTES.join('|') + ')\\b'
>       },
> ```
> 
> One fix here might be to use a multi-matcher. (example: https://highlightjs.readthedocs.io/en/latest/mode-reference.html#beginscope). You'd first match `\s` (with no scope) and then match the attribute... that's the closest we can currently get to a look-behind, which we don't support yet because Safari is still slow to that party.
> 
> Once we could use lookbehind you'd just do a lookbehind for "not space" instead of `\b`...
> 
> A PR would be welcome here if you hav time.

I am working in it

**Comment by akhtarmdsaad** [comment]
I am working on it

**Comment by akhtarmdsaad** [comment]
There is a bug in src/languages/lib/css-shared.js file. adding an underscore( _ ) fixes the problem.

**Comment by Harsh3363** [comment]
Hi @joshgoebel I would like to solve this issue please assign this to me

**Comment by joshgoebel** [comment]
We don't usually do assignments, but I don't think anyone is rushing to complete this before you do.  Happy to see a PR if you contribute one.

**Comment by SamiKamal** [comment]
I think this should be closed as it was solved in https://github.com/highlightjs/highlight.js/pull/3863

**Comment by miragecraft** [comment]
Looks like it's fixed in the official site's demo.
