### ISSUE TITLE
[Request] New language for Drools engine script

### ISSUE THREAD

**Issue by ilxqx** [highlightjs/highlight.js#3824]
**The solution you'd prefer / feature you'd like to see added...**
I am using the Drools rule engine and I hope to display the rule script on a web interface. I also want to highlight it using hljs. Unfortunately, hljs currently does not support the Drools script language among the 197 languages it supports.

I hope to have highlighting for the Drools script language. Thank you.

**Any alternative solutions you considered...**
Currently, I can only use the Ace editor and set it to read-only mode to display Drools script code, but this approach is too cumbersome and not very elegant.

**Additional context...**
No

**Comment by joshgoebel** [comment]
Please see our policy on new language requests:

https://highlightjs.readthedocs.io/en/latest/language-requests.html
