### ISSUE TITLE
(request org repo) highlightjs-ballerina

### ISSUE THREAD

**Issue by YasithD** [highlightjs/highlight.js#3850]
I would like to request the creation of a `highlightjs-ballerina` repository for my 3rd party grammar.

- [x] I have an existing personal repository ready to go

### Metadata

- Grammar Name: Ballerina
- Link to repo: https://github.com/YasithD/highlightjs-ballerina

### Requirements

- [x] I've read the [language Contributor Checklist](https://highlightjs.readthedocs.io/en/latest/language-contribution.html)
- [x] I've read the [Language Contribution Guide](https://github.com/highlightjs/highlight.js/blob/main/extra/3RD_PARTY_QUICK_START.md)
- [x] I'm currently willing to support and maintain this grammar over time
- [x] That repo includes a `dist` folder with CDN-ready `CJS` and `ESM` builds
- [x] That `README.md` includes examples of simple web usage
- [ ] That `README.md` includes examples of Node.js usage

### Afterwards

Submit a PR that:

- [ ] adds mention of your new language to `CHANGES.md`
- [ ] updates `SUPPORTED_LANGUAGES.md` in the main library

**Comment by joshgoebel** [comment]
Done: https://github.com/highlightjs/highlightjs-ballerina

**Comment by YasithD** [comment]
Thanks!
