### ISSUE TITLE
Json language regex performance

### ISSUE THREAD

**Issue by MegatronKing** [highlightjs/highlight.js#3857]
**Describe the issue/behavior that seems buggy**

I translated highlightjs with dart language, everything works perfectly. But when a field in the JSON data is too long, dart will have a StackOverFlow error, seems that the dart VM uses a smaller stack size than Javascript. I have report this issue to Dart-SDK, their suggestion is optimizing the regex. Please see the conversation here: https://github.com/dart-lang/sdk/issues/48425#issuecomment-1592987082

**Comment by joshgoebel** [comment]
Closing this as this is obviously a Dart specific issue.
