### ISSUE TITLE
Generates the class name wrong

### ISSUE THREAD

**Issue by vigneshsivaji** [highlightjs/highlight.js#3858]
**Describe the issue**
 In my javascript code, highlight.js consider this as cs code in the class name.
 x: ej.base.Browser.isDevice ? '21%' : '19%',
 y: ej.base.Browser.isDevice ? '43%' : '47%' 
 This code generates the class name as cs, but that code is javascript.
 ![image](https://github.com/highlightjs/highlight.js/assets/120713139/0a39443b-e968-4955-988c-c1040cf760b1)

**Which language seems to have the issue?**
Javascript

I'm using highlight

...

**Sample Code to Reproduce**

   annotations: [
            {
                content: "<div style='color:green; font-weight:bold; font-size:14px'>Medium</div>",
                region: 'Series',
                x: ej.base.Browser.isDevice ? '21%' : '19%',
                y: ej.base.Browser.isDevice ? '43%' : '47%'
            }]

**Expected behavior**

![image](https://github.com/highlightjs/highlight.js/assets/120713139/198374b4-7c72-4175-a46c-19d3fcdeb9fd)

**Additional context**

**Comment by joshgoebel** [comment]
Auto-detection is not guaranteed to work, it's really more of a "guess".
