### ISSUE TITLE
(ANSI SQL) ANSI specifies keywords must be in  UPPERCASE

### ISSUE THREAD

**Issue by klspstck** [highlightjs/highlight.js#3860]
**Describe the issue**

I wanted to include markdown pages in wordpress with the plugin "WP Githuber MD".
This plugin allows to use "highlight.js"

**Which language seems to have the issue?**

When creating some SQL code snippets I realize keywords in UPPERCASE are not highlighted, but in lowercase.
As an instructor I have to say this is wrong.

At least both cases should be highlighted, because some so called "SQL cracks" may write everything in lowercase.

**Are you using `highlight` or `highlightAuto`?**
I don't know the differences.
...

**Sample Code to Reproduce**

```sql

select
  *
from table
;
```

```sql

SELECT
  *
FROM table
;
```

**Expected behavior**

**Additional context**

Here the preview looks OK. SO it looks like a problem of the mentioned plugin.
I will address that person in charge.

**Comment by joshgoebel** [comment]
I see no issues:

<img width="692" alt="Screen Shot 2023-09-12 at 6 26 05 PM" src="https://github.com/highlightjs/highlight.js/assets/6473/ea9f0e83-b09e-4c72-9c53-562037445948">

Our SQL grammar is case insensitive.   Very likely there is something else wrong with your setup - perhaps you aren't using the SQL grammar at all.  If you can provide an isolated JSFiddle that reproduces your problem with you our library and no other library/app code I'd be happy to take a second look.

Right now this doesn't look like our bug though.

**Comment by klspstck** [comment]
html,body{background-color:#fff;color:#333;line-height:1.4;font-family:sans-serif,Arial,Verdana,Trebuchet MS;}Thank you for the answer.
Yes, it looks loke there is no problem with "highlight.js",
rather with the wordpress pugin using this code.
I notified the developer about it and I am waiting for an answer.
Once again, no problem from your site.
 
KInd regards
Klaus P. StockStock & PartnerAdvanced Education GmbH-----------------------
Josh Goebel schrieb am 13.09.2023 00:28 (GMT +02:00):

I see no issues:

Our SQL grammar is case insensitive. Very likely there is something else wrong with your setup - perhaps you aren't using the SQL grammar at all. If you can provide an isolated JSFiddle that reproduces your problem with you our library and no other library/app code I'd be happy to take a second look.
Right now this doesn't look like our bug though.

**Comment by joshgoebel** [comment]
Awesome. Good luck.
