### ISSUE TITLE
Line numbers bug in angular 

### ISSUE THREAD

**Issue by aryan0909** [highlightjs/highlight.js#3866]
**Describe the issue/behavior that seems buggy**

- I am using highlight js in my project using angular. I was using line numbers also, and I added the functionality to add or delete code in the viewer. But the moment I save the code "replacing the old string literal with the new one" it got extra spaces and extra lines but if I use this without line numbers then it is not giving extra spaces as well as lines. Please look into it.

**Sample Code or Instructions to Reproduce**

Code :
Html:
<pre>
<code contentEditable='true' [highlight]="code" [lineNumbers]="true">
</code>
</pre>

<Button on click=>

Ts: 
code=`import Java.util.*
public class Work {
private String v1;
private String v3;
}
`

**Expected behavior**

**Additional context**

**Comment by joshgoebel** [comment]
My guess is you're (or angular or your lines code) is MAYBE using `innerText` when you want `textContent` or some minor detail thing like that that is distorting your content... I'd google and read up on the difference and see if that helps. _We preserve line breaks in the content when we convert it to HTML._

If you're using `\r\n` encoded text you likely want to change it to `\n` first, there is an open issue on that. In the future we will silently throw away the `\r` and only support `\n` line encoding.

---

We don't really provide support here for "Highlight.js + other stuff", but  I'll leave this open a bit to see if someone else in the community might want to jump in and assist.
