### ISSUE TITLE
(csharp) Raw String Literals are highlighted incorrectly

### ISSUE THREAD

**Issue by rosenzweigv** [highlightjs/highlight.js#3868]
**Describe the issue**

C# Raw String Literals are highlighted incorrectly. It seems that they are highlighted like normal strings, as instances of `"` in the middle of the strings ends the string coloring prematurely.

**Which language seems to have the issue?**

csharp

**Are you using `highlight` or `highlightAuto`?**

highlight

**Sample Code to Reproduce**
[https://jsfiddle.net/xae1v6wL/](https://jsfiddle.net/xae1v6wL/)

**Expected behavior**
See sample code -- The `"quoted text"` should look the same as the rest of the string 

**Additional context**
None

**Comment by akhtarmdsaad** [comment]
is this issue resolved

**Comment by joshgoebel** [comment]
Merged.
