### ISSUE TITLE
Julia and Julia-REPL should be listed separately in SUPPORTED_LANGUAGES

### ISSUE THREAD

**Issue by ShalokShalom** [highlightjs/highlight.js#3879]
Hi 👍🏻 

Currently, the syntax for julia-repl is aliased with that one for julia. 
This is wrong. 

It breaks the code, as both are simply other highlighters, for different purposes. 
I suggest to separate them. 

Thanks a lot

**Comment by joshgoebel** [comment]
> , the syntax for julia-repl is aliased with that one for Julia.

Untrue, it's a separate grammar that references Julia as a `subLanguage`.  This is how most of our repl grammars work.

> It breaks the code

You'll need to provide some examples here and perhaps we could examine this further.

**Comment by ShalokShalom** [comment]
> Untrue, it's a separate grammar that references Julia as a subLanguage. This is how most of our repl grammars work.

Well, this is what you claim [on your own Github page. ](https://github.com/highlightjs/highlight.js/blob/main/SUPPORTED_LANGUAGES.md)

> You'll need to provide some examples here and perhaps we could examine this further.

Is highlightjs used on Github?

**Comment by joshgoebel** [comment]
> Is highlightjs used on Github?

Not that I'm aware of.

> Well, this is what you claim [on your own Github page.](https://github.com/highlightjs/highlight.js/blob/main/SUPPORTED_LANGUAGES.md)

Ah, indeed we do.  A PR to fix that would be accepted.

**Comment by ShalokShalom** [comment]
Done. I also added support for other FSharp files, as you had missed couple of them as well. 

Are we sure, that Julia-REPL is indeed treated separated, and the docs were indeed wrong on that?

**Comment by joshgoebel** [comment]
> Are we sure, that Julia-REPL is indeed treated separated, and the docs were indeed wrong on that?

It is a separate grammar. You can review the source code, same as I can.

**Comment by ShalokShalom** [comment]
Thanks
