### ISSUE TITLE
(Rust) Incorrect highlighting of statements

### ISSUE THREAD

**Issue by JonathanHallstrom** [highlightjs/highlight.js#3881]
`if` and `while` statements are highlighted as functions when using parenthesized expressions.
This seems to happen for any valid rust identifier.
Discovered this in the demo section of the website.

```rs
if (1 + 2) * 2 == 6 {}
if true {}
while (1 + 2) * 2 == 6 {}
while true {}
for (a, b) in (0..10).enumerate() {}
for a in 0..10 {}
```

**Comment by JonathanHallstrom** [comment]
link to reproduce: [https://highlightjs.org/demo#lang=rust&v=1&theme=atom-one-dark&code=aWYgKDEgKyAyKSAqIDIgPT0gNiB7fQppZiB0cnVlxAt3aGlsZdUlxhrIKGZvciAoYSwgYikgaW4gKDAuLjEwKS5lbnVtZXJhdGUoKcglYcQgxR%2FEEg%3D%3D](highlightjs.org/demo)

**Comment by joshgoebel** [comment]
Should be fixable with a negative look-ahead for the "not a function" cases before performing the actual match... there are other examples of this in some of the built-in grammars.
