### ISSUE TITLE
(Python) Python style missing coloring functions

### ISSUE THREAD

**Issue by mzahran001** [highlightjs/highlight.js#3882]
**Describe the issue**
`highlight.js` does not detect python functions
Current output: 
![image](https://github.com/highlightjs/highlight.js/assets/15180702/2a532818-8973-43ec-814b-1a30f900e4b7)

**Which language seems to have the issue?**
Python

**Are you using `highlight` or `highlightAuto`?**
highlight

**Sample Code to Reproduce**
```python
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam

model = Sequential()
model.add(Dense(128, activation='tanh'))
model.add(Dense(2))

opt = Adam(learning_rate=0.05)
model.compile(optimizer=opt, loss='mse', metrics=['mape'])

model.fit(inputs, targets, validation_split=0.2)
```

**Expected behavior**

Change the color for functions and method variables.
![image](https://github.com/highlightjs/highlight.js/assets/15180702/778879da-4b21-4e1a-acb1-879333dc7527)
**Additional Context**
I am using the [website](https://highlightjs.org/demo) to render the code but it didn't detect the functions similar to what happens in Github or on the screenshot provided

**Comment by joshgoebel** [comment]
I don't think the python grammar yet supports `function.dispatch` (as your samples show)... this would be a welcome contribution - this is something we'd love to see in all our grammars if possible.  However, this (and other improvements) are already covered by the wider #2500 initiative.  So this will be closed a dup.

If you'd like to work on a PR for this, please feel free to do so.
