### ISSUE TITLE
Highlight.js removing line breaks from core/code block after update

### ISSUE THREAD

**Issue by jeremyfaucher** [highlightjs/highlight.js#3884]
I am running highlight.js in the WordPress block editor and set highlight.js to run when core/code block is updated. The core/code block natively uses `<br data-rich-text-line-break="true">` for it's line breaks. But when highlight.js runs it removes the line breaks.

Before:
<img width="284" alt="wgtwm" src="https://github.com/highlightjs/highlight.js/assets/3885507/2ded2ab9-1b06-48d3-85b7-f2be465110bc">
<img width="346" alt="KErsG" src="https://github.com/highlightjs/highlight.js/assets/3885507/092fc468-ee03-4e45-be37-ee2070bd7659">

After:
<img width="446" alt="6ti09" src="https://github.com/highlightjs/highlight.js/assets/3885507/fee6759c-7dda-439d-b735-66ab32813514">
<img width="347" alt="LLOFy" src="https://github.com/highlightjs/highlight.js/assets/3885507/d7ec1a77-d1cb-41f3-9d0e-586c4baff53b">

I tried using the highlight.js ignoreUnescapedHtML function:

```
//Define a custom function to exclude specific elements
hljs.configure({
ignoreUnescapedHTML: /<br\/?>/i, // Ignore <br> and <br/> tags
});
```
and this one:

```
//Define a custom function to exclude specific elements
hljs.configure({
ignoreUnescapedHTML: /<br\s*data-rich-text-line-break="true"\s*>/i
});
```
But could not get to work. [https://highlightjs.readthedocs.io/en/latest/api.html
](url)

**Comment by joshgoebel** [comment]
This is simply not supported behavior (using `BR`s).  Use `\n` instead or do the transform (from `BR` to `\n`) immediately before calling Highlight.js to highlight the block. 

`ignoreUnescapedHTML` ignores/strips all HTML, it does not preserve it.

**Comment by jeremyfaucher** [comment]
Okay. Yes, I am currently testing transforming (from BR to /n). Until then I see using an older version of highlight.js like (8.9.1) with the `hljs.initHighlightingOnLoad();` function does not remove the `<br>` tags.

codepen test here: [](https://codepen.io/jeremyfaucher/pen/ZEVZPjb)

**Comment by joshgoebel** [comment]
Yes, older versions supported this once.  For security reasons we don't recommend any HTML inside code blocks.  It usually does more harm than good (paving the way for code injection attacks, etc).
