### ISSUE TITLE
nginx is missing in the CDN build though documented under "common"

### ISSUE THREAD

**Issue by timorieber** [highlightjs/highlight.js#3889]
**Describe the issue/behavior that seems buggy**
I recently included this library using the Cloudflare CDN link https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/highlight.min.js. In production I noticed that nginx configs did not get highlighted.

**Sample Code or Instructions to Reproduce**
In this fiddle there is a nginx code block and it is not highlighted at first run. Then uncomment the nginx.js in the HTML head and run the fiddle again. The code block is highlighted.

**Expected behavior**
As stated in the docs under https://highlightjs.readthedocs.io/en/latest/readme.html#getting-the-library one can look at the "common" languages in the download section and see what languages are included in the CDN build. nginx is listed there, but not included in the CDN build.

**Comment by joshgoebel** [comment]
@allejo Is the common section on the website not dynamic (getting it's cues from the source)?


@timorieber   `nginx` is no longer in common.  It was removed with v11.  You'll now need to manually select it.

**Comment by timorieber** [comment]
> @timorieber `nginx` is no longer in common. It was removed with v11. You'll now need to manually select it.

Did this already when I filed this issue, thank you!

**Comment by allejo** [comment]
> @allejo Is the common section on the new website not dynamic (getting it's cues from the source)?

Oof, yea I think I built this list manually based on the old site two years ago; [highlightjs.org:utilities/constants.ts@`28b4990`](https://github.com/highlightjs/highlightjs.org/blob/28b4990e7087295144b2939b3efccb756d5be58b/utilities/constants.ts)

Is the category information available on compiled languages? Or is it only available in the original source files?

**Comment by allejo** [comment]
I've updated the website code to automatically determine categories based on the grammar files in this repo (see https://github.com/highlightjs/highlightjs.org/commit/c4bed562c3a22f4bbfa6462b7aa44a1981492cd7). Categories should be accurate on the website now.

Since `nginx` is no longer included with the "common" bundle and the website now respects the library's categories, I'm closing this issue as complete.

**Comment by joshgoebel** [comment]
Awesome, than ks!
