### ISSUE TITLE
(YAML) keys containing brackets highlighted wrongly

### ISSUE THREAD

**Issue by zewazi** [highlightjs/highlight.js#3894]
**Describe the issue**
Highlight.js library seems not to be able to color YAML keys properly, when there is brackets ( or ) inside YAML keys.

**Which language seems to have the issue?**
YAML

**Are you using `highlight` or `highlightAuto`?**
highlight

Calling it out like so in Vue 3 project:
`hljs.highlight(data.value, {language: 'yaml'}).value`

Also reproduces in demo app:
https://highlightjs.org/demo

...

**Sample Code to Reproduce**
1. Go to https://highlightjs.org/demo
2. language YAML, random theme
3. code:
field1: "1"
field2: "2"
field3(broken): "3"
"field4(broken)": "4"
field5: "5"

**Expected behavior**
field3(broken) and "field4(broken)" are colored same way as field1, field2, field5

**Additional context**
<img width="1612" alt="image" src="https://github.com/highlightjs/highlight.js/assets/50274125/d40f3bc4-54fa-465b-99c8-87e02f031543">

**Comment by joshgoebel** [comment]
Sounds like our regex for detecting keys simply needs to be improved or else a few variants added... I think the quoted version almost makes sense as a variant...
