### ISSUE TITLE
[Request] Ignoring parts within specific delimiters

### ISSUE THREAD

**Issue by szopeno** [highlightjs/highlight.js#3901]
**Is your request related to a specific problem you're having?**
I am trying to use both MathJax and highlightjs - however, math rendering only works when I use class="nohighlight", disabling
syntax coloring

**The solution you'd prefer / feature you'd like to see added...**
I imagine adding options like "ignore-within-delimiter: $" which would cause highlight NOT to try to highlight strings delimited with $

E.g. <pre><code> x := $P_j$ </code></pre>

P_j should be rendered by mathjax or katex and not colored by highlight

**Comment by joshgoebel** [comment]
This kind of thing is complex and not something we'd add to the core parser.  You'd need to:

- loop over the textual content, remove your delimited blocks (but track their placement for reinsertion)
- highlight
- reinsert the delimited content into the HTML with correct placement (after converting it to whatever)
