### ISSUE TITLE
(request org repo) highlightjs-codeowners

### ISSUE THREAD

**Issue by Nataliia-Radina** [highlightjs/highlight.js#3914]
I would like to request the creation of a `highlightjs-codeowners` repository for my 3rd party grammar.

- [x] I have an existing personal repository ready to go

### Metadata

- Grammar Name: Codeowners
- Link to repo: [_link to existing repository_](https://github.com/Nataliia-Radina/highlightjs-codeowners)

### Requirements

- [x] I've read the [language Contributor Checklist](https://highlightjs.readthedocs.io/en/latest/language-contribution.html)
- [x] I've read the [Language Contribution Guide](https://github.com/highlightjs/highlight.js/blob/main/extra/3RD_PARTY_QUICK_START.md)
- [x] I'm currently willing to support and maintain this grammar over time
- [x] That repo includes a `dist` folder with CDN-ready `CJS` and `ESM` builds
- [x] That `README.md` includes examples of simple web usage
- [x] That `README.md` includes examples of Node.js usage

### Afterwards

Submit a PR that:

- [ ] adds mention of your new language to `CHANGES.md`
- [ ] updates `SUPPORTED_LANGUAGES.md` in the main library

**Comment by Nataliia-Radina** [comment]
I have a problem with tests failing and code owner files being detected as a stylus. Is anyone available to help?

**Comment by joshgoebel** [comment]
https://github.com/highlightjs/highlightjs-codeowners

**Comment by joshgoebel** [comment]
Looking forward to your PR to add to languages.md.  Will close this issue now.

**Comment by Nataliia-Radina** [comment]
> Looking forward to your PR to add to languages.md. Will close this issue now.

@joshgoebel Thanks! I think it was already done in https://github.com/highlightjs/highlight.js/pull/3919
