### ISSUE TITLE
(rust) raw keyword variable names are not highlighted correctly

### ISSUE THREAD

**Issue by JayAndJef** [highlightjs/highlight.js#3924]
**Describe the issue**
In rust, one can put `r#` before a keyword name to escape it. Highlight.js does not recognize when this happens and instead highlights the keyword name as a keyword.

**Which language seems to have the issue?**
Rust

**Are you using `highlight` or `highlightAuto`?**
`highlight`

**Sample Code to Reproduce**
```rs
pub fn main() {
	let r#use = "hello"; // r#use should be highlighted as a variable
}
```

**Expected behavior**
In the above code block, `r#use` should be highlighted as a variable name. Instead, `r` is highlighted as a variable name and `use` is highlighted as a keyword.

**Additional context**

**Comment by joshgoebel** [comment]
A simple rule that matches `r#*` and applies no scope would fix the issue of false positives here.

**Comment by ThinkingVincent** [comment]
rush.js에서 새로운 정규표현식을 적용하여 문제를 해결해봤습니다.
https://regexr.com/
이 정규표현식 사이트에서
(r#)?[a-zA-Z_]\w*
이 정규식을 활용하면 모든 경우에 r#키워드가 제대로 식별됩니다.
test-browser에서도 정상적으로 작동하는 것 같아요.

**Comment by ThinkingVincent** [comment]
I tried applying a new regex in rust.js to solve the problem.
https://regexr.com/
In this regex site
`(r#)?[a-zA-Z_]\w*`
With this regex, the r# keyword is properly identified in all cases.
It seems to work fine in the test-browser as well.
