### ISSUE TITLE
(rust) quotes around a char emoji are not colored properly

### ISSUE THREAD

**Issue by tomsarry** [highlightjs/highlight.js#3933]
**Describe the issue**
In rust, single quotes around an emoji are not colored properly.
However, autodetect (on csharp) successfully colors it.

**Which language seems to have the issue?**
Rust

**Are you using `highlight` or `highlightAuto`?**
`highlight`

**Sample Code to Reproduce**
https://jsfiddle.net/cawyx173/

**rust, coloring doesn't work**
![image](https://github.com/highlightjs/highlight.js/assets/55455075/ad74b894-840e-4ff0-ae53-3749212131f9)

**autodetect (csharp), works**
![image](https://github.com/highlightjs/highlight.js/assets/55455075/4aecde36-0a4b-4158-b2ee-479fbf46cce1)

**Expected behavior**
When using rust highlighting, single quotes around an emoji should have the same color as single quotes around any other character.

**Additional context**
Syntax highlighting works properly using double quotes around emojis.
Problem seen in [rust book](https://doc.rust-lang.org/stable/book/ch03-02-data-types.html).

**Comment by joshgoebel** [comment]
```
 {
        className: 'string',
        variants: [
          { begin: /b?r(#*)"(.|\n)*?"\1(?!#)/ },
          { begin: /b?'\\?(x\w{2}|u\w{4}|U\w{8}|.)'/ }
        ]
      },
```

I'm guessing `.` doesn't cover Emoji... I'd have to play around with this one...

**Comment by tomsarry** [comment]
I talked a bit too fast, the pattern above does not work either (I think :sparkles: is encoded using only one u16 so is not a problem).
After looking at the [char](https://doc.rust-lang.org/src/core/char/methods.rs.html#11) implementation, the following are also valid but not matched by the expression above:
- `'\u{10ffff}'`
- `'\u{FFFD}'`
- `🥰` (actually, most unicode emojis seem to fail)
- `'𝕊'`

I really am not a regex expert, but I found the following matches for emojis / unicode characters, this might be of some help
- https://www.regextester.com/106421
- https://unicode.org/reports/tr51/#EBNF_and_Regex

**Comment by joshgoebel** [comment]
Want to see if my fix works?
