### ISSUE TITLE
MiniProgramError SyntaxError: Invalid regular expression: /[\p{L}_]/: Invalid property name in character class 

### ISSUE THREAD

**Issue by seepine** [highlightjs/highlight.js#3939]
**Describe the issue/behavior that seems buggy**

In android wechat miniprogram, not support `/[\p{L}_]/`

**Sample Code or Instructions to Reproduce**

```js
import hljs from 'highlight.js'

lang = hljs.getLanguage(lang) ? lang : 'plaintext'
text = hljs.highlight(text, { language: lang }).value
```

**Expected behavior**

can work

**Additional context**

<img width="401" alt="image" src="https://github.com/highlightjs/highlight.js/assets/93666053/34a3d897-ac2f-468f-b436-09cb6f917d94">
<img width="1075" alt="image" src="https://github.com/highlightjs/highlight.js/assets/93666053/6eaaacb1-b1b8-40bf-85a6-8c1527869207">

**Comment by joshgoebel** [comment]
Your JS runtime or browser is too old.  Regex`\p` support is required for using Highlight.js 11.
