### ISSUE TITLE
(repo) highlightjs-zig

### ISSUE THREAD

**Issue by fwx5618177** [highlightjs/highlight.js#3946]
I have created a new 3rd repo for supporting zig. It's reality performance:

![image](https://github.com/highlightjs/highlight.js/assets/25654385/41804f27-7919-4708-87bb-68eac10ba8db)

### Metadata

- Grammar Name: Zig
- Link to repo: https://github.com/fwx5618177/highlightjs-zig

### Requirements

- [x] I've read the [language Contributor Checklist](https://highlightjs.readthedocs.io/en/latest/language-contribution.html)
- [x] I've read the [Language Contribution Guide](https://github.com/highlightjs/highlight.js/blob/main/extra/3RD_PARTY_QUICK_START.md)
- [x] I'm currently willing to support and maintain this grammar over time
- [x] That repo includes a `dist` folder with CDN-ready `CJS` and `ESM` builds
- [x] That `README.md` includes examples of simple web usage
- [x] That `README.md` includes examples of Node.js usage

### Afterwards

Submit a PR that:

- [x] adds mention of your new language to `CHANGES.md`
- [x] updates `SUPPORTED_LANGUAGES.md` in the main library

Here are PR link: https://github.com/highlightjs/highlight.js/pull/3950

**Comment by joshgoebel** [comment]
Awesome.  I've played with Zig.  It's pretty sweet!

**Comment by fwx5618177** [comment]
> Awesome. I've played with Zig. It's pretty sweet!

Yeah, I decide to maintain this grammar overtime.
