### ISSUE TITLE
[Request] Updated union type keywords in Rust

### ISSUE THREAD

**Issue by ThinkingVincent** [highlightjs/highlight.js#3948]
**Is your request related to a specific problem you're having?**
Rust supports keywords of type `union`.
[doc.1](https://github.com/rust-lang/rfcs/blob/master/text/1444-union.md)
[doc.2](https://blog.rust-lang.org/2017/07/20/Rust-1.19.html)

But `union` hasn't been added to the **rust.js** keyword list in highlight.js yet - all the other keywords are included.
https://github.com/highlightjs/highlight.js/blob/8b88a7d4c3e88f157a87b8d50088af329d700eeb/src/languages/rust.js#L73C4-L77C15

**The solution you'd prefer / feature you'd like to see added...**
Add the `union` string to the list of keywords in **rust.js.**

**Any alternative solutions you considered...**
When you use union as a purposeful type in your code, it is designed to be properly highlighted. It's just not included in the KEYWORDS array. So maybe you don't need to modify anything. However, if the KEYWORDS array should contain all the keywords supported by rust, it seems like a good idea to add union as well.
https://github.com/highlightjs/highlight.js/blob/8b88a7d4c3e88f157a87b8d50088af329d700eeb/src/languages/rust.js#L287-L296

**Additional context...**

### as is
![image](https://github.com/highlightjs/highlight.js/assets/103738589/292a8d9f-6b2c-4c29-8a1b-93daa953f4a0)

### to be
![image](https://github.com/highlightjs/highlight.js/assets/103738589/5c90a3c7-49b6-4c7f-a501-dee44f8737df)

**Comment by joshgoebel** [comment]
What's an example of where `union` is used in Rust outside of defining a new class/data type?

**Comment by ThinkingVincent** [comment]
As far as I know, the `union` keyword is not used except when defining a new union. The same goes for enum and struct, but they are all included in KEYWORDS, so I'm just suggesting it.

**Comment by joshgoebel** [comment]
> The same goes for enum and struct, but they are all included in KEYWORDS

Ha, well that's a good argument.
