### ISSUE TITLE
(JAVA) Does not highlight the reserved keyword goto

### ISSUE THREAD

**Issue by alvinsjoy** [highlightjs/highlight.js#3962]
**Describe the issue**
The `goto` keyword is actually reserved in Java but it's not used and has no functionality. Highlight.js does not highlight the reserved keyword goto.
Image below shows the demo page of the [highlight.js](https://highlightjs.org/) website.
![image](https://github.com/highlightjs/highlight.js/assets/89687635/1326c845-93a4-419d-a6ff-211dd866d4f7)
You can see that `goto` is not highlighted.
Whereas the image below shows how `goto` is highlighted in the Visual Studio Code editor.
![image](https://github.com/highlightjs/highlight.js/assets/89687635/424b8128-eba4-458f-b6f2-e69a08b889b7)

**Which language seems to have the issue?**

Java

**Are you using `highlight` or `highlightAuto`?**

highlight

**Sample Code to Reproduce**

As `goto` is actually a useless keyword, you can just type in `goto` after selecting the language as Java.

**Expected behavior**

As you can see the [screenshot](https://github.com/highlightjs/highlight.js/assets/89687635/424b8128-eba4-458f-b6f2-e69a08b889b7) of Visual Studio Code editor above, the `goto` function must be highlighted.
**Additional context**

**Comment by joshgoebel** [comment]
Seems simple enough. We'd love a PR for this.
