### ISSUE TITLE
Some styles/*.css files do not have semi-colons in portions.

### ISSUE THREAD

**Issue by m34github** [highlightjs/highlight.js#3966]
**Describe the issue/behavior that seems buggy**

Some theme's css files do not have semi-colons in portions.
It does not affect to behaviors, is just for the coding-style.

e.g. [src/styles/googlecode.css](https://github.com/highlightjs/highlight.js/blob/main/src/styles/googlecode.css#L67)

**Sample Code or Instructions to Reproduce**

The following css files do not have semi-colon(s).

- src/styles/googlecode.css
- src/styles/hybrid.css
- src/styles/lightfair.css
- src/styles/obsidian.css
- src/styles/tokyo-night-dark.css
- src/styles/tokyo-night-light.css

**Expected behavior**

Not recommended
```css
.foo {
  color: #FFF
}
```

Recommended
```css
.foo {
  color: #FFF;
}
```

**Additional context**

I could not find the coding-style-guide, linter-rule, or something like that.
However, In my opinion, it is better to write codes in the same way.

**Comment by joshgoebel** [comment]
If we were to start linting the CSS we'd need to:

- agree on a linter
- agree on linting rules
- add the linting to CI
- reject PRs that aren't linted
- etc... 

We really don't want to add additional obstacles to contributing, so I think we're just not that interested in linting our CSS.  Also, the final build assets should already be CSS beautified/standardized.

**Comment by m34github** [comment]
I also think that linter is not needed now.
My suggestion had focused on only that adding semi-colon to css files.

If it's not sensitive about code-format in here's community, I'm ok that this issue can be closed.

**Comment by joshgoebel** [comment]
> My suggestion had focused on only that adding semi-colon to css files.

Without a linter and enforcement you can't guarantee they will even stay put - or that new themes added would be consistent... _given that_ it's not worth our time to even review such a PRs for mistakes. 

> not sensitive about code-format in here's community

We do have linting for the JS _code_, and our CSS files are "clean" even if not perfectly consistent.  So we absolutely have standards, they just aren't as high as perhaps some would like.
