### ISSUE TITLE
download page bug

### ISSUE THREAD

**Issue by BenRacicot** [highlightjs/highlight.js#3971]
Hi, when I select "all languages" on [the downloads page ](https://highlightjs.org/download) and download, I get a 139 byte file that cannot be unzipped. Just reporting what I believe its a bug, hope this is helpful.

**Comment by tomwt-awa** [comment]
Because the file will be too big. You'll get it if you open the zip file with a text editor. It'll be ok if you download "common" only.

**Comment by joshgoebel** [comment]
@allejo Couldn't we first add up the sizes of all the grammars (pre-zip) and have some magic threshold we set that tells people they picked too many - and to try again?  We should not encourage builds with ALL the grammars anyways as that's just silly and forcing the browser to do extra parsing over and over for obscure grammars someone will never need.

**Comment by BenRacicot** [comment]
Yeah @joshgoebel was going to reply something similar, I actually didn't need the download because of Github files/releases.

Was just reporting to help out.

**Comment by joshgoebel** [comment]
Do we have an "all" build in releases?

**Comment by janbrasna** [comment]
FYi this is also tracked in https://github.com/highlightjs/highlightjs.org/issues/15

**Comment by joshgoebel** [comment]
Closing as dup of #15 from the website repo.
