### ISSUE TITLE
(typescript) Using `namespace` as a variable name breaks highlighter state

### ISSUE THREAD

**Issue by pkaminski** [highlightjs/highlight.js#3972]
**Describe the issue**
When I use `namespace` as the name of the variable, everything that follows is highlighted incorrectly.  While `namespace` is a TS keyword it's fine to use it as a variable name too.

**Which language seems to have the issue?**
`typescript`

**Are you using `highlight` or `highlightAuto`?**
`highlight`

**Sample Code to Reproduce**
```ts
const message = 'foo';
const namespace = 'bar';
function baz() {}
```

https://jsfiddle.net/g0fu1zmw/1/
https://www.typescriptlang.org/play?#code/MYewdgzgLgBAtgUwhAhgcwTAvDA5AMxBFwG4BYAKFEljBUQgAcVhMdcAjFAJ1MvwCuYYFACW4GFwBeACgCUMAN4BfSkA

**Expected behavior**
See GitHub or TS playground renderings above, for example.  It's fine (though not ideal) if `namespace` is highlighted as a keyword in this context, as long as it doesn't break highlighting of everything that follows.

**Additional information**
Original problem report in https://github.com/Reviewable/Reviewable/issues/1134.

**Comment by joshgoebel** [comment]
Can you provide a more complex example than this for proper namespace use:

```
namespace Validation {
```

Or are namespaces always so simple?

**Comment by pkaminski** [comment]
I'm far from an expert on TypeScript but I think that's pretty much it, though it can be prefixed by a few other keywords, and can also be nested in case that matters:
```ts
declare namespace Foo {
  export namespace Bar {
  }
}
```

**Comment by joshgoebel** [comment]
Then I think we could solve this with a multi-matcher (see second example of beginScope: https://highlightjs.readthedocs.io/en/latest/mode-reference.html#beginscope)... to match patterns like:

`"namespace" [className]`

Much better than the existing match namespace and then get stuck until you see a `{`.

**Comment by akhtarmdsaad** [comment]
Please go through my pull request. I think it resolves the issue.
