### ISSUE TITLE
[Request] Documentation: How to use the Emitter API?

### ISSUE THREAD

**Issue by rauschma** [highlightjs/highlight.js#3974]
**Is your request related to a specific problem you're having?**\
I’m using Highlight.js to syntax-highlight code for LaTeX documents. I tried but failed to use the Emitter API.

**The solution you'd prefer / feature you'd like to see added...**\
I created a repository that would be enough documentation (if it worked...): https://github.com/rauschma/hljs-emitter

**Any alternative solutions you considered...**\
My current workaround is to use package `lowlight`. But I don’t need the intermediate tree it creates; the Emitter API itself would be enough.

**Comment by joshgoebel** [comment]
Please see:

- https://highlightjs.readthedocs.io/en/latest/mode-reference.html#emittokens
- https://github.com/highlightjs/highlight.js/issues/3619

We now allow grammars to "bring their own emitters"... that's what is documented at the first link - and what I think perhaps you should try.  There is also a private (but _stable_) API to replace the main Highlight.js entirely...  That seems to be what you're trying now, but I can't offer real support for that, as it's private (and unsupported) - but if you want to learn about it:

- read `TokenTreeEmitter` in the source
- read the `lowlight` source as that's how lowlight works

**Comment by joshgoebel** [comment]
Ignore my first response, you don't want to replace our parser - you want to replace the emitter itself.

The `__emitter` API (using our parser, but replacing our emitter) is a private (_yet quite stable_) API. As it's private [ie, unsupported] I can't offer real support, but if you want to learn about it I'd suggest:

- read `TokenTreeEmitter` in the source
- read the `lowlight` source carefully (as it uses this same private API)

**Comment by rauschma** [comment]
In case you are interested – this is how I use Highlight.js to produce PDFs with syntax-highlighted code: https://fosstodon.org/@rauschma/111800543890963559
