### ISSUE TITLE
Invalid RegExp when using `highlightAll()`

### ISSUE THREAD

**Issue by kasvith** [highlightjs/highlight.js#3982]
**Describe the issue/behavior that seems buggy**
Hi, it seems when using `highlightAll()` the following error throws out

```
Invalid regular expression: /(?!-)([!#\$%&*+.\\/<=>?@\\\\^~-]|(?!([(),;\\[\\]\`|{}]|[_:"']))(\\p{S}|\\p{P}))--+|--+(?!-)([!#\$%&*+.\\/<=>?@\\\\^~-]|(?!([(),;\\[\\]\`|{}]|[_:"']))(\\p{S}|\\p{P}))/mu: Invalid escape
```

**Sample Code or Instructions to Reproduce**

**Expected behavior**

No regexp errors

**Additional context**

Im using NextJS 14.1.0
This error only happens in production build

**Comment by joshgoebel** [comment]
Does your engine support `\p`.  That is a requirement.

**Comment by joshgoebel** [comment]
Is this reproducible in the latest version of Chrome?

**Comment by joshgoebel** [comment]
Closing along with #4013. (lack of response). Current best guess is a broken build system corrupting the JS code.

**Comment by kasvith** [comment]
Hi, sorry i didnt notice your replies, will check and get back

**Comment by joshgoebel** [comment]
That's a nice little trick until it better supports these regex constructs.
