### ISSUE TITLE
[Request] BASH Improvement Fast....

### ISSUE THREAD

**Issue by TbhV2** [highlightjs/highlight.js#3983]
**Is your request related to a specific problem you're having?**
bash language/shell for terminal like need improvement

**The solution you'd prefer / feature you'd like to see added...**
&& || etc need syntax highlighting and highlight arguments

**Any alternative solutions you considered...**
Commands preview (syntax highlighting) for my web 

**Additional context...**
Make it fast

**Comment by joshgoebel** [comment]
Please provide an example or two of "highlight arguments". Thanks.

**Comment by TbhV2** [comment]
Also depends on program

Commonly used with start **-**

eg:

wget -O filename link

etc other commands same some commands without **-**  this was diffcult ? & Command a first command also a color need like zsh,etc

**Comment by joshgoebel** [comment]
> Commonly used with start -

But not always, so how could we know what is an isn't an argument?  I'm not sure only highlighting `-` arguments is so good...

**Comment by TbhV2** [comment]
Yes, also diffcult because every program depend, highlight after` -word`, `-` a color and `word` another color or same color

**Comment by joshgoebel** [comment]
Closing this as out of scope.
