### ISSUE TITLE
Python code not fully highlighted

### ISSUE THREAD

**Issue by pmac-dev** [highlightjs/highlight.js#3984]
**Describe the issue**
Some parts of this Python code are not highlighted. 

**Which language seems to have the issue?**
Python

**Are you using `highlight` or `highlightAuto`?**

highlightAll()

**Sample Code to Reproduce**
Please check this jsfiddle:

https://jsfiddle.net/dz32yks9/

or this screenshot, html+HighlightJS:

![mywebsite](https://github.com/highlightjs/highlight.js/assets/63117811/b3a2da8a-75d8-4424-a872-a21ff75de62d)

**Expected behavior**
Functions, variables and constants should be highlighted too, just like Github or VSCode:

![github](https://github.com/highlightjs/highlight.js/assets/63117811/26d11eb3-f465-42ce-8848-fe73abadc822)

![VSCode](https://github.com/highlightjs/highlight.js/assets/63117811/b2a0d722-f72a-4379-8ae5-3ee82c2ef023)

**Additional context**

**Comment by ghomem** [comment]
Reproducible on the demo as well:

![Screenshot_20240213_002645](https://github.com/highlightjs/highlight.js/assets/3352900/0624602b-dad7-4a71-8ba9-48bc91e4bc70)

**Comment by joshgoebel** [comment]
A PR would be very welcome, but I'm closing this as a dup of #2500... we're very open to these types of improvements for all grammars, but we don't need 189 individual issues.

**Comment by joshgoebel** [comment]
Ruby, Wren, and other grammars have some rules that could be examined if you wanted to work on a PR...
