### ISSUE TITLE
(C#) Assigning a variable in code sample brings to tottaly different highlight

### ISSUE THREAD

**Issue by HedgehogNSK** [highlightjs/highlight.js#3990]
**Describe the issue**
Hello. I'm using your extension for blogger platform. I just found out that if sample of code doesn't contain any variable assignment, then highlighter doesn't determine that the language of a sample is C#. 
I use "[vs2015](https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/styles/vs2015.min.css)" style template

**Are you using `highlight` or `highlightAuto`?**
I use snippet from the highlight homepage. If this question asks do I set language name in `<code>` tag explicitly? Then the answer is: I tried them both to determine the issue.

**Sample Code to Reproduce**
```
public partial class MainWindow : Window
{
    DisposableBag disposable; // DisposableBag is struct, no need new and don't copy

    public MainWindow()
    {
        Observable.IntervalFrame(1).Subscribe().AddTo(ref disposable);
        Observable.IntervalFrame(1).Subscribe().AddTo(ref disposable);
        Observable.IntervalFrame(1).Subscribe().AddTo(ref disposable);
    }

    void OnClick()
    {
        Observable.IntervalFrame(1).Subscribe().AddTo(ref disposable);
    }

    protected override void OnClosed(EventArgs e)
    {
        disposable.Dispose();
    }
}
```
When I don't set language explicitly `<code>`:
![image](https://github.com/highlightjs/highlight.js/assets/23266328/385996ee-1525-4c6e-b383-678bf032989a)

When I set language explicitly `<code class="cs">`:
![image](https://github.com/highlightjs/highlight.js/assets/23266328/c38265c7-2497-4474-8390-e0def1d8e0f6)

When I don't set language explicitly, but I add assignment of some value (ex. `var x = 1;`):
![image](https://github.com/highlightjs/highlight.js/assets/23266328/86f95c9c-ead2-45b6-b93b-28ce6f3ac87a)

**Expected behavior**
1. AutoDetection has to detect C# language even if there is no assignment of any variables.
2. Names of classes, methods, types, as well  as keywords as "ref", "class" etc  have to by highlighted

**Comment by dschach** [comment]
The code you provided auto-detects to scss. 

scss: relevance 21, csharp: 19

I don't know how to "fix" it, or even if it needs to be fixed. Auto-detect is difficult and should probably not be used, as it will be deprecated with v12.0 anyway, I believe. It's best to specify the language for each of your snippets.

**Comment by joshgoebel** [comment]
Yeah, we make no guarantees about auto-detect, it's more of a toy than a precision tool.  Specify the language and you'll get much better results.
