### ISSUE TITLE
(basic) Closing quotation marks are not required for a PRINT statement (gwbasic)

### ISSUE THREAD

**Issue by Ruard** [highlightjs/highlight.js#3996]
**Describe the issue**
I may be wrong and this probably depends on _basic_ dialect, but it seems (I found some old code that runs) that for _gwbasic_ closing quotation marks are not required for a PRINT statement. The interpreter seems to assume that the end of the line closes the string (like there was a quotation mark).

In this case, when an ending quotation mark is omitted, the following line(s) are part of the string until a quotation mark is found.

![afbeelding](https://github.com/highlightjs/highlight.js/assets/15624821/7d68f6cc-c8df-4822-9b28-11abd51fa56c)

**Which language seems to have the issue?**
basic. And in my case specifically for gwbasic code.

**Are you using `highlight` or `highlightAuto`?**
highlight: language-basic

**Sample Code to Reproduce**

```
10	CLS
20	INPUT "Hoeveel paarden ";H:CLS
30	LOCATE 1,1:PRINT "╔════════╦════════════════════╗
40	PRINT "║ nummer ║ naam               ║
50	PRINT "╠════════╬════════════════════╣
60	FOR F=1 TO H
70	LOCATE 23,2:PRINT "Paard";F:LOCATE 23,10:INPUT P(F)
80	GET #1,P(F)
```

**Expected behavior**
At line 30 the symbols after **"** should be highlighted as string for the rest of the line. Line 40 however should start with the normal highlighting as it is not part of a continued string.

It mentioned the PRINT statement but this is also the case for e.g. CHAIN and LOAD.

**Comment by joshgoebel** [comment]
What is the behavior of most other basic intepretters I wonder when a line break is inserted in the middle of a string?

**Comment by akhtarmdsaad** [comment]
In Python also, string highlighting goes wrong

[Line break in Python](https://highlightjs.org/demo#lang=python&v=1&theme=atom-one-dark&code=c3RyaW5nID0gImhlbGxvIAkjIGhpZ2hsaWdodMQZc2hvdWxkIGJyZWFrIGhlcmUKYSA9IDUKYiA9IDYKcHJpbnQoYStiKQpXb3JsZCEhIgoKIyBXcm9uZyBjb2RlCtBgySgJIyBTeW50YXhFcnJvcgojIFJlc3Qgb2bFNyB3b3JrcyBmaW7ZcNFaXMxbdGhlIGNvcnJlY3Qgb9pFU28gdG8gaW5zZXJ0IGxpbmXnAOlpbiBzaW5nbGUgcXVvdGVkIMdtaW4gcHl0aG9uLCB3ZSBuZWVkIFwgKGJhY2tzbGFzaCnkAP3GISBwcm92aWRlcyB0cmlwyknHSnMgZm9yIG11bHRpxXfHYAonJycKxRExxgcyICdmb28gYmFyxxgzxCMJI%2BcA3A%3D%3D)

Same goes for cpp
[Cpp](https://highlightjs.org/demo#lang=cpp&v=1&theme=atom-one-dark-reasonable-min&code=CiNpbmNsdWRlIDxpb3N0cmVhbT4KCmludCBtYWluKCkKewogICAgc3RkOjpjb3V0PDwiSGVsbG8gLy8gRXJyb3IgTWlzc2luZyBlbmTEB3F1b3RlxTRXb3JsZCI7CQndKyAKxS1yZXR1cm4gMDsKfQ%3D%3D)


This mode may help to overcome this issue
https://highlightjs.readthedocs.io/en/latest/mode-reference.html#endswithparent
Any suggestions ... ?

Is there any need to open issue for them (python and cpp)??

**Comment by joshgoebel** [comment]
I don't see any issues with python or cpp examples provided. **We do not care about invalid syntax.**. If invalid syntax highlights poorly (or not at all), that is not our concern.  We do our very best to highlight valid syntax.

**Comment by Ruard** [comment]
> What is the behavior of most other basic intepretters I wonder when a line break is inserted in the middle of a string?

I'm not into basic interpreters, so don't take my word for it. But I suppose there is a difference between e.g. Qbasic and GWbasic. The first one reads blocks of code while GWbasic reads one line of code, though this line may contain multiple statements separated by colons. If I'm correct Qbasic allows line numbers while for GWbasic the line numbers are mandatory.

I think your other comment about invalid syntax is interesting. Though in this case the syntax is valid and code will run, you can argue that it is at least bad code. Like invalid XML that works because the browser fills in the gaps. This is a thin line.

The solution I had in mind (if this is not too complicated or too much work) is to create a rule for basic code that has line numbers. When (all) lines start with a line number then an 'open string' is closed when either a quotation mark or line break is encountered and in other cases this rule is ignored. But I can live with it when you decide to close this issue as 'will not repair', because of this thin line.

**Comment by joshgoebel** [comment]
> Though in this case the syntax is valid and code will run

The one python example I tried was not valid.  But valid or not the highlighting looked "fine" to me for most or all the cases - so it's not clear to me what behavior you're expecting in the CPP or Python cases if you don't show a "correct" version (perhaps from another highlighter, etc).

**Comment by Ruard** [comment]
@joshgoebel Please note, this issue is **not** about Python or CPP, it's about **Basic**. So can we please focus on Basic?

**Comment by joshgoebel** [comment]
I go where the wind blows. :-)

I did some quick research.  I think we'd be open to a PR that allows BASIC strings to terminate with EITHER the first `"` or newline that is found - whichever comes first.
