### ISSUE TITLE
[Request] Support namespaced tagged template strings in JavaScript

### ISSUE THREAD

**Issue by aral** [highlightjs/highlight.js#4001]
**Is your request related to a specific problem you're having?**

[Kitten](https://codeberg.org/kitten/app) exposes `html` and `css` tagged template strings not from the global namespace but from `globalThis.kitten` (so as not to pollute the global namespace).

e.g.,

```js
export default () => kitten.html`
  <h1>I’m not highlighted *sadface*.</h1>
`
```

Currently, highlight.js does not recognise and highlight these as HTML.

**The solution you'd prefer / feature you'd like to see added...**

I’d love to see the HTML and CSS tagged template string match criteria expanded so they match `.html` and `.css`, not just `html` and `css` so that, for example

```
someNamespace.html`…` 
```

would also be recognised as HTML.

**Any alternative solutions you considered...**

Leaving a space after the dot works since JavaScript is whitespace agnostic but it looks and feels wrong to have to do that just to make the syntax highlighter happy :)

**Comment by joshgoebel** [comment]
Can you show me an article or anything that might suggest this is as prolific a "standard" as uppercase class names in JS?  We do in several cases highlight idiomatic code (past the syntax itself) - but I'm not certain this yet rises to that same level...

**Comment by joshgoebel** [comment]
@allejo Any thoughts here?  Am I being to string in my thinking?

**Comment by aral** [comment]
> Can you show me an article or anything that might suggest this is as prolific a "standard" as uppercase class names in JS? We do in several cases highlight idiomatic code (past the syntax itself) - but I'm not certain this yet rises to that same level...

I’m not sure about any articles but the TypeScript Language Server (used in VSCode, etc.) correctly handles these.

e.g.,

![Screenshot of a compound tagged template string being correctly syntax highlighted in VSCode using the TypeScript Language Server](https://github.com/highlightjs/highlight.js/assets/41798/e6aaf5c5-1797-4416-b1e3-8be809ce1589)

**Comment by joshgoebel** [comment]
Is it matching on <code>anythingatall.html``</code>  - or does it only work for kitten?

**Comment by aral** [comment]
@joshgoebel On anything at all; I don’t think Microsoft know or care about Kitten ;)
