### ISSUE TITLE
(request org repo) highlightjs-unison

### ISSUE THREAD

**Issue by runarorama** [highlightjs/highlight.js#4004]
I would like to request the creation of a `highlightjs-unison` repository for my 3rd party grammar.

- [x] I have an existing personal repository ready to go

### Metadata

- Grammar Name: _Unison_
- Link to repo: https://github.com/runarorama/highlightjs-unison

### Requirements

- [x] I've read the [language Contributor Checklist](https://highlightjs.readthedocs.io/en/latest/language-contribution.html)
- [x] I've read the [Language Contribution Guide](https://github.com/highlightjs/highlight.js/blob/main/extra/3RD_PARTY_QUICK_START.md)
- [x] I'm currently willing to support and maintain this grammar over time
- [x] That repo includes a `dist` folder with CDN-ready `CJS` and `ESM` builds
- [x] That `README.md` includes examples of simple web usage
- [x] That `README.md` includes examples of Node.js usage

### Afterwards

Submit a PR that:

- [x] adds mention of your new language to `CHANGES.md`
- [x] updates `SUPPORTED_LANGUAGES.md` in the main library

**Comment by joshgoebel** [comment]
Are you wanting us to link to your repo or to host the repo here?

**Comment by joshgoebel** [comment]
Done.  Push your repo on over and I'll merge the other PR.

https://github.com/highlightjs/highlightjs-unison

**Comment by runarorama** [comment]
It seems I don't have permission to push there. Should I make a PR against that repo?

**Comment by joshgoebel** [comment]
You have a pending invite you have not accepted.

**Comment by runarorama** [comment]
Ah yes. Pushed the repo
