### ISSUE TITLE
(1C) Authentic syntax highlighting

### ISSUE THREAD

**Issue by LazarenkoA** [highlightjs/highlight.js#4010]
Hello. What do I need to do to add a new theme for the 1C language? Currently, there is no familiar theme (like in the configurator). I have looked through all the themes on https://highlightjs.org/demo.

Example of highlighting in the configurator

![image](https://github.com/highlightjs/highlight.js/assets/15386101/f23fd69c-72d6-499a-ad9f-46beec5f97af)

**Comment by joshgoebel** [comment]
https://highlightjs.readthedocs.io/en/latest/theme-guide.html
