### ISSUE TITLE
Inconsistent highlighting of numbers

### ISSUE THREAD

**Issue by ndattani** [highlightjs/highlight.js#4011]
**Describe the issue/behavior that seems buggy:**

Notice that the number 035 is black but all other numbers in that column are orange:

![image](https://github.com/highlightjs/highlight.js/assets/1163013/23f603af-55c0-4a0b-8c00-31d58cb16dd4)

See this: https://mattermodeling.stackexchange.com/a/12545/5

**Sample Code or Instructions to Reproduce:**

```
aug-cc-pV6Z:    -0.499999 276396 663  (PySCF, 127 functions), default settings
aug-cc-pV7Z:    -0.499999 752574 58   (PySCF, 189 functions), default settings
aug-cc-pV8Z:    -0.499999 966893 035  (PySCF, 268 functions), default settings
aug-cc-pV9Z:    -0.499999 977357 467  (PySCF, 367 functions), default settings
aug-cc-pV10Z:   -0.499999 980721 463  (PySCF, 485 functions), default settings
```

**Comment by joshgoebel** [comment]
Numbers don't start with a 0 in whatever language grammar you are using here.  Please provide additional detail on the language if you believe a prefix 0 number is valid in whichever language this is supposed to be.

**Comment by ndattani** [comment]
@joshgoebel [Apparently](https://meta.stackexchange.com/questions/184108/what-is-syntax-highlighting-and-how-does-it-work#comment1243067_184108) the language is "automatically detected". Based on the text that I provided, are you able to determined which language this is?

**Comment by joshgoebel** [comment]
You could use the web inspector on SE - the HTML generated might tell you.  Otherwise, no idea.

But as this is not a problem with Highlight.js - it's not intended to highlight random text SE - I'm closing this issue.
