### ISSUE TITLE
Getting SyntaxError: Invalid regular expression in production build in Next.js but working fine in development mode

### ISSUE THREAD

**Issue by PriyobrotoKar** [highlightjs/highlight.js#4013]
**Describe the issue/behavior that seems buggy**
I am getting a Application error: a client-side exception has occurred (see the browser console for more information) in the production build but not in development mode. I need help...

Here is the error in brower's console:
```
SyntaxError: Invalid regular expression: /(?!-)([!#\$%&*+.\\/<=>?@\\\\^~-]|(?!([(),;\\[\\]\`|{}]|[_:"']))(\\p{S}|\\p{P}))--+|--+(?!-)([!#\$%&*+.\\/<=>?@\\\\^~-]|(?!([(),;\\[\\]\`|{}]|[_:"']))(\\p{S}|\\p{P}))/mu: Invalid escape
    at RegExp (<anonymous>)
    at t (5548-712049cab3b9f644.js:1:15197)
    at a (5548-712049cab3b9f644.js:1:17673)
    at 5548-712049cab3b9f644.js:1:18319
    at Array.forEach (<anonymous>)
    at a (5548-712049cab3b9f644.js:1:18299)
    at 5548-712049cab3b9f644.js:1:18571
    at R (5548-712049cab3b9f644.js:1:18575)
    at 5548-712049cab3b9f644.js:1:19606
    at Array.map (<anonymous>)
```

**Sample Code or Instructions to Reproduce**
This is the client component :
```
"use client";
import hljs from "highlight.js";
import { useEffect, useState } from "react";

const Codeblock = ({ children }: { children: string }) => {
  const [language, setLanguage] = useState<string | undefined>("");
  const [mounted, setIsMounted] = useState(false);
  useEffect(() => {
    console.log(children);
    console.log(mounted);
    if (mounted) {
      hljs.safeMode();
      hljs.highlightAll();
    }
  }, [mounted, children]);

  useEffect(() => {
    if (typeof window !== "undefined") {
      setIsMounted(true);
    }
  }, []);
  if (!mounted) {
    return;
  }
  return (
    <>
      <pre className="relative">
        <code className="bg-none">{children}</code>
      </pre>
    </>
  );
};

export default Codeblock;

```

And I am calling the client component in the parent  like this:
`return <Codeblock key={uuid()}>{innerHTML}</Codeblock>;`

**Expected behavior**
It should highlight the code in the production build like in the development mode, but its showing this error.

**Comment by fujita-h** [comment]
I'm having the same issue on my Next.js production build.
From the regular expression pattern output in the error, I found that it was a Haskell grammar.
https://github.com/highlightjs/highlight.js/blob/105a11a13eedbf830c0e80cc052028ceb593837f/src/languages/haskell.js#L17-L24

The error no longer occurs by excluding Haskell's grammar.
If you don't need Haskell's grammar, the easiest workaround is to not use it.

Additionally, in my environment, this issue did not occur with Next.js 14.1.1, but did occur with Next.js 14.1.3. Considering that the problem does not occur in dev mode but occurs in production, the problem may be in Next.js.

**Comment by joshgoebel** [comment]
Does it work if you only remove the `uniSymbol` portion of Haskell?

**Comment by joshgoebel** [comment]
>  5548-712049cab3b9f644.js

Please use the library on it's own without running it thru a build system to confirm the build system itself is not the problem.  The builds we provide work - the regex you list above doesn't - but that's an artifact of your build system, not something we ship.

**Comment by triozer** [comment]
> Closing for lack of response. Right now it appears to be a broken build system producing an invalid build product.

@joshgoebel I'm reopening this issue as I'm experiencing the same problem. After some investigation, I discovered [a related issue](https://github.com/vercel/next.js/issues/19303) in the Next.js repository, which suggests that the problem persists. It appears that the Next.js build system does not fully support the regular expressions used in Haskell, as outlined in #3982. This might be causing the broken build system to produce an invalid build product. Without a viable workaround, other than the excluding Haskell.

**Comment by joshgoebel** [comment]
> which suggests that the problem persists. 

Yes, it's only closed here because it's obviously not our issue - not our code.  The related issue you linked to is pretty clear... once this is fixed in Next.js then all should be well. Nothing we can do.

> Without a viable workaround

Seems the related issue offered a viable workaround of using `plugin-transform-unicode-regex` to transcode the JS back to something Next.js doesn't currently choke on.  Also seems running an older path release of Next.js might fix things?

**Comment by triozer** [comment]
> Nothing we can do.

Yes, I was just trying to document why this issue was happening and redirect user to the Next.js issue. So this one can be closed again. :)

**Comment by kasvith** [comment]
Hi, for nextjs adding `highlight.js` to  https://nextjs.org/docs/app/api-reference/next-config-js/transpilePackages solved the issue

**Comment by UPSxACE** [comment]
> Hi, for nextjs adding `highlight.js` to https://nextjs.org/docs/app/api-reference/next-config-js/transpilePackages solved the issue

This kind of error is still happening, but thank you, that solved it
![image](https://github.com/highlightjs/highlight.js/assets/69174687/4b497161-783d-4911-a539-f343626e646f)

**Comment by kasvith** [comment]
> > Hi, for nextjs adding `highlight.js` to https://nextjs.org/docs/app/api-reference/next-config-js/transpilePackages solved the issue
> 
> This kind of error is still happening, but thank you, that solved it ![image](https://private-user-images.githubusercontent.com/69174687/347203655-4b497161-783d-4911-a539-f343626e646f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1NzYwNzcsIm5iZiI6MTcyMDU3NTc3NywicGF0aCI6Ii82OTE3NDY4Ny8zNDcyMDM2NTUtNGI0OTcxNjEtNzgzZC00OTExLWE1MzktZjM0MzYyNmU2NDZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEwVDAxNDI1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhZWUyNTVlYzY3OWIxMWIyZjljNWE2Mjc1YjNlYmNjYTY0Njg0NWM4NTk5YzkyMzQyNWQzZDAzNGNhNWVlZjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lCDGBd8mcXHkvcc8CMU6x87M7hJDjUM81sKmovW0QEM)

Hmm gor me it was actually gone. but the problem was even adding to `transpilePackagaes` didnt work as expected, so i had to add it only in prod build

**Comment by pradeepcep** [comment]
For me, the error persisted even after adding `highlight.js` (version `11.10.0`) to `transpilePackages` in NextJS (version `14.2.18` using `node` version `v20.17`).

I figured the issue was with only a specific language's grammer as pointed out by @fujita-h above. So instead of loading the whole package with all common languages, I registered only those languages which I needed. Thankfully, the error wasn't from one of these.

```js
import "highlight.js/styles/a11y-dark.css";
import hljs from "highlight.js/lib/core";
import javascript from "highlight.js/lib/languages/javascript";
import json from "highlight.js/lib/languages/json";
import xml from "highlight.js/lib/languages/xml";
import python from "highlight.js/lib/languages/python";
import css from "highlight.js/lib/languages/css";
import sql from "highlight.js/lib/languages/sql";
import yaml from "highlight.js/lib/languages/yaml";

hljs.registerLanguage("javascript", javascript);
hljs.registerLanguage("js", javascript);
hljs.registerLanguage("json", json);
hljs.registerLanguage("html", xml);
hljs.registerLanguage("xml", xml);
hljs.registerLanguage("python", python);
hljs.registerLanguage("css", css);
hljs.registerLanguage("sql", sql);
hljs.registerLanguage("yaml", yaml);
```

After doing this, the build passes successfully even if you don't add `highlight.js` to `transpilePackages` in `next.config.mjs`.

**Comment by joshgoebel** [comment]
Curious, are python and xml "broken" as well in Next.js?  They all use `\p` expressions.

**Comment by joshgoebel** [comment]
So the above seems to indicate xml and python work... can someone play with the haskell string in next js?

```
  const uniSymbol = '(\\p{S}|\\p{P})' // Symbol or Punctuation
```

Is there something about converting it to regex dynamically that breaks - or if you wrote it out explicitely:

```
  const uniSymbol = /(\p{S}|\p{P})/u
```

Is this still invalid code in Next.js?

**Comment by devdubby** [comment]
> So the above seems to indicate xml and python work... can someone play with the haskell string in next js?
> 
> ```
>   const uniSymbol = '(\\p{S}|\\p{P})' // Symbol or Punctuation
> ```
> 
> Is there something about converting it to regex dynamically that breaks - or if you wrote it out explicitely:
> 
> ```
>   const uniSymbol = /(\p{S}|\p{P})/u
> ```
> 
> Is this still invalid code in Next.js?

I think I'm having trouble dynamically converting it to a regular expression. If I do it like below, I get a weird build result.

```js
const regex = '__(\\S(?:.*?\\S)?)__';
const result = new RegExp(`${regex}`);

// => __(\\\\S(?:.*?\\\\S)?)__
```

```js
const regex = '/__(\S(?:.*?\S)?)__/';
const result = new RegExp(`${regex.source}`);
// => /__(\S(?:.*?\S)?)__/
```
