### ISSUE TITLE
Add "jsonc" alias

### ISSUE THREAD

**Issue by cpfeiffer** [highlightjs/highlight.js#4018]
@glen-84 Would you be happier if we added a "jsonc" alias?

_Originally posted by @joshgoebel in https://github.com/highlightjs/highlight.js/issues/2016#issuecomment-538745831_

rouge and shiki support jsonc as identifier, so it would be nice to have this in highlightjs as well.

See
- https://shiki.style/languages
- https://github.com/rouge-ruby/rouge/issues/1028

**Comment by joshgoebel** [comment]
Sounds reasonable.

**Comment by BackupMiles** [comment]
Hi! Can this issue be assigned to me?

**Comment by joshgoebel** [comment]
Just make a PR - people aren't rushing in huge lines to complete these issues. :)

**Comment by BackupMiles** [comment]
Sure will! Thank you :D

**Comment by BackupMiles** [comment]
Quick question: would a "jsonc" alias suffice to the json.js returned object?
From what I gather the json.js language already accepts comments

**Comment by joshgoebel** [comment]
Yes we just need to add the alias.
