### ISSUE TITLE
Download from Website does not work with all/most languages selected

### ISSUE THREAD

**Issue by girlpunk** [highlightjs/highlight.js#4019]
**Describe the issue/behaviour that seems buggy**
Downloading from the website does not work with a large number of languages selected.

**Sample Code or Instructions to Reproduce**
1. Browse to https://highlightjs.org/download
2. Tick the "Select all languages" box
3. Click download
4. A file called `highlight.zip` will be downloaded, however this is not a ZIP file. It contains the following
```
{"errorType":"Function.ResponseSizeTooLarge","errorMessage":"Response payload size exceeded maximum allowed payload size (6291556 bytes)."}
```

**Expected behaviour**
A valid ZIP file should be downloaded, containing the library

**Comment by joshgoebel** [comment]
Closing.  Duplicate of https://github.com/highlightjs/highlightjs.org/issues/15.
