### ISSUE TITLE
Cannot checkout 11.9.0 tag

### ISSUE THREAD

**Issue by aral** [highlightjs/highlight.js#4027]
**Describe the issue/behavior that seems buggy**

---

__Update:__ The correct commit appears to be: 2a4acf4.

---

When you git pull from the repo, you do not get the 11.9.0 tag.

On Github, this is shown:

![Screenshot of Github interface showing warning that commit does not belong to this repository](https://github.com/highlightjs/highlight.js/assets/41798/601e5ae1-c6d6-4f94-bd1d-534f6a2257d2)

Can one of the contributors please fix the tag so folks can backport new commits in main to it, especially since main appears to have breaking changes in it (please see #4026).

Thanks! :)

**Comment by joshgoebel** [comment]
11.9.0 now points back into the history of main.  Thanks for report!
