### ISSUE TITLE
(request org repo) highlightjs-postscript

### ISSUE THREAD

**Issue by ThomasRinsma** [highlightjs/highlight.js#4030]
I would like to request the creation of a `highlightjs-postscript` repository for my 3rd party grammar.

- [X] I have an existing personal repository ready to go

### Metadata

- Grammar Name: `postscript`
- Link to repo: https://github.com/ThomasRinsma/highlightjs-postscript

### Requirements

- [X] I've read the [language Contributor Checklist](https://highlightjs.readthedocs.io/en/latest/language-contribution.html)
- [X] I've read the [Language Contribution Guide](https://github.com/highlightjs/highlight.js/blob/main/extra/3RD_PARTY_QUICK_START.md)
- [X] I'm currently willing to support and maintain this grammar over time
- [X] That repo includes a `dist` folder with CDN-ready `CJS` and `ESM` builds
- [X] That `README.md` includes examples of simple web usage
- [X] That `README.md` includes examples of Node.js usage

### Afterwards

Submit a PR that:

- [ ] adds mention of your new language to `CHANGES.md`
- [ ] updates `SUPPORTED_LANGUAGES.md` in the main library

**Comment by joshgoebel** [comment]
Sorry somehow I missed this.  Still wanting the repo?

**Comment by ThomasRinsma** [comment]
No worries, sure, if it's useful for the project!

**Comment by joshgoebel** [comment]
Done. https://github.com/highlightjs/highlightjs-postscript
