### ISSUE TITLE
Could not find the language 'HTML, XML'

### ISSUE THREAD

**Issue by Antecer** [highlightjs/highlight.js#4033]
if `lang` is `xml`, the language name will result `HTML, XML`
```js
function test(code, lang) {
	let language = hljs.getLanguage(lang)?.name ?? 'plaintext';
	return hljs.highlight(code, {language}).value;
}
```
Then i will get this error:
![image](https://github.com/highlightjs/highlight.js/assets/8684916/2d9b48de-eef1-494b-9fd0-8330c7833634)

if i replace `HTML, XML` to `xml`, it will work normal:
```
function test(code, lang) {
	let language = hljs.getLanguage(lang)?.name ?? 'plaintext';
	if (language == 'HTML,xml') language = 'xml';
	return hljs.highlight(code, {language}).value;
}
```

**Comment by joshgoebel** [comment]
> if lang is xml, the language name will result HTML, XML

This is correct. You are supposed to pass the shortname (ie, `xml`) to `highlight`, not the name... the name is only for completness.
