### ISSUE TITLE
(C#) `file` keyword/accessibility modifier isn't highlighted

### ISSUE THREAD

**Issue by Arthri** [highlightjs/highlight.js#4050]
**Describe the issue**
The `file` accessibility modifier is left unhighlighted when applied to top-level types

**Which language seems to have the issue?**
C#

**Are you using `highlight` or `highlightAuto`?**
`highlight`

...

**Sample Code to Reproduce**

```cs
file class K {}
public class K {}
```
[Highlight.js demo](https://highlightjs.org/demo#lang=csharp&v=1&theme=an-old-hope&code=ZmlsZSBjbGFzcyBLIHt9CnB1YmxpY8sS)

**Expected behavior**
The file class keyword shares the same color as other accessibility modifiers such as public and private

**Additional context**
None

**Comment by alvinsjoy** [comment]
Hi @joshgoebel, can this be closed if `file` is added to the [CONTEXTUAL_KEYWORDS](https://github.com/highlightjs/highlight.js/blob/9267f5022c14bcd848b8a9024f8c88230fcf7b54/src/languages/csharp.js#L115-L150) as stated in the [docs](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/#contextual-keywords)? If yes, I would like to do it.
Re: [C# docs on file](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/file)
https://github.com/highlightjs/highlight.js/blob/9267f5022c14bcd848b8a9024f8c88230fcf7b54/src/languages/csharp.js#L115-L150

**Comment by joshgoebel** [comment]
Most likely, that array is just merged with regular KEYWORDS at this point.

**Comment by alvinsjoy** [comment]
> Most likely, that array is just merged with regular KEYWORDS at this point.

Yeah some of the new [Contextual keywords](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/#contextual-keywords) aren't different from the regular keywords. And most of them are not present in the array.
These are: [args](https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/program-structure/top-level-statements#args), [dynamic](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/reference-types#the-dynamic-type), [nint](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/integral-numeric-types#native-sized-integers), [record](https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/types/records), [required](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/required) and [scoped](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/statements/declarations#scoped-ref).
Should I add them to the same PR, or do I need to create a different PR?
