### ISSUE TITLE
Unnecessary output while loading the highlight.js plugin.

### ISSUE THREAD

**Issue by Daucloud** [highlightjs/highlight.js#4056]
**Describe the issue/behavior that seems buggy**
I used the command `npm i highlight@latest --save` to install the highlight.js, and it is shown that the version is `11.9.0` in the `package.json`. However, when I execute the command `hexo g` (as for hexo , you can learn about it [here](https://github.com/hexojs/hexo)), it still output the message `Version 9 of Highlight.js has reached EOL and is no longer supported.
Please upgrade or ask whatever dependency you are using to upgrade.
https://github.com/highlightjs/highlight.js/issues/2877`. Is this message unnecessary?
![](https://img.picgo.net/2024/05/23/2024052315045306bef55d72e33828d.png)

**Sample Code or Instructions to Reproduce**

**Comment by joshgoebel** [comment]
Version 9 is EOL and contains serious security vulnerabilities - hence the warning. https://github.com/highlightjs/highlight.js/blob/main/SECURITY.md

I'd say hexo or one of it's dependencies is pulling in the old version.  Perhaps try https://stackoverflow.com/questions/25997519/how-to-view-the-dependency-tree-of-a-given-npm-module
