### ISSUE TITLE
[Request] New package release

### ISSUE THREAD

**Issue by aral** [highlightjs/highlight.js#4059]
Hey folks,

The last package release on npm was in Oct 2023 and there have been 72 commits to main since.

What are your thoughts on issuing a new release on npm?

(The markdown-it-highlight.js module depends on this and I’d love to get some of the latest commits into it.)

Thanks! :)

**Comment by joshgoebel** [comment]
Pushing 11.10.0 currently.

**Comment by aral** [comment]
Appreciate it, Josh. Thank you + hope you’re having a lovely weekend :)
