### ISSUE TITLE
(request org repo) highlightjs-mirth

### ISSUE THREAD

**Issue by casuallyblue** [highlightjs/highlight.js#4060]
I would like to request the creation of a `highlightjs-mirth` repository for my 3rd party grammar.

- [X] I have an existing personal repository ready to go

Mirth is a new strongly-typed concatenative programming language.

It is inspired by Forth, Joy, Haskell, Lisp, and monoidal category theory.

Mirth's compiler can be found here: https://github.com/mirth-lang/mirth

### Metadata

- Grammar Name: Mirth
- Link to repo: https://github.com/casuallyblue/highlightjs-mirth

### Requirements

- [X] I've read the [language Contributor Checklist](https://highlightjs.readthedocs.io/en/latest/language-contribution.html)
- [X] I've read the [Language Contribution Guide](https://github.com/highlightjs/highlight.js/blob/main/extra/3RD_PARTY_QUICK_START.md)
- [X] I'm currently willing to support and maintain this grammar over time
- [X] That repo includes a `dist` folder with CDN-ready `CJS` and `ESM` builds
- [X] That `README.md` includes examples of simple web usage
- [X] That `README.md` includes examples of Node.js usage

### Afterwards

Submit a PR that:

- [x] adds mention of your new language to `CHANGES.md`
- [x] updates `SUPPORTED_LANGUAGES.md` in the main library

**Comment by joshgoebel** [comment]
Invite pending. 

https://github.com/highlightjs/highlightjs-mirth
