### ISSUE TITLE
(request org repo) highlightjs-bend

### ISSUE THREAD

**Issue by RohanVashisht1234** [highlightjs/highlight.js#4062]
I would like to request the creation of a `highlightjs-bend` repository for my 3rd party grammar.

- [x] I have an existing personal repository ready to go

### Metadata

- Grammar Name: Bend
- Link to repo: https://github.com/RohanVashisht1234/bend-highlight-js/

### Requirements

- [x] I've read the [language Contributor Checklist](https://highlightjs.readthedocs.io/en/latest/language-contribution.html)
- [x] I've read the [Language Contribution Guide](https://github.com/highlightjs/highlight.js/blob/main/extra/3RD_PARTY_QUICK_START.md)
- [x] I'm currently willing to support and maintain this grammar over time
- [x] That repo includes a `dist` folder with CDN-ready `CJS` and `ESM` builds
- [x] That `README.md` includes examples of simple web usage
- [x] That `README.md` includes examples of Node.js usage

### Afterwards

Submit a PR that:

- [x] adds mention of your new language to `CHANGES.md`
- [x] updates `SUPPORTED_LANGUAGES.md` in the main library

**Comment by RohanVashisht1234** [comment]
Um, it has been more than 3 weeks, please reply when ever you have time.

**Comment by joshgoebel** [comment]
Sorry somehow I missed this.

https://github.com/highlightjs/highlightjs-bend

**Comment by RohanVashisht1234** [comment]
ok, I have updated https://github.com/highlightjs/highlightjs-bend
