### ISSUE TITLE
(YAML) Handling of '\'

### ISSUE THREAD

**Issue by hoehrmann** [highlightjs/highlight.js#4068]
Highlight.js seems to treat `'\'` in YAML as escaping the `'` but with `'` quoting the backslash does not escape the apostrophe in YAML.

![image](https://github.com/highlightjs/highlight.js/assets/249002/91be554c-c4c6-4c13-8125-966a1b3a5706)

**Comment by joshgoebel** [comment]
Can anything be escaped in single quoted YAML strings?

**Comment by hoehrmann** [comment]
> Can anything be escaped in single quoted YAML strings?

https://yaml.org/spec/1.2.2/#single-quoted-style covers this. The apostrophe can be escaped by doubling it. That's it.
