### ISSUE TITLE
Display doesn't look correct.

### ISSUE THREAD

**Issue by nasrin1748** [highlightjs/highlight.js#4071]
**Describe the issue/behavior that seems buggy**

I am trying to run the example from https://www.eddymens.com/blog/highlightjs-add-line-numbers and when I make the pre tag editable and go to the next line the display doesn't look correct.
<img width="178" alt="9" src="https://github.com/highlightjs/highlight.js/assets/79505893/e22a08e7-e658-4523-9707-be3b08e46b71">

**Sample Code or Instructions to Reproduce**

**Expected behavior**

I should go to the next line number.

**Additional context**

**Comment by joshgoebel** [comment]
Line numbers (and editability) are not features of the core library and thus unsupported here.  I willl leave this open a few days to see if any volunteers might want to try to help out.

**Comment by Dxuian** [comment]
is this issue still open ?

**Comment by nasrin1748** [comment]
Yes, it's still open.

**Comment by joshgoebel** [comment]
Closing now since this has been open a long time with no real progress.
