### ISSUE TITLE
[Request] Manually nest a language within a language

### ISSUE THREAD

**Issue by gqqnbig** [highlightjs/highlight.js#4075]
**Is your request related to a specific problem you're having?**

```
$ ll
total 28K
-rwxrwxr-x 1 vm vm 17K Jul  8 05:26 a.out
-rw-rw-r-- 1 vm vm 647 Jul  8 05:27 program.cpp
$ cat program.cpp
#include &lt;stdio.h>
#include &lt;unistd.h>

int main() {
    pid_t pid = fork();
    return 0;
}
```

I want to highlight this piece of code. Apparently, the whole piece is of language shell session, but the output of cat is in C++.

Thus I write the following markup, but it doesn't work.

```
<pre><code class="language-console">$ ll
total 28K
-rwxrwxr-x 1 vm vm 17K Jul  8 05:26 a.out
-rw-rw-r-- 1 vm vm 647 Jul  8 05:27 program.cpp
$ cat program.cpp
<pre><code class="language-cpp">#include &lt;stdio.h>
#include &lt;unistd.h>

int main() {
    pid_t pid = fork();
    return 0;
}
</code></pre></code></pre>
```

#3439 may be relavent, where joshgoebel confirmed that "The content inside `<pre><code>` should be ONLY text", which explains why my second level pre code does not work.

Do you have any idea how to solve this problem?

**Comment by gqqnbig** [comment]
For references, Latex package Listings  has option escapechar. 

```latex
\begin{lstlisting}[language=c++, escapechar=@]
#include <stdio.h>
#include <unistd.h>

int main() {
    pid_t pid = fork(); //@ \color{Green} $0.99\dot{9}$ is equal to 1.  @
    return 0;
}
\end{lstlisting}

```

The output is like

![texstudio_QMyXKqnqDF](https://github.com/highlightjs/highlight.js/assets/614159/b9cdd73e-5ba6-4608-88d4-716a9975f7b6)

**Comment by joshgoebel** [comment]
No, we're not going to support nested HTML code blocks like this.  We try to keep it simple and support the 90% use cases. If you want to do this you can get almost everything you want (in this simple case) just by removing the nesting and having multiple discrete blocks.

```
<pre><code class="lang-console">...</code></pre> 
<pre><code class="lang-cpp">...</code></pre> 
```
