### ISSUE TITLE
A function that only returns rootNode given some code

### ISSUE THREAD

**Issue by SSbit01** [highlightjs/highlight.js#4076]
I am developing a website that makes extensive use of highlight.js to highlight code blocks. It works flawlessly for that purpose.

However, I am also developing a small code editor for the website, which I want to use highlight.js for real-time syntax highlighting as well. For optimization and good performance, I have studied the repository a little and I have discovered that the `highlight()` function also returns an object called `_emitter`, where another object called `rootNode` is located, which has the following structure:

```javascript
const highlightedMarkdown = hljs.highlight("text node *italic text*", { language: "md" })
console.log(highlightedMarkdown._emitter.rootNode)
```

```javascript
{
    children: [
      "text node",
      { children: ["*italic text*"], scope: "emphasis" }
    ]
}
```

This is perfect for efficiently highlighting code in a code editor instead of replacing the whole output, I wonder if there is a specific function that only returns this `rootNode` instead of a whole object with the HTML output already calculated.

**Comment by joshgoebel** [comment]
> the highlight() function also returns an object called _emitter, where another object called rootNode is located

This is (so far) a stable, yet still private API - and likely to stay that way.  If you pin to a specific version you'll probably be ok, but we don't offer any support for emitter outside of the public API that's used to write custom self-driving grammars.
