### ISSUE TITLE
[Request] seclang support

### ISSUE THREAD

**Issue by emiliocamposmartin** [highlightjs/highlight.js#4077]
Request support fot seclang (modsecurity) language and we would like to see the project support seclang as support bash or others.

Regarding seclang please refer to all those  *.conf files:
https://github.com/coreruleset/coreruleset/tree/main/rules

Thanks!

**Comment by joshgoebel** [comment]
Please read our policy on requesting new languages: https://highlightjs.readthedocs.io/en/latest/language-requests.html
