### ISSUE TITLE
(PHP) Inline php code inside html quotes wrongly highlighted

### ISSUE THREAD

**Issue by samuelgfeller** [highlightjs/highlight.js#4082]
**Issue**
Inline PHP code inside html quotes is highlighted as string and everything that comes after it as well.   
E.g. `<p class="<?= $className ?>">This is not highlighted correctly</p>`

**Which language seems to have the issue?**
PHP

**Are you using `highlight` or `highlightAuto`?**
Highlight, NOT auto.

**Sample Code to Reproduce**
Code: see expected behaviour.

![image](https://github.com/user-attachments/assets/b7f093b7-48eb-4e5b-bac6-050596b35e2e)

**Expected behavior**
```php
<?php
echo 'This text is highlighted';
?>

<p class="<?= $className ?>">
    This text and everything that comes after it is treated as string
    and not highlighted
</p>

<?php
echo 'even this!';
?>
```

**Comment by joshgoebel** [comment]
To highlight a PHP template (mixed PHP & HTML) you'll need to use `php-template` grammar, not `php`.

**Comment by samuelgfeller** [comment]
@joshgoebel thank your quick answer. I'm writing code documentation in markdown which is then converted to html with [parsedown](https://parsedown.org/). 

`php-template` and `phptemplate` don't seem to be valid code block tags in markdown. The IDE doesn't recognize them and the highlight does not work on github. 

What is the reason highlightjs separates php and php-template?   
Is there any valid code block tag for php templates that markdown, github, the IDE and highlightjs understand? 

If not, does `php-tempate` highlight php code exactly the same as `php` grammar? And is there an easy way to create a js addition so that markdown php code block tag is always highlighted in `php-template` grammar? 

Or maybe you have another suggestion on how to fix this issue but I'm really curious as to why highlightjs doesn't go the markdown/github way and combine php and php-templates. Mixed html and php is valid in a vanilla php file.

**Comment by joshgoebel** [comment]
I'm not involved with the parsedown project and can't offer support for that here.  The names I provided are the name of our grammars you'd use them according to the documentation:

```
<pre><code class="language-php-template">
</code></pre>
```

> What is the reason highlightjs separates php and php-template?

Because they aren't the same.

> If not, does php-tempate highlight php code exactly the same as php grammar? 

Not exactly, php-template allows HTML, `<?php` tags, etc... `php` does not.

> And is there an easy way to create a js addition so that the markdown php code block tag is always highlighted as php-template grammar?

Don't think so, you can't just reregister the language since php-tempate references php internally.

> Mixed html and php is valid in a vanilla php file.

Interesting, what would an example look like?

**Comment by samuelgfeller** [comment]
> Because they aren't the same contextually and it makes parsing simpler to have the author specify the context.

I understand that it simplifies parsing for you, but in my opinion, this imposes a high cost on the author. For someone writing documentation in HTML, it might be manageable to determine if there are `<?php` tags and adjust the class name accordingly each time. 

However, for those like me who prefer writing technical documentation in Markdown or similar formats, it becomes nearly impossible because there is no `php-template` tag in standard Markdown. Highlight.js seems to be unique in this approach

> Mixed HTML and PHP is valid in a vanilla PHP file.

What I meant is that if you create a file named `index.php` on a webserver with PHP, both HTML and PHP are valid within the `.php` file extension.

If you think my request makes sense, can you register my issue as feature request? If the highlighting is significantly slower when it has to understand php template and php code for the same `php` tag I'd be happy with a flag in the settings or something. It would make my life so much easier if I didn't have to dig into the parsedown code and change it to go through each line to check if there is a `<?php` or `<?=` somewhere.

**Comment by joshgoebel** [comment]
That's one way to go about it. :)
