### ISSUE TITLE
Language names with non-word characters cannot be detected correctly

### ISSUE THREAD

**Issue by rhanqtl** [highlightjs/highlight.js#4085]
**Describe the issue/behavior that seems buggy**

Commit hash: `9267f5022c14bcd848b8a9024f8c88230fcf7b54`

Current `languageDetectRe` cannot match language names with non-word characters, e.g., `language-c++` and `language-c#`.

**Sample Code or Instructions to Reproduce**

Below element cannot be processed as expected because of being treated as C code:

```html
<pre class="highlight"><code class="language-c++" data-lang="c++">class Example {
 public:
    Example() = default;
};</code></pre>
```

**Expected behavior**

Should match names with non-word characters.

**Comment by rhanqtl** [comment]
Seems that `/\blang(?:uage)?-([\w-]+(?:\+\+)?)(?!\w)/i` is correct.

**Comment by joshgoebel** [comment]
The letters are you wanting to match are simply not valid CSS class names.  If you want something more complex I'd suggest using a custom implementation buit with `data-language`.

**Comment by rhanqtl** [comment]
@joshgoebel But they are possible output of other tools, e.g., the HTML code snippet I posted is generated by AsciiDoctor.

**Comment by joshgoebel** [comment]
> the HTML code snippet I posted is generated by AsciiDoctor.

Consider filing an issue with AsciiDoctor and ask them to stop generating broken class names. :-)

---

You can also simply reconfigure this regex yourself:

https://highlightjs.readthedocs.io/en/latest/api.html#configure

Though if as a result you find there are any strange issues with non-valid CSS class names we can't help you.
