### ISSUE TITLE
(css) Line breaks disappear

### ISSUE THREAD

**Issue by Vanessa219** [highlightjs/highlight.js#4101]
**Describe the issue**
Line breaks disappear

**Which language seems to have the issue?**
css

**Are you using `highlight` or `highlightAuto`?**

`hljs.highlight`

**Sample Code to Reproduce**
```
hljs.highlight(`[\n1`,
          {
            language:"css",
            ignoreIllegals: true
          }
        ).value
```

![QQ_1724903357711](https://github.com/user-attachments/assets/e389ed9b-6b09-481c-b4a1-9475a9c2888c)

**Expected behavior**

Line breaks do not disappear

**Comment by joshgoebel** [comment]
Oh wow, that is one heck of a bug.  That shouldn't even be possible.

**Comment by TCOTC** [comment]
![image](https://github.com/user-attachments/assets/c73970a5-7bd4-4321-b4bc-f73bc2a5e89d)
