### ISSUE TITLE
Update highlight.js from 11.2.0 to 11.3.0,  Minify JS Unexpected token: punc ())

### ISSUE THREAD

**Issue by Julinear** [highlightjs/highlight.js#4108]
**Describe the issue/behavior that seems buggy**
when I update highlight.js version from 11.2.0 to 11.3.0 and  npm run build，there displayed the following error message:

```
[ ERROR ]  Minify JS
           Unexpected token: punc ())

  L31009:  scope: {
  L31010:    1: "keyword",
  L31011:    3: "title.class"
```
here is my dependencies:
```
 "dependencies": {
    "@types/jquery": "^3.3.34",
    "highlight.js": "11.3.0",
    "jquery": "3.6.4"
  },
  "devDependencies": {
    "@stencil/core": "1.8.8",
    "@stencil/sass": "1.0.1",
    "dayjs": "^1.8.14",
    "diff2html": "^2.9.0",
    "rollup-plugin-node-builtins": "^2.1.2",
    "rollup-plugin-node-globals": "^1.4.0",
    "workbox-build": "4.3.1"
  }
```

**Expected behavior**
Is there any solutions?

**Comment by Julinear** [comment]
@isagalaev

**Comment by joshgoebel** [comment]
In what context are you running `npm build` - your own project?  If so, what build system are you using.

**Comment by Julinear** [comment]
Thanks for your notice. I use the @stencil/core, then I upgrade the version of it. It solved.
