### ISSUE TITLE
(PHP) Attributes with \ highlighted as comment instead of meta

### ISSUE THREAD

**Issue by DanielBadura** [highlightjs/highlight.js#4115]
**Describe the issue**
Using Attributes with `\` are hilighted as comments instead of meta. If it's only a leading `\` it is working as expected. But as soons as we add a `\` after that, the highlighting is not correct anymore. This is a common situation when using attributes with PHP for example using Doctrine or Swagger etc. 

**Which language seems to have the issue?**
`php`

**Are you using `highlight` or `highlightAuto`?**

`highlight`

**Sample Code to Reproduce**
```php
use Doctrine\ORM\Mapping as ORM;

#[\ORM\Entity]
final class Account
{
    #[ORM\Id]
    #[ORM\Column('uuid')]
    private AccountId $id;

    #[Column('string')]
    #[\Column('string')]
    private string $name;
}
```

![Bildschirmfoto 2024-09-10 um 11 28 09](https://github.com/user-attachments/assets/864cdf52-621b-460d-beb7-af9931484210)

**Expected behavior**
Same meta highlighting in these cases.

**Additional context**
Using highlight js through https://github.com/rehypejs/rehype-highlight which is using https://github.com/wooorm/lowlight. But i dont think the problem comes from there, since it's also wrong highlighted in the demo.

**Comment by joshgoebel** [comment]
What is the definition of an attribute in PHP, just `#[...]` or are there very precise rules?

**Comment by DanielBadura** [comment]
Yes, Attributes are beginning with `#[` and ending with `]`. They can applied on various things in the language:

- functions (including closures and short closures)
- classes (including anonymous classes), interfaces, traits
- class constants
- class properties
- class methods
- function/method parameters

Also, each attribute may have values associated with it, but doesn't have to, similar to how a constructor of a class works. Also Attributes can be nested.
```php
class Value 
{
}

#[Attribute('value', new Value(), new Attribute()]
function foo() {}
``` 

Here an example how PHPStorm is highlighting it:
<img width="462" alt="Bildschirmfoto 2024-09-21 um 15 13 16" src="https://github.com/user-attachments/assets/48ed4bae-b6fb-4b29-992a-1ac958d2952a">

**Comment by joshgoebel** [comment]
Could you test #4119?

**Comment by joshgoebel** [comment]
Try that fix.

**Comment by DanielBadura** [comment]
Yes this works, thank you! Very much appreciate it!
