### ISSUE TITLE
(diff) Line starting with ++ is considered as comment when added

### ISSUE THREAD

**Issue by jjaffeux** [highlightjs/highlight.js#4123]
Hi, we recently noticed this issue in our diffs:

**Describe the issue**

If you add a line which starts with `++` with the `+` added to note the addition it will become `+++` and be considered as a comment. Same is true for deletion and `--`.

**Which language seems to have the issue?**

diff

**Are you using `highlight` or `highlightAuto`?**

highlight

**Sample Code to Reproduce**

```
hi
+add
++plus
+++doubleplus <-- not highlighted in green
++++tripleplus <-- not highlighted in green
```

```
hi
-subtract
--minus
---doubleminus <-- not highlighted in red
----tripleminus <-- not highlighted in red
```

**Expected behavior**

It correctly highlights the lines in green/red.

I know `+++` and `---` are used as comments in some parts of the diff, but ideally we should be able to differentiate these cases.

Thanks for your help!

**Comment by jjaffeux** [comment]
Yes I agree, that was also my understanding, but having a small experience with highlight I wanted to check.

**Comment by joshgoebel** [comment]
Want to try your hand at writing a custom context aware diff parser in raw JS? :)

**Comment by jjaffeux** [comment]
> Want to try your hand at writing a custom context aware diff parser in raw JS? :)

Not really I mostly wanted to be sure I was not missing something here. If I spend some time contributing to higlight it will most likely be to add liquid support.

**Comment by joshgoebel** [comment]
Closing as #cantfix without a full parser or a much more precise definition of diff (we try to support many variants now).
