### ISSUE TITLE
[Request] char.escape scope support for common languages

### ISSUE THREAD

**Issue by noraj** [highlightjs/highlight.js#4155]
Most languages hljs parser are not implementing `char.escape`.

Here are those who do it:

https://github.com/highlightjs/highlight.js/blob/2bd6ff65635640c99b04cd4217cfe45ca682f884/src/languages/nix.js#L49-L52
https://github.com/highlightjs/highlight.js/blob/2bd6ff65635640c99b04cd4217cfe45ca682f884/src/languages/elixir.js#L75-L79
https://github.com/highlightjs/highlight.js/blob/2bd6ff65635640c99b04cd4217cfe45ca682f884/src/languages/wren.js#L212-L220
https://github.com/highlightjs/highlight.js/blob/2bd6ff65635640c99b04cd4217cfe45ca682f884/src/languages/haskell.js#L198-L201
https://github.com/highlightjs/highlight.js/blob/2bd6ff65635640c99b04cd4217cfe45ca682f884/src/languages/llvm.js#L118-L122
https://github.com/highlightjs/highlight.js/blob/2bd6ff65635640c99b04cd4217cfe45ca682f884/src/languages/nsis.js#L190-L194

but all those are less common or very uncommon languages.

It would be nice to have escape sequence highlight in common languages such as ruby, json, javascript, python, etc.

Example for JSON:

Without:

![image](https://github.com/user-attachments/assets/8b1551b7-cc40-4508-92cb-a34d301229c3)

With:

![image](https://github.com/user-attachments/assets/887c420b-fc8c-40d0-a0e1-27da0f758a06)

**Comment by joshgoebel** [comment]
Would love to see anyone work on this - higher fidelity highlighting is always welcome - esp for simple things like this.  This is technically already covered by #2500 though, so I'm closing this as a duplicate.  If you'd like to contribute any of this work, just pick a grammar and jump in with a PR.
