### ISSUE TITLE
(apache) continuation lines are not recognized

### ISSUE THREAD

**Issue by bmarwell** [highlightjs/highlight.js#4157]
**Describe the issue**

Given this snippet:

```
<IfModule mod_deflate.c>
 AddOutputFilterByType DEFLATE "application/atom+xml" \
 "application/javascript" \
 "text/xml"
</IfModule>
```

The line continuation marks (` \`) are not recogniezed. Everything following the first line ending with a continuation mark will not be highlighted correctly.

**Which language seems to have the issue?**
`apache` aka `apacheconf`

**Are you using `highlight` or `highlightAuto`?**

highlight="apache" in vue (but can reproduce on vanilla highlightjs)

**Sample Code to Reproduce**

See: https://jsfiddle.net/L52ndpkb/

Screenshot:

![Screenshot 2024-11-01 at 11 36 13](https://github.com/user-attachments/assets/7e191cf8-2d43-4613-85c3-79858cda95df)

**Expected behavior**

Same highlighting as without continuation lines:

![Screenshot 2024-11-01 at 11 37 11](https://github.com/user-attachments/assets/e79f13c7-a97f-44da-833b-0757250c0314)

**Additional context**

./.

**Comment by joshgoebel** [comment]
If you can build source you can try my fix.

**Comment by bmarwell** [comment]
Thanks, will try on Monday. Great response! I hope the description was clear and reproducible. I love the idea of including a fiddle link in the issue template, that was very helpful for documenting the reproducer. Great work! 👍🏻

**Comment by bmarwell** [comment]
Hi, I cannot build it myself, but as far as I can tell, the patch looks correct :)
