### ISSUE TITLE
(request org repo) highlightjs-liquid

### ISSUE THREAD

**Issue by laurelthorburn** [highlightjs/highlight.js#4173]
I would like to request the creation of a `highlightjs-liquid` repository for my 3rd party grammar.

- [x] I have an existing personal repository ready to go

### Metadata

- Grammar Name: Liquid
- Link to repo: https://github.com/laurelthorburn/liquid

### Requirements

- [x] I've read the [language Contributor Checklist](https://highlightjs.readthedocs.io/en/latest/language-contribution.html)
- [x] I've read the [Language Contribution Guide](https://github.com/highlightjs/highlight.js/blob/main/extra/3RD_PARTY_QUICK_START.md)
- [x] I'm currently willing to support and maintain this grammar over time
- [x] That repo includes a `dist` folder with CDN-ready `CJS` and `ESM` builds
- [x] That `README.md` includes examples of simple web usage
- [x] That `README.md` includes examples of Node.js usage

### Afterwards

note: assuming i do this after the liquid repo has been created?

Submit a PR that:

- [ ] adds mention of your new language to `CHANGES.md`
- [x] updates `SUPPORTED_LANGUAGES.md` in the main library (https://github.com/highlightjs/highlight.js/pull/4174)

**Comment by joshgoebel** [comment]
>  That repo includes a dist folder with CDN-ready CJS and ESM builds

I'm not seeing the `dist` folder in your repository.

**Comment by laurelthorburn** [comment]
> > That repo includes a dist folder with CDN-ready CJS and ESM builds
> 
> I'm not seeing the `dist` folder in your repository.

It's there on my local, let me see why it didn't push.

**Comment by laurelthorburn** [comment]
> > That repo includes a dist folder with CDN-ready CJS and ESM builds
> 
> I'm not seeing the `dist` folder in your repository.

@joshgoebel Yep, git ignore auto removed `dist`.  Fixed:

https://github.com/laurelthorburn/liquid/tree/main/dist

**Comment by joshgoebel** [comment]
Done. https://github.com/highlightjs/highlightjs-liquid
