### ISSUE TITLE
[Request] On the `contenteditable` issue : I have the code for it.

### ISSUE THREAD

**Issue by denis-migdal** [highlightjs/highlight.js#4176]
**Is your request related to a specific problem you're having?**

Currently, and by design, highlight.js doesn't support highlight of `contenteditable` code.
However, this is still a need as shown by several issues : #3607, #3598, #3583, #3294, #1925.

**The solution you'd prefer / feature you'd like to see added...**

I have a solution below that could be added to highlight.js or to a separate plugin.
Could also be an entry in the FAQ/Documentation, or whatever.

If you really do not want to include it in highlight.js, I can write a plugin.
If so, I may need some help as am really not familiar with  highlight.js internals/plugins.

Still, posting the code here would at least help some people.
The code is written in TS (JS with types annotations). I can remove the type annotations if needed.

**Additional context...**

The solution is very simple, upon each changes :
1. get the caret position ;
2. highlight the code ;
3. restore the caret position.

**Step 0 : listen to the changes**

```ts
type CursorPos = number|null;

export function hl(code: string, language: string): string {
    return hljs.highlight(code, { language }).value;
}

export function initContentEditableCode(target: HTMLElement, language: string) {

    target.setAttribute("spellcheck", "false");
    target.innerHTML = hl(target.textContent!, language);
    
    // listen to changes
    target.addEventListener("input", (ev) => {
        
        const ev_target = ev.target as HTMLElement;

        // get the cursor position
        const cursor_pos = getCursorPos(ev_target);

        // highlight
        ev_target.innerHTML = hl(target.textContent!, language);

        // restore the cursor position
        setCursorPos(ev_target, cursor_pos);
    });

}
```

**Step 1 : get the caret position **

```ts
function getCursorPos(target: HTMLElement): CursorPos {

    if( document.activeElement !== target )
        return null;

    let rrange = window.getSelection()!.getRangeAt(0);

    let path = [];
    let cur  = rrange.startContainer;

    while(cur !== target) {
        path.push(cur); 
        cur = cur.parentNode!;
    }

    let cursor = 0;

    let children = target.childNodes;
    for(let i = path.length-1; i >= 0; --i) {
        for(let j = 0; j < children.length; ++j) {
            if( children[j] === path[i])
                break;
            cursor += children[j].textContent!.length;
        }
        children = path[i].childNodes;
    }

    let offset = rrange.startOffset;

    // https://developer.mozilla.org/en-US/docs/Web/API/Range/startOffset
    if( rrange.startContainer.nodeType === Node.TEXT_NODE)
        cursor += offset;
    else {
        for(let i = 0; i < offset ; ++i)
            cursor += rrange.startContainer.childNodes[i].textContent!.length;
    }

    return cursor;
}
```

**Step 3 : restore the caret position**

```ts
function setCursorPos(target: HTMLElement, cursor: CursorPos) {

    if( cursor === null)
        return;

    let cur: Node = target;

    while(cur.nodeType !== Node.TEXT_NODE) {
        if( cur.childNodes.length === 0)
            break;

        for( let i = 0; i < cur.childNodes.length; ++i ) {
            const clen = cur.childNodes[i].textContent!.length;
            if( cursor <= clen ) {
                cur = cur.childNodes[i];
                break;
            }
            cursor -= clen;
        }
    }
    
    var range = document.createRange();
    var sel = window.getSelection()!;
    range.setStart(cur, cursor);
    range.collapse(true);
    sel.removeAllRanges();
    sel.addRange(range);

}
```

**Bonus : handle tabulations **

```ts

    target.addEventListener("keydown", (ev: KeyboardEvent) => {
        if(ev.code === "Tab") {
            ev.preventDefault();

            // https://stackoverflow.com/questions/2237497/make-the-tab-key-insert-a-tab-character-in-a-contenteditable-div-and-not-blur
            var doc = target.ownerDocument.defaultView!;
            var sel = doc.getSelection()!;
            var range = sel.getRangeAt(0);

            var tabNode = document.createTextNode("\t");
            range.insertNode(tabNode);

            range.setStartAfter(tabNode);
            range.setEndAfter(tabNode); 
            sel.removeAllRanges();
            sel.addRange(range);
        }
    });
```

**Comment by denis-migdal** [comment]
>  no idea how well this would scale;

Personally, I only use it for small codes that can be edited, e.g. :
- for a demo/example in documentations ;
- as an answer input field.

I didn't test it on larger code (and do not aim to do so).

> Also, there are MUCH better solutions for live editing, such as [CodeMirror](https://codemirror.net/), etc. that already support such functionality.

For my needs, highlight.js is more appropriate as I do not need some killer features, but need to easily tweak the result.
I have a kind of system that "injects" some text that need to be framed, but not syntax highlighted.

> _I'm assuming you intend to package it up more nicely though, is that correct?_ I'm not sure we'd just want a wiki entry with all these separate pieces code for end users to try and glue together on their own.

I can make github repo with a non-minimized ES6 JS file, that'd expose a wrapper, and some functions, as well as write some documentation, with a demo.
I do not know when I'd do it though.

A little question:
```html
<pre><code class="language-html">...</code></pre>
```

Is the `pre` really necessary ?
Indeed, we can simulate it with :
```css
white-space: pre;
font-family: monospace;
```

**Comment by joshgoebel** [comment]
> Is the pre really necessary ?

Suppose that would depend on your definition of necessary.  But if you read the docs you can see that we support matching anything you'd prefer, not just pre code... (though then you'd possibly need to edit the theme, etc)

Also funny that we get a mention in the ChatGPT answer as to one reason this is still useful in 2024.

From ChatGPT:

---

The use of `<pre><code>` to wrap code blocks in HTML has traditionally been recommended for several reasons related to semantics, formatting, and accessibility. Here's a detailed explanation:

---

### **Why `<pre><code>` Has Been Used Traditionally**

1. **Semantics:**
   - The `<code>` tag alone indicates that the content is a snippet of code, but it does not inherently handle whitespace preservation or formatting.
   - The `<pre>` tag, short for "preformatted text," ensures that whitespace (including spaces, tabs, and line breaks) is preserved, which is critical for code readability and accuracy.

2. **Whitespace Preservation:**
   - Programming languages and structured text often rely on precise spacing. Using `<pre>` ensures the formatting of the code block is displayed exactly as written, without collapsing spaces or ignoring newlines (which happens with most HTML elements).

3. **Accessibility:**
   - Combining `<pre>` with `<code>` provides a clear semantic and visual cue for screen readers, making it easier for assistive technologies to convey that the content is both preformatted and code.

4. **Styling and Consistency:**
   - The `<pre>` element naturally displays text in a monospaced font, aligning with the expectations of how code should appear. Although CSS can achieve this on its own, `<pre>` provides this behavior without additional styles.

5. **Browser Compatibility:**
   - For decades, wrapping `<code>` in `<pre>` ensured consistent rendering of code blocks across browsers without needing complex CSS rules.

---

### **Is This Still Recommended in 2024?**

Yes, in most cases, using `<pre><code>` together is still the best practice for displaying code blocks. Here's why:

#### **Advantages That Still Apply:**
1. **Semantics and Accessibility:**
   - While ARIA roles (like `role="code"`) and better CSS handling have improved code block accessibility, `<pre><code>` still offers the most natural semantic structure.

2. **Whitespace Handling:**
   - Although you can mimic `<pre>` behavior with `white-space: pre;` in CSS, `<pre>` remains the simplest and most effective way to ensure proper formatting for whitespace-sensitive content.

3. **Fallbacks and Robustness:**
   - `<pre><code>` works well even in environments with minimal or no CSS support (e.g., text-only browsers or email clients).

4. **Tool Compatibility:**
   - Many code highlighting libraries (e.g., Prism.js, Highlight.js) and markdown-to-HTML converters rely on `<pre><code>` as the standard structure for code blocks.

#### **Potential Alternatives in 2024:**
- **CSS-Only Approaches:**
  - If you want to use just `<code>` and achieve preformatted text using CSS (`white-space: pre; font-family: monospace;`), it's possible. However, this requires more effort and can lead to inconsistencies in environments without CSS.

- **Custom Components:**
  - Frameworks like React or Vue often encourage custom components for code blocks, but these typically output `<pre><code>` under the hood to align with HTML standards.

---

### **Conclusion:**
While modern CSS allows more flexibility, `<pre><code>` remains the gold standard for:
- Preserving code formatting.
- Ensuring semantic clarity.
- Maintaining broad compatibility with tools and accessibility standards.

In 2024, it’s still recommended for code blocks unless you have a very specific reason to use a CSS-only solution.

**Comment by joshgoebel** [comment]
> I can make github repo with a non-minimized ES6 JS file, that'd expose a wrapper, and some functions, as well as write some documentation, with a demo.

Cool beans.

**Comment by denis-migdal** [comment]
I started to create the github repo:
https://github.com/denis-migdal/hljs_editable

You can test it here :
https://denis-migdal.github.io/hljs_editable/demo

This is still quite a dirty draft.

I still need to port some features I have:
- undo/redo.
- trim of the source code, i.e. removing the indentation due to the `<code>` indentation as well as removing the first and last lines.
- use of `<script>` to properly escape HTML code.

It may take me long time before going back to it, it depends how I progress in other works.

**Comment by joshgoebel** [comment]
Good luck.
