### ISSUE TITLE
[Request] Sync diff highlight behavior with vim

### ISSUE THREAD

**Issue by RocketMaDev** [highlightjs/highlight.js#4177]
I'm working on some binary diff patches, and the "line" should be a hex value instead of just a dec value. In vim, it just highlight the whole line starts and ends with `@@`, so it works perfectly.

<img width="459" alt="Snipaste_2024-11-28_00-42-08" src="https://github.com/user-attachments/assets/a47cd3cc-a158-45a1-a675-a370537df480">

However, highlight.js limits values between `@@` to be dec values, so in my blog, the line tag falls back from `meta` to `line` and loses highlight.

<img width="408" alt="Snipaste_2024-11-28_00-45-50" src="https://github.com/user-attachments/assets/486d97ac-bb32-41fb-ba6a-16ef1796b79a">

This request may not be entirely reasonable, but I still would like to pull a request to mod `\d` to `\w` to match these customized meta lines like in vim. Would you be open to this change? If so, I’ll submit the PR as soon as I can.

**Comment by joshgoebel** [comment]
I think `\w` is a bit too broad, but a patch that added a 4th variant to the either that did something like:

`[\dA-Fa-f]`

... could be nice here.  Thoughts?

**Comment by RocketMaDev** [comment]
Though matching hex digits may be more reasonable, Vim just matches `\S`...

**Comment by joshgoebel** [comment]
We aim for precision, esp when precision is so easy to have (as in this case).  You interested in working on this one?

**Comment by RocketMaDev** [comment]
I see. What about `(0[xX])?[\da-fA-F]+`? Some users may prepend a "0x" prefix.

**Comment by joshgoebel** [comment]
> Some users may prepend a "0x" prefix.

Some users?  

The goal is to support various software generated diff formats here - that's what I am assuming you are showing me... Do we know of some specific software that would generate hex numbers with leading `0x`?  If not we shouldn't get ahead of ourselves.

**Comment by RocketMaDev** [comment]
I'm sorry that I didn't explain my thought. There is no well-known software uses this format. I want to make this patch because I would like to develop a project to patch ELF with GNU diff-like format. Generally, code address is displayed in hex instead of dec, so I "modded" diff format so that code address could be inputted easily.

That's why I said it's not so reasonable as this is my modded format and is just used in my own project...

**Comment by joshgoebel** [comment]
Ah, if this is just for personal use then I'd just create a custom grammar that does what you need.

**Comment by RocketMaDev** [comment]
@joshgoebel in that case, may I create a PR adding a 3rd party language "binpatch"?

**Comment by joshgoebel** [comment]
Well, we don't add new grammars to the core library (see our 3rd party dev docs), but often we'll link to them from SUPPORTED_LANGUAGES.... but...

> There is no well-known software uses this format.

How obscure are we talking, do you have any links to tools, etc?  I'm not sure it would need to be well-known, but if it's not really known at all then it wouldn't be of much use to anyone at all I'd think.

**Comment by RocketMaDev** [comment]
I see. Then when I finished developing the tool, I'll follow 3rd party guideline and create a repo.

**Comment by RocketMaDev** [comment]
Anyway, since I shouldn't update diff.js, let's leave this issue aside. I'll open another issue when ready.
