### ISSUE TITLE
How to appropriately include license for CSS files

### ISSUE THREAD

**Issue by createyourpersonalaccount** [highlightjs/highlight.js#4189]
Hello,

I use highlight.js with node to highlight source code blocks in my blog on the backend. The only file I need to serve users is the css theme. What is the license of the theme?

For example, if I use atom-one-light.css, I see the following notice (not available in the min file):

```
Atom One Light by Daniel Gamage
Original One Light Syntax theme from https://github.com/atom/one-light-syntax
```

So, what is the license? Is it BSD-3 because that's what highlight.js comes with? Is it whatever Daniel Gamage had? If you can help me understand this issue I would appreciate it.

**Comment by joshgoebel** [comment]
I'm no license expert but my thinking would be that when anything is merged/committed to the project that it would come under our licensing.  I'd be happy to make that explicit also if needed - all our themes should be open for any use, personal, professional, etc... 

Now the Base64 themes could be different since we just pulled those from an entirely different project.  Though to be fair the original Base16 project was MIT: https://github.com/chriskempson/base16

I probably wouldn't worry unless your a big huge corporation and wanted to reach out to the original author just to get their blessing.

**Comment by joshgoebel** [comment]
Does that help?

**Comment by createyourpersonalaccount** [comment]
@joshgoebel Thanks for the response. For example here's what Base16 license has (MIT):

> The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

You could include the entire license text in the CSS file in a comment (together with the attribution line "Copyright (C) 2012 Chris Kempson") but obviously that bloats the serving of the file. Other options are either only including it in the non-min CSS file or having it entirely detached in a LICENSES/ directory that explains which license corresponds to which files.

What I think is the case is that including only your license is not appropriate. In fact in my case, because I'm serving the CSS file, I do not need to include your license at all, AFAIK the output of highlight.js is not licensed under your license, so I do not need to include your license in my served HTML files. I would however need to include the license of the CSS file.

I could be wrong about this. My blog is on a repo on GitHub, so I know that I need to include the appropriate licenses for everything. If I only served files over an HTTP server, then I'd have to include licenses embedded in the served files. If you look at what Google does in its index page, it has small copyright notices for every served JS code, things like:

```js
/*
 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
```

I think that's what needs to be done here even for the minified files: an indication of the copyright owner and the license type.

**Comment by joshgoebel** [comment]
Base16 themes already include a notice:

`License: ~ MIT (or more permissive) [via base16-schemes-source]`

I'll think we'll go ahead and add our standard header to all the CSS files, just like we already do the main built JS file. Modified slightly to include a license URL, which does make sense:

```
/*!
  Highlight.js v11.11.1 (git: 08cb242e7d)
  (c) 2006-2024 Josh Goebel <hello@joshgoebel.com> and other contributors
  License: https://github.com/highlightjs/highlight.js/blob/main/LICENSE (BSD-3-Clause)
 */
```

**Comment by createyourpersonalaccount** [comment]
Great, thank you. That is a good idea.

**Comment by createyourpersonalaccount** [comment]
Oh, but in my opinion you should not include version information in the license comment.

**Comment by joshgoebel** [comment]
What is the harm?

**Comment by createyourpersonalaccount** [comment]
There is no harm if you don't plan to update it, but there is a misconception that you have to update copyright/license statements, such as (c) 2020-2024 (which in 2025 you'd update to 2020-2025), which is unnecessary and would only cause confusion. 

You can see this answer <https://stackoverflow.com/questions/2390230/do-copyright-dates-need-to-be-updated/2391555#2391555>. See also the [Berne convention](https://en.wikipedia.org/wiki/Berne_Convention and [Common law copyright](https://en.wikipedia.org/wiki/Common_law_copyright).

A claim like (c) 2006-2024 means that you don't make a claim for 2005, and it complicates slightly what happens when 2025 comes. The easier approach is to just have (c) 2006, relying on the Berne convention to cover you for the later years, and hopefully 2006 is the year where the file appeared in the repository.

So for example, if you include the version information, does it mean only that version is copyrighted/licensed? Less is more when it comes to copyright and licensing claims.
