### ISSUE TITLE
(CSS) Multiple line breaks

### ISSUE THREAD

**Issue by Vanessa219** [highlightjs/highlight.js#4192]
**Describe the issue**
When has `[`, an extra line break will be added.

**Which language seems to have the issue?**
CSS

**Are you using `highlight` or `highlightAuto`?**
`highlight`

**Sample Code to Reproduce**

https://github.com/siyuan-note/siyuan/issues/12357#issuecomment-2561961591

```cs
hljs.highlight("[",
  {
    language: "css",
    ignoreIllegals: true
  }
).value;

// output: '<span class="hljs-selector-attr">[\n</span>'
```

**Expected behavior**
output: `'<span class="hljs-selector-attr">[</span>'`

**Additional context**
Highlight.js v11.11.1 (git: 08cb242e7d)

**Comment by joshgoebel** [comment]
Try 62f8a60 if you can.

**Comment by Vanessa219** [comment]
Thanks, it works.
