### ISSUE TITLE
Add AMD module definition support

### ISSUE THREAD

**Issue by ghost** [highlightjs/highlight.js#42]
Highlight.js rocks. It's the best of its kind!

Could you add an AMD module definition? This would make Highlight.js compatible with all AMD loaders out there.

Here is some info: http://requirejs.org/docs/whyamd.html#dolib

**Comment by jakelodwick** [comment]
Highlight works great with RequireJS. I just threw it into a `shim` in my `require.config` call:

![image](https://cloud.githubusercontent.com/assets/25925/10628337/3932f666-7792-11e5-914a-d9784f080bc3.png)

(language is CoffeeScript)

Thanks, @isagalaev!

**Comment by AminHuang** [comment]
Why I cannot use require.js well?


    var hljs = require("//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.0.0/highlight.min.js");
    hljs.initHighlightingOnLoad();


What is wrong? I got this:
![image](https://cloud.githubusercontent.com/assets/6110040/11715132/75b72b10-9f7a-11e5-8b80-733e33004ae0.png)

**Comment by sourrust** [comment]
@AminHuang The link to the error documentation helps but you can do this:

```html
<script src="//cdnjs.cloudflare.com/ajax/libs/require.js/2.1.22/require.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.0.0/highlight.min.js"></script>
<script>
require(['hljs'], function(hljs) {
  hljs.initHighlighting();
})
</script>
```
