### ISSUE TITLE
Async highlighting

### ISSUE THREAD

**Issue by rayshan** [highlightjs/highlight.js#448]
Hi, is there a way to know when highlighting is finished? Would be awesome to have ability to take a callback, so it'll work nicely with something like `marked` markdown parser: 
https://github.com/chjj/marked

**Comment by 3nuc** [comment]
```html
<script async src="//cdn.jsdelivr.net/gh/highlightjs/cdn-release@11.0.0-beta1/build/highlight.min.js"></script>
<script>window.addEventListener('load', () => hljs.highlightAll());</script>
```

**Comment by joshgoebel** [comment]
This just loads the library async, that has nothing to do with the topic of this thread.
