### ISSUE TITLE
highlight as diff and language

### ISSUE THREAD

**Issue by choxi** [highlightjs/highlight.js#480]
Is there a way to get highlight.js to highlight both the language and as a diff? For example, I'd like to do:

``` javascript
var hello = function() {
-  "hello";
+  return "hello";
}
```

The ideal end result would highlight the Javascript keywords, but also highlight the lines. Here's an example from [the Meteor book](https://www.discovermeteor.com/):

![Example](http://i.imgur.com/pEZ64GM.png)

**Comment by mb21** [comment]
Starlight [can do this](https://expressive-code.com/key-features/text-markers/#combining-syntax-highlighting-with-diff-like-syntax). Seems they're using [expressive-code](https://github.com/expressive-code/expressive-code) under the hood.
