### ISSUE TITLE
React JSX support?

### ISSUE THREAD

**Issue by gre** [highlightjs/highlight.js#494]
Hi,

Is there any way to highlight (and detect) JavaScript code using the React JSX syntax? It would be awesome.

Best regards,
gre

**Comment by rstacruz** [comment]
The problem with E4X (and hence, JSX) support in hl.js is that in requires your tag to end in `>;`:

https://github.com/isagalaev/highlight.js/pull/123/files#diff-223ea81c103e681d4def42a5047c8becR34

```js
var compo = React.render(<Component />, mountnode); /* not ok */

/* ok */
render: function () {
  return <div>Hello {this.props.name}</div>;
}
```

**Comment by jbe456** [comment]
I still have the issue with the latest version:

![jsx](https://cloud.githubusercontent.com/assets/4415696/12131978/4ceed780-b3e5-11e5-8162-60ed5cfe523e.png)

You can see from the screenshot and the HTML below that the XML span incorrectly covers the rest of the code.

```html
<code class="hljs javascript"><span class="hljs-keyword">var</span> HelloWorld = React.createClass({
  render: <span class="hljs-function"><span class="hljs-keyword">function</span><span class="hljs-params">()</span> </span>{
    <span class="hljs-keyword">return</span> (
      <span class="xml"><span class="hljs-tag">&lt;<span class="hljs-title">p</span>&gt;</span>
        Hello, <span class="hljs-tag">&lt;<span class="hljs-title">input</span> <span class="hljs-attribute">type</span>=<span class="hljs-value">"text"</span> <span class="hljs-attribute">placeholder</span>=<span class="hljs-value">"Your name here"</span> /&gt;</span>!
        It is {this.props.date.toTimeString()}
      <span class="hljs-tag">&lt;/<span class="hljs-title">p</span>&gt;</span>
    );
  }
});

setInterval(function() {
  ReactDOM.render(
    <span class="hljs-tag">&lt;<span class="hljs-title">HelloWorld</span> <span class="hljs-attribute">date</span>=<span class="hljs-value">{new</span> <span class="hljs-attribute">Date</span>()} /&gt;</span>,
    document.getElementById('example')
  );
}, 500);</span></code>
```

Any plan on fixing it?

**Comment by isagalaev** [comment]
@jbe456 yeah, it wasn't fixed. We have a separate issue on that — #839. It turned out to be a real inconvenience for our current parser.

**Comment by MartinHaeusler** [comment]
+1, Typescript (*.tsx) Support would be even better.

**Comment by namestise** [comment]
Why this issue being closed? JSX is rendered very ugly
![screen shot 2017-03-15 at 3 26 03 pm](https://cloud.githubusercontent.com/assets/20994365/23939556/d284026c-0993-11e7-94a3-d12f541f900d.jpg)

**Comment by hundsim** [comment]
Any updates on this?

**Comment by egor-rogov** [comment]
Does anyone have an idea how to fix it? Pull requests are welcome.

**Comment by bexuma** [comment]
@egor-rogov, consider switching to Prism.js, they do support jsx language highlight.

**Comment by yourWaifu** [comment]
I found this thread on a Google search, but you should go here instead: https://github.com/highlightjs/highlight.js/issues/2998

**Comment by LeakedDave** [comment]
Prism is laggy.. why won't this work :/

**Comment by gentlee** [comment]
Found solution - registering `xml` highlights JSX for javascript and typescript.

```
import xml from 'highlight.js/lib/languages/xml'

hljs.registerLanguage('xml', xml)
```
