### ISSUE TITLE
Java underscores in literals

### ISSUE THREAD

**Issue by martinvw** [highlightjs/highlight.js#509]
Since Java 7 we are allowed to have an underscore as a seperator in a numerical literal, see: http://docs.oracle.com/javase/7/docs/technotes/guides/language/underscores-literals.html

So this is completely valid but not yet supported by highlight.js. A first glance the code does not yet allow me to supply you with a patch. But I suppose at should not be too difficult.

long creditCardNumber = 1234_5678_1234_5678L;
long oneMilion = 1_000_000L;

**Comment by yihangho** [comment]
The implementation of this is causing some problem when accessing members that begin with an underscore. For example, `Contacts._ID`:

![screen shot 2015-05-19 at 6 31 02 pm](https://cloud.githubusercontent.com/assets/4226956/7700952/46f31314-fe55-11e4-9029-cfb33451d905.png)

as opposed to the correct highlighting:

![screen shot 2015-05-19 at 6 31 58 pm](https://cloud.githubusercontent.com/assets/4226956/7700969/675f8cae-fe55-11e4-9ad2-c21caeb94f1b.png)

**Comment by Sannis** [comment]
I've created issue about this.
