### ISSUE TITLE
Unable to clone the repository due to: error: object c15765f108a2799a540bf4fd7bd9aa85542a8720:invalid author/committer line - missing space before email

### ISSUE THREAD

**Issue by jan-matejka** [highlightjs/highlight.js#590]
Unable to clone the repository due to:
error: object c15765f108a2799a540bf4fd7bd9aa85542a8720:invalid author/committer line - missing space before email

**Comment by yaccz** [comment]
Actually I found out it's caused by setting transfer.fsckObjects = true on client. Just gotta turn it off for repositories with broken history.

**Comment by isagalaev** [comment]
Thanks for revisiting that!
