### ISSUE TITLE
Add support for PowerShell.

### ISSUE THREAD

**Issue by basbossink** [highlightjs/highlight.js#672]
Highlight.js supports a very large number of languages which is great. I would really be ecstatic if support for [Windows PowerShell](http://en.wikipedia.org/wiki/Windows_PowerShell) would be added. For more information about [PowerShell](http://technet.microsoft.com/en-US/scriptcenter/dd742419.aspx) have a look [here](http://technet.microsoft.com/en-US/scriptcenter/dd742419.aspx).

**Comment by riQQ** [comment]
PowerShell support was added with  #588 / 480946018e99435be288e345be9beb23ad52d0fa.
