### ISSUE TITLE
contains 'self' is ambiguous with `variants`

### ISSUE THREAD

**Issue by WolfgangKluge** [highlightjs/highlight.js#826]
I have a minor issue with http://highlightjs.readthedocs.org/en/latest/reference.html#variants in combination with `self`. Here's an example language

``` javascript
  return {
    contains: [
      {
        className: 'test',
        variants: [
          {
            begin: '<',
            end: '>'
          },
          {
            begin: '\\{',
            end: '\\}'
          }
        ],
        contains: [
          'self'
        ]
      }
    ]
  };
```

This would match nested pairs of `<<>>` as well as `{{}}` - but not the inner part of a mixed form like `<{}>`. It seems like `self` refers to specific mode variant.

Sure, I can write two different modes to get this done where every mode contains the respectively  other modes plus `self`.
But I think it would be much more simply to have it "_full recursive_". Or at least the docs should be more specific at this point.

To get it work, the example language has to be defined this way

``` javascript
  var test1 = {
    className: 'test',
    begin: '<',
    end: '>',
    contains: []
  };
  var test2 = {
    className: 'test',
    begin: '\\{',
    end: '\\}',
    contains: []
  };

  test2.contains.push(test1, 'self');
  test1.contains.push(test2, 'self');

  return {
    contains: [
      test1,
      test2
    ]
  };
```

Wolfgang

**Comment by isagalaev** [comment]
I tried to look at it a while ago and couldn't come up with anything sensible… Gotta think some more.

**Comment by yyyc514** [comment]
@isagalaev Do you recall if there was some issue why this couldn’t or shouldn’t just be expanded to contain both?  I’m not sure it’d be easy, but seems like it’d just involve changing the behavior of `expand_mode`, no?

**Comment by isagalaev** [comment]
@yyyc514 here's the problem. When you come onto a mode with `variants`, expanding it produces two independent modes like these:

    [ { ..., contains: ['self']}, { ..., contains: ['self']} ]

And by the time the recursive process in `compileMode` gets to those `contains`, each `'self'` can only refer to one concrete variant of the original mode. I don't know how to fix it. If you teach `expand_mode` how to deal with `'self'` in `contains`, it would mean making it recursive? Inside of the already recursive `compileMode`?

All in all, it's not something I can actually help with, sorry!

**Comment by yyyc514** [comment]
Ah, whatever you said just now gave me the kick my brain needed.  The problem here is that each variant expands into a mode of it's own and at that point "self" becomes ambiguous.

@WolfgangKluge Do you have an actual real-world use cause inside a language or is still truly your actual use case, matching up brackets?

**Comment by yyyc514** [comment]
> To get it work, the example language has to be defined this way

@WolfgangKluge If you were doing this often or commonly though you'd wrap that up in a nice little helper, so it really wouldn't be as bad as you're making it out.  I tagged this docs as it wouldn't hurt to explain this behavior somewhere as you suggested.
